### ISSUE TITLE
Add assertions in access functions on C level

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#100]
We just debugged an instance of C code trying to run ElmPRec on an atomic record, which went horribly wrong.

Ideally we add assertions of types in all accessor functions to make (HPC-)GAP crash rather than trying to read or write bogus data.

**Comment by stevelinton** [comment]
We need to make sure that the ones of key code paths (like ELM_PLIST) ARE turned off in a standard build, or we'll take a big performance hit.

**Comment by ChrisJefferson** [comment]
We should probably (by default) aim to turn them all off in standard build, to make people more confident they can add them where they like.

From my past experience, the safest thing would be to just invent a new function `gap_assert`?, rather than trying to make sure that `assert` gets turn on and off at the right time.

**Comment by fingolfin** [comment]
I never noticed this issue before, but @markuspf comment on #295 pointed me to it....

So I guess this is (indirectly) a request for a `--enable-debug` flag on `configure`, right? Adding that should be no problem. What should it do? For one thing, it could set a `#define DEBUG_MODE`, for further changes in the code. Do you also want other things done? E.g. we could disable optimization in that case.

**Comment by markuspf** [comment]
I think that having `--enable-debug` and putting assertions in the form of @ChrisJefferson suggested `gap_assert` around generously would be quite helpful for `GAP` and `HPC-GAP`. Disabling optimisation and adding `-g` options to the compiler (if it is not already) are other immediate things that come to mind.
Also we should probably think about displaying in the banner when GAP was build with the debug flag in case one is wondering why the current `GAP` is so slow in benchmarks (I know I will wonder about that at least once).

**Comment by fingolfin** [comment]
This has been done now -- of course it is still work in progress, but I think we can safely close this issue. Feel free to reopen if you disagree.
