### ISSUE TITLE
Wrong result computing PreImagesRepresentative

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1006]
The following is taken from http://tracker.gap-system.org/issues/391, was reported there by @laurentbartholdi and attributed to Van Lyuen Le:
```
gap> D := DihedralGroup(40);;
gap> g := SemidirectProduct(AutomorphismGroup(D),D);;
gap> f := GroupHomomorphismByImages(g,g,List(GeneratorsOfGroup(g),x->(x^Projection(g))^Embedding(g,1)));
[ f1, f2, f3, f4, f5, f6, f7, f8, f9, f10 ] -> [ f1, f2, f3, f4, f5, f6, <identity> of ..., <identity> of ..., <identity> of ..., <identity> of ... ]
gap> g.1*g.7 in Image(f);
false
gap> PreImagesRepresentative(f,g.1*g.7);
f1
gap> PreImagesRepresentative(f,g.1*g.7)^f = g.1*g.7;
false
```

**Comment by hulpke** [comment]
This seems to be the same issue as 1005 -- the method for PreImagesRepresentative does not test for membership. But for me this actually gives an error now. Maybe not the nicest one (indeed a check seems to be in the wrong place), but an error nevertheless.

**Comment by fingolfin** [comment]
Note sure what you mean with "it gives an error now" -- I get the exact output I pasted above with master. The big difference to #1005 in my eyes is that there, an error is shown which is not helpful -- annoying, but nothing more. Here, a mathematically incorrect answer is given, which I consider much more serious, as it could even lead to incorrect research findings.

**Comment by fingolfin** [comment]
Ahh, I see now, you added a commit to #968 which turns this into an error. If that's the case, then yes, this issue becomes a dupe of #1005 :-)

**Comment by fingolfin** [comment]
This has been resolved by @hulpke
