### ISSUE TITLE
When using Read(), ctrl-C sometimes does not work

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1010]
Using master, I was using `Read()` to execute a file with essentially a big for loop in it, computing and printing lots of stuff.

I then tried to abort the execution using Ctrl-C. But this only resulted in GAP printing the message
```
^CNoticed user interrupt, but you are back in main loop anyway.
```
Clearly that was incorrect.

In the end, I had to rapidly press ctrl-c multiple times, until GAP finally noticed two of them in a way that lead to the `gap: you hit '<ctr>-C' twice in a second, goodbye.` message. But again, it wasn't enough to just hit it twice; I really hit the combo a dozen times or so, as fast as I could, else it wouldn't notice it.

**Comment by markuspf** [comment]
Any chance I could get that file for testing?

I assume you're running on MacOS, not sure whether signal handling on MacOS is very different from linux or BSDs.

**Comment by fingolfin** [comment]
Without a test case to reproduce this, this issue is worthless. Closing for now
