### ISSUE TITLE
Triple quoted strings don't do any escaping.

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#1013]
When using triple quoted strings like so

```
gap> """\0xff""";
"\\0xff"
```
as opposed to
```
gap> "\0xff";
"\377"
```

This is "documented" at the top of the triple string parsing function, I just wonder whether it's desirable or not before I start hacking up the function.

**Comment by fingolfin** [comment]
I think that's desirable, and is what e.g. Python does.

The idea is that basically, you can copy & paste any text into triple strings, without worrying about escaping backslashes and double quotes and stuff.

**Comment by markuspf** [comment]
I agree. I can get my escapes essentially by using `ReplacedString", though I might provide a function that does all escapes that are documented for GAP.

**Comment by fingolfin** [comment]
So, can we close this now?

**Comment by markuspf** [comment]
Yup.
