### ISSUE TITLE
Search for help topics matching SetSomething and HasSomething

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1019]
The following idea had been suggested by @frankluebeck in the old Redmine based issue tracker (http://tracker.gap-system.org/issues/304).

It should be possible to improve the search in the help system in a way that, for example, the search for system setters and testers such as `?SetIsMapping` and `?HasIsMapping` will return corresponding attributes and properties. e.g. `IsMapping` (currently the search for `?SetIsMapping` will report that it is currently undocumented, despite the fact that `IsMapping` is documented).

**Comment by stevelinton** [comment]
This seems like a good idea. The only real question I can see is how to keep a reasonably clean interface with the help system.  Maybe the help system could have a system of pluggable filters that could transform the search string.

**Comment by fingolfin** [comment]
@alex-konovalov Actually, that old item was created by you and not by @frankluebeck :-).

Another way to approach this would be to modify GAPDoc to emit additional index entries: Whenever an attribute or property `IsFOO` is documented, then also emit index entries for `HasIsFOO` and `SetIsFOO`. Of course those don't need to be visible in the HTML index.

**Comment by alex-konovalov** [comment]
@fingolfin you're right, it was my idea :-). Thanks for reminding - now I know how to do this. 

I've implemented some time ago a feature which ensures that the search for e.g. `Normaliser` will also search for `Normalizer` even if the synonym is not defined (see `TRANSATL` global variable in `lib/helpbase.gi`). 

In the same way I can modify the search in a way that the search for `HasSomething` and `SetSomething` will also search for `Something`.

I think that adding additional index entries is not a way to go - with this, `H` and `S` sections of the index in HTML and PDF will just explode. I suspect that suppressing them in the index will be too tedious, if possible at all.

**Comment by fingolfin** [comment]
Resolvde by 86321d90dedca9eaba5c082c085e13963bc9cd6d
