### ISSUE TITLE
GAP4stones in tst files, unify them?

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#1021]
Where can one find the documentation for GAP4stones? I sort of figured (by running ````make teststandard````) that these are supposed to somehow give an indication on how long a test will run. 
However, I cannot find anywhere this documented in a proper way. Nor do I see that the numbers in the tst files are anything more than ad-hoc. I certainly have no idea what numbers to put into tst files, I just copied over the number from another file. 

Maybe at some point it would be nice to have these numbers align with each other, and also to document the meaning of these numbers.

**Comment by alex-konovalov** [comment]
@hungaborhorvath numbers are periodically renormalised (cf #666), so don't worry too much about placing arbitrary number. I don't mind if GAP4stones will disappear at all, but taking them out is not in my priority list.

**Comment by james-d-mitchell** [comment]
@hungaborhorvath and @alex-konovalov just to mention that this is related to Issue #446. I too wouldn't mind if GAP4stones disappeared.

**Comment by ChrisJefferson** [comment]
My personal preference would be to kill GAP4stones.. they don't really mean anything, and they mean even less now we are frequently extending the testsuite (as they are based on how long the tests take to run).

**Comment by Stefan-Kohl** [comment]
Yes, indeed. -- Of course for compatibility,  STOP_TEST should then just ignore the second argument if it is given (and not throw an error).

**Comment by alex-konovalov** [comment]
GAP4stones were removed in https://github.com/gap-system/gap/pull/1072.
