### ISSUE TITLE
Error, CVEC_INTREP_TO_CVEC: no cvec

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#1022]
Affects current master. This also gives a diff in ````bugfix.tst:2982```` for which the comment says ````# 2012/06/18 (FL)````
````
 ┌───────┐   GAP v4.8.6-971-g66b4b1e of 2016-12-15 11:23:53 (CET)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 3.0, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.1, AutPGrp 1.6, 
             Browse 1.8.6, CRISP 1.4.4, Cryst 4.1.12, CrystCat 1.1.6, 
             CTblLib 1.2.2, FactInt 1.5.3, FGA 1.3.1, GAPDoc 1.5.1, IO 4.4.6, 
             IRREDSOL 1.3.1, LAGUNA 3.7.0, Polenta 1.3.7, Polycyclic 2.11, 
             RadiRoot 2.7, ResClasses 4.5.0, Sophus 1.23, SpinSym 1.5, 
             TomLib 1.2.6, Utils 0.43
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> if LoadPackage("cvec",false) <> fail then mat := [[Z(2)]];
> ConvertToMatrixRep(mat,2); cmat := CMat(mat); cmat := cmat^1000; fi;
Error, CVEC_INTREP_TO_CVEC: no cvec in
  CVEC_INTREP_TO_CVEC( l, v 
 ); at /home/ghorvath/work/gap/pkg/cvec-2.5.6/gap/cvec.gi:833 called from 
CVec( v, c 
 ) at /home/ghorvath/work/gap/pkg/cvec-2.5.6/gap/cmat.gi:153 called from
<function "unknown">( <arguments> )
 called from read-eval loop at *stdin*:2
    try 'return;' (which will not work here!)
brk> 
````
Result is the same with or without packages loaded.

**Comment by fingolfin** [comment]
This suggest a problem in or with the `cvec` package. My first thought is: Did you compile cvec? This looks as if an older cvec kernel extensions is sitting around somewhere, and is combined with the most recent cvec...

In any case, I cannot reproduce it...

**Comment by hungaborhorvath** [comment]
I just used ````Buildpackages.sh```` on the stable gap yesterday (with no errors for this particular package), and I have a symlink to these packages for the development version of gap.

Also, I can load the package.....
````
 ┌───────┐   GAP v4.8.6-971-g66b4b1e of 2016-12-15 11:27:02 (CET)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 3.0, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.1, AutPGrp 1.6, 
             Browse 1.8.6, CRISP 1.4.4, Cryst 4.1.12, CrystCat 1.1.6, 
             CTblLib 1.2.2, FactInt 1.5.3, FGA 1.3.1, GAPDoc 1.5.1, IO 4.4.6, 
             IRREDSOL 1.3.1, LAGUNA 3.7.0, Polenta 1.3.7, Polycyclic 2.11, 
             RadiRoot 2.7, ResClasses 4.5.0, Sophus 1.23, SpinSym 1.5, 
             TomLib 1.2.6, Utils 0.43
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> LoadPackage("cvec");
─────────────────────────────────────────────────────────────────────────────
Loading  orb 4.7.6 (Methods to enumerate orbits)
by Juergen Mueller (http://www.math.rwth-aachen.de/~Juergen.Mueller),
   Max Neunhöffer (http://www-groups.mcs.st-and.ac.uk/~neunhoef), and
   Felix Noeske (http://www.math.rwth-aachen.de/~Felix.Noeske).
Homepage: https://gap-packages.github.io/orb
─────────────────────────────────────────────────────────────────────────────
─────────────────────────────────────────────────────────────────────────────
Loading  cvec 2.5.6 (Compact vectors over finite fields)
by Max Neunhöffer (http://www-groups.mcs.st-and.ac.uk/~neunhoef).
Homepage: https://gap-packages.github.io/cvec
─────────────────────────────────────────────────────────────────────────────
true
gap> if LoadPackage("cvec",false) <> fail then mat := [[Z(2)]];
> ConvertToMatrixRep(mat,2); cmat := CMat(mat); cmat := cmat^1000; fi;
Error, CVEC_INTREP_TO_CVEC: no cvec in
  CVEC_INTREP_TO_CVEC( l, v 
 ); at /home/ghorvath/work/gap/pkg/cvec-2.5.6/gap/cvec.gi:833 called from 
CVec( v, c 
 ) at /home/ghorvath/work/gap/pkg/cvec-2.5.6/gap/cmat.gi:153 called from
<function "unknown">( <arguments> )
 called from read-eval loop at *stdin*:3
    try 'return;' (which will not work here!)
brk> 
````
Further, my stable GAP is not affected. 
````
 ┌───────┐   GAP 4.8.6, 12-Nov-2016, build of 2016-12-13 10:34:33 (CET)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.1, AutPGrp 1.6, Browse 1.8.6, CRISP 1.4.4, Cryst 4.1.12, CrystCat 1.1.6, CTblLib 1.2.2, FactInt 1.5.3, FGA 1.3.1, GAPDoc 1.5.1, IO 4.4.6, IRREDSOL 1.3.1, LAGUNA 3.7.0, Polenta 1.3.7, 
             Polycyclic 2.11, RadiRoot 2.7, ResClasses 4.5.0, Sophus 1.23, SpinSym 1.5, TomLib 1.2.6, Utils 0.43
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> if LoadPackage("cvec",false) <> fail then mat := [[Z(2)]];
> ConvertToMatrixRep(mat,2); cmat := CMat(mat); cmat := cmat^1000; fi;
gap> 
````

**Comment by ChrisJefferson** [comment]
You can't use kernel modules compiled for one version of GAP in another version of GAP, is that what you are doing?

We should probably have code to check that, and explicitly reject such modules.

**Comment by hungaborhorvath** [comment]
Ok, I will try building packages for development gap, and look if the error still exists.

In the meantime, it would be nice to know how people manage their stable and development packages. Do you copy the uncompiled version completely, and compile separately for stable and for development? Because I thought that it is ok to just symlink them, I even think that I was advised to do so in some readme file or webpage....

**Comment by ChrisJefferson** [comment]
@hungaborhorvath : Good question, it's a pain.

I just tend to keep separate copies. You can symlink packages without kernel modules.

We could consider encoding in the directory name of where the package binaries are stored the version of the GAP kernel, but that would obviously be a major change.

**Comment by hungaborhorvath** [comment]
@ChrisJefferson Ok, so is there a list of those packages that have kernel modules? Or of those that do not? Maybe the packages with kernel modules are the ones that require to be built?

**Comment by ChrisJefferson** [comment]
@hungaborhorvath : Unfortunately, I don't think we have a fixed list.

I believe you just need to look for packages which run `LoadDynamicModule` on my machine, that's:

```
> for i in *; do if grep -r LoadDynamicModule $i > /dev/null; then echo $i; fi; done
Browse
Gauss
Hap1.11
NormalizInterface-0.9.7
PackageMaker
PolymakeInterface
cvec-2.5.5
digraphs-0.5
edim
ferret
float-0.6.2
gapcpp
io
json
kerneltest
linboxing
orb-4.7.6
profiling
```

At the moment there is (I believe) no way to arrange these packages such that you can load one copy of the directory from both master and 4.8.

**Comment by alex-konovalov** [comment]
@hungaborhorvath asked

> In the meantime, it would be nice to know how people manage their stable and development packages. Do you copy the uncompiled version completely, and compile separately for stable and for development? Because I thought that it is ok to just symlink them, I even think that I was advised to do so in some readme file or webpage....

with 
```
make bootstrap-pkg-full
cd pkg
../bin/BuildPackages.sh
```

you can easily get the same set of packages as in the last stable release without symlinking. 

`make bootstrap-pkg-full` assumes that the subdirectory `pkg` does not exist. It creates this directory, downloads `http://www.gap-system.org/pub/gap/gap4pkgs/bootstrap-pkg-full.tar.gz` (which is updated after each minor release), and unpacks it. You need only to call `../bin/BuildPackages.sh` after that to build binaries.

**Comment by alex-konovalov** [comment]
P.S. @hungaborhorvath it could be me who suggested that symlink works, but is no longer the case (may still work in the stable branch, but not in master).

**Comment by hungaborhorvath** [comment]
Well, apparently compiling the packages running ````LoadDynamicModule```` did the trick, thank you. 

BTW, I wrote the following script to manage my packages, take note of the part "Prepare packages for GAP development". If anybody wants, you can use it for ````make bootstrap-pkg-full````, or whatever. 
(BTW, where are all these documented???)

````
GAPSTABLE=gap4r8p6_2016_11_12-14_25.tar.bz2
GAPDIR=~/work/gap4r8/
GAPDEVDIR=~/work/gap/

## GAP newest stable
cd ~/work
wget http://www.gap-system.org/pub/gap/gap48/tar.bz2/$GAPSTABLE
tar jxf ./$GAPSTABLE
rm ./$GAPSTABLE
cd gap4r8
./configure
make

## GAP development
cd ~/work
git clone https://hungaborhorvath@github.com/hungaborhorvath/gap
mkdir -p $GAPDEVDIR/pkg

# GAP stable package management
cd $GAPDIR/pkg

## GAP package sgpdec
wget https://github.com/gap-packages/sgpdec/archive/v0.7.33.tar.gz
tar zxf ./v0.7.33.tar.gz
rm ./v0.7.33.tar.gz

## GAP package subsemi
wget https://github.com/gap-packages/subsemi/archive/v0.76.tar.gz
tar zxf ./v0.76.tar.gz
rm ./v0.76.tar.gz

# Prepare packages for GAP development
while read PKG in
do
  if grep -r LoadDynamicModule $PKG > /dev/null
  then
    cp -r $GAPDIR/pkg/$PKG $GAPDEVDIR/pkg
  else
    ln -s $GAPDIR/pkg/$PKG -t $GAPDEVDIR/pkg
  fi
done < <(find ./ -maxdepth 1 -type d | sed 's|./||')

## Build packages for GAP stable
(../bin/BuildPackages.sh > >(tee ./buildpackages.out) 2> >(tee ./buildpackages.err >&2) ) > ./buildpackages.log 2>&1

## make GAP development
cd $GAPDEVDIR
./configure
make
make manuals

## GAP development package management
cd pkg

## Ferret for GAP
wget https://github.com/gap-packages/ferret/releases/download/v0.7.1/ferret-0.7.1.tar.gz
tar zxf ./ferret-0.7.1.tar.gz
rm ./ferret-0.7.1.tar.gz

## Build packages for GAP development
(../bin/BuildPackages.sh > >(tee ./buildpackages.out) 2> >(tee ./buildpackages.err >&2) ) > ./buildpackages.log 2>&1
````

**Comment by hungaborhorvath** [comment]
@alex-konovalov Thanks. I think I will stick with symlinks for those packages that do not have this ````LoadDynamicModule````. I know it is stupid, but I feel that we should not waste the space just because it is extremely cheap.
