### ISSUE TITLE
TriangulizedMat documentation does not match actual behaviour

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1030]
The documentation for `TriangulizedMat` resp. `RREF` currently says this: `... It returns a immutable matrix in upper triangular form. ...`

But this is not true, as a quick look at the implementation or a brief experiment shows:
```gap
gap> IsMutable(TriangulizedMat([[Z(2)]]));
true
```

So we should fix either the documentation or the behaviour. Since it is quite likely that some code out there relies on the current behaviour, I tend to change the documentation.

**Comment by alex-konovalov** [comment]
I agree with fixing documentation. `TriangulizedMat` calls `m:=List(mat,ShallowCopy)` and then `TriangulizeMat(m)`, and documentation for the latter says that it takes a mutable matrix and changes it. I can't explain how "immutable" appears in `TriangulizedMat`...
