### ISSUE TITLE
ParGAP bug with Sort(deltas) in MasterSlaveDeadSlave function

### ISSUE THREAD

**Issue by valdecar** [gap-system/gap#1041]
Warning: non-native English speaker
### Problem
In declaration of MasterSlaveDeadSlave function in  pargap/libmasslave.g file from one can found lines:
```
deltas := List(slaveArray, x->realtime-x.time);
Sort(deltas);
```
But, because of slaveArray is list that can contain holes (holes in list `l` means `l:=[1,,,3,5,,7])`, deltas also can contain holes. In that case `Sort(deltas)` return error. 
### How detect
1) First way:
 You can run tests from /gap4r8/pkg/pargap/tst/pargap.tst:
```
#run pargap 
mpiexec -n 3 /pathToGap/gap4r8/pkg/pargap/bin/pargap.sh
#load tests
gap> ReadTest(Filename(DirectoriesPackageLibrary("pargap", "tst"), "pargap.tst"));
#It print:
 --unimportant data not shown--
 # Input is:
 ParMultMat(A,A) = A*A;
 # Expected output:
 true
 # But found:
  Error, List Element: <list>[1] must have an assigned value
 ########
pargap/tst/pargap.tst
GAP4stones: 5405405
```
2) Second  way (and how it bug was first detected):
For that case I  use my_for function from parDraft.g file. It declared as:
```
ParInstallTOPCGlobalFunction("my_for",
function(_list1,_list2,_list3)
    
    # global data, known all slaves
    local i,result,len1,len2,len3,
           doTask;

    result:=[];
    i:=0;
    len1:=Length(_list1);
    len2:=Length(_list2);
    len3:=Length(_list3);
    
    doTask:=function(i)
            #what each slave will do
            local j,k,t;
            for j in [1..len2] do
                for k in [1 .. len3] do
                    #do some work there
                    t:=2+2;
                od;
            od;
            return(false);
    end;
     #  TaskInputIterator and DefaultCheckTaskResult  is native pargap functions
    MasterSlave(TaskInputIterator([1..len1]),doTask,DefaultCheckTaskResult);
    return(result);
end
);

```
and used as:
```
#run pargap:
mpiexec -n 3 /pathToGap/gap4r8/pkg/pargap/bin/pargap.sh
#load parDraft.g:
gap>Read("parDraft.g"); 
gap>l:=[1..100];;
gap>my_for(l,l,l);
#this return
master -> 1:  1
master -> 2:  2
2 -> master: false
master -> 2:  3
2 -> master: false
master -> 2:  4
1 -> master: false

Error, List Element: <list>[1] must have an assigned value in
  Sort( deltas 
 ); at /home/valdecar/programs/gap4r8/pkg/pargap/lib/masslave.g:466 called from 
MasterSlaveDeadSlave(  
 ); at /home/valdecar/programs/gap4r8/pkg/pargap/lib/masslave.g:271 called fro\
m
TOPCmasterSendTaskInput( SubmitTaskInput, taskAgglomCount 
 ) at /home/valdecar/programs/gap4r8/pkg/pargap/lib/masslave.g:181 called from
TOPCmaster( SubmitTaskInput, CheckTaskResult, UpdateSharedData, taskAgglom 
 ); at /home/valdecar/programs/gap4r8/pkg/pargap/lib/masslave.g:135 called fro\
m
MasterSlave( TaskInputIterator( [ 1 .. len1 ] ), doTask, 
 DefaultCheckTaskResult ); at parDraft.g:32 called from
CallFuncList( fnc, arg 
 ) at /home/valdecar/programs/gap4r8/pkg/pargap/lib/masslave.g:507 called from
...  at line 3 of *stdin*
you can 'return;' after assigning a value
brk> 
```
if error not shown try change `l` to some more complicated like `l:=[1..1000];`.
### possible fix (of symptoms)
So I added string `deltas:=Compacted(deltas);` before `Sort(deltas);`  in function MasterSlaveDeadSlave declaration in file "pargap/lib/masslave.g". After that all seems work. But I still don't understand why one simple function like my_for has led to a call function with horrible name like MasterSlaveDeadSlave.
So I decide to add this issue in hope that some more awareness will check it again. 
### configuration
gap 4.8.6
pargap 1.4.0 (from gap4r8/pkg folder)
openmpi-common 1.6.5-8
libopenmpi-dev 1.6.5-8 
rest in config.log 
pargap was maked with:
`./configure --with-basic-gap-configure`

[parDraft.g.txt](https://github.com/gap-system/gap/files/671796/parDraft.g.txt)
[config.log.txt](https://github.com/gap-system/gap/files/671797/config.log.txt)

**Comment by fingolfin** [comment]
Added to ParGAP repo as https://github.com/gap-packages/pargap/issues/2

**Comment by alex-konovalov** [comment]
@valdecar thank you for reporting this. I am closing this issue here, since it's now migrated to ParGAP's newly established repository at https://github.com/gap-packages/pargap/issues/2.
