### ISSUE TITLE
Third and fourth argument to NewRepresentation and DeclareRepresentation are ignored

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1042]
This is more a question or a "request for comments" and an issue:

Today, I was wondering what the `slots` argument to `DeclareRepresentation` and `NewRepresentation` really do es(the manual is a bit vague on that), and also what the fourth argument `req` (supposedly for "required"?) is about -- the documentation does not talk about it at all.

To my surprise, it seems that both arguments are simply ignored?!? Perhaps they were meant for future extensions that were never implemented? Or perhaps they were removed at some point?

There are some things we could do:

1. identify what those arguments were meant for, and implement that functionality
2. remove `req` from the documentation, but keep accepting it silently for backwards compatibility
3. remove both `slots` and `req` from the documentation, but keep accepting them silently for backwards compatibility
4. as a variation of 2 and 3, we could also warn if either is used (say, if `InfoObsolete` is set to a non-zero value).

Regarding 1, perhaps `slots` was meant to be used as some kind of limited type checking, where objects are not allowed to bind other "slots" than those. But in reality, this never (????) was enforced. So it is very likely that if we started to enforce it, code would break. Hence option 1 does not seem very realistic at this point -- though perhaps it could be implemented in the form of an `InfoWarning` message or so?

**Comment by hulpke** [comment]
As far as I remember, these "slots" were supposed to be record components that could, respectively that would have to exist in a component object. Its purpose presumably was to keep control over what components were entered (and to force most of them into attributes) but it was never implemented and never missed, furthermore many declarations in the library only list few components.

 my preference would be for two, that is removing it from the documentation but quietly accepting them as no-op arguments for existing code.

**Comment by frankluebeck** [comment]
I vote for variant 3.

**Comment by fingolfin** [comment]
@hulpke Did you perhaps also mean variant 3 (and not 3)? Just wondering because what you write refers to `slots`, and you write "accepting them" which would fit 3, not 2.

**Comment by hulpke** [comment]
Yes, 3. I didn’t read that far and tghought req was the general ``requirements’’ for using `DeclareRepresentation’. Sorry!

  Alexander

**Comment by ThomasBreuer** [comment]
This can be closed since #4519 has been merged.
