### ISSUE TITLE
Tighten up rules on loading workspaces

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#1089]
At the moment GAP checks the kernel version when loading workspaces (so for example 4.4.11 won't load a 4.4.10 workspace). I would like to suggest the following tightening of the rules:

* Reject if `HAVE_LIBREADLINE` is different
* Reject if `BUILD_VERSION` is different (that is, the git version the kernel was build from)

Only the last one I imagine might be controversial, but I think we should do it, as a few times I have found it can produce hard-to-debug errors. We could instead in this last case just produce a warning if people really want to be able to try it.

EDIT: I wondered about rejecting if `GMP_VERSION` is different, but I don't think that should effect workspaces, and would break workspaces when the OS updates the GMP version.

The coding for this is easy, but I wanted to get thoughts before starting.

Would fix #1079

**Comment by stevelinton** [comment]
The GMP version would only matter if gmp changed it's mpn binary data format, which seems pretty unlikely.

**Comment by fingolfin** [comment]
This was fixed by PR #2720 
@ChrisJefferson the "fixes" keyword must appear for before each issue number in order for the issue to be auto-closed when the PR gets merged.
