### ISSUE TITLE
Add tst/test-error to standard test suite

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1090]
As @ChrisJefferson said,
> I started adding some tests for this kind of thing, in tst/test-error. They aren't linked up yet to the general testing unfortunately. I will look into it.

**Comment by fingolfin** [comment]
Hooking them up with travis shouldn't be hard: We just need to invoke `tst/test-error/run_error_tests.sh` in e.g. `etc/ci.sh`, right? But see also #1094
