### ISSUE TITLE
UniteSet makes immutable arguments mutable, and removes string rep.

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1095]
A weird test failure on PR #1072 lead me to the following discovery:
```gap
gap> not IsMutable(CHARS_LALPHA); IsStringRep(CHARS_LALPHA);
true
true
gap> UniteSet("abc",CHARS_LALPHA);
gap> not IsMutable(CHARS_LALPHA); IsStringRep(CHARS_LALPHA);
false
false
```
So, the globale variable `CHARS_LALPHA` is immutable and in string rep before the call to `UniteSet`. Afterwards, it is neither.

**Comment by fingolfin** [comment]
Wow, this must be an anicent bug (?!).

Turns out that the kernel function `IsSet` invokes `PLAIN_LIST` on anything that is not a plist but a small list (such as a string in stringrep...) and sorted.

And since `IsSet` is invoked on both arguments of `UniteSet`...

So to fix this, we could change `IsSet` to not modify its arguments. But that will have a ripple effect, we'd have to carefully inspect everything call it. For `FuncUNITE_SET`, it's not so bad because it already calls `SetList` on its second argument if it is not a set. But for the first argument, things are different.

I guess we might need two variants of `IsSet` (e.g. by giving it a second argument, a boolean which indicates whether it should attempt to convert its argument in-place or not. And even for the version that performs in-place conversion, we should consider honoring the immutable flag -- in this case, that would mean checking `IS_MUTABLE_OBJ` *before* `IsSet`

Moreover, we now may want to provide versions of `UniteSet` etc. for strings, and/or arbitrary small lists. The code would be almost identical, of course, just `ELM_PLIST` be replaced by `GET_ELM_STRING` or `ELM_LIST`. So we could use some preprocessor magic to reduce the required effort... (And if we were allowed to use C++, then some basic template programming would very easily take care of this, too).

Finally, if we fix this, it might affect some library code which implicitly expects that the arguments of `UniteSet` (and other set functions) are turned into plain lists.

**Comment by fingolfin** [comment]
Seems this bug has been around since the old repository was started :)

**Comment by fingolfin** [comment]
So `PlainString` was not correctly preserving mutability, that fixes half of the problem.

After having looked longer at the relevant code, I guess it is intentional that the representation of the string is changed. I still find it questionable to do this, but there is a lot of code in the kernel of that nature, so trying to change it might be quite monumental...

**Comment by alex-konovalov** [comment]
Is this related to problems discussed in http://tracker.gap-system.org/issues/79 ? Cf. the following:
```
gap> E;
<Operation "E">
gap> Filtered(NamesSystemGVars(),name->IsSubset(LETTERS,name));;
gap> E;
Error, Variable: 'E' must have a value
not in any function at line 3 of *stdin*
```

**Comment by alex-konovalov** [comment]
@fingolfin Is this fixed by #1096?

**Comment by fingolfin** [comment]
@alex-konovalov No, it is not:
```gap
gap> not IsMutable(CHARS_LALPHA); IsStringRep(CHARS_LALPHA);
true
true
gap> UniteSet("abc",CHARS_LALPHA);
gap> not IsMutable(CHARS_LALPHA); IsStringRep(CHARS_LALPHA);
true
false
```

**Comment by fingolfin** [comment]
... but it *is* a duplicate of issue #815. Closing in favor of that older issue.
