### ISSUE TITLE
Print Filters for Operations, Attributes, Properties

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#1115]
There should be a way to get filter information about Constructors, OPerations, Attributes, and Properties, for example if one prints them, for example

```
gap> Normaliser;
<Operation Normalizer(IsGroup, IsObject)>
```
obvious extensions include printing what filters there are actually methods installed, though that could be a longish-list and should not be just printed.

I'll assign it to myself, but anyone who feels like beating me to it feel free to ;).

**Comment by fingolfin** [comment]
A different solution for this was merged recently in the form of the `ShowDeclarationsOfOperation` helper function.
