### ISSUE TITLE
Unhelpful error message (?)

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#1117]
When playing with the parser I get this

```
gap> function()  
> 1+1;
Syntax error: end expected
1+1;
^
```

**Comment by ChrisJefferson** [comment]
What would you like instead?

**Comment by ChrisJefferson** [comment]
This is printed by line read.c:1535. We can change the `"end"` to anything we like easily (that `"end"` is just what is printed in the error, it's not part of the parsing).

The reason this appears is we loop checking for every kind of valid expression until we find no more, then we expect to find an `end` (or `od` for blocks)

**Comment by fingolfin** [comment]
I think this is more or less the same issue as #2017
