### ISSUE TITLE
Missing tools for tools archive

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1118]
In GAP 4.8.6 installation you can find the archive `etc/tools.tag.gz` and the script `etc/install-tools.sh` script which unpacks this archive ensuring that files will go into intended directories:
```
Unpacking tools.tar.gz archive ...
x etc/convert.pl
x etc/README.tools
x etc/packpack
x etc/buildman.pe
x etc/unzoo.c
x doc/gapmacrodoc.tex
x doc/gapmacro.tex
x doc/manualindex
x doc/gapmacrodoc.pdf
Done!
``` 
This setup is here from 2012, and `etc/README.tools` describes its content: https://github.com/gap-system/gap/blob/stable-4.8/etc/README.tools. The tools archive is created when the GAP source distribution is wrapped using scripts from https://github.com/gap-system/gap-distribution/tree/master/DistributionUpdate. It became broken at some point this winter, as some files that are supposed to go to the tools archive were removed (`remake.sh` is fine, I will fix this on the release wrapping side):

```
find: 'gap4r9/tst/remake.sh': No such file or directory
find: 'gap4r9/etc/buildman.pe': No such file or directory
find: 'gap4r9/etc/install-tools.sh': No such file or directory
find: 'gap4r9/etc/packpack': No such file or directory
```

In more details:
- etc/convert.pl - stays
- etc/README.tools - stays
- etc/packpack - removed in https://github.com/gap-system/gap/commit/dc1907f90a1017413be687a2c6b41baa1f1c231e
- etc/buildman.pe - removed in https://github.com/gap-system/gap/commit/d0ab7a6bcc2a529b47c04585b723fcaf5e4d421c
- etc/unzoo.c - removed in https://github.com/gap-system/gap/pull/540/commits/be0aa5eb3857110ad03ced98937e48b18c7780d4
- doc/gapmacrodoc.tex - stays
- doc/gapmacro.tex - stays
- doc/manualindex - stays
- doc/gapmacrodoc.pdf - produced from `doc/gapmacrodoc.tex` during the release wrapping

and `install-tools.sh` has been removed in https://github.com/gap-system/gap/commit/dc1907f90a1017413be687a2c6b41baa1f1c231e.

As a quick fix, because I need to get release wrapping back to work, I am going to restore 
`install-tools.sh` and remove commands related to the deleted files. But I am not sure if we still need the tools archive in the long run. IIRC the idea in 2011 was to provide scripts which are mainly of interest to package authors, and now we have better tools and better ways of redistributing them. 
 
P.S. Once similar thing happened already: https://github.com/gap-system/gap/issues/640

**Comment by ChrisJefferson** [comment]
Do you really need `install-tools.sh` All it does is `tar -xvzf tools.tar.gz -C ../`?

**Comment by alex-konovalov** [comment]
I think so, otherwise if users will just click on the file or extract it without adding `-C ../`, the files may end up in wrong locations.

**Comment by alex-konovalov** [comment]
So far I've done https://github.com/gap-system/gap/commit/20169c70cfc503f2d38a31402b8fa64d3a65787d and https://github.com/gap-system/gap-distribution/commit/dc46fd01a4bfec70d1b8c41866d55382462660a6 to restore `install-tools.sh` and remove references to deleted files. This permits me to resume weekly tests of the release candidates on the new Jenkins setup, then if we wish we can make more changes more carefully.

**Comment by fingolfin** [comment]
I am not hat all convinced and somewhat upset that the file was restored via direct commit, instead of a PR, thus giving no chance for review and/or alternative solutions. In particular, I think we shold just drop the tools arcgive.

Was it really such an emergency that it couldn't wait for at least a day?

**Comment by alex-konovalov** [comment]
Yes, it really was - I need to migrate jobs from old Jenkins to new one, to avoid further tests rotting and restart checks for package updates. I had time yesterday and have some other plans for today. And I was also upset that the file was removed via direct commit ;-)

**Comment by fingolfin** [comment]
The file was not removed via a direct commit, it came via a pull request: https://github.com/gap-system/gap/pull/1064

**Comment by fingolfin** [comment]
I am quite concerned that it took 25 days for this problem to be noticed. (To be clear, that's not meant as a criticism of Alex.) If the scripts or whatever which use install-tools.sh scripts were run daily (or at least every few days) by a test server, this would not have happened.
Perhaps it just was bad luck because the GAP jenkins is down, though, and normally would have been noticed earlier?

**Comment by fingolfin** [comment]
As it is, I think the file should not have been restored, and we should remove it again (see #1125), and instead the distribution scripts should be adjusted to not refer to it anymore. Also, `doc/ref/helpintf.xml` should be adjusted to not refert to it anymore. Is there any other place that would need to be adapted?

**Comment by alex-konovalov** [comment]
Apologies, it was a PR indeed - I looked at the master branch and haven't figured that out because it was rebased.  It's a nitpick, but it took 22 days, not 25. Because we were forced to run a subset of scripts, and there was no weekly wrapping of the release candidate those days (there were nighty tests of the master branch although). 

I think the PR #1064 was a bit rushed. If one edits `README.tools` and throws away something referring package update system, it's better to ask for me to check.

**Comment by alex-konovalov** [comment]
I am closing this issue, as the problem described here has been resolved, and release candidate wrapping for the next major release has been fixed. We will work in #1125 to try to drop the tools archive at all properly, with simultaneous changes in the release wrapping scripts.
