### ISSUE TITLE
Fresh failures in teststandard with all packages

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1119]
On Jenkins, teststandard passes with `-A` option, but fails when all packages are loaded. @james-d-mitchell, @markuspf, @hulpke do you recognise any of your changes that may be related?

```
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/tst/teststandard/reesmat.tst:1121
# Input is:
BruteForceIsoCheck(map);
# Expected output:
true
# But found:
Error, Semigroups: GreensRClassOfElement: usage,
the element does not belong to the D-class,
########
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/tst/teststandard/reesmat.tst:1123
# Input is:
BruteForceInverseCheck(map);
# Expected output:
true
# But found:
Error, Semigroups: GreensRClassOfElement: usage,
the element does not belong to the D-class,
########
```

```
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/tst/testinstall/opers/StructureDescription.tst:87
# Input is:
StructureDescriptionForFiniteSimpleGroups(Ree(27));
# Expected output:
"Ree(27)"
# But found:
Error, reached the pre-set memory limit
(change it with the -o command line option)
########
```

```
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/tst/testinstall/semigrp.tst:288
# Input is:
S := Semigroup(PartialPerm([1]));
# Expected output:
<trivial partial perm monoid of rank 1 with 1 generator>
# But found:
<trivial partial perm group of rank 1 with 1 generator>
########
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/tst/testinstall/semigrp.tst:298
# Input is:
S := Semigroup(IdentityTransformation);
# Expected output:
<trivial transformation monoid of degree 0 with 1 generator>
# But found:
<trivial transformation group of degree 0 with 1 generator>
########
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/tst/testinstall/semigrp.tst:307
# Input is:
S := Monoid(PartialPerm([1]));
# Expected output:
<trivial partial perm monoid of rank 1 with 1 generator>
# But found:
<trivial partial perm group of rank 1 with 1 generator>
########
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/tst/testinstall/semigrp.tst:309
# Input is:
S := Monoid(PartialPerm([1]));
# Expected output:
<trivial partial perm monoid of rank 1 with 1 generator>
# But found:
<trivial partial perm group of rank 1 with 1 generator>
########
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/tst/testinstall/semigrp.tst:315
# Input is:
S := Monoid(IdentityTransformation);
# Expected output:
<trivial transformation monoid of degree 0 with 1 generator>
# But found:
<trivial transformation group of degree 0 with 1 generator>
########
```

```
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/tst/testinstall/semitran.tst:53
# Input is:
S := Semigroup(IdentityTransformation);
# Expected output:
<trivial transformation monoid of degree 0 with 1 generator>
# But found:
<trivial transformation group of degree 0 with 1 generator>
########
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/tst/testinstall/semitran.tst:147
# Input is:
S := Semigroup(IdentityTransformation);
# Expected output:
<trivial transformation monoid of degree 0 with 1 generator>
# But found:
<trivial transformation group of degree 0 with 1 generator>
########
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/tst/testinstall/semitran.tst:171
# Input is:
S := Semigroup(IdentityTransformation);
# Expected output:
<trivial transformation monoid of degree 0 with 1 generator>
# But found:
<trivial transformation group of degree 0 with 1 generator>
########
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/tst/testinstall/semitran.tst:285
# Input is:
IsomorphismTransformationMonoid(S);
# Expected output:
Error, IsomorphismTransformationMonoid: usage,
the argument must be a semigroup with a multiplicative neutral element,
# But found:
Error, Semigroups: IsomorphismTransformationMonoid: usage,
the argument <s> must have a multiplicative neutral element,
########
```

**Comment by hungaborhorvath** [comment]
````
########> Diff in /data/gap-jenkins/workspace/GAP-pkg-update-master-quicktest/\
GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-update-mas\
ter-snapshot/tst/testinstall/opers/StructureDescription.tst:87
# Input is:
StructureDescriptionForFiniteSimpleGroups(Ree(27));
# Expected output:
"Ree(27)"
# But found:
Error, reached the pre-set memory limit
(change it with the -o command line option)
########
````
The test itself was added by me for better coverage of ````grpnames.gi````. At that time the gave an instantaneous answer. In fact, I updated to current master, recompiled both gap and manuals, and this one line still gives me an immediate answer:
````
 ┌───────┐   GAP v4.8.6-1245-g20169c7 of 2017-02-05 09:27:44 (CET)
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp 6.0.0, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 3.0, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.1, AutPGrp 1.6, 
             Browse 1.8.6, Carat 2.1.6, CRISP 1.4.4, Cryst 4.1.12, 
             CrystCat 1.1.6, CTblLib 1.2.2, FactInt 1.5.3, FGA 1.3.1, 
             GAPDoc 1.5.1, IO 4.4.6, IRREDSOL 1.3.1, LAGUNA 3.7.0, 
             Polenta 1.3.7, Polycyclic 2.11, RadiRoot 2.7, ResClasses 4.5.0, 
             Sophus 1.23, SpinSym 1.5, TomLib 1.2.6, Utils 0.43
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> StructureDescriptionForFiniteSimpleGroups(Ree(27)); time;
"Ree(27)"
24
gap> 
````
Maybe I am not loading a package that jenkins loads?

**Comment by james-d-mitchell** [comment]
The changes in recent pull requests relating to semigroups were to fix bugs highlighted by new tests added in the dev version of the Semigroup package. The tests in the current release version of Semigroups are broken by these changes, and so library tests are broken by being replaced with methods in Semigroups that have bugs in the release version. I am preparing a new version of Semigroups to address this. It will be ready by the time the 4.9 release is ready but maybe not much before.

**Comment by alex-konovalov** [comment]
@hungaborhorvath yes, as I've said, it fails with all packages are loaded. Try to call `LoadAllPackages();` and see if it works.

**Comment by ChrisJefferson** [comment]
Given we want to be able to test with `LoadAllPackages`, there seems to be 2(?) choices:

1) Don't load the semigroups package until it is fixed
2) Disable the new tests until the semigroups package is fixed

**Comment by alex-konovalov** [comment]
(2) is not acceptable, (1) cuts too much, and (3) is to ignore errors till new Semigroups release... But I've tried (4) and will switch to using the stable version of Semigroups in https://github.com/gap-system/gap-distribution/commit/ac7062bc437b6d7fa29345f9f308ed366200fa93. This will explain whether all errors in this issue are caused by Semigroups, or only some of them.

I do hope that the latest official release of Semigroups works in master branch. Otherwise, I can indeed to (1) with specifying `semigroups=no` instead of `semigroups=stable`.

**Comment by alex-konovalov** [comment]
P.S. Of course now me and @james-d-mitchell should remember to revert https://github.com/gap-system/gap-distribution/commit/ac7062bc437b6d7fa29345f9f308ed366200fa93 after the next Semigroups release!

**Comment by hungaborhorvath** [comment]
Ok, I have checked the problem with the ````Ree(27)```` group. The main problem is that the package ````Gpd-1.45```` defines a nice monomorphism method for ````IsAbelian```` in ````pkg/gpd-1.45/lib/gpd.gi:2325````, and then that will be invoked for the ````Ree(27)```` group, instead of the generic method from ````lib/magma.gd:868````. And creating the nice monomorphism takes an enormous time for this group. 

I believe this is the same error as in #987. A quick fix could be just to remove this check from the tests. The test itself does nothing else, anyway, just adds coverage for ````grpnames.gi:1715-1716````.

**Comment by hulpke** [comment]
@alex-konovalov I did not merge anything recently -- unlikely to be my code

Concerning the observation by @hungaborhorvath I can't fathom why one would want a nice monomorphism for `IsAbelian` -- it is just a test on the generators and can be done in the original group as soon as we can compare elements.  My inclination is to consider it a bug (or too general an installation) in Gpd.

**Comment by alex-konovalov** [comment]
Semigroups package could be a red herring here. All tests pass in 32-bit builds. Could be a combination of factors - e.g. one test now passes because less memory needed, and another passes because some package failed to compile. Looking...

**Comment by alex-konovalov** [comment]
Ok, first, the semigroups package is not related. Second, without packages, we have 3 sec for `opers/StructureDescription.tst`. @cdwensley could you please have a look at Gpd? See comments by @hungaborhorvath and @hulpke above.

**Comment by cdwensley** [comment]
The offending method for IsCommutative is removed in gpd-1.46 just released. 
This method did not "define a nice monomorphism method for IsAbelian", but rather defined a method for IsAbelian when a nice monomorphism existed - it just tested the nice object.  But, I now realise, there may be nice objects for which it may be hard to determine this property.  Apologies for any inconvenience caused.

**Comment by alex-konovalov** [comment]
@cdwensley Thank you - now everything runs well (modulo diffs caused by other reasons).

I've now precise understanding which errors have been cause by Semigroups and which not. The only TODO for this issue is to waiting for @james-d-mitchell to submit new release of Semigroups that will not break master branch tests.

**Comment by alex-konovalov** [comment]
To remind myself the status of this issue: it waits for the new version of Semigroups by @james-d-mitchell

**Comment by alex-konovalov** [comment]
Closing as Semigroups 3.x has been released.
