### ISSUE TITLE
Overflow in SySystemInitFile

### ISSUE THREAD

**Issue by isuruf** [gap-system/gap#1171]
### Observed behaviour
When building gap on a long prefix, the buffer `SySystemInitFile` overflows leading to an error,

    gap: hmm, I cannot find 'lib/init.g' maybe use option '-l <gaproot>'?

I'm building gap as a [conda](https://conda.io/docs/) package and when building the package it is done on a long path (255 chars) so that the binary package can be copied to long prefixes. Therefore SySystemInitFile is longer than 256 and causes an overflow.

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.8.3, 19-Mar-2016, build of 2017-02-26 06:48:53 (UTC)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Packages:   GAPDoc 1.5.1
 Try '?help' for help. See also  '?copyright' and  '?authors'
```

I can send a PR to fix this. (I didn't check, but other `char*`s in `src/system.c` might overflow as well.)

**Comment by ChrisJefferson** [comment]
The obvious thing to look at is `PATH_MAX` (which unfortunately still isn't the longest length of a path, but hopefully will be long enough.. lots of other things start breaking after `PATH_MAX`).

Unfortunately, for technical reasons we can't just `malloc` out way around the problem. What is the upper limit path you think it's reasonable you'll create? (Is that a sensible question?)

**Comment by isuruf** [comment]
conda has a upper limit for the prefix at 255, so 512 works for me. I can check what the lowest upper limit can be for conda.

**Comment by frankluebeck** [comment]
We have discussed the possibility of allowing longer paths on several occasions. And we sticked to buffer lengths of 256 characters because of claims that longer paths are not supported in Windows. 

And isn't this enough for all practical purposes? I do not fully understand from the initial post why this becomes a problem. 

We could certainly try to implement a better error message for the case that longer paths occur.

**Comment by ChrisJefferson** [comment]
@frankluebeck : Some systems like  conda (a python packaging system) can make deeply nested directory structures when they install sub-packages. This makes it easier to hit the limit.

Having > 256 character buffers wouldn't a problem for windows -- it just wouldn't use the rest of the space.

I can't think of any good reason not to make the buffers equal to 4K. This is the value of PATH_MAX on many operating systems, and provide plenty of extra space. This won't use a measurable amount of extra memory.

**Comment by vbraun** [comment]
On Windows only the legacy non-unicode path api has a limit of 256 bytes; The limit with the current API is 32k chars: https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx#maxpath

+1 to upping the limit to 4K

Conda intentionally builds in a long (and artificial) directory path. At install time, conda searches the binary for hardcoded paths and replaces it with the install path + \0

**Comment by fingolfin** [comment]
@isuruf could you please try again with latest master and tell us if that resolves the issue for you?

**Comment by isuruf** [comment]
Works for me. Thanks
