### ISSUE TITLE
HPC-GAP crashes under Windows and i686 under CentOS 5

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#118]
This is not related to the today's merge from the master branch - I've started to observe this last week. I am just creating this issue as a reminder for myself to look. 

The Windows version of HPC-GAP is compiled under Cygwin. We were able to build it in the past, but then it became unstable in July 2014 - segfault happened straight after start. Now, since the morning March 19th the test fails with another symptoms:
```
+ bin/gap.sh -r -A -S tst/testinstall.g
Syntax error: warning: unbound global variable in /mnt/disk2/opt/hudson-\
slave/workspace/GAP-HPC-compilers/GAPABI/32/GAPGC/boehm/GAPGMP/gmp/label\
/32bit/GAP-HPC-snapshot/lib/cmdledit.g line 297
 READLINEINITLINE(ShallowCopy(str));
                 ^
Syntax error: warning: unbound global variable in /mnt/disk2/opt/hudson-\
slave/workspace/GAP-HPC-compilers/GAPABI/32/GAPGC/boehm/GAPGMP/gmp/label\
/32bit/GAP-HPC-snapshot/lib/cmdledit.g line 301
 BINDKEYSTOGAPHANDLER(ShallowCopy(str));
                     ^
Syntax error: warning: unbound global variable in /mnt/disk2/opt/hudson-\
slave/workspace/GAP-HPC-compilers/GAPABI/32/GAPGC/boehm/GAPGMP/gmp/label\
/32bit/GAP-HPC-snapshot/lib/cmdledit.g line 311
   BindKeysToGAPHandler(a);
                       ^
Syntax error: warning: unbound global variable in /mnt/disk2/opt/hudson-\
slave/workspace/GAP-HPC-compilers/GAPABI/32/GAPGC/boehm/GAPGMP/gmp/label\
/32bit/GAP-HPC-snapshot/lib/cmdledit.g line 316
   ReadlineInitLine(a);
                   ^
Syntax error: warning: unbound global variable in /mnt/disk2/opt/hudson-\
slave/workspace/GAP-HPC-compilers/GAPABI/32/GAPGC/boehm/GAPGMP/gmp/label\
/32bit/GAP-HPC-snapshot/lib/cmdledit.g line 322
 ReadlineInitLine(Concatenation("\"", seq, "\": \"", subs, "\""));
                 ^
Syntax error: warning: unbound global variable in /mnt/disk2/opt/hudson-\
slave/workspace/GAP-HPC-compilers/GAPABI/32/GAPGC/boehm/GAPGMP/gmp/label\
/32bit/GAP-HPC-snapshot/lib/actor.g line 72
 RunAsyncTask(ACTOR_LOOP, actor_state);
             ^
Syntax error: warning: unbound global variable in /mnt/disk2/opt/hudson-\
slave/workspace/GAP-HPC-compilers/GAPABI/32/GAPGC/boehm/GAPGMP/gmp/label\
/32bit/GAP-HPC-snapshot/lib/error.g line 192
   if QUITTING or not BreakOnError then
                                      ^
Syntax error: warning: unbound global variable in /mnt/disk2/opt/hudson-\
slave/workspace/GAP-HPC-compilers/GAPABI/32/GAPGC/boehm/GAPGMP/gmp/label\
/32bit/GAP-HPC-snapshot/lib/session.g line 62
   BreakOnError := false;
                 ^
Syntax error: warning: unbound global variable in /mnt/disk2/opt/hudson-\
slave/workspace/GAP-HPC-compilers/GAPABI/32/GAPGC/boehm/GAPGMP/gmp/label\
/32bit/GAP-HPC-snapshot/lib/session.g line 93
   BreakOnError := false;
                 ^
/tmp/hudson14346.sh: line 37:  8647 Segmentation fault      bin/gap.sh -r -A -S tst/testinstall.g > testinstalllog.txt
Build step 'Execute shell' marked build as failure
```

**Comment by alex-konovalov** [comment]
P.S. I've also discovered that the same happens on the gcc 4.1.2 on our quite outdated 32-bit CentOS 5 Jenkins slave.

**Comment by alex-konovalov** [comment]
Analysing Jenkins logs, I've find out that on 32-bit CentOS 5 slave the problem was observed for the first time after the build based on commit 3425a450714172b23fa9b3e72d3ce16c4ecc5406. Prior to that, the build based on commit 7974275bcdcd9deed84cf113ae5bf1a7713d047a worked fine on all Linux slaves.

**Comment by ChrisJefferson** [comment]
I would guess this is a problem with not having readline, based on the names?

I tried building on CentOS 5, but it seems I'll have to manually install git, which I don't really fancy doing. Perhaps I can figure out how to tell hpcgap it doesn't have readline?

**Comment by alex-konovalov** [comment]
Actually, readline is present on that CentOS 5 machine, and GAP 4 builds pick it up properly.  Also, @rbehrends temporarily switched off readline support in HPC-GAP. So suspect this is something else. To avoid installing git, I will inspect Jenkins workspace for the test directly (hopefully shortly).

**Comment by alex-konovalov** [comment]
I've logged in and indeed this is not related to readline. There is another error before error-handling is initialized:
```
-bash-3.2$ bin/gap.sh  -r -A -S
Error before error-handling is initialized: 
[ "Lists Assignment: <list> must be a mutable list" 
 ]Error before error-handling is initialized: 
[ 
  "Record: '<atomic record>.CommandLineOptions' must have an assigned val\
ue" ]Error before error-handling is initialized: 
[ "Variable: 'TEACHING_MODE' must have a value" 
 ]Error before error-handling is initialized: 
[ 
  "Record: '<atomic record>.CommandLineOptions' must have an assigned val\
Syntax error: warning: unbound global variable in /mnt/disk2/opt/hudson-\
slave/workspace/GAP-HPC-compilers/GAPABI/32/GAPGC/boehm/GAPGMP/gmp/label\
/32bit/GAP-HPC-snapshot/lib/cmdledit.g line 297
  READLINEINITLINE(ShallowCopy(str));
                  ^
```
Perhaps this is a side-effect of commit 5bbc74b3eb33e4081b451af7c7f4a591338c9532 making some things immutable or atomic...

**Comment by alex-konovalov** [comment]
Update: starting GAP with `-D` option, one could see in which files the two early errors occur:

```
-bash-3.2$ bin/gap.sh -r -A -D
#I  READ_GAP_ROOT: loading 'lib/init.g' as GAP file
#I  READ_GAP_ROOT: loading 'lib/kernel.g' as GAP file
#I  READ_GAP_ROOT: loading 'lib/global.g' as GAP file
#I  READ_GAP_ROOT: loading 'lib/system.g' as GAP file
Error before error-handling is initialized: [ "Lists Assignment: <list> must be a mutable list" ]
Error before error-handling is initialized: [ "Record: '<atomic record>.CommandLineOptions' must have an assigned value" ]
#I READ_GAP_ROOT: loading 'lib/read1.g' as GAP file
...
...
...
#I  READ_GAP_ROOT: loading 'lib/info.gi' as GAP file
Error before error-handling is initialized: [ "Variable: 'TEACHING_MODE' must have a value" ]
#I  READ_GAP_ROOT: loading 'lib/assert.gi' as GAP file
...
#I  READ_GAP_ROOT: loading 'lib/cmdledit.g' as GAP file
Syntax error: warning: unbound global variable in /mnt/disk2/opt/hudson-slave/workspace/GAP-HPC-compilers/GAPABI/32/GAPGC/boehm/GAPGMP/gmp/label/32bit/GAP-\
HPC-snapshot/lib/cmdledit.g line 297
  READLINEINITLINE(ShallowCopy(str));
                  ^
...
Syntax error: warning: unbound global variable in /mnt/disk2/opt/hudson-slave/workspace/GAP-HPC-compilers/GAPABI/32/GAPGC/boehm/GAPGMP/gmp/label/32bit/GAP-\
HPC-snapshot/lib/session.g line 93
    BreakOnError := false;
                  ^
#W  global variable 'LineEditKeyHandlers' has not been defined
#W  global function 'LineEditKeyHandler' has not been defined
Segmentation fault
-bash-3.2$ 
```

**Comment by rbehrends** [comment]
The point where it breaks can be figured out as follows:

1. Run `bin/current/gap` from gdb. 
2. Set a breakpoint on `CallErrorInner` (`break CallErrorInner`).
3. Run the program with `r` (add GAP options if necessary, e.g. `r -A -r`).
4. Check out the current file and line via `TLS->input`, e.g.:
    * `p (char *)TLS()->input->name`
    * `p TLS()->input->number`

Note that depending on gdb version and a few other things, `TLS()` may not be usable from `p`. In this case, use the patch in https://github.com/gap-system/gap/pull/120 so that you can use `DBG_TLS()` instead.

**Comment by alex-konovalov** [comment]
Thanks for detailed instructions, @rbehrends! Indeed, I had to use `DBG_TLS()` there. The first error is reported at line 362 of `system.g`, which is just the last line of `CallAndInstallPostRestore`.

**Comment by alex-konovalov** [comment]
Ok, that's what's going on: when `CallAndInstallPostRestore` is called, there are lines like
```
    # On 32-bit we have to adjust some values:
    if GAPInfo.BytesPerVariable = 4 then
      i := 1;
      while not(IsBound(GAPInfo.CommandLineOptionData[i])) or
            GAPInfo.CommandLineOptionData[i][1] <> "m" do i := i + 1; od;
      GAPInfo.CommandLineOptionData[i][2] := "64m";
...
```
but since `GAPInfo.CommandLineOptionData`, this does not work. The condition `GAPInfo.BytesPerVariable = 4 ` explains why we do not see it on most of our testing platforms.

The fix would be to make a copy of `GAPInfo.CommandLineOptionData`, tweak it and then replace the original list and make it immutable. `ShallowCopy` is not available at this stage of loading GAP, so one would have to copy the list piecewise. I will work on the fix.

**Comment by alex-konovalov** [comment]
Ah, `SHALLOW_COPY_OBJ` is available - that makes it easier!

**Comment by alex-konovalov** [comment]
Submitted PR #138 to fix this.

**Comment by alex-konovalov** [comment]
As a follow-up, Windows version now shows the `Loading the library and packages ...` message and then terminates - behaviour observed since July 2014. I will create a new issue for that.
