### ISSUE TITLE
Proposal: Kernel debugging

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#1200]
This is a proposal for kernel-level debugging in GAP. Various existing macros will be wrapped up under these options. This is inspired by gcc's checking framework.

**In the documentation of ./configure**

`--enable-checking`
`--enable-checking=list`
    When you specify this configuration option, GAP enables extra internal checks. List is a comma separated list of categories, which can currently contain `basic`, `gasman` and `gasmanextra` (this list may expand). The default when `list` is missing is `basic, gasman`. By default, all options will be enabled which do not slow GAP down significantly. `gasmanextra` can make GAP VERY slow (take several minutes to start).

    GAP packages may have to be rebuilt when `--enable-checking` is enabled, or changed.

**Internal implementation:**

For each option `X` to `--enable-checking`, GAP will define a macro called `GAP_CHECK_X` in `config.h`.

In a header called `debug.h`, for each option `X` GAP will create an `assert`-like macro called `GAP_ASSERT_X`, which compiles to `assert` when checking of `X` is enabled, and to nothing when checking `X` is disabled.

`basic` will add sanity checking for many standard functions, for example the `PLIST*` and `PERM*` functions will check that they only operate on the right type of bag, and any references are within the bound of the bag. They will not check, for example, that a `PERM` forms a valid permutation (as this test can be very expensive).

**Comment by james-d-mitchell** [comment]
This sounds like a really good idea to me.

**Comment by markuspf** [comment]
This would also address #100

**Comment by ChrisJefferson** [comment]
Now done (or at least, something similar done!)
