### ISSUE TITLE
Task: get rid of hpcgap/doc

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1203]
There are still a handful of files left in `hpcgap/doc`:
```
ref:
extractexamples.g  language.xml  runexamples.g  testcoverage.g

tut:
extractexamples.g  runexamples.g
```
The diff in `language.xml` is genuine, it talks about `atomic` being a reserved keyword. I guess to merge this, we need to rewrite the text on the GAP side to mention HPC-GAP...

For the *.g files, it seems @alex-konovalov made the changes in 11f11ebc91cc9396a183903c8dceaaebd5046f72

**Comment by alex-konovalov** [comment]
Closed by #1897
