### ISSUE TITLE
Get rid of SyStopTime?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1214]
One set remaining HPC-GAP kernel diffs involves `SyStopTime`, which was removed in HPC-GAP, see 943bc26fa218541e147fadce4c2803ffa1e4edee

I wonder if we should just get rid of `SyStopTime` in GAP, too?

Perhaps somebody wants to run an experiment, and export `SyStopTime` to the GAP level, then run GAP for some time with various things, and see if it ever has a non-zero value?

**Comment by fingolfin** [comment]
@markuspf @ChrisJefferson any comments?

**Comment by markuspf** [comment]
I think we should remove `SyStopTime` from GAP.

**Comment by fingolfin** [comment]
Done in PR #1246 resp. 965c8b74f260dbd6becde654162b71cdf2b451f6
