### ISSUE TITLE
Complete merge of GAP and HPC-GAP kernels

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1216]
As I write this, `hpcgap/src` still contains 49 source and header files (in contrast to `src`, which contains about three times as many).

Our goal for now is to get rid of `hpcgap/src`, or at least of as much of it as possible, by unifying the two `src` directories. By now, most of the "trivial" unification work has been done. Next is a bunch of different things, which require different treatment... This issue here is meant to be the master issue for keeping track of these things. Details can be collected in separate issues, if necessary. 

So here is a list of some diffs and how we might resolve them. It is clearly incomplete; we can add to it over time.
* [x] The global `GlobalState` and `ThreadLocalStorage` structs need to be unified. This affects many files. For details, see https://github.com/fingolfin/gap/issues/106 -- @markuspf wanted to work on this.
* [ ] `c_*.c` - these files are generated by `gac` from their `lib/*.g` counterparts. I expect these to be among the last things to be synchronized. Ignore them for now.
* [x] Some profiling related diffs in `code.{c,h}` and `profile.c` (and possible elsewhere, including the library). @ChrisJefferson is probably best equipped to deal with this
* [x] Global variables: These were changed in a major way in HPC-GAP. @ChrisJefferson looked at this before.
* [x] Support for multi-arg lambdas was added in GAP but is not yet in HPC-GAP. Again @ChrisJefferson (who wrote this code) might be best equipped to look into this
* [x] In `iostream.c`, there are two diffs related to SIGCHLD -- that code was removed for HPC-GAP in a0242d78b207b91d96e395307ad5c01deafc6935 by @ChrisJefferson
* [x] in `scanner.c` the IO code was heavily modified; `GAPState` members `InputFiles` and `OutputFiles` were changed from arrays of structs to arrays of pointers of structs (see b59c4fc76b356a6914edccd680b740a1ccdab38f). I don't quite understand why, though... 
* [x] merge `stats.c`, see PR #1462

**Comment by markuspf** [comment]
I am working on this, I am just a bit impeded by teaching at the moment.

**Comment by fingolfin** [comment]
I essentially completed the merge of the kernel in PR #1462 resp. commit a92bdaa1309acde5eeaf7950567b15da32df0a90.

Of course there are still the generated `c_*.c` files, but for now, there is little we can do about them. At the same time, I think they are pretty much irrelevant, as they are generated -- the main urge to merge the kernel was to prevent the two kernels from getting out of sync. And that has been achieved.

Therefore, I am now closing this.
