### ISSUE TITLE
HPC-GAP may not compile due to missing backtrace support; make it conditional

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1217]
In order to debug some issues with HPC-GAP, I turned on `PRINT_BACKTRACE` unconditionally for HPC-GAP. However, this uses `backtrace_symbols_fd` which is not available on every OS.

So we should replace this HACK by something proper. Some things we could do:
1. Add an `--enable-backtrace` (or so) option to `configure`.
2. `configure` could check for the presence of`backtrace_symbols_fd` (perhaps only if `--enable-backtrace` is given; if the check fails, error out with a message saying something like `backtrace printing not supported`)
3. Even if built with backtrace support, a user may wish to enable or disable that, so we could also add a GAP command line option to turn it on/off. This is kind of optional, not sure we want it, but I thought I should mention it for completeness.

**Comment by fingolfin** [comment]
As mentioned on #1223, we also should add necessary flags, and perhaps use http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_execinfo.m4

**Comment by ChrisJefferson** [comment]
My preference would be (2). We want GAP to build, and leaving on the backtrace even in release would be (in my opinion) useful. People should never see it unless they find a serious bug in GAP, and it would give us more useful feedback if people do crash GAP.
