### ISSUE TITLE
InitCopyGVar doesn't understand thread-local variables

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#122]
`InitCopyGVar` is used to link C and GAP level variables. I think this doesn't understand thread-local variables, which upsets compiling. I'm not sure how to fix this -- it might be fundamentally incompatable with the way we currently do compiling (we would have to make the thread-local GAP variables into thread-local C variables, for a start). In that case, we might need some hack to get around this problem.

**Comment by rbehrends** [comment]
Yes, and unfortunately it's not trivial to handle. A workaround is to use `ThreadVar.x` instead of `x`, which is already used in a few places where using a thread-local variable directly causes or caused problems.

**Comment by ChrisJefferson** [comment]
Will `ThreadVar` work, or will it just get the same problem (I'll only capture `ThreadVar` once?)

My current plan is to change files we want to compile to use `VAL_GVAR` and `ASS_GVAR`. This forces correct dispatch, and we only use 3 thread local variables in these files, so it shouldn't add any overhead.

**Comment by rbehrends** [comment]
That would work, too. `ThreadVar` is a global variable that is guaranteed to always point to the thread-local record containing the thread-local variables and does not change (you can see in `ValAutoGVar()` how it works).

**Comment by ChrisJefferson** [comment]
Fixed this in another way, as described, thanks.
