### ISSUE TITLE
Split up `gap.c` (and possibly some other files)

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1220]
Right now, `gap.c` contains a grab bag of mostly unrelated functions. I'd like to many things out of it and into different (existing or new) files. Some examples:
* the timeout code could go into a new file `timeout.c`
* code related to Gasman could go into `gasman.c`; or if we want to keep that free from "GAP specific code", into a new companion file, e.g. `gasman_interface.c` or whatever
* error functions (and perhaps also UpEnv, DownEnv, ...) could go into an `error.c`
* `FuncTHREAD_UI` and other HPC-GAP specific stuff could go into a separate file for that... perhaps `src/hpc/thread_ui.c` ? Also two funcs from `stringobj.c` could go there: `FuncFIND_ALL_IN_STRING` and `FuncNORMALIZE_NEWLINES`
* ...

This would then also help with our HPC-GAP unification effort, as most of the new files would be in-sync already now.

**Comment by fingolfin** [comment]
@markuspf @ChrisJefferson any comments?

**Comment by markuspf** [comment]
No really more than "yes, lets do it, I have been itching to do so for a while".

While we're at it we can identify the things that make up the console UI (as in HPC-GAP the ThreadUI), and I can carefully try to move that out further, in preparation for a shared library version of GAP (in which gap.c should then be obsolete?).

**Comment by fingolfin** [comment]
The timeout code is gone; the error related stuff has been moved to `src/error.c`; module related things to `src/modules*`; at least some of the HPC-GAP specific were moved out, too. All in all, `src/gap.c` went from 3512 lines in GAP 4.8 down to 1877 lines. 

While there is more potential to move things to "better" places, I don't think we need to keep an issue open for this.
