### ISSUE TITLE
Add -lexecinfo to print backtraces

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#1223]
On my machine, to print backtraces, it is necessary to explicitly add `-lexecinfo` to the linker.

**Comment by markuspf** [comment]
http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_execinfo.m4

might be useful for this.

**Comment by fingolfin** [comment]
This is related to issue #1217

**Comment by fingolfin** [comment]
Merging this into #1217
