### ISSUE TITLE
Bug in either CommutatorFactorGroup or EpimorphismNilpotentQuotient

### ISSUE THREAD

**Issue by oantolin** [gap-system/gap#1232]
I think I found a bug when calculating the order of commutator factor groups of finitely presented group.

### Observed behaviour

```
gap> F := FreeGroup(2);
<free group on the generators [ f1, f2 ]>
gap> G := F / [F.1^8, F.1^2 * F.2 * F.1^(-1) * F.2^(-2)];
<fp group on the generators [ f1, f2 ]>
gap> Commutator := H -> Kernel(EpimorphismNilpotentQuotient(H,2));
function( H ) ... end
gap> [Index(G, Commutator(G)), Order(CommutatorFactorGroup(G))];
[ 8, 8 ]
gap> C := Commutator(G);
Group(<fp, no generators known>)
gap> [Index(C, Commutator(C)), Order(CommutatorFactorGroup(C))];
[ 135, 45 ]
```

### Expected behaviour

If I understood the documentation correctly, the function `Commutator` I defined should compute the subgroup generated by commutators, in which case the index of `Commutator(H)` in `H` should always equal the order of the commutator factor group. In the above transcript, this is verified for the group `G`, but fails for the commutator subgroup `C`.

### Copy and paste GAP banner (to tell us about your setup)

```
 ┌───────┐   GAP 4.8.3, 19-Mar-2016, build of 2017-01-12 19:41:17 (UTC)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-unknown-linux-gnu-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
 Packages:   Alnuth 3.0.0, AtlasRep 1.5.0, AutPGrp 1.6, CTblLib 1.2.2, FactInt 1.5.3, GAPDoc 1.5.1, LAGUNA 3.7.0, Polycyclic 2.11, TomLib 1.2.5
 Try '?help' for help. See also  '?copyright' and  '?authors'
```

**Comment by hulpke** [comment]
Not a bug. The defined function finds the kernel of the largest class 2 nilpotent quotient. This can (as for G) be the derived subgroup, but (as for C) can be smaller.

**Comment by oantolin** [comment]
Oh, I'm off by one on what nilpotency class means (yet again)! So nilpotency class 1 is abelian (and nilpotency class 2 means all commutators are central).

Sorry for wasting your time. Please close or delete this issue add you see fit.
