### ISSUE TITLE
Bugs with 0-generated objects

### ISSUE THREAD

**Issue by laurentbartholdi** [gap-system/gap#1238]
There is a bug in the handling of 0-generated monoids:

`IsFpMonoid(FreeMonoid(0)/[])` returns `false`.

The problem is that GAP constructs a free group on 0 generators, rather than a free monoid. They're isomorphic, but then GAP doesn't know that FP groups are also FP monoids.

**Comment by markuspf** [comment]
I assume you are testing this on the `stable-4.8` branch?

On master I get the following:

```
gap> FreeMonoid(0);
<free monoid on the generators [  ]>
gap> IsFpMonoid(FreeMonoid(0) / []);
true
```

This is most likely because of https://github.com/gap-system/gap/pull/950.

Please do not conflate separate bugs in the same issue; the second one is an entirely separate bug, I will move it to a new issue.

**Comment by fingolfin** [comment]
This isn't an issue in GAP 4.9.
