### ISSUE TITLE
segmentation faults in make testmanuals 

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#126]
Just to inform that `make testmanuals` now shows segmentation faults in many chapters. I've narrowed this down to Jenkins build at 6pm on March 19 th running fine and another Jenkins build at 9.36am on March 20th showing the problem. 

This is another example which is hard to reproduce. If you run `make testmanuals`, the log in `dev/log` directory shows reproducible segfaults at same chapters each time. However, trying to extract examples to run them using `Test`, even with assertion level 2, does not trigger the bug at all. 

Finally, I've found a way to reproduce it. Workspace is involved. Create a test file `bug.tst` with the following lines:
```
gap> s8 := Group( (1,2), (1,2,3,4,5,6,7,8) );
Group([ (1,2), (1,2,3,4,5,6,7,8) ])
gap> a8 := DerivedSubgroup( s8 );
Group([ (1,2,3), (2,3,4), (2,4)(3,5), (2,6,4), (2,4)(5,7), 
  (2,8,6,4)(3,5) ])
gap> IsNaturalAlternatingGroup(a8);
true
gap> a8;
Alt( [ 1 .. 8 ] )
gap> syl2 := SylowSubgroup( a8, 2 );; Size( syl2 );
64
gap> Normalizer( a8, syl2 ) = syl2;
true
```
Then load GAP with `-r -A` and save workspace as `test.wsp`. After that load GAP from that workspace with `-r -A -L test.wsp` and try to perform the test:
```
gap> Test("~/Desktop/bug.tst");
Segmentation fault: 11
```

**Comment by ChrisJefferson** [comment]
Is this gap or hpcgap?

**Comment by alex-konovalov** [comment]
This is GAP, master branch.

**Comment by ChrisJefferson** [comment]
The problem is that the following lines in LoadLibrary, objscoll.c don't get called again, so these variables aren't setup

```
    SCOBJ_NW_STACK_GVAR = GVarName( "SCOBJ_NW_STACK" );
    SCOBJ_LW_STACK_GVAR = GVarName( "SCOBJ_LW_STACK" );
    SCOBJ_PW_STACK_GVAR = GVarName( "SCOBJ_PW_STACK" );
    SCOBJ_EW_STACK_GVAR = GVarName( "SCOBJ_EW_STACK" );
    SCOBJ_GE_STACK_GVAR = GVarName( "SCOBJ_GE_STACK" );
    SCOBJ_CW_VECTOR_GVAR = GVarName( "SCOBJ_CW_VECTOR" );
    SCOBJ_CW2_VECTOR_GVAR = GVarName( "SCOBJ_CW2_VECTOR" );
    SCOBJ_MAX_STACK_SIZE_GVAR = GVarName( "SCOBJ_MAX_STACK_SIZE" );
```

Is there a way of making a function which gets called on workspace restore? If so, that would easily fix it.

**Comment by ChrisJefferson** [comment]
Found it (hopefully), postrestore is what I wanted.

**Comment by alex-konovalov** [comment]
Thanks! Good that we use workspaces to speed up regression tests :) Travis tests of your PR went well, but manual examples are not tested there - let's merge the PR and see how far Jenkins fares.
