### ISSUE TITLE
HPC-GAP: Send hpcgap/pkg-diffs/automata-2015-11-18.diff to upstream

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1271]
The changes in https://github.com/gap-system/gap/blob/master/hpcgap/pkg-diffs/automata-2015-11-18.diff should be sent to upstream, and a new release be requested.

**Comment by alex-konovalov** [comment]
Step one would be to liaise with its authors and establish a repository under https://github.com/gap-packages

**Comment by fingolfin** [comment]
I have already exchanged numerous emails about this with the authors, it is planned.

**Comment by fingolfin** [comment]
Pinging @ManuelAFDelgado and @stevelinton (also notified via separate email)
