### ISSUE TITLE
Clarify GAP licensing terms: GPL 2 or later; in particular, GPL 3 is OK

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1273]
GAP has been licensed under the "GPL 2 or later" for a long time. Indeed, `doc/ref/copyrigh.xml`  says so. (Off-topic: can we rename that file to `copyright.xml`, please?)

But this is not so clear when looking at other places. For starters, I think our `README.md` should explicitly state the license (using similar verbiage as in the manual), and state some copyright.

We might also want to add this in other places, not sure where, though.

BTW, I just noticed we have text like "Copyright © (1987-this year)" -- I am pretty sure that's not legally valid *shrug*.

**Comment by alex-konovalov** [comment]
About "this year" - this is in the development version. When the release is made, `<!ENTITY RELEASEDAY "today">` and `<!ENTITY RELEASEYEAR "this year">` in ` doc/versiondata` are replaced by the actual dates by the `updateversioninfo` script (see https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/updateversioninfo).

**Comment by ChrisJefferson** [comment]
Just following this up, there doesn't seem to be any complaints, so i think we should just clean this up, for clarification.

I'm sure `copyrigh.xml` is an old 8.3 filename, and seeing as GAP doesn't compile on any such OSes, I'm sure we can change it.

**Comment by fingolfin** [comment]
I think this is really important for GAP 4.9 and quite easy to do.

**Comment by fingolfin** [comment]
Working on this now.
