### ISSUE TITLE
RemoveCopyFopyInfo in hpcgap/src/gvars.c is nonsense

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1280]
GCC produces the following warnings (among others):
```
../../hpcgap/src/gvars.c: In function ‘RemoveCopyFopyInfo’:
../../hpcgap/src/gvars.c:1203:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     l = LEN_PLIST(CopiesGVars);
     ^
../../hpcgap/src/gvars.c:1206:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     l = LEN_PLIST(FopiesGVars);
     ^
```
Upon inspecting the code in question, I think it is bogus:
```
void RemoveCopyFopyInfo( void )
{
    UInt        i, l;

    LockGVars(1);
    l = LEN_PLIST(CopiesGVars);
    for ( i = 1; i <= l; i++ )
        SET_ELM_PLIST( CopiesGVars[GVAR_BUCKET(i)], GVAR_INDEX(i), 0 );
    l = LEN_PLIST(FopiesGVars);
    for ( i = 1; i <= l; i++ )
        SET_ELM_PLIST( FopiesGVars[GVAR_BUCKET(i)], GVAR_INDEX(i), 0 );
    NCopyAndFopyDone = 0;
    UnlockGVars();
    return;
}
```
Note that in HPC-GAP, `CopiesGVars` and `FopiesGVars` are *arrays* of `Obj` objects, so `LEN_PLIST(CopiesGVars)` (the code the compiler warns about) indeed makes no sense. Moreover, I think `CopiesGVars[GVAR_BUCKET(i)]` really makes no sense either.

I have not yet looked closer at how the rewritten gvar code in HPC-GAP works, which is why I am not trying to fix this. My guess is that the two loops each need to be replaced by something like this:
```
  for (k = 0; k < ARRAY_SIZE(CopiesGVars); ++k) {
    l = LEN_PLIST(CopiesGVars[k]);
    for ( i = 1; i <= l; i++ )
        SET_ELM_PLIST( CopiesGVars[k], i, 0 );
  }
```
Then again, this might still be wrong or even nonsense; in any case, something needs to be changed there.

**Comment by fingolfin** [comment]
@rbehrends Any comments?

**Comment by rbehrends** [comment]
The modified loop needs to abort early if `CopiesGVars[k]` is null, but otherwise seems correct. The pointers can be null, as we're creating the extra buckets only on demand.

I think the code was an unfinished conversion of the original version (where `CopiesGVars` and `FopiesGVars` were just plain lists). It never showed up during testing, because the function is only called prior to workspace saving, which doesn't work for HPC-GAP.

**Comment by rbehrends** [comment]
Actually, to update my earlier comment, the loop shouldn't abort early, but just skip null entries, as there can be "holes" in the array.

**Comment by fingolfin** [comment]
So you mean like this?
```C
for (k = 0; k < ARRAY_SIZE(CopiesGVars); ++k) {
    if (CopiesGVars[k] == 0)
        continue;
    l = LEN_PLIST(CopiesGVars[k]);
    for ( i = 1; i <= l; i++ )
        SET_ELM_PLIST( CopiesGVars[k], i, 0 );
  }
```

**Comment by rbehrends** [comment]
That looks about right, yes.
