### ISSUE TITLE
`SetPrintFormattingStatus( "*stdout*", false );` does not quite work

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1308]
This happens with master and originally comes from here: http://stackoverflow.com/questions/43833333

If one puts
```gap
SetPrintFormattingStatus( "*stdout*", false );
Print( Primes{[1..30]}, "\n" );
```
into a file `test.g` and then runs it via `gap test.g`, then output formatting is not actually ignored, and so line breaks are inserted.

**Comment by markuspf** [comment]
The problem here is that `*stdout*` is opened multiple times and the `SetOutputFormattingStatus` call sets the wrong stream's formatting bit. I am working on a fix.
