### ISSUE TITLE
Compiler Warnings (Apple LLVM)

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#1320]
After recent updates (both of xcode and of course of GAP) when compiling, I now get a large number of warnings of the type:

src/gap.c:3156:9: warning: missing field 'nargs' initializer [-Wmissing-field-initializers]

The offending line is { 0 } and thus

http://stackoverflow.com/questions/13373695/how-to-remove-the-warning-in-gcc-4-6-missing-initializer-wmissing-field-initi

makes me believe that it is a compiler quirk. Is this something the build process needs to be aware of?

**Comment by fingolfin** [comment]
This is my fault. I only checked warning with GCC, not clang. I'll take care of it.

**Comment by hulpke** [comment]
This seems to have been fixed by #1321
