### ISSUE TITLE
Compiler Warning with gcc 5.4.1

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#1329]
With my GCC I get the following warning

```
cc1: warning: unrecognized command line option '-Wno-implicit-fallthrough'
```

```
➤ gcc --version
gcc 5.4.1 [DragonFly] Release/2016-08-27
```

**Comment by fingolfin** [comment]
I cannot reproduce this with my GCC 5.4.0 According to the GCC documentation, the default since GCC 4.4 was to have `-Wno-unknown-warning` active. So for some reasons DragonFly override this default *sigh*. But OK, we can just explicitly add `-Wno-unknown-warning`
