### ISSUE TITLE
More src/sysfile warnings

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#1345]
I am not sure if these were intentional, but since #1339 I receive these warnings at compilation: 
````
src/sysfiles.c: In function ‘SyLoadModule’:
src/sysfiles.c:425:13: warning: ISO C forbids conversion of object pointer to function pointer type [-Wpedantic]
     *func = (InitInfoFunc) init;
             ^
src/sysfiles.c: At top level:
cc1: warning: unrecognized command line option "-Wno-unknown-warning-option"
cc1: warning: unrecognized command line option "-Wno-implicit-fallthrough"
````
GAP seems to compile and run properly, though. The version for cc is:
````
ghorvath@DesktopPC:~/work/gap$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10) 
````

**Comment by fingolfin** [comment]
I am not sure what you mean with "intentional", but I am certainly aware of this warning. The code is perfectly valid, though, and the warning pointless.

There is no really good way to avoid it, though. We could
* drop the `-pedantic` flag
* use `#pragma` directives to disable the warning before the `dlsym` call and enable it afterwards again
* just live with it
* ... ?

**Comment by ChrisJefferson** [comment]
There are two ways I know of to shut this warning up (warning, not compiled this, but I believe they are right). If someone could test them, that would be helpful.

```(InitInfoFunc)(size_t) init;```

or (longer)

```
struct FuncPtrWrapper { InitInfoFunc funcptr; };
func = (*(struct FuncPtrWrapper*)(&init)).funcptr;
```

**Comment by fingolfin** [comment]
I'd strongly advise against that! At least POSIX discusses the legitimacy of casting function pointers to `void *` and back (see e.g. <http://pubs.opengroup.org/onlinepubs/009695399/functions/dlsym.html>). But casting function pointers to anything else is entirely undefined. So, we'd be replacing code which is formally violating ISO C, but considered to be correct in some other standards, by code which is not. Indeed, a `size_t` may not even be able to store a pointer.

Of course, both of your code snippets, as well as the code that are currently in GAP, in practice do work on all current systems. But that is kind of besides the point, IMHO.

**Comment by ChrisJefferson** [comment]
In that case, I'd probably drop `-pedantic`. It doesn't do a lot anyway, and I don't think we care about being "pure C" (and aren't anyway).

**Comment by fingolfin** [comment]
I'd be fine with dropping `-pedantic`.
