### ISSUE TITLE
Unconditionally using compiler warning flags causes gcc 4.3.4 compile failure

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#1346]
On a supercomputer I am allowed to use compilation stops:
````
DEBRECEN[service0] ~/bin/gap (0)$ make
   C       src/ariths.c => obj/ariths.lo
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough"
cc1: error: unrecognized command line option "-Wno-unknown-warning-option"
make: *** [obj/ariths.lo] Error 1
DEBRECEN[service0] ~/bin/gap (2)$ cc -v
Using built-in specs.
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.3 --enable-ssp --disable-libssp --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --program-suffix=-4.3 --enable-linux-futex --without-system-libunwind --with-cpu=generic --build=x86_64-suse-linux
Thread model: posix
gcc version 4.3.4 [gcc-4_3-branch revision 152973] (SUSE Linux) 
DEBRECEN[service0] ~/bin/gap (2)$ 
````
The number in parentheses in the prompt is supposed to show the error code (2 in this case).

Could this be because of #1339?

**Comment by fingolfin** [comment]
please run `make V=1` and show us the outputnof that.

**Comment by hungaborhorvath** [comment]
````
DEBRECEN[service0] ~/bin/gap (0)$ make V=1
/bin/sh ./libtool --mode=compile gcc -std=gnu99 -MQ "obj/ariths.lo" -MMD -MP -MF "obj/.deps/ariths.d"  -I/opt/nce/packages/global/python/2.7.5/include/python2.7   -I. -DHAVE_CONFIG_H     -Wall -Wextra -pedantic -Wshadow -Wno-unused-parameter -Wno-sign-compare -Wno-implicit-fallthrough -Wno-unknown-warning-option  -c src/ariths.c -o obj/ariths.lo
libtool: compile:  gcc -std=gnu99 -MQ obj/ariths.lo -MMD -MP -MF obj/.deps/ariths.d -I/opt/nce/packages/global/python/2.7.5/include/python2.7 -I. -DHAVE_CONFIG_H -Wall -Wextra -pedantic -Wshadow -Wno-unused-parameter -Wno-sign-compare -Wno-implicit-fallthrough -Wno-unknown-warning-option -c src/ariths.c  -fPIC -DPIC -o obj/.libs/ariths.o
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough"
cc1: error: unrecognized command line option "-Wno-unknown-warning-option"
make: *** [obj/ariths.lo] Error 1
DEBRECEN[service0] ~/bin/gap (2)$ 
````
The number in parentheses is supposed to show the error code (2 in this case).

**Comment by fingolfin** [comment]
It's weird that the compiler would choose to treat this warning as an error. Hm.

**Comment by ChrisJefferson** [comment]
This is just an old gcc problem, it was 4.4 (I think) before gcc started ignoring unknown warnings.

**Comment by fingolfin** [comment]
OK. Well, we could do multiple things then (possibly in combination):
* add a `--disable-extra-warnings` switch to configure
* ... or the opposite: `--enable-extra-warnings` (but I'd prefer to have warnings on by default, to encourage people to avoid them)
* add a check to detect whether the compiler supports the given warning flags. However, doing this beyond "the compiler still manages to produce working code with the warnings present" is tricky, i.e. detecting extras like "warning: option XYZ is not supported" isn't really possible this way
* add checks to explicitly detect compilers that are known to support a given warning flag (i.e. "GCC newer than X.Y" or "clang newer than X.Y"). Of course this goes directly against the fundamental autoconf principle of detecting features, not hardcoding mappings from software versions to features (a principle I wholeheartedly agree with); alas, sometimes pragmatism has to win over principles
* the reverse: add checks to explicitly detect compilers known to *not* support a feature
* ... other ideas?

BTW, I wonder if we can setup a system were we can test compile with older GCC and clang versions, and perhaps more "exotic" compilers like Intel's icc?

**Comment by ChrisJefferson** [comment]
I'd like to add one more thing -- when we make releases, disable all warnings (the false positives will be more annoying than any real positives I believe).

Also, I don't know autoconf, but can we check if running with flags outputs anything at all to stderr or stdout, in a little test file?

**Comment by fingolfin** [comment]
Anything you can do with a shell script, you can do with autoconf. So of course you can do that. But it may not be meaningful. E.g. GCC these days only shows warnings about unknown options if it is going to print any other kind of diagnostics anyway. So you'd not see those warnings unless you deliberately triggered a diagnostic - which defeats the purpose...

**Comment by ChrisJefferson** [comment]
@fingolfin : Well, at least people wouldn't see messages in a "clean" build, as you say, nothing's perfect here unfortunately.

**Comment by fingolfin** [comment]
We may also want to look into using <https://www.gnu.org/software/autoconf-archive/ax_compiler_flags_cflags.html> resp. adapting it for our uses.

**Comment by hungaborhorvath** [comment]
@fingolfin I guess it might be related so I am posting here instead of n another issue. 

On a supercomputer where a week ago gap still compiled properly now I get this:
````
   C       src/gap.c => obj/gap.lo
cc1: warnings being treated as errors
In file included from src/gap.c:81:
./src/stats.h: In function ‘EXEC_STAT’:
./src/stats.h:55: error: declaration of ‘stat’ shadows a global declaration
/usr/include/sys/stat.h:455: error: shadowed declaration is here
In file included from src/gap.c:96:
./src/hookintrprtr.h: In function ‘VisitStatIfHooked’:
./src/hookintrprtr.h:150: error: declaration of ‘stat’ shadows a global declaration
/usr/include/sys/stat.h:455: error: shadowed declaration is here
At top level:
cc1: error: unrecognized command line option "-Wno-unknown-warning-option"
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough"
make: *** [obj/gap.lo] Error 1
````
On this computer ````cc -v```` gives this:
````
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) 
````
