### ISSUE TITLE
Add configure options to make use of existing GAP kernel debugging flags

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1356]
There are several useful GAP kernel debugging flags, e.g. `MEMORY_CANARY` for GASMAN makes it possible to use valgrind with GAP effectively. It would be nice if these were more "developer visible" and documented. Towards that end, perhaps we can added configure options to enable each of them. Here is an (probably incomplete) of such flags:

* [ ] `CHECK_FOR_CLASH_IN_INIT_MARK_FUNC`
* [ ] `CHECK_FOR_CLASH_IN_INIT_SWEEP_FUNC`
* [ ] `CHECK_NDENSE_BAGS`
* [ ] `CHECK_TL_ASSIGNS`
* [ ] `CHECK_NDENSE_BAGS`
* [ ] `DEBUG_FUNCTIONS_BAGS`
* [ ] `DEBUG_GLOBAL_BAGS`
* [ ] `DEBUG_GMP`
* [ ] `DEBUG_HANDLER_REGISTRATION`
* [ ] `DEBUG_LOADING`
* [ ] `DEBUG_MASTERPOINTERS`
* [ ] `DEBUG_RATIONALS`
* [ ] `MEMORY_CANARY` -> perhaps `--enable-valgrind`?
* [ ] `TRACEFRAMES`

**Comment by ChrisJefferson** [comment]
Some of these can probably just be put under `GAP_ASSERT`, like `CHECK_FOR_CLASH_IN_INIT_MARK_FUNC` (which checks one function is called only very rarely).

Others could hopefully be put into groups. Long term (with some benchmarking) my preference would be to aim for something like gcc's debugging, with a small set of options, where the options are required just because some checks are very expensive.

Here is a suggested piece of documentation, based on gcc's:

```
-enable-debug=list
When you specify this option, GAP performs various extra checks. This should never change the behaviour of GAP, except when an internal error occurs. This will slow down GAP. The default option is `assert`, which turns on some basic assertions. You can also choose `all` (all but `valgrind` and `canary`) or `none` (no checks). Individual checks are enabled with `assert` (general assertions), `gc` (checks involving garbage collection), `numbers` (checks involving integers and rationals), `extra` (checks which are known to be very slow), `canary` (a special checker for the memory manager, which is VERY slow).

‘valgrind’ does not add any explicit checks, but makes changes to GAP to make it work better with the external valgrind simulator, available from http://valgrind.org/. The `extra` and `valgrind` checks are very expensive. `canary` is EXTREMELY expensive.
```

**Comment by ChrisJefferson** [comment]
This is now done for useful flags
