### ISSUE TITLE
unity of finite fields

### ISSUE THREAD

**Issue by fchapoton** [gap-system/gap#1378]
Hello,
by working on sagemath ticket https://trac.sagemath.org/ticket/12073
I reached the following issue, which is somewhat annoying.

### Observed behaviour
gap> One(Z(5))=1*Z(5);
false

### Expected behaviour
gap> One(Z(5))=1*Z(5);
true

### Copy and paste GAP banner (to tell us about your setup)
This is the gap included in sagemath 8.0.beta9.
 ┌───────┐   GAP 4.8.6, 12-Nov-2016, build of 2017-06-01 10:21:32 (CEST)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Packages:   GAPDoc 1.5.1
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'

**Comment by markuspf** [comment]
This is the expected behaviour. `Z(5)` is the *generator* of the multiplicative group of `GF(5)` (as documented over [here](http://www.gap-system.org/Manuals/doc/ref/chap59.html#X7AA52FAF7EDEDD56) and certainly not the `One` of this field. `Z(5)^0` is what you want, and then you also get
```
gap> One(Z(5)) = Z(5)^0;
true
```
