### ISSUE TITLE
`FreeMagma` has unhelpful error messages, inconsistent argument checks, and can create incorrect 0-generator objects

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#1385]
First off this is a bug:
```
gap> FreeSemigroup();
Error, List Element: <list>[1] must have an assigned value in
  if IsFilter( arg[1] )  then
    lesy := arg[1];
    zarg := arg{[ 2 .. Length( arg ) ]};
else
    zarg := arg;
```

```
gap> F := FreeSemigroup([]);
<free semigroup on the generators [  ]>
gap> Size(F);
infinity
gap> e := Enumerator(F);
<enumerator of <free semigroup on the generators [  ]>>
gap> e[2];
^2
```

I would also argue that this is a bug (or at least an extremely unhelpful error message yet again)
```
gap> FreeMagma(0);
Error, usage: FreeMagma(<name1>,<name2>..),FreeMagma(<rank>) at /home/makx/dev/gap/lib/mgmfree.gi:316 called from
<function "FreeMagma">( <arguments> )
 called from read-eval loop at *stdin*:7
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk>
```

Though it is documented that the rank has to be positive, but why should there not be a `FreeSemigroup(0)` (which would be empty)? 

I can fix most of this, just leaving it here for me to remember. (of course I welcome people beating me to it)

**Comment by wilfwilson** [comment]
This has been resolved for `FreeSemigroup`s in #4372.

I will work on a similar fix for `FreeMagma` (and `FreeMonoid` and `FreeMagmaWithOne`, if they have similar problems). 

I have added a feature request in #4424 to see about properly supporting these objects with zero generators.
