### ISSUE TITLE
`Difference' returns range in memory-wasting representation

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#1416]
### Observed behaviour

gap> Difference([1..10^15],[10^15]);
gap: cannot extend the workspace any more!

### Expected behaviour

gap> Difference([1..10^15],[10^15]);
 [ 1 .. 999999999999999 ]

### Copy and paste GAP banner (to tell us about your setup)

 ┌───────┐   GAP 4.8.7, 24-Mar-2017, build of 2017-03-31 17:24:56 (CEST)
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp
 Loading the library and packages ...
 Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
 Packages:   GAPDoc 1.5.1

**Comment by fingolfin** [comment]
There are no custom methods for `Difference` and ranges, so it ends up converting the range into a list, which of course runs out of memory.

I guess one could teach `Difference` about ranges (say by installing additional methods), though I am not sure how useful that would be in practice (you'd still not be able to do, say `Difference([1..10^15],[42]);`)

**Comment by Stefan-Kohl** [comment]
Well -- adopting "ResClasses style", in a good enough implementation we could have either

gap> Difference([1..10^15],[42]);
[ 1 .. 41 ] U [ 43 .. 1000000000000000 ]

or

gap> Difference([1..10^15],[42]);
[ 1 .. 1000000000000000 ] \ [ 42 ]

and there would be a heuristic which would decide when it gets most efficient to convert to a plain list.

**Comment by fingolfin** [comment]
Of course we could support "ranges with holes" or "unions of ranges" -- but I think this goes way beyond what a general purpose CAS should provide. It adds a lot of code complexity, and which representation is "best" will depend on use cases. And tons and tons of code would have to be adapted to deal with such "lists", would have to be carefully reevaluate so as to not accidentally convert them into a different representation, etc.
And that for a feature which 99% or so of all use cases don't need at all.

Hence I think it's better to leave such "advanced" things to packages that actually need them.

**Comment by fingolfin** [comment]
I don't think we'll implement this. But of course patches are welcome.
