### ISSUE TITLE
HPC-GAP crashes on Windows

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#143]
This is a follow-up of #118. 

Presently, HPC-GAP compiles under Cygwin, but then an attempt to start it with `bin/gap.sh -r -A -S tst/testinstall.g` fails after displaying `Loading the library and packages ...` messages. 

I will try to log in into the Jenkins Windows slave and get further details.

**Comment by alex-konovalov** [comment]
In the meantime, things became more stable here: under Windows, `bin/gap.sh -r -A -S tst/testinstall.g` results in "Error, Cannot lock required regions" in `lib/mapping.gi` almost each time.

**Comment by rbehrends** [comment]
I'm investigating this, but will have to look at on Windows under gdp; meanwhile, I've submitted a pull request that adds some assertions to region locking to verify that they are not being used wrongly (though I would be very surprised if any of them actually triggered).

**Comment by fingolfin** [comment]
I don't see a point in keeping this open.
