### ISSUE TITLE
Compiler warnings when compiling package with C++ compiler

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#1437]
I am getting a bunch of warnings like the following when compiling the Semigroups package:

 ```In file included from /home/travis/build/gap-packages/gap/src/system.h:27:0,
                 from /home/travis/build/gap-packages/gap/src/compiled.h:17,
                 from src/converter.h:25,
                 from src/semigrp.h:24,
                 from src/semigrp.cc:19:
/home/travis/build/gap-packages/gap/gen/config.h:334:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE /**/
<command-line>:0:0: note: this is the location of the previous definition
```
You can see this on travis:

https://travis-ci.org/gap-packages/Semigroups/jobs/243645478

**Comment by james-d-mitchell** [comment]
Perhaps @fingolfin has a suggestion to fix this?

**Comment by fingolfin** [comment]
The error message sounds as if you are passing `-D_GNU_SOURCE` to the compiler -- could you please give the compiler invocation leading to this warning, so we can verify?

In any case, we can probably stop defining this symbol globally, and instead only define it in the few files that need it (right now I can only think of `macfloat.c`).

**Comment by ChrisJefferson** [comment]
Whenever you compile c++ on a linux box, gcc/g++ automatically define `_GNU_SOURCE`.
