### ISSUE TITLE
Can we avoid irreducibility tests when creating algebraic extensions?

### ISSUE THREAD

**Issue by frankluebeck** [gap-system/gap#1458]
### Observed behaviour
In the following code
```
f0 := GF(13);
p1 := CyclotomicPolynomial(f0, 5);
f1 := AlgebraicExtension(f0, p1);
p2 := X(f1)^5 - RootOfDefiningPolynomial(f1);
f2 := AlgebraicExtension(f1, p2);
p3 := X(f2)^5 - RootOfDefiningPolynomial(f2);
f3 := AlgebraicExtension(f2, p3);
p4 := X(f3)^5 - RootOfDefiningPolynomial(f3);
f4 := AlgebraicExtension(f3, p4);
```
the creation of `f4` takes considerable time (>1 minute). The reason is that the irreducibility of the polynomial `p4` over `f3` is checked. But in the context I'm working in I know  that the polynomials I give to `AlgebraicExtension` are irreducible. Actually, should not every user who uses this function be sure about this? How can I avoid this unnecessary irreducibility check? I tried several tricks but without success.

### Expected behaviour
`AlgebraicExtension` should always be very fast.

**Comment by fingolfin** [comment]
Sounds to me like you are asking for / suggesting an NC variant. Seems quite plausible.

**Comment by frankluebeck** [comment]
For a pull request addressing this inefficiency (and some additional comments) see "Avoid irreducibility test in `AlgebraicExtension`" #1482.

**Comment by fingolfin** [comment]
Based on @frankluebeck's last comment, my impression is that this has been resolved and thus can be closed.

**Comment by frankluebeck** [comment]
To add a better cross-reference: this was resolved in "New 'AlgebraicExtensionNC' operation." (#1665).
