### ISSUE TITLE
Create and follow a "release checklist"

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1477]
It would be good if we had a "release checklist", like other biggish projects:

Such a checklist would contain all steps required to make a release. Really, *all* of them, from how and which mailing lists to notify when, what and how to tag, how to make tarballs, how and where to upload them, a list of sites or mailing lists to notify about the release etc. (for an example, see e.g. <http://wiki.scummvm.org/index.php/HOWTO-Release> which I created a decade ago).

This serves several purposes:

1.  To make sure knowledge is not lost, and thus to reduce the bus factor -- right now, I think only @alex-konovalov knows all of this, and if he is incapacitated, we have a problem. The other p
2. To make sure no steps are forgotten during a release (think of an airplan pilot's take-off checklist)
3. It allows auditing the whole process, and also allows identifying opportunities for improvements, such as extra steps which can be automated.

The closest to this I am aware of is https://github.com/gap-system/gap/wiki/GAP-release-workflow but this page is woefully incomplete, and I am pretty sure @alex-konovalov does not actually use it ;-).

UPDATE: @alex-konovalov has now a nice such checklist on <https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/RELEASE_CHECKLIST.md>

**Comment by alex-konovalov** [comment]
Needed action, and it was already in my plan. You're right that I am not actually using it. I use doc/dev manual and some other notes instead. I should take care of this issue - ideally while making the next release.

**Comment by alex-konovalov** [comment]
Not a full release checklist, but documentation for release wrapping scripts updated in Feb 2017 is at https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/README.md

**Comment by alex-konovalov** [comment]
I've started notes at https://github.com/gap-system/gap-distribution/wiki/Release-checklist, plan to expand them while publishing GAP 4.8.8 shortly.

**Comment by alex-konovalov** [comment]
https://github.com/gap-system/gap-distribution/wiki/Release-checklist has been expanded a lot while I've been publishing GAP 4.8.8. Maybe it now could be placed under version control in gap-distribution repository so that one could easier submit PRs to edit it.

**Comment by alex-konovalov** [comment]
The release checklist has been placed under version control here: https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/RELEASE_CHECKLIST.md. 

You can now comment on it on the commit https://github.com/gap-system/gap-distribution/commit/86283c6650c80b9098c56c29286e963c50c9c60e and submit pull requests with suggested modifications.

Will keep this issue open for a while to make more developers aware of the checklist and solicit comments.

**Comment by alex-konovalov** [comment]
I've followed this checklist in subsequent releases to validate it. Added some omissions and corrected some statements. It seems now in an adequate shape.
