### ISSUE TITLE
provide package installation interface

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#1499]
This is a proposal for relatively easy (at least for most cases at hand) to implement functionality that would allow installing GAP packages via a uniform interface provided by GAP, e.g. from the shell, by running something like `gap --install blah` or via a dedicated script (or from GAP prompt); one can as well think of `gap --install <URL>` for a non-standard package which can be found at `<URL>`. It would ideally also handle possibilities to get different versions, etc.

This is an alternative to the current hacky ways to build/install GAP packages.

People who are used to work with Python (or perl, or Haskell, or would instantly recognise this as something very similar to `pip install` (or the respective facility in the corresponding system).  Some CAs have such facilities, e.g. [Macaulay2](http://www.math.uiuc.edu/Macaulay2/) has `getPackage` command.

Apart from the end users, this would also simplify the issues faced by various software distributions (such as Linux distros, Sagemath, etc) that provide GAP.

Last but not the least, package developers might like this feature as a means of testing new versions of packages.

**Comment by ChrisJefferson** [comment]
I think many people would like something like this, but it is (obviously) a fairly major undertaking -- particularly because a bad implementation would be worse than nothing at all, and (unfortunately) obviously not research, so there aren't many people who have the time to spend on it.

Anyone who wants to work on this is welcome of course, I would love to see such a system exist.

**Comment by stevelinton** [comment]
One detail among many to consider is _which_ gap root the package should be installed into.

**Comment by dimpase** [comment]
On Sun, Jul 16, 2017 at 5:58 AM, Steve Linton <notifications@github.com>
wrote:

> One detail among many to consider is *which* gap root the package should
> be installed into.
>

Isn't a GAP invocation meant to know its root?
Although yes indeed, is there an exposed functionality to get its value?

**Comment by ChrisJefferson** [comment]
A gap invocation can have several roots. This is useful, because it allows users to install packages in their home directory, in global installs the 'pkg' directory of your gap install may well not be writable.

**Comment by dimpase** [comment]
Right, I confused the place where the main part of GAP installation lives (does it have a proper name in GAPpish?) with the place(s) where packages live.

**Comment by fingolfin** [comment]
@mtorpey has been working on a Package manager; he'll announce more about it when he feels it is ready for broader consumption.

**Comment by slel** [comment]
The `PackageManager` GAP package seems to solve this issue, maybe it can be closed.
