### ISSUE TITLE
Add RegisterTNUM functionality

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#15]
This actually came up in a discussion on the [io package](https://github.com/gap-system/io). @fingolfin suggested that we add functionality for packages to register TNUMs. I will paste the jist of the discussion here for reference. I'd implement and pull-request this, if @fingolfin doesn't already have code for this.

This will enable a clean solution to a global variable problem in io (and probably elsewhere).

**This is from [io issue 4](https://github.com/gap-system/io/issues/4)**
> We do this already in the packages [SingularInterface](https://github.com/gap-system?/SingularInterface) (formerly "libsing") and [NormalizInterface](https://github.com/fingolfin/NormalizInterface). The way this is done right now is the following: For each package that needs it, a TNUM is reserved (SingularInterface uses `T_SINGULAR`; NormalizInterface currently uses T_SPARE1; and there is also `T_POLYMAKE`, but I think it is not in use right now).

> GAP itself never creates objects (or rather, "bags") with these TNUMs, but external packages do this. The cool thing about this is that it allows those external packages to do proper memory management, as the GAP garbage collector GASMAN provides hooks for this, set via `InitFreeFuncBag` and `InitMarkFuncBags`. With this, wrapping e.g. C++ objects becomes relatively easy; the code for NormalizInterface is rather short, see [normaliz.cc](https://github.com/fingolfin/NormalizInterface/blob/master/src/normaliz.cc).

> This system is not perfect, but works reasonably well. The only problem is that it currently requires a modification to the GAP kernel for each package that wants to do this. This is clearly a problematic model that does not scale well. And I really hope it will have to scale, as I'd like to see wrappers for e.g. libcurl (full-blown HTTP client support), libz/libzlib/libarchive (various libraries for dealing with compressed files or even archives), pcre (or any other regular expression library), GMP (exposing the high-level GMP functions, which we currently can't use in GAP -- this should be rather easy to achieve, and I'd like to do it in a way that integrates well with SingularInterface and NormalizInterface).

> The simplest ad-hoc solution for this is to reserve a bunch of TNUMs for packages and let packages register a TNUM. I have been using this internally for quite some time now, and it boils down to a rather short code change, essentially this (plus some header modifications):
> ```
> static Int lastFreePackageTNUM = FIRST_PACKAGE_TNUM;
> 
> /****************************************************************************
> **
> *F  RegisterPackageTNUM( <name>, <typeObjFunc> )
> **
> **  Allocates a TNUM for use by a package. The parameters <name> and
> **  <typeObjFunc> are used to initialize the relevant entries in the
> **  InfoBags and TypeObjFuncs arrays.
> **
> **  If allocation fails (e.g. because no more TNUMs are available),
> **  a negative value is returned.
> */
> Int RegisterPackageTNUM( const char *name, Obj (*typeObjFunc)(Obj obj) )
> {
>    if (lastFreePackageTNUM > LAST_PACKAGE_TNUM)
>       return -1;
>
>    Int tnum = lastFreePackageTNUM++;
>
>    InfoBags[tnum].name = name;
>    TypeObjFuncs[tnum] = typeObjFunc;
>
>    return tnum;
>}
>```
>
>Packages then would call `RegisterPackageTNUM` from their `postRestore` function, like this:
>```
>extern Obj T_SINGULAR = 0;
>
>static Int PostRestore(StructInitInfo* module)
>{
>...
>    T_SINGULAR = RegisterPackageTNUM("singular wrapper object", _SI_TypeObj);
>    if (T_SINGULAR == -1)
>        return 1; /* signal an error */
>...
>```
> so that even workspaces should work, provided that packages are loaded in the exact same order as before. (To fix the latter constraint, one could store which TNUM was assigned to which  package; alas, for now I deemed it not worth the effort, as other things are likely to break when the load order changes, such as types get assigned which flag values etc. -- but it certainly would be possible to improve this).

> Note that I deliberately did not include a mechanism for querying TNUMs. This keeps the code very simple and makes it easy to keep it bug free, while not preventing packages from exchanging TNUM. For example, I imagine we'll have a GMPInterface package at some point, and both SingularInterface and NormalizInterface will want to use its "external GMP integers". Well, no problem, it can simply assign the TNUM integer value to a global gap variable, say `GMPINTERFACE_TNUM`, and then SingularInterface and NormalizInterface can use that

**Comment by markuspf** [comment]
After I merged this PR, I made a new package: https://github.com/gap-packages/RegisterPackageTNUMDemo

If anyone has any nice ideas what to do in the example package, I'm all ears.

**Comment by alex-konovalov** [comment]
@markuspf, what's the plan for the package then? Are you going to test it on your own and just provide here as a reference? I am not sure if it makes sense to deposit this package for the redistribution with GAP as a separate package, but IMHO it would have perfect sense to show how to use RegisterTNUM functionality in the Example package.

Disclaimer: at the moment, the official release of the Example package offers only an example of an external binary. There is also an example of the kernel module in the repository, which, however, is not yet released. We could work on this kernel module template during the next coding sprint, for example, and demonstrate how to use RegisterTNUM there.

Regarding this issue - should it be closed? Perhaps not, since the PR is merged, but the documentation is still missing. If we want this to be in the GAP 4.8 beta to be used by package authors, we do have to document it better.

**Comment by markuspf** [comment]
I have no opinion on where the code should go, as long as it is discoverable and not buried under more complicated other stuff.

The really simple code from this package could go in the Example package, and then we could write the GMP interface as a real demo (which then also serves a useful purpose)?

I am also not sure whether I am the best person to write any documentation on this by myself, since I obviously seem to think this stuff is self-explanatory.

**Comment by alex-konovalov** [comment]
@markuspf OK, then I don't mind closing this. It will be visible under the collection of issues for the milestone for GAP 4.8.0 at https://github.com/gap-system/gap/milestones/GAP%204.8.0
