### ISSUE TITLE
Inconsistent answer from slice with repeats

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#1500]
Consider the following code:

```
gap> x := [1..10];
[ 1 .. 10 ]
gap> x{[2,2,2,2]} := [1..4];
[ 1 .. 4 ]
gap> x{[2,2,2,2]};
[ 4, 4, 4, 4 ]
gap> x;
[ 1, 4, 3, 4, 5, 6, 7, 8, 9, 10 ]
```

The line which worries me is the second. `:=` is supposed to return "the result of the assignment", but here we can see (by comparison with line 3), that it has not. Now, I can think of several fixes for this. Unfortunately, they are all fairly costly.

* Ban repeated values in slices (obviously costly to check).

* Do some more work calculating the return value (annoying, as I suspect usually no-one wants it).

The "cheapest" option is to document that you shouldn't have repeats in slices, and that behaviour will be "unpredictable" if you do.

**Comment by stevelinton** [comment]
A better description of the return value is "the value assigned" which is the same in normal usages, but correct in this one. On the other hand having repeated values in slices is rarely correct and will make almost any fast method for slice assignment need special cases, so I'd definitely support making the outcome undefined in that case.

**Comment by stevelinton** [comment]
Where do we say that assignment returns "the result of the assignment"? I can't find this anywhere.

**Comment by fingolfin** [comment]
I also can't find anything like that in the manual.

@ChrisJefferson could you please clarify? Otherwise, I suggest simply closing this, as I don't see any contradictions in the documentation.

**Comment by ChrisJefferson** [comment]
This clearly isn't really interesting, so let's just close it.
