### ISSUE TITLE
intersection of two finite index subgroups of a free group leads to a crash on Windows

### ISSUE THREAD

**Issue by ignatsoroko** [gap-system/gap#1522]
### Observed behaviour

I am working with a free group F on two generators and form two subgroups: K of index 2304, and H of index 24. When I form their intersection U, any call such as Rank(U) or Index(F,U) leads to a crash. I am copying the code with the definition of F, K, H and U below. You can also see it in the attached file "ex-crash.txt" 
[ex-crash.txt](https://github.com/gap-system/gap/files/1161671/ex-crash.txt)

```gap
NormalCore:=function(F,L)
	local S,R,x,N;
	R:=List(RightCosets(F,L),x->Representative(x));
	S:=List(R,x->Image(ConjugatorAutomorphismNC(F,x),L));
	N:=Intersection(S);
	return N;
end;
F:=FreeGroup("a","b");
AssignGeneratorVariables(F);
T:=LowIndexSubgroupsFpGroup(F,4);
S:=Filtered(T,x->Index(F,x)=4);
L:=List(S,x->NormalCore(F,x));
K:=Intersection(L{[1..4]}); 
Index(F,K); 
H:=L[5];;
Index(F,H);
U:=Intersection(K,H);  
```

The "crash" means the following:
1) no message printed on the screen
2) GAP window closes
3) the file gap.exe.stackdump is created with contents:

Exception: STATUS_STACK_OVERFLOW at rip=0052A95DC89
rax=0000000000000018 rbx=0000000000000001 rcx=000006FF005A59E0
...
[many more lines]

### Expected behaviour

Everything seems to work well on Mac. Max Horn checked it in GAP 4.8.6 on Mac OS X 10.11 (both with and without any packages loaded), and got:
```
gap> Index(F,U);
27648
gap> Rank(U);
27649
```
So it is probably Windows memory allocation issue (or issue with my computer). Any ideas for a workaround?

### Copy and paste GAP banner (to tell us about your setup)

Command line:
start "GAP" C:\gap4r8_x86_64\bin\x86_64-unknown-cygwin-gcc-default64\mintty.exe -s 120,40 
```
 ┌───────┐   GAP 4.8.7, 24-Mar-2017, build of 2017-03-24 22:12:47 (GMTST)
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-unknown-cygwin-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.1, AutPGrp 1.8, Browse 1.8.6, CRISP 1.4.4, Cryst 4.1.12,
             CrystCat 1.1.6, CTblLib 1.2.2, FactInt 1.5.4, FGA 1.3.1, GAPDoc 1.5.1, IO 4.4.6, IRREDSOL 1.3.1,
             LAGUNA 3.7.0, Polenta 1.3.7, Polycyclic 2.11, RadiRoot 2.7, ResClasses 4.6.0, Sophus 1.23, SpinSym 1.5,
             TomLib 1.2.6, Utils 0.46
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap>
```

I also checked it on a 32-bit version of GAP 4.8.7 under Windows (with the standard installation parameters), with the same result (crash).

**Comment by fingolfin** [comment]
Thanks for the report!

I think the best course of action would be for someone with access to a debugger on Windows (just `gdb` might do it) run GAP in the debugger, and try to get a backtrace.

**Comment by wilfwilson** [comment]
With no packages loaded, on my Mac, I ran the above code with no problems, ending with `U:=Intersection(K,H);`. However I then ran `Index(F, U);` and `Rank(U)`, and got the following error:

```
gap> Index(F,U);
27648
gap> Rank(U);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 3rd choice method found for `IsPGroup' on 1 arguments at /Users/Wilf/GAP/lib/methsel2.g:250 called from
<compiled statement>  called from
<function "unknown">( <arguments> )
 called from read-eval loop at *stdin*:19
```

Is this perhaps related to the recent p-group changes?

```
gap> IsFinite(U);
false
gap> IsPGroup(U);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 3rd choice method found for `IsPGroup' on 1 arguments at /Users/Wilf/GAP/lib/methsel2.g:250 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at *stdin*:19
```

**Comment by ignatsoroko** [comment]
wilfwilson, this error is probably due to FGA package not loaded. It contains methods for dealing with free groups. 

Max Horn checked before and on Mac everything works fine (with FGA loaded). The error described above is Windows specific, as it seems.

**Comment by alex-konovalov** [comment]
Good news - I can reproduce this :) On Windows 8 with 32-bit and 64-bit GAP 4.8.8 and with 32-bit release candidate for GAP 4.9, starting GAP with `gap.bat`. Next, on Windows 7 machine with Cygwin, starting GAP with `gap.sh`, it crashes with `Segmentation fault (core dumped)` message. This is what is shown when I start GAP in gdb:
```
gap> Rank(U);
[Thread 5948.0xa20 exited with code 35584]
[Thread 5948.0x1608 exited with code 35584]
[Thread 5948.0x17c0 exited with code 35584]
[Thread 5948.0x130c exited with code 35584]
[New Thread 5948.0x9e4]
[Inferior 1 (process 5948) exited with code 0105400]
```
and
```
gap> Index(F,U);
[Thread 3148.0x750 exited with code 35584]
[Thread 3148.0x2e8 exited with code 35584]
[Thread 3148.0x15c8 exited with code 35584]
[Thread 3148.0x1464 exited with code 35584]
[Thread 3148.0x1620 exited with code 35584]
[Inferior 1 (process 3148) exited with code 0105400]
```

**Comment by alex-konovalov** [comment]
I've looked at `Rank(U)`. It boils down to `FreeGeneratorsOfGroup(U)`, which involves using FGA package. Now this worked:
```
gap> FreeGroupAutomaton(U);
<simple inverse automaton representation>
```
but this crashed:
```
gap> FGA_GeneratorsLetterRep(FreeGroupAutomaton(U));
```
Without FGA, I am observing the same problem which @wilfwilson mentioned, so disabling it does not seem to be a workaround.

Next, it calls `FGA_FindGeneratorsAndStates`, and that crashed at the very end when `SetFGA_States` is called. This is the full example:
```
LoadPackage("fga");
NormalCore:=function(F,L)
local S,R,x,N;
R:=List(RightCosets(F,L),x->Representative(x));
S:=List(R,x->Image(ConjugatorAutomorphismNC(F,x),L));
N:=Intersection(S);
return N;
end;
F:=FreeGroup("a","b");
AssignGeneratorVariables(F);
T:=LowIndexSubgroupsFpGroup(F,4);
S:=Filtered(T,x->Index(F,x)=4);
L:=List(S,x->NormalCore(F,x));
K:=Intersection(L{[1..4]});
Index(F,K);
H:=L[5];;
Index(F,H);
U:=Intersection(K,H);
A:=FreeGroupAutomaton(U);

    q := A!.initial;;
    nr := 0;
    Gens := [];
    q.repr := [];
    Q := [q];;

    for nq in Q do
        freegens := [];
        nr := nr + 1;
        nq.nr := nr;
        for i in BoundPositions(nq.delta) do
            q := nq.delta[i];
            if IsBound(q.repr) then
                if nq.repr = [] or nq.repr[Length(nq.repr)] <> -i then
                    Add(Gens, Concatenation(nq.repr, [i], -Reversed(q.repr)));
                    freegens[i] := Length(Gens);
                fi;
            else
                q.repr := ShallowCopy(nq.repr);
                Add(q.repr, i);
                Add(Q, q);
            fi;
        od;
        for i in BoundPositions(nq.deltainv) do
            q := nq.deltainv[i];
            if not(IsBound(q.repr)) then
                q.repr := ShallowCopy(nq.repr);
                Add(q.repr, -i);
                Add(Q, q);
            fi;
        od;
        if freegens <> [] then
            nq.freegens := freegens;
        fi;
    od;

    SetFGA_States(A, Q); # CRASHES HERE!!!
    SetFGA_GeneratorsLetterRep(A, Gens);
```
I have commented out line 329 in `lib/Autom.gi` from the FGA package, and the calculation now works with the results reported by @fingolfin. Of course, that may work for `Rank` but `FGA_States` is used in some other places in FGA, so that does not sound like a right solution.  Perhaps @chsievers can comment here? 

Still necessary to understand hat's going on in `SetFGA_States(A, Q)`.

**Comment by alex-konovalov** [comment]
@ignatsoroko could you please try if  commenting out line 329 in lib/Autom.gi from the FGA package has an effect for you? Even although that may not be the actual cause of the problem.

**Comment by ignatsoroko** [comment]
@alex-konovalov I just tried to comment the line `SetFGA_States(A, Q);` in fga/lib/Autom.gi. Nothing good came out of it. Now an easier code causes crash with stack dump:
```
NormalCore:=function(F,L)
    local S,R,x,N;
    R:=List(RightCosets(F,L),x->Representative(x));
    S:=List(R,x->Image(ConjugatorAutomorphismNC(F,x),L));
    N:=Intersection(S);
    return N;
end;
F:=FreeGroup("a","b");
AssignGeneratorVariables(F);
T:=LowIndexSubgroupsFpGroup(F,2);
NormalCore(F,T[2]); # crash!
```
Obviously, `SetFGA_States(A, Q)` sets the computed value Q for the object A. It is needed for other methods in FGA package.

**Comment by ChrisJefferson** [comment]
Is some package spawning new threads? Do we know which one?

**Comment by alex-konovalov** [comment]
@ChrisJefferson Threads appear n gdb output even when GAP started with `-r -A`:
```
(gdb) run
Starting program: /cygdrive/c/gap-4.9.0/bin/i686-pc-cygwin-gcc-default32/gap -r -A
[New Thread 6084.0x508]
[New Thread 6084.0xccc]
[New Thread 6084.0x1550]
[New Thread 6084.0xe40]
[New Thread 6084.0x12e4]
 ┌───────┐   GAP 4.9.0 of 26-Nov-2017
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: i686-pc-cygwin-gcc-default32
 Configuration:  gmp 6.0.0, readline
 Loading the library and packages ...
 Packages:   GAPDoc 1.6, PrimGrp 3.2.0, smallgrp 1.2, TransGrp 2.0.2
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> quit;
[Thread 6084.0xccc exited with code 0]
[Thread 6084.0x1550 exited with code 0]
[Thread 6084.0xe40 exited with code 0]
[Thread 6084.0x12e4 exited with code 0]
[Inferior 1 (process 6084) exited normally]
(gdb) q
```

**Comment by alex-konovalov** [comment]
@ignatsoroko thank you for example. Using it, I can now reproduce the crash in master branch when GAP is started with default set of packages. But it works when GAP started with `-r -A`. It could be that FGA is a red herring here, but I am nor sure yet.

**Comment by fingolfin** [comment]
Just to clarify: Even if FGA is involved in triggering the crash, the fundamental bug cannot be in it -- it is pure GAP package, no kernel extension. Crashes are always GAP's fault (or that of a kernel extension).

Now, `SetFGA_States` is just the setter of the `FGA_States` attribute. And that setter is compiled GAP code. So it may possibly lead to a crash. To get a better idea, it might be helpful to use the uncompiled setter instead -- to do this, edit `src/compstat.c` and change the line `// #define AVOID_PRECOMPILED` to `#define AVOID_PRECOMPILED`, then recompile GAP and try again.

Does it still crash?

**Comment by alex-konovalov** [comment]
With @ignatsoroko's short example:
* load GAP with `-r -A`: example works
* load FGA package - no dependencies, so no other packages loaded
* Now rerun example - it crashes.

@fingolfin yes, certainly. I will now try to recompile and see.

**Comment by ChrisJefferson** [comment]
I think we need more stack.

I did a horrible hack where I ran make with `V=1` and then added `--stack,16777216` to the `-W` options like this:

```
gcc ./src/gapw95.c -o .libs/gap.exe -Wl,--export-all-symbols,--stack,16777216  ./.libs/libgap.dll.a /home/caj/gap/extern/install/gmp/lib/libgmp.dll.a -L/usr/local/lib -L/home/caj/gap/extern/install/gmp/lib
```

Then I ran:

`.libs/gap.exe -l .` and the tests pass.

I am a little confused as to exactly how cygwin's executables get linked together, so I'm not sure how to edit the makefile to do this "properly" (and am completely swamped today and tomorrow).

**Comment by alex-konovalov** [comment]
@fingolfin recompiled with `#define AVOID_PRECOMPILED`: still crashes.

**Comment by chsievers** [comment]
It might be relevant that FGA potentially creates a lot of garbage collectable records.

If I had to disable a normally harmless attribute setter to avoid a crash, I wouldn't trust any result I might still be able to get, as it seems to indicate some memory corruption.

BTW, to better know which `Rank` is computed, there is also `RankOfFreeGroup`.

**Comment by alex-konovalov** [comment]
@chsievers thanks, see also my updated comment above regarding non-viewable `A!.initial`.

**Comment by chsievers** [comment]
@alex-konovalov `A!.initial` is a record that represents a state containing lists of other states that refer back to this state, so it is not something one would usually want to view (but it should be possible with small automata). Of course this mutual referencing is also a challenge to the garbage collector.

**Comment by fingolfin** [comment]
Actually, the mutual referencing isn't a problem for the garbage collector at all, that's trivial.

But other code which tries to traverse this data structure may have a harder time. E.g. the code for printing a record has to do some elaborate things in order to produce somewhat understandable results. But that, too, should be fine here (after all, the crash is not caused by printing).

The message @alex-konovalov produces is very interesting, though: "viewing stopped, too many recursion levels!" is printed when the nesting level exceeds MAXPRINTDEPTH = 1024. I.e. there is a record containing a list containing a record containing a list ... etc., more than 1024 levels deep (and these are pairwise distinct records, as GAP would detect recursion and do the right thing). Also:
```
gap> MemoryUsage(q);
Error, recursion depth trap (5000) in
  return MarkObject( MEMUSAGECACHE, obj ); at /Users/mhorn/Projekte/GAP/gap.github/lib/memusage.gi:105 called from
MU_AddToCache( o ) at /Users/mhorn/Projekte/GAP/gap.github/lib/memusage.gi:169 called from
MemoryUsage( s ) at /Users/mhorn/Projekte/GAP/gap.github/lib/memusage.gi:202 called from
MemoryUsage( o[i] ) at /Users/mhorn/Projekte/GAP/gap.github/lib/memusage.gi:179 called from
MemoryUsage( s ) at /Users/mhorn/Projekte/GAP/gap.github/lib/memusage.gi:202 called from
MemoryUsage( o[i] ) at /Users/mhorn/Projekte/GAP/gap.github/lib/memusage.gi:179 called from
```
So there around 5000 levels of recursion here.

Now @ChrisJefferson reports the issue goes away if he forces a larger stack. So my guess is that some code is recursively processing those records, and the recursion of more than 1024 level simply is too much for the tiny default stack in cygwin.

We can (and probably should) increase the default stack on Cygwin now, but generally speaking, we should do a better job of catching recursions which are too deep, and produce a sensible error (like in the `MemoryUsage` example above), instead of segfaulting.

The other thing I'd like to do, though, is to find out which code exactly is causing the crash, i.e. blowing up the stack. Perhaps it can be rewritten to avoid that (just like the MemoryUsage code could easily be rewritten to not be recursive).

**Comment by fingolfin** [comment]
So `SetFGA_States` here is just a the default "system setter", defined in `lib/type1.g` and then compiled to C code in `src/c_type1.c`. That was the reason I asked to avoid that, as I hoped it would turn the offending code into GAP code, which is easier to debug. Alas, that was in vein, because the actual setter function is produced by the kernel function `SETTER_FUNCTION`. The code of that is inside the kernel in `DoSetterFunction`. And I think relevant is this line of code...
```
      AssPRec( obj, rnam, CopyObj(value,0) );
```
... i.e. the kernel is making an immutable copy of the value, which here is `Q = [q]`. And that ends up doing that deeply nested recursion.
While it is in principle possible to rewrite the code to not use recursion, I am convinced there are other places which will similar problems; so we just should increase the stack size. Of course this just makes it harder to trigger the problem, but I think it's the best we can do for now.

**Comment by fingolfin** [comment]
@alex-konovalov can you perhaps check if this patch to the build system fixes the problem?
```patch
diff --git a/Makefile.rules b/Makefile.rules
index 7f705f631..28516292d 100644
--- a/Makefile.rules
+++ b/Makefile.rules
@@ -391,6 +391,9 @@ bin/cygwin-version.txt:

 GAP_CPPFLAGS += "-DCOMPILECYGWINDLL"

+# increase stack size, the default is too small (see issue #1522)
+GAP_LDFLAGS += -Wl,--stack,16777216
+
 # Special build rules for CYGWIN / Windows: In order to allow kernel
 # extensions, we employ a trick: GAP itself is compiled into DLL, in which
 # GAP's standard main function is renamed. And gap.exe is a tiny binary which
```

**Comment by chsievers** [comment]
So `SetFGA_States` does a lot more than an assignment!
That was never intended and made me a bit nervous at first.
Actually it doesn't harm correctness, but costs time and memory: now the whole automaton exists twice!
I think I'll change the attribute to a component of the automaton representation.
Then it will also no longer be possible to hit the recursion limit this way.

(Also, it is not just `Q = [q]`, as I keep `Add`ing states to `Q`.)

**Comment by fingolfin** [comment]
@chsievers Well, attributes in GAP are by definition immutable. So if you set an attribute to a value which is mutable, GAP must make an immutable copy. If you don't need the mutable original anymore, you can also call `MakeImmutable` on it first, before setting it as value for the attribute.

Of course if you stop putting this value in an attribute, you don't need to worry about that anymore.

**Comment by alex-konovalov** [comment]
@fingolfin thanks - I've build GAP with your patch under Cygwin, started it with `bin/gap.sh` and no crash happens any more. Now you or me can submit the patch.

**Comment by ignatsoroko** [comment]
I'd like to thank everybody who spent their time and effort to resolve this problem!
