### ISSUE TITLE
fplsa: update required to fix compilation problems, and clarify license

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1543]
The `fplsa` package does not compile on modern system out of the box, due to its use of the `malloc.h` header which is not part of ANSI/ISO C. The attached patches resolve this, and fix several warnings.

In addition, there is no license specified in the package. This must be clarified if we are to continue distributing it. The natural candidate would be to license it under GPL 2 or later, as it arguably contains code derived from GAP itself. In any case, the package authors need to clarify this.

We tried to reach the package authors a few times in the past, most recently 4th March 2016; so far no reaction.

[0001-fplsa-fix-compile-error.patch.txt](https://github.com/gap-system/gap/files/1185873/0001-fplsa-fix-compile-error.patch.txt)
[0002-fplsa-fix-warnings.patch.txt](https://github.com/gap-system/gap/files/1185874/0002-fplsa-fix-warnings.patch.txt)

**Comment by fingolfin** [comment]
Authors have been contacted again today, via email.

**Comment by fingolfin** [comment]
Email address of Vladimir Kornyak listed in `PackageInfo.g` bounced, so that's another thing to be fixed in the package.

**Comment by fingolfin** [comment]
Good news: authors quickly replied this time, gave permission for us to update the package, licensed under "GPL2 or later". I created a repo at https://github.com/gap-packages/fplsa

**Comment by alex-konovalov** [comment]
@fingolfin what happened to this? Is there a plan to release an updated FPLSA after 4.9 beta will be out?

**Comment by fingolfin** [comment]
FPLSA 1.2 was released a few days ago, yay :-).
