### ISSUE TITLE
IO now required to make manuals

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1544]
Commit https://github.com/gap-system/gap/commit/f619f1ebe436ff51d16ab6835e6907447bca9900 allows to build GAP manuals in a single GAP session. It however happens that it needs `ChangeDirectoryCurrent` function provided by the IO package and thus requires IO package to be available.

I am now adjusting release wrapping scripts to deal with that, but a long term solution, in my mind, is either to remove this dependency on IO or made IO needed to run GAP.

**Comment by stevelinton** [comment]
Would it be better to move this specific function from IO into core. It is very generally useful and shouldn't be too hard to do portably.
