### ISSUE TITLE
GAP precords are not thread-safe

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#1548]
GAP precords are not thread-safe. There is a method `SortPRecRNam`, which is used to sort the elements of a `PRec`, whenever we look up an element.

Therefore in HPC-GAP the following can occur:

1) Create a record p
2) Write a bunch of fields of p
3) Call `MakeImmutable(p)`
4) Start reading `p` in two different threads (which should be fine as it is immutable), both of which will start trying to sort the members of `p`.
5) Segfault.

The "fix" for this should be fairly easy, we should call `SortPRecRNam` as we make the record immutable. However, there are more places than this can happen than you might expect, as objects are implements as precords. Needs someone to go through carefully tracking where this can occur.

**Comment by stevelinton** [comment]
Addressed in #1553
