### ISSUE TITLE
Problem with AlgebraicExtension and ImmutableVector

### ISSUE THREAD

**Issue by frankluebeck** [gap-system/gap#1561]
### Observed behaviour
In GAP master branch:

```
gap> f:=GF(1009);
GF(1009)
gap> x:=Indeterminate(f,"x");
x
gap> pol := x^2+Z(1009)^108*x+Z(1009)^864;
x^2+Z(1009)^108*x+Z(1009)^864
gap> 
gap> AlgebraicExtension(f,pol);
Error, <n> must be a positive integer at /users/luebeck/gap4/lib/integer.gi:1099 called from
LogInt( q, common ) at /users/luebeck/gap4/lib/vecmat.gi:1355 called from
ConvertToVectorRepNC( v, f 
 ); at /users/luebeck/gap4/lib/vecmat.gi:1520 called from
ImmutableVector( rchar, i, true 
 ) at /users/luebeck/gap4/lib/algfld.gi:108 called from
AlgebraicElementsFamily( f, p 
 ) at /users/luebeck/gap4/lib/algfld.gi:172 called from
<function "DoAlgebraicExt">( <arguments> )
 called from read-eval loop at *stdin*:5
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> rchar;
0
brk> i;
[ 0*Z(1009), Z(1009)^0 ]
```
### Expected behaviour
Should return the extension
### Comments.

`ImmutableVector` is called with `rchar` argument 0. I'm not sure what this is supposed to do.

The code works in GAP 4.7.6.

**Comment by YongGe101** [comment]
# This is an <h1> tag
## This is an <h2> tag
###### This is an <h6> tag
*This text will be italic*
_This will also be italic_

**This text will be bold**
__This will also be bold__

_You **can** combine them_
* Item 1
* Item 2
  * Item 2a
  * Item 2b
1. Item 1
1. Item 2
1. Item 3
   1. Item 3a
   1. Item 3b
![GitHub Logo](/images/logo.png)
Format: ![Alt Text](url)
http://github.com - automatic!
[GitHub](http://github.com)
As Kanye West said:

> We're living the future so
> the present is our past.
I think you should use an
`<addr>` element here instead.
```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```    function fancyAlert(arg) {
      if(arg) {
        $.facebox({div:'#foo'})
      }
    }
def foo():
    if not bar:
        return True
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item
First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column
16c999e8c71134401a78d4d46435517b2271d6ac
mojombo@16c999e8c71134401a78d4d46435517b2271d6ac
mojombo/github-flavored-markdown@16c999e8c71134401a78d4d46435517b2271d6ac
#1
mojombo#1
mojombo/github-flavored-markdown#1

**Comment by stevelinton** [comment]
In AlgebraicElementsFamily (algfld.gi around line 90)  we see
```
if Size(f)<=256 then
    rchar:=Size(f);
  else
    rchar:=0;
  fi;
```
Most, but not all places in the following lines only try and do any format conversions to the vectors if rchar > 0, but the call to ImmutableVector at line 108 doesn't have this guard. 

Changing rchar to Size(f) at line 108 seems to fix the problem and creates no other obvious problems, but this function could use a rewrite to clarify the logic.
