### ISSUE TITLE
Unresolved links in HPC-GAP manual

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1568]
This should be cleaned up:

1) In the Changes manual:

```
#W WARNING: non resolved reference: rec(
  BookName := "ref",
  Func := "CallWithTimeout" )
#W WARNING: non resolved reference: rec(
  BookName := "ref",
  Func := "CallWithTimeoutList" )
```

(these were advertised when they were introduced, but subsequently withdrawn).

2) In the HPC manual:

```
#W WARNING: non resolved reference: rec(
  Func := "write-once" )
```
and
```
#W There were LaTeX Warnings:
LaTeX Warning: Label `WaitTask' multiply defined.
LaTeX Warning: Label `ExecuteTask' multiply defined.
LaTeX Warning: Label `RunTask' multiply defined.
LaTeX Warning: Reference `write-once' on page 16 undefined on input line 806.
LaTeX Warning: Reference `UNSAFEVIEW' on page 16 undefined on input line 807.
LaTeX Warning: Reference `MAXINTERRUPT' on page 37 undefined on input line 2133
LaTeX Warning: Reference `MAXINTERRUPT' on page 37 undefined on input line 2146
LaTeX Warning: Reference `SWITCHOBJ' on page 52 undefined on input line 2850.
Package atveryend Info: Empty hook `AtVeryVeryEnd' on input line 3296.
```

**Comment by fingolfin** [comment]
I guess the refs to `CallWithTimeout` etc. should just be replaced by something like `<C> CallWithTimeout</C>`

**Comment by alex-konovalov** [comment]
Remaining issues in principle can be quickly fixed by replacing `<Ref Func="UNSAFE_VIEW"/>` by `<Ref Label="UNSAFE_VIEW"/>`. But this is not the right solution. What actually must be done is to convert Subsections to ManSections. 

Also, a side note - the manual states @vjanjic as an author, but the chapter on MPI has been withdrawn.
