### ISSUE TITLE
Unhelpful error message

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#1577]
```
gap> Z(13) / 13;
Error, FFE operations: <divisor> must not be zero
not in any function at *stdin*:90
you can replace <divisor> via 'return <divisor>;'
```

**Comment by fingolfin** [comment]
I am not sure what the issue here is. For me, this error message makes perfect sense. What would you consider a "helpful" error message?

**Comment by alex-konovalov** [comment]
Maybe `FFE operations: <divisor> must not be zero element of the finite field` ?

**Comment by markuspf** [comment]
This is invalid. I was thinking that GAP reported this when I did `Z(13)/7`, say but I was wrong.
