### ISSUE TITLE
Unable to load multiple packages at once

### ISSUE THREAD

**Issue by sr-murthy** [gap-system/gap#159]
Unless I am mistaken `LoadPackage (<package name>);` is only able to load one package at a time, would it not be useful to add a `LoadPackages` command that accepts a list of package name strings and loads them in that order?

**Comment by ChrisJefferson** [comment]
While this does sound like a sensible suggestion, I wonder if it would be better to treat people about how to combine GAP functions? For example, in the past I have used:
`ForAll(["semigroups", "ferret"], LoadPackage)`.
Does this have the behaviour you planned for `LoadPackages` I wonder? (This does stop when one package fails to load, but that is what I wanted, if something doesn't load I'm giving up anyway).

**Comment by alex-konovalov** [comment]
@ChrisJefferson I had a similar idea, but using `Apply` - this way, it doesn't stop if anything fails to load. For example,
```
Apply( ["semigroups","ferret","wedderga"], LoadPackage);
```

**Comment by sr-murthy** [comment]
Yes, I suppose you could do it in those ways, but from a user's perspective it would be simpler to have a specific command for loading several packages at once.  If a package name is incorrect or does not exist then an appropriate message should be shown, while those which are correct should be loaded.  For example, in Python one can import several modules at once using `import` as follows:

    import json, io, strings

where `strings` is a non-existing module.  It will load the valid packages `json` and `io`, but displays an error for `strings`:

    ImportError: No module named strings

It is just nice to have one command for the user that does something useful and specific that they would need, rather than having them use an existing command in a new way, especially for something as basic as importing several packages, which is quite common in other languages.

**Comment by alex-konovalov** [comment]
@ChrisJefferson: Of course, because `LoadPackage` returns `true` or `fail`, one could also use `List` instead of `ForAll` and call e.g.
```
List( ["semigroups","ferret","wedderga"], LoadPackage);
```
to get a list of returns from `LoadPackage` - this will not stop on the 1st failed loading.

By the way, PEP 8 - Style Guide for Python Code says that "Imports should _usually_ be on separate lines" (see https://www.python.org/dev/peps/pep-0008/#imports) even though the syntax permits importing several modules at a time.

**Comment by sr-murthy** [comment]
I know that PEP8 recommends importing Python modules on separate lines, but PEPs are not iron rules to be followed, but suggested guidelines.  In my opinion, it is logical to have a command to be able to import several packages at once.  Probably this is not a big issue for GAP users, in which case I can close the issue, but if not, then I am happy to work on implementing it.

**Comment by fingolfin** [comment]
I completely fail to imagine a use case for this. Could you provide some motivation? In many years of using GAP, I do not recall yearning for such a feature even once... :).

**Comment by sr-murthy** [comment]
In that case I will close the issue.  I'm not saying it is based on my observation of GAP users' preferences, I am just an individual user, but it occurred to me that as the number of packages grows some users, who may need to use multiple packages simultaneously for their work, may appreciate a command that will allow them to import them using one simple command, which does not require the knowledge of list methods.

**Comment by alex-konovalov** [comment]
Please also note that if there is a constant need to load some package in addition to default ones, one can put appropriate `LoadPackage` call in the `gap.ini` file (see [here](http://gap-system.org/Manuals/doc/ref/chap3.html#X7FD66F977A3B02DF)).
