### ISSUE TITLE
Documentation for InstallMethodWithRandomSource is incorrect

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1596]
The documentation for `InstallMethodWithRandomSource` implies that if no random source is given, then `GlobalRandomSource` is used. But in reality, `GlobalMersenneTwister` is used.

Either the documentation or the code should be changed to address this.

**Comment by ChrisJefferson** [comment]
Woops, a typo (but quite a bad one).

**Comment by fingolfin** [comment]
Fixed by #1601
