### ISSUE TITLE
Bit masking for small ints

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#1611]
In implementing AVL trees and some other things, a real bottleneck is that GAP does not allow you to quickly pack and unpack small numbers into ranges of bits within a 32 or 64 bit word. In C this is easy and on modern hardware very fast (x86_64 has an instruction for the job). An example is the AVL trees. I currently use a small int to store the imbalance of each node, which really only uses 2 bits. I'd like to use some of the other bits to store the size of the subtree rooted at that node, and whether the node has a left (resp right) child (which allows threading). Doing that in GAP would be both cumbersome and slow, but using more words wastes both memory and more critically cache space and memory bandwidth.

I'd like to add some functions to do this at GAP level (possibly backed up by some kernel shenanigans to make them faster. Eventually it might want support from the parser to make these operations even faster. Here is one possible API.

`MakeMaskSet(bits1,bits2,...,bitsn)`
This gives an error if `bits1+bits2+....+bitsn` is more than the number of usable bits in a
small int (28 or 60). Otherwise it returns a record  with fields

- ` widths := [bits1,bits2,....bitsn];`  just for convenience
-  `builder := function(x1,x2,...,xn);` takes n numbers st `0 <= xi < 2^bitsi`
-  `getters := [getter1,....gettern);` where `getteri` is a function of one argument
-  `setters := [setter1,....settern);` where `setteri` is a function of two arguments

`builder` returns a small int which "wraps" `x1..xn` 
`getteri` extracts the ith field from such a smallint
`setteri` overwrites the ith field in such a smallint

Good practice would be to keep the functions from this record that you need often in local variables. It should be possible to make them very fast -- storing precomputed masks in the function object somewhere and using special C handlers, or even using in-line assembler to access the BEXTR instruction.

I'd welcome thoughts on the API (or indeed the concept).

**Comment by ChrisJefferson** [comment]
I wonder if `MakeMaskSet` should return an opaque object, which you pass as the first argument to some functions? Partly because otherwise the getters, setters and builders can't just straight hit kernel functions.

**Comment by stevelinton** [comment]
My plan is to implement MakeMaskSet in the kernel and create new function objects for the setters, getters  and builders there with special handlers and no body. My goal is to support code like

r := MakeMaskSet(2,1,1,56)
get_imbalance := r.getters[1];
get_has_leftchild := r.getters[2];
get_has_rightchild := r.getters[3];
get size_subtree := r.getters[4];

then ..... get_imbalance(node)  should be as fast to interpret (two local variable references, one EvalFunccall1Args and nothing else.

**Comment by ChrisJefferson** [comment]
My only worry was how to get the mask info into the getters functions efficiently. If you know how to do it, then I can learn how to do it :)

**Comment by stevelinton** [comment]
I need to find a field in the function object that I can use, similarly to how operations and attributes and stuff work.

**Comment by markuspf** [comment]
Assuming we're talking about the same `function object` (https://github.com/gap-system/gap/blob/d9d4c4b66472f3c95c0c6b258bdc159ced306fe2/src/calls.h#L118) I was going to extend this to be able to hold the location of the declaration of said object (for operations etc), so extending it by some more might not be too controversial unless there is a severe performance impact.

(Or would you store this in the function  body bag, which in this moment seems to make more sense to me.)

**Comment by stevelinton** [comment]
Current code uses NLOC_FUNC and BODY_FUNC, which are otherwise useless since these are not GAP functions.

**Comment by fingolfin** [comment]
This was implemented in PR #1616.
