### ISSUE TITLE
Extra space in filename completion

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1620]
If there is only one file in the directory, 

    Test("

after pressing Esc twice completes to 

    Test("testall.tst 

with an extra space after `tst`. This is not convenient, since it should be erased manually.

This can not be reproduced if the directory has more than one file, e.f.

    Test("fl

completes to

    Test("flush.tst"

**Comment by frankluebeck** [comment]
In the standard configuration the double Esc just calls the "complete" function of the readline library, which by default does a filename completion. You just have to live with what it does.

Of course, you could implement your own alternative function in GAP and overwrite the default ...
