### ISSUE TITLE
Crash when entering `Error` (and printing backtrace)

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#1624]
This is observed by @lucjon using current `master` with `--enable-hpcgap`; if you clone `https://github.com/lucjon/newss` and checkout the branch `break-repro`, and then run the following gap script

```
LoadPackage("newss");
ReadPackage("newss", "test/tests.g");
PerformTests(DefaultTests, rec ( load_groups_list := "pkg/newss/test/groups.grp" ));
```

Every so often GAP will segfault in `FuncPRINT_CURRENT_STATEMENT`. This is because `CURR_FUNC` is `0`, as one can see from the backtrace when one runs this in `gdb` (which thankfully works).

**Comment by fingolfin** [comment]
@lucjon This should be fixed on master thanks to PR #1848. If not, please reopen.
