### ISSUE TITLE
MinimalNormalSubgroups is slower than NormalSubgroups

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#164]
While testing some ideas I came across some examples where MinimalNormalSubgroups is significantly slower than NormalSubgroups. For example, this is the case with the group of Rubik's cube (3x3x3): 

cube := Group( ( 1, 3, 8, 6)( 2, 5, 7, 4)( 9,33,25,17)(10,34,26,18)(11,35,27,19), ( 9,11,16,14)(10,13,15,12)( 1,17,41,40)( 4,20,44,37)( 6,22,46,35), (17,19,24,22)(18,21,23,20)( 6,25,43,16)( 7,28,42,13)( 8,30,41,11), (25,27,32,30)(26,29,31,28)( 3,38,43,19)( 5,36,45,21)( 8,33,48,24), (33,35,40,38)(34,37,39,36)( 3, 9,46,32)( 2,12,47,29)( 1,14,48,27), (41,43,48,46)(42,45,47,44)(14,22,30,38)(15,23,31,39)(16,24,32,40) );

`NormalSubgroups` computes in 12 seconds on my laptop (with CRISP), and afterwards `MinimalNormalSubgroups` computes immediately. But if I call `MinimalNormalSubgroups` without calling `NormalSubgroups` first, then it computed for minutes before I decided to shut it down. However, `Socle` gave an answer in 13 seconds. (And it happens to be Abelian, but note that cube is non-solvable.)

A similar phenomenon occurred when trying it for the direct product of S10 with itself:  `MinimalNormalSubgroups` takes 26 seconds, `NormalSubgroups` computes in 2.5 seconds (and afterwards `MinimalNormalSubgroups` is instantaneous). Interestingly, `Socle` gave an answer in 170 ms, which is significantly faster than any of the above. 

Is it possible to increase efficiency for `MinimalNormalSubgroups`? It would help factoring groups into direct products. (E.g. the number of direct factors is bounded by the number of minimal normal subgroups <=> number of direct factors of socle.) Of course, as an alternative, I can always call Socle for solvable groups and then simply decompose it into direct factors, but this may not work very well for nonsolvable groups.

**Comment by hulpke** [comment]
The default method uses conjugacy classes, while the method using all normal subgroups requires `HasNormalSubgroups'. If one removes this prerequisite it would go the faster way.

**Comment by markuspf** [comment]
@hungaborhorvath has this been addressed with the merge of your recent pull requests? If so, can we close this then?

**Comment by hungaborhorvath** [comment]
No, my PR was about nilpotent groups, and cube is not solvable. In fact, if anything this issue became (slightly) worse (16 seconds on my machine, and if I run ````MinimalNormalSubgroups```` on cube, then it errors out by reaching pre-set memory limit). 

I think this issue is mainly for those people to comment (like @hulpke, @bh11, etc.) who understand deeply how ````NormalSubgroups```` computations work nowadays, and can decide when should ````NormalSubgroups```` be computed first when ````MinimalNormalSubgroups```` is called, in order to avoid the ````ConjugacyClasses```` method, which probably is much smaller nowadays for many groups. 

Or better yet, using the above knowledge, one could write faster ````MinimalNormalSubgroups```` methods. E.g. calling ````NormalSubgroups```` on the cube above runs ````grplatt:1786````, so maybe that algorithm can be modified for ````MinimalNormalSubgroups````? 

Both ````MinimalNormalSubgroups```` and ````MaximalNormalSubgroups```` can be very useful for deciding (at least in one way) if a group is direct indecomposable, and therefore could help speeding up the computation of ````StructureDescription````.
