### ISSUE TITLE
Incorrect IsOne methods for Rees (0-)matrix semigroup elements

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#1661]
### Observed behaviour

For the following non-trivial Rees 0-matrix and Rees matrix semigroup, `IsOne` returns `true` for the multiplicative zero element. This is incorrect.
```
gap> R := ReesZeroMatrixSemigroup(Group(()), [[()]]);;
gap> IsOne(MultiplicativeZero(R));
true
gap> ForAll(R, s -> s * MultiplicativeZero(R) = s);
false
gap> IsTrivial(R);
false
```

```
gap> S := ReesMatrixSemigroup(R, [[MultiplicativeZero(R)]]);;
gap> x := RMSElement(S, 1, MultiplicativeZero(R), 1);;
gap> IsOne(x);
true
gap> ForAll(S, s -> s * x = s);
false
gap> IsMultiplicativeZero(S, x);
true
gap> IsTrivial(S);
false
```

The method returns `true` if it's a 1x1 Rees (0-)matrix semigroup, and the element in question is idempotent. That's invalid; a 1x1 Rees (0-matrix semigroup) can contain many idempotents; at most one can be an identity.

The bigger question: **do Rees (0-)matrix semigroups ever satisfy `IsMagmaWithOne`?** I don't think so, and the `IsOne` method shouldn't even apply to a `Rees(Zero)MatrixSemigroupElement`. Do you agree @james-d-mitchell or anyone else? I think I should just delete these methods; another option would be to fix and adapt these methods and instead have them as methods for `MultiplicativeNeturalElement`.

### Copy and paste GAP banner (to tell us about your setup)

```
 ┌───────┐   GAP 4.8.7-4206-g1ba5a47-dirty of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin13.4.0-gcc-default64
 Configuration:  gmp 6.1.2
 Loading the library and packages ...
 Components: trans 1.0, prim 3.0
 Packages:   GAPDoc 1.5.1
```

**Comment by james-d-mitchell** [comment]
Isn't a 1 by 1 Rees matrix semigroup over a group just a group, and hence it has a one?

**Comment by wilfwilson** [comment]
A Rees (0-)matrix semigroup has a multiplicative neutral element (identity) if and only if it is 1x1 and the matrix entry is a unit of the underlying semigroup.

My question was a technical rather than mathematical one:
```
gap> R := ReesMatrixSemigroup(SymmetricGroup(3), [[()]]);
<Rees matrix semigroup 1x1 over Sym( [ 1 .. 3 ] )>
gap> IsMagmaWithOne(R);
false
```
The identity of this is `(1, (), 1)`, but since `R` it's not a magma with one (i.e. `(1, (), 1) ^ 0` doesn't work), at the moment it seems inconsistent for for `IsOne` to apply. Note that the doc for `IsOne` says `IsOne(elm) is true if elm = One( elm ), and false otherwise`. The doc for `One` includes the following: `Note  that  One  is  applicable  to  a  domain  only  if  it  is a magma-with-one`

**Comment by james-d-mitchell** [comment]
Oh yes, I see what you mean, if Rees matrix semigroups in GAP are not in the category `IsMagmaWithOne`, then there should not be a method for `One` as you write.

**Comment by wilfwilson** [comment]
Okay, I'm just going to remove the `IsOne` methods
