### ISSUE TITLE
TemporaryGlobalVarName is not threadsafe

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#1671]
The function `TemporaryGlobalVarName` is not thread-safe, as it produces the same variable name when called from multiple threads.

My suggested fix would be (other options available!)

1) Add a dummy version of `CurrentThread` and `ThreadID` to GAP. Then you can call in both GAP and HPC-GAP `CurrentThread(ThreadID())` to get a number about to current thread.

2) Put that number into the string generated by `TemporaryGlobalVarName`.

**Comment by fingolfin** [comment]
Orthogonally to this, we've also now deprecated `TemporaryGlobalVarName` and the only two remaining known uses are in the `anupq` and `SCSCP` packages. And I am working on removing its use in anupq, see https://github.com/gap-packages/anupq/pull/35

**Comment by fingolfin** [comment]
We marked `TemporaryGlobalVarName` as obsolete for GAP 4.11; and only SCSCP still uses it (but I made https://github.com/gap-packages/scscp/pull/46 to get rid of it).

Hence I don't think there is any point in worrying about its thread safety at this point.
