### ISSUE TITLE
Incorrect behaviour for certain partial perm semigroups

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#1674]
Currently, in the GAP `master` branch, not using the Semigroups package.

### Observed behaviour

I'll create this semigroup, which is a semigroup of size 2 with an identity and a zero:
```
gap> x := PartialPerm([1]);
<identity partial perm on [ 1 ]>
gap> y := PartialPerm([0]);
<empty partial perm
gap> S := Semigroup(x, y);
<partial perm monoid of rank 1 with 2 generators>
```
It has two D-classes, but GAP finds only one:
```
gap> GreensDClasses(S);
[ <Green's D-class: <identity partial perm on [ 1 ]>> ]
```
And therefore it gets the size and number of elements wrong:
```
gap> Elements(S);
[ <identity partial perm on [ 1 ]> ]
gap> y in Elements(S);
false
gap> y in GeneratorsOfMonoid(S);
true
```
If I do this in a different order, I get the correct list of elements, but an error:
```
gap> S := Semigroup(x, y);
<partial perm monoid of rank 1 with 2 generators>
gap> Elements(S);
[ <empty partial perm>, <identity partial perm on [ 1 ]> ]
gap> GreensDClasses(S);
Error, <S> and <T> must have the same size at /Users/Wilf/GAP/lib/semirel.gi:1262 called from
SemigroupHomomorphismByImagesNC( m, fpsemi, List( pos, function ( x )
        return fpelts[x];
    end ) ) at /Users/Wilf/GAP/lib/semirel.gi:1124 called from
FroidurePinExtendedAlg( semi
 ); at /Users/Wilf/GAP/lib/semirel.gi:575 called from
GreensLClasses( semi ) at /Users/Wilf/GAP/lib/semirel.gi:610 called from
<function "unknown">( <arguments> )
```
This problem **does not** occur with the Semigroups package loaded.

### Expected behaviour

The semigroup `S` should have two elements, have size 2, and 2 D-classes.

### GAP banner

 ┌───────┐   GAP 4.8.8-4239-ga7ce041 of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin13.4.0-gcc-default64
 Configuration:  gmp 6.1.2
 Loading the library and packages ...
 Components: trans 1.0
 Packages:   GAPDoc 1.5.1
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'

**Comment by wilfwilson** [comment]
This happens with other partial perm semigroups:
```
gap> SymmetricInverseMonoid(2);
<symmetric inverse monoid of degree 2>
gap> GreensDClasses(last);
[ <Green's D-class: <identity partial perm on [ 1, 2 ]>> ]
```
This should have 3 D-classes

**Comment by wilfwilson** [comment]
This narrows down the problem a bit:
```
gap> S := Semigroup(x, y);
<partial perm monoid of rank 1 with 2 generators>
gap> FroidurePinExtendedAlg(S);
gap> LeftCayleyGraphSemigroup(S);
[ [  ] ]
```

**Comment by markuspf** [comment]
The problem is this

```
gap> One(x);
<identity partial perm on [ 1 ]>
gap> One(y);
<empty partial perm>
```

Since `FroidurePinExtendedAlg` filters out all generators that are equal to `One(x)`.

**Comment by markuspf** [comment]
The documentation of `One` claims that it should return *the* multiplicative neutral element of its argument. This does not really make sense for partial permutations since there are potentially many of them as far as I understand.

**Comment by james-d-mitchell** [comment]
So a more radical solution to this would be to simply delete the offending code in GAP (I wrote it, I confess), and require the Semigroups package where this does not occur.

**Comment by markuspf** [comment]
I think this would require most of GAP's semigroup functionality to happen in the semigroups package.

While I in principle support moving as much semigroups functionality as we can to the semigroups package (see also #1681), we need to be careful about the ways in which the semigroups code interacts with the rest of the GAP libraries and packages.

I remember that there are some string functions that refer to free monoids, so we should check carefully that we don't break anyone's code.

I propose that we should *not* do this for 4.9 and hold off (merging!) any radical things for after `stable-4.9` has been created.

**Comment by markuspf** [comment]
Looking at the places in which `FroidurePinExtendedAlg` is used it seems that its not very integral to the "functioning" of the library, so removing `FroidurePinExtendedAlg` is an option, but maybe its still worth fixing it?

**Comment by wilfwilson** [comment]
I think I can fix the incorrect result that I originally reported by replacing the line
https://github.com/gap-system/gap/blob/a4b35953124d9112e1aed382e78778584a81edf1/lib/semirel.gi#L975
with
```
gens:=Set(Filtered(GeneratorsOfMonoid(semi), x -> x <> One(semi)));
```
Of course, this doesn't resolve the more fundamental issue that `One` and `IsOne` are doesn't behave as intended for partial permutations. But I'll prepare a PR with this change.

**Comment by james-d-mitchell** [comment]
Just to chip in: `One` and `IsOne` do behave as intended, it is just that their behaviour does not correspond with the documentation. 

The principal issue is that `One(x)` when `x` is a partial perm cannot return the same object for every partial perm, unless we define a partial perm on all of the natural numbers (currently partial perms are only ever defined on a finite set). So, for this to be compatible with the documentation either:

1.  we have to have this uniquely special partial perm defined on all the natural numbers
2. `One(x)` should return `fail`, and we cannot any longer make monoids of partial permutations.

There are drawbacks to either of these, and I proposed changing the documentation and not the behaviour of partial perms.

**Comment by wilfwilson** [comment]
Yes, sorry @james-d-mitchell I wasn't as clear as I should have been - I meant that `IsOne` and `One` for partial perms don't behave in the way that was intended *by whoever wrote the documentation.* Certainly they do what you intended.
