### ISSUE TITLE
Problems with building GMP for HPC-GAP under Cygwin

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#168]
I have moved our Jenkins Windows build to a new Windows 7 virtual machine with a fresh Cygwin installation, which now provides gcc 4.9.2.

The following problem happens now:

```
=== Extracting gmp-5.0.4 ===
=== Building gmp-5.0.4 ===
checking build system type... Invalid configuration `coreisrb-pc-cygwin': machine `coreisrb-pc' not recognized
configure: error: /bin/sh ./config.sub coreisrb-pc-cygwin failed
=== Failed to build gmp-5.0.4 ===
``` 

@rbehrends, do you think it's a problem in older GMP (GAP 4 has GMP 5.0.5 and it builds fine), or a problem in HPC-GAP?

Perhaps synchronising GMP versions in both branches would be useful. Note that the latest GMP release is 6.0.0a (2014-03-24) and we may try to get that into GAP 4.8 beta.

**Comment by rbehrends** [comment]
This looks like a problem with GMP's configure script, since the "checking build system type" is about the first thing it does, and "coreisrb-pc-cygin" looks odd for a build system type. Can you try and see if GMP's configure runs on its own for GMP 5.0.4?

**Comment by alex-konovalov** [comment]
No:
```
$ ./configure
checking build system type... Invalid configuration `coreisrb-pc-cygwin': machine `coreisrb-pc' not recognized
configure: error: /bin/sh ./config.sub coreisrb-pc-cygwin failed
```
This seems to be fixed in GMP 5.0.5:
```
$ ./configure
checking build system type... coreisbr-pc-cygwin
checking host system type... coreisbr-pc-cygwin
checking for a BSD-compatible install... /usr/bin/install -c
...
```

**Comment by rbehrends** [comment]
Then we should probably try and use GMP 5.0.5 or later. Switching to 5.0.5 is easy, because the .tar.gz file is already in the repository (from an earlier merge with GAP 4.something). You just have to change the line `build_external("gmp-5.0.4", ...)` in `SConstruct` to say `"gmp-5.0.5"` instead of `"gmp-5.0.4"` (this should be line 365). I recommend trying at first if it builds with this change, and if it does, to commit the change.

**Comment by alex-konovalov** [comment]
Thanks - switched to GMP 5.0.5 in commit 481499a63682e7572aff0f99c6a6cee93c6b4ea7
