### ISSUE TITLE
Reactivate the `dev/Updates`  system (or something similar) for tracking changes for release notes

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1702]
The plan: Any pull request which adds a feature or fixes a bug that should be conceivably mentioned in release notes should also add a file briefly summarizing these changes in the `dev/Updates` directory. Then we can can generate release notes with help of these.

Why not add a line to a `CHANGES` file? Because if multiple PRs add a change, they'll all add the new line in `CHANGES` in the same place, leading to a conflict (so after on PR has been merged, the others would have to be adjusted first), which is very annoying.

In the old system, a typical `dev/Updates` file looks like this:
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Format 'yyyy/mm/dd'
!! Date
2016/01/11
!! Changed by
SL
! Reported by
Nick Loughlin
!! Type of Change
Fix: wrong result

!! Description
Under some circumstances the union of a combination of lists of small integers
and ranges could be computed incorrectly. This change fixes this and also
avoids expanding ranges unnecessarily in some cases.

! Test Code
# included in union.tst

! Prefetch

!! Changeset

!! End
```

This file format can then be parsed by a script to generate a human readable list of changes (but is there such a script? and where? @alex-konovalov ?)

The problem I see with this is that doing that is quit annoying. Also, one cannot really fill in the `Changeset` entry. Personally, I'd at the very least remove the `Prefetch` and `Changeset` fields, and make some of the other optional. 

But perhaps it would be better to do a more sweeping change, and e.g. use a JSON or YAML based format. Or just plain text files contain a description of the issue and nothing else. Rationale:
* we ask for tests to be added anyway, so `Test Code` is not necessary
* we can write a script which given such a file, finds out in which commit it was added and by whom, this can be used to populate the date and "changed by" field
* we can also query the GitHub API to find the PR adding the file, and then use that to also add its number resp. a link to it to the release notes
* this leaves "Type of Change"; that would actually be nice to retain (though if we used labels on GitHub consistently, it could also be computed from those).

Anyway: We should decide on something for this ASAP, and then insist that going forward, all reviewers check that PRs including a `dev/Updates` file if it makes sense.

**Comment by stevelinton** [comment]
Reported by is relevant for bugs. We used to include that in the release announcements and it would be good to do so again, to give credit where it's due. We can't rely on all reports appearing in the form of github issues.  The "Type of Change" stuff is also something that's good to include in the release announcement. If the release includes fixes for wrong results in an area you care about it may be good rerun research computations. Agreed the other fields are not needed.

**Comment by fingolfin** [comment]
I thought about this some more. The advantage of having these files is that all data is in the repository, and can be easily recovered in the distant future, even if GitHub goes away / we stop using it.

The drawback is that one has to remember creating these files, come up with names for them, fill them with content etc. I am simply concerned whether people will really do this consistently. Also, now they have to write that text, too, in addition to a good commit message and a pull request description (granted, one can reuse text between the three).

So, I want to make that easy and pain free as possible. Also, it should be trivial to validate those files, if we want to collect their content automatically later on.

One way to achieve that is to provide scripts which create one of those files for you, and another for validating it; the latter could also be run as part of the travis tests. Also, we could switch to another data format; perhaps JSON or XML make more sense? OTOH, the existing format essentially seems fine to me, too *shrug*

Question (perhaps for @alex-konovalov): are there scripts which parse `dev/Updates` to generate a changelog? if so, where are they? couldn't find them (just scripts which parse them to extract tests, but to be honest, I am not sure whether it makes sense to keep doing that).

**Comment by alex-konovalov** [comment]
The only automated use of `dev/Updates` file that I am using at the moment is `make testupdates` which extracts tests from `dev/Updates` entries and regularly run on Jenkins. 

The script was called `dev/DistributionUpdate/maindist/Update.g` and it has been deleted in the following commit: https://github.com/gap-system/gap/pull/13/files#diff-837b949249dcd66121806fe023412def (and I have never used it). IIRC it was used to make overview of the releases at https://www.gap-system.org/Download/Updates/index.html up to GAP 4.4.12. After that, since GAP 4.5 releases overview became parts of the new "Changes" manual.

The idea of the simplified dev/Update file still appeals to me. One of the simplifications should be that it does not need to include tests in this file - instead, they will go into appropriate locations in tst. Two other alternatives that we have tried - editing the [Wiki page](https://github.com/gap-system/gap/wiki/Changes-between-GAP-4.8-and-GAP-4.9) or asking for a well-polished text for the release notes in the description of the PR - are hard to achieve.

**Comment by fingolfin** [comment]
In the end, we went a different way, and now use labels on GitHub pull requests to create the change log.
