### ISSUE TITLE
Chapter on relations has no single example at all

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1705]
My attention was turned to this by [this question](https://math.stackexchange.com/questions/2359463/poset-test-and-hasse-diagram-in-gap). 

Some examples of this functionality may be found in the test file https://github.com/gap-system/gap/blob/master/tst/testinstall/relation.tst and in my 10+ old teaching materials at https://www.gap-system.org/ukrgap/Examples/relation.htm.

**Comment by grouptheoryenthusiast** [comment]
Hi,

I had a question about style/format for adding examples to the documentation chapter.

Is it allowed for an example to demonstrate several different functions.

For instance could there be an example which defines a relation, show it is reflexive, symmetric, transitive, then that it is an equivalence relation and finally finds the equivalence classes,  or is it that the point of the examples is to  demonstrate only the function in whose description it has been embedded. If this is allowed, where would be the correct place for such an example?

Also, as the entries in the chapter are numbered, can one use a function with a later number in an earlier example?

Thank you

James

**Comment by AnnaKDS** [comment]
@ssiccha it seems like somebody forgot to close this issue
