### ISSUE TITLE
Replacing ReadTest by Test

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#172]
There are packages still using `ReadTest` instead of `Test`. Would it be a problem to make `Test` with comparison up to whitespaces a synonym of `ReadTest` ?

**Comment by ChrisJefferson** [comment]
It sounds reasonable, perhaps give it a try :)

If it works, there is a bunch of code we can strip out, which would be nice.

**Comment by alex-konovalov** [comment]
Implemented in #290
