### ISSUE TITLE
Check the status of obsoletes before GAP 4.9.0

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1768]
Some entries from obsoletes (moved there before 4.8.0) are not used in any of the redistributed packages any more and may be deleted.

Mainly a reminder for myself to submit a PR.

**Comment by ChrisJefferson** [comment]
Just to clarify, do you mean delete them entirely, so currently working GAP code which uses them will break?

**Comment by alex-konovalov** [comment]
Yes. The procedure used in the past was to move to obsolete in a major release, and delete entirely (if no packages use it by that time) in the next major release.

I am not going to mechanically remove everything which is not used by packages, and PR will be reviewed, in case someone will suggest to keep some things. But for example I think it's fine to delete KERNEL_VERSION and PACKAGE_VERSIONS and maybe other package-related things which are not used in any of the redistributed packages (mentioned in #1734)
