### ISSUE TITLE
Compiler emits call to InfoDecision but symbol is defined `static` in intrprtr.c

### ISSUE THREAD

**Issue by kalbr** [gap-system/gap#1781]
With a fresh checkout of master, the compiling the snippet
```gap
SomeFunc := function(a, b)
    Info(InfoWarning, 1, "foo");
    return a+b;
end;
```
produces a module that fails to load:
```
LoadDynamicModule("libtest.la.so");
#W dlopen() error: dlopen(libtest.la.so, 9): Symbol not found: _InfoDecision
  Referenced from: libtest.la.so
  Expected in: flat namespace
 in libtest.la.so
```

It seems that `InfoDecision` is declared in compiled.h, but has no non-static definition. I fixed this locally with the following trivial diff:
```diff
diff --git a/src/intrprtr.c b/src/intrprtr.c
index fc1bc9576..c08153f56 100644
--- a/src/intrprtr.c
+++ b/src/intrprtr.c
@@ -4533,7 +4533,7 @@ void            IntrInfoBegin( void )
 
 }
 
-static Obj InfoDecision;
+Obj InfoDecision;
 static Obj InfoDecisionFast;
 static Obj IsInfoClassListRep;
```

**Comment by fingolfin** [comment]
This regression is likely caused by PR #1464, where we overlooked that the GAP compiler also needs to be adjusted. Also relevant for PR #1770

**Comment by ChrisJefferson** [comment]
Just so I cover your use case, could you give the complete list of commands you use to create, build, and load the dynamic module?
