### ISSUE TITLE
Problematic syntax error / break loop interaction when doing `1[2]:=3`

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1804]
I originally noticed the following when experimenting with constant gvars, but eventually realized it doesn't have to do anything with it; instead it is a regression compared to GAP 4.8 and older. Specifically, this:
```
gap> 1[2]:=3;
Error, List Element: <list> must be a list (not a integer)
not in any function at *stdin*:1
you can replace <list> via 'return <list>;'
brk> quit;
Syntax error: ; expected
1[2]:=3;
     ^
```

So the problem here is that we now in principle support `foo[idx]` for arbitrary objects; in principle, you can install such a method handling the case where `foo` is an integer. 

Possible solutions that come to mind:
1. Stop treating `1[2]` as a syntax error.
2. Disallow `foor[2]` for `foo` an integer, and hide the first error in that case.

I think 1. is the "correct" solution in view of our new capabilities. Indeed, I think the "new" error message is more helpful than the syntax error. This becomes particular visible with constant gvars:
```
gap> x:=1;; MakeConstantGlobal("x");;
gap> x[1]:=2;
Error, List Element: <list> must be a list (not a integer)
not in any function at *stdin*:4
you can replace <list> via 'return <list>;'
brk> quit;
Syntax error: ; expected
x[1]:=2;
     ^
```
Here, the first error is quite helpful; while the syntax error is not helpful at all.

**Comment by stevelinton** [comment]
The same error shows up in `[1,2,3][2] := 3;`  
This arguably should be legal, but useless. Indeed the equally useless:
```
foo := function() return []; end;
foo()[1] := 2;
```
works (or at least raises no errors).

A problem though is something like
```
x := IdentityMat(3);
x{[1,2]]}[2] := [2,3];
```
which sets the 1,2 and 2,2 entries of `x` to 2 and 3 respectively
versus
```
x := IdentityMat(3);
(x{[1,2]]})[2] := [2,3];
```
which is a syntax error. If we suppress this error, both of these would be valid and have different meanings, which would, at least, require careful documentation.

**Comment by ChrisJefferson** [comment]
I think you might be misinterpreting that error?

`1[2]` isn't a syntax error by itself (although it fails because we haven't installed a method for `\[\](IsInt,IsInt)`. The problem is that we don't view `1[2]` as a valid left hand side of an assignment, so the parser assumes it has reached end of statement, and complains when it doesn't see a semicolon. You get the same error for `2 := 3` in master, 4.8 and 4.7.

It's worth (I think) looking at a few examples:

```
gap> x := 1;
gap> 2 := 3; # Same in 4.8, 4.7 and master
Syntax error: ; expected
2 := 3;
   ^
3
gap> x[2] := 3; # Same in 4.8, 4.7 and master
Error, List Assignment: <list> must be a list (not a integer)
not in any function at *stdin*:3
you can replace <list> via 'return <list>;'
gap> invalidfunc() := 3; # Same in 4.7, 4.8 and master
Error, Variable: 'invalidfunc' must have a value
not in any function at *stdin*:5
Syntax error: ; expected
invalidfunc() := 3;
               ^
3
gap> 1[2] := 3; # Differs
# In 4.8
Syntax error: ; expected
1[2] := 3;
 ^
# In master
Error, List Element: <list> must be a list (not a integer)
not in any function at *stdin*:3
you can replace <list> via 'return <list>;'
brk>
Syntax error: ; expected
1[2] := 3;
      ^
```

**Comment by ChrisJefferson** [comment]
So maybe we need to change `; expected` into something about `invalid assignment`?

And also separately, we could change the `Error, List Assignment: <list> must be a list (not a integer)` to not enter the break loop, as I don't think it's super-useful to be able to replace the list when you passed in an integer :)

**Comment by fingolfin** [comment]
To clarify: My primary (and hopefully uncontroversial) complaint is that the syntax error is only displayed *after* leaving the break loop. That can be super confusing:
```
gap> 1[2]:=3;
Error, List Element: <list> must be a list (not a integer)
not in any function at *stdin*:1
you can replace <list> via 'return <list>;'
brk>
brk>
brk> 1+1;
2
brk>
Syntax error: ; expected
1[2]:=3;
     ^
```

The suggestion that we only show one error, not two, is just one way to address this. I don't mind if that suggestion turns out invalid or infeasible, as long as the reported issue is resolved :-)

**Comment by ChrisJefferson** [comment]
So the path through the parser (for the curious) is:

read.c:2795 -- if the line starts with an identifier, read an expression, which might be an assignment.

If the line doesn't start with an identifer, it can't be an assignment. Therefore read an expression which can't be an assignment (line 2816). This correctly parses 1[2], tries to execute it (and fails, as \[\] isn't defined for IsInt,IsInt).

Now get to 2819, we find we haven't got a semicolon, and produce "; expected".

This problem has always been there, it's just easier to cause now, for example: `() + () := 3` causes the same behaviour in gap 4.7, 4.8 and master.

**Comment by stevelinton** [comment]
@fingolfin so this is an instance of the general confusion caused by the very eager evaluation in the parser. A common (but less confusing) instance at least for clumsy typists like me is 
```
foo(bar)l
```
(hit 'l' instead of ';') 

This will fully evaluate `foo(bar)` including any associated break loops, interaction, I/O, etc. before reaching the `; expected` error.   Short of abandoning eager execution (which would, I admit make life much simpler, except that it would break a few systems that rely on being able to read really long lists, permutations, etc. without having to store a parse tree anywhere) I'm not really sure what can be done.

**Comment by ChrisJefferson** [comment]
I think this isn't a bug, and isn't really fixable without significant general changes, so should be closed.

**Comment by fingolfin** [comment]
I agree.
