### ISSUE TITLE
Do we still need to support non-GMP long integers?

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#181]
Title says it all really. I just noticed that Markus' recent PR #178 still includes patches to the non-GMP integer arithmetic. Is there any reason to continue to support that?

**Comment by ChrisJefferson** [comment]
I would like to get rid of it, recently there was an aliasing bug which I fixed, having had a quick look over the code I would expect other aliasing / undefined behaviour bugs to rise up over the coming years, and removing the code would remove the need to track them all down!

**Comment by markuspf** [comment]
There's the issue that if this code is never used nor tested that we don't know what value this code still has.

I wonder whether we could remove it, replace gmp by minigmp, and getting rid of the necessity of having gmp bundled with the gap distribution (and giving people the option to use a system GMP if they want to).

I don't know how many relevant architectures exist where neither gmp nor minigmp would work, I suspect.

**Comment by hulpke** [comment]
On Jun 9, 2015, at 6/9/15 6:25, stevelinton <notifications@github.com> wrote:
> 
> Title says it all really. I just noticed that Markus' recent PR #178 still includes patches to the non-GMP integer arithmetic. Is there any reason to continue to support that?

Since GMP seems to work (and we presumably can keep a working version of GMP in perpetuity, even if they do incompatible changes) I don’t see a fundamental reason for keeping the old arithmetic.

Just in case in the future something weird happens, it might be useful to record what was the last release version in which the old arithmetic still worked.

Best,

  Alexander

**Comment by stevelinton** [comment]
> On 9 Jun 2015, at 16:45, Alexander Hulpke <notifications@github.com> wrote:
> 
> On Jun 9, 2015, at 6/9/15 6:25, stevelinton <notifications@github.com> wrote:
> > 
> > Title says it all really. I just noticed that Markus' recent PR #178 still includes patches to the non-GMP integer arithmetic. Is there any reason to continue to support that?
> 
> Since GMP seems to work (and we presumably can keep a working version of GMP in perpetuity, even if they do incompatible changes) I don’t see a fundamental reason for keeping the old arithmetic.

That’s not totally easy — new compilers often break gmp (or are broken in ways that only gmp sets off) but 
there are already drop-in alternatives, so we can assume that something will continue to run the gmp interface.

Steve

**Comment by alex-konovalov** [comment]
On 9 Jun 2015, at 15:18, Markus Pfeiffer <notifications@github.com> wrote:
> 
> There's the issue that if this code is never used nor tested that we don't know what value this code still has.

Just to clarify to which extend this code is tested: actually, all nightly and weekly tests are run in both configurations - with and without GMP. But we know that code coverage in our tests is not comprehensive, and because since GAP 4.5 GMP support is default, further user testing of this code is minimal.

I don't mind getting rid of non-GMP long ints. This will only help to speed up testing cycle :)

**Comment by hulpke** [comment]
> > 
> > Since GMP seems to work (and we presumably can keep a working version of GMP in perpetuity, even if they do incompatible changes) I don’t see a fundamental reason for keeping the old arithmetic.
> 
> That’s not totally easy — new compilers often break gmp (or are broken in ways that only gmp sets off) but 
> there are already drop-in alternatives, so we can assume that something will continue to run the gmp interface.

We’re also not throwing away our code. Should in future GMP be fatally broken and old versions not compile we could in principle go back and resurrect our code.
Yes, it will need the fixes then which were not done in between (and doing them then will take more time), but this extra time would be only needed in the case of a dysfunctional future for GMP and all alternatives. I think that chance is low.

Alexander

**Comment by stevelinton** [comment]
Once 4.8 is released, I'll commit the change to remove non-GMP support in the main branch.

**Comment by alex-konovalov** [comment]
I've created a milestone GAP 4.9.0 (Beta release of GAP 4.9) and used it for this issue. Please use if for anything else that we may want to do in the next major release after GAP 4.8 beta. As soon as GAP 4.8.0 beta will be out, we will create `stable-4.8` branch where changes for GAP 4.8.1 will stabilise, and then `master` branch will be a prototype of GAP 4.9.

**Comment by fingolfin** [comment]
I am all for getting rid of that unmaintained code path.

**Comment by fingolfin** [comment]
Is there any reason not to remove the non-GMP code path *now*? Given that stable-4.8 already was branched some time ago, I can't think of one...

**Comment by stevelinton** [comment]
Can't think of one.

**Comment by markuspf** [comment]
#629 does the removal of non-GMP integers.

**Comment by markuspf** [comment]
#629 has been merged, and hence I'll close this issue.
