### ISSUE TITLE
Overview of changes in GAP 4.8 for the beta-release

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#182]
Just to remind ourselves that for the beta release we have to prepare an overview for the "Changes" manual.

**Comment by stevelinton** [comment]
The partial variadic function code is there and needs to be flagged up to package authors in the beta because it does break a few packages that (mis)use arg as an argument name in functions that are not meant to be variadic. There are some warnings in the current code, which will either be removed (use of new syntax) or turned into errors (use of arg not in last place) in the non-beta 4.8.x series

**Comment by alex-konovalov** [comment]
Another things to be reminded to package are new PackageInfo.g components (see issue #7 and PR #206).

**Comment by alex-konovalov** [comment]
Another novelty in GAP 4.8: https://github.com/gap-system/gap/pull/28

**Comment by ChrisJefferson** [comment]
Filename/lines on backtraces and TraceMethods
Line-based profiling and code coverage (which could do with better documentation for 4.8)

**Comment by alex-konovalov** [comment]
@ChrisJefferson absolutely agree! Could you please now document both changes (Filename/lines on backtraces and TraceMethods; Line-based profiling and code coverage) at https://github.com/gap-system/gap/wiki/Changes-between-GAP-4.7-and-GAP-4.8? I will be converting that page to GAPDoc immediately prior to the release.

**Comment by alex-konovalov** [comment]
@ChrisJefferson ping :) We may be in a good position for GAP 4.8 beta now, and this is one of the small number of things that have to be done before. Could you please write a couple of paragraphs for https://github.com/gap-system/gap/wiki/Changes-between-GAP-4.7-and-GAP-4.8 on:
* Filename/lines on backtraces and TraceMethods
* Line-based profiling and code coverage (which could do with better documentation for 4.8)

**Comment by alex-konovalov** [comment]
By now, we have documented at https://github.com/gap-system/gap/wiki/Changes-between-GAP-4.7-and-GAP-4.8 and Changes manual all items mentioned in this issue that have to be announced with the beta release. I am closing this issue, which is the last open issue for GAP 4.8.0 milestone. Testing of the release candidate is underway.
