### ISSUE TITLE
HPC-GAP: `MakeReadOnly` name is potentially confusing (compared to `MakeReadOnlyGlobal`)

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1836]
HPC-GAP introduces a new global library function  `MakeReadOnly(obj)`, which moves `obj` into the readonly region.

However, this name is very similar to `MakeReadOnlyGlobal`, which has been around forever.

The two have virtually nothing in common; in particular, `MakeReadOnlyGlobal` acts on the "gvar slot" (and not on the object bound to it), while `MakeReadOnly` acts on objects, not "gvar slots".

I think this may result in some really annoying programming errors, and will lead to loads of confusion for people starting out with HPC-GAP. I expect people will confuse the two constantly.

Since `MakeReadOnlyGlobal` is ancient, I think our best course of action would be to rename `MakeReadOnly`. Not sure what to call, it thought... some ideas:
* `MakeReadOnlyObject` (still easy to confuse, but at least there is a hint in the name from which one can deduce it)
* `MigrateToReadOnlyRegion` clear, but very technical. Also: much longer....
* ... [ your idea here ]

Or perhaps somebody has a better idea than renaming `MakeReadOnly`?

**Comment by stevelinton** [comment]
I'd be happy with MakeReadOnlyObject (or even MakeObjectReadOnly). If people aren't clear on the distinction between a variable and the object it refers to, they are not going to get far with concurrent programming

**Comment by fingolfin** [comment]
I tried to make this change and noticed that there is also `MakeReadOnlyObj`, which differs from `MakeReadOnly` in that it is not recursive, i.e. only modifies the object itself, not its subobjects.

Contrast this with `ShareObj` vs. `ShareSingleObj`, `MigrateObj` vs. `MigrateSingleObj` etc. -- so I now think we should rename
*  `MakeReadOnlyObj` -> `MakeReadOnlySingleObj`
* `MakeReadOnly` -> `MakeReadOnlyObj`

Drawback of this would be that now we have an old and a new meaning of `MakeReadOnlyObj` and they differ. I don't think any code outside of the GAP repository really uses `MakeReadOnlyObj`, so this is *probably* OK for now, but still annoying.

An alternative would be to use the following new names:
*  `MakeReadOnlyObj` -> `MakeReadOnlySingleObject`
* `MakeReadOnly` -> `MakeReadOnlyObject`
Arguably, spelling out "Object" is more GAP-ish than using the abbreviation "Obj" anyway.

Either way, the two packages `ZeroMQInterface` and `parallelenumeration` (both undeposited) would have to be adjusted, but that's simple enough. But this is the kind of change I'd really like to get done before GAP 4.9!

Now, if we use the names ending in `Object`, then it would make sense to also change all other HPC-GAP function ending in `Obj` to end in `Object`. A few more of these are already used by packages, most notable `LockAndMigrateObj` will be in the new GAPDoc, and `LockAndMigrateObj` as well as `MigrateObj` are used in the transgrp package. Of course that's easy enough to deal with using synonyms (and ultimately, coordinating changes with the package authors).

Thoughts?
