### ISSUE TITLE
Problem with reesmat.tst (orb+semigroups)

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1860]
This has been discussed in #1809 and was identified as a separate issue. When Semigroups package is loaded, the following diffs appear:
```
########> Diff in /circa/scratch/gap-jenkins/workspace/GAP-pkg-tested-master-q\
uicktest/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-u\
pdate-master-snapshot/tst/teststandard/reesmat.tst:693
# Input is:
ForAll(enum, x-> x in U);
# Expected output:
true
# But found:
false
########
########> Diff in /circa/scratch/gap-jenkins/workspace/GAP-pkg-tested-master-q\
uicktest/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/kovacs/GAP-pkg-u\
pdate-master-snapshot/tst/teststandard/reesmat.tst:712
# Input is:
ForAll(enum, x-> x in UU);
# Expected output:
true
# But found:
false
########
```
As @markuspf points out, this maybe related to the breaking of hash functions for permutations in "orb" package after PR #1831 which make spermutations remember their inverses.

**Comment by wilfwilson** [comment]
These diffs are present when I use the released version of Orb (4.7.6), but not when I use the master branch of Orb (which contains a fix for the hashing of permutations). So I think @markuspf is right, and this should disappear when the next version of Orb is released.

**Comment by alex-konovalov** [comment]
Waiting for the new Orb then. One could see this problem when current Orb is loaded in the new Travis test here: https://travis-ci.org/gap-system/gap-docker-master-testsuite/jobs/299400942

This Travis test allows everyone (not only to those who can access Jenkins) to see how  testinstall/standard/bugfix/extra behaves with no packages, with default packages, and with all packages loaded, using the GAP Docker container for the master branch with packages from the packages-master.tar.gz archive.

**Comment by alex-konovalov** [comment]
Picked up new Orb (and Semigroups too) - now the test is back to normal.
