### ISSUE TITLE
Teach "make bootstrap" to use `curl` if `wget` is not available

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1866]
On macOS, `curl` is available but `wget` is not.

**Comment by fingolfin** [comment]
Would be great to get this into 4.9. Shouldn't be too hard either. E.g. we could add an `etc/download.sh` shell script, which looks something like this (untested):
```sh
#/bin/sh
set -e
command -v wget >/dev/null 2>&1 && exec wget "$@"
command -v curl >/dev/null 2>&1 && exec curl -O "$@"
echo "Error, failed to download: neither wget nor curl available"
exit 1
```
Then change `Makefile.rules` to use that script.

Caveat: This disables a trick we use to make our Travis builds a bit more robust, by passing lots of extra options to wget in `etc/ci-prepare.sh`, like this:
```
make bootstrap-pkg-full WGET="wget -N --no-check-certificate --tries=5 --waitretry=5 --retry-connrefused"
```
It should still be possible to get this "robust" variant. Easiest would be to just add those options into `download.sh` (and similar options for `curl`), but I am not sure we really want that for every user. E.g. the `--no-check-certificate` worries me (and I am not sure why I added that in ae866b630fcf185a4d5a40b04fa8c4655519f97e anyway, perhaps we should just drop it?)

Another option would be to simply replace `WGET = wget -N` in `Makefile.rules` by `DOWNLOAD = etc/download.sh`, and then use `$(DOWNLOAD)` instead of `$(WGET)` later on. This, it still is possible to insert a custom download command (so any PR doing all of this should of course also adjust `etc/ci-prepare.sh` accordingly).

**Comment by fingolfin** [comment]
As @alex-konovalov correctly pointed out to me, end users won't care about these targets, so no need to get this into 4.9 (won't hurt either, of course).

**Comment by alex-konovalov** [comment]
Put this under GAP 4.10 milestone to help @cdwensley
