### ISSUE TITLE
Error message changed in testbugfix in 32-bit mode 

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1890]
In master branch I have the following recent new diff occurring in 32-bit builds:

```
########> Diff in /circa/scratch/gap-jenkins/workspace/GAP-major-release-test/\
GAPCOPTS/32build/GAPTARGET/bugfix/label/kovacs/gap4r9/tst/testbugfix/2017-06-2\
0-restrictedperm.tst:14
# Input is:
RestrictedPerm((1,2^40),[ 1, () ]);
# Expected output:
Error, Permutation literal exceeds maximum permutation degree -- 1099511627776\
\
 vs 4294967295
# But found:
Error, Permutation: <expr> must be a positive integer (not a integer (>= 2^28)\
\
)
########
```

**Comment by stevelinton** [comment]
The first messahe should be produced on a 64 bit system, the second on a 32  bit one. There is no way to test production of the first error message on a 32 bit system.

**Comment by alex-konovalov** [comment]
OK, then we have `tst/test32bit` and `tst/test64bit` directories to put two test cases there. I was surprised that it apparently passed the CI test, but indeed we are running the bugfix test only in 64-bit mode there.
