### ISSUE TITLE
Remove GMP (and possibly Boehm GC) from repository

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1898]
I'd like to eventually remove GMP (and also Boehm GC) from the repository. Why? I find it annoying to have it in the tree (e.g. it spams `git grep` results). It also throws off tools which analyze our repository (they add GMP to our line counts). I also find the whole "extern" dir somewhat confusing, so I'd like to hide it as much as possible...

As far as I can see, the main reasons we have GMP in the repository are these:
1. Developer convenience: If a developer doesn't have GMP installed globally, then GAP automatically builds a version of GMP ready to use. (This has the important subcase of a developer who only has 64bit GMP installed, but wants to test 32bit GMP).
2. User convenience: By having GMP in the repo, we also have it in the distribution, and that of course benefits users who want to compile GAP by themselves.
3. Consistency / stability of GMP version: By shipping a GMP version we "trust", we can avoid problems that occurred in the past, where certain GMP versions were buggy on some major platforms.

Thing is, we can achieve goal 2 without having GMP in the repository: We can bundle GMP as part of the release process. One might quite sensibly argue that this has the drawback of being tested only very rarely, so we'd only notice breakage when making releases, a rather infrequent process. To address this, I'd propose two things: 

1. First, we actually should test the whole release process frequently. Ideally, we could provide nightly (or at least weakly) builds of GAP for download which are created using the full (and fully automated) release process [this obviously is not meant to include the extensive and slow compatibility testing of all packages etc.; I just mean the part were we point some scripts at a git branch, and run it to make a `gap.tar.gz`).
2. The mechanism for "bundling" GMP should be integrated into the build system, so that it can easily be tested on Travis. Also, it could be used to address goal 1 (developer convenience).

Indeed, developer convenience: I think most of them will be fine installing GMP via their system package manager. Of course if you are not root on your machine, or if you need a 32bit version of GMP but don't want to install that globally (resp. your package manager has none), then it'd still be nice if GAP could build GMP for you.
But for that it's sufficient to have a build rule which is able to download GMP for you! No need to have it in the repository.

We already expect developers to be able to run `make bootstrap` to download package archives, so this adds not much more (esp. if we extend downloading to also work with `curl` instead of `wget`, see issue #1866). This also takes care of goal 3, as we can of course fix which version of GMP shall be downloaded.

So, I propose the following:
* resolve issue #1866 by providing an `etc/download.sh` (or so) script
* add build system logic to download a specific GMP version, and build that instead of the code we bundle in `extern/gmp`.
* once that works to our satisfaction, get rid of `extern/gmp` and adapt the release tools to use that build rule to download gmp, and then bundle it into the GAP release archive.
* to simplify the above, we could have a `make download-gmp` target which even work without running `configure` (to do that, I'd put the relevant make rules into a new `Makefile.shared`, and then include that from both `Makefile.rules` and `Makefile`. The same could be done with the bootstrap rules).

If that works out, I'd like to do the same with Boehm GC and libatomic (we can leave our patches as patch files, and apply them via our build system). This is also somewhat related to issue #1466.

**Comment by ChrisJefferson** [comment]
I'm not opposed to this, although I also don't care about GMP (and Boehm, and libatomic) being in the repository.

I have never gotten an out-of-tree GMP to work properly on Macs, so I do want to keep good support for the in-tree version. My only comment should be that we should make sure it's not "hard to find". The easiest way to solve this would be, if the configure script can't find GMP, to just print something like (not suggested text :) )

```
GMP not found
Either install on your OS, or run "make download-gmp".
```

**Comment by fingolfin** [comment]
Off-topic, but: I still find it really bizarre that you have problems getting GMP to work on Macs. It shouldn't be harder than anywhere else. Well, at least with either a hand-build version (GMP supports the `./configure --prefix=WHATEVER && make && make install` dance just fine), or a sane package manager (MacPorts or Fink). I would expect that even Homebrew gets something so basic right, but of course they sometimes do really weird things.

**Comment by fingolfin** [comment]
(Same for GNU readline, which works great if self compiled, or via Fink and MacPorts, and for several GAP users I know also using Homebrew)

**Comment by ChrisJefferson** [comment]
I don't really care enough, as the built in one works perfectly, but sometimes GAP doesn't build, then sometimes packages can't find the GMP I built GAP with.

The problem may well be I'm trying to use GMP from homebrew, but homebrew seems to be the most popular package manager for macs at the moment.

**Comment by ChrisJefferson** [comment]
Readline just never gets found properly by configure, configure always claims it's broken.

**Comment by ChrisJefferson** [comment]
Not for this bug report, but I always see this (multiple machines)

```
./configure --with-readline
.....
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking for rl_ding in -lreadline... no
configure: error: in `/mnt/c/Users/caj/files/reps/gap/gap':
configure: error: --with-readline was given, but test for readline failed
```

**Comment by fingolfin** [comment]
That error is because it picks up BSD readline (shipped with Mac OS X), not the real readline. Try `./configure --with-readline=/usr/local` (or wherever homebrew is installed)

**Comment by ChrisJefferson** [comment]
I see the same problem on Ubuntu.

**Comment by fingolfin** [comment]
The GMP issues also sound as if you don't tell GAP and/or packages where GMP is. Of course we could use the bad old tradition of searching in /usr/local "for the user". Personally, in the past I found this causes more problems than it solves. But on Mac OS X, it would help Homebrew users on macOS. Anyway: with the revised package build system (both autoconf and gac) I am working on right now, packages should automatically get the GMP used by GAP, so you'll have to at most tell GAP where to find GMP

**Comment by alex-konovalov** [comment]
Regarding 

>First, we actually should test the whole release process frequently. Ideally, we could provide nightly (or at least weakly) builds of GAP for download which are created using the full (and fully automated) release process [this obviously is not meant to include the extensive and slow compatibility testing of all packages etc.; I just mean the part were we point some scripts at a git branch, and run it to make a gap.tar.gz).

Of course we have weekly builds of the release candidate in Jenkins. It wraps master branch with inserted version numbers and release date, pre-built documentation, latest packages picked up for the redistribution, etc. While it sits behind the firewall, there is no obstacles to either automate publishing it by copying the archive(s) to some publicly accessible location, or have a Jenkins job which does that and may be triggered manually (so that one could evaluate test results first).

**Comment by hulpke** [comment]
A remark from someone clueless about some of the deeper innards:
I really like that I get a working GRP as part of the git pull.

I would hate it, if I had to install and maintain a GMP separately, in particular if this would have to work somewhat orthogonally to the OS upgrade, have compilation issues (I am using a Mac and their clang compiler has ideosynchrasies) or would descend into library hell by requiring special versions of glib and so on.

I could easily live with a setup that would require me to pull a GMP repository (or download a version of GMP) into a suitable directory with GAP going through the appropriate compilation process itself.

I like @ChrisJefferson 's suggestion of the 
make download-gmp 
target, which I guess would some this as I described.

**Comment by fingolfin** [comment]
@hulpke yes, my proposal included the `make download-gmp`.

Another variant would be that if configure/make detect that GMP is missing, they simply automatically download them, *if* curl or wget are installed (the former is always installed on macOS, and I think most Linux machines have curl or wget installed). If neither wget or curl are installed, it'd still error out.

Anyway, this is not something I plan to even look at closer for the near future. Also, of course staying with the current setup is an option; it's just that *I* don't want to maintain it, so if there are problems with it, somebody else hopefully steps up.

**Comment by fingolfin** [comment]
For the time being, it seems we'll have to keep supporting this, so I am withdrawing this.
