### ISSUE TITLE
Bug in the computation of a permutation group isomorphic to a group of automorphisms

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#1902]
The following bug was not present in older versions of GAP.

```
gap> g:= SmallSimpleGroup( 979200 );;
gap> a:= AutomorphismGroup( g );;
gap> Size( a );
3916800
gap> im:= Image( IsomorphismPermGroup( a ) );;
gap> Size( im );
1958400
```

I get the wrong result in GAP 4.8.7 and 4.8.8,
and also in a not too old development version.

**Comment by hulpke** [comment]
Ouch! I'll fix it.

**Comment by hulpke** [comment]
I have corrected it. The problem was that the formula for outer automorphisms for groups of type C only works for parameter n\ge 3, C2(q) needs to be considered as B_2(q) instead. This is fixed (though there is so far nor formula for type B implemented.
