### ISSUE TITLE
Add a unit test framework for C code, to test e.g. ObjInt_UInt, ObjInt_Int8, ObjInt_Int

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1917]
It would be good to have a C unit test framework where we can test dedicated kernel functions without having to come up in a "natural" way. Right now, the best one can seems to be to write C functions `FuncTEST_SOME_CODE`, export them to GAP, and then call them from there.

A general framework could also do that, but with a single function, which then is responsible for executing the whole test suite(s).
Or perhaps some other way would do -- whatever, in the end, it just would be nice to have tests for things like `ObjInt_Int8`, which used to have bugs for edge cases in the past; so it would be really good to be able to add systematic tests for such relatively self-contained functions.

See also PR #1909 for some more relevant C functions.

**Comment by ChrisJefferson** [comment]
I previously thought about doing this with a special package, although that would still require exporting the functions to the GAP level.

I started with a simple package: https://github.com/gap-packages/kerneltest . We could extend and improve this.

**Comment by fingolfin** [comment]
`ObjInt_UInt` are now tested via regular .tst files, with the help of some helper kernel functions.

For libgap, we now have started to create C based tests; this essentially allows doing what this issue describes.
