### ISSUE TITLE
Broken '~' 

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#1924]
###  Observed behaviour in 4.8.8 (and expected behaviour) 
gap> LoadPackage("rcwa");
gap> LoadDatabaseOfGroupsGeneratedBy3ClassTranspositions(6);
"3CTsGroups6"

### Observed behaviour in master branch (as reported by automated package tests)
gap> LoadPackage("rcwa");
gap> LoadDatabaseOfGroupsGeneratedBy3ClassTranspositions(6);
Error, '~' does not have a value here

**Comment by alex-konovalov** [comment]
Thanks. Just to add that something similar happened before - see
* https://github.com/gap-system/gap/issues/1133
* https://github.com/Stefan-Kohl/stefan-kohl.github.io/issues/3

**Comment by alex-konovalov** [comment]
The full error message points to `pkg/rcwa-4.5.1/data/3ctsgroups6/database.g` called from called from `ReadAsFunction( Concatenation( PackageInfo( "rcwa" )[1].InstallationPath, "/data/3ctsgroups6/database.g" ) )( )`. The file `pkg/rcwa-4.5.1/data/3ctsgroups6/database.g` has only several usages of `~`, so I've managed to create a minimal example.

1. Pasting in GAP
```
rec( trsstatusset := [1..21],
trsstatuspos := 
  ReadAsFunction(Concatenation(PackageInfo("rcwa")[1].InstallationPath,
                               "/data/3ctsgroups6/trsstatuspos.g"))(),
trsstatus := List(~.trsstatuspos,i->~.trsstatusset[i]) );
```
results in the error message
```
Error, '~' does not have a value here`
```

2. This command
```
trsstatuspos := 
  ReadAsFunction(Concatenation(PackageInfo("rcwa")[1].InstallationPath,
                               "/data/3ctsgroups6/trsstatuspos.g"))();
```
works and returns a list of integers (of length 52394)

3. Setting `trsstatuspos` directly like below also works:
```
rec( trsstatusset := [1..21],
trsstatuspos := [ 1 .. 21 ],
trsstatus := List(~.trsstatuspos,i->~.trsstatusset[i]) );
```

So it is calling `ReadAsFunction` inside `rec()` which does not work.

**Comment by ChrisJefferson** [comment]
Thanks. I'm sure I remember already fixing this bug once! But obviously we didn't add a test.

**Comment by alex-konovalov** [comment]
#1929 should fix this. 

BTW, @Stefan-Kohl, I observe a diff in RCWA tests when GAP is started with `-A` option:
```
########> Diff in /circa/scratch/gap-jenkins/workspace/GAP-pull-request-quickt\
est/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/packages/label/kovacs/GAP-pull-reque\
st-snapshot/pkg/rcwa-4.5.1/tst/rcwa_ct.tst:110
# Input is:
elm := RepresentativeAction(RCWA(Integers),[0,-7,1,2],[7,1,3,0],
                               OnTuples);
# Expected output:
<rcwa permutation of Z with modulus 15, of order 18>
# But found:
<rcwa permutation of Z with modulus 15, of order 3>
########
```

**Comment by Stefan-Kohl** [comment]
Firstly, thank you for fixing this!

Secondly, I already checked that the observed diff is harmless (otherwise I'd have reported it as well ...). It's just a matter of another representative being chosen, likely due to changes elsewhere in GAP. The result is correct (since the returned permutation moves the points in the right way), and the proper fix is to put a double semicolon after the statement in the test file.

**Comment by alex-konovalov** [comment]
It's thanks to @ChrisJefferson for the actual fix then! For the `RepresentativeAction` example, I hope the fix will appear eventually in due order.

**Comment by Stefan-Kohl** [comment]
I think harmless diff's in tests are low-priority issues, which are fixed when a new version of the package is released anyway. I'm rather pleased that presently there are so few of them, although quite some things appear to have been changed in the master branch in comparison with GAP 4.8.8.

**Comment by alex-konovalov** [comment]
> I think harmless diff's in tests are low-priority issues, which are fixed when a new version of the package is released anyway. 

That's exactly what I mean by "appear eventually in due order"... After all, it's for a package autor to decide. Please just remember to look periodically at "Packages requiring inspection" tests at https://github.com/gap-system/gap-distribution, as I certainly can not judge the harmlessness of  package diffs without package authors.
