### ISSUE TITLE
Manual refers to undocumented IsSmallList

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#1926]
`IsSmallList` is not documented but after #1905 the manual refers to it, hence building the manual results in this:
```
#I Second run through document . . .
#W WARNING: non resolved reference: rec(
  Func := "IsSmallList" )
```

**Comment by fingolfin** [comment]
I am not sure we want to document it. We can just remove the ref to it from the documentation again.

**Comment by alex-konovalov** [comment]
Either way is fine with me.
