### ISSUE TITLE
Better detection of problems with building GAP manuals in CI

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/gap#1927]
At the moment, `makemanuals` Travis test calls `make doc`, which calls `doc/make_doc` script. It will be useful if `doc/make_doc` would finish with some exit code, and we would be able to detect if the build fails. In particular, we currently need to check manually for unresolved references, and that is easy to overlook (see e.g. https://travis-ci.org/gap-system/gap/jobs/302054144 for PR #1905).

**Comment by fingolfin** [comment]
Agreed.

Note that `doc/make_doc` (or rather, the file `doc/make_doc.in` from which it is created) already tries hard to exit with a non-zero exit code if there is a problem. However, GAP itself throws a bit of a wrench into this, as it may fail with an error and then still produces exit code 0... Maybe the GAP script inside of it should start with `GAP_EXIT_CODE(1);` and end with `GAP_EXIT_CODE(0);` ; that way, if anything interrupts its execution, it should exit with code 1 (but I did not test it).

To test this works, one needs a good way to fail `make doc`, e.g. insert some invalid XML into one of the manual files?

**Comment by alex-konovalov** [comment]
Note that there is also `make check-manuals` (see #3124) which fails if some problems with cross-references are detected.

> To test this works, one needs a good way to fail make doc, e.g. insert some invalid XML into one of the manual files?

Exactly, so testing included force-pushing several versions of the pull request with errors, before arriving into its final version.
