### ISSUE TITLE
Write some text introducing HPC-GAP and warning about its status (e.g. as README.hpcgap.md)

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#1944]
Since we are going to bundle HPC-GAP, people will discover it and wonder about it.

One really bad thing that could happen is that people find it, try it, and are disappointed, and then will never consider it again. Or people may be interested, but can't figure it out.

So I think we should have a `README.hpcgap.md` which briefly says what HPC-GAP is, what its status is, how to build it, and where to learn more. Perhaps also a suggestion where to write if one wants to learn more.

**Comment by alex-konovalov** [comment]
if https://github.com/gap-system/gap/wiki/Building-HPC-GAP is up to date, that could provide half of this file...

**Comment by alex-konovalov** [comment]
Closed by #2130
