### ISSUE TITLE
Setting Pcgs and IsPcgsElementaryAbelianSeries

### ISSUE THREAD

**Issue by martin-leuner** [gap-system/gap#195]
This bug is quite hard to reproduce. Or rather it is reproducible, but hard to narrow down: I ran the same code twice within the same session and the error did reliably appear, but I failed to make a smaller example exhibiting the error.

Setup:
I have a list consisting of about 370,000 sets and a fixed group. I want to compute stabilisers and their StructureDescription:

```gap
gap> Set( List( efs, f -> StructureDescription( Stabiliser( aut, f, OnSets ) ) ) );
```

This works fine for more than 300,000 sets. Then:

```gap
Error, List Element: <list>[6] must have an assigned value in
  return pcgs!.depthMapFromParent[DepthOfPcElement( ParentPcgs( pcgs ), elm )]; called from
DepthOfPcElement( p, Comm( x, k ) ) called from
func( elm ) called from
ForAny( p{ran}, function ( x )
      return DepthOfPcElement( p, Comm( x, k ) ) < n[j];
  end ) called from
func( elm ) called from
ForAny( p{ran}, function ( k )
      return ForAny( p{ran}, function ( x )
              return DepthOfPcElement( p, Comm( x, k ) ) < n[j];
          end );
  end ) called from
IsPcgsElementaryAbelianSeries( Pcgs( G ) ) called from
PcgsElementaryAbelianSeries( G ) called from
CompositionSeriesUnderAction( act, G ) called from
AllInvariantSubgroupsWithQProperty( G, G, ReturnTrue, ReturnTrue, rec(
     ) ) called from
NormalSubgroups( G ) called from
DirectFactorsOfGroup( N[j] ) called from
DirectFactorsOfGroup( G ) called from
StructureDescription( Stabiliser( aut, f, OnSets ) ) called from
func( C[i] ) called from
<function "List">( <arguments> )
brk> Position( efs, f );
300658
```

But if I try this case outside of the loop, it works:
```gap
brk> StructureDescription( Stabiliser( aut, efs[300658], OnSets ) );
"S3 x S3 x S3"
```

If I take a smaller list, say 30 entries up to and including the failing one, the error also doesn't appear. Up to now I have only been able to observe the error when running the loop on the complete list.

What I've been able to gather: If the error appears, the Pcgs of the group G have been set via InducedPcgsWrtHomePcgs and they are a little strange:

```gap
brk> G;
<permutation group of size 36 with 3 generators>
brk> GG := Group( GeneratorsOfGroup(G) );
<permutation group with 3 generators>
brk> Pcgs(G);
Pcgs([ (4,6)(10,12)(15,17)(19,21)(23,26)(25,28)(31,33)(36,38)(40,42)(44,
    47)(46,49)(51,53)(55,57)(59,62)(61,64)(65,67)(69,72)(71,74)(75,78)(77,
    80)(82,84), (2,10,6,8,4,12)(3,9)(5,11)(7,13)(14,19,21)(15,24,17)(16,23,
    26)(18,25,28)(29,31,33)(35,55,42,50,40,57)(36,60,38,51,45,53)(37,59,47,
    52,44,62)(39,61,49,54,46,64)(41,56)(43,58)(48,63)(65,76,67)(66,75,
    78)(68,77,80)(69,81,72)(71,83,74)(73,82,84),
  (1,3)(8,14)(10,19)(11,20)(12,21)(13,22)(29,35)(31,40)(32,41)(33,42)(34,
    43)(51,65)(52,66)(53,67)(54,68)(59,75)(60,76)(61,77)(62,78)(63,79)(64,
    80) ])
brk> Pcgs(GG);
Pcgs([ (1,3)(8,14)(10,19)(11,20)(12,21)(13,22)(29,35)(31,40)(32,41)(33,
    42)(34,43)(51,65)(52,66)(53,67)(54,68)(59,75)(60,76)(61,77)(62,78)(63,
    79)(64,80), (1,9,3)(2,8,14)(4,10,19)(5,11,20)(6,12,21)(7,13,22)(29,50,
    35)(31,55,40)(32,56,41)(33,57,42)(34,58,43)(36,51,65)(37,52,66)(38,53,
    67)(39,54,68)(44,59,75)(45,60,76)(46,61,77)(47,62,78)(48,63,79)(49,64,
    80), (4,6)(10,12)(15,17)(19,21)(23,26)(25,28)(31,33)(36,38)(40,42)(44,
    47)(46,49)(51,53)(55,57)(59,62)(61,64)(65,67)(69,72)(71,74)(75,78)(77,
    80)(82,84), (2,6,4)(8,12,10)(14,21,19)(15,17,24)(16,26,23)(18,28,
    25)(29,33,31)(35,42,40)(36,38,45)(37,47,44)(39,49,46)(50,57,55)(51,53,
    60)(52,62,59)(54,64,61)(65,67,76)(66,78,75)(68,80,77)(69,72,81)(71,74,
    83)(73,84,82) ])
brk> IsPcgsElementaryAbelianSeries(Pcgs(GG));
true
brk> IsPcgsElementaryAbelianSeries(Pcgs(G));
Error, List Element: <list>[6] must have an assigned value in…
```

I can upload a 19 MB file with my input for this bug, but you would have to wait several hours before the error appears. If you have any ideas on how to narrow down this bug I would try that first.

**Comment by martin-leuner** [comment]
Just now a run in a fresh session with some garbage code beforehand errored out:

```gap
gap> q := List([1..50], z -> List([1..2000], x -> List([1..x], y -> y)));;
gap> Read( "bug-input.g" );
gap> Set( List( efs, f -> StructureDescription( Stabiliser( aut, f, OnSets ) ) ) );
Error, List Element: <list>[6] must have an assigned value in
  return pcgs!.depthMapFromParent[DepthOfPcElement( ParentPcgs( pcgs ), elm )]; […]
you can 'return;' after assigning a value
brk> Position( efs, f );
306689
```

The occurrence of the error at a different position seems to suggest some issue with the memory management.

**Comment by hulpke** [comment]
> On Jul 28, 2015, at 1:14 PM, Martin Leuner <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> Just now a run in a fresh session with some garbage code beforehand errored out:
> 
> gap> q := List([1..50], z -> List([1..2000], x -> List([1..x], y -> y)));;
> gap> Read( "bug-input.g" );
> gap> Set( List( efs, f -> StructureDescription( Stabiliser( aut, f, OnSets ) ) ) );
> Error, List Element: <list>[6] must have an assigned value in
>   return pcgs!.depthMapFromParent[DepthOfPcElement( ParentPcgs( pcgs ), elm )]; […]
> you can 'return;' after assigning a value
> brk> Position( efs, f );
> 306689
> The occurrence of the error at a different position seems to suggest some issue with the memory management.
> 

Or random elements — not that it makes it easier ….

   Alexander

**Comment by hulpke** [comment]
Another observation:

> What I've been able to gather: If the error appears, the Pcgs of the group G have been set via InducedPcgsWrtHomePcgs and they are a little strange:
> brk> G;
> <permutation group of size 36 with 3 generators>
> brk> GG := Group( GeneratorsOfGroup(G) );
> <permutation group with 3 generators>
> brk> Pcgs(G);
> Pcgs([ (4,6)(10,12)(15,17)(19,21)(23,26)(25,28)(31,33)(36,38)(40,42)(44,
>     47)(46,49)(51,53)(55,57)(59,62)(61,64)(65,67)(69,72)(71,74)(75,78)(77,
>     80)(82,84), (2,10,6,8,4,12)(3,9)(5,11)(7,13)(14,19,21)(15,24,17)(16,23,
>     26)(18,25,28)(29,31,33)(35,55,42,50,40,57)(36,60,38,51,45,53)(37,59,47,
>     52,44,62)(39,61,49,54,46,64)(41,56)(43,58)(48,63)(65,76,67)(66,75,
>     78)(68,77,80)(69,81,72)(71,83,74)(73,82,84),
>   (1,3)(8,14)(10,19)(11,20)(12,21)(13,22)(29,35)(31,40)(32,41)(33,42)(34,
>     43)(51,65)(52,66)(53,67)(54,68)(59,75)(60,76)(61,77)(62,78)(63,79)(64,
>     80) ]

These permutations generate a group of order 36 (indeed the same as GG), but there are only 3 — so this is not a valid pcgs.

A.

**Comment by martin-leuner** [comment]
Yeah, seems to be random elements. A fresh run with no Random calls beforehand consistently fails at position 306689, a run with a hundred Random(Integers) calls consistently fails at position 38494, regardless of the amount of memory used beforehand.

**Comment by hulpke** [comment]
Thanks for testing. Could you try one more thing:

Before each iteration of the calculation, save the state of the random number generator. Run until if gets an error. Exit the break loop.
Reset the random number generator to the stored state. Call the same calculation again. Does it run again in the error? If so we might have a reproduceable short example.

**Comment by martin-leuner** [comment]
I actually tried that last evening and against my expectation it did not work:
```gap
gap> for f in efs do lastGMTState := State( GlobalMersenneTwister ); StructureDescription( Stabiliser( aut, f, OnSets ) ); od;
Error, List Element: <list>[6] must have […]
brk> Position(efs,f);
38494
brk>
gap> Reset( GlobalMersenneTwister, lastGMTState );; StructureDescription( Stabiliser( aut, efs[38494], OnSets ) );
"S3 x S3 x S3"
```

**Comment by hulpke** [comment]
As I forgot to reply to this earlier:

I look at this as an issue in CRISP and will not investigate further.

**Comment by alex-konovalov** [comment]
@hulpke Thanks for reminding - I've just sent the link to the CRISP's author.

**Comment by alex-konovalov** [comment]
@hulpke it's not clear whether this is really an issue with CRISP though: I understand one of the last commentslike the faulty Pcgs is set *before* CRISP constructs a subgroup. Anyhow, we need a way to reproduce this, and maybe check if it also appears in the current the master branch.

**Comment by bh11** [comment]
@martin-leuner 
Maybe it's best if you make your sample code and data available for download (probably it's too large to simply attach it here). Please also include a copy of the GAP banner (version, modules and packages loaded) at the beginning of your session.

**Comment by martin-leuner** [comment]
A 2.3 MB file with data to cause the bug is available [here](http://www.mathb.rwth-aachen.de/~leuner/pcgs-bug-data.g). You should see the error after running
```gap
List( efs, f -> StructureDescription( Stabiliser( aut, f, OnSets ) ) );
```
and waiting for about half an hour.

Here's the gap I run:
```
 ┌───────┐   GAP, Version 4.7.8 of 09-Jun-2015 (free software, GPL)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-unknown-linux-gnu-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.0, AutPGrp 1.6, Browse 1.8.6, Carat 2.1.4, CRISP 1.3.8, Cryst 4.1.12, CrystCat 1.1.6, CTblLib 1.2.2, FactInt 1.5.3, FGA 1.2.0, GAPDoc 1.5.1, IO 4.4.4, IRREDSOL 1.2.4, LAGUNA 3.7.0,
             Polenta 1.3.2, Polycyclic 2.11, RadiRoot 2.7, ResClasses 3.4.0, Sophus 1.23, SpinSym 1.5, TomLib 1.2.5
```

**Comment by bh11** [comment]
Thanks for the sample code.

This is indeed a bug in CRISP. I'm currently testing a fix.

**Comment by bh11** [comment]
I've wrapped a [new version of CRISP](http://www.icm.tu-bs.de/%7Ebhoeflin/crisp/crisp-1r3n9.tar.bz2) which fixes this bug (and which should be picked up by the GAP server shortly).

**Comment by alex-konovalov** [comment]
@bh11 Thanks - the new version of CRISP has been picked up on Monday and passes nightly tests. After the coming weekend it will hopefully pass weekly tests. Just to clarify, the CRISP overview page on the GAP site (http://www.gap-system.org/Packages/crisp.html) will provide the new version only **after** the next GAP release, which could be an update release (4.7.8 with newer packages), a minor release (4.7.9) or a major release (4.8.X) whichever will happen the first. In the meantime, @martin-leuner, please get the new CRISP version from its site and install it yourself.

If this is an important bugfix, we may consider this as an additional stimulus to make an update or minor release sooner.

**Comment by martin-leuner** [comment]
@alex-konovalov Sure, thanks for the fix, @bh11. Judging by the super low frequency with which the bug appeared in my tests this shouldn't be a fix warranting an early release, although I obviously don't know in what other circumstances the bug might crop up.
