### ISSUE TITLE
Info backtraces give incorrect location

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#198]
The following function:

```f := function() local S; S := []; Info("cheese", 2); end;```

Gives incorrect backtrace information. I plan to fix this, but noting so I don't forget.

**Comment by alex-konovalov** [comment]
Just to check, is this the same what you're observing?
```
gap> f := function() local S; S := []; Info("cheese", 2); end;
function(  ) ... end
gap> f();
Error, Usage : InfoDecision(<selectors>, <level>) called from
<compiled or corrupted statement>  called from
<function "f">( <arguments> )
 called from read-eval loop at line 2 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
```

**Comment by ChrisJefferson** [comment]
Yup, that ```<compiled or corrupted statement>``` should be ```Info("cheese", 2);```, with a line number (if appropriate)

**Comment by alex-konovalov** [comment]
Technically, `Info` is a keyword and not a function, so it is indeed called from a compiled statement because the call is in the GAP kernel. I am not sure if the backtrace information may be reported any better.

**Comment by ChrisJefferson** [comment]
Was just looking at this, as you replied. I now get:

```
Error, Usage : InfoDecision(<selectors>, <level>) called from
Info( "cheese", 2 ); on line 1 of file *stdin* called from
<function "f">( <arguments> )
 called from read-eval loop at line 2 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
```

**Comment by alex-konovalov** [comment]
Ah, nice! Looking forward to new PR.

**Comment by stevelinton** [comment]
No the backtrace for Info should still work. The “compiled” there refers to code produced by some versions of the GAP compiler 
which left out the backtrace information to speed up the compiled code.

S

**Comment by ChrisJefferson** [comment]
Fix in #202, including a similar problem with Assert. However, it's failing some manual tests and I don't know why.

**Comment by alex-konovalov** [comment]
Looked at logs - there was some error while building the manuals. Could you please check if 'make manuals' works in your branch?

**Comment by ChrisJefferson** [comment]
I am looking at the issue, but it doesn't look new -- it looks like we recently started testing 'make testmanuals' on both mac and linux, and it has never passed on mac.

**Comment by alex-konovalov** [comment]
Ah yes - the failing tests are only on OS X and clearly no tex is there so the build failed. Thus your PR passes the test. We need to figure out how to configure OS X slave in travis to add latex or to exclude this configuration from testing. 

This tests only whether we can build the manual so it is perfectly fine to do this only on Linux.
