### ISSUE TITLE
PrintFormattedString in GAPDoc handles [] differently to Print

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#199]
```PrintFormattedString``` in GAPDoc should be the same as ```Print```, except handling wrapping. However, it handles ```[]```, differently, for example:

```
gap> Print([]);
[  ]
gap> PrintFormattedString([]);
gap>
```

This is causing me a problem, because ```Info``` calls ```PrintFormattedString``` from GAPDoc if it is available, meaning statements like: ```Info(InfoMe, 1, [1], [], [])``` drop the empty lists.

I realise this is more a GAPDoc problem, but putting it here for now. Could be fixed by stopping Info calling out into GAPDoc, or changing GAPDoc's handling of ```PrintFormattedString``` to the same way as ```Print``` (which basically special-cases empty lists which are not StringReps).

**Comment by frankluebeck** [comment]
On Mon, Aug 24, 2015 at 09:17:55AM -0700, Christopher Jefferson wrote:
> ```PrintFormattedString``` in GAPDoc should be the same as ```Print```, except handling wrapping. However, it handles ```[]```, differently, for example:
> 
> ```
> gap> Print([]);
> [  ]
> gap> PrintFormattedString([]);
> gap>
> ```


I don't agree. ```PrintFormattedString``` does exactly what it should and
what its name suggests: it prints a formatted string (without introducing
additional line breaks). 

```
gap> IsString([]);
true
gap> Length([]);
0
```

So, in your example ```PrintFormattedString``` works correctly. 
For non-strings it (usually) runs into an error, try
```PrintFormattedString(123);```.

> This is causing me a problem, because ```Info``` calls
> ```PrintFormattedString``` from GAPDoc if it is available, meaning
> statements like: ```Info(InfoMe, 1, [1], [], [])``` drop the empty
> lists.
> 
> I realise this is more a GAPDoc problem, but putting it here for now.
> Could be fixed by stopping Info calling out into GAPDoc, or changing
> GAPDoc's handling of ```PrintFormattedString``` to the same way as
> ```Print``` (which basically special-cases empty lists which are not
> StringReps).

I don't see a problem with ```PrintFormattedString``` or GAPDoc. The problem
is that in the code in info.gi an argument [] is (correctly) identified as 
empty string, and then it is printed as such.

Maybe the code in info.gi should be changed from ```if IsString(s)``` to
```if IsStringRep(s)```.

**Comment by stevelinton** [comment]
> 
> I don't see a problem with ```PrintFormattedString``` or GAPDoc. The problem
> is that in the code in info.gi an argument [] is (correctly) identified as 
> empty string, and then it is printed as such.
> 
> Maybe the code in info.gi should be changed from ```if IsString(s)``` to
> ```if IsStringRep(s)```.
> 

Yes. Sounds right.

**Comment by ChrisJefferson** [comment]
@frankluebeck Yes, you are right. I mis-read the documentation for IsFormattedString.

I might go further, and do what 'Print' does internally, which is:

```if (IsString(s) and Length(s) > 0) or IsStringRep(s)```, which just catches the empty list case, in case people build strings as non-string reps.
