### ISSUE TITLE
Update CONTRIBUTING.md and README.md

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#2]
These two files are to be sharpened and updated to our needs, preferably really soon.

**Comment by alex-konovalov** [comment]
These files are written in the **Markdown** format, and you may find its short description in GitHub help pages [here](https://help.github.com/articles/markdown-basics/).

**Comment by alex-konovalov** [comment]
I am revising these two files in my fork and will submit a pull request for you to review later.

**Comment by alex-konovalov** [comment]
You may see my changes in https://github.com/alex-konovalov/gap/commit/081b57547c570f163d7edf3e0f2256796a74afec. Any other suggestions before I will submit a pull request? I am also working on a PDF "Quickstart" document for developers, which we may put on [Wiki](https://github.com/gap-system/gap/wiki)

**Comment by markuspf** [comment]
Closed with #3
