### ISSUE TITLE
ModuleState is not properly initialized in kernel extensions

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2013]
Right now, module constructors are only run once, during `InitializeGap`. Thus if a module is loaded late on, as part of a kernel extension in a package, its module state constructor is *not* run. Contrast this to its initKernel and initLibrary functions, were great care is taken to also run them for module loaded like this.

In single threaded GAP, a package can easily work around this, as you can simply not use a module constructor and instead put everything into your `InitLibrary` function. But for HPC-GAP, this means that in all already running states, a packages module state would not be initialized.

Of course no packages uses module state yet, simply because no package kernel extension takes advantage of HPC-GAP yet (or even bothers to try to be compatible). But in order to not prevent them from doing so, we'd have to solve this issue.

The obvious fix is to add the relevant calls to the constructor (if any) to `READ_GAP_ROOT`, `FuncLOAD_DYN` and `FuncLOAD_STAT`. (And while we are it, it seems these functions do not  bother to check whether `info->initLibrary != 0`, which they should).

Right now, that would mean extending the interface exposed by `gapstate.{c,h}` to include a way to run the constructor of a single module, say by using its name.

I think the more elegant solution, which IMHO also fits in better with the traditional module interface, is to add `initModuleState` and `deinitModuleState` members to struct `StructInitInfo`, instead of passing them to `RegisterModuleState`. This way, it's trivial to find and call the right module state methods when loading a kernel extension.

While I am at it, I think `doc/dev/kernel.xml` then should be updated to mention when exactly `initModuleState` is called, relative to `initKernel`/`initLibrary`, and what to move into it vs. `initLibrary`. (Maybe that should also be in a comment for struct

**Comment by ChrisJefferson** [comment]
I like the idea of putting them into the struct, and putting them at the end shouldn't break any packages (might produce warnings of course, but that's fine, and there won't even be that after they switch to C99 initalisers)
