### ISSUE TITLE
Regression: parser ignores anything after `?`

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2017]
This regression was introduced by PR #1886, which introduced `S_HELP` to the parser. 

First off, if `?` is not the first non-space thing on an input line, it eats up all input after it (so almost like `#`, except the semicolon `;` is still handled). Example:
```
gap> 1?hello world, this is so much fun!!!;
1
gap> 1??;
1
```
For reference, this is what I get in GAP 4.8.8:
```
gap> 1?hello world, this is so much fun!!!;
Syntax error: ; expected
1?hello world, this is so much fun!!!;
 ^
Error, Variable: 'hello' must have a value
not in any function at line 6 of *stdin*
gap> 1??;
Syntax error: ; expected
1??;
 ^
```

I guess we'll want to raise an error in `GetHelp()` if the `?` did not occur at the start of the line. So we could just check `GetLinePosition() == 0`. Of course that would mean it is not anymore possible to add spaces before a help query; but then, this is also how it was in GAP 4.8, so it would be an acceptable loss, IMHO. That said, of course it would be nicer to allow the user to add those spaces in front of the help query.

**Comment by fingolfin** [comment]
The idea of using `GetLinePosition() == 0` is of course bollocks:
```
gap> 1
> ?hello'
1
```

What we really want is a way to enforce that `S_HELP` is only accepted as first symbol of a statement.

We might even want to restrict it to interactive input. That would suggest removing it from `STATBEGIN` and `ReadStats()` and then special casing it in `ReadEvalCommand`? Or perhaps there should be a flag in the reader which indicates "this is the start of a fresh interactive input", which is set to 0 / false at the end of `GetSymbol`; then `GetHelp` checks that flag; if it is 0, it immediately produces an error. Otherwise it proceeds like now.

**Comment by ChrisJefferson** [comment]
I'm curious what is going on here -- I would expect the parser to reject this for the same reason it would reject any invalid expression, like '1 1'.

**Comment by fingolfin** [comment]
Perhaps because the number parsing is very lenient. E.g. from `ReadLongNumber`:
```C
       /* remember the current symbol and get the next one */
       status = STATE(Symbol);
       Match(STATE(Symbol), "partial number", follow);

       /* Now there are just lots of cases */
       switch (status) {
       case S_PARTIALINT:
         switch (STATE(Symbol)) {
...
         default:
           len = appendToString(string, len);
           IntrLongIntExpr(string);
           done = 1;
         }
         break;
```
So this is overly generous...

**Comment by fingolfin** [comment]
Actually, while I still find that code suspicious, this is a red herring. We end up in `GetHelp` via `ReadLiteral`, which matches away an `S_INT` and gets the next symbol.

We then return through the call stack, back to `ReadExpr`, and finally to `ReadEvalCommand`. Which does:
```C
    /* every statement must be terminated by a semicolon                  */
    if (!IS_IN(STATE(Symbol), S_SEMICOLON) && STATE(Symbol) != S_HELP) {
        SyntaxError( "; expected");
    }
```
And that's what is producing the error if you enter `1 1` or `1 1;` -- and we skip it, as we now are looking at `S_HELP`. The problem is that we have no good way to tell if `S_HELP` is the first symbol we are reading, or not.

And for some added fun:
```
gap> 1 1 ?1;
Syntax error: ; expected
1 1 ?1;
  ^
Help:  No such topic.
```

**Comment by fingolfin** [comment]
Also this, which shows that the problem really predates the `S_HELP` code:
```
gap> 1 1 1;
Syntax error: ; expected
1 1 1;
  ^
1
```

**Comment by alex-konovalov** [comment]
This goes into 4.9.2, if it will be fixed by then.
