### ISSUE TITLE
Problem with Ctrl-C interruption 

### ISSUE THREAD

**Issue by frankluebeck** [gap-system/gap#2044]
### Observed behaviour
Running the following code in GAP master branch
```
gap> while true do od;
```
I cannot interrupt the loop with Ctrl-C (but I can stop gap with double Ctrl-C).

### Expected behaviour
The loop should be interruptable, as it was in all older versions of GAP which I tried (at least up to 4.8.6).

**Comment by fingolfin** [comment]
Ouch. That's a major regression.

**Comment by ChrisJefferson** [comment]
This was caused by making T_EMPTY a non-interruptable TNUM.

**Comment by ChrisJefferson** [comment]
(I don't have time to prepare a PR for this right now, sorry)
