### ISSUE TITLE
Changed default behaviour of Test

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#2049]
The documented default for the `showProgress` component
of the optional argument record for `Test` was `false` up to GAP 4.8.8.
In the master branch, the documented default is `"some"`.
This means that every personal test setup will have to be changed
in order to set the value explicitly to `false`.
Was this change really intended?

**Comment by fingolfin** [comment]
Yes, the change was intentional -- at least I certainly did not change the behaviour *and* the documentation in lock step by accident ;-), and it was also explicitly discussed during review, and approved by multiple people.

I am not sure what you mean with "every personal test setup will have to be changed". I certainly didn't have to change anything, nor am I aware of anybody else, so you are the first one from whom I here concerns about this. OTOH, several people already expressed to me that they considered the new behavior a nice improvement over what we had before.

Perhaps you could elaborate what you consider your "personal test setup", and in how far this changed default requires action on your part? Then perhaps we can find a way to suitably accommodate all our needs.

**Comment by ThomasBreuer** [comment]
I would say that the new behaviour makes sense at most
when one calls `Test` in an interactive session.
My test setup takes input files that contain (among other things) several `Test` calls,
and writes the output to some files.
I see no other way to avoid progress messages in these files
(where they are certainly useless) than to add a second argument to the `Test` calls.
Did I miss something?

**Comment by fingolfin** [comment]
I see. (I always use `TestDirectory` and never pipe output `Test` anywhere, but I think @alex-konovalov does that in the Jenkins setup, so I assume he may have encountered this as a problem, too?)

Hmm, we discussed disabling the progressive output (resp. changing the default back to `false`) whenever GAP's output is not attached to a terminal. But apparently this was never implemented?!?

I'll take a look, and perhaps I can implement this. Would that resolve the problem for you?

**Comment by alex-konovalov** [comment]
When the new setup is used on Travis, then it's cleverly omits line counts. This is not the case in Jenkins, so indeed I see something like 
```
# line 69 of 75 (92%)
# line 71 of 75 (94%)
# line 73 of 75 (97%)
# line 75 of 75 (100%)
                                    
     419 ms (393 ms GC) and 1.53MB allocated for zmodnze.tst
-----------------------------------
total    130577 ms (54755 ms GC) and 6.99GB allocated

#I  No errors detected while testing

=========OUTPUT END: testinstall with packages=========
```
In the logs. I was considering suggesting an option to disable that, but decided that I actually like it - I can see where exactly the test segfaulted or run out of time, while this is unclear without progress indicators. Of course, test logs became bigger, but they are searchable, so I can search for example for `> Diff` and for `===OUT` to jump to interesting places.

Summarising, I think this option may be useful, although I might not be interested it applying in Jenkins.

**Comment by ThomasBreuer** [comment]
Thanks for the additional information.
If the progress messages would disappear automatically from logfiles
then this would be fine,
but if I am the only user who does not like the current feature
then it is not worth to waste time on another change of its implementation.

**Comment by ChrisJefferson** [comment]
Are you saving gap's output with lotto, or redirecting from the command line?

It might be reasonable to add a function which checks if GAP is connected to a terminal, and then only display extra info in that case, but then the messages would still appear when LogTo is in use.

**Comment by ThomasBreuer** [comment]
Concerning @ChrisJefferson's question:
I am using input/output redirection.

Concerning the idea to detect whether GAP is running in a terminal,
a simpleminded way to achieve this would be to set the TERM environment variable to `dumb`
in the beginning of a redirected GAP session,
and to check for `GAPInfo.SystemEnvironment.TERM = "dumb"` in the GAP session.
(Of course it would be more elegant if GAP could find out itself
whether there is a terminal or not.)

**Comment by fingolfin** [comment]
I will create a PR where I add a kernel function to query whether input resp. output are connected to a tty -- we already have that information readily available (well, I think at least, let's see how it works out ;-)
