### ISSUE TITLE
Development Manual

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#205]
This manual was separated from the main repo when we were moving systems, and it was a useful 
pathfinder for new tools. It should be reunited now (and probably edited). This is blocking PR #54

**Comment by alex-konovalov** [comment]
the development manual is now in https://github.com/gap-system/gap-distribution/tree/master/doc/dev - do we want to make it a part of the main repository?

**Comment by stevelinton** [comment]
Ah. That's already more recent information than I had remembered. Having it in gap-distribution doesn't seem too bad.

**Comment by stevelinton** [comment]
Actually bringing them into the same repo might be a good idea, so that a single pull request can change both. Logically the documentation of RegisterTNUM should be part of PR #54, for instance.

**Comment by alex-konovalov** [comment]
Done - the new location is https://github.com/gap-system/gap/tree/master/doc/dev
