### ISSUE TITLE
Problem with ClassesSolvableGroup when called for a trivial group

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#2055]
According to the documentation of `ClassesSolvableGroup`,
the following behaviour of GAP 4.8.8
and of a not very old version of the master branch
is a bug.

```
gap> g:= DihedralGroup( 8 );
<pc group of size 8 with 3 generators>
gap> t:= TrivialSubgroup( g );;
gap> IsConjugate( t, g.1, g.2 );
false
gap> ClassesSolvableGroup( t, 4, rec( candidates:= [ g.1, g.2 ] ) );
<identity> of ...
```

(`IsConjugate` is not affected
because `ClassesSolvableGroup` does not get called in this situation.)

**Comment by hulpke** [comment]
In the current version of the code, the `candidate` elements must both lie in the group. This is in fact tested in `RepresentativeActionOp` before calling `ClassesSolvableGroup`. (It should be possible to extend this, but currently its not done.)
I see this as a bug in the documentation and will add a correction to the pending patch for 4.9.1 I have.
