### ISSUE TITLE
Remove `lib/queue.g` again?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2066]
When merging HPC-GAP in, we added `lib/queue.g` which is loaded relatively early on by the library.

But nothing uses it, and its code has been imported (in modified form) into the datastructures packages.

So, can we remove it again?

**Comment by ChrisJefferson** [comment]
If nothing uses it, we should remove it, particularly before we release 4.9.

**Comment by fingolfin** [comment]
I just discovered that it *is* used after all, namely by `hpcgap/lib/hpc/stdtasks.g`

That still leaves me wondering if we should make it HPC-only to reduce the chance of people using it and relying on it (even though it is undocumented)

**Comment by alex-konovalov** [comment]
I think it's ok to load it only in HPC-GAP mode then. This should be done before beta - I've added this to GAP 4.9.0 milestone.
