### ISSUE TITLE
Update config.guess

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#207]
The config.guess in GAP fails to recognise ppc64le. An updated version works.

**Comment by fingolfin** [comment]
I am all for that. Let's take the latest version of it, and also of config.sub, from

http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
