### ISSUE TITLE
Prints `Duplicate cookie io.c:IO_mkstemp` during startup

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#2076]
The current master branch e77c92678 prints `Duplicate cookie io.c:IO_mkstemp` during startup.

On my machine the commit 234ae0924 `kernel: permanently enable some debug checks` seems to introduce this.

**Comment by ssiccha** [comment]
This will be resolved by a new release of the `io` package.

**Comment by alex-konovalov** [comment]
@ssiccha thanks. just to add that this now fails the Travis CI test e.g. here https://travis-ci.org/gap-system/gap-docker-master-testsuite/jobs/326806278

**Comment by alex-konovalov** [comment]
IO 4.5.1 released, picked up for the redistribution and now appears in packages-master.tar.gz and other package archives for bootstrapping.
