### ISSUE TITLE
No return value of ObjectifyWithAttributes?

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#2083]
`Objectify` returns the object it has created.
I find this very convenient.
Is there any reason why `ObjectifyWithAttributes` does not return the object in question?

**Comment by fingolfin** [comment]
I am pretty sure there is no good reason. My guess would be that this was an oversight -- though @stevelinton would know best, he added the function 1998-08-10 in a commit with message "First (GAP) try at SetMultipleAttributes and ObjectifyWithAttributes".

But even if there was a reason, I don't see one now. A pull request adding `return obj;` to that function would most likely be merged (perhaps even into stable-4.9, if somebody (you?) wants it badly enough in GAP 4.9)
