### ISSUE TITLE
Long filenames in backtraces are annoying

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#21]
I want to shorten filenames from the GAP standard library in backtraces.

The development version of GAP now prints out filename and lines in backtraces. For example, given a file `t.g` in the current directory containing `f := function() Stabilizer(AlternatingGroup(5), [1.0], OnSets); end;`, then running `f()` produces the following output (on my machine):

```
gap> f();
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `^' on 2 arguments called from
act( pnt, id ) on line 439 of file /Users/caj/work/source/gap/gap/lib/oprt.gd called from
TestIdentityAction( acts, pnt, act ) on line 844 of file /Users/caj/work/source/gap/gap/lib/oprt.gd called from
CallFuncList( StabilizerFunc, arg ) on line 2841 of file /Users/caj/work/source/gap/gap/lib/oprt.gi called from
Stabilizer( AlternatingGroup( 5 ), [ 1.0 ], OnSets ); on line 2 of file t.g called from
<function "f">( <arguments> )
 called from read-eval loop at line 5 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
```

Notice that `t.g` is given a short name, but `/Users/caj/work/source/gap/gap/lib/oprt.gi` is given the full, long file-system name.

I would like to change that second one to something shorter, but I'm not sure what the best option is. Perhaps  `{GAP_ROOT}/lib/oprt.gi`? That does leave the problem that GAP can have multiple roots of course, but I feel something shorter would be better for most users.

**Comment by alex-konovalov** [comment]
Thanks for suggestion. I would prefer to keep long paths: with them it's easier to spot if things go wrong because of using wrong GAP installation (you've already mentioned multiple roots yourself), whenever interactively or looking at the test logs. Also, if I need to open that file or change into its directory, I can just copy and paste full path to it.

**Comment by markuspf** [comment]
Easy way out: Make it a user preference and have both options!

**Comment by alex-konovalov** [comment]
@markuspf :+1: for making this a user preference. I'd be happy with any choice of the default setting then.

**Comment by fingolfin** [comment]
For me, the long paths are very useful. E.g. they allow me to immediately identify and possibly open the correct files if needed.

And -1 for a user preference which about 3 people overall will ever use, at most, and all of those could just as well have a local patch applied to their GAP installation(s) doing this...

**Comment by ChrisJefferson** [comment]
I would agree with no having a preference -- I would quite like (in a seperate line of work) to try to reduce some of the options we already have in GAP, to reduce the need to support them.

There seems to be general support for full file names, so I will leave them unless in future there is a significant change in opinion -- I'll just have to start using wider terminals!
