### ISSUE TITLE
Regression for StructureDescription

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#2109]
The regular tests (for the AtlasRep package) have uncovered the following regression
in the stable-4.9 branch, according to Alexander's report.
The same happens also in the master branch.

```
gap> StructureDescription( Group( [ 
>     (1,5,15,8)(2,16,9,7)(4,11,12,6)(13,14), 
>     (1,7,12,5)(2,9,3,14)(4,6,8,13)(10,15,11,16) ] ) );
"(C2 x C2 x C2 x C2) : ((C3 x C3) : C4)"
```

In older GAP versions, the output is

```
"(A4 x A4) : C4"
```

and I think this is better.

**Comment by fingolfin** [comment]
Well, `StructureDescription` always is a heuristic, and for any heuristic, you'll be able to find examples were there are better solutions. So I am not sure how and whether we should "resolve" this.

For what it's worth, you can recover the old result (in this case) by passing the `nice` option:
```
gap> G:=Group([ (1,5,15,8)(2,16,9,7)(4,11,12,6)(13,14), (1,7,12,5)(2,9,3,14)(4,6,8,13)(10,15,11,16) ]);;
gap> StructureDescription(G : nice);
"(A4 x A4) : C4"
```

This is not the default for performance reasons, though I guess on might make it default for group orders below a certain limit (resp. for orders which have at most `N` prime factors for some constant `N`, or something like that, depending on how the performance is in practice, which I did not check)

**Comment by ThomasBreuer** [comment]
I think that performance is not an issue for functions like `StructureDescription`
or `Display`, whose output is not intended to be used programmatically.

Thanks for the hint about the option `nice`.

**Comment by fingolfin** [comment]
It is an issue when the performance can of from a few seconds to a few hours...

**Comment by frankluebeck** [comment]
In stable-4.9 or master I only get the answer `"(C2 x C2 x C2 x C2) : ((C3 x C3) : C4)"` when I start gap without the package `Crisp` (which is loaded by default). After loading `Crisp` I get `"(A4 x A4) : C4"`.

**Comment by fingolfin** [comment]
So the "nicer" description can be obtained by either loading the `crisp` package, or by passing the `nice` option. That's good of course.

The problematic (i.e. slow) cases of `StructureDescription` seem to be p-groups (and thus also groups with certain large p-sylow subgroups, or large normal p-subgroups). Here are some numbers, with and without crips, for a group of order 64:
```
gap> StructureDescription(SmallGroup(64,266)); time;
"((C4 x C2) : C2) : (C2 x C2)"
8445
gap> StructureDescription(SmallGroup(64,266) : nice); time;
"(C4 x C2 x C2) : (C2 x C2)"
36404
gap> LoadPackage("crisp", false);;
gap> StructureDescription(SmallGroup(64,266)); time;
"(C2 x ((C4 x C2) : C2)) : C2"
233
gap> StructureDescription(SmallGroup(64,266) : nice); time;
"(C4 x C2 x C2) : (C2 x C2)"
37111
```

So without packages, the time for a description goes from ~8 seconds to ~36. With crisp, the difference is more dramatic, it goes from `1/4 of a second to ~37 seconds.

I did not try to find the slowest example here, I picked one at semi-random. There are examples of order 128 and 256 where the difference is even worse.

OTOH, for non-prime power orders, things are better. But still, the `nice` option makes an impact: Testing all non-p groups of order up to 100 in the small groups library:
```
gap> ords := Filtered([1..100], n -> not IsPrimePowerInt(n));;

# base case: time to just create the group objects
gap> for n in ords do for k in [1..NrSmallGroups(n)] do G:=SmallGroup(n,k); od; od; time;
527

# compute descriptions w/o crisp
gap> for n in ords do for k in [1..NrSmallGroups(n)] do StructureDescription(SmallGroup(n,k)); od; od; time;
16081
gap> for n in ords do for k in [1..NrSmallGroups(n)] do StructureDescription(SmallGroup(n,k) : nice); od; od; time;
78830

# now times with crisp
gap> LoadPackage("crisp", false);;
gap> for n in ords do for k in [1..NrSmallGroups(n)] do StructureDescription(SmallGroup(n,k)); od; od; time;
10307
gap> for n in ords do for k in [1..NrSmallGroups(n)] do StructureDescription(SmallGroup(n,k) : nice); od; od; time;
70215
```

So on average, that's "just" a factor of 5-8 in performance, but in practice there are quite some examples there where the overhead is much bigger, and at some point, quite visible to the user.

All in all, that means while we can certainly try to tweak output for certain input ranges, I don't think we can hope for "optimal" output in general.

**Comment by fingolfin** [comment]
I suggest to close this as "wont fix".

**Comment by ThomasBreuer** [comment]
Closing this isue is o.k. for me, meanwhile I know how to avoid `StructureDescription`.
