### ISSUE TITLE
Set PKG_BRANCH to stable-4.9 in bootstrap rules for stable-4.9 branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#2111]
This is a reminder that when stable-4.9 branch will stabilise and we will stop merging it into master, one should set `PKG_BRANCH` to `stable-4.9` below:

https://github.com/gap-system/gap/blob/483ec5c27fced5250ca4bfa5dc5a3e85a454bce3/Makefile.rules#L980-L988

We don't do it now, to ease merging of stable-4.9 branch into master, which may still happen. Package archives for stable-4.9 and master branch are at the moment identical, so it does not cause any problems (but they may diverge in the future).

**Comment by fingolfin** [comment]
I don't see why you can't do that right now! Either we stop merging `stable-4.9` into master after that. Or, if you think we still might want to do that, simply perform a "dirty" merge right afterwards -- here with dirty I mean that you merge, but inside the merge commit, you revert the change to `Makefile.rules`. By doing that, any future merge will not attempt to copy over the `Makefile.rules` changes again.
(As a variant, you can perform a regular merge, followed by a "revert" commit for the commit which changed `Makefile.rules`, that's perhaps a bit easier to understand when looking at the history).

**Comment by alex-konovalov** [comment]
Closed by https://github.com/gap-system/gap/commit/9be943f3b27493d871a8849f35c11745af1c956a

(was no rush, since archives are at the moment identical, but as we stopped merging stable-4.9 into master, no need to delay this either).
