### ISSUE TITLE
LiePRing package does not load in master branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#2120]
Loading LiePRing package in the master branch results in 

```
Error, <filter> must be a filter at /Users/alexk/GITREPS/gap/lib/oper.g:1295 called from
<function "DeclareAttribute">( <arguments> )
 called from read-eval loop at /Users/alexk/GITREPS/gap/pkg/liepring/gap/liering.gd:36
```

This happens because of the following declarations in `liepring/gap/liering.gd` around line 36:

```
DeclareAttribute( "IsLiePRing", IsRing );
DeclareAttribute( "ClassOfLiePRing", IsLiePRing );
```
which should be replaced by 

```
DeclareProperty( "IsLiePRing", IsRing );
DeclareAttribute( "ClassOfLiePRing", IsLiePRing );
```

because one can not specify an attribute as a filter. This has been revealed after refactoring `DeclareAttribute` in #2078.

**Comment by alex-konovalov** [comment]
To ensure that GAP regression tests continue to work in the master branch, I've disabled LiePRing for the master branch, see https://github.com/gap-system/gap-distribution/commit/9f04acc9e965b9d2a265f2388bcea97c89802b24 

This allows the tests to run, but will not help to reveal any other impacts that future changes in the master branch may have on the package. As soon as there will be a new release with a fix, I will enable the package back. 

The package is still enabled in stable-4.9 branch.

**Comment by fingolfin** [comment]
This will be fixed in the next liepring release.

**Comment by fingolfin** [comment]
The new liepring release which fixes this is out now.
