### ISSUE TITLE
`PrimitivePolynomial` throws errors on integer inputs

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#2134]
`PrimitivePolynomial(1);` throws an error in the current master branch. I would expect it to just return `[1,1]`. Does anything speak against this?

Installing a trivial method for integers and/or rational numbers should be sufficient.

```
gap> PrimitivePolynomial(1);
Error, no method found! For debugging hints type ?Recovery from NoMethodFou\
nd
Error, no 1st choice method found for `PrimitivePolynomial' on 1 arg\
uments at /home/sergio/projects/gap-master/lib/methsel2.g:250 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at *stdin*:8
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```

**Comment by fingolfin** [comment]
1 is not a polynomial, so why would you expect this?

**Comment by fingolfin** [comment]
Argh, I misread, that's of course nonsense

**Comment by ssiccha** [comment]
Well, I think it would be nice to have. Unless something speaks against it like forcing users to make themselves aware that they could e.g. use `x^0`.

**Comment by fingolfin** [comment]
I don't understand your remark on `Factors`. Which problem do you observe?

**Comment by ssiccha** [comment]
@fingolfin Hmm, essentially this:
```
QX := PolynomialRing(Rationals, "x");
Factors(QX, 1);
```
Although now that I write it like this it seems weird to want / allow this to just return `[QX.1^0]`.

But maybe instead one could install methods that print "helpful" error-messages into `PrimitivePolynomial` and `Factors`?

**Comment by fingolfin** [comment]
Well, in both of these cases, 1 is not a polynomial, so I don't find them surprising. The surprise only comes if one believes that a ring R is a subset of any polynomial ring over R. While this is at times a helpful intuition, in others it is not; and in GAP, it also simply not true on a technical level.

Sure, we allow adding integers to polynomials, also for convenience -- IMHO, mainly to make it easier to enter polynomials interactively, which usually means: for "toy" computations.

So what would the justification for the  "convenience" helpers you propose? Under which circumstances would they be useful? The only I can think of is interactive input -- but who would want to compute the primitive polynomial of 1, or its factors?

OTOH, for programs, catching invalid inputs helps debugging, and silently accepting it can make it harder to discover them.

Hence, I am not (yet?) convinced that adding either of these would be beneficial.

**Comment by alex-konovalov** [comment]
OTOH:
```
gap> QX := PolynomialRing(Rationals, "x");
Rationals[x]
gap> Factors(QX,One(QX));
[ 1 ]
gap> Factors(QX,5*One(QX));
[ 5 ]
gap> PrimitivePolynomial(One(QX));
[ 1, 1 ]
```
- this is a way to proceed.

**Comment by ssiccha** [comment]
@fingolfin I always use `List` and in this case I  had a list of polynomials starting with a `1`.

IMO this issue can be closed and instead it would be better to "just" make the method selection error messages generally more helpful.

**Comment by ssiccha** [comment]
@alex-konovalov I think this is just `One(QX)` being printed as `1` instead of `X^0`.
