### ISSUE TITLE
Release notes for GAP 4.10

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#2139]
To keep up with changes in the master branch and picking up relevant items for GAP 4.10 release notes, there is a Wiki page with a query to pick up PRs which have been merged but do not have appropriate labels yet. Please visit it periodically and check for any unprocessed PRs: https://github.com/gap-system/gap/wiki/GAP-4.10-release-notes

**Comment by fingolfin** [comment]
Is there any point in keeping this issue open? What purpose does it serve?

**Comment by alex-konovalov** [comment]
It is assigned to milestone 4.10.0 and will be shown in its [TODO list](https://github.com/gap-system/gap/milestone/9). Please keep it as a reminder (at least it will be reminding to me).

**Comment by alex-konovalov** [comment]
Closed by #2945.
