### ISSUE TITLE
Some suggestions for the `changes` manual and the website

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2150]
I find it confusing that the changes manual orders the chapters from newer to older (i.e. first GAP 4.9, then 4.8, then 4.7), but the sections from older to newer. I think we should be consistent and always order in the same chronological direction. My preferred direction would be from newer to older, so that at the top one finds the most recent information. This is the order most changelog files, etc. use.

Another things I find confusing is that the GAP website lists descriptions of changes in GAP releases in multiple places:

* the changes manual
* the "Release history " page, a bit hidden away under http://www.gap-system.org/Download/Updates/index.html
* the "History" page, at http://www.gap-system.org/Doc/History/history.html

Of these, I feel that we could at least eliminate the "Release history" page, by merging it into the changes manual. The 4.4.x series seems to already be in the changes manual, so we "only" would have to transfer the entries for the GAP 4.3 bugfix releases. Afterwards, we could delete the pages (and perhaps in their place leave little HTML files which forward to the new locations in the changes manual, but without appearing in the site navigation).

**Comment by alex-konovalov** [comment]
I think the idea was that the chapter starts with the quite extensive overview of changes in the major release. These are quite significant, and we want them to be visible at the beginning of the chapter (on top of the page in html) so one does not have to scroll trough all minor releases to reach them. 

I am now going to add changes overview in GAP 4.9.2 release - will add them at the end of the chapter for now, let's see what others think.

**Comment by alex-konovalov** [comment]
Overview of GAP 4.9.2 release is now in #2591.

**Comment by alex-konovalov** [comment]
This is relevant to work in progress by @dimpase in https://github.com/gap-system/gap/pull/3886, which  Changes manuals book into markdown.

**Comment by fingolfin** [comment]
This got a bit better with the recent website migration. Now I think the next step could be to add to https://www.gap-system.org/Doc/History/history.html also a link to https://www.gap-system.org/Releases/ and vice versa; and the latter could also point to https://github.com/gap-system/gap/blob/master/CHANGES.md *or a nicer HTML version that we could put somewhere*.

Afterwards, this issue could IMHO be closed.

**Comment by fingolfin** [comment]
This is OK now (modulo the fact that website needs a major overhaul)
