### ISSUE TITLE
Incorrect use of VERSION in SymbCompCC package

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#2153]
I've noticed that the following problem breaks tests of release candidates of GAP 4.10.

In `pkg/SymbCompCC-1.2/gap/SchurExtensions/SchurExtensions.gd` there are lines

```
if VERSION < "4.5.0" then ;
else DeclareOperation( "SchurMultiplicator", [ IsPPPPcpGroups ] );
fi;
```

This comparison is not correct. It is only luck that `VERSION < "4.5.0"` worked until `4.9.X`. Of course now we also have GAP 4.8.10, so we may see another examples of comparing versions in the wrong way. 

First of all, to compare versions one should only use [`CompareVersionNumbers`](https://www.gap-system.org/Manuals/doc/ref/chap76.html#X787DFEB383545A49). Second, VERSION is obsolete and should be replaced by `GAPInfo.Version`.

For now, I will disable this package for the master branch because it breaks regression testing there.

P.S. The website of the package is gone, last release made in 2011, the package has a COPYING file and is distributed under GPL v2.

**Comment by fingolfin** [comment]
A new SymbCompCC release fixing this is out now.
