### ISSUE TITLE
resclasses: broken methods for \< and Difference; some other concerns

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2164]
While writing systematic test for the GAP library code in `lib/coll.gi` (see PR #2161), I discovered that my tests were broken when loading `ResClasses`, due to custom methods there. In some cases, the new results were arguably correct, just different.

But in some cases, those custom methods in ResClassses (which apply to standard library objects, i.e. not just types defined by ResClassse) are IMHO simply wrong. Since there is no issue tracker for ResClasses as far as I know, I am collecting a list of those problems I am aware of here.

While I am at it, I'll also mention some redundant methods.

## 1. Broken `\<` methods
```gap
InstallMethod( \<, "for a list of elements and a ring (ResClasses)",
               IsIdenticalObj, [ IsList, IsRing ], 0, ReturnFalse );
...
InstallMethod( \<, "for a ring and a list of elements (ResClasses)",
               IsIdenticalObj, [ IsRing, IsList ], 0, ReturnTrue );
```
These two methods change the behaviour of comparison compared to stock GAP. For example:
```
gap> GF(3) < [0*Z(3)]; # without resclasses
false
gap> GF(3) < [0*Z(3)]; # with resclasses
true
```

## 2. Redundant `IsSubset` method
The following is not needed anymore (since at least GAP 4.6)
```gap
InstallMethod( IsSubset, "for Integers and Rationals (ResClasses)",
               ReturnTrue, [ IsIntegers, IsRationals ], 0, ReturnFalse );
```

## 3. Redundant `Intersection2` methods
The GAP library already has similar methods, so the following two seem to be superfluous:
```gap
InstallMethod( Intersection2, "for a set and the empty set (ResClasses)",
               ReturnTrue, [ IsListOrCollection, IsList and IsEmpty ], 0,
               function ( S, empty ) return [  ]; end );
InstallMethod( Intersection2, "for the empty set and a set (ResClasses)",
               ReturnTrue, [ IsList and IsEmpty, IsListOrCollection ], 0,
               function ( empty, S ) return [  ]; end );
```

## 4. & 5. Broken `Difference` methods
The following method compares two domains with `=` which won't terminate in general for infinite domains. This breaks for example `Difference(Magma(1), Rationals);`. One way to fix that would be to use `IsIdenticalObj(R,R_)` instead, which would also match the comment string, which talks about "the same ring".
```gap
InstallMethod( Difference,
               "for two times the same ring (ResClasses)", IsIdenticalObj,
               [ IsDomain, IsDomain ], SUM_FLAGS,

  function ( R, R_ )
    if R = R_ then
      if   IsRing(R) then return [];
      elif IsZxZ(R)  then return ResidueClassUnion(R,[[1,0],[0,1]],[],[],[]);
      else TryNextMethod(); fi;
    else TryNextMethod(); fi;
  end );
```

The following method has multiple problems: First off, computing `IsSubset(R,S)` may not be implemented / feasible (although arguably, in that case likely no method for `Difference(R,S)` would be available; and *if* one was available, then the author of that could as well add a suitable `IsSubset` method, one would hope). Anyway, secondly and more importantly, if the `IsSubset` calls terminates and returns `true`, then `ResidueClassUnionNC` is called, for *any* ring, even rings not supported by resclasses. A simple example which is broken by this is `Difference(GF(4),[Z(2)]);`
```gap
InstallMethod( Difference,
               "for a ring and a finite set (ResClasses)", ReturnTrue,
               [ IsRing, IsList ], 0,

  function ( R, S )
    if not IsSubset(R,S) then TryNextMethod(); fi;
    return ResidueClassUnionNC(R,One(R),[Zero(R)],[],Set(S));
  end );
```

## 6. Suspicious `\-` methods
While I do not know of an immediate problem, the following two methods seem suspicious to me. E.g. I am concerned that they might cause a slowdown when doing `U - x` for, say, `U` and `x` both vectors or matrices (though I'd hope that "better" methods would be ranked higher). In any case, I don't understand why these methods exist in the first place. Looking at the surrounding code, perhaps so that one can pass in a ring for `x`? In that case, a more specific filter than `IsObject` should be used (of course then one might have to invoke `InstallMethod` multiple times, for the relevant filters).
```gap
InstallOtherMethod( \-,
                    "for residue class union and ring element (ResClasses)",
                    ReturnTrue, [ IsListOrCollection, IsObject ], 0,
                    function ( U, x ) return U + (-x); end );
...
                    "for ring element and residue class union (ResClasses)",
                    ReturnTrue, [ IsObject, IsListOrCollection ], 0,
                    function ( x, U ) return (-U) + x; end );
```

**Comment by Stefan-Kohl** [comment]
Thanks. -- I have applied some of the suggested changes to the development version of the package. Other issues mentioned are status-by-design.

**Comment by fingolfin** [comment]
What does "status-by-design" mean? 

Can one see (and perhaps try out) those changes you made somewhere? Or else, get a concrete list of those issues you resolved, and those you haven't? Thanks!

**Comment by Stefan-Kohl** [comment]
Status-bydesign means basically the same as on MO Meta: https://meta.mathoverflow.net/questions/tagged/status-bydesign.

As far as it concerns seeing or trying out the changes: there are no public repositories of the packages so far, so the answer is presently 'no'. See also my comment here: https://github.com/Stefan-Kohl/stefan-kohl.github.io/issues/2#issuecomment-363590898 .

**Comment by Stefan-Kohl** [comment]
For example, the purpose of the \< - methods is to sort residue class unions by decreasing density. -- The base ring itself has density 1, so comes first, and finite lists of elements have density 0, and therefore come last.

**Comment by alex-konovalov** [comment]
@fingolfin said 
> But in some cases, those custom methods in ResClassses (which apply to standard library objects, i.e. not just types defined by ResClassse) are IMHO simply wrong

and I can't agree more. A package should not override methods defined for other objects with different results. IMHO it would be more proper to introduced new objects called "residue class unions" and do whatever is necessary with them.

**Comment by cdwensley** [comment]
It's not currently a problem, but in the past I have had problems when developing XMod etc when ResClasses methods, with high priority, unexpectedly were applied.

**Comment by Stefan-Kohl** [comment]
@fingolfin , @alex-konovalov -- If some of you agrees to work out reasonable changes to the concepts, such that things still fit together naturally and nicely, then please set up a public repository and go ahead!
-- But PLEASE don't just erase methods which you don't like!

**Comment by alex-konovalov** [comment]
@Stefan-Kohl I agree to help with creating a public repository, setting up the webpage, and running releaseTools script to publish a release when needed. This is the first step. Then issues may be added, describing the tasks, and then maybe someone else will be interested to work on them. Could be a good student project to introduce them to objects and operations in GAP...

**Comment by fingolfin** [comment]
@Stefan-Kohl I certainly have no interest in simply deleting functionality from your package. Breaking your package is of course not desirable! But the problem at hand is that *it* is breaking other people's stuff. E.g. this report did not come out of nothing, it was triggered by me running into problems once resclasses is loaded.

Anyway, I have now seen the changes you made to resclasses, so I will summarize what happened so far (for simplicity, I numbered the subissues in my original report):

1. Unchanged
2. Removed in resclasses repository, thanks
3. Removed in resclasses repository, thanks
4. Removed in resclasses repository, thanks
5. Adjusted in resclasses repository to use the check `if IsFinite(R) or not IsSubset(R,S) then` instead.
6. Unchanged

Regarding issue 5 (the second `Difference` method I mentioned): While that's still not quite without problems (checking finiteness of a ring can be expensive, even undecidable), it is certainly an improvement, thanks! Though I think this should be further restricted to whatever kinds of rings are actually supported. For example, `Difference(Rationals, [1/2]);` or `R:=GroupRing(Integers, FreeGroup(1));; Difference(R, [R.1]);` give, without resclasses loaded, the useful error message
> Error, sorry, cannot subtract from the infinite domain <D>

While with resclasses loaded, it gives a "method not found" error for `ResidueClassUnionCons`. 

I don't mind much about subissue 6, but I do mind the first one, which changes the ordering of objects. While I understand that this is by design, I would argue that this then is bad design, as it breaks the existing "by design" behaviour of GAP, i.e., the package does not behave like a good citizen acting in good faith.
There are several possible remedies I can think of. One is to simply introduce a separate function which compares sets and other objects "by density", say, `IsLessDense`; then of course you can't write `A < B` anymore but rather have to write `IsLessDense(A, B)`. For sorting a list of objects by density, `Sort(list)` would become `Sort(list, IsLessDense)` etc.

**Comment by alex-konovalov** [comment]
@Stefan-Kohl so, shall I set up public repositories for ResClasses and RCWA, made from those you access in St Andrews? With the end of life of that machine coming nearer, and your two repositories being the only ones that are still in use, it would be good to proceed as soon as possible.

**Comment by Stefan-Kohl** [comment]
@alex-konovalov Yes, please. -- Thanks!

**Comment by alex-konovalov** [comment]
Great - here they are:
* https://github.com/gap-packages/resclasses 
* https://github.com/gap-packages/rcwa

**Comment by fingolfin** [comment]
The first problem described above is, sadly, still present.

**Comment by fingolfin** [comment]
Those methods for "sorting by density" seem wrong to me anyhow: for a finite ring, how can it have "larger density" than e.g. the set of all its elements? Moreover, I can't see anything in the GAP manual right now that implies that lists must always be finite. So at least for every countable ring, I could implement a list object which enumerates all objects of that list. Indeed, we already have that:
```
gap> it:=Enumerator(Integers);
<enumerator of Integers>
gap> IsList(it);
true
gap> Length(it);
infinity
```

**Comment by Stefan-Kohl** [comment]
@fingolfin The methods for "sorting by density" work for unions of residue classes of the rings currently covered by the package's functionality, and for finite lists of elements of these rings. -- If you have particular improvements in mind which do not break ResClasses' or RCWA's functionality, you are welcome to go ahead and implement them!

**Comment by alex-konovalov** [comment]
Cross-posted in https://github.com/gap-packages/resclasses/issues/3. We have put ResClasses on GitHub, but never made a release after that. The repository has some changes comparatively to the last public release of ResClasses, but not the fix for the (1) above.

**Comment by fingolfin** [comment]
Point 6 of my list was resolved by https://github.com/gap-packages/resclasses/pull/4 and https://github.com/gap-packages/resclasses/pull/6. This only leaves part of point 5, which I just reported as <https://github.com/gap-packages/resclasses/issues/10>, as well as point 1, which is tracked under https://github.com/gap-packages/resclasses/issues/3

Thus we can close this issue here.
