### ISSUE TITLE
Better distinguish roles of package maintainers

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#2172]
Technical package maintenance and implementing / improving mathematical algorithms for a particular purpose are very different tasks. -- On the one hand, technical maintenance can be performed without caring about the mathematical functionality of a package, and on the other, not few people will be reluctant to delve into the software engineering aspects of package maintenance.
 
Presently there are only 'package maintainers', without further distinction. Users cannot know from this whom to send a crash report, test diff or whom to ask to prepare a new release on the one hand, and whom to ask a question on the mathematical functionality and the implemented algorithms on the other. -- Therefore I would suggest to introduce the notions of a 'technical contact' and a 'mathematical contact' for a package -- similar as for internet domains.

**Comment by alex-konovalov** [comment]
I think this may vary between different packages, so I am not convinced that this will work. 

However, I think there is indeed an underlying problem - there are packages for which original authors are not maintaining them any more, and they don't have an official maintainer. For such package, there may be a collective "The GAP Group" maintainer, meaning that anyone with appropriate permissions on this organisation on GitHub could make changes and make a release, if need be.

**Comment by Stefan-Kohl** [comment]
The present 'maintainer' would be by default just 'technical contact' + 'mathematical contact' -- so what should not work? -- The proposal is just to offer a means to describe responsibilities more precisely.

**Comment by fingolfin** [comment]
To me, anybody who is a maintainer is a contact point for anything, be it technical or mathematical. It is then up to the maintainers of a package to deal with user request's suitably, e.g. to pass them on to somebody who is actually capable of dealing with them, or to reply to user's with something like "sorry, I only take care of making releases, but not of mathematical aspects of this package; please contact XYZ for that". 

Moreover, the package's README, manual and website can already now indicate with more detail whom to contact for each kind of request (and also can point out issue trackers, support mailing lists, etc.). I don't see the added value in having a machine readable version of that information in the `PackageInfo.g` file.

**Comment by Stefan-Kohl** [comment]
@fingolfin To me as well. -- But that precisely is the point! -- Not everybody wants to be contacted about things like test diff's, variables just made obsolete, compilation problems and the ilk. -- But they may still want to show that they are the sole maintainers of their packages in terms of mathematical functionality -- at least as long as this is actually the case -- and give this appropriate visibility.

**Comment by fingolfin** [comment]
My *personal* view is that if you are not willing to deal with any kind of contacts about issues with a package, you should not be a maintainer of that package. Note: I am not saying that every maintainer should be expected to *resolve* with all kinds of requests, just that they should at least be willing to receive them, and then suitably redirect them. E.g. by replying with a (possibly canned) response like "Hi there, thanks for your report. For technical matters like this, please submit an issue at URL, then one of my co-maintainers will take care of it. I really only deal with the mathematical aspects of this package". (This is assuming there are such co-maintainers of course; for a solo maintainer, I'd expect them to, well, *maintain* all aspects of their package, including purely technical ones like failing tests).

BTW: For me, I'd expect somebody who is listed as "author + maintainer" to be a mathematical contact, somebody who is listed as "maintainer but not author" as a pure technical contact. Though I'd still expect the mathematical contact to helpfully reply to technical requests (as above).

But I also don't expect a typical GAP user to ever even notice the distinction between author/maintainer/etc. -- I assume that when they run into issues, they look at the README or manual to find out whom to contact; or perhaps they'll use one of the addresses from the package banner; or they'll contact the GAP support list (and then people there might help them get into contact with the actual package maintainers).

**Comment by alex-konovalov** [comment]
To me, @Stefan-Kohl's suggestion will introduce unnecessary additional bureaucracy for package authors, and will require from us to update PackageInfo.g format and then ask authors to update their entries. 

On the other hand, for an active package there should be no problem if a technical or mathematical request will come to any/all maintainers, and they will sort it out between themselves who does what. 

Also, remember that maintainer will learn in the process, and their roles may evolve - someone will learn more about underlying mathematics, someone about software development techniques, tools and procedures. I don't see why to limit the role in PackageInfo.g (and then have another item to remember to update).

OTOH, for orphaned packages in the need of a maintainer, we can agree on some minimal entry like

```
Persons := [
  rec(
    Organisation  := "The GAP Group",
    IsAuthor      := false,
    IsMaintainer  := true,
    Email         := "support@gap-system.org",
    WWWHome       := "https://www.gap-system.org/",
  )
```

(may require adjusting validation rules). That will mean - in case of any problems, don't try to reach authors yourself, and let the GAP group be your first point of contact.

**Comment by Stefan-Kohl** [comment]
Let's close this issue, coming to the conclusion that there is disagreement among us in this matter.

**Comment by alex-konovalov** [comment]
Thanks. I'd suggest that perhaps we may agree that there is certain problem, but we see different ways of addressing it.
