### ISSUE TITLE
Unexpected error when doing a right transversal in finitely presented groups

### ISSUE THREAD

**Issue by le-on** [gap-system/gap#2173]
When trying to do a right transversal of certain subgroups of a particular finitely presented group, the following error occurs:

### Observed behaviour
```GAP
Error, List Element: <list>[3] must have an assigned value in
  reps[n] := reps[j] * gens[i]; at /opt/gap/gap4r8/lib/grpfp.gi:5157 called from 
oper( Parent( D ), D ) at /opt/gap/gap4r8/lib/domain.gd:449 called from
attr( sub ) at /opt/gap/gap4r8/lib/domain.gd:437 called from
<function "unknown">( <arguments> )
 called from read-eval loop at line 11 of issue.g
you can 'return;' after assigning a value
```

### Code to reproduce
```GAP
s := (1,2)(3,4)(5,6)(7,8)(9,10);
t := (1,4)(2,5,9,10,8)(3,7,6);

F2 := FreeGroup("S", "T");
S := F2.1;
T := F2.2;
PSL2Z := F2 / ParseRelators([S,T], "S^2, (S*T)^3");
index := Maximum(LargestMovedPoint([s,t]), 1);
coset_table := [ListPerm(s, index), ListPerm(s^-1, index), ListPerm(t, index), ListPerm(t^-1, index)];
H := SubgroupOfWholeGroupByCosetTable(FamilyObj(PSL2Z), coset_table);
rt := RightTransversal(PSL2Z, H);
```

I'm not really sure if this is a bug or if I'm doing something wrong here, but in the case where `s := (1,2)` and `t := (2,3)` it works just fine.

### GAP banner
```GAP
 ┌───────┐   GAP 4.8.8, 20-Aug-2017, build of 2017-11-28 12:42:08 (CET)
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp
 Loading the library and packages ...
 Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.1, AutPGrp 1.8, 
             Browse 1.8.7, CRISP 1.4.4, Cryst 4.1.12, CrystCat 1.1.6, 
             CTblLib 1.2.2, FactInt 1.5.4, FGA 1.3.1, GAPDoc 1.6, 
             IRREDSOL 1.4, LAGUNA 3.7.0, Polenta 1.3.7, Polycyclic 2.11, 
             RadiRoot 2.7, ResClasses 4.6.0, Sophus 1.23, SpinSym 1.5, 
             TomLib 1.2.6, Utils 0.46
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by markuspf** [comment]
I bleive ths is a bug. The code that computes the transversal is stating that it assumes the coset table to be "Standard" (as documented in the GAP documentation). Issuing the following

```
gap> StandardizeTable(coset_table, "semilenlex");
```
yields

```
gap> rt := RightTransversal(PSL2Z, H);
RightTransversal(<fp group on the generators [ S, T ]>,Group(<fp, no generators known>))
```

@hulpke is best placed to comment, I can make a fix, too, I believe.

**Comment by hulpke** [comment]
SubgroupOfWholeGroupByCosetTable requires a standardized coset table. I will amend the documentation. I think having it standardize a table is potentially causing problems about which coset is which, so having it automatically standardize is not a good idea. If someone wants to add a standardization test I do not object.

A slightly slicker way to acheive the same is to use a homomorphism instead:

    gap> map:=GroupHomomorphismByImages(PSL2Z,Group(s,t),[PSL2Z.1,PSL2Z.2],[s,t]);
    [ S, T ] -> [ (1,2)(3,4)(5,6)(7,8)(9,10), (1,4)(2,5,9,10,8)(3,7,6) ]
    gap> H:=PreImage(map,Stabilizer(Image(map),1));
    Group(<fp, no generators known>)
    gap> Index(PSL2Z,H);
    10

This avoids having to write down a coset table in the first place.
