### ISSUE TITLE
Stabilizer with a user defined action

### ISSUE THREAD

**Issue by ChristopherRussell** [gap-system/gap#2187]
Please use the following template to submit an issue
(you may delete lines which are not used). Thank You!

### Observed behaviour
```
gap> f := function(x, y)
> return x^(y^2);
> end;;
gap> stab := Stabilizer(SymmetricGroup(4), 2, f);
Group([ (1,2), (1,3)(2,4) ])
gap> Elements(stab);
[ (), (3,4), (1,2), (1,2)(3,4), (1,3)(2,4), (1,3,2,4), (1,4,2,3), (1,4)(2,3) ]
gap> Filtered(SymmetricGroup(4), g -> 2 ^ (g^2) = 2);
[ (), (3,4), (2,4), (2,3), (1,4), (1,4,3), (1,4)(2,3), (1,2), (1,2)(3,4), (1,3,4), (1,3),
  (1,3)(2,4) ]
gap> Size(last) = Size(stab);
false
```

### Expected behaviour
Would expect that `Stabilizer(SymmetricGroup(4), 2, f)` would contain the same elements as `Filtered(SymmetricGroup(4), g -> 2 ^ (g^2) = 2)`. There are elements (e,g, (1,3,4)) missing from `stab` which should be there.

### Copy and paste GAP banner (to tell us about your setup)
8afbf8b0:gap crussell$ gap
 ┌───────┐   GAP 4.8.8-4975-g1b8a8e5 of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin17.3.0-default64
 Configuration:  gmp 6.1.2
 Loading the library and packages ...
 Packages:   Digraphs 0.12.0, GAPDoc 1.5.1, genss 1.6.5, GRAPE 4.7, IO 4.5.1, orb 4.8.0,
             PrimGrp 3.3.0, Semigroups 3.0.13, SmallGrp 1.2, TransGrp 2.0.2

**Comment by markuspf** [comment]
I believe your function does not define a group action.

**Comment by markuspf** [comment]
For instance:
```
gap> f(f(2, (1,2)),(1,2,3,4)) = f(2, (1,2) * (1,2,3,4));
false
```

**Comment by ChristopherRussell** [comment]
Apologies then. I tried to come up with an example because the instance I was having trouble with was more complicated. Perhaps my issue was down to the same problem. Do you know if there is a function which checks if a function is a group action?

**Comment by markuspf** [comment]
The only way to conclusively check this in GAP is by checking all possible inputs, which can be expensive.

You could use random inputs and try finding counterexamples that way, i.e. given a group `G`, an action function `op : X -> G -> X`
```
CheckAction := function(G,Omega,op, limit)
     local i, pnt, elt1, elt2, failure;

     i := 0;
     failure := false;
     repeat
         pnt := Random(Omega);
         elt1 := Random(G); elt2 := Random(G);
         failure := op(op(pnt, elt1), elt2) <> op(pnt, elt1 * elt2);
     until i > limit or failure;
     if failure then
        return [pnt, elt1, elt2];
     else
        return true;
     fi;  
end;
```

```
gap>  G := SymmetricGroup(4);; Om := [1,2,3,4];; op := {p,e} -> p ^ (e ^ 2);;
gap> CheckAction(G, Om, op, 1000);
[ 1, (1,4,2), (2,4) ]
```

Theorem proving doesn't belong into GAP's remit (yet?).

**Comment by fingolfin** [comment]
Closing this as invalid.
