### ISSUE TITLE
kernel idea: deal with line continuations in `io.c` (in `GetLine` ?), not in the scanner.

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2201]
Right now, all kinds of code in `scanner.c` deals with line continuations, i.e., a backslash followed by a newline, as in this example:
```
gap> x:="foo\
> bar";
"foobar"
```
This is quite repetitive. There is code for this in at least `GetIdent`, `GetCleanedChar`, `GetStr`, `GetChar`, and in several places in `GetSymbol`:
```C
...
  case '!':   STATE(Symbol) = S_ILLEGAL;                     GET_CHAR();
    if ( *STATE(In) == '\\' ) { GET_CHAR();
      if ( *STATE(In) == '\n' ) { GET_CHAR(); } }
...
  case ':':   STATE(Symbol) = S_COLON;                       GET_CHAR();
    if ( *STATE(In) == '\\' ) {
      GET_CHAR();
      if ( *STATE(In) == '\n' )
        { GET_CHAR(); }
    }
    if ( *STATE(In) == '=' ) { STATE(Symbol) = S_ASSIGN;  GET_CHAR(); break; }
    break;
...
  case '=':   STATE(Symbol) = S_EQ;                          GET_CHAR();  break;
  case '<':   STATE(Symbol) = S_LT;                          GET_CHAR();
    if ( *STATE(In) == '\\' ) { GET_CHAR();
      if ( *STATE(In) == '\n' ) { GET_CHAR(); } }
    if ( *STATE(In) == '=' ) { STATE(Symbol) = S_LE;      GET_CHAR();  break; }
    if ( *STATE(In) == '>' ) { STATE(Symbol) = S_NE;      GET_CHAR();  break; }
    break;
  case '>':   STATE(Symbol) = S_GT;                          GET_CHAR();
    if ( *STATE(In) == '\\' ) { GET_CHAR();
      if ( *STATE(In) == '\n' ) { GET_CHAR(); } }
    if ( *STATE(In) == '=' ) { STATE(Symbol) = S_GE;      GET_CHAR();  break; }
    break;

  case '+':   STATE(Symbol) = S_PLUS;                        GET_CHAR();  break;
  case '-':   STATE(Symbol) = S_MINUS;                       GET_CHAR();
    if ( *STATE(In) == '\\' ) { GET_CHAR();
      if ( *STATE(In) == '\n' ) { GET_CHAR(); } }
    if ( *STATE(In) == '>' ) { STATE(Symbol)=S_MAPTO;     GET_CHAR();  break; }
    break;
...
```

This also means that sometimes you are allowed to use a line continuation; sometimes you can use one, but don't have to; and sometimes don't need to use one at all.

E.g. inside a (non-triple quote) string, you can't have newlines, so if you want to break it, you need a line continuation:
```
gap> x:="foo\
> bar";
"foobar"
gap> x:="foo
Syntax error: String must not include <newline>
x:="foo
      ^
> ;
```
You can use one to break `:=` or `<=`  etc. "in the middle:
```
gap> x :\
> =1;
1
gap> x :
Syntax error: ; expected
x :
  ^
```
You can use line continuations to break identifiers and keywords:
```
gap> x m\
> od 5;
1
```

But you cannot use them to e.g. split double or triple dots:
```
gap> [1.\
> .4];
Error, Record Element: <rec> must be a record (not a macfloat)
not in any function at *stdin*:36
you can replace <rec> via 'return <rec>;'
brk>
gap> {x...}->x;
function( x... ) ... end
gap> {x..\
Syntax error: Three dots required for variadic argument list
{x..\
   ^
> ;
Syntax error: -> expected
;
^
gap>
```

Whenever one adds some new syntax, one has to be super careful about thinking how to deal with line continuations. All this complexity would go away if the IO code handled with them, getting rid of line continuations before the scanner sees them.

There is one drawback, though: one has to be very careful about not breaking `SyntaxError` and `SyntaxWarning` output, and about using correct line number references in e.g. coded functions. But since the current line number comes from the IO module anyway (via `GetInputLineNumber()`) I am hopeful this can be achieved without too much hassle (one just needs to be aware of it, and add suitable test cases to verify this does not break).

**Comment by fingolfin** [comment]
One minor drawback of this would that triple strings with lines ending in what looks like a line continuation would change behavior. Right now, we have this:
```
gap> x:="""haha\
> !""";
"haha\\\n!"
```
With this proposal, it would become:
```
gap> x:="""haha\
> !""";
"haha!"
```
which is the same as for the single quoted analog:
```
gap> x:="haha\
> !";
"haha!"
```
Personally I am not worried about this; it also matches what e.g. Python does (which I believe is the origin of our triple quote syntax, no?)

**Comment by stevelinton** [comment]
This seems like a good idea if you can get the warnings, line number annotations on functions, etc. to work correctly. I think the original behaviour was partly because there were fewer cases to think about and partly because of the need back then to avoid `malloc` so that lines really needed to live in fixed-length buffers.

**Comment by ChrisJefferson** [comment]
While it is a change of behaviour for triple strings it is (I think) unintentional, I was trying to emulate Python.

**Comment by fingolfin** [comment]
It turns out that implementing this is almost trivial, and seems to work without problems, *except* I discovered a bad interaction with comments: starting GAP with my patch prints these messages upon startup:
```
Syntax warning: Unbound global variable in /Users/mhorn/Projekte/GAP/gap.spielwiese/lib/stbcbckt.gi:241
        blist := BlistList( [ 1 .. NumberCells( P ) ], cellsP{ S } );
               ^
Syntax warning: Unbound global variable in /Users/mhorn/Projekte/GAP/gap.spielwiese/lib/stbcbckt.gi:242
        p := Position( blist, true );
                            ^
Syntax warning: Unbound global variable in /Users/mhorn/Projekte/GAP/gap.spielwiese/lib/stbcbckt.gi:244
            IntersectBlist( blist, BlistList( [ 1 .. NumberCells( P ) ],
                                 ^
Syntax warning: Unbound global variable in /Users/mhorn/Projekte/GAP/gap.spielwiese/lib/stbcbckt.gi:246
            p := Position( blist, true );
                                ^
```

The reason is this code:
```gap
InstallGlobalFunction( StratMeetPartition, function( arg )
    local   P,  S,  # first and second partition
            g,      # permutation such that <P> meet <S> / <g> is constructed
            rbase,  # R-base record, which records processing of fixpoints
            strat,  # meet strategy, the result
            p,  s,  # indices looping over the cells of <P> resp. <S>
            i,      # result of call to `SpliltCell'
            pnt,    # fixpoint to be processed
            cellsP, #\
            blist,  #  >see explanation below
            blist2, #/
	    splits,
	    lS,
            rap,  cell,  nrcells;

```

Note the line `cellsP, #\`: Currently, in GAP that `\` at the end of the line is ignored, so this works. With my patch, it is now treated as a line continuation, so the line with `blist` is effectively commented out, leading to the error messages above.

Of course, this behavior matches what e.g C does. So this change may well be regarded as a feature, *except* that it could break existing code... I'd imagine this breakage to be very rare (I just scanned through all packages in the distro and which I otherwise have sitting around, and as far as I could see, none were affected by the above problem). Still, this could be a deal breaker. Or might require teaching the scanner about comments which might not want (though it's not that hard...)

**Comment by fingolfin** [comment]
So one thing I could of course do is to move the handling of comments into `GET_CHAR`... right now, the scanner deals with comments (and whitespace) like this:
```C
  /* skip over <spaces>, <tabs>, <newlines> and comments                 */
  while (c==' '||c=='\t'||c=='\n'||c=='\r'||c=='\f'||c=='#') {
    if ( c == '#' ) {
      while ( c != '\n' && c != '\r' && c != '\377' )
        c = GET_NEXT_CHAR();
    }
    c = GET_NEXT_CHAR();
  }
```
Clearly, it wouldn't be a problem to migrate that into `GET_NEXT_CHAR`. Except that one would have to be very careful about this inside of strings and triple strings... Which means that in the end, I think this isn't an option.

Another option would be to add a new function `IGNORE_REST_OF_LINE()`, which would be called by the above snippet, and which would explicitly *not* handle line continuations.

Then again, I actually like the idea of treating line continuations the same way as in most (?) other languages... Though I notice that modern C compilers also issue warnings if e.g. a single line comment `\\` ends in a line continuation. We could also try to do that, by having `IGNORE_REST_OF_LINE()` as above, but now it does handle line continuations, and returns a flag indicating whether it saw one; if we see one, then we can (optionally?) issue a `SyntaxWarning` inside of `scanner.c`.

Thoughts?

**Comment by ChrisJefferson** [comment]
I would be happy to change the handling of \ in this case, it would seem more consistent.

**Comment by fingolfin** [comment]
Another note: In C, C++ or Python, if you end a line with, say `bla \\`, then the first backslash quotes the second, so this does not result in a line continuation. In GAP, this is different: We treat this as a single backslash followed by a line continuation, both right now and also with my patch. From an implementation POV that's the easiest to achieve; but then again, perhaps it would be better to match the behavior of "main stream" languages?

**Comment by frankluebeck** [comment]
Generally , I clearly support the idea to move the handling of continuation into a single place.

But I'm not happy with changing the documented behaviour that the rest of the line is ignored after a # comment character.  It is not a problem to avoid lines finishing with '\\' in an actual comment. 

But I often use comments to (temporarily) comment out code (I have a key in my editor that toggles adding/removing '##  ' at the beginning of a line and moves to the next line). When '\\' at the end of comment lines is suddenly interpreted as continuation character this becomes more complicated.

In any case this is rare problem, but I would prefer if the handling of comment lines would be the same as before.

**Comment by ChrisJefferson** [comment]
@frankluebeck : Actually, I think your example of commenting and uncommenting will behave better in the new case (although I admit differently). Consider the following code.

```
x := f(a,b, \
c);
```

Now imagine we comment out the first line:

```
# x := f(a,b, \
c);
```

Currently, this leaves half a line of code uncommented, and produces invalid code. In the new mode, we will comment out the continued line as well.

I can't imagine a case where you would want the old behaviour and not the new one, when you comment out a block of code. Perhaps you have a better example.

**Comment by frankluebeck** [comment]
In your example I would of course comment the next line as well. Actually, in your example a continuation character is not needed at all.

I only use continuation characters in strings to be printed, and sometimes comment out parts of it when debugging the code. Nevertheless, this is a rare problem in practice.

My main point is that the simple and documented rule that everything in a line is ignored after a # comment character is broken by the proposed change. I would prefer if this rule could be kept (if it easy to achieve in the implementation).

**Comment by fingolfin** [comment]
I am really fine either way.

But just to say: The only rule on comments I could find in the manual is in [section 4.4 "Whitespaces"](https://www.gap-system.org/Manuals/doc/ref/chap4.html#X7C53CEFC8641B919) (if you know of other places talking about this, please add them). It says:
> A comment starts with the character #, which is sometimes called sharp or hatch, and continues to the end of the line on which the comment character appears. The whole comment, including # and the Newline character is treated as a single whitespace. Inside a string, the comment character # loses its role and is just an ordinary character.

I see no conflict with the potential new handling of line continuation here: the line simply does not end at a line continuation. Of course it's easy to miss the possibility, but I'd just add a mention of it in the paragraph I just quoted.

Conversely, if we decide to keep the current behavior, I'd still mention it explicitly with an added sentence at this spot: "Note that a line continuation character cannot be use to continue a comment to the next line" or so, perhaps with an example.

I'd also add a link to the documentation of line continuation there, which is [section 6.2](https://www.gap-system.org/Manuals/doc/ref/chap6.html#X866092F281910B74). And mention the phrase "line continuation" there (and add it to the index). I am also somewhat confused by that section, which says:
> This is achieved by ending a line by a backslash or by a backslash and a carriage return character, then continue the input on the beginning of the next line. When reading this GAP will ignore such continuation backslashes, carriage return characters and newline characters.

How would I enter "a carriage return", in order to end the line by one? If this was meant to deal with Windows line ends, I'd just remove it, as I think it confuses more than it helps. But perhaps something else was intended?

Finally, I wonder if this in [section 4.6 "Identifiers"](https://www.gap-system.org/Manuals/doc/ref/chap4.html#X860313A179A5163F) should also be changed to refer to line continuation (with a link):
> The escape sequence \newline is ignored, making it possible to split long identifiers over multiple lines.
