### ISSUE TITLE
Installation via homebrew/science is deprecated.

### ISSUE THREAD

**Issue by suessflorian** [gap-system/gap#2209]
Using:
`brew install homebrew/science/gap --with-packages`

Results:
`Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.`

According to docs, should work.
https://www.gap-system.org/Download/alternatives.html

MacOS 10.13.3 - HomeBrew fully updated.

**Comment by fingolfin** [comment]
OK, so I guess we need to update the website to remove the link to the homebrew package.

**Comment by fingolfin** [comment]
Hrm, and the offer to,provide GAP on a CD should be removed. And overall, it should be made clear that these alternative downloads are by third parties and not supported by the GAP team (perhaps except for the docker variant?)

**Comment by fingolfin** [comment]
Website has been updated some time ago to warn about the deprecation of the homebrew package etc.

**Comment by alex-konovalov** [comment]
For the record, trying to resurrect Homebrew GAP installer at https://github.com/Homebrew/homebrew-core/pull/36156
