### ISSUE TITLE
Installing new Attributes and Properties for IsList not working

### ISSUE THREAD

**Issue by cschoennenbeck** [gap-system/gap#2216]
Installing new Attributes and Properties for IsList objects does not work as expected. Either this should yield an error or be mentioned in the documentation.
### Observed behaviour
```gap
gap> DeclareAttribute("IsMyAttribute", IsList);
gap> InstallMethod(IsMyAttribute, [IsList], x->[]);
gap> L:=[3,4];;
gap> MakeImmutable(L);;
gap> IsMyAttribute(L);
[  ]
gap> KnownAttributesOfObject(L);
[ "LENGTH" ]
```
This happens on both the master branch and e.g. with version 4.8.7 (where , in the last step, the return value of `KnownAttributesOfObject` is just `[  ]`).

**Comment by fingolfin** [comment]
I see no issue here. Plain lists do not store attributes, and are not in the filter IsAttributeStoringRep.

I think this is documented, too, but am in my phone, so I can't check right now.

**Comment by ssiccha** [comment]
Would it make sense / is it possible to somehow tell a user that they are trying to install methods for objects that are not in `IsAttributeStoringRep`?

**Comment by fingolfin** [comment]
No, it is perfectly reasonable to use attributes with objects which are not attribute storing.

To get back to my earlier comment: [section 13.5 of the reference manual](https://www.gap-system.org/Manuals/doc/ref/chap13.html#X7C701DBF7BAE649A) states:
> It depends on the representation of an object (see 13.4) which attribute values it stores. An object in the representation IsAttributeStoringRep stores all attribute values once they are computed. Moreover, for an object in this representation, subsequent calls to an attribute will return the same object; this is achieved via a special method for each attribute setter that stores the attribute value in an object in IsAttributeStoringRep, and a special method for the attribute itself that fetches the stored attribute value. (These methods are called the "system setter" and the "system getter" of the attribute, respectively.)


All internal lists (plists, blists, ranges) and also internal records (precords) are *not* attribute storing. Same for positional objects (at least by default); right now, only component objects can be attribute storing.
