### ISSUE TITLE
Idea: record location of `InstallMethod` call

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2239]
Right now, one can use e.g. `LocationFunc` or `PageSource` on methods installed for an operation, which is quite handy. But sometimes the same function is installed several times; or a kernel function is installed as a method (possibly also several times), and in these cases, the location of the function definition does not coincide with the location of the method installation.

Thus, it would be nice if we could store the location of the method installation, too. I assume it could be e.g. stored in the methods array, along with the other methods.

The tricky part might be to figure out the location itself. I assume this may require some work on the kernel to be possible. We'd somehow need to retrieve the location of the place `InstallMethod` was called... Perhaps some clever lvar walking can help?!? hum

**Comment by markuspf** [comment]
I have some prototype code that does this (in multiple variations).

My first incarnation had a global variable that complemented the `OPERATIONS` array.

 I think an approach similar to `GET_OPER_FLAGS` (which stores the location of the declarations for each operation already) can work here, too.

**Comment by fingolfin** [comment]
Well, I assume we'd have to add one more entry per method into each `METHODS_OPERATION(oper,n)` list, storing the location info there. Of course *that* in turn requires adjusting all places that deal with `METHODS_OPERATION` -- so at least `INSTALL_METHOD_FLAGS` and the kernel code in `GetMethodUncached`
