### ISSUE TITLE
Remove ParGAP from GAP 4.9.1 distribution

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2285]
See https://mail.gap-system.org/pipermail/gap/2018-March/001082.html

**Comment by alex-konovalov** [comment]
This should be rather an issue for https://github.com/gap-system/gap-distribution (because the relevant commit will be made there), but fine to keep it here as it's already created.

**Comment by alex-konovalov** [comment]
Done - see https://github.com/gap-system/gap-distribution/issues/44
