### ISSUE TITLE
Git-SHA in GAP banner

### ISSUE THREAD

**Issue by mohamed-barakat** [gap-system/gap#229]
It would be nice to have the short Git-SHA displayed in the banner.

**Comment by alex-konovalov** [comment]
Do you mean printing the sha1 of the current revision while running the GAP development version, or the sha1 of the revision from which the current GAP release was wrapped, or both?

**Comment by frankluebeck** [comment]
I would say that the Git-SHA is useless (if not confusing) information for most GAP users. Therefore, it is not sensible to include it in the banner.

Of course, the Git-SHA is useful information for some users and it is a good idea to make it somehow available from within GAP, e.g., in GAPInfo.gapSHA. People/develpers who want to see it printed whenever they startup GAP can then put a 'Print(GAPInfo.gapSHA, "\n");' in their gaprc file.

**Comment by mohamed-barakat** [comment]
Yes, I am primarily interested in the seeing this version while running a development version. I agree with Frank that this might be less useful for the released version.

**Comment by markuspf** [comment]
@frankluebeck the typical GAP user won't see this hash. I made a few changes to my pull request that will only cause the hash to be displayed when one is using git. The released version of gap will just have the normal version number in the banner.
This will be deduced from a tag in the git repository to be able to track which commit the release was made from.

**Comment by hulpke** [comment]
@frankluebeck, @markuspfeiffer (is this the right use of @?)

> @frankluebeck the typical GAP user won't see this hash. I made a few changes to my pull request that will only cause the hash to be displayed when one is using git. The released version of gap will just have the normal version number in the banner.

My question yesterday was prompted by the same concern as Frank voiced. If the release version just prints the normal version number, that resolves my concern.

Thank you!

   Alexander

**Comment by markuspfeiffer** [comment]
@hulpke Your usage was (almost) correct. I guess you wanted to message @markuspf instead of me. We may share the same name, but we're not the same person ;)

**Comment by alex-konovalov** [comment]
Another useful case of this is when the banner is the part of the Jenkins or Travis log which has to be copied and pasted somewhere - saves time from looking from this information elsewhere and helps to ensure that all involved in the conversation have the same revision in mind. Thanks.

**Comment by alex-konovalov** [comment]
Still I'd like to reopen this issue and suggest to improve formatting of the banner. The easiest fix would be to move (free software, GPL) to the next line after the GAP's URL.
![screen shot 2015-09-21 at 20 25 58](https://cloud.githubusercontent.com/assets/5751387/10014114/f582f482-610e-11e5-9fb8-41ecbfc77405.png)

**Comment by markuspf** [comment]
I think we should just remove the (free software, GPL). If we agree on a maximum width (72 or 80 characters) we can make sure this is never exceeded of course.

**Comment by alex-konovalov** [comment]
The horisontal line separating package banners is 77 characters - I think that is the limit.

**Comment by markuspf** [comment]
If we remove the `Version` as well, I think we're golden, i.e. we'd have
```
GAP v4.7.7-314-g0eee3d4-dirty of 2015-09-21 18:04:39 (BST)
```
A slight issue might be that the number of commits can of course have more than 3 digits and so this string becomes longer.

**Comment by alex-konovalov** [comment]
:+1: this is still well within the boundaries.

**Comment by alex-konovalov** [comment]
Regarding removing "(free software, GPL)" - I do prefer to move it to the next line after the GAP URL rather than just remove. I had a look at discussion we had in June 2010 for a smaller GAP banner to be introduced in GAP 4.5, and it was there where we agreed that this fact is good to reflect in the banner (and prior to that, we had a line suggesting to enter `?license` for license info).

It's good to show this in the banner to be seen by those who may just see GAP accidentally.

**Comment by fingolfin** [comment]
I don't think we should keep "(free software, GPL)" for the following reaons:
1. I think licensing information it is sufficiently covered by the text `See also  '?copyright' and  '?authors'` -- both refereneced texts mention the GPL explicitly, and state what it is
2. Somebody who is not already deeply aware of licensing issues won't even know what "GPL" means. Those who do know will easily deduce that "?copyright" should tell them licensing information
3. The text "free software" is meaningless by itself, too -- people who start GAP clearly already got it somehow on their system, without payment. What are they meant to learn from this text, then?

That said, I won't loose sleep if we keep it in. But I'd like to hear what people thin it conveys that is not already covered (better) by the pointer to the copyright page in the documentation, or by the LICENSE file shipped with GAP.

**Comment by alex-konovalov** [comment]
OK, then let's delete it and close this issue... Thanks for pointing to the fact that we do have `?copyright` hint (when I started GAP to check, I had a lot of package banners to obscure it). Then it's already enough.

**Comment by rbehrends** [comment]
It's also worth considering what the actual use case is for this feature. As I understand it, it's mostly for people running development versions to quickly see that they actually run the right version. In this context, I'm not sure if all that information actually *has* to be included. You just need enough information to verify "yes, this is the version I think I'm running".

**Comment by stevelinton** [comment]
The other use case is people who are using development versions reporting bugs — if the log includes the SHA it makes it easier for others to reproduce.

S

**Comment by alex-konovalov** [comment]
Shorter 1st line is implemented in #247.
