### ISSUE TITLE
testinstall/integer.tst requires non-required package

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#2295]
### Observed behaviour
If `FactInt` is not available, then `gap/tst/testinstall/integer.tst` fails on the master branch as of today. This is because in line 42 of that test file the `FactInt` package is loaded. This causes the Semigroups package travis tests to fail, because we don't install `FactInt`, but we do run `testinstall.g` from GAP to ensure that we haven't broken anything there:

https://travis-ci.org/gap-packages/Semigroups/jobs/357799015

### Expected behaviour

Tests in GAP should not depend on non-required packages. This test should rather be in the tests of `FactInt`.

### Copy and paste GAP banner (to tell us about your setup)

~~~~
 ┌───────┐   GAP 4.8.8-5206-g13b2249 of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin17.2.0-default64
 Configuration:  gmp 6.1.2
 Loading the library and packages ...
 Packages:   Digraphs 0.12.0, GAPDoc 1.6.1, genss 1.6.5, GRAPE 4.7, IO 4.5.1,
             orb 4.8.0, PrimGrp 3.3.0, Semigroups 3.0.15, smallgrp 1.2,
             Smallsemi 0.6.11, TransGrp 2.0.2
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
~~~~

**Comment by alex-konovalov** [comment]
Alternatively, you can run it only if FactInt is available. An example how to do this is at https://github.com/gap-system/gap/blob/master/tst/testextra/ctblpope.tst

**Comment by fingolfin** [comment]
@alex-konovalov that's not really a viable option for tests, and the example you link to IMHO actually shows that it's not attractive; it is only viable for very short tests, and you completely loose the ability to test outputs. This is actually a major missing feature from our tests: the ability to mark portions of a .tst file (or at least the whole file) as "only run this if condition XYZ is met". Likewise, an option to mark a section of a tests as "known to fail" would be highly desirable.

@james-d-mitchell I'll look into resolving this, but I am afraid your PR #2298 isn't an acceptable option to me.
In the meantime, I really wonder why you can't simply load FactInt, it's on GAP's default autoload list, too... ?

**Comment by james-d-mitchell** [comment]
@fingolfin Of course, we could load `FactInt`, but then we have to add downloading (and installing, if necessary) to our travis setup, which is just an addition unnecessary step.

It seems to me to be a reasonable principle that the tests in GAP test GAP but not its packages. The tests for a package should be in the package. If this principle is adhered to (as I think it was until yesterday when this test was added), then the, in my opinion, unnecessary work of having to adjust our travis setup, file this issue, make pull requests fixing the issue, disappears. I don't see the rationale for including this test in GAP in the first place, but perhaps I am missing something.

Of course, you could argue that running the GAP tests in the Semigroups package travis is somehow a bad idea, or that we ought to install all of GAPs packages so that we can run the GAP tests in our travis setup. For the former, I can't think of reason we should not do this, in fact, it saved us many times from committing changes that break GAP's tests. For the latter, travis is already slow sometimes, and so we'd prefer to install a minimum of additional GAP packages.

From this perspective, would adding PR to the FactInt package including the test deleted in PR #2298 not be the best solution?

**Comment by fingolfin** [comment]
There seems to be a misunderstanding here: these tests are for GAP library functions! The only reason I load FactInt is because it affects the results. So to properly fix this, I need to take a product of larger primes.

**Comment by james-d-mitchell** [comment]
Ah, indeed, I misunderstood. It is still arguable that this test should be in FactInt, though, since it only applies if FactInt is loaded. On the other hand, I can see why you'd want it in the GAP tests, so probably allowing the test to run whether or not FactInt is available is the best solution. 

How about something like:

~~~~
gap> not IsPackageMarkedForLoading("factint") or FactorsInt(2^155-19) = 
> [ 167, 11824964268989, 53849995530347, 429484354827785909 ];
true
gap> not IsPackageMarkedForLoading("factint") or PartialFactorization(2^155-19) = 
> [ 167, 11824964268989, 53849995530347, 429484354827785909 ];
true
gap> not IsPackageMarkedForLoading("factint") or PartialFactorization(2^155-19, 1) =
> [ 167, 273484587823896504154881143846609846492502347 ];
true
~~~~
with `IsPackageMarkedForLoading` replaced with the correct thing, if that's not it.
