### ISSUE TITLE
Undocumented and unused functions in grp/classic.gi: remove? document?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2327]
While looking for code that needs testing, I noticed in https://codecov.io/gh/gap-system/gap/src/master/grp/classic.gi that there are several undocumented functions which are never used anywhere, and in a few cases, seem to have functionality duplicated by functions that were added later. These are not called anywhere in the library, nor by any distributed package, nor by any package I am aware on here on GitHub

For each, I propose that we either remove it (possibly moving it to e.g. `dev/deleted-code/` or so instead); or else document it and add tests.

These are the functions:
* `EichlerTransformation`
* `WallForm` (used by `SpinorNorm`)
* `SpinorNorm`
* `WreathProductOfMatrixGroup` (see also`MatWreathProduct` in `lib/gprdmat.gi`, which is equally undocumented; added by @hulpke in 3f339849d20415d4999b835b455e805be3fb1650)
* `TensorWreathProductOfMatrixGroup`
* `CentralProductOfMatrixGroups`

**Comment by hulpke** [comment]
The routine MatWreathProduct is installed as method for WreathProduct for Matrix groups, and thus gets used. When I added it I was not aware of the similar function in classic.gi.

As for classic.gi, I suspect this originated in code from Frank Celler's thesis. These are useful functions, even if at the moment there is no test or them or just superficial documentation .

I have a slight preference for MatWreathProduct over WreathProductOfMAtrixGroup, as the former constructs the same group as as the corresponding Magma function does.
