### ISSUE TITLE
Smaller bootstrap for tests

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#233]
We need a smaller bootstrap for the testing on travis, as the download is slow at times and takes the bulk of the runtime.

**Comment by alex-konovalov** [comment]
Yes, I am watching this at the moment. Maybe go back to `bootstrap-pkg-minimal` and then explicitly downloading archives for some packages that are needed to please tests? For example, `makemanuals` in Travis only checks that manuals _may be built_, so it does not require all packages at all.

**Comment by alex-konovalov** [comment]
A cleaner solution, not guaranteed before the end of these GAP Days, would be for me create an intermediate archive of packages with a fixed name, and an extra bootstrap target in the Makefile. Then Travis file would not require an update if e.g. version number or package location changes.

**Comment by fingolfin** [comment]
Maybe an alternative (or complementary) solution would be to use Travis' caching features, see http://docs.travis-ci.com/user/caching/
I have not looked closely, so maybe it doesn't work for us for some reason -- but they explicitly ask for feedback on that page, and I am sure they'd love to *not* download gigabytes of data all the time for our builds ;-)

**Comment by fingolfin** [comment]
Perhaps an even better and easier solution is to take them up on this offer, mentioned on the caching page:
>  Anything that’s commonly not changing is better suited for something like our APT caching proxy. Please shoot us an [email](support@travis-ci.com) and we’ll see about adding your custom source to our cache.

**Comment by fingolfin** [comment]
I got a reply from the Travis team. It turns out the proxy feature is not really applicable, and probably would not help much anyway. But they encourage us to experiment with the caching feature.

**Comment by alex-konovalov** [comment]
I think the proxy feature had improved in the meantime...

**Comment by fingolfin** [comment]
We are using caching now on both Travis and AppVeyor -- so I am closing this now.
