### ISSUE TITLE
Replace SyKernelVersion = "4.dev" by info from SCM

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#234]
We can fill the output of `git describe` in here, basically the information that is put into SyKernelSHA in #230, but it has be done consistently throughout the repository, and the release tools will have to be adapted to this change.

This will make it easier to release GAP by tagging a release in the repository.

**Comment by alex-konovalov** [comment]
@markuspf isn't this done?

**Comment by fingolfin** [comment]
This is indeed done.
