### ISSUE TITLE
last2, last3 not available inside a break loop

### ISSUE THREAD

**Issue by cdwensley** [gap-system/gap#2374]
This happens in a fresh 4.9.0 :-
gap> 1;2;3;[last,last2,last3];
1
2
3
[ 3, 2, 1 ]
gap> Error("to enter a break loop");
Error, to enter a break loop called from
not in any function at *stdin*:2
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 1;2;3;[last,last2,last3];      
1
2
3
[ 3, 3, 2 ]

When I queried this on Slack, Chris Jefferson replied: 
Short answer, no. Longer answer, the "bug" is we have a variable called `LastDepth`, which lets you pick how many of the last variables are changed. In this case we have set `LastDepth=1`, which means only last is getting updated. Why would we ever want to support that? 
The simple fix (you could test it) is to change the 4th argument to SHELL in error.g:240 from '1' to '3'. 

This change has been made; testinstall and teststandard pass; and a PR has been made.

**Comment by alex-konovalov** [comment]
@cdwensley shall this be closed now?

**Comment by cdwensley** [comment]
Yes - covered by PR #2375 and #2379.
