### ISSUE TITLE
Time taken by Immediate Methods

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#2386]
This is motivated by #2377:

When running the following example from the test suite
```
G:=PcGroupCode( 741231213963541373679312045151639276850536621925972119311,11664);;
IsomorphismGroups(G,PcGroupCode(CodePcGroup(G),Size(G)))=fail;time;
```
on my machine (just minimal packages, but AutPGroup is loaded), in the current master the calculation takes 234 seconds on my Laptop. If I restart GAP the same way, but issue the command
```
    IGNORE_IMMEDIATE_METHODS:=true;
```
first, the calculation takes 200 seconds, that is close to 20% of the time is spent by immediate methods.

It is possible that this reflects bad programming of mine in the isomorphism test -- a lot of groups and vector spaces are created. However `TraceImmediateMethods` shows that time is spent on (e.g.) testing whether the group is cyclic and perfect because it has size 1, to check whether Size should be set to infinity, because IsFinite has been set to `false`, and so on. 

The immediate methods themselves are probably rather harmless, but they change the type of an object (sometimes multiple tiles) just after it has been created, and the changed type then need to be compared with existing types to avoid duplication of types.

**Comment by fingolfin** [comment]
This is all fine and well, but it just seems to be a description of how some things currently are, but I can't see a specific request, or otherwise determine what concrete issue this is meant to describe? Are you asking for immediate methods to be made faster? Or for them to be used less? Or to be reduced entirely? Or something else?
