### ISSUE TITLE
segfault in xmodalg package tests in the master branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#2401]
This is a new failure observed in standard tests of the Browse package run in the Docker container for the master branch (built on 24th April): https://travis-ci.org/gap-system/gap-docker-pkg-tests-master/jobs/370829546 
```
########> Diff in /home/gap/inst/gap-master/pkg/Browse/tst/test.tst:311
# Input is:
BrowseGapManuals( "inline/collapsed" );
# Expected output:
# But found:
Error, recursion depth trap (5000)
########
```
This happens when GAP is started with `-A`, or all packages are loaded. Tests pass with default packages loaded at GAP startup. 

CC @frankluebeck

**Comment by alex-konovalov** [comment]
For the record, in the same build, two other packages have other kinds of failures, may be related:
- @bh11 irredsol https://travis-ci.org/gap-system/gap-docker-pkg-tests-master/jobs/370829585
- @aodabas xmodalg https://travis-ci.org/gap-system/gap-docker-pkg-tests-master/jobs/370829616

**Comment by alex-konovalov** [comment]
@frankluebeck For Browse, I've restarted the test with the new container built this morning, and the problem disappeared.

**Comment by alex-konovalov** [comment]
@bh11: The problem with irredsol also vanished in the new build. 

@aodabas: xmodalg still segfaults when all packages are loaded: https://travis-ci.org/gap-system/gap-docker-pkg-tests-master/jobs/370829616 

I will rename the issue to reflect the new state.

**Comment by fingolfin** [comment]
If a package tests starts to segfault for a package that does not include a kernel extension, then in 99% of all cases, that's GAP's problem, not the packages: plain GAP code should not lead to a segfault, period, if it does, even if the package does something unusual, it's our (GAP's) fault. I'd make an exception for cases where they deliberately use a low-level, undocumented `SNAKE_CASE` function, but in all other cases, I blame GAP.

In this case, I wonder if the recent regression in GAP's master branch (see issue #2415) could be responsible for some of crashes?

**Comment by alex-konovalov** [comment]
@fingolfin I think so - this is no longer happens.
