### ISSUE TITLE
IteratorOfCartesianProduct and empty lists

### ISSUE THREAD

**Issue by isadofschi** [gap-system/gap#2420]
`IteratorOfCartesianProduct` gives the following error if one of the arguments is empty:
```
	Error, Each arguments must be a finite collection called from
	IteratorOfCartesianProduct2( arg ...
```
I think this is a bug. For example:
```
	IteratorOfCartesianProduct([1,2],[]);
```
gives this error, while 
```
	Cartesian([1,2],[]);
```
correctly returns `[]`.
Calling
```
	IteratorOfCartesianProduct([[1,2],[]]);
```
also gives an error.

I have tried this in GAP 4.8.4 and GAP 4.8.10.

**Comment by fingolfin** [comment]
Ahh, actually I mixed up two different bugs here: the one you report is *NOT* fixed in GAP 4.9 nor in the master branch! Sorry for the confusion.
