### ISSUE TITLE
files.tst does not pass on Windows

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#2442]
In the master branch, when GAP is built and then copied on a Cygwin-free machine for testing, we have:
```
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-master-windows-\
build/GAP-master-snapshot/tst/teststandard/files/files.tst:104
# Input is:
testRead("example.txt", {} -> InputTextFile(Filename(dir, "examplegz.txt")),
lines, false);
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `ReadAllLine' on 1 arguments
The 1st argument is 'fail' which might point to an earlier problem
########
```

**Comment by alex-konovalov** [comment]
If this will not happen shortly, we will have to disable this test if OS is Windows, to prevent Windows tests from rotting.

**Comment by ChrisJefferson** [comment]
I would disable it for now, we can always reenable it when zlib / whatever is added.

**Comment by ChrisJefferson** [comment]
I believe this test was never disabled, and now works fine in windows, could you retest?

**Comment by alex-konovalov** [comment]
@ChrisJefferson yes, now works fine, indeed.  The other problem is happening now:
```
########> Diff in /proc/cygdrive/C/gap-4.10.0/tst/testinstall/files/files.tst:
100
# Input is:
testRead("example.txt", {} -> InputTextFile(Filename(dir, "example.txt")),
lines, true);
# Expected output:
# But found:
At position 17, expected 16, on line 2 of example.txt
At position 33, expected 31, on line 3 of example.txt
failed read past end of file example.txt
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `PositionStream' on 1 arguments
########
```
Could this be because the file is automatically converted to have Windows-style line endings?

**Comment by ChrisJefferson** [comment]
Yes, I'm not sure how to fix that...

**Comment by alex-konovalov** [comment]
I can declare that file to be binary i.e. excluded from line-endings conversion.

**Comment by alex-konovalov** [comment]
@ChrisJefferson confirm that tests pass if the file has unix line endings. I've now handled this in https://github.com/gap-system/gap-distribution/commit/e09edaafb8cd2f0e603727bcd164ab5e901012e2.
