### ISSUE TITLE
Rename C function ErrorMayQuit to ErrorNoReturn

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#2453]
`ErrorNoReturn` is the name of the corresponding GAP function and IMO also describes better what the function does.

If this is done there should be an "alias" `ErrorMayQuit` on the C level until all packages adopt the new name.

**Comment by fingolfin** [comment]
I guess implementing this would be trivial, but perhaps we first need some discussion to determine if we really want to do it this way?

**Comment by ssiccha** [comment]
Do you have other ideas?

I think it is quite easy to figure out what `ErrorMayQuit` does. So I'm also fine with leaving it as it is now.

On the other hand this seems like a nice chance to try out the `sed` command.

**Comment by DominikBernhardt** [comment]
@fingolfin @ssiccha Ping. Is there a decision on what should happen with this Issue?

**Comment by ssiccha** [comment]
I'd be ok with closing this issue.
