### ISSUE TITLE
`MakeImmutable` on weak pointer objects does not make subobjects immutable

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2480]
This can be observed here:
```
gap> l:=[ [1], [2], [3] ]; w:=WeakPointerObj(l);
[ [ 1 ], [ 2 ], [ 3 ] ]
WeakPointerObj( [ [ 1 ], [ 2 ], [ 3 ] ] )
gap> MakeImmutable(w);
[ [ 1 ], [ 2 ], [ 3 ] ]
gap> IsMutable(w);
false
gap> IsMutable(w[1]);   #  sublist is *NOT* mutable
true
gap> MakeImmutable(l);
[ [ 1 ], [ 2 ], [ 3 ] ]
gap> IsMutable(l);
false
gap> IsMutable(l[1]);
false
```

This is a bug, as it violates the semantics GAP promises for immutable objects; e.g. their mathematical properties may not change.

As for the cause of the bug: the kernel function `MakeImmutableWPObj` only retypes the bag, but does not even attempt to make subobjects immutable. So fixing this shouldn't be hard (but some tests for this should also be added).

**Comment by ChrisJefferson** [comment]
Without diving in (so this might already be handled /discussed), I wonder if we should also make immutable weak pointers not weak? It seems weird an immutable object can change?

**Comment by fingolfin** [comment]
This is already the case: the immutable w above is actually a plist

**Comment by stevelinton** [comment]
That was my code (long ago) and it's a bug not some subtle scheme,
