### ISSUE TITLE
GAP Crash in 'loops' package

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#2481]
From the [GAP Forum]:

Dear Gap Forum

I have installed latest version (4.9) of Gap. If I run following programmes on GAP:
LoadPackage("loops");
L:=LeftBolLoop(15,1);
G:=SymmetricGroup(15);
H:=Stabilizer(G,1);
taut:=Filtered(H,h->(L.4^h=Inverse(L.5^h)*L.3^h));

then *gap terminal vanishes unexpectedly. GAP icons also vanishes from the desktop. * Please help me to remove the trouble. It is noted that it was not happened for the version 4.8.10.

My System(laptop Lenovo V310) properties is:

Windows 10 (original)
Core i5
RAM 8GB

Thanks

**Comment by ChrisJefferson** [comment]
Could you provide some more information?

How long does it take to crash?
Exactly which copy of GAP did you download? The exe? The 64-bit version?

**Comment by fingolfin** [comment]
No response, closing.

**Comment by ChrisJefferson** [comment]
Yes, but this isn't connected to that issue.
