### ISSUE TITLE
GAP on Cygwin limited to small workspace

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#2483]
In the GAP 4.9.1 release, on Cygwin, trying to allocate more than about 100MB once GAP has started causes "gap: cannot extend the workspace any more!"

**Comment by alex-konovalov** [comment]
This is puzzling - how then teststandard runs fine in Jenkins then? Could you provide more details please:
- is this in the Cygwin shell or in a GAP installation on a Cygwin-free machine?
- which version of Windows is used?
- what's the example of the calculation that you do?

**Comment by ChrisJefferson** [comment]
I was wrong, it's more like 600MB. However, one doesn't get a warning break loop, just "gap: cannot extend the workspace any more!".

I just do:

x := List([1..1000000],a->a); (which makes a 4MBish list)
Then:
y := List([1..100], q -> DEEP_COPY_OBJ(x));; (which makes about 400MB, that's OK).
z := List([1..50], q -> DEEP_COPY_OBJ(x);; (which tries to make another 200MB, not OK).

**Comment by ChrisJefferson** [comment]
It works fine in 64-bit.

**Comment by fingolfin** [comment]
So I assume this was different in GAP 4.8?

One wild guess would be that this is caused by the fact that we are now a bit more liberal about using malloc/free in the GMP code -- perhaps that cause heap fragmentation? We use some tricks to avoid that, but I wouldn't be surprised to learn that these don't work on Cygwin.

Of course it might be something else, too.

**Comment by alex-konovalov** [comment]
I went a bit further:
```
gap> z := List([1..50], q -> DEEP_COPY_OBJ(x));;
gap> z1 := List([1..50], q -> DEEP_COPY_OBJ(x));; 
gap> z2 := List([1..50], q -> DEEP_COPY_OBJ(x));;
Error, reached the pre-set memory limit
(change it with the -o command line option) in
  return res; at /proc/cygdrive/C/gap-4.9.2/lib/coll.gi:755 called from
<function "List">( <arguments> )
 called from read-eval loop at *stdin*:6
you can 'return;'
brk>
```
with Windows resource monitor reporting this after the break loop happened:
![screen shot 2018-06-28 at 13 05 01](https://user-images.githubusercontent.com/5751387/42033213-06e9b2ba-7ad4-11e8-8817-8f2afd6e6256.png)

**Comment by ChrisJefferson** [comment]
I think the amount of memory available varies from machine to machine, depending on how memory is laid out. The long-term solution to this is just to push people to a 64-bit build, so I'm happy to close this and just tell 32-bit Cygwin users to use whatever memory they get, which may shrink depending on windows version / memory / phase of the moon.
