### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#25]
I have taken all the hpcgap branches (other than hpcgap-default) and turned them into tags, as they are not expected to continued in future.

The branches stable-4.1 to stable-4.6 and stable-4.beta were all closed in mercurial some time ago. I intend to turn them into tags as well, called (for want of better names) 'closedbranch/stable-4.1', etc.

This will leave:

hpcgap-default
master
stable-4.7

as the only branches.

**Comment by alex-konovalov** [comment]
Sounds good to me, moreover since we're not going to make any releases from these branches. I suggest to do it and close this issue when done.
