### ISSUE TITLE
Broken `Integers = [0];` in resclasses

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#2503]
Until 3252d1e3e8ce2f55, the code `Integers=[0]` worked, due to a method in resclasses. Somehow it's priority has fallen. The applicable methods are now:

```
function( D, C ) ... end
gap> ApplicableMethod(\=, [Integers, [0]], 1, 2);
#I  Searching Method for = with 2 arguments:
#I  Total: 187 entries
#I  Method
168: ``=: for a domain and a list'' at /mnt/c/Users/caj/files/reps/gap/gap/lib/domain.gi:
35 , value: 10
#I  Skipped:
#I  Method
172
 : ``=: for an infinite domain and a list of elements (ResClasses)'' at /mnt/c/Users/caj/files\ /reps/gap/gap/pkg/resclasses-4.7.1/lib/resclass.gi:1281 , value: 9
function( D, l ) ... end
```

Whereas they used to be:

```
#I  Searching Method for = with 2 arguments:
#I  Total: 187 entries
#I  Method
159
 : ``=: for an infinite domain and a list of elements (ResClasses)'' at /mnt/c/Users/caj/files/\ reps/gap/gap-clean/pkg/resclasses-4.7.1/lib/resclass.gi:1281 , value: 12
#I  Skipped:
#I  Method
171: ``=: for a domain and a list'' at /mnt/c/Users/caj/files/reps/gap/gap-clean/lib/domain.gi:
35 , value: 10
function( D, C ) ... end
```

It might be reasonable to add `HasIsFinite(D) and not(IsFinite(D))` to the `=` for a domain and a list in GAP, which would also solve this problem.

**Comment by alex-konovalov** [comment]
@fingolfin @ChrisJefferson I've submitted PR at https://github.com/gap-system/gap/pull/2579 - please have a look.

**Comment by fingolfin** [comment]
While PR #2579 fixes the symptom reported here, it does not explain the cause of the change in ranking. Looking a bit closer, it turns out that the rank of `IsFinite` dropped from 4 in GAP 4.8, to 3 in master. And that of `IsList and IsFinite` even went down from 7 to 4.

I'd like to understand why this happened; and then perhaps we should rank the fallback methods in GAP artificially down, as deciding equality by enumerating the domain really should be a last resort.

**Comment by fingolfin** [comment]
The rank difference indeed comes from hidden implications:
```
# GAP 4.8
gap> NamesFilter(WITH_HIDDEN_IMPS_FLAGS(FLAGS_FILTER(IsFinite)));
[ "IsListOrCollection", "IsCollection", "IsFinite", "Tester(IsFinite)" ]

# GAP 4.9
gap> NamesFilter(WITH_HIDDEN_IMPS_FLAGS(FLAGS_FILTER(IsFinite)));
[ "IsListOrCollection", "IsFinite", "HasIsFinite" ]
```
