### ISSUE TITLE
BrowseConwayPolynomials results have several errors (typos?)

### ISSUE THREAD

**Issue by FifiBonacci** [gap-system/gap#2505]
### Observed behaviour
I got interested in Conway Polynomials, and tried the Browser command above.
Overall very nice! 
But of the polynomials I checked, I found several errors (verified by using the ConwayPolynomial function). The errors are mainly in the exponents. These are the primes and degrees where I saw errors:
p=3: 4-7
p=5: 2-5
p=7: 2-4
p=11: 2
p=13: 2
For example:
 3 │   5 │                                      X^5 + 2 X^2 + 1
should be:
 3 │   5 │                                      X^5 + 2 X^1 + 1
since ConwayPolynomial(3,5) = x_1^5-x_1+Z(3)^0

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.9.1 of 05-May-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin17.5.0-default64
 Configuration:  gmp 6.1.2
 Loading the library and packages ...
 Packages:   AClib 1.3, Alnuth 3.1.0, AtlasRep 1.5.1, AutPGrp 1.9, 
             Browse 1.8.7, CRISP 1.4.4, Cryst 4.1.17, CrystCat 1.1.8, 
             CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.1, IO 4.5.1, 
             IRREDSOL 1.4, LAGUNA 3.9.0, Polenta 1.3.8, Polycyclic 2.13.1, 
             PrimGrp 3.3.1, RadiRoot 2.8, ResClasses 4.7.1, SmallGrp 1.3, 
             Sophus 1.24, SpinSym 1.5, TomLib 1.2.6, TransGrp 2.0.2, 
             utils 0.54
```

**Comment by alex-konovalov** [comment]
@FifiBonacci thank you for reporting this! `BrowseConwayPolynomials` belongs to the Browse package by @frankluebeck and @ThomasBreuer. I've looked at this and there seems to be a bug in the `stringpol` function (which is a local function inside `BrowseConwayPolynomials` that generates a string representation of the polynomial).

**Comment by frankluebeck** [comment]
@FifiBonacci : Thanks for the report. We have fixed this in our repository. A new version of Browse will appear soon.

**Comment by ThomasBreuer** [comment]
Meanwhile a new Browse version is available at [the home page of the Browse package](http://www.math.rwth-aachen.de/~Browse/).
