### ISSUE TITLE
Print an alert when trying to test a non-test file

### ISSUE THREAD

**Issue by emmakatherina** [gap-system/gap#2506]
While working on a GAP package I tried to test a file called `testparallel.g` which itself already calls `TestDirectory()`. As a GAP beginner I didn't know that this file should be called by writing `Read("testparallel.g")` and wouldn't have found out if I wasn't explicitely told about it.
Maybe we could make this part easier for beginners by printing a warning when a non-test file is called by `Test()`?
Me and @ssiccha where thinking about something like ```The tested file is not a test file and should preferably be called with Read().```

Would it be easy to distinguish between test files and non-test files? What do you think about this suggestion?

**Comment by ssiccha** [comment]
The reason for Emma 's confusion was that testing testparallel.g returned true. From the pov of `Test`, it contains no `gap >` input lines but contains “output“ lines. So it just returns true.

Wrt Emma's suggestion: I don't think it is necessary to talk about what a test file or non-test file is. If I read the proposed warning, I would then have to look into the documentation to find out the exact definition of when a file is considered a test file. 

I think `Test` could alternatively give a warning message like `The test file contains no input lines to execute.` This should be easy to implement and is sufficient to let the user know they `Test`ed the wrong file, IMO.

Alternatively, one could let testing a file which contains no `gap >` input lines but contains “output“ lines return false.

**Comment by ChrisJefferson** [comment]
I agree we should do something better. I often run Read on tests and Test and gap files.

I think we should:

1) report if a tested file didn't have any tests in it.
2) (maybe more controversial) warn if a file ending .tst is Read, or a file ending .g/.hi/.gd is Tested.

**Comment by alex-konovalov** [comment]
+1. Maybe a warning when `Test` called on a file not having a `.tst` extension?

**Comment by ssiccha** [comment]
@ChrisJefferson 
1. +1
2. I think printing a warning if Test is called with a .g* file is fine since this doesn't not change behavior when actually testing .tst files.
For Read being called on .tst files: This should anyways throw Syntax errors when it encounters `gap> `. We could  give a special error message in this situation.

**Comment by fingolfin** [comment]
Clearly `Test` should produce an error if it see lines that neither start with `gap>` nor are comments nor are outputs to previous commands. If we manage that, I'd prefer if it did not check the file extensions.

As to `Read`, I think the output one gets now when reading a `.tst` file is "good enough",

**Comment by fingolfin** [comment]
@emmakatherina Thanks for your report. This is now improved in the master branch, and this shall be in GAP 4.10.

**Comment by fingolfin** [comment]
This will also be further improved by #2524
