### ISSUE TITLE
'make manuals' should display gapdoc's error output

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#254]
I've always assumed that gapdoc produces no useful error messages, because when an error occurs when running `make manuals`, the following output is produced:

```
Error,  called from
brk>
```

However, it turns out I have been misjudging gapdoc! There is useful error messages, but they get re-directed into 'make_manuals.out'.

Seeing as GAP sends some parts of it's error message (the 'Error' and 'called from') to stderr, but not the actual message, or (now) the backtrace, probably those two things should also go to stderr as well.

**Comment by fingolfin** [comment]
This was actually (by "accident") addressed recently, because I ditched that log. So now I get this (after deliberately breaking some XML):
```
$ make manuals
GAP_VERSION = 4.8.6-5098-ge4d8d2e-dirty
   SED     src/gap_version.c.in => gen/gap_version.c
   C       gen/gap_version.c => obj/gap_version.lo
   LINK    gap
doc/make_doc
--------------------
Building GAP manuals
--------------------
----------------------------
Building GAP manual 'ref' at /Users/mhorn/Projekte/GAP/gap.github.playground/d\
oc/ref
Run 1 of 2
----------------------------
#I Composing XML document . . .
#I Parsing XML document . . .
XML Parse Error: Line 62864 Character 1
Original file: ./addmagma.xml, line number 105.
-----------
</Chapter>
^
-----------
wrong end tag, expecting "</Chap2ter>" (starts line 62431)
!!! Type 'Show();' to watch the input string in pager - starting with
    line containing error !!!
Or 'ShowOrigin();' to look it up in its source file.
Error,  at /Users/mhorn/Projekte/GAP/gap.github.playground/pkg/GAPDoc-1.5.1/lib/XMLPa\
rser.gi:146 called from
make: *** [Makefile.rules:660: doc] Error 1
~
```

Of course you still get no interactive prompt that would allow you to use `Show()` or `ShowOrigin()`, but I am afraid we can't change that, as `make doc` is supposed to used by automated systems like Travis. But I still think it resolves this issue nicely.
