### ISSUE TITLE
Change PrintCSV to not use SizeScreen

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2545]
Instead it should use something like `SetPrintFormattingStatus`.

For testing, I'd also consider changing `SizeScreen([4096,sz[2]]);` in it temporarily to, say `SizeScreen([40,sz[2]]);` to force an undesirable wrapping; with `SetPrintFormattingStatus` in effect, if all went right, this should be gone.

**Comment by hulpke** [comment]
Can one do this when printing to files given by a string, or does it require setting up a stream?

Is there a concrete problem triggered by SizeScreen, or is it just general cleanup?

**Comment by fingolfin** [comment]
For starters, using an arbitrary cut-off at 4096 means that this has a potential of failing if you get lines longer than 4096 chars. I'd try to create an example to trigger this to test.

What is really wanted here is to disable wrapping, so we should do that, not change the screen size as a workaround. In multi threaded mode, changing the screen size temporarily could have bad effects, too (though I think we already try to isolate the "virtual screen size" between threads)

In this case, I think the simplest solution would be to switch to using a file stream. For any significant amount of data, printing to a file stream is better than using `PrintTo("FILENAME", ...)` anyway, as it's much faster (it avoids having to constantly re-open, seek, write, close the same file).

**Comment by fingolfin** [comment]
But all in all, this is of course not an urgent issue. Feel free to ignore it! I or somebody else may one day write a patch for it, or maybe nobody ever cares -- but I noticed this in the code, and it is may habit to try to either fix issues as I notice them, or else make a note about them here.

**Comment by ssiccha** [comment]
This doesn't sound too complicated to do. I'll label it with "good first issue".

Also, the documentation is a bit inconsistent. It gives `PrintCSV( filename, list[, fields] )` as possible arguments but says:
```
If the option noheader is set to true the line with the record field names will not be printed.
```
