### ISSUE TITLE
Introduce global switch to en/disable printing of tracebacks

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#2547]
This comes from the discussion in #2530.

Currently, `BreakOnError` influences both whether an interactive break loop is started and whether a traceback is printed. Namely, `BreakOnError = false` suppresses both.

Suppressing both break loops and tracebacks is needed by `Test` and its related functions. Otherwise e.g. changes in filenames would introduce diffs when testing error messages.

I suggest to introduce a global variable `TracebackOnError` (or any better name) that controls whether tracebacks are printed. Anything depending on the old behaviour of `BreakOnError = false` would only need to also set `TracebackOnError := false`.

**Comment by fingolfin** [comment]
The problem I have with this proposal is that it requires *changing* all code which relies on the current behaviour; and changing it at the same time, and in a fashion that causes it to at least trigger syntax errors when used with older GAP versions (about unused `TracebackOnError`), unless great care is taken.

Also, all use cases of `BreakOnError` I was aware of before Jupyter really want to suppress tracebacks, so they all need to be adapted.

As I see it, I already suggested an alternate for you to enable the traceback again while still bypassing the break loop; is there a problem with that which means you need something like `TracebackOnError`? What is it?

What I could get behind is something like `AlwaysShowTracebackOnError`; if false, you get the current behavior, if true, you always get the traceback. This way, existing code does not need to be changed.

**Comment by ssiccha** [comment]
> The problem I have with this proposal is that it requires changing all code which relies on the current behaviour; and changing it at the same time, and in a fashion that causes it to at least trigger syntax errors when used with older GAP versions (about unused TracebackOnError), unless great care is taken.

That makes sense. I like the suggestion using `AlwaysShowTracebackOnError`.

> As I see it, I already suggested an alternate for you to enable the traceback again while still bypassing the break loop; is there a problem with that which means you need something like TracebackOnError? What is it?

I think for this to work errorLVars needs to become a global stack (see #2530).

Please correct me if I am wrong, I think whenever one is interacting with GAP from another process (e.g. when using GAP as libGAP) one would benefit from `ErrorInner` also printing tracebacks. So instead of having to overwrite `OnBreak` it would be a lot nicer to just have a command line argument like `--nobreakloop` (which e.g. sets `BreakOnError := false` and `AlwaysShowTracebackOnError := true`).
I am ok with both options but would prefer the latter.

**Comment by fingolfin** [comment]
If `AlwaysShowTracebackOnError` works for you, feel free to make a PR introducing it.

I don't see why interaction with GAP from another process would in general benefit from tracebacks? In some circumstances, they may be helpful for debugging others, but in others, they may be undesirable. If interfacing with Jupyter needs such an interface (or if at least things would be greatly simplified for it that way), let's add it. If not, I'd rather wait for somebody who needs it to actually request it. I don't know, perhaps the SageMath interface would benefit? @nthiery may be able to say more...

**Comment by nthiery** [comment]
>    I don't see why interaction with GAP from another process would in
>    general benefit from tracebacks? In some circumstances, they may be
>    helpful for debugging others, but in others, they may be undesirable.
>    If interfacing with Jupyter needs such an interface (or if at least
>    things would be greatly simplified for it that way), let's add it. If
>    not, I'd rather wait for somebody who needs it to actually request it.
>    I don't know, perhaps the SageMath interface would benefit? [1]@nthiery
>    may be able to say more...

Justine was working last week on running some code of her GAP code
from Sage, and reported briefly to me that it was really a pain to
debug when there was a failure. I did not see it first hand though
to know the exact details.

Anyway, having a traceback displaying the issue on the GAP side would
presumably help in such situations; possibly something turned off by
default but that we could turn on from Sage, e.g. maybe just by:

```
    sage: gap.AlwaysShowTracebackOnError()
```

Maybe this requires something finer (mostly on the Sage side) to
control how the error message is transferred and printed.

Cheers,
                                Nicolas

**Comment by ssiccha** [comment]
@nthiery #2551 got merged into the master branch a few weeks ago and introduces a new command line option `--alwaystrace`. This tells GAP to always print the traceback information when encountering an error. Instead of using `--alwaystrace` at the command line you can also toggle this behavior by setting the global variable `AlwaysPrintTracebackOnError` in GAP to true or false.
