### ISSUE TITLE
Remove DoLowIndexSubgroupsFpGroup_Old 

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/gap#2553]
The following code seems to be obsolete since GAP 4.5.0 - can we remove it? Perhaps @ThomasBreuer (assuming from `T` in the comment) or @hulpke could confirm? 

https://github.com/gap-system/gap/blob/c6bd9d13c9a69cb38c89a4674cd297ca716f4327/lib/grpfp.gi#L5584-L5596

**Comment by hulpke** [comment]
Oh -- I have thought for >20 years that #T is TODO.
Anyhow, the old code was left there just in case the new code had some horrible bug, it could safely go.

**Comment by fingolfin** [comment]
Yes, `#T` means TODO. Though I prefer to spell that out in new comments.
