### ISSUE TITLE
Renormalise runtimes in tests

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#256]
Tests claim that the `next' time is an approximation of the running time for the next file, but many of the values does not match the reality.

**Comment by ChrisJefferson** [comment]
I don't know how this is done -- so it might have gotten broken when I rearranged the tests. If you know how it used to be done, let me know, and I'll have a look.

**Comment by alex-konovalov** [comment]
The starting point would be `teststandardrenormalize` target in the Makefile. What it does is described in https://github.com/gap-system/gap/blob/master/doc/dev/testing.xml. Most likely it needs an update after the tests were rearranged.

**Comment by ChrisJefferson** [comment]
An initial patch to do this is at #257, need to update the dev documentation, and probably delete the old code (also, might need the gapstones we aim for setting correctly -- I couldn't find what it was so I went for 10,000).

**Comment by alex-konovalov** [comment]
I've renormalised runtimes and committed new values in https://github.com/gap-system/gap/commit/79206f6613e8056459003299cd550b587866ae0e. I've run `make teststandard` on Linux 8-core desktop and no problems were reported. Let's see now how it goes on other machines, because the order in which tests are performed may be changed, so there could be possible side-effects. 

Remarkably, I did not tweak any values to ensure that the tests will be run either very early or very late in `teststandard.g` - that hack was used in the past e.g. to move `bugfix.tst` and `grpconst.tst` to the very end since they load some packages. This is not very reproducible practice, since one can't in this case just run `make teststandardrenormalize` automatically and commit chages. I hope we may not use this hack any more. If we want a clean approach, we should put tests loading additional GAP packages into separate targets.

Finally, I am puzzled that teststandard runtimes are 1912636ms and 2061179ms without/with packages respectively, but corresponding GAP4Stones are 10320 and 4884. Why slowdown from 31 to 34 minutes causes more than two times less GAP4Stones? Was it wrong to reduce the reference number from 100K to 10K?

**Comment by alex-konovalov** [comment]
P.S. Let's keep this issue open for now - at least the documentation  should be updated to specify what's the machine where the reference numbers were produced.

**Comment by alex-konovalov** [comment]
After renormalisation, the order of tests changed and ONLY in 64-bit mode we have a diff if ALL packages are loaded:
```
########> Diff in /Volumes/hudson-fs/workspace/GAP-dev/GAPCOPTS/64build/GAPGMP\
/gmp/GAPTARGET/standard/label/fruitloop/GAP-git-snapshot/tst/teststandard/hash\
2.tst, line 23:
# Input is:
Length(Orbit(h,h.1,OnPoints));   
# Expected output:
32385
# But found:
Error, reached the pre-set memory limit
(change it with the -o command line option)
########
```
I will investigate if this point to something serious.

**Comment by alex-konovalov** [comment]
Running out of memory stopped with new `-o 1g` setting.
