### ISSUE TITLE
HPC-GAP grpperm.tst Diff

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#26]
Running the grpperm.tst in HPC-GAP on my machine does not only take an exorbitant amount of time (4 minutes in GAP, more than 10 in HPC-GAP) it also Diffs:

```
########> Diff in tst/grpperm.tst, line 76:
# Input is:
NrMovedPoints(g/h);
# Expected output:
168
# But found:
112
########
```

I can reproduce this with the current hpcgap-default branch on my laptop and lovelace, one of our Linux test machines. Hence, it is not just a fluke caused by my obscure operating system (DragonFly 4.1-DEVELOPMENT).

**Comment by alex-konovalov** [comment]
Thanks. This diff is known and safe to ignore for now (though the test probably should be reworked to run smoothly). It comes from a different degree of a permutation representation. 

The slowdown should be investigated indeed.

**Comment by alex-konovalov** [comment]
I've tried to have a look at slowdown, but at the moment I can't run `grpperm.tst` in HPC-GAP. The following example is broken:
```
gap> g:=WreathProduct(MathieuGroup(11),Group((1,2)));
<permutation group of size 125452800 with 5 generators>
gap> Length(ConjugacyClassesSubgroups(g));
Error, Attempt to write object 4413342128 of type object (weakptr) without having write access in
  while i <= Length( f )  do
    a := ElmWPObj( f, i );
...
...
od; on line 1117 of file /Users/alexk/GITREPS/hpcgap-fork/lib/pcgsperm.gi
```
and the next as well, with the backtrace pointing to the same location at `pcgsperm.gi`:
```
gap> g:=SemidirectProduct(GL(3,5),GF(5)^3);
<matrix group of size 186000000 with 3 generators>
gap> g:=Image(IsomorphismPermGroup(g));
```
Looks like this is a side-effect of PR #51.

**Comment by markuspf** [comment]
I am having a hard time reproducing this. It seems to mainly happen in travis tests. I have only seen this fail once on my laptop and now have run testbugfix.g and tesstravis.g on lovelace multiple times and these examples just work.

Even though this is the mapping code, the error happens in a region that (as far as I can see) does not want to write to the weakptr object. I have tried (in my own fork) to use atomic readwrite, but something is odd here.

I will open a new issue as soon as I have more information.

**Comment by ChrisJefferson** [comment]
This could be an issue with weakptrs -- I don't know if hpc-gap actually does anything with weak ptrs yet, probably worth having a look.

**Comment by markuspf** [comment]
On Tue, Mar 17, 2015 at 11:41:42PM -0700, Christopher Jefferson wrote:
> This could be an issue with weakptrs -- I don't know if hpc-gap actually does
> anything with weak ptrs yet, probably worth having a look.

Yes it does, even though there's no guarantee that it does it right of course.

The error message is actually a WriteGuard error message, so it's probably
best to first refer to @rbehrends.

**Comment by alex-konovalov** [comment]
Please note that the 2nd example is much faster, so it's more convenient for debugging: 
```
gap> g:=SemidirectProduct(GL(3,5),GF(5)^3);
<matrix group of size 186000000 with 3 generators>
gap> g:=Image(IsomorphismPermGroup(g));
<permutation group of size 186000000 with 3 generators>
```
It also works after replacing `readonly` by `readwrite` in `lib/pcgsperm.gi`.

**Comment by alex-konovalov** [comment]
@markuspf @ChrisJefferson Wonderful, thanks - #77 should fix access problem, then I may have a look at performance.

**Comment by fingolfin** [comment]
Getting back to the original issue here: Testing `NrMovedPoints(g/h)` is nonsense to start with, as its depends on a randomized algorithm. Indeed, if I enter 
```
gap> g:=Group([
> (2,3,5,4)(6,14,21)(7,12,22,9,13,24,10,11,25,8,15,23)(16,32,27)(17,31,
> 29,18,35,26,20,33,30,19,34,28), (1,26,25,2,28,24)(3,30,23,5,29,21)
> (4,27,22)(6,9)(7,8)(11,18,35,13,16,31,12,17,33,15,19,32)(14,20,34) ]);;
gap> h:=Group([ (31,32,33,34,35), (26,27,28,29,30), (21,22,23,24,25),
> (16,17,18,19,20), (11,12,13,14,15), (6,7,8,9,10), (1,2,3,4,5) ] );;
gap> NrMovedPoints(g/h);
```
into a fresh HPC-GAP sessions, I get `224`; doing the same with my regular GAP, I get 1920 (!), but doing it again, or when I start my regular GAP with `-A` I get 224. This is (as far as I could tell) all due to the state of the random number generators. Hence, the above three commands should simply removed from the test, as they do not constitute a valid test of anything. Or, if one wants to pretend that this is a useful test of the factor code for perm groups (it really isn't), then replace `NrMovedPoints` by e.g. `Size`.

I changed this in master and hpcgap-default accordingly.

**Comment by alex-konovalov** [comment]
So far I have identified that the commands causing the most visible slowdown are
```
g:=WreathProduct(MathieuGroup(11),Group((1,2)));ConjugacyClassesSubgroups(g);
```
Using `MathieuGroup(10)` gives you a more convenient smaller example - it also runs slower in HPC-GAP.

**Comment by stevelinton** [comment]
I haven't got any closer to understanding the difference wqith HPCGAP, but thanks to 
Chris's profiler I am on the track of a massive speedup for grpperm.tst in gap4, and hopefully helping other permutation group code as well.

**Comment by alex-konovalov** [comment]
This example fails again:
```
########> Diff in /home/hudson/hudson/workspace/GAP-HPC-standard/GAPABI/64/GAPGC/boehm/GAPGMP/gmp/label/graupius/GAP-HPC-snapshot/tst/grpperm.tst, line 80:
# Input is:
Length(ConjugacyClassesSubgroups(g));
# Expected output:
2048
# But found:
Error, Attempt to write object 367891616 of type list (plain,cyc) without having write access
```
This happened before today's merge - I've seen this in alpha-release test logs on Saturday for the first time.

**Comment by markuspf** [comment]
On Mon, Mar 23, 2015 at 01:37:45PM -0700, Alexander Konovalov wrote:
> This example fails again:
> 
> ########> Diff in /home/hudson/hudson/workspace/GAP-HPC-standard/GAPABI/64/GAPGC/boehm/GAPGMP/gmp/label/graupius/GAP-HPC-snapshot/tst/grpperm.tst, line 80:
> # Input is:
> Length(ConjugacyClassesSubgroups(g));
> # Expected output:
> 2048
> # But found:
> Error, Attempt to write object 367891616 of type list (plain,cyc) without having write access
> 
> This happened before today's merge - I've seen this in alpha-release test logs
> on Saturday for the first time.
> 
> 

Can you specify in which context this fails? I cannot reproduce this on my
computer right now.

**Comment by ChrisJefferson** [comment]
Can you try completely clearing the workspace? I saw this, and then it
disappeared after I completed blasted my workspace clean (of course, it
might come back).

**Comment by alex-konovalov** [comment]
This was first observed in Jenkins build - in this setting, we perform each build starting from a completely wiped workspace to avoid interacting with relics of the past builds. Next, for this build some GAP 4 packages are just dropped into pkg directory as they are needed by some tests (this should be really cleaned up, but so far that's the case). The minimalistic set of packages to please `testall.g` is: 
* autpgrp-1.5.tar.gz
* atlasrep1r5p0.tar.gz 
* ctbllib-1r2p2.tar.gz
* grpconst-2.3.tar.gz
* irredsol-1r2n4.tar.gz
* tomlib1r2p4.tar.gz

(we do not need GAPDoc as it's already there in the hpcgap-default branch). 

Now you may see what happens below. The error is in the GAP library file, but it's triggered by the call from AutPGrp package which is called from `AutomorphismGroup`:
```
gap>  g:=WreathProduct(MathieuGroup(11),Group((1,2)));
<permutation group of size 125452800 with 5 generators>
gap> Length(ConjugacyClassesSubgroups(g)); 
...
Loading  AtlasRep 1.5.0 (An Atlas of Group Representations) ...
Loading  CTblLib 1.2.2 (The GAP Character Table Library) ...
Loading  TomLib 1.2.4 (The GAP Library of Tables of Marks) ...
Loading  AutPGrp 1.5 (Computing the Automorphism Group of a p-Group) ...
...
Error, Attempt to write object 88089632 of type list (plain,cyc) without having\
 write access in
  wt{n + [ 1 .. nhwg ]} := [ 1 .. nhwg ] * 0 + class
 ; on line 503 of file /home/hudson/hudson/workspace/GAP-HPC-standard/GA\
PABI/64/GAPGC/boehm/GAPGMP/gmp/label/graupius/GAP-HPC-snapshot/lib/pquot\
.gi called from 
UpdateWeightInfo( qs 
 ); on line 587 of file /home/hudson/hudson/workspace/GAP-HPC-standard/G\
APABI/64/GAPGC/boehm/GAPGMP/gmp/label/graupius/GAP-HPC-snapshot/lib/pquo\
t.gi called from
DefineNewGenerators( qs 
 ) on line 1644 of file /home/hudson/hudson/workspace/GAP-HPC-standard/G\
APABI/64/GAPGC/boehm/GAPGMP/gmp/label/graupius/GAP-HPC-snapshot/lib/pquo\
t.gi called from
PCover( Q 
 ) on line 336 of file /home/hudson/hudson/workspace/GAP-HPC-standard/GA\
PABI/64/GAPGC/boehm/GAPGMP/gmp/label/graupius/GAP-HPC-snapshot/pkg/autpg\
rp/gap/autos.gi called from
AutomorphismGroupPGroup( G 
 ) on line 405 of file /home/hudson/hudson/workspace/GAP-HPC-standard/GA\
PABI/64/GAPGC/boehm/GAPGMP/gmp/label/graupius/GAP-HPC-snapshot/pkg/autpg\
rp/gap/autos.gi called from
AutomorphismGroup( G 
 ) on line 1875 of file /home/hudson/hudson/workspace/GAP-HPC-standard/G\
APABI/64/GAPGC/boehm/GAPGMP/gmp/label/graupius/GAP-HPC-snapshot/lib/morp\
heus.gi called from
...  at line 2 of *stdin*
brk> LastInaccessible;
[ 1, 1, 2, 2, 2, 2, 2 ]
brk> RegionOf(LastInaccessible);
<region: read-only region>
brk> wt;
[ 1, 1, 2, 2, 2, 2, 2 ]
```

**Comment by markuspf** [comment]
I still cannot reproduce this. This is also a different problem from the initial issue. This sort of hiding in an issue another issue is not good practisae, and I'd rather open a new issue that describes the problem, if anyone can reproduce it?

**Comment by markuspf** [comment]
I will close this issue since the original issue was fixed by @fingolfin and entailing issues are either hard or impossible to reproduce. I suggest opening a new issue in case this problem comes up again.
