### ISSUE TITLE
No rule to make target 'gap_version.h', needed by 'system.o' (Windows)

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#261]
Building GAP binaries for Windows (GAP-major-release-win-build in Jenkins) fails as follows:
```
gcc -I. -I../.. -DCONFIG_H  -I/cygdrive/c/Users/jenkins/workspace/GAP-major-release-win-build/gap4r8/bin/i686-pc-cygwin-gcc-default32/extern/gmp/include -Wall -g -O2  -g -O2  -o sysfiles.o -c ../../src/sysfiles.c
make[1]: *** No rule to make target 'gap_version.h', needed by 'system.o'.  Stop.
make[1]: Leaving directory '/cygdrive/c/Users/jenkins/workspace/GAP-major-release-win-build/gap4r8/bin/i686-pc-cygwin-gcc-default32'
Makefile:428: recipe for target 'cygwin' failed
make: *** [cygwin] Error 2
Build step 'Execute shell' marked build as failure
Archiving artifacts
```

**Comment by markuspf** [comment]
On Sun, Sep 27, 2015 at 03:08:53PM -0700, Alexander Konovalov wrote:
> Building GAP binaries for Windows (GAP-major-release-win-build in Jenkins)
> fails as follows:
> 
> gcc -I. -I../.. -DCONFIG_H  -I/cygdrive/c/Users/jenkins/workspace/GAP-major-release-win-build/gap4r8/bin/i686-pc-cygwin-gcc-default32/extern/gmp/include -Wall -g -O2  -g -O2  -o sysfiles.o -c ../../src/sysfiles.c
> make[1]: *** No rule to make target 'gap_version.h', needed by 'system.o'.  Stop.
> make[1]: Leaving directory '/cygdrive/c/Users/jenkins/workspace/GAP-major-release-win-build/gap4r8/bin/i686-pc-cygwin-gcc-default32'
> Makefile:428: recipe for target 'cygwin' failed
> make: *** [cygwin] Error 2
> Build step 'Execute shell' marked build as failure
> Archiving artifacts

Someone familiar with the release process will have to write a/adapt the
script that generates gap_version.h to reflect the gap version and build date.

The file cnf/mkversionheader.sh is currently used when building from a git
tree.

This is basically #234

**Comment by alex-konovalov** [comment]
Thanks. Looks related to https://github.com/gap-system/gap-distribution/issues/1 as well.

**Comment by alex-konovalov** [comment]
Fixed in commit https://github.com/gap-system/gap/commit/a44ee24472f46bb9669e5851a555bda372621b30
