### ISSUE TITLE
Unused functions in ctbl.gi

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2646]
The following functions are unused (found by looking at <https://codecov.io/gh/gap-system/gap/src/master/lib/ctbl.gi>), nor do they seem to be documented.

* CharacterTable_IsNilpotentNormalSubgroup
* ColumnCharacterTable
* ClassPositionsOfSolvableRadical
* CharacterTableOfNormalSubgroup

Should they be used somewhere? Documented for users? Removed? Maybe @ThomasBreuer knows more?

I also noticed that there are two methods installed for `CorrespondingPermutations` in `lib/ctblfuns.gi`, one with 2 and one with 3 args. But except for one `else if` clause, plus some tiny (accidental??) differences, they are identical. Perhaps it would be better to merge the two into one?

**Comment by alex-konovalov** [comment]
@fingolfin @ThomasBreuer #2681 has been merged - just to check, is this issue fully addressed now and may be closed?

**Comment by fingolfin** [comment]
I think so
