### ISSUE TITLE
document IrreducibleRepresentations(...:unitary)

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#265]
things like  IrreducibleRepresentations(SL(2,5):unitary); work in 4.7.8, but are not documented.

**Comment by alex-konovalov** [comment]
Thanks, this is already documented in `IrreducibleRepresentationsDixon` manual section in the master branch and will appear in GAP 4.8:
```
##  If the option unitary is given GAP tries, at extra cost, to find a
##  unitary representation (and will issue an error if it cannot do so).
```
