### ISSUE TITLE
Bug in example package

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#2653]
(I know that is an unhelpful subject, but I don't have anything better).

A problem has been observed running the 'example' package tests, see for example:

https://travis-ci.org/gap-system/gap-docker-pkg-tests-master/jobs/403360835

Some lines of the output are disappearing.

I tracked the first appearance of the bug to: `c5d05fc0595e42e`. However, I don't think that is the true source -- if I remove the part of the diff which changes `tst/testutil.g`, the bug goes away, even though that code is never actually run when finding the bug.

On some computers I can reproduce the bug by running:

`echo 'SetAssertionLevel( 2 ); ReadGapRoot( "tst/testutil.g" ); SetUserPreference("UseColorsInTerminal",false); RunPackageTests( "example", "4.1.0", "tst/testall.g", "false" );' | /home/caj/files/reps/gap/gap/bin/gap.sh --quitonbreak -b -m 100m -o 1g -q -x 80 -r -A`

(you may have to adjust 4.1.0 if you have a different version of example, but that's fine).

**Comment by ChrisJefferson** [comment]
UPDATE: Found out why `c5d05fc0595e42e` introduced a bug. We can reduce `CheckOutputDelegations` to:
```
BindGlobal( "CheckOutputDelegations",
function()
local m;
    Error("CHEESE");
     m.method;
end);
```

(The `Error` is to prove this method is never run). The problem arises when `method` is used. I assume this is because we have a global lookup table of record names, and this is introducing `method` into this cache. I don't know why this is then causing weird bugs. However, the broken part of `Example` is also using the record name `method`.

**Comment by ChrisJefferson** [comment]
UPDATE: There is no bug. Example is assuming RecNames is sorted. Sorry.

**Comment by alex-konovalov** [comment]
@ChrisJefferson thanks - done in https://github.com/gap-packages/example/pull/19, new release of Example package is coming shortly.
