### ISSUE TITLE
Error message <corrupted statement> when using `[i,j]` with invalid indices

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#2656]
In GAP 4.9.1 and in the current master branch I get:
```
gap> l := [[1]];
[ [ 1 ] ]
gap> f := {} -> l[2,1];
function(  ) ... end
gap> f();
Error, List Element: <list>[2] must have an assigned value in
  return m[i][j]; at /home/sergio/projects/gap-master/lib/matrix.gi:30 called from 
<corrupted statement>  called from
<function "f">( <arguments> )
 called from read-eval loop at *stdin*:3
you can 'return;' after assigning a value
brk> 
```

Is it worth the effort to let GAP show the line from where the offending `l[2,1]` was called?

**Comment by stevelinton** [comment]
It's easy to fix this problem -- Just add `SET_BRK_CALL_TO( expr)` in `EvalElm2List` much as it appears in `ElmList`, and it seems to work correctly. 

However, when I starting looking through related  functions, though like `EvalElmsList` and `EvalAss2List` I become confused about where `SET_BRK_CURR_STAT` and `SET_BRK_CALL_TO` ought to appear and why. Does anyone understand the rules for these? If so, any chance of writing something about them (perhaps as comments `vars.h` where they are defined?

**Comment by ChrisJefferson** [comment]
I did look at this at some point, and got confused. I think @fingolfin was looking too, not sure how confused he got. This might require a sit down at a gap days to decide what we want, once and for all :)

**Comment by stevelinton** [comment]
It looks like PR #2520 is WIP on tackling this.

**Comment by fingolfin** [comment]
I'll take care of this as part of PR #2520 (or some successor PR)
