### ISSUE TITLE
Avoid the need to repeatedly traverse long plain lists with mutable contents in method selection.

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#266]
Method selection for certain plain lists is very slow:

 The problem arises for long lists containing mutable objects. In that case since the list has no way of being alerted when one of its (recursive) entries is mutated, it cannot remember very much about its type. So when any Operation is called on it, it has to decide its type, for which purpose it needs to traverse the list (and recursively any other lists with mutable subobjects). This is linear-time, but still expensive compared to just looking up a type.

To get out of this we have to do one of two things, neither of them easy:
1. Set up some kind of notification mechanism, so that the list can provisionally remember its type, and be notified when any subobject mutates so that it can adjust or forget the type. This is fiddly low-level code that risks slowing down all object access.
2. Redefine the promises about what type information will be available for lists, so that method selection can be done without traversing the list (so the list will have some very weak type). This will involve installing a lot of methods for such untraversed lists all over the library.

2 is probably the better solution, especially now we have vector objects which should be prefered for one use case of plain lists anyway, but it's a lot of work.

**Comment by fingolfin** [comment]
I don't think either is realistically feasible w/o breaking a lot of stuff and/or *major* efforts.

Instead we now have `InstallEarlyMethod` to make it possible to deal with plain lists of lists before starting method dispatch. This is not great, but at least it works and does not break existing code.
