### ISSUE TITLE
Should `\<` and `\>` be balanced?

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#2677]
The markers `\<` and `\>` can be used to indicate preferences for line breaks.
I would expect that the two markers should be balanced inside individual
`ViewObj`, `ViewString` etc. methods.
Is this the case?

Background  of the question:
Recently I stumbled over an unbalanced example, in `lib/csetgrp.gi`:
```
InstallMethod(ViewString,"DoubleCoset",true,[IsDoubleCoset],0,
function(d)
  return(STRINGIFY("DoubleCoset(\<",
                   ViewString(LeftActingGroup(d)),",\>",
                   ViewString(Representative(d)),",\>",
                   ViewString(RightActingGroup(d)),")"));
end);
```
A heuristic filter for finding such cases is the following.
```
gap> unbalanced:= function( func )
>       local str;
>       str:= String( func );
>       return Length( PositionsSublist( str, "\\<" ) ) <>
>              Length( PositionsSublist( str, "\\>" ) );
>    end;
gap> meth:= MethodsOperation( ViewString, 1 );;
gap> cand:= Filtered( meth, r -> unbalanced( r.func ) );;
gap> Length( cand );
13
```
(Of course, `unbalanced` may find candidates that return balanced strings,
and methods that return unbalanced strings may be overlooked by `unbalanced`,
for example due to `if` statements in the code of the method in question.)

**Comment by fingolfin** [comment]
This is a bug. It throws of the printing logic, and also causes a spurious newline to be added when viewing a double coset:
```
gap> G:=SymmetricGroup(2);
Sym( [ 1 .. 2 ] )
gap> s:=DoubleCoset(G, (1,2,3), G);
DoubleCoset(Sym( [ 1 .. 2 ] ),(1,2,3),Sym( [ 1 .. 2 ] ))

gap> RightCoset(G, (1,2,3));
RightCoset(Sym( [ 1 .. 2 ] ),(1,2,3))
```

**Comment by fingolfin** [comment]
Twelve of the matches reported go back to the same two functions in the library, namely `_ViewStringForSemigroups` and `_ViewStringForSemigroupsGroups`. In one case, this is a spurious match, in the other an actual bug. I will make a PR fixing both.

Also, I thought `\>` increased the indent and `\<` decreased it -- in light of that, their use in the `ViewString` methods for double and right cosets makes no sense to me, as both first *decrease* it in the middle of printing, and then later increase it again. I think these should either be reversed, or simply removed. Perhaps @hulpke has some insights on this?

**Comment by frankluebeck** [comment]
> Also, I thought \> increased the indent and \< decreased it 

I would say that one should not interpret these characters in terms of  "indentation". The `\<` decreases and `\>` increases the likelihood that GAP will insert a line break in this place. E.g., `"\< := \>"` tells GAP that a line break after the `":="` is preferable to a line break before.  So, it can be sensible  that the `\<` are coming first.

Unfortunately,  GAP's algorithm for deciding line breaks using the `\<\>` hints is complicated and not easy to describe (understand).

**Comment by fingolfin** [comment]
So the answer to the question in this answer is "yes" (at least IMHO, and nobody voiced a different opinion). And several places were this was incorrect have been fixed.

Can this issue be closed now then?

**Comment by ThomasBreuer** [comment]
Yes, this can be closed.
