### ISSUE TITLE
An error in executing a .gap file

### ISSUE THREAD

**Issue by BuddhiniAnge** [gap-system/gap#2679]
I am trying to load two .gap files but I receive the following error message. What could be the reason?

Thanks a lot in advance.

![image](https://user-images.githubusercontent.com/42027545/43571541-d6ef51f8-965a-11e8-8a1d-fe3a745becf1.png)

I have already read F1.gap file. I don't understand why it says F1 must be readable to load the F2.gap file.

Please help me to solve this problem.

**Comment by stevelinton** [comment]
The error message tells you that F1 is being read from line 23 of F2. So your F2 file must include a line which Reads F1. Just because GAP has read a file once, doesn't stop you reading it again.

**Comment by BuddhiniAnge** [comment]
Thanks a lot.

Is there a way I can make it function properly? Is there a code which can be used in the command window above or should I type Read("  ") for F1 in the F2's file by opening it? And if so how can I open the F2's file? Is it by typing as Open(" / F2.gap")?.

Please help me in this regard.

Thanks.

**Comment by stevelinton** [comment]
You will need a general purpose text editor and you will need to understand what the two files are actually doing, and why F2 reads F1 at that point in order to adjust them appropriately.

**Comment by BuddhiniAnge** [comment]
Is it like notepad(general purpose text editor)?

**Comment by stevelinton** [comment]
I think so, but I'm not really a windows user.

**Comment by BuddhiniAnge** [comment]
Ok, Thank you very much for helping.😊

**Comment by BuddhiniAnge** [comment]
I was able to adjust the previous error, Thanks to your help.

But now I'm getting a new error as in the image below. Can you please explain and help to solve it.

Thanks a lot.
![image](https://user-images.githubusercontent.com/42027545/43624525-9c03f87c-9705-11e8-9987-ac6ea49ad362.png)

**Comment by stevelinton** [comment]
Could you maybe attach your F1 and F2 files? It's much easier to debug something if you can see it.

**Comment by BuddhiniAnge** [comment]
OK.
[Set of .gap files.zip](https://github.com/gap-system/gap/files/2256425/Set.of.gap.files.zip)

I have named the file "IsHamiltonianCycle" as F1, "LKH" as F2 in my image used for the question and the file UndirectedGeneratingSets is required to run them both.

**Comment by stevelinton** [comment]
So your F1 file isn't a GAP input file. It's a log file, and contains very little of use. Have you accidentally overwritten the file you meant to use?

**Comment by BuddhiniAnge** [comment]
Yes, that's what must have happened. After seeing your comment, now I checked by taking another copy of the file and it worked (I am using some programs written and available open source so I downloaded a new copy of F1 now).

Thanks a lot!😊😊😊

**Comment by alex-konovalov** [comment]
@BuddhiniAnge: about an editor for Windows, please see [this question from GAP F.A.Q](https://www.gap-system.org/Faq/faq.html#8.3). I use Notepad++ when I need to so some work on Windows from time to time, and it seems quite good, especially with the syntax highlighting module by @fingolfin.
