### ISSUE TITLE
Setup Travis tests for Julia integration

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2685]
Now that the Julia GC code has been merged, it would be good to make sure it doesn't get broken accidentally. For now, I am trying to ensure that by watching out for "suspicious" PRs, but of course it'd be better to just compile and test it on Travis, via a new `testjulia` Travis job.

The main obstacle for that is that we need a patch version of Julia for that, based on the code in https://github.com/JuliaLang/julia/pull/28368 -- but compiling Julia from scratch simply takes too long for a simple Travis job.

To fix this, we need to upload a prebuilt Julia binary somewhere and then download/install it as part of the `testjulia`. One way to do that might be by using Docker? (Perhaps @sebasguts or @alex-konovalov have some insights on that). Another much more naive approach is that somebody builds that Julia branch on a system running a compatible Ubuntu version, and we just turn that into a tarball. (Of course then we need to update it whenever the Julia PR is updated).

**Comment by sebasguts** [comment]
We could configure travis itself to upload a julia binary, build out of the PR, to GitHub. This way we could update it everytime the PR changes, along with the tests. It would be built in a compatible environment, too.

Otherwise we would have to run the test in a dockerimage. I think @alex-konovalov has a setup for running travis tests in docker.

**Comment by fingolfin** [comment]
@sebasguts I am a bit worried that we'd hit the 50 minutes limit for jobs on Travis when trying to build Julia from scratch, though.. but if somebody wants to try that, that'd be awesome.

**Comment by fingolfin** [comment]
This was done some time ago
