### ISSUE TITLE
LogFFE returns negative results on 32 bit

### ISSUE THREAD

**Issue by grahamee** [gap-system/gap#2687]
On Win32:

```
gap> LogFFE(Z(37^3)^49564,Z(37^3)^1055);
-44792
```
On Linux and Mac (64 bit) versions the correct value is returned:

```
gap> LogFFE(Z(37^3)^49564,Z(37^3)^1055);
38120
```
The returned negative value is exactly consistent with a 32-bit signed integer overflow in the multiplication at finfield.c:1753.

I guess there are a limited number of cases where this can happen, with fields close to the limit for the internal representation. 

```
 ┌───────┐   GAP 4.9.2 of 04-Jul-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: i686-pc-cygwin-default32
 Configuration:  gmp 6.0.0, readline
 Loading the library and packages ...
 Packages:   AutPGrp 1.9, CRISP 1.4.4, FactInt 1.6.2, GAPDoc 1.6.1, GRAPE 4.8, GrpConst 2.6, IO 4.5.1, IRREDSOL 1.4,
             PrimGrp 3.3.1, SmallGrp 1.3, TransGrp 2.0.2
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by fingolfin** [comment]
Thanks for the report and the analysis, much appreciated! I am working on a fix, which will be in GAP 4.10, due to be released later this year. (we might also backport it to GAP 4.9.3, *if* we make such a release, which I don't know yet.
