### ISSUE TITLE
Quaternion groups and Dicyclic groups, bug? confusion?

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#2725]
On the current GAP master branch (and probably past GAPs) the following happens, which is at least surprising:

```
gap> Q := QuaternionGroup(12);;
gap> IsQuaternionGroup(Q);
false
```

Now this could be because of different definitions of `QuaternionGroup` being used in the constructor vs the method for `IsQuaternionGroup`; it looks like the documentation uses `DicyclicGroup` and `QuaternionGroup` interchangeably (and `grp/basic.gd` declares `QuaternionGroup` and `DicyclicGroup` as synonyms).

 "My definion" of `QuaternionGroup` would be "Dicyclic group whose order is a power of 2" (though I don't have a reference to back that up right now, other than wikipedia).

This view is supported by the following (except that there seems to be a minimum size of 8 as well):

```
gap> Qs := List(4*[1..32], QuaternionGroup);;
gap> List(Qs, x->[Size(x), IsQuaternionGroup(x)]);
[ [ 4, false ], [ 8, true ], [ 12, false ], [ 16, true ], [ 20, false ], [ 24, false ], 
  [ 28, false ], [ 32, true ], [ 36, false ], [ 40, false ], [ 44, false ], 
  [ 48, false ], [ 52, false ], [ 56, false ], [ 60, false ], [ 64, true ], 
  [ 68, false ], [ 72, false ], [ 76, false ], [ 80, false ], [ 84, false ], 
  [ 88, false ], [ 92, false ], [ 96, false ], [ 100, false ], [ 104, false ], 
  [ 108, false ], [ 112, false ], [ 116, false ], [ 120, false ], [ 124, false ], 
  [ 128, true ] ]
```

Maybe @hulpke has an opinion on this?

**Comment by hulpke** [comment]
@markuspf 
No, I've not been involved with the function and only know quaternion groups for 2-power order.

**Comment by alex-konovalov** [comment]
"My definitions" have only one quaternion group which has order 8, and use the term "generalised quaternion group" for other dicyclic groups of order 2^n.

**Comment by markuspf** [comment]
Looking at the documentation of `QuaternionGroup` and `DicyclicGroup` its also out of date, so I could update it.

I'd rename `QuaternionGroup` to `DicyclicGroup`; the same with `QuaternionGroupCons`. That by itself is straightforward.

Question is: If I change `QuaternionGroup` to require the size of the group to be a power of 2 (or even to be equal to 8) that might break some code so I fear that ship might have sailed.

I could add a new function `GeneralisedQuaternionGroup` (and filter `IsGeneralisedQuaternionGroup`) that requires the size to be a power of 2. 

All these functions would end up in `DicyclicGroup` (resp. `IsDicyclicGroup`) in the end.

**Comment by fingolfin** [comment]
I like the plan @markuspf proposes. I.e. instead of making `DicyclicGroup` a synonym of `QuaternionGroup` (i.e. the current state), swap this. As to checking for powers of 2 in `QuaternionGroup`: yes, making that a requirement now is risky. But you could install an `InfoWarning` that is shown in that case. And we could think about making this an obsolete feature (i.e. so that when `-O` is passed, it gets turned off), and/or threaten to remove it in a future GAP version.

BTW, note that `IsQuaternionGroup` (and also `QuaternionGenerators`) are undocumented parts of `grpnames.gd`, just like most of that file; so one may wonder whether to change that.
