### ISSUE TITLE
Repsn IrreducibleAffordingRepresentation dies for some groups

### ISSUE THREAD

**Issue by JacekHoleczek** [gap-system/gap#2728]
I get the following error (for the second group in the gap code below):
```
######################################################################
########## ... gap 4.7.6 32-bit / Linux x86_64 ... ##########
Error, exceeded the permitted memory (`-o' command line option) in
  MakeImmutable( a ); called from
UnderlyingElement( left ) * UnderlyingElement( right ) called from
seed[1][j] * seed[3] called from
Group_PseudoRandom( grp ) called from
PseudoRandom( grp ); called from
Group_InitPseudoRandom( grp, i + 10, Maximum( i * 10, 100 ) ); called from
...  at line 26 of *stdin*
you can 'return;'
########## ... gap 4.9.1 64-bit / Linux x86_64 ... ##########
Error, reached the pre-set memory limit
(change it with the -o command line option) in
  MakeImmutable( a ); at /.../lib/wordlett.gi:421 called from
UnderlyingElement( left ) * UnderlyingElement( right ) at /.../lib/grpfp.gi:146 called from
seed[2] * seed[1][k] at /.../lib/grp.gi:5198 called from
Group_PseudoRandom( grp ) at /.../lib/grpfp.gi:348 called from
PseudoRandom( grp ); at /.../lib/grp.gi:5171 called from
Group_InitPseudoRandom( grp, i + 10, Maximum( i * 10, 100 ) ); at /.../lib/grp.gi:5184 called from
...  at *stdin*:26
you can 'return;'
######################################################################
```
when I try (I tried to play with the "-o" command line option but it didn't help):

######################################################################
```
if not IsBound(groups) then
  groups := [ SmallGroup(60, 5),
              Image(IsomorphismFpGroup(SmallGroup(60, 5))) ];
fi;

SetPrintFormattingStatus("*stdout*", false);

RequirePackage("repsn");;

for g in groups do
  c := Irr(g);
  Print("\n\n", IdGroup(g), " ", StructureDescription(g), "\n");
  for i in([1..Size(c)]) do
    if c[i][1] = 3 then # 3-dimensional representations only
      Print("\n... ", i, " ... "); View(c[i]); Print("\n");
      r := IrreducibleAffordingRepresentation(c[i]);
      # Print("\nDisplay(r) ... \n"); Display(r);
      im := Image(r);
      Print("\nDisplay(Image(r)) ... \n"); Display(im);
      break; # the very first 3-dimensional representation only
    fi;
  od;
od;
```
######################################################################

**Comment by alex-konovalov** [comment]
Thank you for your question. This is what happens here: the first group is given as a permutation group, and the second, while being isomorphic to the first, is given as a finitely presented group. GAP supports groups in different internal representations - permutation groups, matrix groups, [pc groups](https://www.gap-system.org/Manuals/doc/ref/chap46.html) and finitely presented groups. Same questions may be answered with different efficiency dependently on the internal representation of the group. Usually it's most efficient to deal with a permutation group or a pc group, and then use techniques that GAP provides to construct and use mapping between a group and its isomorphic copies in other internal representations. 

You may find the following GAP Jupyter notebook to be useful: "Using GAP Effectively: Some Tips and Pitfalls". It is based on @stevelinton's talk at the Second CoDiMa Training School in Computational Discrete Mathematics (ICMS, Edinburgh, 17-21 October 2016, https://www.codima.ac.uk/school2016/), and I've recently converted it to the Jupyter notebook format to use at the GAP tutorial at [PGTC 2018](http://www-groups.mcs.st-and.ac.uk/~pgtc2018/). In particular, look around "Working in the right Group" and "Finitely Presented Groups" sections and see how to use group homomorphisms. Please ask if you will have further questions.

P.S. `RequirePackage` is obsolete - please use `LoadPackage("repsn");` instead.

**Comment by JacekHoleczek** [comment]
Thank you, very much for your reply.
I tried to switch to an isomorphic group hoping that I will then get unitary generators' matrices (the "original" group returns non-unitary generators' matrices). 
It seems to me that you try to discourage me from using `IsomorphismFpGroup` (and so the crash that I reported is not really a bug).
They usually work fine, e.g.:
```
  groups := [ SmallGroup(120, 5),
              Image(IsomorphismFpGroup(SmallGroup(120, 5))) ];
```
(But I still do not get unitary matrices and it seems to me that gap has no routine which "unitarizes" representations.)

**Comment by alex-konovalov** [comment]
Yes, I don't consider this a bug - although interesting that it works for SL(2,5) but not for A5. 

Have you tried `IrreducibleRepresentationsDixon` with the "unitary" option for these groups - maybe that will help? See https://www.gap-system.org/Manuals/doc/ref/chap71_mj.html#X8493ED7A86FFCB8A for the example.

**Comment by JacekHoleczek** [comment]
Many thanks again.
Actually, repsn `IrreducibleAffordingRepresentation` returns unitary generators' matrices for the vast majority of groups that I used up to now.
I did also try `IrreducibleRepresentationsDixon` some time ago but it failed for some groups  / irreducible representations (now I don't remember which) and so I started to look for another "general purpose" solution (via isomorphisms).

**Comment by markuspf** [comment]
Well, the crux of the matter is randomisation, and in this case the `PseudoRandom` operation on finitely presented groups. The documentation for `PseudoRandom` explicitly states:

 ```
  The  default  algorithm  for  PseudoRandom  (30.7-2)  makes  little  sense for finitely
  presented or free groups, as it produces words that are extremely long.
```
One can give a radius in which the pseudo random element is chosen, but it is not clear to me how to sensibly choose this. Maybe in the knowledge that the finitely presented group is finite one can.

In your example `Random` seems to work ok (admittedly because it'll use an isomorphism to a permutation group), I managed to produce an affording representation for all characters using a hack applied to the `repsn` package. Of course this hack defeats the purpose of going to a finitely presented group.

As the documentation states, `IrreducibleRepresentationsDixon` can be quite costly, and unitary representations come at an extra cost, so depending on which groups you tried this might be out of reach for this implementation; (for A_5 it refuses to produce a unitary representation)

Maybe @ThomasBreuer has some insights?

**Comment by hulpke** [comment]
The representation produced by `IrreducibleRepresentationsDixon` can be made unitary through a further option. This potentially requires going to a larger field (as square roots need to be taken). It fails if such a field cannot be embedded into the cyclotomic numbers.

some of the algorithms choices involve random elements, so redoing the calculation might help. Changing the groups representation will not.

**Comment by JacekHoleczek** [comment]
I tried:
```
g:=SmallGroup(60, 5);
r:=IrreducibleRepresentationsDixon(g : unitary);
```
and gap 4.9.1 indeed fails with an error "cannot guarantee unitary", but gap 4.7.6 reports no error and returns representations (but I haven't checked if they are unitary now, sorry).

So, it seems to me I really need to find a procedure which takes any matrix representation returned by gap and makes it unitary afterwards (actually, I need it only for dimensions up to 3 only).

**Comment by alex-konovalov** [comment]
Yes, "unitary" option appeared in GAP after [this question](https://math.stackexchange.com/questions/1101017/how-getting-the-unitarized-irreducible-representations-with-gap). Options mechanism does not provide a way to check for non-supported options.

**Comment by fingolfin** [comment]
Closing, as I believe this request has been completely handled. If you have further issues with the repsn package, I suggest to report them at resp. ask them on the repsn issue tracker at <https://github.com/gap-packages/repsn/issues>
