### ISSUE TITLE
Converting a large rational to float unexpectedly overflows

### ISSUE THREAD

**Issue by jukkakohonen** [gap-system/gap#2734]
### Observed behaviour
The following code creates a rational number of size approximately 2.8e47, then converts it into a float. The resulting float is infinite. If the rational is converted first to integer, then to float, it gives a finite result.

[bug.zip](https://github.com/gap-system/gap/files/2313607/bug.zip)

Code:

```
w := 1874828359335503337899808492325520666779721869625836902490839559943749408538631874202906463470615316691296914794049608011593978038275224855360636423311500047372558326759773284862438360638637274727994908986389801178712170411093612945133626992418843228371154667318842716358519556774822914267332601381851895513116083/
     6617444900424221398971269536559702828526496887207031250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;

Print("Int(w)        = ", Int(w), "\n");
Print("Float(w)      = ", Float(w), "\n");
Print("Float(Int(w)) = ", Float(Int(w)), "\n");

```
Example run:

> Int(w)        = 283316051368302984470234264807186985028632077781
> Float(w)      = inf
> Float(Int(w)) = 2.83316051368303e+47

### Expected behaviour
Float(w) should be approximately 2.8e47, since w is nowhere big enough to overflow the floats. From FLOAT we see that the maximum float on this system is 1.797693134862316e+308.

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.9.2 of 04-Jul-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64
 Configuration:  gmp 6.1.0, readline
 Loading the library and packages ...
 Packages:   AClib 1.3, Alnuth 3.1.0, AtlasRep 1.5.1, AutPGrp 1.9, CRISP 1.4.4, Cryst 4.1.17, CrystCat 1.1.8, 
             CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.1, IRREDSOL 1.4, LAGUNA 3.9.0, Polenta 1.3.8, 
             Polycyclic 2.14, PrimGrp 3.3.1, RadiRoot 2.8, ResClasses 4.7.1, SmallGrp 1.3, Sophus 1.24, SpinSym 1.5, 
             TomLib 1.2.6, TransGrp 2.0.2, utils 0.54
```

**Comment by markuspf** [comment]
The reason why this overflows is because GAP separately converts the numerator and the denominator to floats, and the numerator overflows.

**Comment by markuspf** [comment]
Slightly improved algorithm; not sure whether this is numerically sensible
```
gap> Float(QuoInt(NumeratorRat(w), DenominatorRat(w))) + Float(RemInt(NumeratorRat(w), DenominatorRat(w))/DenominatorRat(w));
2.83316e+47
```

**Comment by fingolfin** [comment]
Note that the converse, converting a float to a rational, also is far from optimal:
```
gap> Rat(1./10^4);
1/10000
gap> Rat(1./10^5);
0
```

**Comment by jukkakohonen** [comment]
Thanks to markuspf's analysis on the reason, here's a much simpler example of the problem.

```
gap> a := 10^309 + 1;;
gap> b := 10^308;;
gap> Float(a/b);
inf
gap> Float(Int(a/b));
10.

```
