### ISSUE TITLE
Cayley graph

### ISSUE THREAD

**Issue by BuddhiniAnge** [gap-system/gap#2744]
Can someone please explain the result I have obtained through the below command "CayleyGraph" in GAP. Do f1,f2,... mean the vertices visited in order? So then are they elements of the group G? Can we obtain a graphical view of the Cayley graph as well? What does the SchreierVector mean?

![1](https://user-images.githubusercontent.com/42027545/44625975-f55ffb80-a931-11e8-89a1-50eb41c8d679.jpg)

Thanks a lot in advance.

**Comment by fingolfin** [comment]
Note that `CayleyGraph` is a command of the GRAPE package. It is documented in the GRAPE package manual, which you can access via `?CayleyGraph` in this case, or read online: https://www.gap-system.org/Manuals/pkg/grape/htm/CHAP002.htm#SECT007

This issue tracker is for bugs and feature requests in the GAP core system, not for general questions on how to use it, or (as in this case) on using specific GAP packages. Your questions thus are better suited for the GAP forum mailing list, or the GRAPE author (or possibly the GAP support mailing list, although I really think here the general GAP forum is a better place). Another good place to ask might be https://math.stackexchange.com
