### ISSUE TITLE
Command for Semidirect products

### ISSUE THREAD

**Issue by BuddhiniAnge** [gap-system/gap#2749]
I need to obtain the below group assigned to a variable "G1" in GAP so that I can use that group G1 as needed. How to type the command in GAP to assign this group to G1? (I took p=7 and q=3).

![image](https://user-images.githubusercontent.com/42027545/44678407-e96d5a00-aa55-11e8-913d-d6edda94ed4c.png)

I tried to use the SemidirectProduct command but when I use AutomorphismGroup command an error is coming.

Please be kind enough to tell me the necessary commands.

Thanks a lot in advance.

**Comment by alex-konovalov** [comment]
First, let me recommend several resources mentioned [here](https://math.stackexchange.com/questions/104195/what-is-the-best-way-to-self-study-gap), which are useful for the first steps in GAP, in particular, [the GAP Tutorial](http://www.gap-system.org/Manuals/doc/tut/chap0.html) and the Software Carpentry lesson ["Programming with GAP"](http://alex-konovalov.github.io/gap-lesson/).

For example, you could find information about assignments to variables [here](http://www.gap-system.org/Manuals/doc/tut/chap2.html#X82F47EA88347AC2D) and about finitely presented groups [here](http://www.gap-system.org/Manuals/doc/ref/chap47.html). 

Please note that this is an issue tracker for bug reports and feature requests in the core GAP system, and it is not our support channel. There are well-established support channels for GAP users such as [GAP Forum and GAP Support](https://www.gap-system.org/Contacts/Forum/forum.html), and also there is the [Mathematics Q&A site](https://math.stackexchange.com/questions/tagged/gap), which has the GAP tag and recommendations on asking questions on GAP [here](https://math.stackexchange.com/tags/gap/info).
