### ISSUE TITLE
Bug: representations maps an involution to an element of an infinite order.

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#276]
This is a problem of a homomorphism mapping an involution to an element of an infinite order. This may be reproduced by the following code:
```
G:=MathieuGroup(11);
chi := Filtered(Irr(G), x -> Degree(x)=10);
I := List( chi, x -> IrreducibleRepresentationsDixon(G,x));;
List( I, x -> Order(Image( x, (1,4)(2,3)(5,7)(6,11) ) ) );
```
It's hard to catch, since sometimes it runs fast, sometimes long but still returning correct results, but sometimes it concludes that a representation of degree 10 maps (1,4)(2,3)(5,7)(6,11) into a matrix of an infinite order. Below you may see this in two consecutive runs in GAP 4.7.8:
```
gap> G:=MathieuGroup(11);
Group([ (1,2,3,4,5,6,7,8,9,10,11), (3,7,11,8)(4,10,5,6) ])
gap> chi := Filtered(Irr(G), x -> Degree(x)=10);
[ Character( CharacterTable( Group([ (1,2,3,4,5,6,7,8,9,10,11), (3,7,11,8)(4,10,5,6) ]) ),
  [ 10, 2, 1, -1, 2, 0, 0, 0, -1, -1 ] ), Character( CharacterTable( Group([ (1,2,3,4,5,6,7,8,9,10,11), (3,7,11,
   8)(4,10,5,6) ]) ), [ 10, -2, 1, 1, 0, -E(8)-E(8)^3, E(8)+E(8)^3, 0, -1, -1 ] ), 
  Character( CharacterTable( Group([ (1,2,3,4,5,6,7,8,9,10,11), (3,7,11,8)(4,10,5,6) ]) ),
  [ 10, -2, 1, 1, 0, E(8)+E(8)^3, -E(8)-E(8)^3, 0, -1, -1 ] ) ]
gap> I := List( chi, x -> IrreducibleRepresentationsDixon(G,x));;
gap> List( I, x -> Order(Image( x, (1,4)(2,3)(5,7)(6,11) ) ) );
[ 2, 2, 2 ]
gap> G:=MathieuGroup(11);
Group([ (1,2,3,4,5,6,7,8,9,10,11), (3,7,11,8)(4,10,5,6) ])
gap> chi := Filtered(Irr(G), x -> Degree(x)=10);
[ Character( CharacterTable( Group([ (1,2,3,4,5,6,7,8,9,10,11), (3,7,11,8)(4,10,5,6) ]) ),
  [ 10, 2, 1, -1, 2, 0, 0, 0, -1, -1 ] ), Character( CharacterTable( Group([ (1,2,3,4,5,6,7,8,9,10,11), (3,7,11,
   8)(4,10,5,6) ]) ), [ 10, -2, 1, 1, 0, -E(8)-E(8)^3, E(8)+E(8)^3, 0, -1, -1 ] ), 
  Character( CharacterTable( Group([ (1,2,3,4,5,6,7,8,9,10,11), (3,7,11,8)(4,10,5,6) ]) ),
  [ 10, -2, 1, 1, 0, E(8)+E(8)^3, -E(8)-E(8)^3, 0, -1, -1 ] ) ]
gap> I := List( chi, x -> IrreducibleRepresentationsDixon(G,x));;
gap> List( I, x -> Order(Image( x, (1,4)(2,3)(5,7)(6,11) ) ) );
[ 2, infinity, 2 ]
```

**Comment by stevelinton** [comment]
It looks like the bug is in the Dixon's algorithm computation of the matrix representation for the character Character( CharacterTable( Group([ (1,2,3,4,5,6,7,8,9,10,11), (3,7,11,
   8)(4,10,5,6) ]) ), [ 10, -2, 1, 1, 0, -E(8)-E(8)^3, E(8)+E(8)^3, 0, -1, -1 ])

which sometimes produces matrices with very large denominators and infinite orders. The code that does the work seems to be DIxonRepGHchi in ctblgrp.gi, which is not too easy to follow without digging into the underlying papers.

**Comment by hulpke** [comment]
The following seems to be reproducible:

G:=MathieuGroup(11);
H:=Subgroup(G,[( 1, 7,10, 4, 9, 5)( 2, 6)( 3, 8,11) ]);
chi := Filtered(Irr(G), x -> Degree(x)=10);
I := List( chi, x -> DixonRepGHchi(G,H,x));;
List(I,x->List(MappingGeneratorsImages(x)[2],Order));

**Comment by alex-konovalov** [comment]
@hulpke Thanks. On 5 runs in GAP 4.7.8, your example reported infinite order 4 times and once returned a correct result (so this is still not a reliable test for bugfix.tst).

With the fix in the master branch, I've tried five times and all outputs were correct. I will cherry-pick this on the stable-4.7 branch too after the next round of tests.
