### ISSUE TITLE
Clobber warning

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#2761]
Out of curiousity, I tried compiling GAP with `-Os`. I get the following warning:

```
   C       src/read.c => obj/src/read.lo
src/read.c: In function ‘EvalRef.isra.25’:
cc1: warning: argument ‘ISRA.365’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
   LINK    gap
```

ISRA is a name gcc gives things when it makes up new functions/arguments. I can get rid of this by making the arguments to EvalRef volatile, but I can't decide if that is something we technically should be doing -- I think not, as we don't change the values of either of the arguments.

I mention this as I found it, but I think we should ignore it unless similar warnings appear with compile settings we support, on compilers we care about.

**Comment by fingolfin** [comment]
I cannot reproduce this. Which GCC version on which OS (Linux? Mac? precise version?) is this?

**Comment by ChrisJefferson** [comment]
64-bit ubuntu 18.04, gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3). I went into GNUmakefile and changed "-g -O2" to "-Os"

**Comment by fingolfin** [comment]
Does adding `const` help?

**Comment by ChrisJefferson** [comment]
Nope, it seems to be the first argument which is already const causing the problem -- gcc is expanding the struct into 3 integers (hence the weird function name), and is (I assume) not doing it wrong.

I can also reproduce this problem in gcc 8.0.1. Annoyingly, most attempts to reduce the size of the file end up hiding the warning. I'm going to try gcc bugzilla.

**Comment by ChrisJefferson** [comment]
This has been accepted as a bad warning by gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87153

I therefore suggest we just close this and ignore it.
