### ISSUE TITLE
atlasrep: POSITION_FIRST_COMPONENT_SORTED used

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2789]
The atlasrep package uses the undocumented kernel function `POSITION_FIRST_COMPONENT_SORTED`. It would be nice if that could stop. As an alternative, this code:
```gap
pos:= POSITION_FIRST_COMPONENT_SORTED( WidthUnicodeTable, ints[j] );
```
could likely be replaced with this, as done in several other packages (however, I have not tested this within altasrep):
```gap
pos:= PositionSorted( WidthUnicodeTable, [ ints[j] ] );
```

Once an atlasrep version not using this has been released, we can get rid of `PositionFirstComponent` and also this kernel function behind it.

**Comment by ThomasBreuer** [comment]
I have changed the code in my development version.

**Comment by fingolfin** [comment]
Thank you

**Comment by alex-konovalov** [comment]
The "Package issues automation moved this from Incoming to Fix released on 7 Sep" message above is incorrect. The fix is applied but not released. We should waiting for a new release of AtlasRep to close this, otherwise it falls below the radar.

**Comment by fingolfin** [comment]
The atlasrep 2.x version in GAP 4.10.2 resolved this.
