### ISSUE TITLE
Add way to query absolute path for current directory?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2794]
For a script, I wanted to temporarily change the current working directory and later restore it. I naively thought I could use record the value of `DirectoryCurrent()`, then call `ChangeDirectoryCurrent` (from the IO package), and later restore to the stored path.

But that doesn't work, because `DirectoryCurrent()`always returns the same thing: `dir("./")`.

I found no way to get the CWD, in particular no calls to `getwd` or `getcwd` in GAP or IO (well, GAP now has one in the internal function `find_yourself`, but that's not helpful).

There is `GAPInfo.SystemEnvironment.PWD`, but that isn't updated if `ChangeDirectoryCurrent` is called, so it's only helpful if no code before mine changed the CWD.

For now, I'll resort to using `Process` to executed `pwd` in a shell. But I really think we should add something here that does this in a more straightforward way.

BTW, I also noticed that @ChrisJefferson back in 2015 changed `io` to only defined `ChangeDirectoryCurrent` if it wasn't defined already -- my guess is in order to add this function to the GAP library. But that hasn't happened, has it?

**Comment by fingolfin** [comment]
I just released IO 4.5.4 which adds `IO_getcwd`. But I still think GAP should have something like this builtin.

**Comment by dimpase** [comment]
By the way, how does one extract `"foo"` from these `dir("foo")` created by `DirectoryCurrent()` and many other similar functions, e.g. `DirectoriesPackagePrograms(...)`  ? 

It's not documented, or at least beyond my ability to find this in GAP docs.
