### ISSUE TITLE
Look into using coveralls in addition to Codecov

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2811]
Recently, Codecov has started to experience more and more problems: viewing coverage reports for pull requests has been broken for several weeks now (they have been notified about it). Right now, processing coverage reports is completely broken (support tells me they are "aware" and have " 'all hands on deck' working to resolve this as soon as possible"). Many small (and not so small) issues I reported to them in the past months were never addressed.

While I really like Codecov (at least when it is working), and I do hope they'll recover, I still think we should look into alternatives. The only one I know that seems close in abilities to Codecov is https://coveralls.io

I think it would be highly useful to set this up *in parallel* to Codecov. The Julia folks are doing this, too.

For this, we need to convert the `profiling` output to their JSON format, which looks pretty simple to me; see https://docs.coveralls.io/api-introduction for details.

Then, of course, one has to integrate this all with our Travis & AppVeyor setup. This shouldn't be too hard, either, but of course it still requires somebody to actually invest the work...

Once we have this running for GAP itself, we could also look into adding this to our standard scripts for Travis&Codecov support for GAP packages.

**Comment by fingolfin** [comment]
The JSON format for this is trivial, see https://docs.coveralls.io/api-introduction

They recommend this for uploading C/C++ coverage: https://github.com/eddyxu/cpp-coveralls. That's a simple Python tool. I guess I'd just take it, modify it to also recognize and upload GAP data, and then use that.

**Comment by markuspf** [comment]
There is now a PR to the profiling package (https://github.com/gap-packages/profiling/pull/61) that adds support for coverage output in the coveralls format.

**Comment by fingolfin** [comment]
Initial work on this was done in PR #3133 (merged); more work is needed, see PR #3138

**Comment by alex-konovalov** [comment]
@fingolfin #3138 merged too - can this be closed then?
