### ISSUE TITLE
Log2Int(-(2^60)) = -1

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#282]
As in description, seems to just be this one value which is wrong. Assume it's an issue with small/large int crossover. Going to have a look.

**Comment by markuspf** [comment]
Looks like `-(2^60)` is stored as a INTOBJ instead of a GMP integer.

**Comment by ChrisJefferson** [comment]
Yup. I'm fairly sure that is the intention (looking around at the code), although it's a bit unclear (I can make a GMP integer of value -(2^60) if I want to, by using hexstring. Should that be allowed?)

**Comment by ChrisJefferson** [comment]
The fix is fairly simple, on line 634-635 of gmpints.c, we need to consider from NR_SMALL_INT_BITS, not NR_SMALL_INT_BITS-1

**Comment by markuspf** [comment]
Then we'd be using 61 bits for integers though wouldn't we? 2^60 uses 61 bits, as does -2^60, within 60 bits they both look the same, they're both 0.

**Comment by frankluebeck** [comment]
It is correct that the integers in `IsSmallIntRep` are those in the interval -2^60..2^60-1 on 64bit systems
and in the interval -2^28..2^28-1 on 32bit systems. 

The fix is to change both, line 633 of `src/gmpints.c` and line 533 of `src/integer.c`  to
        for(res = NR_SMALL_INT_BITS, mask = (Int)1 << (NR_SMALL_INT_BITS);

**Comment by markuspf** [comment]
I got confused by the constant name `NR_SMALL_INT_BITS` then and assumed GAP would be using 60 bits for IsSmallIntRep.
It's perfectly sensible to specify the range to be `-2^60..2^60-1`, although I could not find this documented anywhere (yet).
