### ISSUE TITLE
Cleaning up temp directories after a Fork

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#2827]
I'm not sure if the IO package, or GAP, should be fixing this (and exactly what the fix should be..), but I'm registering the problem here.

Consider the following code:

```
t := DirectoryTemporary();
IO_fork();
QUIT_GAP(0);
```

This produces the error `Error, dirname must be a directory`. This appears because the first GAP to exit cleans up the temporary directory, and therefore the second GAP to exit finds the directory already missing. This is coming up when running tests for the profiling package.

I'm not sure of the best fix -- one would have to consider desired semantics. One option would be to just clarify the warning, to something like "Temporary directory <name> already removed", which would at least help understand what has gone wrong. We could also hide the error message if a temporary directory is already cleaned up.

**Comment by stevelinton** [comment]
I think it would be sensible for the automatic cleanup when GAP exits to tolerate temporary directories being already deleted (or at the most to give a warning). One could also imagine user code assiduously deleting them, which is not an unreasonable thing to do.

**Comment by ChrisJefferson** [comment]
I've addressed this in #2856 , which handles directories being deleted, but does print a message out that we skipped over the directory. At the same time I tidied up AtExit, which (I feel) ran handlers in a weird order.

**Comment by fingolfin** [comment]
@ChrisJefferson so, is this resolved then? The PR did not contain a "Resolves #XYZ"

**Comment by ChrisJefferson** [comment]
I think the fix is "good enough", and no-one seems too upset by the problem, so let's say it's resolved :)
