### ISSUE TITLE
Add `ChangeDirectoryCurrent` to GAP

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2831]
Back in November 2015, @ChrisJefferson made `ChangeDirectoryCurrent` conditionally defined in `io`. IIRC the idea was that this way, we could eventually add it to GAP itself.

Let's do that?

**Comment by alex-konovalov** [comment]
Yes! The same was suggested in #364.

**Comment by fingolfin** [comment]
Duplicate of #364
