### ISSUE TITLE
loading workspaces doesn't work with `--nointeract` option

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#2832]
Please use the following template to submit an issue
(you may delete lines which are not used). Thank You!

### Observed behaviour

`gap --nointeract -L foo.ws`
still gives a prompt

### Expected behaviour

It should not. More precisely, an executable linking libgap should be able to 
load a saved workspace and keep going after this. This also does not work ATM.

This is with `GAP 4.10dev-1163-g94ead70-dirty of today`

**Comment by dimpase** [comment]
Note that #2833 presently is broken due to the current issue, at least according to @fingolfin and @markuspf

**Comment by ChrisJefferson** [comment]
I suspect the `SESSION` at session.g:73 needs to be wrapped in `if not GAPInfo.CommandLineOptions.norepl then` like init.g:1045.

**Comment by dimpase** [comment]
A fix that work for libgap, as well, won't touch `*.g` files, IMHO.

**Comment by ChrisJefferson** [comment]
I'm not clear what the problem is for libgap, and how libgap loads workspaces and then runs GAP. If you don't want GAP to run the repl, you have to tell it not to run the repl.

**Comment by dimpase** [comment]
It's apparently at the level of `argv` parsing for (lib)gap; if I run the corresponding test from #2833 without `-q --nointeract` I do see that otherwise everything seems to work:
```
$ ./test-libgapwsload   -A -l . -m 32m -T   -L /tmp/libgap.ws
# Initializing GAP...
 ┌───────┐   GAP 4.10dev-1164-geb4850f-dirty of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64
 Configuration:  gmp 6.1.2, readline
 Loaded workspace: /tmp/libgap.ws
 Packages:   GAPDoc 1.6.1, PrimGrp 3.3.1, SmallGrp 1.3, TransGrp 2.0.4
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> h;
<fp group on the generators [ f1, f2 ]>
gap> 
```

**Comment by dimpase** [comment]
#2840 works for me with the test from #2833.
