### ISSUE TITLE
CollectBags should have an option to pad collected bags

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#2837]
At present `CollectBags` frees the corresponding memory, but there is no way to ask it to pad (or at least zero out) the memory it has freed.

Such an option would be useful for debugging purposes (without it it's hard to see whether a bag has been protected or not).

**Comment by dimpase** [comment]
@rbehrends says that this is currently not implemented.

**Comment by ChrisJefferson** [comment]
`--enable-valgrind` adds padding to GASMAN, and also makes the appropriate calls to make GAP work with valgrind (by marking the padding as innaccessible for valgrind). That isn't documented however.

Also GASMAN always zeros out it has freed (unless there is a bug somewhere). However, as GASMAN compresses, there is a good chance the memory where a dead bag lived now has a different bag moved into it.

**Comment by fingolfin** [comment]
I am not sure what @rbehrends meant with this not currently being implemented; see what @ChrisJefferson wrote.

What is the actual problem you want to resolve? What do you mean with a "protected" bag?

**Comment by dimpase** [comment]
After some discussion with @rbehrends, it appears that it's not possible to deterministically  force collection of an object. This makes the issue largely moot --- I wanted to test that something is collected depending upon `MARK_BAG` is called on the object, or not. But this looks hard.

**Comment by ChrisJefferson** [comment]
Not sure exactly what your use case is -- at the c level straight after calling collect you can see if the master plumber is free. At gap level, out object into a weak pointer list, if it disappears it was GCed.

**Comment by fingolfin** [comment]
@dimpase I hope the weak pointer (wpobj) suggeston by @ChrisJefferson is helpful for you.

Closing this as wontfix.
