### ISSUE TITLE
Add `IsPackageLoaded`

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#2842]
On several occasions, either myself or others I talked to had need for a `IsPackageLoaded(pkgname)` command. Let's add it.

**Comment by alex-konovalov** [comment]
Caveat: see examples of errors in Windows in https://github.com/gap-system/gap/issues/1820 when for some packages a break loop occurs during their loading, and then after exiting from the break loop, calling `LoadPackage` again returns `true`, although these packages are clearly broken.

**Comment by fingolfin** [comment]
Of course if a package errors out in the middle of loading, it can end up in an inconsistent state. But then also `LoadPackage` will "incorrectly" (?) report the package as loaded. So, while this may be something that could be improved, it seems to me like a separate issue.

`IsPackageLoaded` simply would perform the same check as `LoadPackage`, but it would never proceed to actually load a package. Any improvements that are made to `LoadPackage` to detect "broken" or "incompletely loaded" packages of course should then also be applied to `IsPackageLoaded`.
