### ISSUE TITLE
new format for OPERATIONS - how to get corresponding flag lists?

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#2875]
The old format of OPERATIONS consisted of the list of even length, with for each k the
(2k-1)-entry an Operation/Attribute/Property, and 2k-th entry the list of the shape
`[ [ flag list], ...]`. (This was still there in GAP 4.8.8).
And so it was possible for an object `x` to compare a "flag list" with the output of `FlagsType(TypeObj(x))` and decide whether the OPERATION[2k-1] is applicable to `x`.
This is used in Sagemath interface to GAP [here, in a GAP function](https://github.com/sagemath/sage/blob/b84538eeeab812319359fb14404c462abf46b2f1/src/ext/gap/sage.g#L64)

In 4.10 the "flag lists" are gone. How does one get them now?

**Comment by markuspf** [comment]
The list `OPERATIONS` contains only operations, `GET_OPER_FLAGS` gives you the flags for an operation.

Since both are all-caps they're supposed to be "internal use only", so I would want to maybe think about making a slightly friendlier API for them (in particular the function you mention might be useful for completion functions in jupyter and other places.)

**Comment by dimpase** [comment]
Yes, absolutely, this is for (tab) completions, and more generally, operation discovery on GAP and libgap objects in Sagemath - any other application needing this functionality will benefit from an appropriate API.

**Comment by markuspf** [comment]
Note though that completion in GAP works differently from sage: In GAP methods for operations are selected based on the types of all inputs, and you type the operation's name first, so I think tab-completion in GAP would select an *object*.

Even with a binary operation, say `Normaliser` you get the following (how does sage even handle this?):

```
gap> G := AlternatingGroup(5);;
gap> U := Group((1,2,3));;
gap> Normaliser(G,U);
Group([ (1,2,3), (2,3)(4,5) ])
```

With how I understand the tab-completion in sage one'd want to type `G.<tab>` and get `Normaliser`?

**Comment by dimpase** [comment]
Yes, that's what Sage  means under tab completion. 

Essentially, Sage is co-opting all the methods discovered into the class in question, so one can e.g. do
```
sage: G=libgap.AlternatingGroup(5)
sage: U=G.Subgroup([G.GeneratorsOfDomain()[1]])
sage: N=G.<tab>
...
Normalizer
...
sage: N=G.Normalizer(U)
sage: print(U,N)
(Group( [ (3,4,5) ] ), Group( [ (3,4,5), (1,2)(4,5) ] ))
```
Here `Normalizer` etc is in a menu that pops up if you hit `<tab>` after typing `G.`

Note that this mimics a normal modern Python behaviour (used to be an extension in Python2) with usual Python objects:
```
$ python
Python 3.7.0 (default, Sep  6 2018, 23:41:04) 
>>> l=[1,2,3]
>>> l.<tab>
l.append(   l.count(    l.insert(   l.reverse(  
l.clear(    l.extend(   l.pop(      l.sort(     
l.copy(     l.index(    l.remove(   
>>> l.
```
----

Potentially, one could perhaps have a command-line (or graphic) UI that takes into account types of `G` and `U` and pops up a list of methods to call on `(G,U)` - I never saw anything of this sort, though.

**Comment by fingolfin** [comment]
As far as I can tell, @markuspf answered this question already. Any reason to leave it open? If so, please amend the issue title and description; if not, please close.

**Comment by dimpase** [comment]
As you see, my latest comment is an answer to Markus' question. So this is more of a dialog.

**Comment by fingolfin** [comment]
But a dialog that stopped 28 days ago... There seems to be no clear aim here, and so I don't see how this belongs on the issue tracker. If you'd like to request a feature or report a bug, please state so; otherwise, I'll close this.

**Comment by dimpase** [comment]
no problem at all.
