### ISSUE TITLE
Unresolved reference: "IsBound" for a list position

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#289]
`<Ref Func="IsBound" Label="for a list position"/>` can not be resolved from several places in the manual:
```
#I  #W WARNING: non resolved reference: rec(
  Func := "IsBound",
  Label := "for a list position" )

#I  #I Producing simplified search strings and labels for hyperlinks . . .

#I  #I Constructing LaTeX version and calling pdflatex:

#I  #I Writing LaTeX file, 
#I  3 x pdflatex with bibtex and makeindex, 
#I  
#W There were LaTeX Warnings:

#I  LaTeX Warning: Reference `IsBound:for a list position' on page 251 undefined on

#I   input line 14242.
```

**Comment by ChrisJefferson** [comment]
Is this a long-standing bug, or something recently broken?

**Comment by alex-konovalov** [comment]
First time appeared in the weekly release candidate build from the master branch on September 6th. The build on August 30th was OK. This is not something what is detected automatically...

**Comment by alex-konovalov** [comment]
Fixed in https://github.com/gap-system/gap/commit/4feb9a8e79d1f3a8ce0422d613106f9ca0eecff5
