### ISSUE TITLE
GAP code coverage broken by fork()

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#2906]
If `IO_fork` is used while `--cover` or `--profile` is active, the resulting profiles are sometimes corrupt. This leads to the `io` packages' coverage to look even worse than it is.

**Comment by fingolfin** [comment]
@ChrisJefferson has been working on this

**Comment by fingolfin** [comment]
Personally, I don't see a need to backport this, but if somebody wants to argue for it, go ahead!

In the meantime, this can then be closed. For the record, I believe PRs #2908 and #2914 are relevant.
