### ISSUE TITLE
Segfault when running `tst/testinstall/kernel/streams.tst`

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#2925]
I am experiencing the following segfault when running `tst/testinstall/kernel/streams.tst` from the GAP master branch.
```
$ bin/gap.sh -A -r
 ┌───────┐   GAP 4.10dev-1307-g0bd0966 of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin17.7.0-default64-kv6
 Configuration:  gmp 6.1.2, GASMAN
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.1.dev, PrimGrp 3.3.1, SmallGrp 1.3, TransGrp 2.0.4
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> Test("tst/testinstall/kernel/streams.tst");
# line 27 of 143 (18%)Segmentation fault: 11
```
I can try to provide more information if this is not immediately reproducible by others.

**Comment by alex-konovalov** [comment]
This is happening neither in https://travis-ci.org/gap-system/gap-docker-master-testsuite (Ubuntu bionic docker container) nor in Jenkins nodes in St Andrews (macOS and Scientific Linux). Just in case, did rebuild GAP after most recent pull?

**Comment by wilfwilson** [comment]
Yes, I rebuilt completely, and this is running without packages as shown. This also occurs in the Travis setup for the Semigroups package. See for instance the end of this log: https://travis-ci.org/wilfwilson/Semigroups/jobs/442356846

Although the words `Segmentation fault` are not printed to the screen on that Travis link, GAP is clearly crashing when `streams.tst` is being run, which is what is causing the Travis job to fail.

**Comment by ChrisJefferson** [comment]
I can reproduce this on my laptop.

**Comment by alex-konovalov** [comment]
Retracting my earlier comment. Rebuild and checked on my laptop and waited for some nightly Jenkins builds to complete - yes, this is  actually very reproducible.

**Comment by ChrisJefferson** [comment]
So the problem is @fingolfin 's changes to `FuncREAD_NORECOVERY`. The function now assumes if it is given something which is not StringConv, then it must be a stream. You can reproduce the failure with something like:  `READ_NORECOVERY(fail);`.
