### ISSUE TITLE
Unbound global variable warning marked incorrectly

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#2958]
The `Unbound global variable` syntax warning always marks the token after the unbound variable, for example:

```
gap> f := function() for abc in [1..5] do od; end;
Syntax warning: Unbound global variable
f := function() for abc in [1..5] do od; end;
                        ^^
function(  ) ... end
gap> f := function() while def do od; end;
Syntax warning: Unbound global variable
f := function() while def do od; end;
                          ^^
function(  ) ... end
gap> f := function() def := 4; end;
Syntax warning: Unbound global variable
f := function() def := 4; end;
                    ^^
function(  ) ... end
```

I strongly suspect this is because we don't know if something is an unbound global variable until we've looked at the next token to see if it is the start of a lambda function.

**Comment by fingolfin** [comment]
Indeed, that seems like the most likely explanation. Fixing this could be done by recording the position of the previous token(s), I guess, and then somehow expressing that the "underlining" should happen for that.

**Comment by fingolfin** [comment]
@ChrisJefferson fixed this some time ago in a PR I can't be bothered to dig up :-)
