### ISSUE TITLE
BuildPackages doesn't report PolymakeInterface build failure

### ISSUE THREAD

**Issue by RussWoodroofe** [gap-system/gap#2971]
In the prerelease of GAP 4.10.0, I ran BuildPackages.sh.  As I don't have Polymake, PolymakeInterface failed to build (as expected).  

But after the build, PolymakeInterface wasn't in log/fail.log.  Probably it should've been?

The output from building PolymakeInterface follows.

==== Checking PolymakeInterface-2018.09.25
Running './configure' '/Users/russw/Documents/Programming/CocoaGap/gap' 
./configure: line 23: polymake-config: command not found
./configure: line 25: polymake-config: command not found
./configure: line 27: polymake-config: command not found
./configure: line 29: polymake-config: command not found
./configure: line 31: polymake-config: command not found
Running 'make' 
mkdir -p bin/x86_64-apple-darwin16.7.0-default64
cp /Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/config.h bin/x86_64-apple-darwin16.7.0-default64/
fPIC -Wall -O0 -g -pipe -m64 -o bin/x86_64-apple-darwin16.7.0-default64/polymake_fktn.o -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/extern/gmp/include -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/../.. -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64 -DCONFIG_H -c src/polymake_fktn.cpp	
make: fPIC: No such file or directory
make: [bin/x86_64-apple-darwin16.7.0-default64/polymake_fktn.o] Error 1 (ignored)
cp /Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/config.h bin/x86_64-apple-darwin16.7.0-default64/
fPIC -Wall -O0 -g -pipe -m64 -o bin/x86_64-apple-darwin16.7.0-default64/polymake_main.o -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/extern/gmp/include -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/../.. -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64 -DCONFIG_H -c src/polymake_main.cpp
make: fPIC: No such file or directory
cp /Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/config.h bin/x86_64-apple-darwin16.7.0-default64/
make: [bin/x86_64-apple-darwin16.7.0-default64/polymake_main.o] Error 1 (ignored)
fPIC -Wall -O0 -g -pipe -m64 -o bin/x86_64-apple-darwin16.7.0-default64/polymake_polytopes.o -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/extern/gmp/include -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/../.. -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64 -DCONFIG_H -c src/polymake_polytopes.cpp
make: fPIC: No such file or directory
cp /Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/config.h bin/x86_64-apple-darwin16.7.0-default64/
make: [bin/x86_64-apple-darwin16.7.0-default64/polymake_polytopes.o] Error 1 (ignored)
fPIC -Wall -O0 -g -pipe -m64 -o bin/x86_64-apple-darwin16.7.0-default64/polymake_cone.o -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/extern/gmp/include -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/../.. -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64 -DCONFIG_H -c src/polymake_cone.cpp	
make: fPIC: No such file or directory
cp /Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/config.h bin/x86_64-apple-darwin16.7.0-default64/
make: [bin/x86_64-apple-darwin16.7.0-default64/polymake_cone.o] Error 1 (ignored)
fPIC -Wall -O0 -g -pipe -m64 -o bin/x86_64-apple-darwin16.7.0-default64/polymake_fan.o -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/extern/gmp/include -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/../.. -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64 -DCONFIG_H -c src/polymake_fan.cpp	
make: fPIC: No such file or directory
cp /Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/config.h bin/x86_64-apple-darwin16.7.0-default64/
make: [bin/x86_64-apple-darwin16.7.0-default64/polymake_fan.o] Error 1 (ignored)
fPIC -Wall -O0 -g -pipe -m64 -o bin/x86_64-apple-darwin16.7.0-default64/polymake_data.o -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/extern/gmp/include -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/../.. -I/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64 -DCONFIG_H -c src/polymake_data.cpp	
make: fPIC: No such file or directory
fPIC -Wall -O0 -g -shared -dynamiclib -undefined dynamic_lookup -m64 -o bin/x86_64-apple-darwin16.7.0-default64/polymake_main.so bin/x86_64-apple-darwin16.7.0-default64/polymake_main.o bin/x86_64-apple-darwin16.7.0-default64/polymake_fktn.o bin/x86_64-apple-darwin16.7.0-default64/polymake_polytopes.o bin/x86_64-apple-darwin16.7.0-default64/polymake_cone.o bin/x86_64-apple-darwin16.7.0-default64/polymake_fan.o bin/x86_64-apple-darwin16.7.0-default64/polymake_data.o  -L/Users/russw/Documents/Programming/CocoaGap/gap/bin/x86_64-apple-darwin16.7.0-default64/extern/gmp/lib -lgmp
make: [bin/x86_64-apple-darwin16.7.0-default64/polymake_data.o] Error 1 (ignored)
make: fPIC: No such file or directory
make: [bin/x86_64-apple-darwin16.7.0-default64/polymake_main.so] Error 1 (ignored)

Tue Nov  6 17:51:42 CST 2018

**Comment by fingolfin** [comment]
This is a bug (or rather: multiple bugs) in the build system of the `PolymakeInterface` package, and should be reported to its maintainers (pinging @sebasguts )

I identify at at least the following problems:

1. it's `configure` script lacks `set -e` and hence does not abort with a  non-zero exit code upon unexpected errors
2. the `configure` script does not properly check if `polymake-config` exists and is executable (it should detect that this is not the case, and exit with a helpful error message a non-zero exit code)
3. The `Makefile` that is now generated is invalid, and while it errors, that error is not correctly propagated, so it also exits with exit code zero.

Hence, GAP has no good way to detect a failure (scrapping output of a build system is *not* a good way).

**Comment by fingolfin** [comment]
The polymake repos is the wrong place for reporting this, too; PolymakeInterface is a project of its own (and a subproject of the homalg project). I'd hope its PackageInfo.g or README give a hint on how/where to report issues (but have not checked, am typing on a phone right now)

**Comment by RussWoodroofe** [comment]
Found it!  I knew the difference between Polymake and PolymakeInterface.  If you go to the subpage for PolymakeInterface, then issues are turned off there, and the link with homalg wasn't immediately apparent to me.  Opened an issue there.

**Comment by fingolfin** [comment]
Could you clarify to what "subpage for PolymakeInterface" you refer here? I.e., which URL?

**Comment by RussWoodroofe** [comment]
I see.  I think I was looking at the private repository of @sebasguts.  That's the number one hit if you google "PolymakeInterface github" (and also the number 2nd, 3rd, 4th hits, at least for me).  
https://github.com/sebasguts/PolymakeInterface

Perhaps there should be a link from there to homalg.

**Comment by alex-konovalov** [comment]
@sebasguts really need to archive that one and maybe some more inactive repositories...
