### ISSUE TITLE
Segfault on autocomplete with colored-completion-prefix turned on in Bash

### ISSUE THREAD

**Issue by zickgraf** [gap-system/gap#2982]
### Steps to reproduce

1. Install Bash 4.4 (tested versions: 4.4.18 and 4.4.23)
2. Put the line `set colored-completion-prefix on` in ~/.inputrc
3. Open a (new!) terminal and start GAP by typing `gap`
4. Type the single letter `A` and press tab twice

### Observed behaviour
GAP crashes with a segmentation fault

### Expected behaviour
GAP displays a list of commands starting with `A`

### Copy and paste GAP banner (to tell us about your setup)
 ┌───────┐   GAP 4.10.0 of 01-Nov-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64
 Configuration:  gmp 6.1.2, readline
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.2.dev, IO 4.5.4, PrimGrp 3.3.2, SmallGrp 1.3, TransGrp 2.0.4
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'

### Notes
1. I have tested this on Arch Linux with GAP 4.9.3 and 4.10 and on Debian Testing with GAP 4.9.3
2. The segfault also occurs for inputs longer than one letter, e.g. for `Ad`
3. Sometimes autocomplete works on the first try but segfaults on further tries. E.g. in the following sequence the first two completions work but the third segfaults: `el<TAB><TAB><BACKSPACE><BACKSPACE>el<TAB><TAB><BACKSPACE><BACKSPACE>el<TAB><TAB>`
4. systemd-coredump displays the following:
```
Process 9880 (gap) of user 1000 dumped core.
                                                  
Stack trace of thread 9879:
#0  0x00007fc136acc715 n/a (n/a)
```

**Comment by ChrisJefferson** [comment]
I have made a PR ( #2986 ) which fixes the crash, but it doesn't really make this option work. I'm having to guess how to fix it as there doesn't seem to be any documentation I can find for what the first element of the first argument of the readline function we use ( rl_display_match_list ) should be.

**Comment by markuspf** [comment]
Note that this issue has been fixed in https://github.com/gap-system/gap/pull/2991.

**Comment by zickgraf** [comment]
I have recompiled GAP from the master branch and confirm that the segfault is gone, thanks for the quick fix!

What is the policy on closing issues, shall I close it or should it stay open until the fix is released?

**Comment by ChrisJefferson** [comment]
Thanks, I should have closed the issue when the PR was merged, so I'll close it now :)
