### ISSUE TITLE
Rare assertion error in sanity.g in stable-4.10 branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#2990]
Happened this morning in https://gap-ci.cs.st-andrews.ac.uk/job/GAP-stable-sanity/GAPCOPTS=64build,label=kovacs/9/display/redirect (link only accessible from St Andrews):
```
testing group t20n968
conjugacy classes
rational classes
automorphism group
testing group Group( [ f1, f2, f3, f4, f5, f6, f7 ] )
subgroups
normal subgroups
conjugacy classes
rational classes
automorphism group
20,968,192,133
testing group t20n969
conjugacy classes
Error, Assertion failure in
 Assert( 2, Sum( clout, function ( i )
         return Index( F, i[2] );
     end ) = Size( F ) - Size( M ) 
); at /circa/scratch/gap-jenkins/workspace/GAP-stable-sanity/GAPCOPTS/64build\
/label/kovacs/GAP-stable-snapshot/lib/clashom.gi:1050 called from 
Build step 'Execute shell' marked build as failure
```
Logged into the build workspace, started GAP with default packages and tried this:
```
Read("tst/sanity.g");
for i in [1..100] do Print(i,"\n");TestsForGroup(TransitiveGroup(20,969));od;
```
and got the same at 77th iteration:
```
76
testing group t20n969
conjugacy classes
rational classes
automorphism group
77
testing group t20n969
conjugacy classes
Error, Assertion failure in
  Assert( 2, Sum( clout, function ( i )
          return Index( F, i[2] );
      end ) = Size( F ) - Size( M ) 
 ); at /circa/scratch/gap-jenkins/workspace/GAP-stable-sanity/GAPCOPTS/64build/label/kovacs/GAP-stab\
le-snapshot/lib/clashom.gi:1050 called from 
ConjugacyClassesSubwreath( F, FM, n, S1, Action( FM, components[1] ), T1, components, emb, proj 
 ) at /circa/scratch/gap-jenkins/workspace/GAP-stable-sanity/GAPCOPTS/64build/label/kovacs/GAP-stabl\
e-snapshot/lib/clashom.gi:1339 called from
ConjugacyClassesFittingFreeGroup( G 
 ) at /circa/scratch/gap-jenkins/workspace/GAP-stable-sanity/GAPCOPTS/64build/label/kovacs/GAP-stabl\
e-snapshot/lib/clashom.gi:2363 called from
ConjugacyClassesViaRadical( G 
 ) at /circa/scratch/gap-jenkins/workspace/GAP-stable-sanity/GAPCOPTS/64build/label/kovacs/GAP-stabl\
e-snapshot/lib/clashom.gi:3071 called from
ConjugacyClasses( G ) at tst/sanity.g:61 called from
TestsForGroup( TransitiveGroup( 20, 969 ) ); at *stdin*:4 called from
...  at *stdin*:4
you may 'return;'
brk>
```

**Comment by hulpke** [comment]
From experiments (the error goes away if not autoloading packages, or if turning the print level higher) I strongly suspect it to be an issue of objects being slightly corrupted or not properly zeroed out in some kernel function.

**Comment by ChrisJefferson** [comment]
Oh black, I hoped it might not be fixed by increasing the print level. I hoped it was a random number issue.

I will try running with a over the weekend and see if I can find anything. If anyone can make it happen faster, great!

**Comment by alex-konovalov** [comment]
@ChrisJefferson You don't need to run the whole sanity.g. 
```
Read("tst/sanity.g");
for i in [1..100] do Print(i,"\n");TestsForGroup(TransitiveGroup(20,969));od;
```
did not take long for me to get to the break loop.

**Comment by ChrisJefferson** [comment]
@alex-konovalov : Running GAP with every debug option turned on slows things down by thousands of times, so it will still take a while to hit that problem! However hopefully the bad behaviour is being executed on every loop of the test.

**Comment by ChrisJefferson** [comment]
Found it (or, found something). Will investigate and report back.

**Comment by ChrisJefferson** [comment]
@hulpke : You had a good instinct, it was something writing past the end of a Bag.

**Comment by hulpke** [comment]
@ChrisJefferson Wow, how did you find this so quickly? 
(It had to be a memory issue -- I think I ran exactly the same input after some other runs and the error status flipped.)

**Comment by markuspf** [comment]
@ChrisJefferson added valgrind support (and all kinds of other memory debugging magic) to GAP a while ago to debug exactly this kind of issue. He ran the test with it enabled, which slows it down considerably, but detects things such as writing past the end of bags.
