### ISSUE TITLE
build: gac is unusable due to silly paths

### ISSUE THREAD

**Issue by jengelh** [gap-system/gap#3001]
### Observed behaviour
```
$ unzip gap-4.10.0-core.zip
$ cd gap-4.10.0/
$ ./configure --prefix=/usr && make && make install
$ cd ../
$ rm -rf gap-4.10.0
$ gac
gac: line 73: /home/abuild/rpmbuild/BUILD/gap-4.10.0/sysinfo.gap: No such file or directory
$ grep BUILD /usr/bin/gac
abs_top_builddir="/home/abuild/rpmbuild/BUILD/gap-4.10.0"
abs_top_srcdir="/home/abuild/rpmbuild/BUILD/gap-4.10.0"
```

### Expected behaviour
Don't encode the build-time paths!

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.10.0 of 01-Nov-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-suse-linux-gnu-default64
 Configuration:  gmp 6.1.2, readline
```
(It's the gap package in and from openSUSE in-the-making; https://build.opensuse.org/package/show/science/gap )

**Comment by fingolfin** [comment]
Invalid for the same reasons as issue #3003

**Comment by jengelh** [comment]
Would it be ok to submit a PR that fixes installation and, similar to how extern/gmp and extern/zlib is built, requires the use of `make install`?

**Comment by ChrisJefferson** [comment]
@jengelh : It would be good to have a working `make install`, but making a working `make install` has been a long, and ongoing process and we couldn't accept anything which made things worse -- in particular GAP and all it's packages would have to continue to work with no changes in behaviour, or what they have to run, for users who don't care about `make install`.

**Comment by fingolfin** [comment]
If you are seriously interested in working on a full blown `make install`, we'd certainly be interested in your contributions. However, completing this is a major task, and likely will require changes to packages as well; and until it is completely implemented, I would still want to disable it, because people would still use it, and overlook any warnings. We could, however, expose an incomplete implementation under a target name like `broken-incomplete-install-use-at-your-own-peril`. That way, anybody using it will known that we are aware it is incomplete...

**Comment by jengelh** [comment]
The thing is, the gac program will need to work from both the just-built source tree as well as when installed because of hardcoded paths:
```
gap_compiler="${abs_top_builddir}/gap"
```
The way it's now, it won't work when installed; conversely, changing it to `@bindir@/gap` will make it work when installed yet not when in the source tree. Since installing is just an organized copy operation that does not require special permissions (one can always `./configure --prefix=$HOME`), that seems like an acceptable way out.
Else, gac.in would have to become a terrible pattern file with lots of `@placeholders@` and be transformed twice just to make it runnable from its builddir :-/
