### ISSUE TITLE
Coverage reporting for GAP code broken

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3019]
At some point very recently, coverage reported by codecov went up from 83.8 to 85.2 % simply because it stopped reporting anything on GAP coverage. It now only shows coverage for files in src.

Perhaps one of my recent changes to the travis / ci setup are to blame; or perhaps this is an issue with the profiling package. Perhaps @ChrisJefferson or @alex-konovalov have any insights?

**Comment by alex-konovalov** [comment]
Last release of profiling is 2.0.1, it has been included in all three releases since GAP 4.9.2. So I'd start debugging from recent changes to the travis / ci setup first.

**Comment by markuspf** [comment]
It's the `--nointeract` switch in `ci-gather-coverage.sh`I'll submit a PR
