### ISSUE TITLE
HPC-GAP/factint/travis interactions

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#3025]
Please use the following template to submit an issue
(you may delete lines which are not used). Thank You!

### Observed behaviour
Travis tests fail for #2997. Specifically the HPCGAP test `tst/testinstall/hpc/tasks.tst`

The problem is seen in 
```
gap> t := RunTask( Factors, Integers, 65537^2-1);
gap> TaskError(t);
"Error, Attempt to read object 4874949504 of type list (plain,empty) without having read access"
```

It can be avoided by running HPC-GAP with `-A` presumably because this suppresses `factint`

It seems that `factint` uses lots of caches and similar arrangements without any precautions for multi-threading.

### Expected behaviour

This test should pass if the core system is correct.

I suggest not loading `factint` for HPC-GAP tests, since it is (a) used automatically by the library and (b) contains functions that cannot be run in a background thread.

**Comment by fingolfin** [comment]
A simple way to not load factint in the HPC-GAP test would be to edit `etc/ci-prepare.sh` and insert something like
```sh
if [[ $HPCGAP = yes ]]
then
  rm -rf $SRCDIR/pkg/FactInt*
fi
```
near or at the end.
