### ISSUE TITLE
Compilation problem with 4.10

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#3026]
### Observed behaviour

when compiling I get an error

    C       src/read.c => obj/src/read.lo
    src/read.c: In function ‘ReadVar’:
    src/read.c:619: error: unknown field ‘var’ specified in initializer
    src/read.c:619: warning: missing braces around initializer
    src/read.c:619: warning: (near initialization for ‘ref.<anonymous>’)
    src/read.c:619: error: unknown field ‘nest0’ specified in initializer
    At top level:
    cc1: warning: unrecognized command line option "-Wno-cast-function-type"
    cc1: warning: unrecognized command line option "-Wno-implicit-fallthrough"

### Expected behaviour

GAP should compile. (I can hack around it, but others might not be able to) 

### Copy and paste GAP banner (to tell us about your setup)

gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC)

(This is a system with lots of memory I have access to but no root access. For stability reasons it is still using an older RedHat, so "update the compiler" is not an option for me)

**Comment by fingolfin** [comment]
This sounds like a compiler bug, but one that we should be able to work around. Could you please try replacing the offending line by this:
```C
    LHSRef ref = { R_INVALID, {0}, {0} };
```
If that does *not* help, we can still resort to this:
```C
LHSRef ref; ref.type = R_INVALID; ref.var = 0; ref.nest0 = 0;
```
or this
```C
LHSRef ref;
memset(&ref, 0, sizeof(ref));
```

**Comment by hulpke** [comment]
@fingolfin 
The first version you suggest works OK. Thanks.

**Comment by alex-konovalov** [comment]
Backported to stable-4.10 in 986d08a9387941988e7bec9379b041c57d37cb2d to be ready for GAP 4.10.1 release.
