### ISSUE TITLE
Possible infinite recursion in PRINT_OR_APPEND_TO_FILE_OR_STREAM

### ISSUE THREAD

**Issue by embray** [gap-system/gap#3028]
If a stream that is being used to print errors cannot be opened (e.g. an error elsewhere prevents streams from being closed properly) this can result in an infinite recursion when reporting that error.

The specific problem is in the error handling logic here: https://github.com/gap-system/gap/blob/efd36263527f76bf3cc1cf33c5799a9bbc8734a6/src/streams.c#L799

If an `ErrorQuit` (for example) occurs elsewhere, and the stream assigned to `ERROR_OUTPUT` cannot be opened for whatever reason, this results in another call to `ErrorQuit` with the same broken stream assigned and so on.  Perhaps this should do something else: Try to open `*errout*` as a last resort, `Panic()`, etc.

**Comment by markuspf** [comment]
See #2487

**Comment by fingolfin** [comment]
I believe we resolved this some time ago (and the fixes are already in GAP 4.11). If you still can trigger an issue and/or believe there is one based on reading the code, please don't hesitate to reopen this and/or file a new issue.

**Comment by embray** [comment]
I can believe it's been fixed but I'm not sure since the code I originally implicated hasn't been updated, but it might be dealt with elsewhere.  I admit I don't recall how the issue was originally triggered.  It might have shown up while developing the workaround I had to add for the Python libgap interface to capture error output: https://gitlab.com/sagemath/sage/-/blob/1e728ac0d36514f52871268588d38fe1392a5e5a/src/sage/libs/gap/util.pyx#L198

**Comment by fingolfin** [comment]
There is a new dedicated function for opening errout in `src/error.c` with fallbacks in case there is an error doing so. See https://github.com/gap-system/gap/blob/9723019120f605fe89c590d86aa40d95c735563c/src/error.c#L58
