### ISSUE TITLE
libgap API: How much (if any) of GASMAN to expose?

### ISSUE THREAD

**Issue by embray** [gap-system/gap#3030]
Currently none of the garbage collection related functions are (intentionally) exposed in libgap-api.h.  At the very least least the `markBagsCallback` that currently gets passed to `GAP_Initialize` needs to be able to call `MarkBag` on objects being tracked by the user.

If you didn't want to expose GASMAN internals at all (e.g. maybe for working with GAP built to use a different GC?) an alternative might be to change the `markBagsCallback` to simply return a pointer to an array of Bags (or some more opaque object pointer type) that the user wishes to be marked as active by the GC.  So instead of the current implementation of

```
    /* allow installing a custom marking function. This is used for integrating
       GAP (possibly linked as a shared library) with other code bases which use
       their own form of garbage collection. For example, with Python (for
       SageMath) or Julia. */
    if (ExtraMarkFuncBags) {
        (*ExtraMarkFuncBags)();
    }
```

something roughly more like

```
if (ExtraMarkFuncBags) {
    Bag* tmp = ExtraMarkFuncBags();
    for (tmp; tmp != NULL; tmp++) {
        MarkBag(*tmp);
    }
}
```

just a thought, in case you would prefer to keep GC-related details more private.

**Comment by fingolfin** [comment]
I have no problem with exposing `MarkBag` as `GAP_MarkBag`, it is supported by all three GC implementations, too, and if we ever add more, they'll also have it. BTW, you can also see that we (well, I at least) consider this acceptable by looking at https://hackmd.io/s/SJzZVOLem . So if you want to submit a PR adding it, we'll merge it.

**Comment by embray** [comment]
Okay, fine by me!  It would be good to have `CollectBags` as well, which I also see in your list of "functions which are probably OK for the API".

**Comment by fingolfin** [comment]
Yeah, `CollectBags` is fine, too. I would recommend only exposing the `full` argument, though, so e.g. `void GAP_ CollectBags(int full)`. Also, feel free to come up with a name where it is "easier to guess what it means"; perhaps `GAP_CollectGarbage`? I find it hard to judge this, as of course I am intimately familiar with the internal GAP "API", and so for me, the closer the new name is to the internal name, the "easier"; but people who just want to use the API might appreciate some fresh air.

**Comment by embray** [comment]
> BTW, of course we are aware that many more APIs are needed (indeed, for the various GAP-to-X interfaces I've been working on, I'd need more). But instead of blindly adding random APIs based on guesses whether somebody might or might not need them, we prefer to add them based on request resp. actual use, to make sure the APIs we add are usable and useful in practice, and not just in theory.

Yes, definitely.  A "YAGNI" approach would be good here (which is why I was hesitant about requesting anything related to garbage collection at all).  

> `ClearError` -> we can expose that, but on the long run, I'd rather not, but instead get the error handling story "right". But that's not something I expect to be quickly done, so I guess we can add it to the API, with the understanding that it might go or change to a no-op in a distant future revision of the API

It might still prove useful even in a revised error-handling situation.  Consumers of the API will want to check whether an error occurred, and possibly manually call some "ClearError" to indicate that the error has been handled somehow, and execution of the GAP kernel may proceed normally.  Otherwise, one might call further GAP functions with an already set error condition, which might cause undefined or undesired behavior.  Also, per my comments in #2487 I could try to work on the error-handling situation, as I have a pretty good handle on the situation now, I think...

**Comment by fingolfin** [comment]
With PR #4215 merged, can this be closed? If not, what do you think is missing from the GASMAN / GC interface?

**Comment by embray** [comment]
Thanks, I missed that this was merged.
