### ISSUE TITLE
problematic method to compute the identity of a matrix group

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#3048]
The file `lib/grpmat.gi` contains the following method installation.
```
InstallOtherMethod( One,
    "for matrix group, call `IdentityMat'",
    [ IsMatrixGroup ],
    grp -> ImmutableMatrix(DefaultFieldOfMatrixGroup(grp),
             IdentityMat( DimensionOfMatrixGroup( grp ),
             DefaultFieldOfMatrixGroup( grp ) ) ));
```
I would like to just remove this method, but perhaps someone has a better idea.

Apparently the idea behind this method is that one wants to avoid computing
the identity of a representative of the group (this is done in a lower ranked method),
since GAP might be forced to create a superfluous element of the group for that.

However, this approach is logically wrong,
since the matrix entries themselves cannot know in general
how the matrices in question shall look like.

Just two examples:
- Think of a matrix group over the rationals, where one can implement the matrices as
  arrays of rationals or as arrays of integers plus a common denominator;
  the domain of matrix entries does not know about the intended matrix design.
- Think of matrices with memory concerning how they were created from seed matrices;
  the above method cannot create anything reasonable in this case.

Note that `IdentityMat` is a function that creates a plain list of lists,
thus the above method must be avoided whenever one deals with other kinds of matrices.

**Comment by fingolfin** [comment]
I agree that this should just be removed. If someone (e.g. @hulpke) knows concrete examples were it matters, we can investigate alternative solutions to whatever problem this was meant to solve.

**Comment by hulpke** [comment]
I vaguely remember that there was a problem with the method requiring the representative (IIRC in some example, it was expensive to get a representative), but I don't recall details. I will bring it up if it arises again.

**Comment by stevelinton** [comment]
@hulpke Seems like, if that is the situation it would be better to store the One of the group when the group is created.

**Comment by ThomasBreuer** [comment]
When one creates a group then there is no problem to fetch a representative if either
a nonempty list of generators is stored or the identity is stored or a parent is stored
that is able to fetch a representative.
(Perhaps several library methods for that could be unified.)
If none of these applies then usually one will be in trouble.
In the special case of matrix groups, one might know the base ring and the dimension,
but as I had sketched, this is not enough.
Thus I think that in such a situation, one will either need a very special method that can create
a representative on demand, or (as @stevelinton suggested) the identity should be stored
already when the group is created.

**Comment by markuspf** [comment]
I assume we can close this issue now that #3050 is merged?

**Comment by ThomasBreuer** [comment]
Yes, pull request #3050 solves the problem.
