### ISSUE TITLE
Builtin zlib: Fix incompatbility with libgap.la

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3049]
When GAP is built, it wants to link against zlib. If we can't find headers and libraries for zlib, we build our own version of that. But for simplicity, we only build a static linked version.

Unfortunately, this is a problem when linking `libgap.la`, which now triggers on most (all?) systems a warning or even an error. And of course in `master`, we now build `libgap.la` as part of the default target, making this more prominent

Several fixes come to mind:
1. re-enable building of zlib as a dynamic library (possibly with new custom build rules, e.g. using our `libtool` executable)
2. Don't build `libgap.la` if we use our builtin zlib (or at least don't build it as part of the default target)
3. Replace zlib with https://github.com/richgel999/miniz (or something similar) and link that as part of the GAP binary, not an external library, and make sure not to export any of it symbols; that way, it remains fully transparent to the outside world. UPDATE: Unfortunately, miniz does not provide gzopen, gzread etc., so that's not as trivial a change as I originally hoped.

**Comment by fingolfin** [comment]
Pinging @ChrisJefferson to make sure he's aware of this issue, too

**Comment by ChrisJefferson** [comment]
I think in the short term (2) seems sensible, just to get GAP working again. I'm happy for someone to do (1). I tried doing it originally but found linking staticly was easier.
