### ISSUE TITLE
Tabs on continuation lines break GAP's testing

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#3068]
if one uses tab characters on continuation lines in a test file, this confuses GAP:

```
gap> f := function()
>\tlocal a;
>\tif a = 0 then
>\t\tError("a is zero");
>\tfi;
> end;;
```

```gap> Test("tab.tst");
########> Diff in tab.tst:1         
# Input is:
f := function()
	local a;
		Error("a is zero");
end;;
# Expected output:
>	if a = 0 then
>	fi;
# But found:
########
false
```

**Comment by ChrisJefferson** [comment]
There is another bug here, which I think is making this one harder to spot. GAP allows continuation lines in the middle of the output, and puts them as part of the input.

```
gap> x := 2 +
>	cheese
> 2;
3
```

gives:

```
########> Diff in t.tst:1           
# Input is:
x := 2 +
2;
# Expected output:
>	cheese
3
# But found:
4
########
false
```

**Comment by ChrisJefferson** [comment]
This issue has been improved somewhat. Further improves were unfortunately difficult due to the fact that some package rely on not this specific case, but similar cases where tests are formatted strangely.
