### ISSUE TITLE
Error when computing irreducibles of a permutation group

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#3114]
The following happens in GAP 4.10.0 as well as in the current master branch.

```
gap> g:= AtlasGroup( "U3(8).3^2" );;
gap> Irr( g );;
Error, List Element: <list>[19] must have an assigned value in
  M[s][t] := M[s][t] + T[2][i]; at /.../ctblgrp.gi:1790 called from
D.ClassMatrixColumn( D, M, bestMat, col
 ); at /.../ctblgrp.gi:716 called from
SplitStep( D, bsm ); at /.../ctblgrp.gi:2065 called from
DixonSplit( D ) at /.../ctblgrp.gi:2171 called from
IrrDixonSchneider( G, rec(
     ) ) at /.../ctblgrp.gi:2152 called from
IrrDixonSchneider( G ) at /.../ctblgrp.gi:2194 called from
...  at *stdin*:2
type 'quit;' to quit to outer loop
```

(The error messages are not exactly the same in the two versions,
in the sense that they point to different positions in `<list>`.)

GAP 4.9.0 does not have this problem.
The same holds for GAP 4.7.6.
(And the computation in GAP 4.9.0 is much faster than that in GAP 4.7.6.)

**Comment by hulpke** [comment]
@ThomasBreuer I have been unable to reproduce this in either 4.10 or the development version, both on a Mac and under Linux (They all calculated the table). Can you send me your startup banner, so I can compare if there is any difference in autoloaded packages, and maybe also Linux/compiler version?

**Comment by ThomasBreuer** [comment]
@hulpke Thanks for investigating this problem.
For the sake of simplicity, take the two permutation generators as given by `AtlasGroup`,
start GAP without packages, and construct the group just from the given permutations.
In this situation, I get the abovementioned error message, and the GAP banner looks as follows.
```
 ┌───────┐   GAP 4.10.0 of 01-Nov-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64
 Configuration:  gmp 6.1.2, Julia 1.1.0-DEV, readline
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.2, PrimGrp 3.3.2, SmallGrp 1.3, TransGrp 2.0.4
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```
`gcc --version` says `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609`.

**Comment by hulpke** [comment]
@ThomasBreuer Thank you. I get the same banner, but for the Julia entry, but my calculation works OK. My gcc under Linux is much older

    gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)

Can you run your GAP without Julia included?

**Comment by ThomasBreuer** [comment]
@hulpke Thanks. When GAP is compiled without Julia, the problem disappears.
I will turn this issue into one for the Julia integration.

**Comment by ThomasBreuer** [comment]
@rbehrends @fingolfin Could you please have a look at this problem?

**Comment by rbehrends** [comment]
I'll have a look at it, but probably not before Thursday; it may be related to the GC bug I am chasing (and if it is, that'll be nice, as it would then be reproducible).

**Comment by fingolfin** [comment]
I can reproduce this, and as another daya point, I get:
```
brk> T[2];
"identity"
```

**Comment by fingolfin** [comment]
@rbehrends what is the status of this?

**Comment by rbehrends** [comment]
The problem that I'm dealing with is that while it is reproducible, the computation takes long enough that it's still difficult to pinpoint where exactly the memory corruption occurs.

**Comment by ChrisJefferson** [comment]
This bug also occurs with `"U3(8)"` (just to give another place to test from)
