### ISSUE TITLE
[i,j] syntax not supported by AtomicLists in HPCGAP

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#3115]
This works fine in HPCGAP:
```
gap> l := [];;
gap> l[1] := [];;
gap> l[1,1] := 5;;
gap> l;
[ [ 5 ] ]
```

This doesn't:
```
gap> l := AtomicList(5, 0);;
gap> l[1] := AtomicList(5, 0);;
gap> l[1,1] := 5;               
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `[]:=' on 4 arguments at /home/sergio/.local/opt/hpcgap/lib/methsel2.g:249 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at stream:30
type 'quit;' to quit to outer loop
```

**Comment by fingolfin** [comment]
That's a feature, not a bug. This syntax is meant for matrix access, don't use atomic "lists" for that'

Of course you could still install methods to do what you want with atomic lists, but I'd recommend against it.

**Comment by alex-konovalov** [comment]
I have removed "Release notes: not needed" label - as its description says "Set this if the change is not relevant for the release notes", and it is used for PRs, not for issues.

**Comment by ssiccha** [comment]
@fingolfin thanks for the clarification
@alex-konovalov
