### ISSUE TITLE
(Ab)use of attribute "InfoText"

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#313]
The character table library declares the attribute `InfoText`, which is used by the file `polyconvw.gi`.

The way I see it, we either declare a fairly generic attribute "InfoText" for everyone to use, or at least get rid of this cross-dependency.

I am opening this issue mainly to find out which one it should be.

**Comment by frankluebeck** [comment]
I agree that this could be declared in a more generic place (maybe object.gd) and the documentation could be (shorter and) more generic as well. The current documentation could then probably be removed. Instead it could be mentioned in the character table library that this attribute is available for the library tables (similar to its mention in the manual section on `ConwayPolynomial`). 

Note that it is documented that the value of this attribute is a mutable string such that further information can be collected in it on the fly. (At some later stage we may want to allow more general objects.)

**Comment by markuspf** [comment]
I have a work in progress patch for this (https://github.com/markuspf/gap/tree/add-infotext), but because of issue #318 I can't build the documentation right now, so I can't make sure my changes are correct.

**Comment by alex-konovalov** [comment]
Thanks - left some comments at https://github.com/markuspf/gap/commit/f0483a4283435ffb2e9002fb0c7d7cfd417b90a9

**Comment by frankluebeck** [comment]
@markuspf :  Here are some hints which may be useful for future changes as well.

* The syntax `<#GAPDoc ...` and `<#Include...` is not XML, but part of a simple and flexible mechanism to distribute and collect a document over many (e.g., source code) files. See `?GAPDoc: A Tool for Collecting a Document`. In particular, your current use of `<#Include` in `objects.xml` is not correct.
* The label for the `<#GAPDoc`-tag of `InfoText` in `ctbl.gd` must be changed (it must be unique).
* In the `ManSection` for `InfoText` for character tables the `<Attr ...`-element should be changed into a `<Meth ...`-element.
* To distiguish the different sections on `InfoText` a `Label` attribute should be added to the `<Meth`-element mentioned before (such that unique `<Ref`s can be generated and the result of `?InfoText` distinguishes the entries).
* In the ManSection on `ConwayPolynomial` an `<Index ...` entry for `InfoText` could be added.

I'll send a patch via email.

**Comment by markuspf** [comment]
This is now in #330. Thanks @frankluebeck for the patch!

**Comment by fingolfin** [comment]
Since #330 was merged, I believe we can close this now.
