### ISSUE TITLE
Int(nan) attempts to create string of negative length

### ISSUE THREAD

**Issue by mtorpey** [gap-system/gap#3135]
We can produce an object called `nan` by, for example, calling `Log10` on a negative number.  This is to be expected, but what is not expected is what happens when we put `nan` into `Int`:
```
gap> x := Log10(-1.3);
nan
gap> Int(x);
Error, NEW_STRING: Cannot create string of negative length -2147483645
not in any function at *stdin*:6
```
It seems that on the C level, we're trying to use the absolute value of `nan`, which isn't well-defined.  I'm not sure what's causing this, but probably there should be a more sensible error message.

**Comment by fingolfin** [comment]
Same happens for `inf`:
```
gap> x:=1/0.;
inf
gap> Int(x);
Error, NEW_STRING: Cannot create string of negative length -2147483645
```
