### ISSUE TITLE
Random behavior of float numbers

### ISSUE THREAD

**Issue by mohammadfarrokhi** [gap-system/gap#3157]
What's wrong with the following codes? Regardless of the results, I think both results must be the same.

```
gap> 7.8=7.800000000000001;
false
gap> 8.8=8.800000000000001;
true
```

The following code shows the above inconsistency occurs almost randomly.

```
for n in [1..100] do 
	for i in [0..9] do 
		x := n + Float(i/10);
		Print(x,"\n");
	od;
od;
```

**Comment by markuspf** [comment]
Floating point numbers on computers are quite mind boggling beasts. This is not a problem in GAP, but a problem with the representation of floating point numbers as *approximations* of the literal you enter. For example the number `7.8` cannot be represented exactly as a float, the number that is stored is `7.79999999999999982236431605997495353221893310546875`.

As such comparing floating point numbers with `=` is almost never what you want. I recommend reading stuff like this: https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/ for reference.
