### ISSUE TITLE
Add GAP interface to setenv

### ISSUE THREAD

**Issue by gaehler** [gap-system/gap#3166]
By analogy programming, I managed to write (in package Carat) a dynamical kernel module to set an environment variable in the main GAP process. The idea is to teach CARAT programs the current location of their data tables, overriding the value determined at compile time.

It works, but I first got a warning that a dynamic module combined with a static zlib is not portable. After I installed zlib from the distribution (Ubuntu 18.04), the warning went away - but why is the bundled zlib linked statically, if this is not portable?

Also, I wondered whether a GAP interface to getenv and expecially setenv would not be of general interest, rather than implementing this in a package.

I'm using:
GAP 4.10.0 of 01-Nov-2018
Architecture: x86_64-pc-linux-gnu-default64
Configuration:  gmp 6.1.2, readline

**Comment by ChrisJefferson** [comment]
Can you give a list of instructions which cause the error about a static zlib not being portable? I've never seen it before.

**Comment by markuspf** [comment]
Only marginally related: If you're calling `setenv`, I suggest adding this syscall to the `io` package.

**Comment by gaehler** [comment]
@ChrisJefferson Remove Ubuntu package zlib1g-dev, configure and make GAP again, and then, in the GitHub version of GAP-package Carat:
```
./configure <path-to-GAP-root>
make dynmod
```
This produces:
```
/homes/gaehler/gap/gap-current/gac -d -o bin/x86_64-pc-linux-gnu-default64/setcaratdir.so src/setcaratdir.c
/bin/bash /homes/gaehler/gap/gap-4.10.0/libtool --mode=compile gcc -g -O2 -o /tmp/gaclYGsNef/7607_setcaratdir.lo -I/homes/gaehler/gap/gap-4.10.0/gen -I/homes/gaehler/gap/gap-4.10.0/src -I/homes/gaehler/gap/gap-4.10.0 -DHAVE_CONFIG_H -I/homes/gaehler/gap/gap-4.10.0/extern/install/zlib/include -c src/setcaratdir.c
libtool: compile:  gcc -g -O2 -I/homes/gaehler/gap/gap-4.10.0/gen -I/homes/gaehler/gap/gap-4.10.0/src -I/homes/gaehler/gap/gap-4.10.0 -DHAVE_CONFIG_H -I/homes/gaehler/gap/gap-4.10.0/extern/install/zlib/include -c src/setcaratdir.c  -fPIC -DPIC -o /tmp/gaclYGsNef/.libs/7607_setcaratdir.o
/bin/bash /homes/gaehler/gap/gap-4.10.0/libtool --mode=link gcc -module -avoid-version -rpath /lib /homes/gaehler/gap/gap-4.10.0/extern/install/zlib/lib/libz.a -o bin/x86_64-pc-linux-gnu-default64/setcaratdir.so /tmp/gaclYGsNef/7607_setcaratdir.lo

*** Warning: Linking the shared library bin/x86_64-pc-linux-gnu-default64/setcaratdir.la against the
*** static library /homes/gaehler/gap/gap-4.10.0/extern/install/zlib/lib/libz.a is not portable!
libtool: link: gcc -shared  -fPIC -DPIC  /tmp/gaclYGsNef/.libs/7607_setcaratdir.o   /homes/gaehler/gap/gap-4.10.0/extern/install/zlib/lib/libz.a    -Wl,-soname -Wl,setcaratdir.so -o bin/x86_64-pc-linux-gnu-default64/.libs/setcaratdir.so
libtool: link: ( cd "bin/x86_64-pc-linux-gnu-default64/.libs" && rm -f "setcaratdir.la" && ln -s "../setcaratdir.la" "setcaratdir.la" )
rm -f /tmp/gaclYGsNef/7607_setcaratdir.lo

```

**Comment by fingolfin** [comment]
The zlib issue was already reported in issue #3049

**Comment by ChrisJefferson** [comment]
The zlib part of this issue is now fixed. the getenv and setenv sound like very sensible additions to GAP, I'd personally be happy for them to go either in main GAP, or in the IO package.

**Comment by fingolfin** [comment]
`setenv` is a non-portable POSIX API. As such, I think it'd be a much better fit for the `io` package, where adding it would also be relatively easy. I've logged this under https://github.com/gap-packages/io/issues/109

**Comment by fingolfin** [comment]
The new IO 4.8.0 release now provides `IO_setenv`, `IO_unsetenv` and `IO_getenv`. It will be bundled with GAP 4.12.1
