### ISSUE TITLE
GAP enters infinite loop when it cannot open errin (was: make manuals does not work)

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#318]
When I try building the manual using

```shell
gmake manuals
```
`gap` seems to be going into an infinite loop spitting out
```
Error, SHELL: can't open infile *errin* in
   called from 
```

Which seems to be coming from `lib/error.g`.

**Comment by markuspf** [comment]
The same actually happens for `gmake testinstall` as well, which is a bit unfortunate because it means I cannot run tests on my machine before I submit pull requests.

**Comment by markuspf** [comment]
At least for `testinstall` this is *caused* by loading all packages, specifically loading the `datastructures` package and the `orb` package which are at the moment incompatible. This is of course still a bug in that `gap` just gets into an infinite loop here without any useful error message.

**Comment by ChrisJefferson** [comment]
Can you catch gap's output from the start? (and see if it is putting anything in whichever file it redirects input into as well)

**Comment by alex-konovalov** [comment]
OK, so first, this is not an issue about `make manuals` not working (BTW, if it's seriously broken, some Jenkins would probably fail), and second, the `datastructures` package is not deposited. 

Maybe keeping it in `.gap/pkg/` would work for you, since `make` targets call GAP with `-r` option and packages that you're keeping locally in  `.gap/pkg/` will be ignored?

**Comment by ChrisJefferson** [comment]
I've seen this in the past but not been able to reproduce it -- some part of GAP's error reporting gets stuck in an infinite loop, so if you can reproduce it, that's great!

**Comment by markuspf** [comment]
@ChrisJefferson let's focus on `gmake manuals`, because I can reproduce that issue on a cleanly downloaded GAP. I believe this happens when an Error happens in certain places (for example when loading a package). If I `gmake manuals` on my machine and look at the `make_manuals.out` after killing the GAP session that ran amok, there's this:
```
#W WARNING: non resolved reference: rec(
  BookName := "tut",
  Sect := "Attributes" )
fname := ShallowCopy( stream![2] )
 ; on line 154 of file /home/makx/ac/gap/pkg/GAPDoc-1.5.1/lib/HelpBookHandler.\
gHELP_BOOK_HANDLER.GapDocGAP.ReadSix( stream 
 ) on line 1946 of file /home/makx/ac/gap/lib/package.gi called from
<function "GAPDocManualLabFromSixFile">( <arguments> )
 called from read-eval loop at line 29 of makedocrel.g
res := SHELL( context, mayReturnVoid, mayReturnObj, 1, false, prompt, false, 
   "*errin*", "*errout*", false )
 ; on line 234 of file /home/makx/ac/gap/lib/error.gfname := ShallowCopy( stream![2] )
 ; on line 154 of file /home/makx/ac/gap/pkg/GAPDoc-1.5.1/lib/HelpBookHandler.\
g called from
HELP_BOOK_HANDLER.GapDocGAP.ReadSix( stream 
 ) on line 1946 of file /home/makx/ac/gap/lib/package.gi called from
<function "GAPDocManualLabFromSixFile">( <arguments> )
 called from read-eval loop at line 29 of makedocrel.g
res := SHELL( context, mayReturnVoid, mayReturnObj, 1, false, prompt, false, 
   "*errin*", "*errout*", false )
 ; on line 234 of file /home/makx/ac/gap/lib/error.gres := SHELL( context, mayReturnVoid, mayReturnObj, 1, false, prompt, false, 
   "*errin*", "*errout*", false )
 ; on line 234 of file /home/makx/ac/gap/lib/error.g called from
fname := ShallowCopy( stream![2] )
 ; on line 154 of file /home/makx/ac/gap/pkg/GAPDoc-1.5.1/lib/HelpBookHandler.\
g called from
```

This is confirmed by just trying to manually build the reference manual by starting gap, loading the workspace, and reading `makedocrel.g`, where the following Error happens
```
Error, List Element: <list> must be a list (not a boolean) in
  fname := ShallowCopy( stream![2] )
 ; on line 154 of file /home/makx/ac/gap/pkg/GAPDoc-1.5.1/lib/Hel\
pBookHandler.g called from
HELP_BOOK_HANDLER.GapDocGAP.ReadSix( stream 
 ) on line 1946 of file /home/makx/ac/gap/lib/package.gi called f\
rom
<function "GAPDocManualLabFromSixFile">( <arguments> )
 called from read-eval loop at line 29 of makedocrel.g
you can replace <list> via 'return <list>;'
```

Which means that the stream passed into this function is broken. There are two issues:

* Why is the stream `fail`?
* Why does GAP go off on a spin if an error happens when it's run non-interactively?
* Bonus issue: Why does this happen on my machine but not on a Jenkins builder (or apparently anywhere else).

**Comment by ChrisJefferson** [comment]
Is some other stuff appearing on your screen? I notice some parts of GAP's output are missing, I suspect they are going to *errout* (which will be bound to stderr by default), which would show us the actual error which is occuring (seperate long standing issue, clean up what goes to err and what goes to out).

**Comment by markuspf** [comment]
Which bit are you referring to now? The pastes are taken from `make-manuals.out`, and the output on in my terminal window, and except for the repeating error message there is no additional output.

It seems that the error itself is caused by the `.six` file not being created.

**Comment by alex-konovalov** [comment]
@markuspf that may be a clue - check you LaTeX installation then!

**Comment by markuspf** [comment]
Is it not possible to build at least the text/html part of the documentation without LaTeX?
If so: why? and why does GAP not error out properly if there is no LaTeX, then?

Also of course this doesn't solve the infinite loop problem.

**Comment by ChrisJefferson** [comment]
Are you on a strange BSD? If so, I suspect the reason you are hitting this infinite loop has something to do with the code around system.c:1808, in particular the setting of 'syBuf[2]', which is '*errin*'. I can't figure out why it would ever be valid to try to open stderr for reading, but I suspect somehow these streams are getting set up strangely on your machine.

Of course, we should still try to make GAP behave better when these things happen.

**Comment by alex-konovalov** [comment]
> Is it not possible to build at least the text/html part of the documentation without LaTeX?

Not with makedocrel.g which is intended to build the manual in all formats. We may introduce `make manuals-light` if there is a genuine need in such thing (maybe for a quick validation).

**Comment by ChrisJefferson** [comment]
The bad code is: gap.c:258.

Basically, we are already trying to make a new shell, and if we fail to open 'inFile', then we enter another break loop -- an infinite loop proceeds.

There are a couple of different ways to fix this, all of them a bit nasty. My temptation is to just say if we want to read *errin*, and can't, just exit (at the C level), something has gone badly wrong.

**Comment by markuspf** [comment]
Could you enlighten me on what "errin" is?

DragonFly refuses to open `ttyname(fileno(stderr))` in `O_RDONLY` (which might be a bug as well, but I don't know).

I fully agree that we should just panic if we don't know what else to do, it's certainly better than ending up in an infinite loop.

**Comment by ChrisJefferson** [comment]
Most systems just have stdin. I have discovered today GAP seperates this into stdin and errin, where errin is used in break loops. GAP then uses the trick of opening ttyname(fileno(stderr) to read to grab the terminal, even when you redirect a file in. This is why even if you run gap like 'gap < file.in', the break loop still reads from the keyboard.

If you want this behaviour, we could investigate other ways of grabbing the keyboard, even when people have directed a file in.

Of course, we should still make sure if we just don't end up with an errin, we don't go crazy and crash.

**Comment by markuspf** [comment]
I'd be happy if as a first step, GAP didn't just crash and burn in flames. It might well be that DragonFly needs to allow opening the pts device for these types of use: I was trying to think of a nicer way of achieving an `errin`, but currently can't.

**Comment by markuspf** [comment]
So I am looking at fixing this right now. Is it ok to just `ErrorQuit` in the case of `Shell` not being able to open either in or out? It fixes my problem, but I am not familiar enough with the Quit codepaths to know whether this will blow up other people's code all over the place.

**Comment by ChrisJefferson** [comment]
Just for clarity, ErrorQuit is like ErrorMayQuit, but doesn't give a break loop?

That seems like the right choice -- we are already trying to set up a break loop / new shell, we shouldn't error by creating yet another shell!

**Comment by markuspf** [comment]
ErrorQuit just prints an error and quits (according to the documentation, which I decided to trust in). One still gets the rather ugly 
```
Error, SHELL: can't open infile *errin* in
   called from 
```
message, but GAP then quits and doesn't get into an infinite loop.

After all, if we do not know how to handle input or output there is literally no point in trying to continue interactively, but the error message should probably be slightly better.

**Comment by ChrisJefferson** [comment]
@markuspf : Did you make this into a pull request yet? Even if it's not super-nice, it would be nice to get docs building again (so other patches can make their way in).

**Comment by alex-konovalov** [comment]
@ChrisJefferson just in case - the problem with building docs in only on the local machine where @markuspf tested his changes before pushing them. Otherwise docs building works.

**Comment by markuspf** [comment]
On Mon, Nov 02, 2015 at 03:15:22PM -0800, Alexander Konovalov wrote:
> @ChrisJefferson just in case - the problem with building docs in only on the
> local machine where @markuspf tested his changes before pushing them. Otherwise
> docs building works.

This is still a *proper* bug. It can crash on any system that doesn't allow
the trick to open the terminal that it is run on for getting interactive mode
when piping is happening.

@ChrisJefferson, I didn't make it a pull request, but I will.

**Comment by alex-konovalov** [comment]
@markuspf I totally agree that this is a proper big - I'm just saying that id does not block us from merging other patches (unless I've misunderstood @ChrisJefferson who was saying this).

**Comment by dimpase** [comment]
This reminds me of an old discussion on http://trac.sagemath.org/ticket/13211 (in particular segfault on 
gap &>/dev/full) that was also reported on http://tracker.gap-system.org/issues/221 (I can't see the latter, is it gone, moved here, or?)

**Comment by alex-konovalov** [comment]
@dimpase I think you have a different issue in mind: http://tracker.gap-system.org/issues/125. That attempt of an issue tracker for GAP is still accessible (one needs to have an account for that). We did not perform any mass migration of issues - instead, their authors are advised to revisit them, evaluate their status and create new issues on GitHub, if need be. There are some interesting discussions there...
