### ISSUE TITLE
Test failure on OS X in read.tst

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3196]
PR #3165 add the following to `read.tst` (via commit c8e7bab0d2de77715c7616a425a7a6f5811129b7), which fails on Mac OS X (and presumably other non-Linux operating systems):

```
gap> FileString("/dev/full", "outdata", false);
Error, in FileString: No space left on device (28)
```

**Comment by ChrisJefferson** [comment]
Does MAC OS X not have /dev/full, or produce a different error?

**Comment by fingolfin** [comment]
There is no `/dev/full` on OS X, and according to Google, it is Linux specific.
