### ISSUE TITLE
Rare assertion error in sanity.g returns both in stable-4.10 and master branches

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3206]
This has been observed before in #2990 and was claimed to be fixed, however I seen it again in 32-bit build on kovacs ([this link, accessible only from St Andrews](https://gap-ci.cs.st-andrews.ac.uk/view/GAP-weekly/job/GAP-stable-sanity/GAPCOPTS=32build,label=kovacs/19/console)):

```
testing group t20n969
conjugacy classes
Error, Assertion failure in
  Assert( 2, Sum( clout, function ( i )
          return Index( F, i[2] );
      end ) = Size( F ) - Size( M ) 
 ); at /circa/scratch/gap-jenkins/workspace/GAP-stable-sanity/GAPCOPTS/32build\
/label/kovacs/GAP-stable-snapshot/lib/clashom.gi:1050 called from 
```
Observe, it occurs on the same group `t20n969` as before. Maybe there are multiple issues that may trigger this, @hulpke ?

**Comment by alex-konovalov** [comment]
This is still happening: e.g. most recently in 64-bit build on kovacs [here](https://gap-ci.cs.st-andrews.ac.uk/view/GAP-weekly/job/GAP-stable-sanity/30/GAPCOPTS=64build,label=kovacs/console)  (the build only accessible from St Andrews):
```
testing group t20n969
conjugacy classes
Error, Assertion failure in
  Assert( 2, Sum( clout, function ( i )
          return Index( F, i[2] );
      end ) = Size( F ) - Size( M ) 
 ); at /circa/scratch/gap-jenkins/workspace/GAP-stable-sanity/GAPCOPTS/64build\
/label/kovacs/GAP-stable-snapshot/lib/clashom.gi:1050 called from 
Build step 'Execute shell' marked build as failure
```

**Comment by alex-konovalov** [comment]
I can't say at the moment anything for the master branch, as sanity test was only run for stable-4.10. I have now created a similar weekly test [here](https://gap-ci.cs.st-andrews.ac.uk/view/GAP-weekly/job/GAP-master-sanity/) for the master branch so we will see. In the future, I may run this every other week, or once per month, if it will take too much.

**Comment by alex-konovalov** [comment]
This happened in the master branch too, in a 32-bit build, and for a different group ([St Andrews only link to the build](https://gap-ci.cs.st-andrews.ac.uk/job/GAP-master-sanity/GAPCOPTS=32build,label=kovacs/1/console)):
```
testing group t18n935
conjugacy classes
Error, Assertion failure in
  Sum( clout, function ( i )
        return Index( F, i[2] );
    end ) = Size( F ) - Size( M )
  at /circa/scratch/gap-jenkins/workspace/GAP-master-sanity/GAPCOPTS/32build/l\
abel/kovacs/GAP-master-snapshot/lib/clashom.gi:1057 called from 
```
@hulpke perhaps you have any ideas what's happening?

**Comment by alex-konovalov** [comment]
Same in [64-bit build](https://gap-ci.cs.st-andrews.ac.uk/job/GAP-master-sanity/GAPCOPTS=64build,label=kovacs/1/display/redirect) for the same `t18n935` group.

**Comment by alex-konovalov** [comment]
@hulpke how complicated this assertion is? Will it be a big performance penalty if we will run it at level zero? This will prevent users from running into this error without notice, and may lead to easier reproducible cases.

**Comment by hulpke** [comment]
@alex-konovalov As it just sums up known sizes it should not be costly. (Yes, I know I need to look at this code, but there is also other stuff pending.)

**Comment by alex-konovalov** [comment]
Thanks @hulpke - then this could be an option if we will not have a better solution by the time of GAP 4.11.

**Comment by alex-konovalov** [comment]
Seems to be gone in the master branch by now!
