### ISSUE TITLE
testbugfix broken in the master branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3210]
See e.g. https://travis-ci.org/gap-infra/gap-docker-master-testsuite/builds/482463963 where the following happens in all three settings for testbugfix:
```
########> Diff in /home/gap/inst/gap-master/tst/testbugfix/2012-06-18-t00328.t\
st:2
# Input is:
if TestPackageAvailability("anupq") <> fail and
      LoadPackage("anupq",false) <> fail then
for i in [1..192] do Q:=Pq( FreeGroup(2) : Prime:=3, ClassBound:=1 ); od; fi;
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `CallFuncList' on 2 arguments
########
```

**Comment by alex-konovalov** [comment]
`CallFuncList` problem also appears in anupq and resclasses tests here: 
- anupq: https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/482690834
- resclasses: https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/482690902

**Comment by ChrisJefferson** [comment]
Is this now fixed?

**Comment by alex-konovalov** [comment]
This is now fixed (e.g. https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/builds/506582668 for anupq and resclasses, https://travis-ci.org/gap-infra/gap-docker-master-testsuite/builds/506345725 for bugfix).
