### ISSUE TITLE
AllSmallGroups(-10) returns the Same as AllSmallGroups(10) 

### ISSUE THREAD

**Issue by ChoiwahChow** [gap-system/gap#3274]
gap> AllSmallGroups(-10);
[ <pc group of size 10 with 2 generators>, <pc group of size 10 with 2 generators> ]

It should either return error or empty set/group

 ┌───────┐   GAP 4.10.0 of 01-Nov-2018
 │  GAP         │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64
 Configuration:  gmp 6.1.2
 Loading the library and packages ...
 Packages:   AClib 1.3.1, Alnuth 3.1.0, AtlasRep 1.5.1, AutoDoc 2018.09.20, AutPGrp 1.10, Carat 2.2.2, CRISP 1.4.4, 
             Cryst 4.1.18, CrystCat 1.1.8, CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.2, IO 4.5.4, IRREDSOL 1.4, 
             LAGUNA 3.9.0, Polenta 1.3.8, Polycyclic 2.14, PrimGrp 3.3.2, RadiRoot 2.8, ResClasses 4.7.1, SmallGrp 1.3, 
             Sophus 1.24, SpinSym 1.5, TomLib 1.2.7, TransGrp 2.0.4, utils 0.59

**Comment by markuspf** [comment]
This is a problem with the package [smallgrp](https://github.com/gap-packages/smallgrp)

**Comment by markuspf** [comment]
https://github.com/gap-packages/smallgrp/issues/41
