### ISSUE TITLE
Future warning: BlocksFamily is bound in two packages

### ISSUE THREAD

**Issue by mohamed-barakat** [gap-system/gap#328]
The semigroup package binds BlocksFamily:

semigroups-2.5/gap/blocks.gd: BindGlobal("BlocksFamily",

and in the new yet unreleased package of T. Breuer as well:

ctblocks/gap/blockobj.gi: BindGlobal( "BlocksFamily",

**Comment by james-d-mitchell** [comment]
Just to mention that this has been in the released version of Semigroups redistributed with GAP since April of 2014.

**Comment by alex-konovalov** [comment]
Can we close this issue for now? I hope this will be resolved before the package will be released, otherwise we will detect this when we will start to test it, but there is no need to keep it open.
