### ISSUE TITLE
Overloading to resolve name clashes in packages.

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#329]
This idea had been discussed in gap-dev list in 2011. With the growing number of packages and more often name clashes, it may be time to rethink. The scheme that was suggested by @laurentbartholdi concerned `Diameter` which makes sense both in interval arithmetic and for graphs. To resolve this, package authors would have to ask for `Diameter` to be declared in the core GAP system, and then:
* `DiameterOfInterval` is a function in one package
* `DiameterOfGraph` is a function in another package
* `Diameter` is a method to be used by end users, which delegates to `DiameterOfInterval` or `DiameterOfGraph`.
* In the core GAP system `Diameter` is declared in a file called `overload.g`.

Instead of creating functions/operations with common names (e.g. `Graph`, `Cocycle`, `Block`, `Diameter`), package authors:
1. Ask (by email or via pull request) for a generic method to be declared in `overload.g`.
2. Put code like `if not IsBound(Diameter) then DeclareOperation(Diameter,[IsObject]) fi;` in their packages.
3. After some time, when the new version of `overload.g` became a part of the GAP release, remove the check from (2) from their package.

This will resolve name clashes, at the same time preserving the ability to keep natural name choices.

**Comment by frankluebeck** [comment]
This is not convincing. Why should core GAP need to do anything? As  long as several packages declare operations with the same name for different types of objects, there is no problem. Name clashes occur when different packages define functions with the same name. Of course, when packages declare the same operation for the same objects there can still be a conflict (different types of results, different order of arguments, ....).

But sometimes it can be useful to have methods of certain operations also available as functions.

**Comment by james-d-mitchell** [comment]
I agree with @frankluebeck, this sounds like it is a temporary solution that would in the end cause more work than it would save. Is there any prospect of GAP having proper namespaces?

**Comment by laurentbartholdi** [comment]
Dear all,
If I remember well, the point was that certain operations could be
implemented by different packages. Take for example "Diameter" for
intervals. Interval arithmetic could be defined by different packages, and
both should treat standard reals as intervals of width 0. If both packages
declare "Diameter" with filter [IsFloat], there is an annoying warning that
all further installed methods match 2 declarations. On the other hand, it's
harmless for both packages to install two methods; presumably the filters
will help GAP choose the fastest/best method.

**Comment by ChrisJefferson** [comment]
I agree with @frankluebeck, I though the point of Operations is that each package can declare them independantly, and fill in whatever values they like. If there is some reason this isn't possible, or is tricky, we should improve how Operations are defined.

**Comment by markuspf** [comment]
I also agree with @frankluebeck, this method is cumbersome and puts unnecessary load on the developers and it will not scale.

I also would like namespaces like @james-d-mitchell asked for. This discussion came up on the [open mailing list](https://mail.gap-system.org/pipermail/gap/2015-October/000219.html) recently again. 

Doing a good module system is of course hard work (but it has been done many times before in different shades and shapes). I am sure there were reasons why GAP wanted (wants?) to keep a flat namespace, but manually managing it is not the way.

**Comment by alex-konovalov** [comment]
Ok, thanks everyone - I am closing this issue then. For package authors coming across this issue - please see " Functions and Variables and Choices of Their Names" from the Example package manual: http://www.gap-system.org/Manuals/pkg/example/doc/chapA.html#X7DEACD9786DE29F1

**Comment by markuspf** [comment]
On Sun, Nov 01, 2015 at 07:27:23AM -0800, Alexander Konovalov wrote:
> Ok, thanks everyone - I am closing this issue then. For package authors coming
> across this issue - please see " Functions and Variables and Choices of Their
> Names" from the Example package manual: http://www.gap-system.org/Manuals/pkg/
> example/doc/chapA.html#X7DEACD9786DE29F1

Just on the off chance that this will become an FAQ, we might want to add it
to the [FAQ](https://github.com/gap-system/gap/wiki) to make it more
discoverable: I am sure that there is a lot of good documentation, but reality
is that people are very very lazy, so we'll have to make it very obvious (and
sometime maybe even replicate information a couple of times).
