### ISSUE TITLE
configure: using --with-julia should imply --with-gc=julia

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3290]
Alternatively, it could produce an error if `--with-gc=julia` was not given.

Rationale: People have been using `--with-julia=PATH` but did not realize they also need `--with-gc=julia`. While `--with-gc=julia` alone makes sense (it then tries to find a julia executable in your PATH), using `--with-julia=PATH` alone does not.

**Comment by ThomasBreuer** [comment]
I agree, and I am in favor of the implication from `--with-julia` to `--with-gc=julia`.
(And one should get an error in the case of `--with-julia` if an explicitly given `--with-gc` requests another garbage collector.)
