### ISSUE TITLE
testinstall may fail if `DirectoryHome` returns invalid

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3292]
Right now, `tst/testinstall/dir.tst` may fail if no valid home directory is set. Apparently this is the case when building packages in Guix, possibly also in other systems (Nix?). 

This test in particular fails, added by @ChrisJefferson 
```
gap> ForAll([DirectoryHome, DirectoryDesktop,DirectoryCurrent],
>           x -> (IsDirectoryPath(x()) and IsDirectory(x())) );
true
```
I can see why the test is there (to test if these three function return something "sensible), but now I wonder if that really is something we should be "enforcing" in our test suite? After all, it's in principle perfectly valid for a user to set HOME to an invalid value, for whatever reason.

I am really torn on this one... Should we do something? Or just leave it as is? I think Guix will just work around it (and I just learned that Nix already does), but I thought it'd be worthwhile for us to at least briefly think about it; even if we close this as "wontfix", it'll be something we can people at in the future ;-)

**Comment by ChrisJefferson** [comment]
What "invalid" return value do we get? I'd like to call the functions in the test suite, we could check we get a directory or fail, for example.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by fingolfin** [comment]
I think they simply set `HOME` to a non-existing directory.

My guess (which might be nonsense) is that this done so that one can make sure the build script does not accidentally put anything into there; plus, one can grep through the installed files for the name of that dir to see if HOME was accidentally hard coded in any generated files. This is valuable for reproducible builds.

**Comment by fingolfin** [comment]
As an experiment, I did this:
```
$ HOME=/foobar gap -b
gap> DirectoryHome();
dir("/foobar/")
gap>
```

**Comment by ChrisJefferson** [comment]
So I'm happy for that test to be adapted however is sensible... Does this pass either of Is Directory or Is Directory Path? (I'm away from a computer right now).

**Comment by andreas-enge** [comment]
I confirm that HOME is set to a non-existing directory, precisely /homeless-shelter. It would be nice if the test could be adapted or dropped.
