### ISSUE TITLE
Add elevation request to windows installer

### ISSUE THREAD

**Issue by JHahnHRO** [gap-system/gap#3299]
### Observed behaviour
When the GAP 4.10 installer .exe file is executed, it runs with the privileges of the current user. The user is then asked to input an install directory. When the current user's rights do not include write access to said directory, the install process fails early when some file is denied write access.
This does not happen when the .exe file is executed via right click -> "run as administrator".

### Expected behaviour
Ideal: The installer should check if it has write privileges in the given directory and ask for privilege elevation (i.e. the usual "you need admin rights for this" prompt by windows should show) if not.
At the very least the error message should be more useful than some generic "file XYZ could not be opened" message and include a "Please check if you have write access to the directory" or something similar that would make it clearer to the user how to fix the problem.

**Comment by fingolfin** [comment]
ping @alex-konovalov

**Comment by hulpke** [comment]
One problem is that we do not have any contributor with significant expertese in Windows programming. (Also, in an academic setting, it is hard to justify work on such purely technical issues.) If you have experience in how to resolve this we would welcome code suggestions.

**Comment by ChrisJefferson** [comment]
fixed in latest installer -- it prompts for admin access if you want to install globally
