### ISSUE TITLE
Displaying package loading errors in a CI environment

### ISSUE THREAD

**Issue by zickgraf** [gap-system/gap#3306]
For CI purposes I look for a way to disable banners and still display package loading errors (i.e. package not found, dependent package not found, dependent package not available with the required version) without displaying anything if there are no errors.

I would expect this to be be possible by setting
```
SetInfoLevel( InfoPackageLoading, PACKAGE_ERROR );
```
or

```
SetInfoLevel( InfoPackageLoading, PACKAGE_WARNING );
```

However, if I execute
```
SetInfoLevel( InfoPackageLoading, PACKAGE_WARNING );
LoadPackage( "PackageDependingOnNonExistentPackage" );;
```

with banners disabled, I get no output.

Is this the intended behaviour? Is there a good way to achieve my aim?

**Comment by fingolfin** [comment]
I don't see how this relates to banners. Here is what I get with banners ON; notice how with `PACKAGE_WARNING` it doesn't really give any useful information about what caused the failure, or how to resolve it (and that indeed seems to not match what the manual says); only with `PACKAGE_INFO` do I get that info:
```
gap> SetInfoLevel( InfoPackageLoading, PACKAGE_WARNING );
gap> LoadPackage("PackageDependingOnNonExistentPackage");
#I  PackageDependingOnNonExistentPackage package is not available. To see further details, enter
#I  SetInfoLevel(InfoPackageLoading,4); and try to load the package again.
fail
gap> SetInfoLevel( InfoPackageLoading, PACKAGE_INFO );
gap> LoadPackage("PackageDependingOnNonExistentPackage");
#I  PackageDependingOnNonExistentPackage: PackageAvailabilityInfo for version 1.9.4dev
#I  foobar: PackageAvailabilityInfo: no installed version fits
#I  PackageDependingOnNonExistentPackage: PackageAvailabilityInfo: dependency 'foobar' is not satisfied
#I  PackageDependingOnNonExistentPackage: PackageAvailabilityInfo: no installed version fits
fail
```

But that latter information is also available if banners are turned OFF via the `-b` command line option:
```
gap> SetInfoLevel( InfoPackageLoading, PACKAGE_WARNING );
gap> LoadPackage("PackageDependingOnNonExistentPackage");
fail
gap> SetInfoLevel( InfoPackageLoading, PACKAGE_INFO );
gap> LoadPackage("PackageDependingOnNonExistentPackage");
#I  PackageDependingOnNonExistentPackage: PackageAvailabilityInfo for version 1.9.4dev
#I  foobar: PackageAvailabilityInfo: no installed version fits
#I  PackageDependingOnNonExistentPackage: PackageAvailabilityInfo: dependency 'foobar' is not satisfied
#I  PackageDependingOnNonExistentPackage: PackageAvailabilityInfo: no installed version fits
fail
```


Anyway, so the short answer is: to achieve your aim, just disable banners and use `PACKAGE_INFO`.

That said, we probably should ensure that the `dependency 'foobar' is not satisfied` messages are printed with `PACKAGE_WARNING`, too.

**Comment by fingolfin** [comment]
See also PR #3322 in which I changed the "dependency 'foobar' is not satisfied" message to show up already on level PACKAGE_WARNING

**Comment by zickgraf** [comment]
> I don't see how this relates to banners.

With banners enabled and level `PACKAGE_ERROR` or `PACKAGE_WARNING` one at least gets a message if a package could not be loaded:
```
#I  PackageDependingOnNonExistentPackage package is not available. To see further details, enter
#I  SetInfoLevel(InfoPackageLoading,4); and try to load the package again.
```
With banners disabled one does not even know that there was a failure, which I think is unexpected.

> See also PR #3322

Thanks a lot, that should indeed solve my problem! Maybe the following lines should be raised to `PACKAGE_WARNING`, too, and some maybe even to `PACKAGE_ERROR`?
https://github.com/gap-system/gap/blob/6ba858a1cc2451d9972b06a6a257ef35b80afe06/lib/package.gi#L1514-L1515
https://github.com/gap-system/gap/blob/6ba858a1cc2451d9972b06a6a257ef35b80afe06/lib/package.gi#L780-L783
https://github.com/gap-system/gap/blob/6ba858a1cc2451d9972b06a6a257ef35b80afe06/lib/package.gi#L800-L802
https://github.com/gap-system/gap/blob/6ba858a1cc2451d9972b06a6a257ef35b80afe06/lib/package.gi#L993-L995
https://github.com/gap-system/gap/blob/6ba858a1cc2451d9972b06a6a257ef35b80afe06/lib/package.gi#L1514-L1515
https://github.com/gap-system/gap/blob/6ba858a1cc2451d9972b06a6a257ef35b80afe06/lib/package.gi#L1581-L1582

(Since I don't know about all possible errors during package loading this list might not be complete in any sense.)

**Comment by fingolfin** [comment]
> > I don't see how this relates to banners.
> 
> With banners enabled and level `PACKAGE_ERROR` or `PACKAGE_WARNING` one at least gets a message if a package could not be loaded:
> 
> ```
> #I  PackageDependingOnNonExistentPackage package is not available. To see further details, enter
> #I  SetInfoLevel(InfoPackageLoading,4); and try to load the package again.
> ```
> With banners disabled one does not even know that there was a failure, which I think is unexpected.

But you *do* learn about failure: it's the return value. If you are running this in an automated test, then your test setup should of course check the return value and handle it suitably (and e.g. print an error, and possibly exit GAP).

> 
> > See also PR #3322
> 
> Thanks a lot, that should indeed solve my problem! Maybe the following lines should be raised to `PACKAGE_WARNING`, too, and some maybe even to `PACKAGE_ERROR`?

A few of these messages *might* also qualify, but I don't think all of them do, as they are only fired in a situation that is not actually relevant to the (regular) user (who is not right now debugging a `PackageInfo.g` they just wrote).
Anyway, this code is super fiddly, so this would require some extensive analysis and fiddling. Don't expect a change here soon.


As it is, I really don't think the originally reported issue is one.

**Comment by zickgraf** [comment]
We have finished this discussion in person.
