### ISSUE TITLE
kernel/streams.tst fails on Windows in the master branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3309]
```
testing: /proc/cygdrive/C/gap-4.11.0/tst/testinstall/kernel/streams.tst
A########> Diff in /proc/cygdrive/C/gap-4.11.0/tst/testinstall/kernel/streams.t\
st:11
# Input is:
LOG_TO(TmpName());
# Expected output:
true
# But found:
Error, LogTo: cannot log to /tmp/gaptempfile.A2nfPr
########
########> Diff in /proc/cygdrive/C/gap-4.11.0/tst/testinstall/kernel/streams.t\
st:13
# Input is:
CLOSE_LOG_TO();
# Expected output:
true
# But found:
Error, LogTo: can not close the logfile
########
########> Diff in /proc/cygdrive/C/gap-4.11.0/tst/testinstall/kernel/streams.t\
st:28
# Input is:
INPUT_LOG_TO(TmpName());
# Expected output:
true
# But found:
Error, InputLogTo: cannot log to /tmp/gaptempfile.OGafpz
########
########> Diff in /proc/cygdrive/C/gap-4.11.0/tst/testinstall/kernel/streams.t\
st:30
# Input is:
CLOSE_INPUT_LOG_TO();
# Expected output:
true
# But found:
Error, InputLogTo: can not close the logfile
########
########> Diff in /proc/cygdrive/C/gap-4.11.0/tst/testinstall/kernel/streams.t\
st:45
# Input is:
OUTPUT_LOG_TO(TmpName());
# Expected output:
true
# But found:
Error, OutputLogTo: cannot log to /tmp/gaptempfile.WgAeUJ
########
########> Diff in /proc/cygdrive/C/gap-4.11.0/tst/testinstall/kernel/streams.t\
st:47
# Input is:
CLOSE_OUTPUT_LOG_TO();
# Expected output:
true
# But found:
Error, OutputLogTo: can not close the logfile
########
```

**Comment by stevelinton** [comment]
Looks like the real bug is in `TmpName` which should produce something that works in this setting (or error if there is no way to do that)

**Comment by alex-konovalov** [comment]
A solution would be to use `TmpNameAllArchs` instead of `TmpName`. It is defined in `lib/process.gi`:
```
InstallGlobalFunction( TmpNameAllArchs, function( )
    local filename, a;

    filename := TmpName( );
    if ARCH_IS_WINDOWS( ) then
        # replace leading /tmp/ by C:/WINDOWS/Temp/
        a := SplitString(filename, "/");
        a := a[Length(a)]; # is "/tmp/gaptempfile.kS4uyj", get rid of /tmp/ bit

        filename := Concatenation("C:/WINDOWS/Temp/", a);
    fi;

    return filename;
end);
```
Both of these are undocumented, and I remembered this because of the Windows release checklist at https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/RELEASE_CHECKLIST.md.

**Comment by ChrisJefferson** [comment]
You can't assume that's there the temp directory is. Users on machines which are controlled by a department won't be able to write there.

**Comment by alex-konovalov** [comment]
@ChrisJefferson that's where Windows keeps temporary files in Win 7 and in Win 10, and it works on Windows Jenkins slaves which were set up for me by the school, and where GAP is tested under a non-admin account. Even if there might be a chance that this will not work in some very non-standard set up (what will possibly indicate that there may be further problems with using that GAP installation), this will fix the test for a number of standard settings.

**Comment by ChrisJefferson** [comment]
You can't write to c:/windows/temp on multi-user machines (you can't in any of our department labs for example)

**Comment by alex-konovalov** [comment]
Apparently Windows can also use `%userprofile%\AppData\Local\Temp` - we may try to improve `TmpNameAllArchs` to use that, but that would be a separate PR, while #3326 will instantly fix problems with Windows tests, and should not be invalidated by future versions of `TmpNameAllArchs`.
