### ISSUE TITLE
Digraphs package included COUNT_TRUES_BLOCK from src/compiled.h

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#3312]
In the most recent Digraphs release, v0.15.0, `COUNT_TRUES_BLOCK` is included from GAP's `compiled.h`. This has now been moved into `bits_intern.h` in GAP's `master` branch, in particular this means that the newest version of Digraphs doesn't work in the GAP `master` branch. What should we do about this? Should we not be using `COUNT_TRUES_BLOCK`? (I'm speaking as someone who is pretty ignorant of what these header filesarer for, and why we need them in Digraphs, but @james-d-mitchell knows what it's all used for).

**Comment by james-d-mitchell** [comment]
The code for COUNT_TRUES_BLOCK was duplicated in Digraphs before 0.15.0 so I removed it. It will be easy to put it back, is there a reason it should be internal to GAP?

**Comment by fingolfin** [comment]
We can make it public again in GAP, I wasn't aware that Digraphs uses it, nor did our tests reveal it (probably because the tests run against a released version, and the change in Diagraphs is not yet in a releases?)

**Comment by fingolfin** [comment]
Hmm, but  is there a reason you are using `COUNT_TRUES_BLOCK` and not the more high level (and faster) `COUNT_TRUES_BLOCKS`? I.e.,
```patch
diff --git a/src/bitarray.h b/src/bitarray.h
index 6503e10..2bbe1fb 100644
--- a/src/bitarray.h
+++ b/src/bitarray.h
@@ -380,12 +380,7 @@ static inline uint16_t size_bit_array(BitArray const* const bit_array,
   DIGRAPHS_ASSERT(nr_bits <= bit_array->nr_bits);
   Block const*   blocks    = bit_array->blocks;
   uint16_t const nr_blocks = NR_BLOCKS_LOOKUP[nr_bits];
-  UInt           n         = 0;
-  for (uint16_t i = 0; i < nr_blocks; i++) {
-    Block const m = *blocks++;
-    n += COUNT_TRUES_BLOCK(m);  // COUNT_TRUES_BLOCK is defined by GAP
-  }
-  return n;
+  return COUNT_TRUES_BLOCKS(blocks, nr_blocks);
 }
 
 //! Set the bit array \p bit_array to be \c true in position INT_INTOBJ(o) - 1.
```

I am asking because a fix for `COUNT_TRUES_BLOCKS` is easier: I'd just export it as a non-inline function; this way, `COUNT_TRUES_BLOCK` could remain hidden in an internal header.

**Comment by wilfwilson** [comment]
Digraphs has used this since v0.15.0, which I released 7 days ago. However the new release of Digraphs was presumably not yet picked up by the time that your tests ran on the PR, which was unfortunate.

Hopefully James can answer your technical question. I really don’t know about it.

**Comment by james-d-mitchell** [comment]
Good question @fingolfin, there is a reason, I didn't know it existed until now. We can use that instead, and no need to re-expose `COUNT_TRUES_BLOCK` in #3313

**Comment by wilfwilson** [comment]
Although for that there’s still some change required to GAP because `COUNT_TRUES_BLOCKS` is also now in the new internal header

**Comment by fingolfin** [comment]
I believe this is fixed now; it certainly seemed to work fine when I just tried to compile the Digraphs master branch against the latest GAP master branch. However, I'd appreciate if @wilfwilson and/or @james-d-mitchell could double check.

**Comment by wilfwilson** [comment]
Thanks @fingolfin, yes this is all working properly now 🙂
