### ISSUE TITLE
bug in ClassPositionsOfLowerCentralSeries

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#3321]
Frieder Ladisch had reported the following bug:
```
gap> g:= SmallGroup( 3^5, 22 );;
gap> LowerCentralSeries(g);
[ C27 : C9, Group([ f3, f5 ]), Group([ f5 ]), Group([ <identity> of ... ]) ]
gap> ct:= CharacterTable(g);;
gap> ClassPositionsOfLowerCentralSeries(ct);
[ [ 1 .. 35 ], [ 1, 4, 6, 12, 15 ] ]
```
Looking at the code, I found related issues:

- `ElementaryAbelianSeries` runs into an error if the argument is a nonsolvable group.
  According to the documentation, `fail` should be returned.
  I think the function should be adjusted to the documentation.
  (The corresponding function `ClassPositionsOfElementaryAbelianSeries` returns `fail`
  for character tables of nonsolvable groups.)
- `UpperCentralSeries` returns a *descending* series,
  whereas `ClassPositionsOfUpperCentralSeries` returns an *ascending* series.
  The documentation of `UpperCentralSeries` coincides with the return value.
  Here I am not sure what to do.
- In order to run a reasonable amount of tests (on small groups) that compare the
  `ClassPositionsOf...` functions with the corresponding functions for groups,
  it makes sense to improve the code of some `ClassPositionsOf...` methods.

I will provide a pull request.

**Comment by fingolfin** [comment]
Fixed by #3347
