### ISSUE TITLE
Why does TmpNameAllArchs exist / why isn't its code part of TmpName

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3328]
This is the code for this function:
```gap
InstallGlobalFunction( TmpNameAllArchs, function( )
    local filename, a;

    filename := TmpName( );
    if ARCH_IS_WINDOWS( ) then
        # replace leading /tmp/ by C:/WINDOWS/Temp/
        a := SplitString(filename, "/");
        a := a[Length(a)]; # is "/tmp/gaptempfile.kS4uyj", get rid of /tmp/ bit

        filename := Concatenation("C:/WINDOWS/Temp/", a);
    fi;

    return filename;
end);
```

So, why is this Windows specific code not simply inside of `TmpName`? Also, I think @ChrisJefferson recently mentioned that we should use `/proc/cygdrive/c/BLA` instead of `C:\BLA` (and using `C:/BLA`, with forward slashes, seems even weirder to me).

For the record, this function was added in the following commit:
```
commit 51d60ddd9735445823efafb226070cc6025bdc2e
Author: Andreas Distler <adistler@fc.ul.pt>
Date:   2011-06-15 16:48:49 +0000

    introduced TmpNameAllArchs and replaced TmpName in the method of Process for
    input and/or output streams by it to make Process work under Windows,
    changed documentation of DirectoryTemporary removing claims that the function
    might use a string <hint> given as argument and that temporary directories
    might be removed upon garbage collection. AD
```

Ping to @alex-konovalov who might know more

**Comment by ChrisJefferson** [comment]
So, in the long term (I realise I've been talking about this for a while) we should access external programs via bash, so we can use /proc/cygdrive/c/BLA. At the moment if we tried to pass a c:\bla to 'cmd' it would break (but I don't imagine we'd do that very often).

For many users (including on for example our departmental machines) they can't read/write c:/windows/temp. Someone could look up how you are "supposed" to get the temp directory.

**Comment by alex-konovalov** [comment]
Apparently Windows can also use `%userprofile%\AppData\Local\Temp` where the user should have write access.
