### ISSUE TITLE
Windows: Errors in teststandard/processes/streamio.tst in the master branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3332]
See for example [this Jenkins build](https://gap-ci.cs.st-andrews.ac.uk/job/GAP-master-windows-test/316/consoleFull) (St Andrews only)
```
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-master-windows-\
build/GAP-master-snapshot/tst/teststandard/processes/streamio.tst:28
# Input is:
ForAny([1..10], x -> checkPartialRead(write, ReadLine, "aaa", "aaa\n"));
# Expected output:
true
# But found:
Error, Missing second
########
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-master-windows-\
build/GAP-master-snapshot/tst/teststandard/processes/streamio.tst:30
# Input is:
ForAny([1..10], x -> checkPartialRead(write, ReadLine, "aaa", "aaa"));
# Expected output:
true
# But found:
Error, Missing second
########
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-master-windows-\
build/GAP-master-snapshot/tst/teststandard/processes/streamio.tst:32
# Input is:
ForAny([1..10], x -> checkPartialRead(write, ReadAll, "aaa", "aaa\n"));
# Expected output:
true
# But found:
Error, Missing second
########
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-master-windows-\
build/GAP-master-snapshot/tst/teststandard/processes/streamio.tst:38
# Input is:
c := ReadByte(process);
# Expected output:
97
# But found:
fail
########
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-master-windows-\
build/GAP-master-snapshot/tst/teststandard/processes/streamio.tst:40
# Input is:
c := ReadByte(process);
# Expected output:
98
# But found:
fail
########
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-master-windows-\
build/GAP-master-snapshot/tst/teststandard/processes/streamio.tst:42
# Input is:
c := ReadByte(process);
# Expected output:
99
# But found:
fail
########
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-master-windows-\
build/GAP-master-snapshot/tst/teststandard/processes/streamio.tst:44
# Input is:
c := ReadByte(process);
# Expected output:
100
# But found:
fail
########
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-master-windows-\
build/GAP-master-snapshot/tst/teststandard/processes/streamio.tst:46
# Input is:
c := ReadByte(process);
# Expected output:
101
# But found:
fail
########
########> Diff in /proc/cygdrive/C/Users/jenkins/workspace/GAP-master-windows-\
build/GAP-master-snapshot/tst/teststandard/processes/streamio.tst:48
# Input is:
c := ReadByte(process);
# Expected output:
102
# But found:
fail
########
```

**Comment by alex-konovalov** [comment]
Still happens - e.g. in [St Andrews only link](https://gap-ci.cs.st-andrews.ac.uk/job/GAP-master-windows-test/334/console) tonight. This blocks GAP 4.11 and needs addressing.

**Comment by alex-konovalov** [comment]
Still happens - e.g. in [St Andrews only link](https://gap-ci.cs.st-andrews.ac.uk/job/GAP-master-windows-test/395/console) and thus blocks GAP 4.11.

**Comment by embray** [comment]
What's an easy way to run just the tests in `tst/teststandard/processes/streamio.tst` so I can try it myself?

**Comment by alex-konovalov** [comment]
Test("C:/gap-path-to-your-installation/tst/teststandard/processes/streamio.tst");

**Comment by embray** [comment]
I think the problem is just with the test, and it's not too surprising it fails in CI.  I can't reproduce it manually, so far.

It might help to debug if the like `if ReadLine(process) <> secondread then Error("Missing second"); fi;` also output what it *did* read, because otherwise it just says "Missing second".

**Comment by embray** [comment]
Nevermind, I can recreate the same failures if I modify `slowwrite.sh` to just `exit -11` (for example).  It's possible that this test is suffering from the same fork failures that were discussed e.g. on #2890?

**Comment by fingolfin** [comment]
@embray yes, that is possible; which is why I wonder whether my PR #3513 might help with this.

**Comment by alex-konovalov** [comment]
As I wrote in #3513, it does not fix errors from this issue.

**Comment by wilfwilson** [comment]
Note that this test file, `teststandard/processes/streamio.tst`, was only added in 28th January 2019 in #3236. In particular, it was added after GAP 4.10.

I think it is possible, perhaps even likely, that this file would have also failed in GAP 4.10. (Although I have no way of testing this). I propose that we simply disable this test on Windows and proceed with a GAP 4.11 release, which contains many benefits to users on all platforms.

**Comment by ChrisJefferson** [comment]
I also can't get this test to fail, it works fine on both 32-bit and 64-bit

Are you running on a machine with no 'sh'? That would explain the failure.

**Comment by alex-konovalov** [comment]
@ChrisJefferson yes, this is on a cygwin-free machine where the GAP win-zip archive is tested. I agree with @wilfwilson to disable it on Windows. I've submitted PR #3637 to disable it.

**Comment by embray** [comment]
In principle you could also ship bash, and its minor dependencies, with GAP--that can be nice for users too because then they get a bash shell to start gap from :)  But I agree it's probably overkill just to include it for one test.

**Comment by ChrisJefferson** [comment]
longer term, I want to distribute a full cygwin base system (which is small compared to GAP), so lots of things (having a shell, terminfo, temp directories, home directories) get set up correctly and automatically. This would also help running packages which themselves expect a shell.

**Comment by embray** [comment]
@ChrisJefferson The Sage Windows builder might provide some help with that: https://github.com/sagemath/sage-windows

I'm currently not very happy with a lot of how it's structured and makefile is a complete mess.  But it does represent a number of learned lessons.

It also creates two separate Cygwin installs: One for building, and then a smaller one representing what actually gets distributed for runtime.  Though more and more the two are coming into parity as users demand to be able to install optional packages that require compilation anyways.
