### ISSUE TITLE
Gap 4.10.0 Repsn crashes on A5 group

### ISSUE THREAD

**Issue by jorisvergeest** [gap-system/gap#3333]
Unlike earlier GAP versions, when the following is entered into GAP 4.10.0:

 >LoadPackage("repsn");
> g := SmallGroup(60,5);
> gen := GeneratorsOfGroup(g);
> charTab := Irr(g);
> rep := gen[1]^IrreducibleAffordingRepresentation(charTab[2]);

the program crashes (I tried on W10 and a Unix machine).

Detailed output:

gap> Read("d:/joris/gap/a5.gap");

Repsn for Constructing Representations of Finite Groups
                  Version 3.0.2

                    Written by
                 Vahid Dabbaghian

Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `*' on 2 arguments at /proc/cygdrive/C/gap-4.10.0/lib/methsel2.g:250 called from
u * GeneratorsOfGroup( S[i] ) at /proc/cygdrive/C/gap-4.10.0/pkg/repsn/gap/repsn.g:1390 called from
func( C[i] ) at /proc/cygdrive/C/gap-4.10.0/lib/coll.gi:665 called from
List( Co, function ( u )
      return u * GeneratorsOfGroup( S[i] );
  end ) at /proc/cygdrive/C/gap-4.10.0/pkg/repsn/gap/repsn.g:1390 called from
PerfectRepresentation( g, c[1], SpecialCoversData ) at /proc/cygdrive/C/gap-4.10.0/pkg/repsn/gap/repsn.g:49 called from
<function "IrreducibleAffordingRepresentation">( <arguments> )
 called from read-eval loop at d:/joris/gap/a4.gap:7
type 'quit;' to quit to outer loop
brk>

**Comment by dimpase** [comment]
This is fixed in the new repsn version available at https://github.com/gap-packages/repsn

**Comment by dimpase** [comment]
```
 ┌───────┐   GAP 4.10.0 of 01-Nov-2018
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64
 Configuration:  gmp 6.1.2, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.1, Alnuth 3.1.0, AtlasRep 1.5.1, AutoDoc 2018.09.20, AutPGrp 1.10, CRISP 1.4.4, Cryst 4.1.18, CrystCat 1.1.8, CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.2, IRREDSOL 1.4, LAGUNA 3.9.0, 
             Polenta 1.3.8, Polycyclic 2.14, PrimGrp 3.3.2, RadiRoot 2.8, ResClasses 4.7.1, SmallGrp 1.3, Sophus 1.24, SpinSym 1.5, TomLib 1.2.7, TransGrp 2.0.4, utils 0.59
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> LoadPackage("repsn");
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Loading  Repsn 3.1.0 (Constructing representations of finite groups)
by Vahid Dabbaghian (http://www.sfu.ca/~vdabbagh).
Homepage: https://gap-packages.github.io/repsn/
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
true
gap> g := SmallGroup(60,5);
Group([ (1,2,3,4,5), (1,2,3) ])
gap> gen := GeneratorsOfGroup(g);
[ (1,2,3,4,5), (1,2,3) ]
gap> charTab := Irr(g);
[ Character( CharacterTable( Alt( [ 1 .. 5 ] ) ), [ 1, 1, 1, 1, 1 ] ), Character( CharacterTable( Alt( [ 1 .. 5 ] ) ), [ 3, 0, -1, -E(5)-E(5)^4, -E(5)^2-E(5)^3 ] ), Character( CharacterTable( Alt( [ 1 .. 5 ] ) ),
  [ 3, 0, -1, -E(5)^2-E(5)^3, -E(5)-E(5)^4 ] ), Character( CharacterTable( Alt( [ 1 .. 5 ] ) ), [ 4, 1, 0, -1, -1 ] ), Character( CharacterTable( Alt( [ 1 .. 5 ] ) ), [ 5, -1, 1, 0, 0 ] ) ]
gap> rep := gen[1]^IrreducibleAffordingRepresentation(charTab[2]);
[ [ 0, 0, -1 ], [ E(5)^2+E(5)^3, 2*E(5)^2+2*E(5)^3, E(5)+2*E(5)^2+2*E(5)^3+E(5)^4 ], [ 1, -E(5)-2*E(5)^2-2*E(5)^3-E(5)^4, -E(5)-2*E(5)^2-2*E(5)^3-E(5)^4 ] ]
gap> 
```
this is how it works with the new version.

**Comment by jorisvergeest** [comment]
That's great news, thank you,

Joris

________________________________________
