### ISSUE TITLE
I've installed gap using recommended gap-4.10.0.exe but it does not start at all

### ISSUE THREAD

**Issue by vadrer** [gap-system/gap#3336]
### Observed behaviour

I followed installation instruction at https://www.gap-system.org/Download/index.html
this is on Windows 10 version 1803 build 17134.590
I choose installation path D:\apps\gap-4.10.0

when I execute gap.exe I see message box with a title "gap.exe - entry point not found" and message "the procedure entry point __assert_func could not be located in the dynamic library d:\apps\gap-4.10.0\gap.exe

the only button is "OK", when I press it - program terminates

### Expected behaviour

I expect some output like this:
```
 ┌───────┐   GAP 4.8.8, 20-Aug-2017, build of 2018-02-19 20:02:33 (UTC)
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: i386-linux-gnu-gcc-default32
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: small 2.1, small2 2.0, id2 3.0, trans 1.0, prim 2.1
 Packages:   Alnuth 3.1.0, AtlasRep 1.5.1, AutPGrp 1.8, CTblLib 1.2.2, GAPDoc 1.6.1, Polycyclic 2.11, TomLib 1.2.6
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap>
```

### Copy and paste GAP banner (to tell us about your setup)

no banner
![bmp0001](https://user-images.githubusercontent.com/122038/54182557-e9ddb780-44b2-11e9-9dd7-51866bbb311f.png)

**Comment by alex-konovalov** [comment]
GAP can not be started this way. Please use `C:\apps\gap-4.10.0\bin\gap.bat` to start GAP in mintty shell. You can customise that shell as you ike, for example, set up font and colours as explained in https://github.com/gap-system/GapWWW/issues/100. 

The GAP installer creates a shortcut for `C:\apps\gap-4.10.0\bin\gap.bat` in the Windows applications menu.

If you need to start it in Windows command shell, use `C:\apps\gap-4.10.0\bin\gapcmd.bat`. This is less convenient for interactive use, but may be needed for some automated scenarios.

**Comment by vadrer** [comment]
thank you!
