### ISSUE TITLE
ˆ-key does not work on OS X out of the box

### ISSUE THREAD

**Issue by wucas** [gap-system/gap#3346]
### Observed behaviour
On the newest OS X (Mac OS Mojave 10.14.3) with an international english keyboard layout the ˆ-key does not work. If I press ^ and rightarrow it outputs the following:
```
gap> ^
      ^
```
### Expected behaviour
Being able to use ^ as in other programs.
### Copy and paste GAP banner 
```
 ┌───────┐   GAP 4.10.1 of 23-Feb-2019
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin18.2.0-default64-kv3
 Configuration:  gmp 6.1.2
 Loading the library and packages ...
 Packages:   AClib 1.3.1, Alnuth 3.1.0, AtlasRep 1.5.1, AutoDoc 2019.02.22, AutPGrp 1.10, Browse 1.8.8, Carat 2.2.3, CRISP 1.4.4, Cryst 4.1.18, CrystCat 1.1.8, CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, 
             GAPDoc 1.6.2, IO 4.5.4, IRREDSOL 1.4, LAGUNA 3.9.2, Polenta 1.3.8, Polycyclic 2.14, PrimGrp 3.3.2, RadiRoot 2.8, ResClasses 4.7.1, SmallGrp 1.3, Sophus 1.24, SpinSym 1.5, TomLib 1.2.7, 
             TransGrp 2.0.4, utils 0.61
```

As @ChrisJefferson pointed out to me installing readline via `brew -install readline` and recompiling GAP solves the problem. This is explained in the `README.md` in the section about using the development version of GAP. In the `INSTALL.md` this is not mentioned in section 13 about OS X. But interestingly the problem is mentioned in section 10 "If things go wrong" as a problem specific to windows where apparently no workaround is available. 

As a workaround I'd suggest to add the same explanation as in the `README.md` to section 13 of `INSTALL.md` and to put the problem as it is mentioned in section 11 out of the "only windows" part and mention the workaround for OS X there. That way it is easier to find the solution or not run into the problem in the first place.

**Comment by fingolfin** [comment]
I believe this has been settled by #3348?

**Comment by alex-konovalov** [comment]
Looks so!
