### ISSUE TITLE
Add ShowUsedInfoClasses

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#3379]
This was suggested at GAP Days in Halle , and I think it's a good idea to find out what Info levels exist, and which algorithms they will are used in. I thought I'd suggest it before I wrote it, just in case anyone had any deep opinions. In an experiment, here is the suggested documentation :)

ShowUsedInfoClasses( bool )

Called with argument 'true', ShowUsedInfoClasses makes GAP print the InfoClass and level of any executed Info statement. Calling ShowUsedInfoClasses with the argument 'false' stops this information being printed.

Each level of each InfoClass is only printed once. The list of printed InfoClasses and levels is reset by calling ShowUsedInfoClasses(true).

**Comment by fingolfin** [comment]
I am not sure I understand; in which setting would this be useful? Is the idea that one wants to figure out which InfoClasses might affect a certain command, so then before running the command, one would do `ShowUsedInfoClasses(true);`, then execute the command, and watch the InfoClasses being printed?

I feel this kind of information should be part of the documentation, and perhaps even a brief example (could be fake).

**Comment by ChrisJefferson** [comment]
Good plan:

```
gap> ShowInfoClasses(true);
gap> Intersection(MatthiewGroup(23), MatthiewGroup(23)^(1,2));;
#I Would print Info with SetInfoLevel(InfoBckt, 2)
#I Would print Info with SetInfoLevel(InfoBckt, 1)
#I Would print Info with SetInfoLevel(InfoGroup, 1)
#I Would print Info with SetInfoLevel(InfoPermGroup, 1)
#I Would print Info with SetInfoLevel(InfoPermGroup, 1)
#I Would print Info with SetInfoLevel(InfoPerformance, 2)
gap> ShowInfoClasses(false);
```

**Comment by wilfwilson** [comment]
I take it that the actual info statements will still get printed, too? (of course, only those with a low enough level).

**Comment by ChrisJefferson** [comment]
Yes, this won't effect the outputting of Info statements, just let you know what could have been printed.

**Comment by alex-konovalov** [comment]
It would require to implement some bookkeeping, but could make the output less verbose: do not repeat same combinations of the class and level, they will not add anything new. The example above has this line twice

    #I Would print Info with SetInfoLevel(InfoPermGroup, 1)

while one line would suffice.

**Comment by ChrisJefferson** [comment]
Woops, that was a cut+paste mistake, I haven't actually written the code yet, and meant to have no repeats :)
