### ISSUE TITLE
`last` can be used as a variable without a warning

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#338]
You can do the following in GAP:

```
gap> last := x -> x;
```

without an error being given. Is this the correct behaviour? 

Another example:

```
gap> 1;
1
gap> 2;
2
gap> last2 := 10;
10
gap> last2;
2
```

I think this could be rather confusing for non-expert users of GAP who are perhaps not aware that `last`, `last2`, and `last3` are "special" variables.

**Comment by fingolfin** [comment]
The behavior is correct, but perhaps not desirable. We could make those variables read-only, but then the code modifying them needs to be updated.

Of course users could then still modify them, it's just more work. Indeed:
```
gap> MakeReadWriteGVar("fail");
gap> fail:=1;; fail;
1
gap> MakeReadWriteGVar("infinity");
gap> infinity:=42;; infinity;
42
```

**Comment by stevelinton** [comment]
I would support these being ReadOnly globals. While people can still modify them if they have a reason to, it would reduce the risk of accidentally overwriting them, or having your own value overwritten by the system. The same would presumably apply to ~ and time.

**Comment by ChrisJefferson** [comment]
This would break demo.g, and packages which cut+pasted it, but it would be easy to add an explicit "clearLasts" function to replace their usage.

**Comment by fingolfin** [comment]
Indeed, demo.g should be rewritten anyway; I greatly dislike that it tries to "emulate" the main loop, including the `last`/`last2`/`last3` variables and `time`. If we could refactor the code in a way that these things are done in a central place, then future change to this area would be easier. 
The mere fact that people have to copy & edit it for their packages indicates something could be improved; and lastly the dreaded use of `SuPeRfail` should be gotten rid of ... ;-).

Note that `Shell()` in gap.c is the other place modifying these. And the code for `MakeReadOnlyGlobal` currently explicitly does this:
```
    if name in ["time", "last", "last2", "last3", "~"] then
        Error("Making ",name," read-only is not a good idea!");
    fi;
```
