### ISSUE TITLE
testinstall.g does not finish in a thread

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#339]
We have discussed this with @ChrisJefferson, so just to document and save others' time from reporting. When you do

```
task:=RunTask(Read,"tst/testinstall.g"); TaskResult(task);
```

it now runs till the end, then displays total and hangs forever.

**Comment by ChrisJefferson** [comment]
The real issue here is `TaskResult` hangs if the thread running the task exits. Not sure if there is a sensible fix for this.

**Comment by alex-konovalov** [comment]
@ChrisJefferson thanks - just to confirm that the solution that you've suggested by email works:

* for testinstall.g

```
task := RunTask(->TestDirectory( Filename( DirectoriesLibrary( "tst" ), "testinstall" ), rec( testOptions := rec(compareFunction := "uptowhitespace") ) )); QUIT_GAP(TaskResult(task);
```

* for teststandard.g

```
task := RunTask(->TestDirectory( [Filename( DirectoriesLibrary( "tst" ), "testinstall" ), Filename( DirectoriesLibrary( "tst" ), "teststandard" )], rec( testOptions := rec(compareFunction := "uptowhitespace") ) )); QUIT_GAP(TaskResult(task);
```
