### ISSUE TITLE
GAP runs out of memory where GASMAN("collect") would free enough memory to continue

### ISSUE THREAD

**Issue by RussWoodroofe** [gap-system/gap#3396]
GAP can break with an out-of-memory error when a GASMAN("collect") would free enough for it to continue.

I've made some short test code which illustrates the problem

    permanent:=[];
    oom:=function()
    local i,j, tmp;
    
    i:=0;
    while true do
      i:=i+1;
      permanent[i]:=1;
      for j in [1..10] do
        tmp:=Maximum(CoefficientsQadic(j,11));
      od;
    od;
    end;

Running `oom();` on a GAP instance with a low -o (such as "-o 128m") will quickly run out of memory.  Issuing a `GASMAN("collect"); return;` will allow it to continue for a time (although of course it will eventually run out of memory, being that that's what the code is designed to do. :-) )  The memory information automatically given to Gap.app seems to be inaccurate after the explicit invocation of garbage collection.  (I could investigate the details further if it were of interest.)

The issue arose in the context of a non-toy program which does something similar to the above (slowly grows a big array, meanwhile making computations that use memory).  The above was tested on GAP 4.10.0 with Gap.app under macOS.  Similar behavior was observed with the non-toy program on GAP 4.7.9 under Ubuntu.  I've also had similar problems with out-of-memory errors in the past.  

I can share my non-toy program on request.

**Comment by RussWoodroofe** [comment]
@ChrisJefferson asked off github for code that would finish with GASMAN("collect") calls, but not without.  The following modification of the above example does so on my system (macOS, GAP 4.10.0) with "-o 128m"
    permanent:=[];

    oom:=function()
    local i,j, tmp;

    i:=0;
    while i < 3*10^6 do
      i:=i+1;
      permanent[i]:=1;
      for j in [1..10] do
        tmp:=Maximum(CoefficientsQadic(j,11));
      od;
      if i mod 10^4 = 0 then
    #    GASMAN("collect");
      fi;
    od;
    end;
This will complete with the GASMAN line uncommented, and will break at around i=2*10^6 as is.  (You might need to slightly adjust the maximum value of i, depending on specifics of your system.)

**Comment by fingolfin** [comment]
I think this is an intentional design choice, balancing performance with memory usage: at some point, the GC has to decide that it'd be worth it to grow the heap. If you instead try to always perform a full GC when you fill up the existing heap, then you can run into pathologically slow settings: like, suppose the heap is full but one 16 byte object could be collected; and now you ask for 16 bytes. Then you have GC the full heap; it'll free up 16 bytes, you make your allocation, and you are back to square one. Now imagine this repeats in a loops -- it would be abysmally slow. So it's better to insist on the heap having some "breathing room", so that we don't quite *always* have to perform a GC.

BTW you write:
> Issuing a `GASMAN("collect"); return;` will allow it to continue for a time

Note that just doing `return;` will also allow it to continue for a time -- because GAP only shows you that break prompt *after* already having grown the heap (it has to, as it needs some memory to show the break prompt....

So I get this:
```
$ ./gap -o 128m -b
gap> permanent:=[];
[  ]
gap>
gap> oom:=function()
> local i,j, tmp;
>
> i:=0;
> while i < 3*10^6 do
>   i:=i+1;
>   permanent[i]:=1;
>   for j in [1..10] do
>     tmp:=Maximum(CoefficientsQadic(j,11));
>   od;
>   if i mod 10^4 = 0 then
> #    GASMAN("collect");
>   fi;
> od;
> end;
function(  ) ... end
gap> oom();
Error, reached the pre-set memory limit
(change it with the -o command line option) in
  tmp := Maximum( CoefficientsQadic( j, 11 ) ); at *stdin*:11 called from
<function "oom">( <arguments> )
 called from read-eval loop at *stdin*:18
you can 'return;'
brk> return;
gap>
```

**Comment by RussWoodroofe** [comment]
@fingolfin, you've convinced me that this one should be closed without change, and you can go ahead and do so (unless there's some other reason to leave it open).  GAP's memory management is sometimes a bit unexpected to me, but this particular report probably does not identify a real problem.

**Comment by dimpase** [comment]
Incidentally I wonder how to inspect the memory limits from the current GAP session, or via libgap.

I am aware of `GasmanLimits()`, but it does not tell you, say, whether GAP was invoked with `-s `, and if yes, then with which value of `-s `.

**Comment by fingolfin** [comment]
@dimpase best to ask such question on the forum, slack, or an issue of their own, than to tack them to a completely different issue... (which in this case also should have been closed some time ago)
```
gap> GAPInfo.CommandLineOptions.s;
"4g"
```
