### ISSUE TITLE
problem with strictly sorted inhomogeneous lists

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#3398]
The following happens in the current master branch as well as in some released versions of GAP.

```
gap> l:= [ 1, Z(2) ];;
gap> SetIsSSortedList( l, true );
Error, filter not possible for list (plain,dense,nhom)
not in any function at *stdin*:10
type 'quit;' to quit to outer loop
brk>
```
This is strange if one looks at the following.
``` 
gap> 1 < Z(2);
true
gap> l:= [ 1, Z(2) ];;
gap> HasIsSSortedList( l );
false
gap> IsSSortedList( l );
true
gap> HasIsSSortedList( l );
true
```
The second piece of code shows that GAP regards the list as strictly sorted,
and also stores the filter.

Here is a situation --in the master branch-- where one runs into trouble because of the error.
Note that `Filtered` assumes that its result is strictly sorted whenever the argument is strictly sorted, and wants to apply this knowledge.
```
gap> l:= [ 1, Z(2) ];;
gap> IsSSortedList( l );
true
gap> Filtered( l, IsObject );
Error, filter not possible for list (plain,dense,nhom) in
  SetIsSSortedList( res, true ); at .../gapmaster/gap/lib/coll.gi:1380 called from 
<function "Filtered">( <arguments> )
 called from read-eval loop at *stdin*:15
type 'quit;' to quit to outer loop
brk> 
```

**Comment by fingolfin** [comment]
This issue is already present in GAP 4.4.12, so I'd argue it was intentional. Of course we are free to revise this. But it's definitely not a recent regression.

**Comment by ChrisJefferson** [comment]
I think (I'm guessing pre-history) there was a time when "Sets" were supposed to be homogeneous, but now we don't require that any more. Certainly I think #3401 fixes it, and doesn't cause (I think) other problems.

**Comment by ThomasBreuer** [comment]
I do not understand @fingolfin 's comment.
It cannot be intentional that on the one hand, GAP can find out with `IsSSortedList` that a given list is sorted, and then store the filter, but on the other hand, GAP refused to set the filter via `SetIsSSortedList`.
Either inhomogeneous lists should never get the filter `HasIsSSortedList`, or `SetIsSSortedList` should be admissible for inhomogeneous lists.
