### ISSUE TITLE
DirectoryHome() not equals to Directory("~") on Windows

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#340]
New diff in nightly tests after some recent merge:

```
########> Diff in /cygdrive/c/Users/jenkins/workspace/GAP-dev-windows-test/GAP\
-git-snapshot/tst/testinstall/dir.tst, line 11:
# Input is:
DirectoryHome() = Directory("~");
# Expected output:
true
# But found:
false
########
```

BTW, it would be also good to unify the output here and print the path, filename and line number as `......./GAP-git-snapshot/tst/testinstall/dir.tst:11`. I think this is somewhere in `Test`.

**Comment by fingolfin** [comment]
Interesting, what is GAPInfo.UserHome on Windows?

**Comment by alex-konovalov** [comment]
@fingolfin on Windows, GAPInfo.UserHome has the form "/cygdrive/c/Users/accountname"

**Comment by ChrisJefferson** [comment]
What's `Directory("~")` ?

**Comment by aodabas** [comment]
gap> DirectoryHome() = Directory("~");
false
gap> Directory("~");
dir("/cygdrive/c/Users/accountname/")
gap> DirectoryHome();
dir("/cygdrive/c/Users/accountname/Documents/")
gap> GAPInfo.UserHome;
"/cygdrive/c/Users/accountname/"

**Comment by alex-konovalov** [comment]
This is exactly what's happening in the latest nightly build:

```
gap> DirectoryHome();
dir("/cygdrive/c/Users/jenkins/My Documents/")
gap> Directory("~");
dir("/cygdrive/c/Users/jenkins/")
gap> GAPInfo.UserHome;
"/cygdrive/c/Users/jenkins/"
```

So they are both directory objects, but for different directories.

**Comment by fingolfin** [comment]
It would be trivial to resolve this -- the only problem is to decide which one is the "correct" value. I am tempted to say that the output of `GAPInfo.UserHome` is, but then somebody (@hulpke?) spent quite some effort to make `DirectoryHome` return the Windows documents folder.

(BTW, if we keep that code, we really should rewrite `DirectoryHome` and `DirectoryDesktop` (and maybe more...) to *not* hardcode the names of these directories; rather, we should call the relevant Windows APIs for retrieving the proper paths (this requires some kernel code, but relatively straight forward; I'd offer to write it, except that I am not a windows user and have no Windows available, so I'd have to create a VM...)

**Comment by hulpke** [comment]
Yes, my hack was always intended only until someone would figure out how to do this properly using the Windows API (which I think requires accessing the Registry).

The reason for the `My Documents' folder was that I'm not sure whether the normal user folder is guaranteed to be user writeable.

**Comment by dimpase** [comment]
@alex-konovalov in your tests, how much of Cygwin is installed on the host? The results might differ in the "real" case, i.e. in the minimal setup, with cygwin1.dll, and nothing else, the path /cygdrive/c/Users/accountname/ won't even exist, as it is created during a "full" Cygwin installation.

**Comment by ChrisJefferson** [comment]
will be fixed in new cygwin installer

**Comment by ChrisJefferson** [comment]
fixed
