### ISSUE TITLE
Try harder to use the correct indefinite article (a/an) in messages to the user

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#3400]
Sorry that this is a vague issue, perhaps the scope should be narrowed, feel free to edit this to something more actionable. But I wanted to make an issue while I still remembered. Some messages to the user in GAP, such as the following one (produced by `RequireArgumentEx`), use the wrong article:
https://github.com/gap-system/gap/blob/bd34ff4d5f54789fef7ff17faeae75649ce441c6/tst/testinstall/bitfields.tst#L63
To be clear, 'a empty' should be 'an empty'. Although it's not a huge problem, it still doesn't give the best impression of GAP, so I think we should attempt to improve the situation.

@fingolfin suggested a (partial?) solution in [a comment on](https://github.com/gap-system/gap/pull/3394/files#r272914689) #3994. What does anyone think? I can think of the following steps:
* Identify where this might occur in GAP (Perhaps `RequireArgument` is the only place where this happens now? @fingolfin said that he's been trying to solve this problem).
* Decide how far we are willing to go to choose the most appropriate article.
* Implement that.

**Comment by ChrisJefferson** [comment]
Looking around, there are quite a few place where we print "a %s", where %s is set to TNAM_OBJ (usually, but not always as part of a "(not a %s)".

Therefore I'm tempted to suggest a new function, TNAM_OBJ_WITH_ARTICLE (that's a horrible name), which returns TNAMs with the article included.

**Comment by ChrisJefferson** [comment]
A better option might be to add a modifier to '%s', say '%as', which makes it attach 'a/an' as a prefix.

Chris

**Comment by wilfwilson** [comment]
Yes, perhaps introducing `%as` and putting the logic behind there would be a nice solution.

**Comment by fingolfin** [comment]
I am not so sure about `%as` being a good solution at this point. Perhaps if we identify more places where this would be used. But note that providing a fully generic solution that can be used to print arbitrary stuff is highly non-trivial, as there are a ton of exceptions for the use of "a" vs. "an". To get an idea of what is needed, see e.g. here: <https://github.com/rossmeissl/indefinite_article/blob/master/lib/indefinite_article.rb>

Whereas for TNUMs, we have a fixed list of <= 256 entries, and we only need to make sure the articles are correct for those. That's a much simpler problem.

So I'd really start with that, and if we then determine that we really need article inflection in more places, *then* we can look into a more generic solution.

**Comment by fingolfin** [comment]
In `master` we are down to four occurrences of `(not a %s)` in the kernel, so this is mostly resolved now, I think.

**Comment by wilfwilson** [comment]
I had a look at the remaining ones, and I think I'm happy with closing this issue. (I didn't create the issue as "Always use the correct indefinite article"!)

Thanks for your work on this Max.
