### ISSUE TITLE
GAP 4.11 release notes

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3407]
I have created the following Wiki page: https://github.com/gap-system/gap/wiki/GAP-4.11-release-notes. 

The query there returns 146 PRs to be processed (note that after we will create stable-4.11 branch, another query must be added). 

Please help by going through the list of PRs as explained in the instructions on that Wiki page.

When we will be ready, I will convert the Wiki page into a new chapter in the Changes manual.

**Comment by DominikBernhardt** [comment]
Imho they are complete apart from 1 Pr which @fingolfin will fix today.

**Comment by fingolfin** [comment]
We should close this as soon as `stable-4.11` has been branched, and we really resolved all the PRs in the query.

**Comment by alex-konovalov** [comment]
The branching of `stable-4.11` is imminent - I hope to do this today. Before it will diverge too much from master, whole I will be setting up testing infrastructure for the new branch, we will be able to backport some changes from master into `stable-4.11 for a while. 

However, we should close this issue not after stable-4.11 has been branched, but only after the release notes are converted from the Wiki page into a new chapter in the Changes manual.

**Comment by fingolfin** [comment]
I agree with Alex! Also: my previous comment was badly worded, I've updated it

**Comment by alex-konovalov** [comment]
Will be done by @dimpase in #3886

**Comment by alex-konovalov** [comment]
Closed in #3886 by @dimpase - thanks a lot! I hope with switching to markdown we can use approach from https://github.com/gap-system/gap/wiki/GAP-4.11-release-notes app to collectively work on https://github.com/gap-system/gap/wiki/GAP-4.12-release-notes page as soon as it gets updates, and don't go into release notes bottleneck again!
