### ISSUE TITLE
Immutable filenames

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#343]
Just fixed (I hope) a problem encountered by Heiko Dietrich, in which the Process code stored scratch filenames in global variable. The fix is to make them thread-local, but it also caused me to notice that filenames returned by `TmpName` etc. are mutable. The same is true of those returned by `DirectoryContents(..)` and probably lots of other places. Is there any reason for this? It would seem natural to return filenames as immutable. If we made filenames in general be immutable strings, then they can be shared between threads freely.

A few bits of code that mutate the strings in place to change extensions or whatever would no doubt need changing, and oddly I might not have found the bug in Process so easily -- since we would instead have had multiple threads trying to use the same scratch files.

**Comment by alex-konovalov** [comment]
Could it be that not making filenames mutable will protect files from simultaneously being written from concurrent threads? Otherwise, you need to explicitly share the filename if you want the file to receive output from multiple threads, and one should lock the filename first to be able to use it e.g. in `PrintTo`.

**Comment by stevelinton** [comment]
It doesn't provide any rigorous control, of course, but it might serve as a hint that people should think twice before sharing filenames between threads.

**Comment by alex-konovalov** [comment]
@stevelinton shall we close this then and leave filenames as they are?

**Comment by stevelinton** [comment]
OK.
