### ISSUE TITLE
Cygwin reports foreign localisation of Windows

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#344]
This happens in the master branch when it GAP is compiled and run in the Cygwin shell:

```
testing: /home/jenkins/gap/tst/testinstall/dir.tst
########> Diff in /home/jenkins/gap/tst/testinstall/dir.tst, line 11:
# Input is:
DirectoryHome() = Directory("~");
# Expected output:
true
# But found:
#I  Foreign Localization of Windows
Need name of 'My Documents' folder[ ".", "..", ".bashrc", ".bash_history", ".b\
ash_profile", ".inputrc",
  ".mkshrc", ".profile", ".ssh", "gap", "gap4r7" ]
true
########
########> Diff in /home/jenkins/gap/tst/testinstall/dir.tst, line 13:
# Input is:
ForAll([DirectoryHome, DirectoryDesktop,DirectoryCurrent],
          x -> (IsDirectoryPath(x()) and IsDirectory(x())) );
# Expected output:
true
# But found:
#I  Foreign Localization of Windows
Need name of 'My Documents' folder[ ".", "..", ".bashrc", ".bash_history", ".b\
ash_profile", ".inputrc",
  ".mkshrc", ".profile", ".ssh", "gap", "gap4r7" ]
#I  Foreign Localization of Windows
Need name of 'My Documents' folder[ ".", "..", ".bashrc", ".bash_history", ".b\
ash_profile", ".inputrc",
  ".mkshrc", ".profile", ".ssh", "gap", "gap4r7" ]
#I  Foreign Localization of Windows
Need name of 'Desktop' folder[ ".", "..", ".bashrc", ".bash_history", ".bash_p\
rofile", ".inputrc",
  ".mkshrc", ".profile", ".ssh", "gap", "gap4r7" ]
#I  Foreign Localization of Windows
Need name of 'Desktop' folder[ ".", "..", ".bashrc", ".bash_history", ".bash_p\
rofile", ".inputrc",
  ".mkshrc", ".profile", ".ssh", "gap", "gap4r7" ]
true
########
```

**Comment by ChrisJefferson** [comment]
Recently you showed me a trace output from Windows -- is this from the same machine (where we got the following, or a different machine?

```
gap> DirectoryHome();
dir("/cygdrive/c/Users/jenkins/My Documents/")
gap> Directory("~");
dir("/cygdrive/c/Users/jenkins/")
gap> GAPInfo.UserHome;
"/cygdrive/c/Users/jenkins/"
```

**Comment by alex-konovalov** [comment]
That's from different. This issue #344 is from machine with Cygwin observed in Cygwin shell. The issue to which you refer is #340 produced on a Cygwin-free machine with GAP run in mintty (started with gap.bat)

**Comment by ChrisJefferson** [comment]
OK. This issue isn't my fault, I suspect DirectoryHome has never worked on that machine -- we just have to look at why bad things are happening. I'll try to get a cygwin / windows GAP build going so I can investigate.

**Comment by alex-konovalov** [comment]
I think you're right - this was not working before. It's just the new test that detected that.

**Comment by ChrisJefferson** [comment]
What's happening here is that some part of GAP is picking up the cygwin/linux home directory, and some other parts is expecting a Windows home directory, complete with 'My Documents'. It will require some poking to decide why two parts of GAP are disagreeing (and also, which should win).

**Comment by ChrisJefferson** [comment]
Darn, have done a bit of playing and googling, basically depending on how you start it cygwin can decide home is the cygwin home directory, or windows home directory.

So, should we try harder to use the windows one (possibly changing behaviour for some existing users?) I think we probably should.

**Comment by alex-konovalov** [comment]
I think in Cygwin shell it should definitely behave like in Linux, not like in Windows. That's the whole point of running GAP in Cygwin shell instead of starting it with gap.bat. Hence I consider 
```
gap> Directory("~");
dir("/home/jenkins/")
```
to be correct and 
```
gap> DirectoryHome();
#I  Foreign Localization of Windows
Need name of 'My Documents' folder[ ".", "..", ".bashrc", ".bash_history", ".bash_profile", ".inputrc",
  ".mkshrc", ".profile", ".ssh", "gap", "gap4r7" ]
```
not. 

`DirectoryHome` (and `DirectoryDesktop`) were added IIRC by @hulpke for GAP 4.5 to make it more user-friendly for Windows user and just uses hardcoded names of these dedicated folders in various localisation of Windows, e.g.
```
    a:=First(["Desktop",
	      "Bureau", #fr
	      "Bureaublad", #nl
	      "Escritorio", #es
```

**Comment by ChrisJefferson** [comment]
Unfortunately, at present, `DirectoryHome()` effectively looks up `Directory("~")`, and then looks in there for 'My Documents', so we can't have the current implementation of `DirectoryHome`, and have `Directory("~")` go to the cygwin home directory :\

**Comment by ChrisJefferson** [comment]
Just had another look at this. There isn't a nice fix, as it's hard to know if we are in the cygwin home directory or windows home directory (there isn't a well-defined means to check).

There are a few horrible options, none of them pleasant. We could "know" that cygwin home directories seem to start '/home/' for example. We could start calling windows API functions to get the directories we really want.

The best of a bad bunch (I feel) is to make the error for not finding 'Desktop' or 'Documents' into a soft error -- if we can't find them just return "~", which is what we already do on linux.

**Comment by fingolfin** [comment]
As I wrote on #340, we really should be calling the native Windows APIs for retrieving the path of the Documents, Desktop etc. folder.

It also might make sense to change `DirectoryHome` to return the home directory, and add a new `DirectoryDocuments` returning the documents folderr... though instead of all these `DirectoryFOO` dirs, we also could have a single function taking an argument that determines which special directory is wanted (Desktop, Documents... but also Pictures, Movies, ... whatever there is...)

**Comment by ChrisJefferson** [comment]
We now do this "properly", so it's fixed (I checked it on a non-UK windows install and it worked)
