### ISSUE TITLE
Error when testing permutation groups for conjugacy

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#3446]
The file
[conjbug.txt](https://github.com/gap-system/gap/files/3163647/conjbug.txt)
defines three permutation groups `a`, `b`, and `c` of degree 448. Then

    gap> RepresentativeAction(a,b,c);
    Error, no method found! For debugging hints type ?Recovery from NoMethodFound
    Error, no 1st choice method found for `^' on 2 arguments called from
    OnTuples( sub, subs.reps[o]
     ) at /Volumes/BigDisk/oldgap/gap4r8/lib/stbcbckt.gi:724 called from

Clearly this should work.
I have been able to trace this back to GAP 4.7, but did not have an older runneable version to test on.

**Comment by ChrisJefferson** [comment]
Just to say, I had a look at this -- I couldn't figure out what the problem was. I suspect the problem is the search should just be "failing" and backtracking in the failing branch, but the data structures are very weird, and not documented.

**Comment by fingolfin** [comment]
This bug is already present in GAP 4.4.12. As such, I removed the GAP 4.10.2 milestone. I also removed the backport-to-4.10 label, which only applies to pull requests.

**Comment by alex-konovalov** [comment]
I can not see how removing the milestone could be explained by the bug being present in 4.4.12 release (or do I interpret it wrong) but I agree with removing `the backport-to-4.10 label`, and hence removing the milestone.

**Comment by fingolfin** [comment]
@ChrisJefferson if you still think you might have any insights into this... :-)
