### ISSUE TITLE
doc error for DoubleCoverOfAlternatingGroup

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#345]
39.24-11 DoubleCoverOfAlternatingGroup
  
  ‣ DoubleCoverOfAlternatingGroup( n, p ) ──────────────────────────────────────────────────── operation
  
  Constructs  a  double cover of AlternatingGroup(n) as a faithful, completely reducible matrix group in
  characteristic  p  (p ≠ 2) for n ≥ 4. **For n ≥ 3, the symmetric** group is its own Schur cover so fail is
  returned....

The last sentence makes no sense at all. It should read: `For n<4, the alternating group is...`

**Comment by dimpase** [comment]
I'd provide a pull request if I knew where this is documented, but `grep DoubleCover *` does not show anything meaningful anywhere...

**Comment by alex-konovalov** [comment]
Thanks. `grep -R --include=*.g* DoubleCoverOfAlternatingGroup lib/` reports that is is in `lib/schursym.gd`.

**Comment by dimpase** [comment]
Oh, right, it didn't cross my mind that it may be in the source rather than in the docs.

**Comment by dimpase** [comment]
fixed in the master branch, see https://github.com/gap-system/gap/commit/ee6d4fd167416e55b44f43beae90428841c1cc39
