### ISSUE TITLE
`DeclareAttribute` doesn't check whether variable is already bound

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#3470]
I can do `DeclareAttribute("Dimension", IsList);` without GAP complaining. `Dimension` already is an attribute of free left modules though.

**Comment by fingolfin** [comment]
Yeah, but that's perfectly legal, and works as intended.

**Comment by ssiccha** [comment]
Could one add an explanation to the documentation then? I don't understand how that fits with "binds the variable to the name and makes the name read only".
