### ISSUE TITLE
Segmentation fault on wrong access to record components

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#3489]
The following input causes a segmentation fault (already in very old GAP versions).
```
gap> r:= rec( a:= 1 );;
gap> \.( r, "a" );
```
I think GAP should better give an appropriate error message.

In addition to that, I think that the documentation is not clear enough in this respect. 
The section "Record Access Operations" in the GAP Reference Manual says that record component names are encoded by numbers,
and that the correspondence is implemented by `NameRNam` and `RNamObj`.
It does not say what this means for non-infix calls to the operation `\.`
and to the methods installed for this operation.
In particular it does not show an example.
The following example would already be helpful.
```
gap> G:= SymmetricGroup( 4 );;
gap> G.1;
(1,2,3,4)
gap> \.( G, RNamObj( 1 ) );
(1,2,3,4)
gap> meth:= ApplicableMethod( \., [ G, 4711 ] );;
gap> meth( G, RNamObj( 1 ) );
(1,2,3,4)
```
If you agree that extending the documentation this way would be useful
then I can provide a pull request for such a change.

**Comment by ChrisJefferson** [comment]
Good catch! I agree the docs should be better, and also the crash needs fixing.

**Comment by ChrisJefferson** [comment]
Extra comment (I'm looking at this myself), even if you pas an int, if it's not a valid RNAM (say, it's too big) you get crashes/corruption.

**Comment by fingolfin** [comment]
I have a fix for this, but need to clean it up a bit, and also need to teach now, so I'll submit it later.

**Comment by ChrisJefferson** [comment]
I have a seperate fix..
