### ISSUE TITLE
Three more failures in the master branch when GAP started with `-r -A` options: it hangs forever on

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#3498]
Made the comment a separate issue so that one can close without closing top issue

There are also three more failures that I observe in Jenkins in the master branch when GAP started with `-r -A` options: it hangs forever on
-  `tst/teststandard/twocohom.tst`
- `tst/testextra/perfect.tst`
- testing manual examples from Chapter 47

_Originally posted by @alex-konovalov in https://github.com/gap-system/gap/issues/3496#issuecomment-501388527_

**Comment by hulpke** [comment]
I have a fix for at least the first two of this.

**Comment by alex-konovalov** [comment]
@hulpke thanks! I did not manage to locate the offending example for the 3rd more precisely, but hopefully your fix applies there too!
