### ISSUE TITLE
RegisterPackageTNUM introduces serious breakage

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#350]
Consider this example:
```
gap> LoadPackage("RegisterPackageTNUMDemo");
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Loading  RegisterPackageTNUMDemo 0.1 (Demo for RegisterPackageTNUM functionality)
by Markus Pfeiffer (http://www.morphism.de/~markusp).
Homepage: http://gap-packages.github.io/RegisterPackageTNUMDemo/
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
true
gap> G := SmallGroup(192,3);
<pc group of size 192 with 7 generators>
gap> C := CharacterTable(G);
CharacterTable( <pc group of size 192 with 7 generators> )
gap> IsSolvable(C);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `Length' on 1 arguments called from
Length( f ) at /Users/mhorn/Projekte/GAP/gap.github/lib/pcgsperm.gi:1085 called from
CreateIsomorphicPcGroup( pcgs, false, false ) at /Users/mhorn/Projekte/GAP/gap.github/lib/pcgsperm.gi:1132 called from
IsomorphismPcGroup( D.galMorphisms ) at /Users/mhorn/Projekte/GAP/gap.github/lib/ctblgrp.gi:1528 called from
CharacterMorphismGroup( D ) at /Users/mhorn/Projekte/GAP/gap.github/lib/ctblgrp.gi:2042 called from
DixonInit( G, opt ) at /Users/mhorn/Projekte/GAP/gap.github/lib/ctblgrp.gi:2160 called from
...  at line 4 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk>
```

This is not specific to the `RegisterPackageTNUMDemo` package, I can also reproduce it with e.g. `NormalizInterface`, see gap-packages/NormalizInterface#27

Luckily, as long as nobody uses `RegisterPackageTNUM`, this does not matter. But it does make `RegisterPackageTNUM` unusable for now :-/

**Comment by fingolfin** [comment]
OK, the issue is this line in `objects.h`:
```
#define FIRST_PACKAGE_TNUM      T_WPOBJ
```
Ouch. So the first package clobbers T_WPOBJ.

I will fix this, carefully...

**Comment by markuspf** [comment]
This shows how little testing all this received. I think I had a think about the TNUMs in HPC-GAP, but I might have gotten it wrong there too.

Is there a way for us to make sure we do not clobber TNUMs too easily (not only by calling RegisterPackageTNUM, but in the C code)?

**Comment by fingolfin** [comment]
@markuspf Well, this is C code... it's always trivial to shoot your own foot in C, not sure what you'd want to do... :/

**Comment by markuspf** [comment]
@fingolfin, I was thinking of macro magic for instance (I admit that this is a shot in the blue, and maybe not worth the effort).

**Comment by fingolfin** [comment]
Note: It would be kinda nice if this fix was in the first public 4.8.x release.

**Comment by fingolfin** [comment]
@markuspf Still not sure what you are thinking about here... right now, `objects.h` is the only place that allocates TNUMs, so that's the place we need to carefully watch for now -- and we (probably I) messed that up. Other than that, one should be fine, as long as one sticks to the TNUM constants defined there -- well, or the TNUMs returned by `RegisterPackageTNUM`.

**Comment by markuspf** [comment]
Maybe I am just thinking of a way to verify that TNUMs don't overlap like a script that gets all defined TNUMs and just checks they don't overlap.
Since this information will not be mutated too much, and we'll more likely have registered TNUMs from packages I hope, I'm fine with how things are.

**Comment by alex-konovalov** [comment]
> This shows how little testing all this received. 

Let me reiterate: I don't see RegisterPackageTNUMDemo as an individual package submitted for the redistribution with GAP, but we should extend the Example package with an example of a kernel module, and demonstrate there various tricks that package authors may find useful, including this one. This will ensure that we regularly build and test this code. This is a good task for January.
