### ISSUE TITLE
teststandard/processes/children.tst unusable in 64-bit Windows build

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3506]
This issue arises when GAP is build under cygwin and cygwin64, and then copied over to a cygwin-free machine to test it there. 

The cygwin-free machine is a Windows10 VM that can use 4 GB RAM. 

The test of the 32-bit build works there just fine. It takes 13-14 hours to run twice `testinstall.g` and twice `teststandard.g`, with `-A` and with default packages loaded. 

However, the test of the 32-bit build stuck in `teststandard/processes/children.tst` forever, and was terminated after 20 hours. 

```
    3594 ms (718 ms GC) and 419MB allocated for pperm.tst
testing: /proc/cygdrive/C/gap-4.10.2-x86_64/tst/teststandard/processes/childre\
n.tst
Build timed out (after 1,200 minutes). Marking the build as aborted.
Build was aborted
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
Finished: ABORTED
```

I logged in and tried commands from the test interactively, and it works:
```
gap> d := DirectoryCurrent();;
gap> scriptdir := DirectoriesLibrary( "tst/teststandard/processes/" );;
gap> checkpl := Filename(scriptdir, "check.pl");;
gap> check.pl;
Error, Variable: 'check' must have a value
not in any function at *stdin*:6
gap> checkpl;
"/proc/cygdrive/C/gap-4.10.2-x86_64/tst/teststandard/processes/check.pl"
gap> if IsBoundGlobal("IO_RestoreSIGCHLDHandler") then
> ValueGlobal("IO_RestoreSIGCHLDHandler")();
> fi;
gap> runChild := function(ms, ignoresignals)
>    local signal;
>    if ignoresignals then signal := "1"; else signal := "0"; fi;
>    return InputOutputLocalProcess(d, checkpl, [ String(time), signal]);
>  end;;
gap> reps:=1;
1
gap> runChild(1,false);
< input/output stream to check.pl >
gap> runChild(1,true);
< input/output stream to check.pl >
gap> Perform([last,last2],CloseStream);
```

but then trying to call

    children := List([1..20], x -> runChild(Random([1..2000]), Random([false,true])));;

makes computer very slow to response. I started resource monitor and run a new attempt, and it seems like it starts heavy swapping:
 
![cygwin64](https://user-images.githubusercontent.com/5751387/59672807-1db63080-91b8-11e9-88b4-2877513badf0.png)

Shall we have two versions of this test perhaps? A heavy one in `testextra`, which I do not run on Windows, and a lightweight (with just two `runChild` calls as above) in `teststandard` so that we do run this test on Windows to test that at least `InputOutputLocalProcess` works?

**Comment by alex-konovalov** [comment]
If that will be the plan, modified test should be backported into stable-4.10, to help to test it's 64-bit Windows build.

**Comment by alex-konovalov** [comment]
Note that this is in stable-4.10 branch of GAP, not in master (CC @ChrisJefferson w.r.t. #3509).

**Comment by ChrisJefferson** [comment]
This PR and #3509 are not related.
