### ISSUE TITLE
Coverage/profiling bug: `Info` statements inside uncalled functions are marked as covered

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3519]
For an example, see here: <https://coveralls.io/builds/24175509/source?filename=lib%2Ffactgrp.gi#L1241>

Ping to @ChrisJefferson who knows most about our code coverage code :-)

**Comment by ChrisJefferson** [comment]
So, this is being caused by Syntax Tree. I tried tracing through the code but got lost. I'm not clear how it handles info statements to see what is going wrong.

**Comment by fingolfin** [comment]
Ahhh that makes sense. We are cheating in some place and evaluate certain expressions in order to get their value. My guess is that this is the root of the issue. With your hint, I should be able to write a fix (but won't have time for the next 1-2 days at least)

**Comment by fingolfin** [comment]
So, `SyntaxTreeEvalCompiler` uses `EVAL_EXPR`, and that causes the expressions to marked as visited (if profiling is active). I first thought about simply resetting the `visited` flag afterwards; but of course that doesn't take care of any nested expressions... So I think we need a way to disable or othewise avoid profiling, at least temporarily. 

One way to do achieve that would be to export wrappers for `ActivateHooks(&profileHooks);` and `DeactivateHooks(&profileHooks);` from `profile.c` in `profile.h`. Then call them before and after the call to `EVAL_EXPR`

Another option would be to have another macro, say `LOWLEVEL_EVAL_EXPR`, which always directly calls the evaluation function, and never goes through the profiler hooks. Then `EVAL_EXPR` could be implemented in terms of that.
