### ISSUE TITLE
Regression in grpauto and doublecoset benchmarks (memory usage)

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3533]
This used to work in the master branch, but not anymore:
```
cd benchmark/grpauto
../../bin/gap.sh -o 1g test1.g
```
results in
```
# line 63, input:
IsomorphismGroups(gp1,gp2)<>fail;
########> Diff in permiso.tst:63
# Input is:
IsomorphismGroups(gp1,gp2)<>fail;
# Expected output:
true
# But found:
Error, reached the pre-set memory limit
(change it with the -o command line option)
```
This is a weekly test, it passed last time successfully on June 22, but now fails.

In addition,
```
cd benchmark/doublecoset
../../bin/gap.sh -o 2g test3.g
```
also fails in 32-bit build on mac:
```
# line 5, input:
START_TEST("doublecoset3.tst");
# line 6, input:
g:=SimpleGroup("Co3");;
# line 7, input:
m:=MaximalSubgroupClassReps(g);;
# line 8, input:
u:=First(m,x->Index(g,x)=17931375);;
# line 9, input:
dc:=DoubleCosetRepsAndSizes(g,u,u);;
Panic in src/sysmem.c:666: cannot extend the workspace any more!!!
```
The St Andrews-only link to Jenkins is [here](https://gap-ci.cs.st-andrews.ac.uk/view/GAP-weekly/job/GAP-master-benchmarks/).

**Comment by fingolfin** [comment]
Perhaps @hulpke could have a look?

**Comment by hulpke** [comment]
I have a fix for the first issue. The second one is due to the arbitary 1GB limitations and would go away if one allows a bit more memory.

**Comment by fingolfin** [comment]
While the 1GB limit of course *is* arbitrary, one of the reasons for doing it is so that we notice if some computations suddenly a need a lot more memory... Of course it'd be better if we had a more clever way to track changes in memory consumption (and in performance).

**Comment by hulpke** [comment]
Sure. This example just was at the limit before and now slightly exceeds it. (That might mean it was a bad example to start with.)

**Comment by alex-konovalov** [comment]
@hulpke it is the 1st example that has 1GB limit, but the 2nd has 2GB. You can check that I've specified in the issue description how GAP was started. If you tried the 2nd example with 1GB, perhaps you may want to retest it with 2gb to check your conclusion? 

I can increase slightly that memory requirement, but this example used to work for a long time, and still works in the stable-4.10 branch, so I am worried that there may be a genuine regression.

**Comment by hulpke** [comment]
On my machine the second example takes 1.3GB. I'm at a loss why it would take more than 2GB on a 32bit machine.

**Comment by hulpke** [comment]
This seems to be purely a side-effect of using `Test` and its default assertions. Resetting the assertion level makes the problem vanish.
