### ISSUE TITLE
Documentation of standard mathematical functions is unclear

### ISSUE THREAD

**Issue by DominikBernhardt** [gap-system/gap#3540]
This concerns the part of the manual `19.2-10 Standard mathematical operations`:

- It is unclear from the documentation that these functions can only be applied to floats
- `Log2`, `Log10`, `Log1p`, `Exp2`, `Exp10` and `Expm1` need further explanation as to what they are doing.

**Comment by fingolfin** [comment]
Duplicate of issue #1778
