### ISSUE TITLE
Special casing identity in permutation operations

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#3547]
As an experiment, I decided to check how many of the times someone operates on permutations, one of the permutations is the identity, when running testinstall

p*q : 19% of 3410082
Quo: 6% of 690495
Conj: 5% of 30276
p^i for integer i: 2% of 53155

So, given that I think it's certainly worth special casing p*q to handle p or q being the identity. It's probably worth it for quo and conj as well, as we have calculate the length of both permutations, so all we are doing is a comparison on something we already have in a register anyway.

**Comment by wilfwilson** [comment]
I think you’re probably onto a good idea.

However, I’d recommend doing some kind of quick sanity check on the data that you got.

It could be the case that there is just one crazy test in testinstall that’s accounting for almost all of those operations involving the identity. In which case, actually operations involving the identity might be very rare in normal use. Unlikely, but worth a check before putting work into it, I’d say.

**Comment by wilfwilson** [comment]
@ChrisJefferson started telling me that he'd looked into this further, and then our conversation got interrupted, so I don't know what his conclusion was...
