### ISSUE TITLE
Hang at assertion level 2 when computing with a certain group of perms made by PermLeftQuoTransformation

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#3574]
This problem only appears in the GAP `master` branch after https://github.com/gap-system/gap/commit/8c9f355aee4bce42c061d66f779442ee0678082f (I'm not saying that there's anything wrong with that commit, only that that commit brought this problem to light).
```
gap> SetAssertionLevel(2);
gap> p := PermLeftQuoTransformation(IdentityTransformation, Transformation([2, 1]));
(1,2)
gap> G := Group([(1,2,3), p]);; # SymmetricGroup(3)
gap> H := MaximalSubgroupClassReps(G)[2];
Group([ (2,3) ])
gap> Pcgs(H);
[HANG]
```
@ChrisJefferson has been looking into this so far, and has said:
> "It's something deeper and crazy, a perm4 is ended up with a stored perm2 inverse, which breaks lots of things. I don't know how that is happening"

**Comment by ChrisJefferson** [comment]
Here is the series of events:

* Make a Perm4 permutation `p`
* Ask for it's inverse, which sets it's stored inverse, as a Perm4
* Call `TrimPerm(p, i)` for an `i` small enough that `p` is in-place transformed into a Perm2.
* Various pieces of code expect that if `p` has a stored inverse, it will be the same type of permutation as `p`, but it's not, it's a perm2. Awful things happen.

Here is a simple example:

```
# Make p as a Perm4
gap> p := (1,2,3,4)*(2^16,2^16+1)*(2^16,2^16+1);
(1,2,3,4)
# Force inverse calculation
gap> p^-1;
(1,4,3,2)
# Trim. Now it's a perm2
gap> TRIM_PERM(p,4);
gap> p;
(1,2,3,4)
# Calculate some quotients, which uses the internally cached inverse incorrectly
gap> 1/p;
4
gap> 2/p;
1
gap> 3/p;
1
gap> 4/p;
1
# This is what we should get
gap> q := (1,2,3,4);
(1,2,3,4)
gap> 1/q;
4
gap> 2/q;
1
gap> 3/q;
2
gap> 4/q;
3
```
