### ISSUE TITLE
'Length' became considerably slower

### ISSUE THREAD

**Issue by frankluebeck** [gap-system/gap#3577]
### Observed behaviour
In gap-4.10.2 (x86_64):
```
gap> for i in [1..100000000] do od; time;
719
gap> l:=[2..100]+0;;
gap> for i in [1..100000000] do len:=Length(l); od; time;
2063
gap> s:="fhklaheirifnieufhawifhweifhwifuhawifuhwefiuwhf";;
gap> for i in [1..100000000] do len:=Length(s); od; time;
2016
```

Current GAP master (same machine, same memory):
```
gap> for i in [1..100000000] do od; time;
894
gap> l:=[2..100]+0;;
gap> for i in [1..100000000] do len:=Length(l); od; time;
3088
gap> s:="fhklaheirifnieufhawifhweifhwifuhawifuhwefiuwhf";;
gap> for i in [1..100000000] do len:=Length(s); od; time;
3098
```

### Expected behaviour
The empty loop should not be 25% slower and the calls of 'Length' should not be 70% slower than in 4.10.2.

### Comments
Is this connected to the change that lengths of plists and strings are now stored as GAP integers instead of C integers?

**Comment by ChrisJefferson** [comment]
So, I agree this is a problem and needs looking at.

However, the amount of time actually spent in ElmPlist is basically 0. A similar problem is visible, with almost identical slowdown, with (picking a random function) ABS_RAT and an integer:

In GAP master:
```
gap> l := [2..100]+0;; c := 2;;
gap> for i in [1..100000000] do len:=Length(l); od; time; for i in [1..100000000] do ABS_RAT(c); od; time;
3897
2785
```

In 4.10:
```
gap> for i in [1..100000000] do len:=Length(l); od; time; for i in [1..100000000] do ABS_RAT(c); od; time;
2568
1880
```

**Comment by ChrisJefferson** [comment]
Update: we are doing something weird, we are making many more calls to gasman. We should probably do better at benchmarking.

**Comment by ChrisJefferson** [comment]
Update update: that was a mistake.

One big problem I think is checking recursion depth. This got more expensive for 3 reasons:

1) we do it in more places, to try to catch more problems
2) it was moved out of the header so can't be inlined
3) accessing global state was made more general, and in the process got more expensive.

**Comment by ChrisJefferson** [comment]
Update, it was largely caused by a commit of mine, in category (1), where I started checking depth in many more places to try to simplify code and fix a bug. Commit  579456e

**Comment by ChrisJefferson** [comment]
Just in case anyone else is looking at this, I'm preparing a couple of PRs which speed things up faster than 4.10.

**Comment by ChrisJefferson** [comment]
On my computer, after PRs #3578 and #3579 

Stable-4.10:

```
gap> for i in [1..100000000] do od; time;
1512
gap> l:=[2..100]+0;;
gap> for i in [1..100000000] do len:=Length(l); od; time;
3870
gap> s:="fhklaheirifnieufhawifhweifhwifuhawifuhwefiuwhf";;
gap> for i in [1..100000000] do len:=Length(s); od; time;
3992
```

Master:

```
gap> for i in [1..100000000] do od; time;
1248
gap> l:=[2..100]+0;;
gap> for i in [1..100000000] do len:=Length(l); od; time;
3675
gap> s:="fhklaheirifnieufhawifhweifhwifuhawifuhwefiuwhf";;
gap> for i in [1..100000000] do len:=Length(s); od; time;
3748
```

**Comment by frankluebeck** [comment]
Thanks for looking into this. I can confirm the slight speedup of the current master over 4.10.2 on my machine. 

So, this issue is not related to the recent change of storing the length of a list or string as GAP integer.

**Comment by fingolfin** [comment]
So this is resolved, great :-)

**Comment by ChrisJefferson** [comment]
I just wanted to say again, thanks for reporting this. It would be good to automatically find such issues, but writing and maintaining benchmarks is a tricky problem which can be an annoying time sink.
