### ISSUE TITLE
Document !. and ![] in reference manual resp. add them to index

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3583]

**Comment by PaulaHaehndel** [comment]
They are documented in 79.10 and 79.11, but having them in the index would be nice, as they are currently hard to find.

**Comment by fingolfin** [comment]
Thanks for digging those out. Yeah, at the very least, suitable `<Index>` elements should be added there. Even better would be if these had explicit ManSections, as we have for e.g. list operations, see [section 21.2](https://www.gap-system.org/Manuals/doc/ref/chap21.html#X7B202D147A5C2884) in the manual.

Even *better* would be, IMHO, if all information on syntax were found in one chapter, even if each syntactical element was described only briefly, with a link to another section that contains more information.

(Another syntactical element which is hard to is tilde `~`, as used in e.g. `rec(x := [], y := ~.x)` or `[ [], ~[1] ]` -- in fact I couldn't fit this in the reference manual just now either, only a quick mention in the tutorial.)

**Comment by fingolfin** [comment]
There is no GAP syntax involving `{`, in particular no `!{`. The matches you found are not in GAP code.

**Comment by hongyi-zhao** [comment]
If so, why is this still in the GAP-reference manual [here](https://docs.gap-system.org/doc/ref/chap4.html#X7E90E6607F4E4943):

![image](https://user-images.githubusercontent.com/11155854/211329213-b7eefa3e-a4f0-4ccd-803d-7638349b0ef4.png)
