### ISSUE TITLE
Changed behaviour of IsomorphismPermGroup?

### ISSUE THREAD

**Issue by cdwensley** [gap-system/gap#3584]
This query arose from XMod tests failing under gapdev. 
Should this be considered regressive behaviour?  The group is just C_4^3. 
Here is the input file: 
### Input 
```gap
f := FreeGroup( 3 );  a := f.1;   b := f.2;   c := f.3; 
rels := [ a^4, b^4, c^4, Comm(c^-1,a^-1), Comm(c^-1,b^-1), Comm(b^-1,a^-1) ]; 
g := f/rels; 
iso := IsomorphismPermGroup(g);
```

### Observed behaviour - under gapdev 
```
gap> f := FreeGroup( 3 );  a := f.1;   b := f.2;   c := f.3;
<free group on the generators [ f1, f2, f3 ]>
f1
f2
f3
gap> rels := [ a^4, b^4, c^4, Comm(c^-1,a^-1), Comm(c^-1,b^-1), Comm(b^-1,a^-1) ];
[ f1^4, f2^4, f3^4, f3*f1*f3^-1*f1^-1, f3*f2*f3^-1*f2^-1, f2*f1*f2^-1*f1^-1 ]
gap> g := f/rels;
<fp group on the generators [ f1, f2, f3 ]>
gap> iso := IsomorphismPermGroup(g);
[ f1, f2, f3 ] -> [ (5,6,11,7)(8,12,21,15)(9,13,22,16)(10,14,23,17)(18,24,31,27)(19,25,32,28)(20,26,33,29)(30,34,36,35),
(5,8,18,9)(6,12,24,13)(7,15,27,16)(10,19,30,20)(11,21,31,22)(14,25,34,26)(17,28,35,29)(23,32,36,33),
(1,2,4,3)(5,10)(6,14)(7,17)(8,19)(9,20)(11,23)(12,25)(13,26)(15,28)(16,29)(18,30)(21,32)(22,33)(24,34)(27,35)(31,36) ]
```

### Expected behaviour - under gap-4.10.2 
```
gap> f := FreeGroup( 3 );  a := f.1;   b := f.2;   c := f.3;
<free group on the generators [ f1, f2, f3 ]>
f1
f2
f3
gap> rels := [ a^4, b^4, c^4, Comm(c^-1,a^-1), Comm(c^-1,b^-1), Comm(b^-1,a^-1) ];
[ f1^4, f2^4, f3^4, f3*f1*f3^-1*f1^-1, f3*f2*f3^-1*f2^-1, f2*f1*f2^-1*f1^-1 ]
gap> g := f/rels;
<fp group on the generators [ f1, f2, f3 ]>
gap> iso := IsomorphismPermGroup(g);
[ f1, f2, f3 ] -> [ (1,2,3,4), (5,6,7,8), (9,10,11,12) ]
```

**Comment by fingolfin** [comment]
We'll look into it, but in general, we make no promises of stability of the output for functions like `IsomorphismPermGroup`, so if tests rely on it, they are always in risk of being broken.

**Comment by fingolfin** [comment]
I took the liberty of simplifying your test input to make the issue easier to see and reproduce for us. Clearly the output of GAP 4.10.2 is nicer.

**Comment by fingolfin** [comment]
The cause of the difference is this change: we (well, likely @hulpke) added the "cheap" option) in the following:
```patch
diff --git a/lib/grpfp.gi b/lib/grpfp.gi
index 6ead4415d..e46a320a4 100644
--- a/lib/grpfp.gi
+++ b/lib/grpfp.gi
@@ -4116,7 +4116,7 @@ local mappow, G, max, p, gens, rels, comb, i, l, m, H, t, gen, silent, sz,
 
   fi;
 
-  p:=SmallerDegreePermutationRepresentation(H:cheap);
+  p:=SmallerDegreePermutationRepresentation(H);
   # tell the family that we can now compare elements
   SetCanEasilyCompareElements(FamilyObj(One(G)),true);
   SetCanEasilySortElements(FamilyObj(One(G)),true);
```

**Comment by hulpke** [comment]
I would argue that it is not a regression, but a change in not promised behavior: Basically it sees to be worth (fatser runtime and not so much worse results) to not have GAP enforce a so good degree permutation representation, one could always use `SmallerDegreePermutationRepresentation;' to search harder.

**Comment by cdwensley** [comment]
Thanks for your comments @hulpke.  I was very aware that there was no promised behaviour, but I thought the change sufficiently significant to be worth raising it as a question.  I can easily fix the XMod tests.  (The output from `SmallerDegreePermutationRepresentation;' was shown in the original posting, but was removed by @fingolfin - it still does not give the 4.10.2 result.)
