### ISSUE TITLE
Document function SetConjugacyClasses

### ISSUE THREAD

**Issue by vdlee37** [gap-system/gap#3607]
The `SetConjugacyClasses( g, ccl )` function, featuring in an example in section 71.6.3 of the GAP Reference Manual, doesn't seem to be documented.

**Comment by wilfwilson** [comment]
Please see [Section 13.6 "Setter and tester for attributes"](https://www.gap-system.org/Manuals/doc/ref/chap13.html#X79DE5208877AE42A) in the GAP reference manual, especially [13.6-2 Setter](https://www.gap-system.org/Manuals/doc/ref/chap13.html#X7FD8952C841D2B1F), for an idea of what is happening here.

The 'function' `SetConjugacyClasses` is what you get when one calls `Setter` on the attribute `ConjugacyClasses`:
```
gap> Setter(ConjugacyClasses);
<Operation "SetConjugacyClasses">
```
In the example in [Section 71.6.3](https://www.gap-system.org/Manuals/doc/ref/chap71.html#X84DC12AA804C8085):
```
gap> SetConjugacyClasses( g, ccl );
```
the line is telling GAP to remember that the group `g` has the set of conjugacy classes `ccl`. This way, GAP doesn't have to spend time recomputing its conjugacy classes if it is asked for them at some later point.

Every attribute `MadeUpAttribute` in GAP (basically, a function whose value is remembered by GAP) is created along with functions `SetMadeUpAttribute` and `HasMadeUpAttribute`, that, respectively, store a value for `MadeUpAttribute`, and check whether there already exists a stored value for `MadeUpAttribute`.

Perhaps 71.6.3 could include a link to 13.6-2, for people who are confused by the example. Does anyone have any opinions on this?

**Comment by wilfwilson** [comment]
Therefore, to actually address your issue, I would argue that `Set(AttributeName)` should not be separately documented.

**Comment by stevelinton** [comment]
`?SetConjugacyClasses` produces `ConjugacyClasses (attribute)` as its first hit.

`GAPDoc` could add automatic index entries for attribute setters and testers and so on when processing the entry for the attribute, but there would be a lot of them.

**Comment by alex-konovalov** [comment]
And what @stevelinton says would work for all attribute setters and testers since GAP 4.9, which includes pull request #1144: The search for the documentation of system setters and testers now returns corresponding attributes and properties.

**Comment by vdlee37** [comment]
Okay, thanks.

But while instances like `SetName` and `SetParent` have entries in the manual's index, Set*attr* itself doesn't.

**Comment by alex-konovalov** [comment]
@vdlee37 so, do you suggest to add a generic index entries 

* Set*attr*, where *attr* is an attribute - see index entry for *attr* 

* Get*attr*, where *attr* is an attribute - see index entry for *attr*

I am not sure if this is technically possible, but may be useful, if it works.

OTOH, it only will improve the index entry, while some users may never look at it, using the `?` and `??` from the GAP command line and setting their help viewer to HTML browser, as shown  e.g. [here](https://alex-konovalov.github.io/gap-lesson/01-command-line/).

**Comment by vdlee37** [comment]
An entry Set*attr* (*sic*, i.e. with *attr* a wildcard signifying a generic attribute - as used elsewhere in the manual, rather than entries for all individual attributes) may be helpful.

I came across the sample featuring `SetConjugacyClasses` in the PDF, and pressed `Ctrl-F`  to find occurrences elsewhere in the document. But there were no more hits.

**Comment by fingolfin** [comment]
Searching in a static PDF will never be as useful or powerful as searching via the built-in help query feature provided by GAP. We might be able to improve the HTML version of the manual in the future to offer a bit better search but I wouldn't hold my breath for that happening, as we simply lack people who have the time to work on such nonessential features, I am afraid.

All in all, I really don't think we can do much here, other than to recommend that you perform queries to the manual via the GAP command line interface instead.
