### ISSUE TITLE
Bug in NullspaceModQ

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3614]
The following was reported on https://math.stackexchange.com/questions/3329100:
```
gap> NullspaceModQ([[2]],8);
[ [ 0 ] ]
```
But it really should return the list `[ [0], [4] ]`.

**Comment by fingolfin** [comment]
One option would be to just ditch the current implementation and use this code instead (which then also works for arbitrary moduli):
```gap
NullspaceModN := function(M, n)
  local B, coeffs;
  B := BasisNullspaceModN(M, n);
  coeffs := Cartesian(ListWithIdenticalEntries(Length(B), [0..n-1]));
  return Set(coeffs, c -> c * B mod n);
end;
```

Alas, perhaps `NullspaceModQ` is faster in some cases? One would have to conduct experiments to find out (although fast but incorrect code is not that useful...).

Of course one could also instead improve `BasisNullspaceModN` and perhaps even make a `BasisNullspaceModQ`, which strikes me as more useful than `NullspaceModQ` anyway, at least for most purposes.

**Comment by hulpke** [comment]
I am not sure whether `NullspaceModQ` is used anywhere. I would be happy with ditching the function completely (or replace it with the proposed code and move it on the way to obsolescence.
