### ISSUE TITLE
IsomorphismFpGroup for cyclic perm groups of order 3 returns presentation with two generators

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3645]
```
gap> IsomorphismFpGroup(Group((1,2,3)));
[ (1,2,3), (1,3,2) ] -> [ F1, F2 ]
gap> IsomorphismFpGroup(Group((1,2,3,4)));
[ (1,2,3,4), (1,3)(2,4) ] -> [ F1, F2 ]
gap> IsomorphismFpGroup(Group((1,2,3,4,5)));
[ (1,2,3,4,5) ] -> [ F1 ]
gap> IsomorphismFpGroup(Group((1,2)));
[ (1,2) ] -> [ F1 ]
```
In GAP 4.10, we get a single generator presentation in each case.

I suspect this is because special methods for alternating/symmetric groups in natural perm rep were added by @hulpke and these trigger here -- but I'd argue we really want to treat these as cyclic groups.

Would be nice to get this fixed in 4.11, as it breaks the RCWA test suite, and also certainly expectations of various people (e.g. mine ;-).

**Comment by hulpke** [comment]
I have added special treatment of A3.

For me, 4.8, 4.9 and 4.10 all produce two generators for the cyclic group of order 4. This is because the group is solvable and a pc presentation is written down.

I am not aware that we ever had a special method for presentations for cyclic groups.

**Comment by fingolfin** [comment]
Yes, indeed, my apologies: I got confused when I compared outputs across multiple GAP sessions: C_4 gives two generators for me, too.
