### ISSUE TITLE
Compilation issue on older Linux version

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#3648]
I am trying to compile the development version on a machine which (for reasons of "robustness" is using somewhat older versions of compiler etc, I have no way to override that policy. However I think this is not a completely untypical setup) The compiler is

     gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC)

and I had to install autoconf on my own, as the version provided is below 2.68

When trying to compile, compilation fails with

    cc1: warning: unrecognized command line option "-Wno-implicit-fallthrough"
    cc1: warning: unrecognized command line option "-Wno-cast-function-type"
       CXX     src/objfgelm.cc => obj/src/objfgelm.lo
    src/objfgelm.cc:1332: error: insufficient contextual information to determine type

(also on following lines) and 

    src/objfgelm.cc:1384: error: too many initializers for ‘StructGVarFunc’

I'm reporting it as issue, as it might affect compilability of 4.11 (4.10 compiled on the machine) with the new C++ files

**Comment by fingolfin** [comment]
Unfortunately I don't have access to any system with a GCC older than 4.7, so I can't reproduce the issue easily. But then I remembered there is https://godbolt.org and that has G++ 4.4.7, so at least there is a way for me to experiment :-), but only with code snippets.

I think I found a workaround, I'll submit a PR. However, I cannot actually test it (godbolt only allows me to compile snippets, not al of GAP).
