### ISSUE TITLE
Add a way to exit GAP immediately, with an exit code.

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#365]
Currently, I have to use `IO_exit` for that, but as was explained in #364, this is not so nice for various reasons.

Such a feature is very important if one wants to properly script running GAP computations. E.g. when building the manual, or running tests, being able to set an exit code in order to signal the build system that there was a failure.

**Comment by stevelinton** [comment]
Would it be enough to add a one-argument version of QUIT_GAP() and FORCE_QUIT_GAP()?

**Comment by ChrisJefferson** [comment]
Or, what's wrong with QUIT_GAP and FORCE_QUIT_GAP already? :) (you may have missed them being added).

**Comment by alex-konovalov** [comment]
@ChrisJefferson isnt' this something what you've done recently ?

**Comment by fingolfin** [comment]
Great! But I wasn't aware of it. I searched my email archive, I found an email by @ChrisJefferson from October 2014 that he wants to modify `QUIT_GAP` in that way. But I saw no further discussion, nor any description of this new feature in `dev/Updates` or any GAP release notes, i.e. it is not mentioned in chapter 2 of the GAP manual. 

In fact, it doesn't seem to be documented at all: I just re-run `make manuals`, and it neither appears in the index, nor does the built-in help system know anything about it. Though I do see it being mentioned in `doc/ref/mloop.xml`. Huh?

**Comment by fingolfin** [comment]
Argh, never mind. For some really stupid reason, GAP picked up the manual from another, older GAP installation (a matter of a badly placed symlink). Fixed that, so now I see `QUIT_GAP` in all its glory in the manual.

Still think it would be nice to mention it in an `dev/Updates` note, though :)

**Comment by alex-konovalov** [comment]
BTW, PR #150 is marked for GAP 4.8.0 milestone.
