### ISSUE TITLE
Compilation/linking issue

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#3651]
[sorry for filling the issue space:]
still teh same machine as #3648. Thanks to #3649 compilation works, but linking gave an error

       LINK    gap
    obj/src/.libs/collectors.o:(.data.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'

Searching found a recommendation:

If I change `GNUmakefile` in the line

    LIBS = -lm -ldl -lutil -lstdc++

(added the `-lstdc++` bit) then compilation succeeds. Alas I don't understand whether:

a) I can do so without harm for other systems

b) How to do it actually (as the line is auto-created). 

c) Is it just an artifect of me compiling a new autoconf and not compiling a new gcc?

**Comment by fingolfin** [comment]
Can you please report the output for linking if you use `make V=1` to get verbose info about the commands being executed.

Sadly, adding `-lstdc++` is not a portable solution, as this name is not standardized; eg for clang++, it is different. But in fact, adding it should normally not necessary at all, as we use the C++ compiler as linker, which ought to add the standard C++ library automatically. I am not sure why it fails here...

**Comment by fingolfin** [comment]
Also, autoconf has nothing to do with it.

**Comment by hulpke** [comment]
Thank you, @fingolfin for looking at it.
The output is

    Unix54 /home/fac/f/hulpke/gap4 > make V=1
    /bin/sh ./libtool --mode=link gcc -std=gnu99 -export-dynamic  /home/fac/f/hulpke/gap4/extern/install/gmp/lib/libgmp.la       obj/src/ariths.lo obj/src/bags.lo obj/src/blister.lo obj/src/bool.lo obj/src/c_oper1.lo obj/src/c_type1.lo obj/src/calls.lo obj/src/code.lo obj/src/collectors.lo obj/src/compiler.lo obj/src/compstat.lo obj/src/costab.lo obj/src/cyclotom.lo obj/src/debug.lo obj/src/dt.lo obj/src/dteval.lo obj/src/error.lo obj/src/exprs.lo obj/src/ffdata.lo obj/src/finfield.lo obj/src/funcs.lo obj/src/gap.lo obj/gen/gap_version.lo obj/src/gvars.lo obj/src/hookintrprtr.lo obj/src/info.lo obj/src/integer.lo obj/src/intfuncs.lo obj/src/intrprtr.lo obj/src/io.lo obj/src/iostream.lo obj/src/libgap-api.lo obj/src/listfunc.lo obj/src/listoper.lo obj/src/lists.lo obj/src/macfloat.lo obj/src/modules.lo obj/src/modules_builtin.lo obj/src/objcftl.lo obj/src/objects.lo obj/src/objfgelm.lo obj/src/objpcgel.lo obj/src/objset.lo obj/src/opers.lo obj/src/permutat.lo obj/src/plist.lo obj/src/pperm.lo obj/src/precord.lo obj/src/profile.lo obj/src/range.lo obj/src/rational.lo obj/src/read.lo obj/src/records.lo obj/src/saveload.lo obj/src/scanner.lo obj/src/sctable.lo obj/src/set.lo obj/src/stats.lo obj/src/streams.lo obj/src/stringobj.lo obj/src/syntaxtree.lo obj/src/sysfiles.lo obj/src/sysmem.lo obj/src/system.lo obj/src/tietze.lo obj/src/trans.lo obj/src/vars.lo obj/src/vec8bit.lo obj/src/vecffe.lo obj/src/vecgf2.lo obj/src/vector.lo obj/src/weakptr.lo obj/src/gasman.lo   -lz -lreadline    -lm -ldl -lutil -o gap
    libtool: link: gcc -std=gnu99 obj/src/.libs/ariths.o obj/src/.libs/bags.o obj/src/.libs/blister.o obj/src/.libs/bool.o obj/src/.libs/c_oper1.o obj/src/.libs/c_type1.o obj/src/.libs/calls.o obj/src/.libs/code.o obj/src/.libs/collectors.o obj/src/.libs/compiler.o obj/src/.libs/compstat.o obj/src/.libs/costab.o obj/src/.libs/cyclotom.o obj/src/.libs/debug.o obj/src/.libs/dt.o obj/src/.libs/dteval.o obj/src/.libs/error.o obj/src/.libs/exprs.o obj/src/.libs/ffdata.o obj/src/.libs/finfield.o obj/src/.libs/funcs.o obj/src/.libs/gap.o obj/gen/.libs/gap_version.o obj/src/.libs/gvars.o obj/src/.libs/hookintrprtr.o obj/src/.libs/info.o obj/src/.libs/integer.o obj/src/.libs/intfuncs.o obj/src/.libs/intrprtr.o obj/src/.libs/io.o obj/src/.libs/iostream.o obj/src/.libs/libgap-api.o obj/src/.libs/listfunc.o obj/src/.libs/listoper.o obj/src/.libs/lists.o obj/src/.libs/macfloat.o obj/src/.libs/modules.o obj/src/.libs/modules_builtin.o obj/src/.libs/objcftl.o obj/src/.libs/objects.o obj/src/.libs/objfgelm.o obj/src/.libs/objpcgel.o obj/src/.libs/objset.o obj/src/.libs/opers.o obj/src/.libs/permutat.o obj/src/.libs/plist.o obj/src/.libs/pperm.o obj/src/.libs/precord.o obj/src/.libs/profile.o obj/src/.libs/range.o obj/src/.libs/rational.o obj/src/.libs/read.o obj/src/.libs/records.o obj/src/.libs/saveload.o obj/src/.libs/scanner.o obj/src/.libs/sctable.o obj/src/.libs/set.o obj/src/.libs/stats.o obj/src/.libs/streams.o obj/src/.libs/stringobj.o obj/src/.libs/syntaxtree.o obj/src/.libs/sysfiles.o obj/src/.libs/sysmem.o obj/src/.libs/system.o obj/src/.libs/tietze.o obj/src/.libs/trans.o obj/src/.libs/vars.o obj/src/.libs/vec8bit.o obj/src/.libs/vecffe.o obj/src/.libs/vecgf2.o obj/src/.libs/vector.o obj/src/.libs/weakptr.o obj/src/.libs/gasman.o -o gap -Wl,--export-dynamic  /home/fac/f/hulpke/gap4/extern/install/gmp/lib/libgmp.so -lz -lreadline -lm -ldl -lutil -Wl,-rpath -Wl,/home/fac/f/hulpke/gap4/extern/install/gmp/lib -Wl,-rpath -Wl,/home/fac/f/hulpke/gap4/extern/install/gmp/lib
    obj/src/.libs/collectors.o:(.data.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
    collect2: ld returned 1 exit status
    make: *** [gap] Error 1

Also, just in case it helps:

    Unix55 /home/fac/f/hulpke/gap4 > make -v
    GNU Make 3.81
    Copyright (C) 2006  Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.
    There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
    PARTICULAR PURPOSE.

    This program built for x86_64-redhat-linux-gnu
    Unix56 /home/fac/f/hulpke/gap4 > gcc -v
    Using built-in specs.
    Target: x86_64-redhat-linux
    Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
    Thread model: posix
    gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC)
    Unix57 /home/fac/f/hulpke/gap4 > uname -a
    Linux tx1.math.colostate.edu 2.6.32-754.18.2.el6.x86_64 #1 SMP Wed Aug 14 16:26:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ChrisJefferson** [comment]
Jumping in, could you try the following patch for Makefile.rules?

```
--- a/Makefile.rules
+++ b/Makefile.rules
@@ -358,7 +358,7 @@ obj/%.lo: %.c cnf/GAP-CFLAGS cnf/GAP-CPPFLAGS libtool
 # Linker rules for gap executable
 ########################################################################
 
-LINK=$(LIBTOOL) --mode=link $(CC) -export-dynamic
+LINK=$(LIBTOOL) --mode=link $(CXX) -export-dynamic
```

This makes us link with the C++ compiler, instead of the C compiler. I actually thought this was always required when you build a program with some C++ code -- although linking often seems like black magic.

**Comment by fingolfin** [comment]
Oh! Yeah, do as @ChrisJefferson  says!

I feel somewhat confused now -- I could have sworn we already use the C++ compiler for linking (which is why I wrote that we did -- but I was writing from my iPad, w/o being able to consult the code at the time).

Hmm, but then, we don't really use any features from the C++ standard library, so strictly speaking, it shouldn't be necessary, which is likely why we got away with using the C compiler for linking. My guess would be that GCC 4.4 had a bug that made it require the Standard C++ library being linked in even for code that doesn't use any of it.

**Comment by hulpke** [comment]
@ChrisJefferson @fingolfin Thank you -- indeed Chris' suggestion solves it for me. (I did a `make clean` and `configure`, I hope that created all files afresh.)

Thank you!

**Comment by hulpke** [comment]
Just in case it is of help, let me mention the following two links (basically the first Google result when searching for the error message):

https://stackoverflow.com/questions/6045809/link-error-undefined-reference-to-gxx-personality-v0-and-g

https://stackoverflow.com/questions/329059/what-is-gxx-personality-v0-for

which describe the issue.
