### ISSUE TITLE
Problem with several root directories containing the same version of a package

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#3663]
@mohamed-barakat had observed the following problem with GAP's package loading mechanism (see https://github.com/oscar-system/GAP.jl/issues/287).
When a GAP package can be found in several root directories, with the same version number, then GAP ignores all except the first instance.
It may happen that the chosen instance cannot be loaded because a compiled module is missing or has been compiled with configuration parameters that do not fit to the GAP in question (with or without Julia, say), whereas another instance would be loadable.

One could argue that GAP should load the first instance that fits, and then the current behaviour could be called a bug.

No matter whether we regard this as a bug or not, I think it would be not difficult to deal with the situation sketched above.
For that,
- GAP must not refuse different package installations with the same version number; this concerns the function `AddPackageInfos`,
- functions such as `DirectoriesPackagePrograms` and `DirectoriesPackageLibrary` must use the installation path instead of the version number as their search criterion (which is anyhow an improvement),
- `InitializePackageInfoRecords` must sort the info records stably, in order to achieve that the loadable instance gets chosen in the first possible root directory.

Do you think this is sensible?

**Comment by fingolfin** [comment]
Seem fine to me.

**Comment by mohamed-barakat** [comment]
For me too.

**Comment by ThomasBreuer** [comment]
O.k., I will create a pull request for the proposed change.

**Comment by DominikBernhardt** [comment]
@ThomasBreuer For some reason this wasn't closed by merging #3668 . Should this remain open?

**Comment by ThomasBreuer** [comment]
@DominikBernhardt Thanks for spotting this. No, the issue should be closed.

**Comment by mohamed-barakat** [comment]
Thank you very much Thomas 👍
