### ISSUE TITLE
GAP job becomes comatose after a couple of days

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#3666]
This is admittedly a problem awkward to reproduce: I am running (under `screen`) a calculation that takes along time, and lots of memory (40GB or so). I attach a file, that can be read into GAP and starts the calculation.
After a couple of days, the job becomes unresponsive -- that is it does not produce further output, and does not react to interruption (short of the double CTR-C kill-all), but processor time still increments. I have tried two machines (one about 3 times faster than the other) and the problem arises not at the same point in the calculation, but after about the same amount of real time. This makes me believe the problem is not some kernel calculation going AWOL, but a different reason.

This issue seems to have arisen relatively recently, so I suspect some recent change is responsible (but it predates the merge of #3656). Any suggestion would be welcome.
[gapcoma.txt](https://github.com/gap-system/gap/files/3627618/gapcoma.txt)

**Comment by ChrisJefferson** [comment]
Can you attach gdb to the process once it hangs and get a backtrace? Once it hangs, do 'gdb -p pid', getting the pid from 'top', or 'ps'.

**Comment by hulpke** [comment]
Thank you so much, @ChrisJefferson 

I get 

    Loaded symbols for /home/fac/f/hulpke/gap4/pkg/io-4.5.1/bin/x86_64-pc-linux-gnu-default64-kv7/io.so
    FuncTzSearchC (self=<value optimized out>, args=<value optimized out>)
        at src/tietze.c:1258
    1258                             if ( ptx[i1] == pty[(jj + ylen1) % ylen] ||
    Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.212.el6_10.3.x86_64 libgcc-4.4.7-23.el6.x86_64 libstdc++-4.4.7-23.el6.x86_64 ncurses-libs-5.7-4.20090207.el6.x86_64 readline-6.0-4.el6.x86_64 zlib-1.2.3-29.el6.x86_64

(and my heart sinks, as it is Tietze transformations which nobody around understands the code of). But that is already of great help, as it lets me localize the problem area. I'll investigate.

**Comment by ChrisJefferson** [comment]
One more gdb suggestion I've found (often) works:

write `print ErrorMayQuit("",0,0)` into gdb and, if you are lucky, the GAP session will be enter the break loop. Sometimes horrible things happen, as we are forcing GAP to return from the kernel in a non-standard place. Also, you aren't going to do anything useful in this GAP session in future :)

**Comment by hulpke** [comment]
I have changed the code to avoid running into this issue -- however I suspect there is some problem in the kernel code of Tietze transformations, which only shows its head in gratuitously extensive use. I close the issue but hope this comment might help if someone finds it by searching
