### ISSUE TITLE
Evaluation of strings inside the function environments

### ISSUE THREAD

**Issue by mohammadfarrokhi** [gap-system/gap#367]
It seems EvalString() cannot recognize local variables defined inside the environment of functions. Here are the corresponding codes:

gap> Eval:=function(x,y,w) return EvalString(w);end;
function( x, y, w ) ... end
gap> Eval(2,3,"x*y");
Error, Variable: 'x' must have a value
not in any function at line 1 of stream
Error, Could not evaluate string.
 called from
EvalString( w ) called from
<function "Eval">( <arguments> )
 called from read-eval loop at line 670 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> quit;
gap> x:=(1,2);;y:=(1,3);;
gap> Eval(2,3,"x*y");
(1,2,3)

**Comment by markuspf** [comment]
Note that this is [documented behaviour](http://gap-system.org/Manuals/doc/ref/chap27.html#X7DE4CCD285440659)

I also do not see an easy way to make this work in the way it is currently implemented.

Can I ask what usecase you have in mind for this?

**Comment by mohammadfarrokhi** [comment]
Thank you for pointing that! 

A typical example is computing the image of a group under an arbitrary word.

**Comment by alex-konovalov** [comment]
@mohammadfarrokhi please describe more precisely what you're trying to do - there may be a better functionality for that already in place. Perhaps you mean calculating a word in a particular group? Is this what you need?

```
gap> f:=FreeGroup("x","y");
<free group on the generators [ x, y ]>
gap> g:=Group((1,2),(1,2,3));
Group([ (1,2), (1,2,3) ])
gap> hom:=GroupHomomorphismByImages(f,g,GeneratorsOfGroup(f),GeneratorsOfGroup(g));
[ x, y ] -> [ (1,2), (1,2,3) ]
gap> w:=Random(f);
x^-1
gap> Image(hom,w);
(1,2)
...
gap> w:=Random(f);
x^-2*y^7
gap> Image(hom,w);
(1,2,3)
```

**Comment by mohammadfarrokhi** [comment]
In my calculations x and y can be any element of the group. Here is an example:

The following two equivalent set of codes compute the image of the group G under the word w="x^2*y^2". The variable image below is used to compute the set {x^2y^2 | x,y belong to G}.

First:
gap> G:=SymmetricGroup(3);;
gap> image:=[];;
gap> for tuple in Tuples(G,2) do
>  x:=tuple[1];
>  y:=tuple[2];
>  AddSet(image,EvalString(w));
> od;
gap> image;
[ (), (1,2,3), (1,3,2) ]

Second:
gap> G:=SymmetricGroup(3);;
gap> image:=[];;
gap> for tuple in Tuples(G,2) do
>  x:=tuple[1];
>  y:=tuple[2];
>  AddSet(image,x^2*y^2);
> od;
gap> image;
[ (), (1,2,3), (1,3,2) ]

The first codes have the benefit that they woks well if the word w varies over a set of words. So, one can simply compute the image of a group G under a collection of words. If EvalString() was capable of working inside a function environment, it was possible to define the first codes, for example, as a function of G and w and use it alternately.

**Comment by ChrisJefferson** [comment]
`EvalString` is never going to be able to read local variables (unless someone does some truely major surgery at the GAP level), due to the implementation design. One option I have used is to use `EvalString` to define a function, which you can then pass your variables into.

For example:

```
gap> q := EvalString("function(x,y) return x*y; end;");
function( x, y ) ... end
gap> q(1,2);
2
```

**Comment by alex-konovalov** [comment]
BTW, the link provided by @markuspf suggested the workaround by defining some dummy global variables and then assigning function arguments to them inside the function before calling `EvalString`.
 
Though I think that for the problem described by @mohammadfarrokhi there may be more elegant solution, in which words would be not strings but proper associative words...

**Comment by markuspf** [comment]
Dear Mohamed,

have a look at the documentation of StraightLineProgram, I believe this solves
your problem.

Cheers,
Markus

**Comment by frankluebeck** [comment]
Hm, @ChrisJefferson suggested:
```
gap> q := EvalString("function(x,y) return x*y; end;");
function( x, y ) ... end
gap> q(1,2);
2
```
But then you don't need `EvalString`:
```
gap> q := function(x,y) return x*y; end;;
function( x, y ) ... end
gap> q(1,2);
2
```
More generally, I think that `EvalString` is very rarely needed.

**Comment by alex-konovalov** [comment]
I think the idea (of @ChrisJefferson) is how to automatically create a function having a string that represents a word - that's why you may want `EvalString`. For example (assuming that all names are  one letter):

```
gap> w:="x^-1*y*x^2*y^12";
"x^-1*y*x^2*y^12"
gap> a:=Set(List( SplitString(w,"*"), x -> x{[1]}));
[ "x", "y" ]
gap> a:=JoinStringsWithSeparator(a,",");
"x,y"
gap> f:=Concatenation("function(",a,") return ", w, "; end;");
"function(x,y) return x^-1*y*x^2*y^12; end;"
gap> q:=EvalString(f);
function( x, y ) ... end
gap> q(6,7);
581334062442
gap> q((1,2),(1,2,3));
(1,3)
```

**Comment by stevelinton** [comment]
The "right" solution is to use words or straight line programmes rather than EvalString. This is much more reliable and flexible. There is documentation at http://www.gap-system.org/Manuals/doc/ref/chap37.html#X7AECA57280DA3195 and in particular there is a constructor that makes a straight line programme from a string which might be exactly what you need.

**Comment by mohammadfarrokhi** [comment]
Yes, it works well! Thanks for the comments!

**Comment by alex-konovalov** [comment]
@mohammadfarrokhi you're welcome!
