### ISSUE TITLE
Regression in cryst package

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3670]
Reported in https://github.com/gap-packages/cryst/issues/14

Presently tests time out - see e.g. https://github.com/gap-packages/cryst/issues/14

They used to work e.g. 6 day ago - see https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-staging/jobs/584771423

Some change in master branch triggered this.

**Comment by fingolfin** [comment]
It seems to hang in `tst/cryst.tst` line 270:
```
gap> List( M{[2,5,7]}, x -> Orbit( G, x, OnPoints ) );;
```
There, `G` is `SpaceGroupOnRightIT(3,208,'1')`.

I bisected the problem to commit 0c67c5af7e75fdbc5cf94628bcdd2d4141538dd5 introduced in PR #3655 by me. I have not yet looked why this breaks. Of course we can just revert that commit, but it'd be good to understand what's going on.

**Comment by gaehler** [comment]
Is due to a changed behaviour of Pcgs - see my comment in https://github.com/gap-packages/cryst#14

**Comment by gaehler** [comment]
Should be fixed in Cryst Release 4.1.21.
