### ISSUE TITLE
Bug in print/view

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#3677]
This bug requires some setup. Firstly do:

```
gap> x := []; for i in [1..10000] do x := [x]; od;
gap> x;
```

Then press ctrl+c to enter the break loop while `x` is printing, then type 'quit;' to exit the break loop.

Now, the `Print` function is broken, and will sometimes print `~`.

```
gap> l := [1,2,3];
[ 1, 2, 3 ]
gap> l;
[ 1, 2, 3 ]
gap> Print(l,"\n");
~
gap> l;
[ 1, 2, 3 ]
gap> Print(l,"\n");
~
gap> Print(l,"\n");
~
gap> 2;
2
gap> Print(l,"\n");
[ 1, 2, 3 ]
gap> Print(l,"\n");
~
```

This is an interaction of a few different things:

* The main bug. The variable `LastPV` is used to record if we are already "in" a `Print` or `View` statement. If we exit while inside a `Print` or `View` statement, this variable is never reset, and we forever think we are still "inside" the `View` which was printing `x`.

* We leave stale values in os->PrintObjThis and os->PrintObjIndex, which get reused when we think we are inside a `View` statement.

**Comment by dimpase** [comment]
yes, this appears to be the cause for the issue - entering the break loop, and, oops...

I actually vaguely recall seeing these "~" in long GAP sessions involving extending memory.

**Comment by ChrisJefferson** [comment]
More complete bug (this particular problem)

IS_ON_PRINT_STACK calculates `STATE(PrintObjDepth)-1`, but `STATE(PrintObjDepth)` is 0, so subtracting `1` gives us maxint. This could cause a horrible crash, but fortunately the first thing in the stack is
