### ISSUE TITLE
New timeouts in polenta and sophus packages

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3687]
This failure is new, may be caused by recent changes in master or package updates:

polenta https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/593827054

sophus: https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/593827068

**Comment by fingolfin** [comment]
This is already fixed by a new polycyclic release from 1-2 days ago

**Comment by alex-konovalov** [comment]
Ok, will check - likely the latency between package release and it's propagation across various archives.

**Comment by fingolfin** [comment]
Resolved
