### ISSUE TITLE
Extend Timeouts with memory limits maybe?

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#373]
The question of cleanly exiting when a calculation runs out of memory arose recently on the forum.

It would not be hard to add `CallWithMemoryLimit(<limit>, <func>, <args>)` along the same lines as 
`CallWithTimeout`.

limit could be absolute or relative, but a relative limit would require a full garbage collection at the start of the computation to convert it into an absolute one.

Such a limit  could only interrupt computation when a full garbage collection has taken place, and the live memory exceeds the threshold. Only at that time do we have a clear idea of how much memory GAP is using.  

There is a risk that GAP could overrun such a limit considerably if no full garbage collection took place.
We could trigger extra garbage collections if a limit was in force, in the extreme case essentially reducing the -o setting to the limit for the duration of the call, but this would hammer performance.

Given all these caveats, is this worth doing?

**Comment by fingolfin** [comment]
See #664 for a suggestion to phase out `CallWithTimeout` again due to major issues with it.

**Comment by fingolfin** [comment]
Resolved by #1324 (which removes the timeout code).
