### ISSUE TITLE
static assertion failed (ABI=32)

### ISSUE THREAD

**Issue by gaehler** [gap-system/gap#3736]
When compiling the current master on Ubuntu 18.04 (gcc 7.4), configured with ABI=32, I get::
```
In file included from src/system.h:23:0,
                 from src/gasman.h:39,
                 from src/objects.h:20,
                 from src/integer.h:16,
                 from src/integer.c:68:
src/debug.h:36:41: error: static assertion failed: "GMP_LIMB_BITS != 8 * sizeof(UInt)"
 #define GAP_STATIC_ASSERT(cond, msg)    static_assert(cond, msg)
                                         ^
src/integer.c:97:1: note: in expansion of macro ‘GAP_STATIC_ASSERT’
 GAP_STATIC_ASSERT(GMP_LIMB_BITS == 8 * sizeof(UInt),
 ^~~~~~~~~~~~~~~~~
cc1: warning: unrecognized command line option ‘-Wno-cast-function-type’
```

**Comment by fingolfin** [comment]
This look as if a 64bit GMP was picked up. Odd, as this should have failed in `configure`. It works well on Travis and in a local test I made, too.

Could you please attach a log which includes the exact `configure` invocation you are using (just `./configure ABI=32` ?) as well as its output, and perhaps also the `config.log` file? Thanks

**Comment by fingolfin** [comment]
Actually, I wonder what GMP is installed on your system. As such, just the output of `grep GMP GNUmakefile` run in the GAP root directory, might already narrow down the issue.

**Comment by gaehler** [comment]
I have both 64bit and 32bit GMP library installed. But I wanted to test the bundled GMP, so I did `./configure --with-gmp=builtin AB=32`, and then also `./configure AB=32`, both with the same result. It seems that in both cases the bundled GMP is built:
```
BUILD_GMP = yes
GMP_CPPFLAGS = -I${abs_builddir}/extern/install/gmp/include
GMP_LDFLAGS = ${abs_builddir}/extern/install/gmp/lib/libgmp.la
GMP_LIBS = 
```
When I configure without `ABI=32`, the system GMP is taken, and everything is fine. Ah, I see: the GMP in `extern/install/gmp` is still 64bit, and not removed by `make clean`

**Comment by fingolfin** [comment]
Indeed, that was my suspicion. Does it work if you remove `extern/install` and try again?

In general, building the bundled GMP is a bit dodgy; getting this perfectly safe and correct either requires a lot of (usually superfluous rebuilding of GMP from scratch), or a full-blown mini package manager. But using the bundled GMP is something that's mostly meant as convenience for people who are either non-technical, and thus have trouble installing GMP on their system, or else who do not have permissions to do so. Moreover, very few if any people these days should ever build GAP deliberately in 32bit mode on 64bit systems anyway -- there is simply no good reason other than "I have only 2 GB of RAM and 32bit GAP uses a bit less memory" (but then, why are you running a 64bit OS??). Therfore, I don't think it's a high priority to make this peculiar usage scenario safe.

That said, if somebody wants to try it anyway, I am happy to review the PR :-). Two approaches to tackle this come to mind:
1. Adjust the `gmp:` target in `Makefile.rules` resp. the `cnf/build-extern.sh` script to detect if the ABI differs and then force a re-configure and rebuild.
2. Simply always force a full rebuild of GMP and other stuff build as part of every run of `configure`, by inserting the appropriate `rm -rf` calls at the end of `configure.ac`

**Comment by gaehler** [comment]
Yes, removing `extern/install/gmp` solved the problem. I was a bit surprised that `make clean` doesn't do this.

**Comment by fingolfin** [comment]
The question of how much `make clean` should remove is one without good answer. That said, I don't mind changing it to also remove `extern/install` and `extern/build`, as I never use GAP's bundled GMP, so I personally. won't be inconvenienced by it.

**Comment by fingolfin** [comment]
Closing this, as I don't think there is anything specific to be done here, other than perhaps changing what `make clean` does, but that's already in issue #4148
