### ISSUE TITLE
Optimise loop counters in permutat.cc

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#3739]
As @ChrisJefferson noticed in a small thread starting here https://github.com/gap-system/gap/pull/3721#discussion_r345262552, there are several loops in `permutat.cc` of the form:
```
for (i = 1; i <= limit; i++) {
  <do something involving i - 1>
}
```
Someone with the desire may as well, at some point, change these so that the loop does
```
for (i = 0; i < limit; i++) { <do something involving i> }
```
for the small performance gain, where it makes sense.

**Comment by fingolfin** [comment]
Note that the optimizer might actually take care of this, so it might not change anything. I still agree it would be a good change, though.

**Comment by wilfwilson** [comment]
Good point.
