### ISSUE TITLE
Direct product of automorphism groups when one factor is <IdentityMapping>

### ISSUE THREAD

**Issue by cdwensley** [gap-system/gap#3748]
Not sure whether this is a real issue or whether I should not be using IdentityMapping. 

Observed behaviour: 
```
gap> c3 := Group( (1,2,3) );;
gap> ac3 := AutomorphismGroup( c3 );;
gap> c2 := Group( (4,5) );;
gap> ac2 := Group( IdentityMapping( c2 ) );; 
gap> dp := DirectProductOp( [ac2,ac3], ac2 );;
gap> gens := GeneratorsOfGroup( dp );
[ DirectProductElement( [ <object>, <object> ] ), 
  DirectProductElement( [ <object>, [ (1,2,3) ] -> [ (1,3,2) ] ] ) ]
gap> IsGroupHomomorphism( gens[1] );
false
gap> ids := [ One(ac2), One(ac3) ];
[ IdentityMapping( Group([ (4,5) ]) ), IdentityMapping( Group([ (1,2,3) ]) ) ]
gap> DirectProductElement( ids );
DirectProductElement( [ <object>, <object> ] )
```

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.10.2 of 19-Jun-2019
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin17.4.0-default64-kv3
 Configuration:  gmp 6.0.0
 Loading the library and packages ...
 Packages:   AClib 1.3.1, Alnuth 3.1.1, AutoDoc 2019.05.20, AutPGrp 1.10, 
             Carat 2.2.3, CRISP 1.4.4, Cryst 4.1.19, CrystCat 1.1.9, 
             FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.2.dev, IO 4.6.0, 
             IRREDSOL 1.4, LAGUNA 3.9.3, Polenta 1.3.8, Polycyclic 2.14, 
             PrimGrp 3.3.2, RadiRoot 2.8, ResClasses 4.7.2, SmallGrp 1.3, 
             Sophus 1.24, TransGrp 2.0.4, utils 0.67dev
 ```

EDITED to make snippets readable

**Comment by cdwensley** [comment]
GitHub has removed lots of "<object>"s in the output above.  
Trying again to see whether the same happens: 
gap> gens := GeneratorsOfGroup( dp );
[ DirectProductElement( [ <object>, <object> ] ), 
  DirectProductElement( [ <object>, [ (1,2,3) ] -> [ (1,3,2) ] ] ) ]
gap> DirectProductElement( ids );
DirectProductElement( [ <object>, <object> ] )

**Comment by cdwensley** [comment]
Yes, once again "[ \langle object \rangle", \langle object \rangle ]" has become "[ , ]".

**Comment by ChrisJefferson** [comment]
If you put code between lines with 3 backticks (one backtick is `, and I can't write more or github will do things) you can dump code nicely.

```
gap> c3 := Group( (1,2,3) );;
gap> ac3 := AutomorphismGroup( c3 );;
gap> c2 := Group( (4,5) );;
gap> ac2 := Group( IdentityMapping( c2 ) );;
gap> dp := DirectProductOp( [ac2,ac3], ac2 );;
gap> gens := GeneratorsOfGroup( dp );
[ DirectProductElement( [ <object>, <object> ] ), 
  DirectProductElement( [ <object>, [ (1,2,3) ] -> [ (1,3,2) ] ] ) ]
gap> IsGroupHomomorphism( gens[1] );
false
gap> ids := [ One(ac2), One(ac3) ];
[ IdentityMapping( Group([ (4,5) ]) ), IdentityMapping( Group([ (1,2,3) ]) ) ]
gap> DirectProductElement( ids );
DirectProductElement( [ <object>, <object> ] )
```

**Comment by hulpke** [comment]
I'm not sure I understand what is the issue here. Is it how the object is displayed? Or is it a wrong object?

**Comment by cdwensley** [comment]
I'm only slowly working our what the real issue is.  Here is a revised example: 
```
gap> c3 := Group( (1,2,3) );;         
gap> ac3 := AutomorphismGroup( c3 );; 
gap> dp := DirectProduct( ac3, ac3 );;
gap> g1 := GeneratorsOfGroup( dp )[1];
DirectProductElement( [ [ (1,2,3) ] -> [ (1,3,2) ], <object> ] )
gap> g2 := GeneratorsOfGroup( dp )[2];
DirectProductElement( [ <object>, [ (1,2,3) ] -> [ (1,3,2) ] ] )
gap> g1*g2;
DirectProductElement( [ [ (1,2,3) ] -> [ (1,3,2) ],
 [ (1,2,3) ] -> [ (1,3,2) ] ] )
gap> IsGroupHomomorphism( g1 );
false
```
So, yes, I was confused by the IdentityMapping on c3 being displayed as 
```
<object>
```
Could this be improved? 
Secondly, it probably makes little sense to construct the direct product of an automorphism group with, say, a permutation group.  But, if A is a group of automorphisms of G, similarly B on H, then one might expect that AxB is constructed as a group of automorphisms of GxH. 
Clearly DirectProduct does not claim any such thing at present.  Any thoughts on this?

**Comment by fingolfin** [comment]
So the "problem" then is that there is no `ViewString` method for the identity mapping:
```
gap> id:=IdentityMapping(SymmetricGroup(3));
IdentityMapping( Sym( [ 1 .. 3 ] ) )
gap> ViewObj(id);
IdentityMapping( Sym( [ 1 .. 3 ] ) )
gap> ViewString(id);
"<object>"
```
That would be easy enough to fix.

**Comment by cdwensley** [comment]
Method for String attempted in PR #3753. 
Where should any test go?

**Comment by hulpke** [comment]
@cdwensley 

> But, if A is a group of automorphisms of G, similarly B on H, then one might expect that AxB is constructed as a group of automorphisms of GxH.

I don't think this is a plausible assumption. If you take $S_3$ as group of automorphisms of the set {1,2,3}, then $S_3\times S_3$ is not represented as automorphisms of this set but as automoirphisms of {1..6}.

More generally, a group generated by homomorphisms does not automatically get the flag `IsGroupOfAutomorphisms` set, as this is potentially an expensive test.

There is of course no problem in haveing a dedicated function that embeds the automorphisms of the factors in a group of automorphisms of the direct product.

**Comment by cdwensley** [comment]
I meant to imply that G,H were groups. 
I'm planning to add an operation DirectProductOfAutomorphismGroups to Utils, which will do what is needed for XMod developments.

**Comment by cdwensley** [comment]
DirectProductOfAutomorphismGroups now in utils-0.68 released 2019/11/22.
