### ISSUE TITLE
HPC-GAP doesn't support CallWithTimeout

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#377]
During the recent GAP -> HPC-GAP merge (#375), I disabled the code to handle using timers. @rbehrends comments on how this should be correctly implemented [here](https://github.com/gap-system/gap/pull/331#issuecomment-154221726).

In general, care must be taken with how alarms and threads interact.

**Comment by fingolfin** [comment]
See #664 for a suggestion to phase out `CallWithTimeout` again due to major issues with it.

**Comment by fingolfin** [comment]
We removed CallWithTimeout, so this is now obsolete.
