### ISSUE TITLE
Computation of automorphism group of very large group can cause crash to desktop

### ISSUE THREAD

**Issue by Frightning** [gap-system/gap#3774]
I have been able to cause my install of GAP 4.10.2 (32-bit via .exe installer on Windows 10) to crash straight to the desktop without any error message or warning.
To do this, I did the following series of computations (computing the automorphism series of a finite group for a few steps, eventually constructing a very large and then attempting to construct automorphism group). After only a few minutes of running time, GAP crashes. No error message, memory warning, etc. I have GAP set to warn me if it tries to use more than 2gb of ram (and have 16gb of system ram, so there's no lack of physical memory).

Instructions to reproduce:
I start with a group in the SmallGroups library, then compute it's automorphism group. Which happens to be of order 1536. Because of this, IdSmallGroup is not available, and the only way to continue efficiently is to convert to a PermutationGroup (or alternatively PcGroup), I chose the former via the NiceObject command. I then iteratively compute automorphism group and then nice object until reaching a very large (of size~2 quadrillion!). The computation of A4 and G4 took at least a minute combined, so expect it to take a while. Attempting to compute A5 as shown however will crash GAP to desktop after a few minutes.
```
gap> G:=SmallGroup(384,17948);
<pc group of size 384 with 8 generators>
gap> A1:=AutomorphismGroup(G);
<group of size 1536 with 7 generators>
gap> G1:=NiceObject(A1);
<permutation group of size 1536 with 7 generators>
gap> A2:=AutomorphismGroup(G1);
<group of size 6144 with 8 generators>
gap> G2:=NiceObject(A2);
<permutation group of size 6144 with 8 generators>
gap> A3:=AutomorphismGroup(G2);
<group of size 196608 with 11 generators>
gap> G3:=NiceObject(A3);
<permutation group of size 196608 with 11 generators>
gap> A4:=AutomorphismGroup(G3);
<group of size 2078076976496640 with 7 generators>
gap> G4:=NiceObject(A4);
<permutation group of size 2078076976496640 with 7 generators>
gap> A5:=AutomorphismGroup(G4);
```
This behavior is consistently reproducible for me. I would expect an error message of some kind at the very least, if not entering the break loop so I can at least abandon the attempt if it has somehow failed. The group G4 is not solvable, so maybe this has something to do with it?

**Comment by hulpke** [comment]
Dear @Frightning 
Would you be willing to tell us your name and where you're from?

Thank you,

  Alexander Hulpke (Colorado State)
[I am replying, as I am the person who wrote the code.]

**Comment by wucas** [comment]
Okay @Frightning 
I just tried your example and for me the calculation eventually (after about 8min CPU time, based on top) hits the pre-set memory limit of 2G. And then I get the normal warning/breakloop. When I resume it hits 3G. But I am on MacOS and 64bit.
```
% ./gap -o 2g -K 3g
 ┌───────┐   GAP 4.10.2 of 19-Jun-2019
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin18.6.0-default64-kv3
 Configuration:  gmp 6.1.2
 Loading the library and packages ...
 Packages:   AClib 1.3.1, Alnuth 3.1.1, AtlasRep 2.1.0, AutoDoc 2019.05.20, AutPGrp 1.10, 
             Browse 1.8.8, Carat 2.2.3, CRISP 1.4.4, Cryst 4.1.19, CrystCat 1.1.9, CTblLib 1.2.2, 
             FactInt 1.6.2, FGA 1.4.0, Forms 1.2.5, GAPDoc 1.6.2, genss 1.6.5, IO 4.6.0, 
             IRREDSOL 1.4, LAGUNA 3.9.3, orb 4.8.2, Polenta 1.3.8, Polycyclic 2.14, PrimGrp 3.3.2, 
             RadiRoot 2.8, recog 1.3.2, ResClasses 4.7.2, SmallGrp 1.3, Sophus 1.24, SpinSym 1.5.1, 
             TomLib 1.2.8, TransGrp 2.0.4, utils 0.63
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> G:=SmallGroup(384,17948);
<pc group of size 384 with 8 generators>
gap> A1:=AutomorphismGroup(G);
<group of size 1536 with 7 generators>
gap> G1:=NiceObject(A1);
<permutation group of size 1536 with 7 generators>
gap> A2:=AutomorphismGroup(G1);
<group of size 6144 with 8 generators>
gap> G2:=NiceObject(A2);
<permutation group of size 6144 with 8 generators>
gap> A3:=AutomorphismGroup(G2);
<group of size 196608 with 11 generators>
gap> G3:=NiceObject(A3);
<permutation group of size 196608 with 11 generators>
gap> A4:=AutomorphismGroup(G3);
<group of size 2078076976496640 with 7 generators>
gap> G4:=NiceObject(A4); <permutation group of size 2078076976496640 with 7 generators>
gap> A5:=AutomorphismGroup(G4);
Error, reached the pre-set memory limit
(change it with the -o command line option) in
  bimg := OnTuples( bimg, S.transversal[bimg[1]] )
 ; at /Users/lucas/Projects/gap-4.10.2/lib/ghomperm.gi:109 called from 
ImageSiftedBaseImage( S, OnTuples( BaseStabChain( S ), elm ), S.idimage, OnRight 
 ) at /Users/lucas/Projects/gap-4.10.2/lib/ghomperm.gi:1008 called from
ImageElm( map, elm ) at /Users/lucas/Projects/gap-4.10.2/lib/mapping.gi:818 called from
act( p, gen ) at /Users/lucas/Projects/gap-4.10.2/lib/oprt.gi:1024 called from
orbish( G, pnt, gens, acts, act ) at /Users/lucas/Projects/gap-4.10.2/lib/oprt.gd:857 called from
Orbit( au, r ) at /Users/lucas/Projects/gap-4.10.2/lib/morpheus.gi:516 called from
...  at *stdin*:10
you can 'return;'
brk> 
gap: will not extend workspace above -K limit, bye!
```

**Comment by fingolfin** [comment]
My guess would be that 32bit Windows version runs out of memory and crashes. Note that 32bit apps cannot possibly access more than 4GB of RAM, and on most operating systems are limited even more, e.g. to just 2 GB or sometimes 3 GB.

So: just switch to using the 64bit GAP version.

**Comment by hulpke** [comment]
This is likely an issue of 32-bit Windows.
Reducing the permutation degree (`G4` has a faithful representation of degree 624) will substantially reduce memory requirements.

**Comment by Frightning** [comment]
My name is Justin Benfield. I am from the state of Oregon, USA.
Good to know that on Mac OS X, 64-bit it actually gives error/warning message I would expect. That is not happening on my install on Win 10 and that is the reason I bothered with an error report here.

I should also mention that in some similar computations I have had it enter the break loop complaining that the Collector is not large enough (not sure what that is within GAP exactly but it caught my attention), will have to hunt for an example of that behavior if that's worth having.

How would I effect the reduction in degree if I wanted to try and get this computation to work (what GAP commands)?

**Comment by fingolfin** [comment]
@Frightning Please just use the 64bit Windows version of GAP. I know it has a scary "experimental" label, but that can be safely ignored (and in the new GAP release, will be removed). It's been running solid for many people over many years now.

**Comment by fingolfin** [comment]
(Or even better: Use Linux or macOS versions -- Windows support is least good of all, simply because none of the GAP developers use Windows, resp.: while a lot of people seem to use GAP on Windows, sadly very few apparently are capable and/or willing to help improve it on Windows)

**Comment by Frightning** [comment]
This is what my GAP banner looks like:
 ┌───────┐   GAP 4.10.2 of 19-Jun-2019
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: i686-pc-cygwin-default32-kv3
 Configuration:  gmp 6.1.2, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.1, Alnuth 3.1.1, AtlasRep 2.1.0, AutoDoc 2019.05.20, AutPGrp 1.10, Browse 1.8.8, CRISP 1.4.4,
             Cryst 4.1.19, CrystCat 1.1.9, CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, Forms 1.2.5, GAPDoc 1.6.2,
             genss 1.6.5, IO 4.6.0, IRREDSOL 1.4, LAGUNA 3.9.3, orb 4.8.2, Polenta 1.3.8, Polycyclic 2.14,
             PrimGrp 3.3.2, RadiRoot 2.8, recog 1.3.2, ResClasses 4.7.2, SmallGrp 1.3, Sophus 1.24, SpinSym 1.5.1,
             TomLib 1.2.8, TransGrp 2.0.4, utils 0.63
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap>

**Comment by fingolfin** [comment]
@Frightning that just confirms what we knew: you are using a 32bit Windows version. Don't do that.

**Comment by hulpke** [comment]
Dear @Frightning 
Thank you for telling us your real name. (I really prefer knowing whom I talk to rather than anonymous avatars.)
As for your question, a brute force way of reducing the degree would be

  repeat Gold:=G;G:=Image(SmallerDegreePermutationRepresentation(G));until G=Gold;

As for the concrete problem, alas this will likely not be enough.  I am currently testing your example with improvements to the automorphism group code I have been working on, but the calculation still takes excessive memory. The issue in question is to represent automorphism groups of factors as permutation groups.

**Comment by fingolfin** [comment]
@Frightning please let us know if switching to the 64bit version helped.

Other than that, I don't think there's anything left to be done on this issue.
