### ISSUE TITLE
Wrong line reporting in the warning about variadic functions

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#378]
I've seen this in the logs
```
Syntax warning: New syntax used -- intentional? in /mnt/disk2/hudson-slave/wor\
kspace/GAP-dev/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/packagesload/label/64bit/\
GAP-git-snapshot/pkg/qaos/gap/helper.gi line 67
    for i in hook do
      ^
```
Indeed, the function to which this refers has the following formatting:
```
RunHookWithArg :=
  function(hook,arg)
    local i;
    for i in hook do
      arg := i(arg);
    od;
    return arg;
  end;
```
May be fine to ignore though, since the warning will disappear in the public release...

**Comment by stevelinton** [comment]
I'd incline to ignore. It would not be very easy to fix and as you say, it will go away after the betas.

**Comment by alex-konovalov** [comment]
@stevelinton thanks - just to be sure that this doesn't point to something then should be fixed. Will close then.
