### ISSUE TITLE
Segfault core dumped on randomized computation of the size of a large group

### ISSUE THREAD

**Issue by mojishoki** [gap-system/gap#3781]
Hi,

### Observed behaviour
I have been trying to compute the size of a group generated by 2 random elements from the large symmetric group `G:= SymmetricGroup(10000)` and I am trying to do so using the MonteCarlo version of the algorithm with accuracy 1/1000 (which, I believe, is what `StabChainOptions(H).random := 1`  does).

 I first got memory errors for which I decided to increase memory allocated to 8GB (I have 16GB). But somewhere around 2GB, I get a `Segmentation fault (core dumped)` error. 

![image](https://user-images.githubusercontent.com/48044321/70590965-475d7c80-1b89-11ea-8722-7e1a57c72bb2.png)

### Expected behaviour
The same code for the smaller symmetric group of size 1000 for __three__ generators runs in less than 1hr20min on a core i7 6700K. 

### My setup
I am using Windows 10 pro 64bit. To increase the memory, I had to install cygwin32 (32 instead of 64 because GAP uses 32) and I am running GAP as an administrator through cygwin terminal `mintty.exe` inside my cygwin\bin folder.

Thanks in advance.

**Comment by ChrisJefferson** [comment]
cygwin64 should let you use more memory. Cygwin32 is limited by the operating system to 2GB. Could you retry with the 64 bit GAP?

**Comment by ChrisJefferson** [comment]
Also, another thing you should do, to make your problem faster (this is unrelated to the bug).

There is an extremely good chance you are making the symmetric group or alternating group on 10,000 points. To check this:

1) Use 'MovedPoints' on H to check if H moves all the points on [1..10000] (it almost certainly will).

2) Use 'IsNaturalSymmetricGroup' and 'IsNaturalAlternatingGroup', to check if the group is the symmetric or alternating group (the 'Natural' checks you have SymmetricGroup(10000), not just some group which is isomorphic to a symmetric group).

These functions will be much faster, and once you know your group is not the symmetric or alternating group, GAP will calculate a stabilizer chain much faster and with much less memory.

**Comment by fingolfin** [comment]
You seem to be using the 32bit version of GAP. Don't. Get the 64bit Windows version, please (it annoyingly is labelled as "experimental", you can safely ignore that)

**Comment by fingolfin** [comment]
The 32bit version can't use more than 2 GB RAM

**Comment by mojishoki** [comment]
Thanks everyone, I downloaded the 32 bit version because it was not experimental. But you are right 64 bit version works fine.
