### ISSUE TITLE
HPCGAP Challenge

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#38]
The following short test breaks hpcgap in a number of different ways. 

```
check := function(g)
    local  x;
    for x in g do
        if Order(x) > 1 and Order(x) mod 2 = 1 then
            return x;
        fi;
        return fail;
    od;
end;

checks := function(maker, stride, start, limit)
    local  i, x;
    for i in [start, start + stride .. limit -1 - ((limit-1) mod stride) + start] do
        x := check(maker(i));
        if x <> fail then
            return x;
        fi;
    od;
    return fail;
   
end;

tasks := function(m,n) 
    return List([1..m], i->RunTask(checks, j->SmallGroup(n,j), m, i, NrSmallGroups(n)));
end;
```

For various values of m and n I get errors reading files, creating types and from the collectors. If we could make this work I think we would have made a lot of progress.

**Comment by alex-konovalov** [comment]
Just a comment on the status of the Small Groups Library. It is organised by layers, and each layer is responsible for some selection of orders. At the moment, layers 2-8 and 10-11 are done: they were reworked to make it possible to call `NrSmallGroups` and `SmallGroup` from multiple threads. It remains to do layer 9 still (groups of order p^n>3125 for n=4,5,6). 

Thus, if you are getting an error while reading files from the small groups library, it's likely points to a bug in that reworking, which would be nice to isolate to be reproducible without using `check` and `checks`. Could you give me several values of `n` where you are observing the problem?

**Comment by stevelinton** [comment]
The limit of the range in checks should be:

```
 limit - ((limit-start) mod stride)
```

**Comment by stevelinton** [comment]
Problem seems to have fixed itself :-)

**Comment by alex-konovalov** [comment]
I've applied some more stress testing, and I can reproduce the problem with `tasks(32,256)` - the message says that the library file 'sml256.i' must exist and be readable, called from `READ_SMALL_FUNCS[i]( Concatenation( str2, ".", str3 ) );` on line 349 of file `hpcgap/small/small.gi`.

With `tasks(12,256)` I've got even more puzzling
```
#W dlopen() error: dlopen(/Users/alexk/GITREPS/hpcgap/bin/x86_64-apple-darwin13.4.0-gcc-hpc/compiled/small/small2/b/sml256.so, 9): image not found
```
- of course there is a file `.so` in the library, but why GAP tries to call `dlopen`???

**Comment by stevelinton** [comment]
The reason it calls dlopen is that it thinks it has found 
/Users/alexk/GITREPS/hpcgap/bin/x86_64-apple-darwin13.4.0-gcc-hpc/compiled/small/small2/b/sml256.so

which is the canonical place to find a compiled version of the library file which is then loaded automatically. This feature should probably be removed (it dates back to when compiling the library seemed like a good idea.

Of course the real bug is that detection of whether files exist seems to be erratic in HPCGAP when mukltiple threads are doing it. This suggests a race of some kind in system code.

**Comment by ChrisJefferson** [comment]
The function SyFindGapRootFile is highly suspicious, it uses a static buffer and returns a point to it. Am going to look at removing the static buffer, just because it probably should be removed anyway.

**Comment by alex-konovalov** [comment]
In the most recent HPC-GAP all examples that were failing yesterday seem to run nicely. With `tasks(10,3^7)` there are error messages about collectors not being reentrant etc. - perhaps worth to keep this issue open for stress-tests of PRs #69 and #74.

**Comment by alex-konovalov** [comment]
Running tasks `(10,3^7)` now leads to the following error:
```
--- Switching to thread 5
[5] collector is not reentrant called from
[5] Error, CollectWordOrFail( col, v, w 
[5]  ) on line 417 of file /Users/alexk/GITREPS/hpcgap/lib/rwspcclt.gi called from
[5] CollectWord( sc, av, y 
[5]  ); on line 294 of file /Users/alexk/GITREPS/hpcgap/lib/rwspcsng.gi called from
[5] SingleCollector_Solution( sc, gn[i], id 
[5]  ) on line 813 of file /Users/alexk/GITREPS/hpcgap/lib/rwspcsng.gi called from
[5] SingleCollector_MakeInverses( cc 
[5]  ); on line 172 of file /Users/alexk/GITREPS/hpcgap/lib/rwspccoc.gi called from
[5] UpdatePolycyclicCollector( col 
[5]  ); on line 445 of file /Users/alexk/GITREPS/hpcgap/lib/rwspcclt.gi called from
[5] ...  at line 1742 of /Users/alexk/GITREPS/hpcgap/small/small2/sml256.a
[5] you can 'quit;' to quit to outer loop, or
[5] you can 'return;' to continue
[5] brk> 
```

**Comment by stevelinton** [comment]
This seems to have been reduced to then known problems with collectors. Whether or not these are no fixed.  I see no merit in keeping it open.
