### ISSUE TITLE
HPC-GAP build broken

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#381]
HPC-GAP build is broken again.

This is because the gap_version.h header is built too late and ward fails because of that.

**Comment by rbehrends** [comment]
PR #383 should fix this. In a way, this is a bit of a band aid, because `system.c` now gets rebuilt every time because the version header changes every time it is being compiled (because `GAP_BUILD_DATE` is different for every run).

**Comment by markuspf** [comment]
I think a band aid is good enough right now, since hopefully we'll get to renovating the build system soon, and I think this version header is also due for an overhaul.

**Comment by markuspf** [comment]
I merged #383 since it indeed fixed this.
