### ISSUE TITLE
Make CurrentAssertionLevel thread local

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3821]
Right now, `CurrentAssertionLevel` is global. I think this is problematic in HPC-GAP (ping @rbehrends @stevelinton). So I suggest we make it thread local instead.

The easiest way to do that would be to remove it as a GAP variable, and instead put it into the kernel, as a member of the thread local `GAPState`. That would also require moving `SetAssertionLevel` and `AssertionLevel` from the library to the kernel, but that's easy. I can't think of any downsides?

**Comment by rbehrends** [comment]
The only potential problem I can see is that code that depends on the current gvar (and bypasses `AssertionLevel()` and `SetAssertionLevel()` would break. But I don't know any code that would do that? (The documentation describes `CurrentAssertionLevel` as unpublished, but one cannot always rely on user code adhering to that.)

Other than that, that looks like a sensible change. It would probably also make checking the assertion level in GAP code slightly faster.
