### ISSUE TITLE
RepresentativeAction returns incorrect element

### ISSUE THREAD

**Issue by sTertooy** [gap-system/gap#3832]
### Observed behaviour

```
gap> G := SmallGroup(252,34);;
gap> f := GeneratorsOfGroup(G);;
gap> imgs := [ f[1]*f[5]^6, f[1]*f[2]*f[3]^2*f[4]^2*f[5]^6, f[3]^2, f[3]*f[4]^2, Identity(G) ];;
gap> phi := GroupHomomorphismByImages(G,G,f,imgs);;
gap> twicon := 	function ( g, h ) return h*g*( h^phi )^-1; end;;
gap> g := RepresentativeAction(G,f[1],f[3],twicon);;
gap> twicon(f[1],g) = f[3];
false
```

### Expected behaviour
One would expect ``true``. The returned element ``g`` seems to be incorrect.

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.10.2 of 19-Jun-2019
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv3
 Configuration:  gmp 6.1.2
 Loading the library and packages ...
 Packages:   AClib 1.3.1, Alnuth 3.1.1, AtlasRep 2.1.0, AutoDoc 2019.05.20, 
             AutPGrp 1.10, CRISP 1.4.4, Cryst 4.1.19, CrystCat 1.1.9, 
             CTblLib 1.2.2, FactInt 1.6.2, FGA 1.4.0, GAPDoc 1.6.2, 
             IRREDSOL 1.4, LAGUNA 3.9.3, Polenta 1.3.8, Polycyclic 2.14, 
             PrimGrp 3.3.2, RadiRoot 2.8, ResClasses 4.7.2, SmallGrp 1.3, 
             Sophus 1.24, SpinSym 1.5.1, TomLib 1.2.8, TransGrp 2.0.4, 
             utils 0.63
```

**Comment by ChrisJefferson** [comment]
One problem with actions in GAP is (from the manual):

"In GAP, groups always act from the right, that is μ( μ( x, g ), h ) = μ( x, gh ). GAP does not test whether the acting function μ satisfies the conditions for a group operation but silently assumes that is does. (If it does not, results are unpredictable.)"

Your function doesn't satisfy this condition. It acts on the left instead I think.

**Comment by sTertooy** [comment]
Ah, my apologies, I completely overlooked this - this indeed seems to be the issue. Thanks!
