### ISSUE TITLE
Comparison of Cyclotomics to Floats and Integers is weird

### ISSUE THREAD

**Issue by DominikBernhardt** [gap-system/gap#3835]
Let `cyc := -E(8)+E(8)^3`. Mathematically, `cyc = Sqrt(2)` holds. In GAP, we have the following behaviour:
```
gap> cyc < 2;
false
gap> cyc < 2.;
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `<' on 2 arguments at /Users/dominik/gap/lib/methsel2.g:249 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at *stdin*:17
type 'quit;' to quit to outer loop
```
I feel like the first comparison should either also throw an error saying that you shouldn't compare cyclotomics to integers or return the correct result.

**Comment by fingolfin** [comment]
Actually, we already throw such errors when comparing floats to rationals:
```
gap> 1 = 1.;
Error, Comparison of float and 1 is not supported. Please refer to the manual section on floats for details at GAPROOT/lib/float.gi:1007
gap> 1 < 1.;
Error, Comparison of float and 1 is not supported. Please refer to the manual section on floats for details at GAPROOT/lib/float.gi:1007
```

So to resolve the issue here, one just needs to install those methods more broadly. And ideally add some tests for it, too.

**Comment by DominikBernhardt** [comment]
To clarify: I take it you would like a method in `lib/cyclotom.gi` with similar mechanic to 
` InstallMethod( \<, "for rational and float", [ IsRat, IsFloat ], -1, COMPARE_FLOAT_ANY );` from `lib/float.gi`?

**Comment by fingolfin** [comment]
Even simpler, I'd just change those existing methods.

**Comment by ThomasBreuer** [comment]
@DominikBernhardt I do not understand what you mean with "the correct result".
The documentation defines how cyclotomics are compared via `\<` (see Section "Comparison of Cyclotomics").
This covers the comparison of cyclotomics and integers, since integers *are* cyclotomics.
It is clear that this comparison does not and cannot coincide with the mathematical relation < on the real axis.

**Comment by fingolfin** [comment]
I completely missed the first part of this question, about comparing cyclotomics and integers; my previous comments were exclusively about comparing cyclotomics and floats.

On integers vs "proper" cyclotomics, I agree with @ThomasBreuer

**Comment by fingolfin** [comment]
I think there is no issue here? Closing
