### ISSUE TITLE
GAP online help on Windows using browser does not navigate to the precise location

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#3836]
Opening the GAP online help on Windows using browser opens the right chapter, but does not navigate to the precise location on that page, specified by `#`.

_Originally posted by @alex-konovalov in https://github.com/gap-system/gap/issues/3667#issuecomment-533482093_

**Comment by fingolfin** [comment]
@ChrisJefferson remarked on #3667 that
> This page ( https://stackoverflow.com/questions/13852867/how-to-open-html-file-with-anchor-in-c-sharp-with-default-browser ), suggests doing sticking `file://` on the start of the filename, like `file://C:/g.ivank.net/index.html#3:1-2,2-3`, should fix it, but i cant test it due to lack of windows install here.

To which a user responded that it helped resolve the issue for them.

@alex-konovalov pointed out that this is the place to fix the issue: https://github.com/gap-system/gap/blob/8aff4472a6b76afcb71b3a7bc0004ca29999c651/lib/helpview.gi#L68-L86

**Comment by alex-konovalov** [comment]
I've tried that and it does not work. Also, can't find the user confirmation, and not sure if that worked at all indeed.
