### ISSUE TITLE
bug in view for words in a free group

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#3845]
The following happens in GAP 4.10.2 as well as in the current master branch.

```
gap> f:= FreeGroup( ["x","y"] );;
gap> x:= f.1;;  y:= f.2;;
gap> w1:= y^7*x*y*x*y^3*x*y*x;
y^4*(y^2*(y*x)^2)^2
gap> w2:= y^-7*x*y^16;
y^-7*x*y^16
gap> w:= w1 * w2;
y^4*(y^2*y^16^2)^2*y^-7*x*y^16
```

(The way how `w1` and `w2` are viewed is correct, but the way `w` is viewed is wrong.)

**Comment by fingolfin** [comment]
This regression is also in GAP 4.9, but not in GAP 4.8.  It was introduced before the HPC-GAP merge and the new build system. I'm now bisecting it.

**Comment by fingolfin** [comment]
The regression was introduced by commit b2d2bb21ddf6c8c3c60431786ea41fc5d345e080 (ping @hulpke)
