### ISSUE TITLE
Conjugacy action of the quotient group

### ISSUE THREAD

**Issue by gllndr** [gap-system/gap#3855]
I'm new to GitHub and GAP, so if I make some huge mistakes don't be too upset.

I have a normal cyclic subgroup N of G with cyclic quotient G/N and I want to compute the exponent of the conjugacy action of G/N on N but I can't manage to construct conjugacy classes or conjugates of an element.

**Comment by fingolfin** [comment]
So... If I understand it right, you want to compute the exponent of the image of the map `G -> Aut(N)` given by the conjugacy action of `G` (or equivalently, `G/N`) on `N`? 

It all depends a bit on your actual inputs. But a straightforward, albeit somewhat naive way to do this, would be like this:
```
gap> G:=SymmetricGroup(3); N:=AlternatingGroup(3);
Sym( [ 1 .. 3 ] )
Alt( [ 1 .. 3 ] )
gap> H:=Group(List(GeneratorsOfGroup(G), g -> ConjugatorAutomorphism(N, g)));
<group with 2 generators>
gap> Exponent(H);
2
```

**Comment by fingolfin** [comment]
@gllndr does that answer your question? If so, please close this issue; if not, please tell us what is missing.
