### ISSUE TITLE
Trivial action on a quotient

### ISSUE THREAD

**Issue by gllndr** [gap-system/gap#3860]
Given a group G and its p-core V I computed the set of pairs (𝜎, 𝜏) ∈ G^2 such that 𝜏^𝜎 = 𝜏^p;

The images of 𝜎 and 𝜏 in G/V generate G/V.

Now I want to create a function that given this set of pairs tells me if every 𝜏 (where (𝜎, 𝜏) is a pair) acts trivially on V/W where W is the Frattini subgroup.

The function returns 0 if this is true and 1 otherwise.

TG is the function creating the set of pairs.

This is my code:

```
TD:=function(G,p)
    local i,x,l,V,W,t;
    t:=0;
    l:=TG(G,p);
    V:=PCore(G,p);
    if IsAbelian(G) and Order(G/V)=1 then
        t:=1;
        return t;
    fi;
    W:=FrattiniSubgroup(V);
    for i in [1..Size(l)] do
        for x in Elements(V/W) do
            if x^l[i][2]<>x then
                t:=1;
                return t;
            fi;
        od;  
    od;
    return t;
end;
```

But when I run it, for some groups I get this error:

```
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `^' on 2 arguments at /home/gap/inst/gap-4.10.1/lib/methsel2.g:250 called from
x ^ l[i][2] at stream:13 called from
<function "TD">( <arguments> )
 called from read-eval loop at stream:1
```

**Comment by gllndr** [comment]
Actually I already changed my code and it seems to work:

`TD:=function(G,p)`
    local i,x,y,l,V,W,t,hom;
    t:=0;
    l:=TG(G,p);
    V:=PCore(G,p);
    W:=FrattiniSubgroup(V);
    hom:=NaturalHomomorphismByNormalSubgroup(V,W);
    for i in [1..Size(l)] do
        for x in Elements(V) do
            y:=x^l[i][2];
            if Image(hom,y)<>Image(hom,x) then
                t:=1;
                return t;
            fi;
        od;  
    od;
    return t;
end;`

**Comment by fingolfin** [comment]
Good, then I assume this is resolved. Of course iterating over `V` instead of `V/W` performs a lot more work if `W` is large, but that's wasn't your question... :-) And I already described how to do it more efficiently.
