### ISSUE TITLE
Error, repeated further fixpoint in sanity check

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3868]
A new error occurs in the sanity check in the master branch of GAP:
```
12,295,64,150
testing group [A(6)^2]2=A(6)wr2
conjugacy classes
rational classes
automorphism group
Error, repeated further fixpoint -- ambiguity at /circa/scratch/gap-jenkins/workspace/GAP-master-sanity/GAPCOPTS/64build/la\
bel/kovacs/GAP-master-snapshot/lib/morpheus.gi:2415 called from
Build step 'Execute shell' marked build as failure
```
This worked a week ago.

**Comment by alex-konovalov** [comment]
@hulpke could this be coming from your new code?

**Comment by hulpke** [comment]
I don;'t think it should be the new code, as this is completely separate. It might be a side-effect of recent changes that generically tried less aggressive permutation degree reduction, but here such reduction might be needed. I have a fix.
