### ISSUE TITLE
SmallerDegreePermutationRepresentation(G)

### ISSUE THREAD

**Issue by cdwensley** [gap-system/gap#3915]
This is a query about section 43-3.2 of the GAP 4.11.0 manual. 
Firstly, it appears to imply that G should be a transitive group, but: 
    
    gap> G := Group((1,2,3)(4,5,6), (7,8,9)(10,11,12));;
    gap> SmallerDegreePermutationRepresentation(G);     
    [ (1,2,3)(4,5,6), (7,8,9)(10,11,12) ] -> [ (1,2,3), (4,5,6) ]

Secondly, there is mention of using a 'cheap' option, but no example is given so it is not obvious what syntax should be used. 
Thirdly, it appears that there is an undocumented function ReducedPermdegree.  It would be helpful to the uninitiated, assuming that this is not an experimental function, for this to be documented and for some comparison between the two functions to be discussed.

**Comment by hulpke** [comment]
I do not understand why `G` should be transitive. There is no requirement or guarantee given about it.

`cheap` is an option, and thus is called using the standard option mechanism, appending `:cheap` to the argument list:

    SmallerDegreePermutationRepresentation(G:cheap);

Thirdly, there is a description of `ReducedPermdegree` (which is used internally) in grpperm.gd. I do not think it is powerful/good enough to be used in general and adding it to the manual will probably cause more confusion than help. The uninitiated should stay with `SmallerDegreePermutationRepresentation`.

**Comment by cdwensley** [comment]
My point was that the manual entry starts off with "Let G be a permutation group that acts transitively on its moved points." which seems to imply, incorrectly, that G must be (effectively) transitive. 
I am not familiar with the "G:cheap" syntax - no doubt I should be - which was why I was suggesting an example should be included. 
I am happy to stick to SmallerDegreePermutationRepresentation - thanks for the explanation.

**Comment by fingolfin** [comment]
I agree with @cdwensley that "that acts transitively on its moved points." in the first sentence of the `SmallerDegreePermutationRepresentation` documentation is misleading, and would suggest we remove it.

**Comment by hulpke** [comment]
@fingolfin Yes. This sentence described the old situation. I have changed it as part of #3916 
Alas I am experiencing weird timeout and package loading problems by the travis tests for this PR that seem to have no relation to the actual code changes.
