### ISSUE TITLE
Checking for presence of O_DIRECTORY and O_CLOEXEC. 

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#3918]
Trying to build GAP on [ARCHER](https://www.archer.ac.uk/) with @raemarina @IrynaRaievska and @marioa, and observing this:

```
src/iostream.c: In function 'StartChildProcess':
src/iostream.c:396: error: 'O_DIRECTORY' undeclared (first use in this function)
src/iostream.c:396: error: (Each undeclared identifier is reported only once
src/iostream.c:396: error: for each function it appears in.)
src/iostream.c:396: error: 'O_CLOEXEC' undeclared (first use in this function)
make: *** [obj/src/iostream.lo] Error 1
```

As @fingolfin said, that means that default glibc is more than 10 years old and 
>  that's a regression we should fix in GAP: we detect the presence of `posix_spawn` and want to use it, but don't check for presence of `O_DIRECTORY` and `O_CLOEXEC`. .. In the meantime, a workaround might be to remove the test for `posix_spawn` from `configure.ac`.

**Comment by fingolfin** [comment]
Indeed: the proper fix is to check for those two constants in `configure`, and use that together with the presence/absence of `posix_spawn` to control which code `iostream.c` uses.

The suggested workaround is meant for people who encounter this bug right now and can't wait for a fix: they can edit their copy of `configure.ac` to remove the named line, then `make` again (this requires `autoconf` present; if that is not the case, other workarounds are possible, but they are similar complex to the actual fix, which I can work on later)

**Comment by raemarina** [comment]
module load autotools

autoconf --version
autoconf (GNU Autoconf) 2.69

autoconf and then make

We get:

obj/src/.libs/profile.o: In function `InformProfilingThatThisIsAForkedGAP':
/home/d155/d155/maryna/gap-4.11.0/src/profile.c:390: undefined reference to `endsWithgz'
collect2: ld returned 1 exit status
make: *** [gap] Error 1

**Comment by ChrisJefferson** [comment]
Sorry, my fault.

Remove the '#ifdef HAVE_POPEN' and '#endif' from around the function endsWithgz (it should be around line 338 in file profile.c).

Leave the HAVE_POPEN in fopenMaybeCompressed and fcloseMaybeCompressed just below.
