### ISSUE TITLE
GC problems in 4.11.0

### ISSUE THREAD

**Issue by jamesjer** [gap-system/gap#3919]
I am trying to build GAP 4.11.0 for Fedora Rawhide.  I am having issues with the garbage collector.  The initial build used the default gasman collector.  That worked fine on all architectures except aarch64 (the 64-bit ARM architecture).  GAP 4.10.2 did not have any issues on aarch64.  With 4.11.0, the executable and documentation built successfully, but many tests failed like this:
```
$ make check
/builddir/build/BUILD/gap-4.11.0/bin/gap.sh --quitonbreak -b -m 100m -o 1g -q -x 80 -r -l /builddir/build/BUILD/gap-4.11.0 -A  tst/testinstall.g
You should start GAP4 using `gap -A -x 80 -r -m 100m -o 1g -K 2g'.
Architecture: aarch64-redhat-linux-gnu-default64-kv7
testing: /builddir/build/BUILD/gap-4.11.0/tst/testinstall/ConjNatSym.tst
     148 ms (28 ms GC) and 23.8MB allocated for ConjNatSym.tst
testing: /builddir/build/BUILD/gap-4.11.0/tst/testinstall/DirectProductElement\
.tst
########> Diff in /builddir/build/BUILD/gap-4.11.0/tst/testinstall/DirectProdu\
ctElement.tst:2
# Input is:
START_TEST("DirectProductElement.tst");
# Expected output:
# But found:
Error, Length: <list> must be a list (not a function body bag)
########
     106 ms (91 ms GC) and 655KB allocated for DirectProductElement.tst
testing: /builddir/build/BUILD/gap-4.11.0/tst/testinstall/ElmsBlist.tst
########> Diff in /builddir/build/BUILD/gap-4.11.0/tst/testinstall/ElmsBlist.t\
st:1
# Input is:
START_TEST("ElmsBlist.tst");
# Expected output:
# But found:
Error, Length: <list> must be a list (not a integer)
########
     127 ms (82 ms GC) and 4.33MB allocated for ElmsBlist.tst
```

All of the failures refer to START_TEST.  A little experimentation shows that the problem happens at this line in START_TEST: `GASMAN( "collect" );`.  I can try this week to get access to aarch64 hardware to debug the problem, but would appreciate any ideas on what might be going wrong.

I considered using an alternate GC.  Julia is only available on x86, so that doesn't help.  I built with Boehm GC.  That failed because we are now using gcc 10, which defaults to -fno-common, and the version of Boehm GC bundled by GAP has multiple definitions of the same variable.  I added -fcommon to the build flags, and the build succeeded on all 64-bit architectures, including aarch64, but failed on both 32-bit architectures (i686 and 32-bit ARM).  On both platforms, the documentation building step failed:
```
$ make manuals
doc/make_doc
--------------------
Building GAP manuals
--------------------
Error before error-handling is initialized: 
[ 
  "Record: '<rec>.(<obj>)' <obj> must be a string or a small integer (not a lar\
make: *** [Makefile.rules:791: doc] Error 1
```

So my last resort, if none of these problems can be debugged, is to build with the gasman collector on some architectures (i686 and 32-bit ARM, at least) and boehm gc on others (aarch64, at least).  Any guidance or suggestions you can offer are much appreciated.  Thank you.

**Comment by ChrisJefferson** [comment]
We don't currently test on aarch64. Could you get me access to such a machine, or is there a sensible way to get one of reasonable power (raspberry pi or something similar?)

**Comment by fingolfin** [comment]
@ChrisJefferson not directly relevant, but we *do* have the possibility to test aarch64 via Travis, see my PR https://github.com/gap-system/gap/pull/3744 (there are issues, but nothing like the severe GC failures reported here)

@jamesjer don't bother trying with Boehm GC or Julia GC. They are for special purposes only, and should at this point not be used for a regular GAP.

For debugging this, it would be helpful to get the `config.log` GAP produces (can be attached here), as well as the full output of `configure` (can also be attached, or pasted into a comment). Thank you!

**Comment by fingolfin** [comment]
I also have a Raspberry Pi with which I could test tonight -- though last time I tried, it worked fine. In the end, it might also be something that depends on the precise Linux distro in use (difference in the compiler, C lib, etc.), and/or the specific hardware (not all AArch64 CPUs are the same, after all!). 

So, could you please also tell us what AArch64 hardware this is running on? Or perhaps the tested is made using qemu?

**Comment by ChrisJefferson** [comment]
I'm happy to test with qemu if someone can give me instructions to get it running -- I tried earlier but only found old guides that didn't work.

**Comment by jamesjer** [comment]
I haven't yet managed to get direct access to an aarch64 machine, I'm afraid.  Fedora has a couple of test machines that are supposed to be used for such purposes, but both have been rejecting ssh connection attempts for the last few days.  I have filed an issue with the Fedora staff asking for this to be fixed, but haven't heard back yet.  If I don't hear from them in the next 12 hours or so, I will try to do a build with qemu myself.  Right now, all I can do is lob sources at the Fedora build machines and then read the build logs afterward.

I suspect that this behavior will only be reproducible with gcc 10, which Fedora recently switched to.  It may even prove to be an aarch64-specific bug in gcc 10, but that will require some investigation.

I did a few test builds today, and can now tell you that adding --enable-debug makes the problem go away.  I suspected that this was due to disabling __attribute__((always_inline)), so I tried patching system.h to do that directly.  However, the build failed the same way.  I also tried reducing the optimization level to -O1, but that made the documentation building step fail like this:
```
#I Finally the HTML version . . .
#I First run, collecting cross references, index, toc, bib and so on . . .
#I Table of contents complete.
#I Producing the index . . .
#I Writing bibliography . . .
#I Second run through document . . .
Panic in src/gasman.c:2120: Gasman found a bogus header
make: *** [Makefile.rules:791: doc] Error 1
```
which again makes me suspect a gcc bug.  I'll need a machine where I can run a debugger to really figure out what is going on though.  Hopefully tomorrow....

**Comment by ChrisJefferson** [comment]
Thanks for keeping us up to date. I'll warn you that my instinct is this bug will be quite hard to track down (I'm happy to be proved wrong), because usually by the time we find gasman corruption, the bug happened a long time ago.

Please keep us up to date, and in particular if you can figure out what is causing the problems, that will make it easier to figure out what is wrong (I'll hold off buying an ARM machine, until we are reasonably sure it is required, and would let me reproduce the bug).

**Comment by fingolfin** [comment]
All these bugs suggest that objects were freed prematurely by the GC. Which is why I asked for a config.log and the output of the configure script, as those can contain hints for what's going on.

If the issue really only happens with GCC 10, I won't be able to reproduce it right now. It also could be that GCC is doing nothing wrong, but simply is the first compiler were our streak of good luck that ensured GASMAN keeps working is breaking: we always relied on memory addresses used by the active code to resides on the stack, or in registers (and that calling `setjmp` spills those registers onto the stack). There are any number of code transformations that could break these assumptions (e.g. the compiler could always stores values XORed against a random bit pattern on the stack; or call to `setjmp` without a matching `longjmp` could be compiled away (though we took safeguards against that). Or the require stack alignment could be misdetected (see `StackAlignBags`; that's information I could have learned from config.log / configure output); and more. It's hard to tell which it is w/o access to a system were one can reproduce this interactively.

**Comment by ChrisJefferson** [comment]
Sanity check, do you mean gcc-10, I can't find that as a release, or even a branch in the gcc git.

**Comment by fingolfin** [comment]
@ChrisJefferson there is a GCC 10 dev version listed on https://gcc.gnu.org

**Comment by ChrisJefferson** [comment]
I quickly tried on gcc 10 dev, and it works fine on x86_64, so it must be an arm issue, possibly (or possibly not) requiring gcc 10.

**Comment by jamesjer** [comment]
Sorry for the delay.  Life has been far from normal recently.  I got shell access to an aarch64 machine late last week, and ran a git bisect over the weekend.  We are indeed using a GCC 10 dev version.  The GCC developers frequently use Fedora as a testbed before making an official release.  I have only seen problems on the aarch64 platform; every other architecture works fine.

It turns out that 3 git commits are involved.  With e68d9394025cdc57b1c54c4f0ef536c239236c3c, we start to see segfaults and failing tests now and then while running package test suites.  That commit just adds a lot of "static" keywords, nothing more.

With ac79ff04e8491d41c5882fbf535d26bba352ba8f, the recursion depth test starts to fail.  I noticed that the arguments to the mod operator (%) in that commit differ in sign.  I changed the code to read "UInt depth = (UInt)IncRecursionDepth();" and the test passed again.  It would be good to check that the value of depth is really nonnegative before that cast, of course.  Unrelated, but I also note that on 64-bit platforms, the change to funcs.c in that commit requires that the value read from RecursionDepth be truncated from 64 to 32 bits (so it will fit into an "int"), then sign extended back to 64 bits again (so it can be returned as an "Int").  If there is no reason to do that, the compiler can emit more efficient code if depth is declared as an "Int" (or omitted entirely).

The very next commit, a02f6d427091f28ab02e7f81cd5320ee0fa36337 is where GAP's own testsuite starts to fail in a big way.  That commit reverts 579456e2b292ea4c8978e70fd6b2b68fc734b824, which is right after e68d9394025cdc57b1c54c4f0ef536c239236c3c, yet I don't see that behavior when checking out the earlier commit.  There must have been some other change in between that aggravates the situation.

At the very least, I suspect that there is an aarch64-specific inlining bug in gcc.  I'll have to do some more work, but I think the fact that adding "static" keywords is the initial trigger supports that hypothesis.  There may be more bugs involved, of course, but I'm going to chase that possibility first.

**Comment by jamesjer** [comment]
I just did a build with the `UInt depth` change noted above, plus a change to system.h to disable `__attribute__((always_inline))`, and with `-fno-inline` added to the build flags.  All GAP tests passed successfully.  I did a couple of package builds; datastructures and profiling were segfaulting reliably, but now they pass all tests.

**Comment by ChrisJefferson** [comment]
Thanks so much for looking into this.

The inlines could be hiding a more subtle GC related issue (they sometimes do). However, if we can at least fix things for now by globally disabling inlining, that's great.


The recursion depth does sometimes become negative, as we don't perfectly keep track of it. We could make another attempt to really track it more carefully, but also fix things up for now.

**Comment by jamesjer** [comment]
I had time over the weekend to poke at this again.  I added NOINLINE markers to a bunch of functions, verified that the problem was gone, then started removing them.  I managed to get down to a single NOINLINE, on GenStackFuncBags in src/gasman.c.  I tried checking for undefined behavior with `-fsanitize=undefined`, but that currently has a fatal bug on aarch64 (https://bugzilla.redhat.com/show_bug.cgi?id=1816795).  I guess the next step is to inspect GenStackFuncBags manually to see if anything looks suspicious.  Failing that, I will ask the gcc developers to take a look.

**Comment by jamesjer** [comment]
Here's some wild speculation, unsupported by any actual facts.  When GenStackFuncBags is not inlined, the "mark from registers, dirty dirty hack" happens to work.  When it is inlined into CollectBags, the register pressure becomes great enough that some pointer to a garbage collected object is spilled into one of the scratch registers (x1-x18) or one of the vector registers.  These are not saved by setjmp; quoting from `/usr/include/bits/setjmp.h` on an aarch64 system:
```
/* Jump buffer contains:
   x19-x28, x29(fp), x30(lr), (x31)sp, d8-d15.  Other registers are not
   saved.  */
__extension__ typedef unsigned long long __jmp_buf [22];
```
The result is that the object thus pointed to is not marked, it is collected, and then we try to access it via the now invalid pointer.

I have absolutely no evidence whatsoever to support that.

**Comment by fingolfin** [comment]
Interesting, and also somewhat worrying. Hm. 

Out of curiosity, I wonder if you could also test the `master` branch, as the GC code calling `GenStackFuncBags` was refactored a bit. Not that I think it will actually be better, but I am curious: `CollectBags` was split into several functions there, the call to `GenStackFuncBags` is now in `CollectBags_Mark`. 

Of course if some registers are being used that are not saved by `setjmp`, we might have a more serious issue on ours hand on the long anyway. On the other hand, I am not sure how this squares with the C standard: all values must be restorable, so either the data in those scratch registers would have to be discardable, or recomputable from elsewhere (and setjmp/longjmp would have to perform that recomputation, which seems rather unlikely).

So for now, I am still tempted to consider this as a potential compiler bug. That said, this whole business is rather tricky, so I'd not at all be surprised if I (and our code) was wrong...

BTW, of course we can add that NOINLINE to our code, I am not at all arguing against that; but as usual, it'd be best to fully understand what's wrong to prepare for future instances of this :-).

**Comment by fingolfin** [comment]
I  mean, who knows: maybe GCC now even detects that we call `setjmp` without a matching `longjmp` and decides it can optimize that away? Perhaps the fact that `RegsBags` is static, and only accessed by `GenStackFuncBags` and its caller, means that once `GenStackFuncBags` is inlined into the caller, it reasons something like "phew, they are accessing `RegsBags` which contains the `setjmp` state, but that's undefined behavior [is it?!? I didn't think so, but C compilers keep surprising us in nasty ways on that regard], so let's do whatever we want instead" ?

**Comment by jamesjer** [comment]
Master branch builds and runs all tests successfully without any added NOINLINE markers.  That's good news.  What would you like me to do?  Short of disassembling CollectBags and trying to make sense of aarch64 assembly code, I'm not sure what to do next.

**Comment by fingolfin** [comment]
For the immediate future: you could just add the NOINLINE to the GAP 4.11.0 source code and go on with that, I guess? Feel free to also submit a PR to add this into the `stable-4.11` branch so it'll be in GAP 4.11.1 from the start (if you don't have time for that, we'll take care of it).

It would still be good to get to the bottom of this, even if `master` works; because the question remain, *why* does it work, and why doesn't 4.11.0 work? I am racking my brain and can't come up with a good explanation... Let's wait till tomorrow to see if @ChrisJefferson has a brilliant idea. If not, it would actually be interesting to submit this to the GCC developers as a potential bug. Alas, I am not sure how well that'll work if we can't reduce the issue to a much smaller code that reproduce it (GCC devs likely are not that interested in digging into the GAP GC code... but if you happen to have a good connection to them, perhaps you could ask?).

**Comment by ChrisJefferson** [comment]
I don't have any good suggestions. We are dancing with undefined behaviour here, so there was always the chance it would break when we started digging into setjmp/longjmp.

One thought, there are caller/callee saved registers on arm, so I'm trying to figure out if you might need to make a couple of function calls to make sure everything gets saved out fully? But as you said earlier @fingolfin , we need to be able to 'longjmp' back, so how can there be something not saved?

**Comment by fingolfin** [comment]
Hmm, I wonder if the change in https://github.com/gap-system/gap/pull/3952 might be related -- it fixes a warning in clang in the code that scans the `jmp_buf`. Perhaps gcc (?) considers that code to be UB (undefined behaviour) and then pulls of one of these "UB means I can do whatever I want, e.g. nothing, wheeeee, FAST CODE!!!"... :-). Might be interesting to get hands on disassembly of `GenStackFuncBags`. @jamesjer any chance you could provide that?

In the meantime, there was a similar report by Bill Allombert who works on the Debian package. No idea which compiler he used, though.

If adding `NOINLINE` solves the issue, I suggest we add this as a workaround for now, but leave this issue open until we fully understand the problem.

**Comment by ChrisJefferson** [comment]
We are also violating reading one type as another. We could fix that UB by doing some memcpying, but this might be hard to test via travis.

**Comment by fingolfin** [comment]
Bill Allombert read the GC source code comments and pointed out the following, with which I agree:
> Looking at the comment in gasman.c this seems to be a correct fix:
> 
> src/gasman.c: 1623:
> 
> > Note that a
> > compiler may save  a register  somewhere else  if   it wants to  use this
> > register for something else.  Usually  this register is saved further up
> > the  stack,  i.e.,   beyond the   address  of  the  local variable, and
> > 'GenStackFuncBags' would not see this value any more.   To deal with this
> > problem, 'setjmp' must be called *before* 'GenStackFuncBags'  is entered,
> > i.e.,  before the  registers may have been saved  elsewhere.   Thus it is
> > called from 'CollectBags'.
> >
> > To deal with this problem, 'setjmp' must be called *before*
> > 'GenStackFuncBags'  is entered, i.e.,  before the  registers may have
> > been saved  elsewhere.   Thus it is called from 'CollectBags'.
> 
> However, if GenStackFuncBags is inlined inside CollectBags, then it is 
> not actually called so the provisio that 'setjmp' must be called
> *before* 'GenStackFuncBags' is not satisfied. In particular the compiler
> does not have to follow the usual caller-saved/callee-saved register
> convention for function call.
> 
> So I would suggest to mark GenStackFuncBags NOINLINE on all plateforms.

I've therefore made PR #3965.

**Comment by jamesjer** [comment]
It sounds like you've figured out the issue, which is great.  Do you still want a `GenStackFuncBags` disassembly?  I can provide that if you are interested.
