### ISSUE TITLE
Bug in parser for floats

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#392]
Discovered by @rbehrends. In a new GAP session:
```
gap> .n;
fail
```

**Comment by ChrisJefferson** [comment]
This comes from the parser being too lax about parsing float point numbers. We store them as strings during parsing, and need to be stricter about what we accept.

We also nowhere seem to document what we actually do accept (or I just can't find it). I believe the intended format as

` ( -?( [0-9]+(.[0-9]*)? )|(.[0-9]+) ) ([eEqQdD]-?[0-9]+)?`

Or in words, a number of one of the following forms (optionally negative by adding a - on front)

123
123.
123.456
.456

Followed by optionally an e,E,q,Q,d or D, and an integer to denote exponent.

There are more things accepted by the function 'Float', such as `NAN` and `INF`, and `Float` doesn't take the `qQdD` modifiers.

**Comment by ChrisJefferson** [comment]
This seems to be intentional, but I'm not sure what the aim was, so I'm investigating with the original writers.

**Comment by alex-konovalov** [comment]
This will be fixed by PR #394 after it will be merged - thanks @ChrisJefferson

**Comment by ChrisJefferson** [comment]
Now fixed
