### ISSUE TITLE
VERSION file in packages conflicts with C++20 on Macs

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#3942]
From the issue: https://github.com/libsemigroups/libsemigroups/issues/131 . This problem also effects the profiling package https://github.com/gap-packages/profiling/issues/80

Basically, C++20 introduces a header called `version`. Quite a lot of packages have a file called `VERSION` in their root directory which (as macs are case-insensitive) seems to be causing a conflict.

Many, many packages are released with a `VERSION` file, so I suggest (while encouraging developers to release new versions without a VERSION file), we delete the VERSION file from packages when we release GAP. On an initial scan, it looks like only 2 packages depend on this file existing: DeepThought and meataxe64.

**Comment by ChrisJefferson** [comment]
Of course, someone with a mac and an up-to-date enough libc++ could also see exactly what packages this is breaking.

**Comment by fingolfin** [comment]
That conflict should only matter on macOS, though.

And most packages with a VERSION file don't build C++ code. Only a single digit number of packages does that.

And for those, adjusting the CPPFLAG to not include the package root dir should be sufficient to "fix" them

**Comment by fingolfin** [comment]
I just had a look myself, and I see lots and lots of packages that use their `VERSION` file. A typical use is for GAPDoc title pages: 
```
EDIM-1.3.5/doc/edim.xml:19:      Version <#Include SYSTEM "../VERSION">
ExamplesForHomalg-2019.09.02/doc/title.xml:30:  <Version>Version <#Include SYSTEM "../VERSION"></Version>
GaussForHomalg-2019.09.02/doc/title.xml:18:      Version <#Include SYSTEM "../VERSION">
Gauss-2019.09.02/doc/Gauss.xml:20:      Version <#Include SYSTEM "../VERSION">
GradedModules-2020.01.02/doc/title.xml:32:  <Version>Version <#Include SYSTEM "../VERSION"></Version>
GradedRingForHomalg-2020.01.02/doc/title.xml:20:  <Version>Version <#Include SYSTEM "../VERSION"></Version>
HomalgToCAS-2019.12.08/doc/title.xml:34:  <Version>Version <#Include SYSTEM "../VERSION"></Version>
IO_ForHomalg-2019.09.02/doc/title.xml:37:  <Version>Version <#Include SYSTEM "../VERSION"></Version>
LocalizeRingForHomalg-2019.09.02/doc/title.xml:19:  <Version>Version <#Include SYSTEM "../VERSION"></Version>
MatricesForHomalg-2020.01.02/doc/title.xml:31:  <Version>Version <#Include SYSTEM "../VERSION"></Version>
Modules-2019.09.02/doc/title.xml:32:  <Version>Version <#Include SYSTEM "../VERSION"></Version>
RingsForHomalg-2019.12.08/doc/title.xml:40:  <Version>Version <#Include SYSTEM "../VERSION"></Version>
SCO-2019.09.02/doc/title.xml:16:      Version <#Include SYSTEM "../VERSION">
ToolsForHomalg-2019.09.02/doc/title.xml:32:  <Version>Version <#Include SYSTEM "../VERSION"></Version>
forms/doc/forms.xml:37:<#Include SYSTEM "../VERSION">
fwtree-1.3/doc/main.xml:14:<#Include SYSTEM "../VERSION">
fining/doc/fining.xml:35:      <#Include SYSTEM "../VERSION">
homalg-2019.09.01/doc/title.xml:31:  <Version>Version <#Include SYSTEM "../VERSION"></Version>
```
Of course they could (should?) instead use AutoDoc to generate their title pages, but that's a major effort and I don't have time to push that, so we have to hope for package authors to eventually do it; or somebody has to volunteer to either submit issues requesting this, or PRs, to all involved packages.

Yet others use it in their `configure.ac` -- a practice I am trying to get rid of, but again I've not yet tried to submit systematic PRs to all packages. Though a few may already have this "fixed" in their repository.
```
DeepThought-1.0.2/configure.ac:12:AC_INIT([DeepThought], m4_esyscmd([tr -d '\n' < VERSION]))
anupq-3.2.1/configure.ac:5:AC_INIT([ANU p-Quotient Program], m4_esyscmd([tr -d '\n' < VERSION]), [https://github.com/gap-packages/anupq/issues], [anupq], [http://gap-packages.github.io/anupq/])
ferret-1.0.2/configure.ac:12:AC_INIT([ferret], m4_esyscmd([tr -d '\n' < VERSION]))
json-2.0.1/configure.ac:12:AC_INIT([json], m4_esyscmd([tr -d '\n' < VERSION]))
nq-2.5.4/configure.ac:5:AC_INIT([ANU Nilpotent Quotient Program], m4_esyscmd([tr -d '\n' < VERSION]), [https://github.com/gap-packages/nq/issues], [nq], [http://gap-packages.github.io/nq/])
semigroups-3.2.3/configure.ac:12:AC_INIT([semigroups], m4_esyscmd([tr -d '\n' < .VERSION]))
profiling-2.2.1/configure.ac:12:AC_INIT([profiling], m4_esyscmd([tr -d '\n' < VERSION]))
digraphs-1.1.1/configure.ac:12:AC_INIT([digraphs], m4_esyscmd([tr -d '\n' < .VERSION]))
```

**Comment by fingolfin** [comment]
There are other things that reference `VERSION` but those are the major ones.

**Comment by fingolfin** [comment]
At the same time, very few of these packages contain C++ code. In fact I see only four with a VERSION file and a C++ kernel extension: `ferret`, `json`, `semigroups`, `profiling`. Three are by @ChrisJefferson and I think all four are by now fixed anyway?

So, what remains to be done about  this "issue"? Can it be closed?

**Comment by ChrisJefferson** [comment]
Yup, I mainly wanted to make an issue so it didn't get lost, in case it was important.

**Comment by fingolfin** [comment]
I 100% agree it was a good idea to make an issue out of it. That it turned out to be not as bad as initially feared is good, but couldn't be known from the start :-)
