### ISSUE TITLE
Incorrect rendered formula for semiring

### ISSUE THREAD

**Issue by albert-github** [gap-system/gap#3984]
I'm not sure how the API documentation for GAP is generated, but seen the comments and commands it looks like it is done by doxygen (or something alike).

In the file `pkg/semigroups-3.2.3/libsemigroups/include/semiring.hpp` we have around line 41 the following comment:
```
  //! * Mulitplication is left and right distributive over addition, i.e.
  //! \f$a \times (b + c) = a \times b + a \times c\f$ and \f$(a + b)
  //! \times c = (a \times c) + (b \times c)\f$ for all \f$a,b,c\in R\f$;
```
when using doxygen on this (see e.g. https://fossies.org/dox/gap-4.11.0/classlibsemigroups_1_1Semiring.html Detailed Description) a bit a strange formula (with `//!` in it) appears and later on some code appears that should be text.
The cause of this is the comment conversion from `//!` to `/**` comments by doxygen and the fact that an inline formula (`\f$`) is split over multiple lines and code in an inline formula is seen as is and not manipulated so the `//!` remains.
The best / easiest solution is just to keep the inline formula on one line:
```
  //! * Mulitplication is left and right distributive over addition, i.e.
  //! \f$a \times (b + c) = a \times b + a \times c\f$ and 
  //! \f$(a + b) \times c = (a \times c) + (b \times c)\f$ for all \f$a,b,c\in R\f$;
```

**Comment by fingolfin** [comment]
@albert-github you seem to be talking about code of the libsemigroups project, which is not part of GAP itself (it is used by a package that is shipped with GAP, sure, but the core GAP team knows nothing about it and has nothing to do with it). So the GAP issue tracker is not the right place to report issues with it. Try https://github.com/libsemigroups/libsemigroups instead.

**Comment by fingolfin** [comment]
And that page https://fossies.org/dox/gap-4.11.0/index.html is really... weird. Mostly contains unreadable noise and seems to have little to no value. We didn't put this data there, and were never asked to agree to it either, so we bear no responsibility for it.

**Comment by albert-github** [comment]
Thanks for the pointer to the official place of the semigroups package.

I know that you are not involved in it / responsible for it (and I'm not holding you responsible in any way). It is a brute force attempt to create API documentation from a source tree, as not all projects are setup to be used with doxygen some extra files (like txt files) might and give indeed some weird results. This said a lot of information can be retrieved about the API from those pages.

**Comment by fingolfin** [comment]
> This said a lot of information can be retrieved about the API from those pages.

I believe you, but have a hard time understanding how that is possible. The file list is 99% useless chap*txt files, and for the C code it mashes together code from the kernel, packages and 3rd party libraries.

In contrast it is trivial to just run doxygen on the GAP kernel , and it produces reasonable output.

**Comment by albert-github** [comment]
This is correct, but as said a brute force attempt is made to run over the entire GAP software.
