### ISSUE TITLE
Migrate from travis-ci.org -> travis-ci.com

### ISSUE THREAD

**Issue by mohamed-barakat** [gap-system/gap#3988]
Now that more computer algebra systems and packages are on travis.com I suggest doing the migration for gap as well. The team at travis is very helpful once one encounters problems migrating, responding within a day.

**Comment by alex-konovalov** [comment]
I don't like authorising access to private repositories without a need (you can convince me that it's fine in this case, though). Also, the correct URLs are https://travis-ci.org/ and https://travis-ci.com/.

**Comment by mohamed-barakat** [comment]
Maybe I did not understand your critique but you can limit access to selected repos, e.g., just grant access to `https://github.com/gap-system/gap/`.

**Comment by alex-konovalov** [comment]
@mohamed-barakat when I am trying to sign in into travis-ci.org with GitHub, I see this:

![Screenshot 2020-04-27 at 12 04 33](https://user-images.githubusercontent.com/5751387/80365357-5bc3bc80-887f-11ea-8d1e-fceaf370347c.png)

This looks to me like too much, so far did not sign in. Why do I need to let them access to MY private repositories?

**Comment by mohamed-barakat** [comment]
I now understand what you mean. Is it possible to add another user that has enough admin access to `gap-system/gap` and let this user register to travic-ci.com?

**Comment by alex-konovalov** [comment]
This @gap-docker-bot ?

**Comment by mohamed-barakat** [comment]
Yes :)

**Comment by alex-konovalov** [comment]
But won't using another account be less convenient for people with admin rights on their own accounts - they will have to log in under another account to make changes or trigger/stop a build?

Also, what do you mean by "Now that more computer algebra systems and packages are on travis.com" argument? How this will be beneficial for GAP? This is not a portal where someone goes to find different computer algebra systems. Or do you mean some other use cases in mind?

**Comment by mohamed-barakat** [comment]
One strong argument is that travis-ci.org will be shut down anyway at some point in the future. This is why they are motivating people to migrate to travis-ci.com

Since more and more people are logged on on travis-ci.com it makes it easier for them to follow the GAP builds there, rather than being logged on two different sites.

![image](https://user-images.githubusercontent.com/871986/80393683-23d56d00-88b1-11ea-903c-eeac1c05acea.png)

**Comment by fingolfin** [comment]
Several things to note:

- I've been thinking about this for > 1 year, when they originally announced this migration. Which they then postponed, and then stopped communicating about. They always announce things and then sometimes follow through, sometimes not. I think we should consider moving off of Travis entirely, now that there are good alternatives, i.e., GitHub Actions.

- That said, for this particular thing, in the end the main work involved is to go through a bunch of repositories (well, a couple hundred if we count in `gap-packages` and `gap-infra`)  and replace `travis-ci.org` by `travis-ci.com`
- @alex-konovalov I don't know where you are getting this from (and who is "travis-pro") -- the official way to integrate with Travis CI has been [their marketplace app](https://github.com/marketplace/travis-ci) for quite some time now, and this has already been setup for our orgs, including gap-system, so on that front, nothing changes

- In the meantime, I am not aware of any official plans by them to shut down travis-ci.org, and thus no urgency with any of this @mohamed-barakat do you? link?

**Comment by fingolfin** [comment]
To trigger the migration go to https://travis-ci.org/organizations/gap-system/repositories and click on "Sign up for the beta". The fact that they still call this a beta is another sign that it's not something we *need* to worry about right now.

**Comment by alex-konovalov** [comment]
@fingolfin as I said above, that is from trying to sign in into travis-ci.org with GitHub. I didn't know about the marketplace.

**Comment by fingolfin** [comment]
@alex-konovalov aaah, so this is for your personal account then... Still, I am confused: what does "sign into travis-ci.org" have to do with "switching from travis-ci.org to travis-ci.com"? Shouldn't you sign into travis-ci.com to test that?

For that matter: signing into one of these is required to restart and cancel builds already... Aren't you already doing this on travis-ci.org ?! 

Looking at https://github.com/settings/connections/applications/88c5b97de2dbfc50f3ac I guess I already granted them those rights (note that accessing private repos is the only way for them to allow for builds of private repos... this is a deficiency of GitHub, they simply don't offer more fine grained control. That said, it'd be nice if one could choose whether one wants that or not)

**Comment by alex-konovalov** [comment]
@fingolfin ah, sorry for the typo (twice). Yes, I am already signed in to travis-ci.ORG, and the form asking me for access permissions is when trying to sign to  travis-ci.COM what I haven't done before.

**Comment by mohamed-barakat** [comment]
> * In the meantime, I am not aware of any official plans by them to shut down travis-ci.org, and thus no urgency with any of this @mohamed-barakat do you? link?

I migrated couple of months ago after I read that one should migrate before they shut down travis-ci.org. There were no clear deadlines but I simply didn't want to risk getting stuck at some moment.

**Comment by fingolfin** [comment]
@alex-konovalov ahhh OK.

@mohamed-barakat I understand, but then, they still label this beta. And on the Xcode 6.4 images they print the warning that they'll turn this off in "January 2019" ... yet they still run... :-). I am pretty sure they'll send out another round of warnings if they *really* are ready to migrate.

These are the guys who took two years to bring us Ubuntu 16.04. 

I actually just tried to find the announcement for the move from .org to .com, but couldn't; but IIRC it was at least 1-2 years ago?

**Comment by fingolfin** [comment]
According to [this mail](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D) travis-ci.org will be shutdown December 31, 2020. So we ought to look into migration soon *sigh*

**Comment by fingolfin** [comment]
I've migrated all repositories on gap-system, gap-infra and gap-packages, and also already updated the URLs in many repositories (not yet for all packages). So from my POV this is done.
