### ISSUE TITLE
LogToDatedFile does not use the system time

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#4014]
When using `LogToDatedFile` it creates the file `2020-05-07 10-00-42.log` although it's currently 12:00.

**Comment by ssiccha** [comment]
Or is that the fault of my terminal somehow?

**Comment by fingolfin** [comment]
`LogToDatedFile` is not a function provided by GAP. Perhaps it is from some package?

My guess would be that it uses the time in UTC, not in your local timezone.
