### ISSUE TITLE
Commented immediate method for IsNilpotentGroup

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#403]
I was browsing lib/grp.gi and came across a commented immediate method for IsNIlpotentGroup (line 270): 

    #############################################################################
    ##
    #M  IsNilpotentGroup( <G> ) . . . . . . . . . .  test if a group is nilpotent
    ##
    #T InstallImmediateMethod( IsNilpotentGroup, IsGroup and HasSize, 10,
    #T     function( G )
    #T     G:= Size( G );
    #T     if IsInt( G ) and IsPrimePowerInt( G ) then
    #T       return true;
    #T     fi;
    #T     TryNextMethod();
    #T     end );
    #T This method does *not* fulfill the condition to be immediate,
    #T factoring an integer may be expensive.
    #T (Can we install a more restrictive method that *is* immediate,
    #T for example one that checks only small integers?)

Now, I checked the code in integers.gi, and it does _not_ uses the slow factorizing method to determine whether an integer is a prime power or not, but rather the fast method of determining if the number is a full power and then checks if the base is a prime or not. I am wondering if the above code should now be uncommented. 

The following is a rather big group for which IsNIlpotentGroup runs out of memory, while Size and IsPrimePowerInt are almost instantenous.

    gap> A := Group((1,2,3,4),(1,3));
    Group([ (1,2,3,4), (1,3) ])
    gap> HasIsNilpotentGroup(A);
    false
    gap> B := DirectProduct(A, A, A, A);
    <permutation group with 8 generators>
    gap> C := DirectProduct(B, B, B, B);
    <permutation group with 32 generators>
    gap> D := DirectProduct(C, C, C, C);
    <permutation group with 128 generators>
    gap> G := DirectProduct(D, D, D, D);
    <permutation group with 512 generators>
    gap> Size(G); time; 
    15525180923007089351489794884625025552568860171166966111390520380260509526863\
    76886330878408828646477950487730697131073206171580044114814391444287275041181\
    13920445497602084990555026528563159844482526299919371646875089284685381605785\
    6
    8
    gap> IsPrimePowerInt(Size(G)); time; 
    true
    0
    gap> HasIsNilpotentGroup(G);
    false
    gap> IsNilpotentGroup(G); time; 
    Error, reached the pre-set memory limit

At the least this code should be a method, if not an immediatemethod, considering that IsPrimePowerInt should be much faster than computing a central series.

**Comment by hulpke** [comment]
> On Dec 14, 2015, at 2:37 PM, hungaborhorvath <notifications@github.com> wrote:
> 
> I was browsing lib/grpgi and came across a commented immediate method for IsNIlpotentGroup (line 270):

Immediate methods have caused problems in the past in that they have to be considered for being applicable. That is for this method, any time there is a group for which the order has been obtained, this test would be run. In situations such as conjugacy classes or double cosets the time spent on this can be significant and it will have a payoff only in very specific situations. Because of such problems several immediate methods have been disabled, this must have been in around 1998 or 99.

I would therefore strongly urge to keep this method commented out and if desired install an high-ranked ordinary method for `IsNilpotentGroup’ under the condition the group knows its order.

**Comment by hungaborhorvath** [comment]
The pull request #442 solves this, and gives some further enhancement on IsPGroup and on PrimePGroup.
