### ISSUE TITLE
Quotient of FreeGroup by SemigroupCongruence bug

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#405]
If I create a quotient of a free group by a semigroup congruence

```
gap> f:=FreeGroup(2);;
gap> g := f / [[f.1^2, f.2^2]];
<quotient of Group( [ f1, f2 ] ) by SemigroupCongruence( [ [ f1^2, f2^2 ] ] )>
gap> Size(g); # Should be infinity
Error, recursion depth trap (5000)
 in
  return ConstantTimeAccessList( Enumerator( coll ) ); at /home/makx/ac/gap/lib/coll.gi:282 called from 
GeneratorsOfMagma( M ) at /home/makx/ac/gap/lib/magma.gi:1077 called from
Enumerator( coll ) at /home/makx/ac/gap/lib/coll.gi:282 called from
GeneratorsOfMagma( M ) at /home/makx/ac/gap/lib/magma.gi:1077 called from
Enumerator( coll ) at /home/makx/ac/gap/lib/coll.gi:282 called from
GeneratorsOfMagma( M ) at /home/makx/ac/gap/lib/magma.gi:1077 called from
...  at line 3 of *stdin*
you may 'return;'
brk> 
```

It's quite obvious what's happening, but if anyone beats me to a fix, feel free.

**Comment by alex-konovalov** [comment]
Reminder: this still happens in GAP 4.8.6

**Comment by fingolfin** [comment]
Added to 4.9.0 milestone; @markuspf feel free to move it to 4.10.0 if you don't have time to fix it.

**Comment by markuspf** [comment]
Actually I am not sure anymore whether there's anything wrong here: 

```
gap> F := FreeGroup(2);
<free group on the generators [ f1, f2 ]>
gap> G := F / [F.1^2, F.2^2];
<fp group on the generators [ f1, f2 ]>
gap> Size(G);
...
```
This doesn't terminate (proving infinity of this group doesn't work via the CommutatorFactorGroup procedure, and I don't know whether we should try very hard: One can compute a complete finite rewriting system and hence decide whether the group is infinite for some cases, but the question is whether one should try this.

**Comment by markuspf** [comment]
Oh, I see the problem. Its bad if issues lie around for this long. I'll make afix.
