### ISSUE TITLE
Unused computed flag in `SmallGeneratingSet`

### ISSUE THREAD

**Issue by denisrosset** [gap-system/gap#4051]
In `SmallGeneratingSet`, a simple test about orbits is first made, probably to avoid constructing a stabilizer chain. However, the computed flag is never used.

https://github.com/gap-system/gap/blob/2c58a4b428f7c89ea3fe1fe6418ee71f8dfb3e9b/lib/grpperm.gi#L2099

**Comment by fingolfin** [comment]
Great catch! @hulpke added this in a7eec63ba9b3bcea449cfd2405ef4b22e051a23d and will likely know best how to deal with it.

**Comment by hulpke** [comment]
Came from copying a block and then changing. Obviously harmless but fixed.
