### ISSUE TITLE
Performance issue with AllSmallGroups

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#4056]
### Observed behaviour

gap> AllSmallGroups(Size,256,IsSolvable,false); time;
[  ]
0
gap> AllSmallGroups(Size,512,IsSolvable,false); time;
(... hangs ... )

### Expected behaviour

gap> AllSmallGroups(Size,256,IsSolvable,false); time;
[  ]
0
gap> AllSmallGroups(Size,512,IsSolvable,false); time;
[  ]
0

### Copy and paste GAP banner (to tell us about your setup)

 ┌───────┐   GAP 4.11.0 of 29-Feb-2020
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv7
 Configuration:  gmp 5.1.3, GASMAN
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.3, PrimGrp 3.4.0, SmallGrp 1.4.1, TransGrp 2.0.5
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'

**Comment by fingolfin** [comment]
This is a special case of https://github.com/gap-packages/smallgrp/issues/4
