### ISSUE TITLE
CLI option '-o 2g' fails in 32-bit builds

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#4064]
It seems to me that after #4048 by @ChrisJefferson `-o 2g` is rejected in 32-bit builds. It was observed first time on June 13th on kovacs in a weekly benchmark test (St Andrews only link [here](https://gap-ci.cs.st-andrews.ac.uk/view/GAP-weekly/job/GAP-master-benchmarks/)):
```
+ ../../bin/gap.sh -o 2g test3.g
usage: gap [OPTIONS] [FILES]
       run the Groups, Algorithms and Programming system, Version 4.12dev
       use '-h' option to get help.

Build step 'Execute shell' marked build as failure
```
Indeed, I've logged in into the build workspace, and can reproduce it there:

```
$ bin/gap.sh -o 2g
usage: gap [OPTIONS] [FILES]
       run the Groups, Algorithms and Programming system, Version 4.12dev
       use '-h' option to get help.
```
This also does not work:
```
$ bin/gap.sh -o 2048m
usage: gap [OPTIONS] [FILES]
       run the Groups, Algorithms and Programming system, Version 4.12dev
       use '-h' option to get help.

$ bin/gap.sh -m 1600m
Panic in src/sysmem.c:693: cannot extend the workspace any more!
```

**Comment by fingolfin** [comment]
#4048 was by me, not by @ChrisJefferson 

I can confirm this regression. Besides fixing it, we should also think about ways to improving the test suite to test for these things

**Comment by fingolfin** [comment]
I think the problem here is the switch between Int and UInt, and a check for negative values to indicate a parsing error; but 2G and larger values cannot be represented by a 32bit int, so they wrap into negative. Fixing it shouldn't be hard.
