### ISSUE TITLE
Using the "firefox" help viewer on Linux creates empty file named "1"

### ISSUE THREAD

**Issue by jix** [gap-system/gap#4087]
### Observed behaviour

After executing `SetHelpViewer("firefox");` on Linux and then using the help viewer (which works fine) an empty file named "1" appears in the current working directory.

### Expected behaviour

No files are created in the current directory.

### Cause and fix

The templates for the shell commands used to start Firefox and several other browsers on Linux https://github.com/gap-system/gap/blob/c7696ae2bd7f2e7ac4848057de0229a0b17bf68f/lib/helpview.gi#L224 have the redirect `2>1` which redirects standard error into the file named "1", instead it should be `2>&1` which redirects stderr to the same destination as stdout.

### Copy and paste GAP banner (to tell us about your setup)

```
% gap
 ┌───────┐   GAP 4.11.0 of 29-Feb-2020
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv7
 Configuration:  gmp 6.2.0, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2019.09.04, AutPGrp 1.10.2, Browse 1.8.8, CaratInterface 2.3.3, CRISP 1.4.5, Cryst 4.1.23, CrystCat 1.1.9, CTblLib 1.2.2, FactInt 1.6.3, 
             FGA 1.4.0, Forms 1.2.5, GAPDoc 1.6.3, genss 1.6.6, IO 4.7.0, IRREDSOL 1.4, LAGUNA 3.9.3, orb 4.8.3, Polenta 1.3.9, Polycyclic 2.15.1, PrimGrp 3.4.0, RadiRoot 2.8, recog 1.3.2, ResClasses 4.7.2, 
             SmallGrp 1.4.1, Sophus 1.24, SpinSym 1.5.2, TomLib 1.2.9, TransGrp 2.0.5, utils 0.69
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by fingolfin** [comment]
Thank you for your report. A fix for this will appear in a future GAP release.
