### ISSUE TITLE
Units in nonassociative algebras

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#4096]
This is prompted by comments in:

https://mathoverflow.net/questions/368407/unit-group-of-octonions-over-finite-fields

The unit computation for a nonassociative algebra cannot assume that the units form a group:
```
gap> a:=OctaveAlgebra(GF(2));
<algebra of dimension 8 over GF(2)>
gap> u:=Units(a);
<group with 6 generators>
gap> p:=Image(IsomorphismPermGroup(u));
<permutation group of size 120 with 6 generators>
gap> p:=Group(GeneratorsOfGroup(p));;
gap> Size(p);
1440
```

I'm not sure whether the issue is that `a` should not have `IsRing`, or whether the method for units should test associativity first.

**Comment by ThomasBreuer** [comment]
@hulpke `IsRing` does not imply associativity of the multiplication, according to the documentation, thus `IsRing` for `a` is correct.
The `Units` method in question anyhow runs over all elements in `a`; it could return the list of units or a magma object if the given ring is not associative.
