### ISSUE TITLE
Syntax extension: enhanced matrix "coordinates"

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#41]
To get and set entries in matrices, we currently have to write
```
x := a[row][col];
a[row][col] := y;
```
to access an entry. This internall has to frist fetch a row object, then an entry in that. This is problematic for e.g. packed matrices, where there are no real "row" objects; in that case, a temporary object representing the row needs to be represnted. This is a big problem for alternative matrix representations, e.g. sparse representations.

This is why for the new MatrixObj interfaces for matrices-as-objects (as opposed to matrices-as-lists-of-lists), new operations` SetMatElm(a,row,col,val)` and `MatElm(a,row,col)` were defined. Example:
```
x := MatElm(a, row, col);
SetMatElm(a, row, col, y);
```

This works, but of course is syntactically not so nice. Hence, I propose we add new syntactic sugar allowing this syntax (similar syntax exists in various other languages):
```
x := a[row,col];
a[row,col] := y;
```

Note that the code in PR #28 `almost` allows for this; namely, that codes allows passing arbitrary objects as list indices, and thus allows to use lists as indices... so with that patch, one could install methods for `\[\]` and `\[\]\:\=` which then allow writing code like this:
```
x := a[[row,col]];
a[[row,col]] := y;
```
However, this syntax is slightly less nice and less "standard". It also involves creating termporary lists `[row,col]`, so it has a little extra overhead -- if one does many matrix operations, then one ends up creating tons of small termporary objects, which tends to hurt garbage collectors (but perhaps it is not so much of an issue for the generational collector in GAP?).

**Comment by stevelinton** [comment]
I have the beginnings of a PR adressing this, but I'm not sure how to make it visible. It's in stevelinton/gap in branch sl/multi-index. It's far from complete, but what's done seems to work smoothly enough.

**Comment by alex-konovalov** [comment]
Thanks - it's visible at https://github.com/stevelinton/gap/commits/sl/multi-index, the particular commit is https://github.com/stevelinton/gap/commit/7af451259dba77f25243e566bba34f5ecbd9818d

**Comment by fingolfin** [comment]
One way to make it visible would be to just do a pull request now, but say in its title "WIP, do not merge" or so. The PR will automatically update whenever you push new changes to your branch.

**Comment by fingolfin** [comment]
I would also recommend rebading your feature branch on the latest master, instead of doing merges. I'll be happy to explain why and how.

**Comment by stevelinton** [comment]
The solution in my fork is now complete as far as the kernel code goes.

At the moment all multi-indexed access end up as method calls with a plain list of indices as arguments, so m[1,2,3] simply turns into m[[1,2,3]] 

No methods which use this are installed in the library.

There is support for access and assignment for exactly 2 arguments to be handled specially, They go through ASS2_LIST and ELM2_LIST kernel macros, so they could have fastpaths for particular TNUMs or call out to new operations without creating those lists if needed. At the moment this is not used, the kernel macros just build length 2 plain lists.

IsBound and Unbind are supported, but without fastpaths.

The GAP compiler is not supported. There are no tests.

**Comment by fingolfin** [comment]
The latest version of Steves code can be found under PR #192 -- it has tests now, too.
