### ISSUE TITLE
Unify syntax errors and warnings

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#411]
This is a very minor issue, but: Currently, sometimes syntax errors start in upper case, sometimes in lower case. Some examples from `read.c`:
```C
SyntaxError("function literal in impossible context");
SyntaxError("identifier expected");
SyntaxError("Identifier over 1024 characters");
SyntaxError("Badly Formed Number");
```
I think we should unify this and also SyntaxWarning.

**Comment by markuspf** [comment]
Absolutely agree. I was trying to have at least some small extent of error reporting in the Jupyter frontend this morning, and noticed that error messages are not very uniform.

**Comment by stevelinton** [comment]
Thanks to @BlairArchibald for sorting this.
