### ISSUE TITLE
AlwaysPrintTracebackOnError

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4121]
The (undocumented) global variable `AlwaysPrintTracebackOnError` seems to be intended for situations where GAP is integrated with other systems.
In the GAP/Julia integration, I have set the value to `true` in order to get better error messages, see oscar-system/GAP.jl/pull/520.

One problem is that `Test` apparently expects that `AlwaysPrintTracebackOnError` has the value `false`;
If errors occur in a GAP testfile then differences are reported because the output looks differently.
As an example, try the following GAP input.
```
gap> AlwaysPrintTracebackOnError:= true;;
gap> Test( Filename( DirectoriesLibrary( "tst" ), "testinstall/zmodnz.tst" ) );
```
One way to fix this problem would be to set `AlwaysPrintTracebackOnError` to `false` during tests.
Another way would be to change the comparison of error messages inside `Test`.
What do you think?

**Comment by fingolfin** [comment]
Actually, `AlwaysPrintTracebackOnError` is controlled by the command line option `--alwaystrace` and we use it for the GAP CI integration. That it is useful for the GAP-Julia integration is a nice but unplanned benefit :-).

It seems plausible to me to (re)set `AlwaysPrintTracebackOnError` in `Test`.

**Comment by ThomasBreuer** [comment]
Thanks.
I will create a pull request.
