### ISSUE TITLE
PolymakeInterface target has no make rules

### ISSUE THREAD

**Issue by epsilon-0** [gap-system/gap#4135]
When compiling the subpackage PolymakeInterface, the following error occurs

```
mkdir -p bin/amd64
make: *** No rule to make target 'bin/amd64/polymake_main.so', needed by 'default'.  Stop.
```

**Comment by fingolfin** [comment]
This issue tracker here is the wrong place to ask for this (it is for the core GAP system, not for individual packages, who have their own maintainers). Please submit package specific requests in the way the package's documentation states; in this case, via the issue tracker https://github.com/homalg-project/homalg_project/issues
