### ISSUE TITLE
SHA256 files for our downloads are not correct / up-to-date

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4166]
Downloading https://files.gap-system.org/gap4pkgs/packages-stable-4.11.tar.gz and https://files.gap-system.org/gap4pkgs/packages-stable-4.11.tar.gz.sha256 and https://files.gap-system.org/gap4pkgs/packages-stable-4.11.tar.gz.md5 and comparing them, I see that the (weak!) MD5 sum matches, but the SHA256 sum does not:

```
$ cat packages-stable-4.11.tar.gz.*
f8d448bc6cfdd82557f2492082872b10
d062b258cc74b3e39e6a1eb65f75bf0928d04e8588dc4899a152a75f2fdaa741
$ md5sum packages-stable-4.11.tar.gz
f8d448bc6cfdd82557f2492082872b10  packages-stable-4.11.tar.gz
$ shasum -a 256 packages-stable-4.11.tar.gz
9e4f26e8c353912d913d1ef7317d2b071bdeffab552cd2896f39ab735679fa4c  packages-stable-4.11.tar.gz
```

As it is, I have no idea which script or server takes care of updating these files -- probably the Jenkins in St Andrews? @alex-konovalov ?

**Comment by alex-konovalov** [comment]
These files are produced in Jenkins, but they are not copied over to `gap4pkgs` directory automatically. Someone need to check Jenkins tests to see that they do not break the tests first. If they are acceptable, then in the home directory on the host server gap-web.host.cs.st-andrews.ac.uk there are scripts to run:
```
./get-pkg-archives-master.sh
./publish-pkg-archives-master.sh
./get-pkg-archives-stable.sh
./publish-pkg-archives-stable.sh
./update-pkg-archives-checksums.sh
```
The first two handle archives for the master branch, the next two for the stable (-4.11 at the moment), and the last one updates checksums (for all files, not just for the new ones, but that's tolerable for now, as not run often at all).
