### ISSUE TITLE
refactor our `dev/ci*.sh` scripts and tests overall

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4167]
Some thoughts while working on PR #4036:

1. we should move the actual tests out of `dev/ci.sh` into places where it's easy to run them separately and locally. Two approaches come to mind (not mutually exclusive):
   1. move e.g. the code for `testpackages` into a separate script `tst/testpackages.sh` or `dev/ci-testpackages.sh`; then in `dev/ci.sh` just call that
   2. modify the `testpackages` Makefile target to run exactly that test, and rename the existing `testpackages` Makefile target to e.g. `old-testpackages`, or just drop it (I know that @alex-konovalov uses it for some CI somewhere, so of course we have to carefully coordinate these things
   3. in the end, I'd imagine that the main loop in `dev/ci.sh` would be just a few lines, invoking either shell scripts or `make` targets (possibly both, using a logic like this: if `tst/$TESTSUITE.sh` exists run that else run `make $TESTSUITE` -- though at that point, we might as well have all the "testsuites" names be valid Make targets, I guess?)

2. colorize output of test results more to make searching through long test logs visually easier:
   1. teach `Test` to output failures in red (using `TextAttr.1` from GAPDoc) and perhaps success in green (or perhaps leave successful tests uncolored)
   2. teach the other testing stuff we run (see point 1 above resp. `dev/ci.sh`) also to use colors more

3. Perhaps improve the `cnf/download.sh` script to honor SHA256 checksum files if available to avoid unnecessary re-downloads (but see also issue #4166). But be wary, tools like `shasum` are not available everywhere, so we must code defensively and be able fallback to not checking checksums.
    - Note: we already do something like this in the alternate download script `dev/ci-download.sh` but that's tied to Travis and its caching system. But perhaps we could just adapt that to work also with GitHub actions? Hm

4. split up `dev/ci-prepare.sh`:
   1. drop the debug stuff
   2. `dev/ci-install-deps.sh`: install prerequisites (right now just Julia?)
   3. actually build GAP
   4. download packages, possibly build IO and profiling

**Comment by alex-konovalov** [comment]
For now, just one quick response after seeing my mention: if you will rename it for `old-testpackages`, it will be fine. It's used in Jenkins, but fine if it could be eventually retired.

**Comment by fingolfin** [comment]
Some updates:

1. instead of moving everything out of `dev/ci.sh`, I instead opted to make it easy to invoke `dev/ci.sh` interactively, see PR #5567 (which IMO resolves this point)
2. these days we do colorize the errors and diffs in `Test` output. I'll colorize `dev/ci.sh` output some more, too, after which I'll consider this point done, too.
3. SHA256 verification for downloads is not currently done in CI, though the release and package distro scripts do this (see e.g. `download_with_sha256` in `dev/releases/utils.py`). But since downloads are stable and fast right now, I don't see much incentive to work on this right now.
4. is done
