### ISSUE TITLE
GH Actions: figure out why HPC-GAP tests are so slow in debug mode

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4169]
Initial GH Actions support was merged in PR #4036 but for the HPC-GAP tests, I had to downgrade from `teststandard` to the `testinstall` testsuite, because it was running over 3.5 hours instead of maybe half an hour.

I then performed some timings for one of the tests which I noticed to run quite a bit slower, comparing my MacBook Pro (MBP), a Linux server (plesken in Siegen), Travis CI and GitHub actions, running `Test("tst/teststandard/stablesort.tst")` in various different GAP builds (note: cloud build timings fluctuate quite a bit, so take these as ballparks). Here are the results:
- non-debug plain GAP:
  - MBP: 5 seconds
  - Linux: 7 seconds
  - Travis: ? seconds
  - GH Actions: ? seconds
- non-debug HPC-GAP:
  - MBP: 5 seconds
  - Linux: 8 seconds
  - Travis: ? seconds
  - GH Actions: ? seconds
- debug plain GAP:
  - MBP: 74 seconds
  - Linux: 8 seconds
  - Travis: 25 seconds
  - GH Actions: 28 seconds
- debug HPC-GAP:
  - MBP: 78 seconds
  - Linux: 10 seconds
  - Travis: 36 seconds
  - GH Actions: 447 seconds

Note that the tests are also very slow on my MacBook Pro once using a debug build of GAP. @rbehrends speculated that this could be related to clang vs. gcc; or "that the Boehm GC causes extra work in a memory-constrained environment".

This is not super urgent, but it might be a good idea to understand this better.

**Comment by ChrisJefferson** [comment]
Can you give some more details about your Macbook Pro tests?

I ran on my mini mac (which does run 10.13), and I get 11 seconds standard GAP, 26 seconds in debug GAP (just configured with --enable-debug). I'm compiling with clang (LLVM 10.0.0).

**Comment by ChrisJefferson** [comment]
As a sanity check, could you try this patch (which does seem to speed things up on my mac, although it was never as slow as yours)

```diff --git a/src/debug.h b/src/debug.h
index 1d682057c..6e4625817 100644
--- a/src/debug.h
+++ b/src/debug.h
@@ -19,7 +19,9 @@
 */
 
 #ifdef GAP_KERNEL_DEBUG
-#define GAP_ASSERT(x) assert(x)
+#include <stdlib.h>
+#define GAP_ASSERT(x) do { if(!(x)) abort(); } while(0)
+//#define GAP_ASSERT(x) assert(x)
 
 // Enable various GAP debugging features
```

**Comment by fingolfin** [comment]
Mystery of the MacBook builds solved: the debug build I was looking at used `CFLAGS=-g CXXFLAGS=-g` (this helps a lot with stepping through certain code).

That still doesn't explain why the HPC-GAP builds are so super slower?

**Comment by rbehrends** [comment]
The strange part is that it's that extreme only on GitHub Actions. Do we have any timing output to see if it's an overall slowdown or just one or a few tests that cause the problem?

**Comment by ChrisJefferson** [comment]
I checked GAP and HPC-GAP on github actions for teststandard (you should be able to see it here https://github.com/ChrisJefferson/gap/runs/1447314739 )

Standard GAP with debug - 32m
Standard GAP without debug - 22m
HPC-GAP with debug - 3h 30m
HPC-GAP with debug disabled - 2h 5m

So debugging is slowing things down by a similar amount in GAP vs HPC-GAP.

Having a look through the tests, there doesn't seem to be any test specifically which is very slow, although different tests do suffer different slowdowns.
