### ISSUE TITLE
Documentation:  Trying to understand what Conjugacy Classes returns

### ISSUE THREAD

**Issue by JoeMooreBrk** [gap-system/gap#4179]
### Observed behaviour
I may be missing something obvious, but I'm trying to understand the results of ConjugacyClasses.  I would expect a list of sets of elements which are conjugate to each other (with the center either ignored or listed in the first position), but I have not been able to parse it out that way.

**Comment by ChrisJefferson** [comment]
So, you do get a list, but the elements of the list are a compact representation of conjugacy classes (see ConjugacyClass)

If you want one element of the conjugacy class use `Representative`, if you want all of them use `List` (although of course, there can be a lot!)

```
gap> c := ConjugacyClasses(SymmetricGroup(5));
[ ()^G, (1,2)^G, (1,2)(3,4)^G, (1,2,3)^G, (1,2,3)(4,5)^G, (1,2,3,4)^G, (1,2,3,4,5)^G ]
gap> Representative(c[2]);
(1,2)
gap> List(c[2]);
[ (1,2), (1,3), (1,4), (1,5), (2,3), (2,4), (2,5), (3,4), (3,5), (4,5) ]
```

**Comment by ChrisJefferson** [comment]
Quick extra question, do you want conjugate subgroups rather than conjugate elements? Then look at ConjugacyClassesSubgroups.

**Comment by fingolfin** [comment]
Quick addition, you may want to use `AsList` or `AsSet` instead of `List`.

**Comment by fingolfin** [comment]
But even better usually is not do either; a major performance gain in group theory usually is to process conjugacy classes in a clever way which does not require computing all elements of the class.

**Comment by JoeMooreBrk** [comment]
OK, I understand it now.  Thanks.  My confusion was what the representative
was picking up and how to treat the Conjugacy Classes as sets (which I knew
they were).  Also, is this the place for functional questions?  If not,
what is?  It seems that most of the discussion here is by architects of the
software.

**Comment by hulpke** [comment]
@JoeMooreBrk This is the isse tracker for errors in the system. If you are looking for a place to ask usage questions or ask for system help, there is the gap-forum email list:
https://www.gap-system.org/Contacts/Forum/forum.html

or the gap tag on math.stackexchange:
https://math.stackexchange.com/questions/tagged/gap

**Comment by JoeMooreBrk** [comment]
I'm working in GAP WIndows.  I paste in my functions from Notepad++.  After
pasting in a few versions, I sometimes see artifacts like:

gap> ListByMayBeIsomorphicInvariant := function(grplst, arg...)
>       local lvl, sw, iter, useList, invList, idx, chki, invi, listinv,
posinv, sngl, mult;
> # Use MayBeIsomorphicInvariant to classify groups from a list into
potentially
> # isomorphic lists based on a level of invariance
>       if not CheckList(grplst,"First") then return false;fi;
>       if not Filtered(grplst,g->not IsGroup(g)) = [] then
>               Print("First parameter must be a pure list of groups");
>               return false;
>       fi;
>       if Length(arg) = 0 then
>               lvl := 100;
>       else
>               lvl := arg[1];
>       fi;
>       if not CheckInt(lvl,"Second") then return false;fi;
>       sw := MarkTimeSeconds();
>       for iter in [1..lvl] do
>               useList := List(grplst);
>               invList :=
[[[useList[1]],[MayBeIsomorphicInvariant(useList[1],lvl)[2]]]];
>               idx := 2;
>               while (idx <= Size(useList)) do
>                       chki := useList[idx];
>                       invi := MayBeIsomorphicInvariant(chki,lvl)[2];;
>                       # List of invariants
>                       listinv := List(invList,l->l[2]);;
>                       posinv := Position(listinv, invi);
>       #
*
+
-
.
.:=
/
16Bits_AssocWord
16Bits_CombiCollector
16Bits_DepthOfPcElement
16Bits_Equal
16Bits_ExponentOfPcElement
16Bits_ExponentSums1
16Bits_ExponentSums3
16Bits_ExponentSyllable
16Bits_ExponentsOfPcElement
16Bits_ExtRepOfObj
16Bits_GeneratorSyllable
16Bits_HeadByNumber
16Bits_LeadingExponentOfPcElement
16Bits_LengthWord
16Bits_Less
16Bits_ObjByVector
16Bits_Power
16Bits_Product
16Bits_Quotient
16Bits_SingleCollector
32Bits_AssocWord
32Bits_CombiCollector
32Bits_DepthOfPcElement
>       #t(listinv, ": ", invi, ": ", posinv, nl);
>                       if posinv = fail then
>       #
*
+
-
.
.:=
/
16Bits_AssocWord
16Bits_CombiCollector
16Bits_DepthOfPcElement
16Bits_Equal
16Bits_ExponentOfPcElement
16Bits_ExponentSums1
16Bits_ExponentSums3
16Bits_ExponentSyllable
16Bits_ExponentsOfPcElement
16Bits_ExtRepOfObj
16Bits_GeneratorSyllable
16Bits_HeadByNumber
16Bits_LeadingExponentOfPcElement
16Bits_LengthWord
16Bits_Less
16Bits_ObjByVector
16Bits_Power
16Bits_Product
16Bits_Quotient
16Bits_SingleCollector
32Bits_AssocWord
32Bits_CombiCollector
32Bits_DepthOfPcElement
>       #t("Adding",nl);
>                               Add(invList, [[chki],invi]);
>                               Remove(useList,idx);
>                       else
>                               Add(invList[posinv][1], chki);
>                               Remove(useList,idx);
>                       fi;
>               od;
>               sngl := Filtered(invList,l->Size(l[1])=1);
>               mult := Filtered(invList,l->Size(l[1])<>1);
>               Print("After iteration :",iter," there are ",Size(invList),
" distinct groups ",sngl," single ",mult," multiple
",RoundDig(MarkTimeSeconds()-sw,2)," total seconds elapsed",nl);
>       od;
>       return invList;
>       end;;

I was working in gap-4.11.0 and saw them periodically there.  I just
upgraded to:

gap> GAPInfo.Version;
"4.14.0"

Any suggestions?

Thanks for a great product.

**Comment by fingolfin** [comment]
@JoeMooreBrk this issue was closed over 4 years ago. Please don't comment with unrelated new requests. Instead either open a new issue; or send an email to the GAP mailing list gap@gap-system.org; or ask on our Slack chat (<https://gap-system.org/slack>)
