### ISSUE TITLE
Error handling in `READ_ALL_COMMANDS`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4199]
LibGAP's `GAP_EvalString` calls the kernel function `READ_ALL_COMMANDS`, which does the same as the GAP function `READ_ALL_COMMANDS`.
Consider the following GAP session.
```
gap> READ_ALL_COMMANDS( InputTextString( "\"" ), false, true, ViewObj );
Syntax error: String must end with " before end of file in stream:1
[ [ false,,,, "" ] ]
```
The syntax error message is printed to the screen, a result is returned, and the `false` entry in the result indicates that an error happened.

When one uses the above input via LibGAP, what is the recommended way  to handle the error in the code that calls `GAP_EvalString`, that is, access the error message (in order to report it) and then empty the buffer?
This error handling is currently missing in the GAP-Julia integration, see oscar-system/GAP.jl/issues/580.

**Comment by fingolfin** [comment]
I think the idea was/is to set the ERROR_OUTPUT global in GAP to an output stream to which the error messages then are written. (That's not necessarily a great API, but it was the easiest to pull of on short notice back then.)

This is of course what `reset_GAP_ERROR_OUTPUT` does, so we can probably just use that / imitate what `error_handler` does?

**Comment by ThomasBreuer** [comment]
Yes, calling `error_handler` in the function that calls `GAP_EvalString` solves the problem.
