### ISSUE TITLE
Windows installation does not start

### ISSUE THREAD

**Issue by mathlusiverse** [gap-system/gap#4203]
I re-installed GAP using gap-4.11.0.exe, and got the same error message:

### Observed behaviour
gap.exe - System Error
The code execution cannot proceed because cygwin1.dll was not found. Reinstalling the program may fix this problem.

I reinstalled serveral times and did not solve the problem.
I installed cygwin and copy 'cygwin1.dll' into GAP folder, and start gap.exe. It open and close immediately.

I also tried the other installation approach: unzip gap-4.11.0-win.zip, but the end-result is still the same error message.

Can someone please help. Thanks

**Comment by mathlusiverse** [comment]
I decided to install Sage as it includes GAP. Different problem occurs and I can't get Sage working!

My Anti-virus program found that Python3 is infected with idp.generic virus and automatically removed it. I wonder if this is what happened to GAP.

**Comment by fingolfin** [comment]
I think your Anti virus program (like most of them) is useless and destroyed your Sage with no good cause.

However, GAP neither uses nor bundles Python, so that shouldn't be it; though of course AV software can break everything with ease.

Anyway, perhaps @alex-konovalov or @ChrisJefferson or @pedritomelenas have an idea what could be wrong or how to debug it?

**Comment by alex-konovalov** [comment]
@mathlusiverse after installing GAP using gap-4.11.0.exe, you need to start it using gap-4.11.0/bin/gap.bat file. The installer also should place a shortcut so you could also see it in the place where you see other installed applications. If you have just tried to start gap.exe directly, that may be a problem. Another common pitfall is installing GAP in a path that contains spaces (e.g. "Program files"). Hope these hints will help!

**Comment by pedritomelenas** [comment]
As @alex-konovalov suggests, the best way is to use the prebuild image, install it and then start it with the bat file (there should also be an icon on your desktop). 

Long time ago I wrote some steps for the installation on cygwin: https://github.com/pedritomelenas/gap-singular-cygwin

**Comment by ChrisJefferson** [comment]
This is fixed in the newest installer
