### ISSUE TITLE
libgap: add GAP_ValueSmallInt or something like it

### ISSUE THREAD

**Issue by embray** [gap-system/gap#4208]
### Observed behaviour

The libgap API currently exposes a `double GAP_ValueMacFloat(Obj)` function to return a machine double from a GAP machine float.  However, no such interface exists for native ints.  `GAP_SizeInt` and `GAP_AddrInt` can be used to read the limbs of large ints, but converting a small int back to a C int requires knowledge of the internal structure of immediate ints.

### Expected behaviour

A proposed `Int GAP_ValueSmallInt(Obj)` function (or some other name if there's a better one) to return an `Int/intptr_t` from a GAP small int should be added to the API so that the internal structure of small ints does not need to be exposed.

**Comment by fingolfin** [comment]
Agreed!

If you have time to add this, I'll be happy to merge the PR. Otherwise, gotta wait till I have some spare cycles.

**Comment by embray** [comment]
I sort of forget about this since my workaround is working for now.  But my workaround definitely just depends on explicitly knowing GAP internals.  So it would be good to add this.   I just wonder what it should do if it's passed the wrong type of object.
