### ISSUE TITLE
libgap: Add GAP_MakeStringWithLen function

### ISSUE THREAD

**Issue by embray** [gap-system/gap#4211]
### Observed behaviour

The public libgap API provides two functions for creating GAP strings from a C `char *`: `GAP_MakeString` and `GAP_MakeImmString`.

Both of these assume the input string is NULL-terminated, so there is no public API to create a GAP string containing NULL bytes.

### Expected behaviour

There should be a `GAP_MakeStringWithLen` function (the name can be bikeshedded) as well as `GAP_MakeImmStringWithLen` which take a size argument for strings with already known lengths.  These functions already exist in GAP and just need to be exposed to the public API.

**Comment by fingolfin** [comment]
These would be wrapper around `MakeStringWithLen` resp. `MakeImmStringWithLen` so I'd indeed use those names with the `GAP_` prefix.

If you are willing to make a PR adding these, I'd be happy to merge it.

**Comment by embray** [comment]
@fingolfin Will do.  I'll probably send a number of PRs to this tune, as I'm as much as possible trying to eradicate use of all "non-public" APIs.

**Comment by ThomasBreuer** [comment]
@embray Concerning `GAP_MakeStringWithLen`, I thought I had added this to `libgap-api` in the master branch, with pull request #4152.

**Comment by embray** [comment]
Ah right, I noticed this when testing against the master branch.
