### ISSUE TITLE
Functions named "LastReadValue"

### ISSUE THREAD

**Issue by embray** [gap-system/gap#4223]
### Observed behaviour

There is an undocumented global variable `LastReadValue` that is assigned the result of every call of the internal function `READ()`.  If that result happens to be a function, the function's name will become `LastReadValue`.

Example:

```
gap> stream := InputTextString("function() end;");
InputTextString(0,15)
gap> READ_STREAM(stream);
true
gap> LastReadValue;
function(  ) ... end
gap> NameFunction(LastReadValue);
"LastReadValue"
```

### Expected behaviour

The function's name should not be assigned to in this case.  Perhaps there should be away to assign to a global variable *without* invoking the behavior of setting a function's name.

It's mostly harmless, but confusing.

### Copy and paste GAP banner (to tell us about your setup)

```
 ┌───────┐   GAP 4.11.0 of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv7
 Configuration:  gmp 6.1.2, GASMAN, readline
```

**Comment by ChrisJefferson** [comment]
A similar thing happens if you define a function on the prompt (it gets called `last`).

We already have a special route for these kinds of variables (`last`, `ReadLastValue`), so we can make that route not do the implicit naming.
