### ISSUE TITLE
Possible bug in IteratorList

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#4226]
### Observed behaviour
~~~~
gap> tmp := [1, 2, 3, 4];
[ 1, 2, 3, 4 ]
gap> MakeImmutable(tmp);
[ 1, 2, 3, 4 ]
gap> it := IteratorList(tmp);
<iterator>
gap> for x in it do od;
gap> IsDoneIterator(it);
true
gap> NextIterator(it);
Error, List Element: <list>[5] must have an assigned value in
  return iter!.list[iter!.pos]; at /Users/jdm/gap/lib/list.gi:763 called from
iter!.NextIterator( iter ) at /Users/jdm/gap/lib/coll.gi:948 called from
<function "NextIterator for `IsIteratorByFunctions'">( <arguments> )
 called from read-eval loop at *stdin*:21
type 'quit;' to quit to outer loop
brk> quit;
gap> IsDoneIterator(it);
false
~~~~

### Expected behaviour

The iterator should remain **done** after `NextIterator` is called.

### Copy and paste GAP banner (to tell us about your setup)

~~~~
 ┌───────┐   GAP 4.12dev-622-gf3e72d2 built on 2021-01-14 19:49:28+0000
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin13.4.0-default64-kv8
 Configuration:  gmp 6.2.0, GASMAN, readline
 Loading the library and packages ...
 Packages:   AutoDoc 2018.11.19dev, datastructures 0.2.5, Digraphs 1.3.1,
             GAPDoc 1.6.1, genss 1.6.5, GRAPE 4.8.2, images 1.3.0, IO 4.7.0,
             orb 4.8.3, PackageManager 1.1, PrimGrp 3.3.1, Semigroups 3.4.0,
             SmallGrp 1.3, Smallsemi 0.6.12, TransGrp 2.0.4
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap>
~~~~

Fairly sure this is caused by 

~~~~
BindGlobal( "IsDoneIterator_List",
    iter -> ( iter!.pos = iter!.len ) );
~~~~

in line 741 of `list.gi`, which should probably be

~~~~
BindGlobal( "IsDoneIterator_List",
    iter -> ( iter!.pos >= iter!.len ) );
~~~~

or `iter!.pos` shouldn't be incremented after it has reached `Length(iter!.list)`.

**Comment by ChrisJefferson** [comment]
The documentation does claim that bad things can happen if NextIterator is called if IsDoneIterator is true, even GAP crashing.

I wouldn't mind fixing IsDoneIterator, for defensive reasons, but I think IsDoneIterator entering the break loop is OK.

**Comment by james-d-mitchell** [comment]
But `IsDoneIterator` doesn't enter the break loop, it just changes its value from `true` to `false` for no good reason. 
Maybe there's a use case for this, and even though the documentation might say that calling `NextIterator` after `IsDoneIterator` is `true` can result in GAP crashing, there's no reason for it to crash in this case, and I wonder if this is really the desirable behaviour? 

BTW the behaviour between dense and non-dense lists is inconsistent:

~~~~
gap> tmp := [1, 2, , 4];
[ 1, 2,, 4 ]
gap> it := IteratorList(tmp);
<iterator>
gap> for x in it do od;
gap> IsDoneIterator(it);
true
gap> NextIterator(it);
Error, <iter> is exhausted at /Users/jdm/gap/lib/list.gi:746 called from
iter!.NextIterator( iter ) at /Users/jdm/gap/lib/coll.gi:948 called from
<function "NextIterator for `IsIteratorByFunctions'">( <arguments> )
 called from read-eval loop at *stdin*:32
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> IsDoneIterator(it);
true
brk>
~~~~

**Comment by wilfwilson** [comment]
Thanks for the report @james-d-mitchell.

Yes, in the sense that it doesn't contradict the documentation, it's not a bug. But of course that doesn't mean it's the most desirable behaviour, and I also can't see a good reason for the current behaviour. I also agree that the inconsistency between (immutable dense lists) and (mutable or non-dense lists) doesn't feel appropriate.

I'm going to propose a PR that checks whether the iterator is done in `NextIterator` for `IteratorList` iterators. For mutable or non-dense lists, this is already done (albeit indirectly), but the check is commented-out for dense lists. Why should it be inappropriate for dense immutable lists but appropriate for non-dense lists? That's my preferred solution.

If that is not acceptable for some reason, then I will propose a different PR.

**Comment by fingolfin** [comment]
I agree that in the spirit of having a "safe" system, the final call to `IsDoneIterator` should not return `true`, but rather should return false or raise an error; but I still feel compelled that what @james-d-mitchell's code does would behave very similarly in C++: if you increment an iterator beyond the end of a contain, all kinds of things can happen, including crashes, or exactly what we are seeing here: the check `iter != container.end()` will once again return `true` (indicating that the end of the container has not been reached).

But yeah, we should do better than C++ here :-)

**Comment by wilfwilson** [comment]
@fingolfin wrote:
> the final call to `IsDoneIterator` should not return `true`, but rather should return false or raise an error

Just to note, this behaviour is not what my PR #4232 (which you just merged - thanks) implemented. Indeed, I implemented @james-d-mitchell's proposed solution, which means that `IsDoneIterator` for immutable dense lists now returns `true` even  after `NextIterator` is wrongly called, the same as for mutable/non-dense lists.

**Comment by fingolfin** [comment]
Sorry for the confusion, I accidentally swapped true and false in that sentence

**Comment by james-d-mitchell** [comment]
Thanks @fingolfin and @wilfwilson for your comments and the fix!
