### ISSUE TITLE
On-line help fails given a query ending "-ize"

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#4229]
Using the latest GAP master, I've found that the online help sometimes fails in the following way:

Here the first query succeeds but the second query fails to find an appropriate match:
```
gap> ?Pluraliz
Help: Showing `Reference: Pluralize'
gap> ?Pluralize
Help: no matching entry found
Help: 'Pluralize' is currently undocumented.
      For details, try ?Undocumented Variables
```
And here the first and third queries succeed, but the second fails to find anything:
```
gap> ?Stabiliz
gap> ?Stabilize
Help: no matching entry found
gap> ?Stabilizer
```
and the same here:
```
gap> ?Diagonaliz
gap> ?Diagonalize
Help: no matching entry found
gap> ?DiagonalizeMa
Help: Showing `Reference: DiagonalizeMat'
```
The common denominator seems to be the query ending "-ize".

**Comment by ChrisJefferson** [comment]
Looking at the alternatives function:

```
gap> HELP_SEARCH_ALTERNATIVES("Pluralize");
[ "Pluralisee", "Pluralizee" ]
```

I think @ThomasBreuer looked at this most recently -- not blaming him, but maybe he can have a look and see if there is anything obvious going on?

**Comment by ThomasBreuer** [comment]
Yes, I will correct this bug.
