### ISSUE TITLE
conjugate a subgroup into a given one

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4240]
(The following holds for the master branch as well as for released GAP versions.)

Consider the situation that we are given a group G, say, and two subgroups A and B,
and that we want to know an element g in G such that B^g is contained in A.
The GAP function `ContainedConjugates` can be used for that task, but it computes all solutions up to conjugacy, which is more than what we need.
The name of the (undocumented) function `DoConjugateInto` sounds promising, and one can call this function in a way such that one solution is returned once it has been found.
However, `ContainedConjugates` performs better than `DoConjugateInto` in a few quick experiments.
Is there a reason why `ContainedConjugates` does not admit a shortcut (via a global option, say) in order to return just one solution?

**Comment by fingolfin** [comment]
That would indeed be useful! Perhaps @hulpke has insights into this?

**Comment by hulpke** [comment]
As for the reason, I did not need that case when I implemented it :-)
But I don't think it is hard to implement. `ContainedConjugates` is the user function that does something fast if the index is not too large and otherwise dispatches to the slower `DoConjugateInto`.
I'll see to extend it.

**Comment by hulpke** [comment]
I have added functionality (for finding only one conjugate) to PR #4219
