### ISSUE TITLE
Add convenient way to evaluate univariate polynomials.

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4283]
In PR #3901 support was added to apply a homomorphism `f` to an element `x` by writing `f(x)` instead of `Image(f, x)`.

We could do something similar for *univariate* polynomials. (For multivariate ones, the issue is that it is not clear how the order of arguments should be mapped to the various variables; I'd rather avoid that can of worms).

**Comment by fieker** [comment]
On Tue, Feb 23, 2021 at 03:54:50PM -0800, Max Horn wrote:
> In PR #3901 support was added to apply a homomorphism `f` to an element `x` by writing `f(x)` instead of `Image(f, x)`.
> 
> We could do something similar for *univariate* polynomials. (For multivariate ones, the issue is that it is not clear how the order of arguments should be mapped to the various variables; I'd rather avoid that can of worms).
> 
f(x) for univariates is there for ages.
For multivariates we use evaluate(f, [...]), but the order of variables
is the same as the arguments. There is choice?

**Comment by fieker** [comment]
On Tue, Feb 23, 2021 at 03:54:50PM -0800, Max Horn wrote:
> In PR #3901 support was added to apply a homomorphism `f` to an element `x` by writing `f(x)` instead of `Image(f, x)`.
> 
> We could do something similar for *univariate* polynomials. (For multivariate ones, the issue is that it is not clear how the order of arguments should be mapped to the various variables; I'd rather avoid that can of worms).
> 
Sorry, wrong list. My comment was for Oscar
