### ISSUE TITLE
Rare CI crash in or after reesmat.tst

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4314]
I've been seeing the crash below (very rarely) in our CI tests, see e.g. here: https://github.com/gap-system/gap/pull/4307/checks?check_run_id=2021659536#step:6:9632
```
testing: /home/runner/work/gap/gap/tst/testinstall/reesmat.tst
dev/ci.sh: line 34:  9062 Killed                  $GAP --cover $COVDIR/${TEST_SUITE}.coverage <(echo 'SetUserPreference("ReproducibleBehaviour", true);') $SRCDIR/tst/${TEST_SUITE}.g
Error: Process completed with exit code 137.
```

I am pretty sure it was always in/after `reesmat.tst`. Here it was in the job "testpackages testinstall-loadall - ABI=64 - ubuntu-18.04" but I don't know if it always is there or not.

If anybody sees similar crashes, please log them here with a link to the relevant build log, so that we can see if there is a pattern, and perhaps start to investigate.

One theory: this is with all packages loaded; reesmat is about semigroups, I believe, and the semigroups package has C code... so I wonder if this is an issue with its kernel extension...? (In the above test, it was using semigroups 3.4.0). This is *WILD* guess, though, it very well may be in GAP itself. But perhaps somebody who knows more about reesmat test than me (@wilfwilson ?) can quickly see if this theory holds any water

**Comment by wilfwilson** [comment]
I will keep an eye out for this. And I'll have a look at `reesmat.tst` to see if anything stands out. My rough understanding is that Rees matrix semigroups are dealt with entirely on the GAP level in both the Semigroups package and in GAP itself. If that's the case, then this might be tricky to track down! We'll see 🙂

**Comment by wilfwilson** [comment]
Here's another crash like yours Max: https://github.com/gap-system/gap/runs/1936666470?check_suite_focus=true#step:6:9632

And here are two more crashes, with a different message, in a different job: https://github.com/gap-system/gap/runs/2021085658?check_suite_focus=true#step:6:9500 and https://github.com/gap-system/gap/runs/1942418601?check_suite_focus=true#step:6:9500

Job:
```
testpackages testinstall-loadall - ABI=32 NO_COVERAGE=1 - ubuntu-18.04
```
Crash:
```
testing: /home/runner/work/gap/gap/tst/testinstall/reesmat.tst
cannot allocate memory for thread-local data: ABORT
Error: Process completed with exit code 127.
```
See also https://github.com/semigroups/Semigroups/issues/634 for similar failures that we get in the Semigroups package CI.

**Comment by wilfwilson** [comment]
> My rough understanding is that Rees matrix semigroups are dealt with entirely on the GAP level in both the Semigroups package and in GAP itself.

That's not true. Rees matrix semigroups are defined in terms of an arbitrary 'underlying semigroup' (and a matrix with entries from that 'underlying semigroup') - and there's no particular restriction on the representation of the 'underlying semigroup'. So memory issues could creep in via the underlying semigroup.

Anyway – I haven't looked aat this further, yet.

**Comment by ChrisJefferson** [comment]
Jut to say, there is a discussion on this over at https://github.com/semigroups/Semigroups/issues/634 -- I think it might be related to semigroups allocating very large amounts of memory (and I don't know what the memory limit is on CI, but we could be hitting it).

**Comment by wilfwilson** [comment]
Just had another in the `testpackages testinstall-loadall - ABI=64 - ubuntu-18.04` job https://github.com/gap-system/gap/runs/2390184654?check_suite_focus=true
```
testing: /home/runner/work/gap/gap/tst/testinstall/reesmat.tst
dev/ci.sh: line 34:  6128 Killed                  $GAP --cover $COVDIR/${TEST_SUITE}.coverage <(echo 'SetUserPreference("ReproducibleBehaviour", true);') $SRCDIR/tst/${TEST_SUITE}.g
Error: Process completed with exit code 137.
```

**Comment by wilfwilson** [comment]
`testpackages testinstall-loadall - ABI=32 NO_COVERAGE=1 - ubuntu-18.04`
https://github.com/gap-system/gap/runs/2465347831?check_suite_focus=true
```
testing: /home/runner/work/gap/gap/tst/testinstall/reesmat.tst
cannot allocate memory for thread-local data: ABORT
Error: Process completed with exit code 127.
```

**Comment by wilfwilson** [comment]
`testpackages testinstall-loadall - ABI=64 - ubuntu-18.04`
https://github.com/gap-system/gap/runs/2513199383?check_suite_focus=true
```
testing: /home/runner/work/gap/gap/tst/testinstall/reesmat.tst
dev/ci.sh: line 34:  2570 Killed                  $GAP --cover $COVDIR/${TEST_SUITE}.coverage <(echo 'SetUserPreference("ReproducibleBehaviour", true);') $SRCDIR/tst/${TEST_SUITE}.g
Error: Process completed with exit code 137.
```

**Comment by fingolfin** [comment]
This seems to not occur anymore
