### ISSUE TITLE
Update dev/releases README

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#4316]
We've changed quite a bit of the release scripts after the last GAP Days. Me and @ruthhoffmann are looking into updating the README for the `make_archives.py` and `make_github_release.py`.

@wilfwilson could you maybe have a look into updating the description of the website script? Or is the way that it works still going to change a lot?

**Comment by wilfwilson** [comment]
Yes I will look into this. The script is probably going to change substantially, but it's still probably a good idea to have the README in sync now (in case those changes never happen, for instance 😉)

**Comment by ssiccha** [comment]
@ruthhoffmann and I have updated the part on the archive and github release creation. :)
