### ISSUE TITLE
Support `GO( 1, q )`, `SO( 1, q )`, `Omega( 1, q )`, `Omega( -1, 2, q )`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4321]
Currently GAP supports `GO( e, n, q )`, `SO(  e, n, q )`, `Omega( e, n, q )` only for `n` larger than 1, and also `Omega( -1, 2, q )` is not supported.

(This was observed in  oscar-system/Oscar.jl/pull/351.)

I think it would be good to admit also `n = 1` and `Omega( -1, 2, q )`.
(The ATLAS states on p. xi that "the groups are boring for `n` at most 2", but they can be useful in recursions.)

I can provide a pull request if there are no objections.

**Comment by fingolfin** [comment]
No objections, such a PR would be welcome, thanks!
