### ISSUE TITLE
Miscount of low-index-subgroups (of the Grigorchuk group). likely misuse of iterated maximals

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#4330]
There is a problem which causes a miscount of the number of subgroups of index 4 in the Grigorchuk group when using approximate finite presentations and the low-index-subgroups algorithm:
```
gap> LoadPackage("fr");
true
gap> G := GrigorchukGroup;
GrigorchukGroup
gap> phi := EpimorphismFromFpGroup(G,1);;
gap> Number(LowIndexSubgroupsFpGroup(Source(phi),4),H->Index(Source(phi),H)=4);
19
gap> phi := EpimorphismFromFpGroup(G,2);;
gap> Number(LowIndexSubgroupsFpGroup(Source(phi),4),H->Index(Source(phi),H)=4);
19
gap> phi := EpimorphismFromFpGroup(G,3);;
gap> Number(LowIndexSubgroupsFpGroup(Source(phi),4),H->Index(Source(phi),H)=4);
19
gap> phi := EpimorphismFromFpGroup(G,4);;
gap> Number(LowIndexSubgroupsFpGroup(Source(phi),4),H->Index(Source(phi),H)=4);
19
gap> phi := EpimorphismFromFpGroup(G,5);;
gap> Number(LowIndexSubgroupsFpGroup(Source(phi),4),H->Index(Source(phi),H)=4);
19
gap> phi := EpimorphismFromFpGroup(G,6);;
gap> Number(LowIndexSubgroupsFpGroup(Source(phi),4),H->Index(Source(phi),H)=4);
19
```
The (as far as I can tell!) correct value 31 is obtained when computing in quotients modulo level stabilizers instead:
```
gap> Length(Union(List(MaximalSubgroups(Image(EpimorphismPcGroup(G,3))),MaximalSubgroups)));
31
gap> Length(Union(List(MaximalSubgroups(Image(EpimorphismPcGroup(G,4))),MaximalSubgroups)));
31
gap> Length(Union(List(MaximalSubgroups(Image(EpimorphismPcGroup(G,5))),MaximalSubgroups)));
31
gap> Length(Union(List(MaximalSubgroups(Image(EpimorphismPcGroup(G,6))),MaximalSubgroups)));
31
```
Both the wrong value 19 and the correct value 31 can be found in the literature. -- For the former, see e.g. 

Laurent Bartholdi, Rostislav I. Grigorchuk, Zoran Sunik, Branch Groups,
https://arxiv.org/abs/math/0510294, page 68 -- 

and for the latter, see e.g. 

Rene Hartung, Coset enumeration for certain infinitely presented groups,
https://arxiv.org/abs/1106.0259, page 9.

I don't know whether the problem is an issue with the approximate presentations for the Grigorchuk group provided by the FR package, or a bug in the implementation of the low-index-subgroups algorithm for finitely presented groups, or something else.

The GAP version I am using is
```
 ┌───────┐   GAP 4.11.1 of 2021-03-02
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv7
 Configuration:  gmp 5.1.3, GASMAN
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.4, PrimGrp 3.4.1, SmallGrp 1.4.2, TransGrp 3.0
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by fingolfin** [comment]
To make this "work" without involving `fr`: First we define the fp group and verify the low index count (nb, it would be interesting if someone could cross check this in Magma).
```
gap> F:=FreeGroup("a","b","c","d");
<free group on the generators [ a, b, c, d ]>
gap> AssignGeneratorVariables(F);
#I  Assigned the global variables [ a, b, c, d ]
gap> G:=F/[ a^2, b^2, c^2, d^2, b*c*d, (a*d)^4, (a^-1*c*a*c)^4, (a^-1*c^-1*a*b*a^-1*c*a*b)^4, (a*d*(a*c)^2)^4, (a^-1*c*a*c*(a^-1*c*a*b)^2)^4 ];
<fp group on the generators [ a, b, c, d ]>
gap> Number(LowIndexSubgroupsFpGroup(G,4),H->Index(G,H)=4);
19
```
Now we define an epi onto the group produced by `EpimorphismPcGroup(G,3)` (or rather an isomorphic group);
in this quotient of order 128, we find 31 subgroups of index 4.
```
gap> H:=SmallGroup(128, 928);
<pc group of size 128 with 7 generators>
gap> AssignGeneratorVariables(H);
#I  Assigned the global variables [ f1, f2, f3, f4, f5, f6, f7 ]
gap> AssignGeneratorVariables(G);
#I  Global variable `a' is already defined and will be overwritten
#I  Global variable `b' is already defined and will be overwritten
#I  Global variable `c' is already defined and will be overwritten
#I  Global variable `d' is already defined and will be overwritten
#I  Assigned the global variables [ a, b, c, d ]
gap> hom:=GroupHomomorphismByImages(G, H, [a,b,c,d], [f1*f7, f2*f3*f4*f5*f6, f3*f5*f7, f2*f4*f7]);
[ a, b, c, d ] -> [ f1*f7, f2*f3*f4*f5*f6, f3*f5*f7, f2*f4*f7 ]
gap> IsSurjective(hom);
true
gap> subs:=Union(List(MaximalSubgroups(H),MaximalSubgroups));;
gap> ForAll(subs, h -> Index(H, h) = 4);
true
gap> Length(subs);
31
```

So, in conclusion, we have 19 subgroups of index 4 in `G`, and we have a quotient `H` of order 128 in which we find 31 distinct subgroups of index 4. Since these 31 distinct groups must have 31 distinct preimages, it indeed appears to me as if something is wrong here...


Maybe @hulpke has some insights?

**Comment by Stefan-Kohl** [comment]
Oh ... -- in fact I get the following:

gap> H:=SmallGroup(128, 928); # as above
<pc group of size 128 with 7 generators>
gap> AssignGeneratorVariables(H);
#I  Assigned the global variables [ f1, f2, f3, f4, f5, f6, f7 ]
gap> subs:=Union(List(MaximalSubgroups(H),MaximalSubgroups));;
gap> ForAll(subs, h -> Index(H, h) = 4);
true
gap> Length(subs);
31
gap> G := Image(IsomorphismFpGroup(H));
<fp group of size 128 on the generators [ F1, F2, F3, F4, F5, F6, F7 ]>
gap> Number(LowIndexSubgroupsFpGroup(G,4),H->Index(G,H)=4);
19

**Comment by hulpke** [comment]
What is `EpimorphismPcGroup`? Do you mean `EpimorphismPGroup`?

Where does `SmallGroup(128,928)` come from? For me, a PQ for prime 2, class 3 gives group 128,327  and that has 19 subgroups of index 4. 

There is actually still the old (completely independent) implementation of the Low Index in GAP which you can force as `LowIndexSubgroupsFpGroup(G,TrivialSubgroup(G),4,[])`. It gives the same 19 subgroups.

**Comment by fingolfin** [comment]
`EpimorphismPcGroup` comes from the `fr` package.

Anyway, I totally missed that `LowIndexSubgroupsFpGroup` only returns representatives of conjugacy classes. And indeed:
```
gap> H:=SmallGroup(128, 928);;
gap> subs:=Union(List(MaximalSubgroups(H),MaximalSubgroups));;
gap> Size(Set(subs,h->ConjugacyClassSubgroups(H,h)));
19
```

So, yeah, it seems all is in order after all. Phew :-).

**Comment by Stefan-Kohl** [comment]
Oh, indeed that explains things ... . -- The confusion could have been avoided by calling the function LowIndexSubgroupClassRepsFpGroup instead -- in analogy to MaximalSubgroupClassReps.
As e.g. MaximalSubgroups gives all maximal subgroups (also conjugate ones), it was just too natural
to assume that LowIndexSubgroups would do the same.
