### ISSUE TITLE
problem with `ApplicableMethodTypes`: bug or feature?

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4344]
When I dealt with pull request #4325, I observed the following behaviour of `ApplicableMethodTypes`:
```
gap> filt:= IsMatrixGroup and IsFinite;;
gap> type:= NewType( NewFamily( "new" ), filt );;
gap> meth:= ApplicableMethodTypes( IsomorphismPermGroup, [ type ], 0, "all" );;
gap> Length( meth );
6
gap> meth:= ApplicableMethodTypes( IsomorphismPermGroup, [ filt ], 0, "all" );;
#I  Family predicate cannot be tested
gap> Length( meth );
3
```
The reason for the difference is that `type` knows about implied filters of `filt` whereas the filter variant of `ApplicableMethodTypes` considers only `FLAGS_FILTER( filt )`.
The difference would disappear if if the filter variant would consider `WITH_IMPS_FLAGS( FLAGS_FILTER( filt ) )`.

Are there situations where this change would not be regarded as a bugfix?

**Comment by fingolfin** [comment]
I can't think of any situations were taking the implied flags into account would be detrimental -- i.e., I'd welcome a PR doing that, it'd be am improvement
