### ISSUE TITLE
Orthogonal groups (again)

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4355]
Here is one more open item (I hope the last one) concerning orthogonal groups in GAP.

I think the following is true. (Thanks, @frankluebeck, for this suggestion.)
Let $Q$ be the matrix of a quadratic form. Then the value of the form at the vector $v$ is $v Q v^{tr}$.
If we define the matrix $Q'$ by $Q'_{ii} = Q_{ii}$, $Q'_{ij} = 0$ for $i > j$, $Q'_{ij} = Q_{ij} + Q_{ji}$ for $ i < j$,
then $v Q v^{tr} = v Q' v^{tr}$ holds for all $v$.
By definition, the group element $M$ leaves the form invariant if $v M Q M^{tr} v^{tr} = v Q v^{tr}$ holds for all $v$.
This happens if and only if $(M Q M^{tr})' = Q'$ holds.
(For the "only if" part, take the $i$-th standard basis vector $e_i$ to check the equality of the $i$-th diagonal element, and take $e_i + e_j$ to check the equality of the entry in position $(i,j)$.)

Thus we can install a reasonable `\in` methods for orthogonal groups (missing up to now in even characteristic), and improve the tests for orthogonal groups.

**Comment by hulpke** [comment]
Yes. This is already done for Unitary and Symplectic groups.
