### ISSUE TITLE
Don't forget about "Python script to get an overview of changes with PyGithub #4277"

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#4364]
We have a lot of suggestions for the python script handling the overview of changes in #4277. 

Ideally, we would extract all that into separate issues. In the meanwhile, I'm just putting this here so we don't forget about #4277.

Sorry folks, for not structuring this issue more nicely.

**Comment by alex-konovalov** [comment]
1.  Add `None` to each section which didn't have any matching PRs.
