### ISSUE TITLE
InvariantQuadraticForm fails for primes >251

### ISSUE THREAD

**Issue by simonbrandhorst** [gap-system/gap#4376]
### Observed behaviour
```
GO(-1,2,257)
gap> InvariantQuadraticForm(g);
rec( matrix := [ [ z0, z0 ], [ 0z, z0 ] ] )
```

### Expected behaviour
```
gap> g:=GO(1,2,251);
GO(+1,2,251)
gap> InvariantQuadraticForm(g);
rec( matrix := [ [ 0*Z(251), Z(251)^0 ], [ 0*Z(251), 0*Z(251) ] ] )
```
looks better. 
No clue what z0 or 0z are but it does not seem correct. 

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.11.0 of 29-Feb-2020
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv7
 Configuration:  gmp 6.0.0, GASMAN, readline
 Loading the library and packages ...
 Packages:   Alnuth 3.1.2, AtlasRep 2.1.0, AutPGrp 1.10.2, CRISP 1.4.5, CTblLib 1.2.2, 
             FactInt 1.6.3, FGA 1.4.0, GAPDoc 1.6.3, IRREDSOL 1.4, LAGUNA 3.9.3, 
             Polycyclic 2.15.1, PrimGrp 3.4.0, SmallGrp 1.4.1, Sophus 1.24, TomLib 1.2.9, 
             TransGrp 2.0.5
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by ThomasBreuer** [comment]
The entries of the matrix in question look different from the usual FFEs from small finite fields.
The reason is that the construction of the group generators and the invariant forms involves the field with 257^2 elements.
Perhaps the representation of the entries could be improved, but still the result seems to be correct.

**Comment by fingolfin** [comment]
@simonbrandhorst Thanks for the report.

Here 0z is zero in the field GF(257), and z0 is one -- those are shorthand for `0*z` and `z^0`, where `z` is a primitive root (I don't like that they are printed like that all, but that's not the point right now; I filed issue #4380 on this).

The weird thing is that these are FFEs (finite field elements) in a representation that is normally intended for "large" fields only, not for tiny ones like GF(257). The weirdness goes on when one looks at the generators of the group:
```
gap> g.1;
[ [ 126, 15 ], [ 242, 141 ] ]
gap> g.2;
[ [ Z(257)^128, 0*Z(257) ], [ Z(257)^128, Z(257)^0 ] ]
```
Here, the first generator looks like an integer matrix, but actually is an element of the finite field (again: this is bad priniting).

The second generator however is in the usual internal FFE representation. Something is weird.

The relevant function here is `Ominus2`, so I'd start looking there. Perhaps @ThomasBreuer can take care of it.

**Comment by fingolfin** [comment]
@ThomasBreuer ah we overlapped! 

Yes, the result is actually correct (using code that's only available in latest GAP master):
```
gap> g:=GO(-1,2,257);
GO(-1,2,257)
gap> M:=InvariantQuadraticForm(g).matrix;
[ [ z0, z0 ], [ 0z, z0 ] ]
gap> RespectsQuadraticForm(M, g.1);
true
gap> RespectsQuadraticForm(M, g.2);
true
```

**Comment by ThomasBreuer** [comment]
@fingolfin I am going to improve `Ominus2`.
