### ISSUE TITLE
Random for non-dense lists

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4379]
In GAP 4.11 and in the master branch, currently we have the following.
```
gap> Random( [ 1,,,,,, 2 ] );
Error, List Element: <list>[5] must have an assigned value in
  Random( GlobalMersenneTwister, 1, Length( l ) 
 ) at /.../gap/lib/random.gi:240 called from 
<function "Random for an internal list">( <arguments> )
 called from read-eval loop at *stdin*:33
type 'quit;' to quit to outer loop
```

**Comment by ChrisJefferson** [comment]
This is interesting, did it ever work?

I'm not sure what the best thing to do is -- it's not obvious what to return if we hit an empty element (we obviously can't return fail, as the list might contain fail), and if we just skipped over empty values, that's not really a "random sample from the list" (depending on how you define random sample). That's before we decide how to implement it.

**Comment by ThomasBreuer** [comment]
@ChrisJefferson  Apparently nobody has ever seriously tried `Random` on non-dense lists. I found the problem just because I wanted to install some `Random` methods for special random sources, and since the documentation does not assume denseness, I looked at the library code in order to copy the behaviour. This attempt was not successful.

Then I asked myself the question which you raised: What should `Random` do in the case of a non-dense list?
I do not know a good answer.
One possibility would be to simply document that `Random` is not defined for non-dense lists.
Another possibility would be to generate random numbers until one hits a bound position.
(The latter choice could mean that `Random( [] )` starts an infinite loop. Trying what happens now in this case, I stumbled over the following.
```
gap> Random( GlobalMersenneTwister, 1, 0 );                           
1
```
This looks like another bug.)

**Comment by ThomasBreuer** [comment]
O.k., nobody else seems to have an opinion about this question.
I will provide a pull request that changes the relevant method installation to require a dense list.
Note that also `RandomList` is defined only for dense lists.

**Comment by ChrisJefferson** [comment]
Do we require that lists keep "IsDenseList" correctly up to date? I'd assumed (like many other attributes in GAP) a dense list might not set IsDenseList to true, unless explicitly requested.

I think PLists do keep it up to date, but other user-provided lists implementations might not.

**Comment by ThomasBreuer** [comment]
@ChrisJefferson The filter `IsDenseList` is defined as a category, not a property, thus one can rely on `IsDenseList` to be set if the list is dense.

**Comment by ChrisJefferson** [comment]
You would think by now I would have these straight :) Then it's fine to require IsDenseList, thanks.

**Comment by ThomasBreuer** [comment]
Now I found out that the IO package defines a `Random` method for lists that handles non-dense lists, by fetching an index until a position is found that is bound in the list.
Thus it will be better to install this method also in the GAP library, and to keep the documentation that allows one to enter non-dense lists.
(The methods in IO handle also `Random( rs, 1, 0 )` in a better way, by returning `fail`.
However, `Random( rs, [] )` runs into an error --not perfect.)

**Comment by fingolfin** [comment]
Sorry, I didn't see this issue before, only PR #4415 drew my intention to it.

Why does the fact that `io` implement a method for a non-dense list mean that we shouldn't make this more strict? Why can't we document that `Random` is for dense lists, and that for non-dense lists, the behavior is undefined, and may be anything from a random bound value, to an error, to an endless loop?

Of course if there was a usecase for `Random` on non-dense lists, that might alter the decision... But is there any?

Regarding `Random( rs, 1, 0 )` and `Random( rs, [] )`, IMHO both should trigger an `Error`, just like with `Representative`:
```
gap> Representative([]);
Error, <list> must be nonempty to have a representative
```
After all, the documentation says
> Random returns a (pseudo-)random element of the list or collection listorcoll
so for an empty collection, there is no permissible return value, which IMHO implies that an error must be raised. It also makes it a bit easier to find bugs where this happens quicker.

**Comment by ThomasBreuer** [comment]
I do not see a use case for `Random` on non-dense lists (and I have to be careful not to write "nonsense" instead), and it was my plan to restrict the definition from lists to dense lists. However, then IO cannot be loaded because the `InstallMethod` call for `IsList` runs into an error.
I am reluctant to remove functionality that is used in some package.

Concerning the behaviour of `Random` for empty intervals, one gets either `fail` or an error or a meaningless result. The documentation does not define what shall happen in this case. One could argue that this is intentionally left undefined. Still we could show a meaningful error message in the methods in the library.
(In the case of `Random` for empty lists, one gets already an error message.)
