### ISSUE TITLE
Appendices don't work correctly in TeX-based help

### ISSUE THREAD

**Issue by RussWoodroofe** [gap-system/gap#4430]
Several GAP packages that use the older TeX-based help system have appendices.  GAP is unable to find the html files for these appendices.  Indeed, the macros to build the manual.six file replace the appendix letters (A, B, ...) with the numbers following the last chapter.

I believe that the packages affected are exactly ace, CRISP, and Irredsol.  I previously reported this at ace's repository: https://github.com/gap-packages/ace/issues/23 .

A workaround would be to link e.g. CHAP00A.htm to e.g. CHAP007.htm.  Since only a small number of packages are affected, and as new packages are likely to use GAPDoc rather than the older system, this might be a reasonable thing to do.  Note that moving (rather than linking) would cause some other problems, as internal links in the help files use the letters.

A similar problem seems to hold for pdf-based help.  (But does anyone actually use that??)

### Observed behaviour
Typing e.g. "?the meaning of ace" at a gap> prompt display the help as a text file, even if the user has set their help viewer to a web browser.

### Expected behaviour
"?the meaning of ace" should load in the user's preferred help viewer.

**Comment by fingolfin** [comment]
Perhaps @frankluebeck has some insights into this?

**Comment by frankluebeck** [comment]
This seems to be a 25 year old bug which nobody noticed before. I would not fix it (in `doc/gapmacro.tex` and maybe in other places???). The idea of introducing links between the files with number/letter numbering proposed by @RussWoodroofe  sounds sensible to me.

**Comment by alex-konovalov** [comment]
How to achieve it: if packages use https://github.com/gap-system/ReleaseTools, one could put symlinks creation into `.release` file, that would be easy to maintain then.

**Comment by fingolfin** [comment]
Added the discussed workaround in ACE 5.5, see https://github.com/gap-packages/ace/commit/24d1ca8be944b9feb0695e34d1d2352cef7dfa1c

To avoid this in CRIPS and irredsol, I've submitted PRs https://github.com/bh11/crisp/pull/7 and https://github.com/bh11/irredsol/pull/16 -- now it is up to @bh11 to merge those and make new releases :-)

**Comment by fingolfin** [comment]
I believe all affected packages have workarounds in place these days.
