### ISSUE TITLE
Documentation of QuaternionAlgebra

### ISSUE THREAD

**Issue by cdwensley** [gap-system/gap#4445]
This problem occurs in 62.5.1 in the gap4r11 Reference Manual. 
I believe there is an error in the multiplication of basis elements {e,i,j,k}, judging by the case a=b=-1. 
The correct rule is:  kj=-jk=bi. 
This occurs in line 1785 of algebra.gd (gapdev version).

**Comment by fingolfin** [comment]
Agreed

**Comment by fingolfin** [comment]
PR #4447 fixes this
