### ISSUE TITLE
Panic in src/sysmem.c:259: Fatal error setting up multiheap

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4446]
Recently we've sometimes seen the error in the `testbugfix` CI job which uses `--enable-memory-checking`. For example:

https://github.com/gap-system/gap/runs/2468438194?check_suite_focus=true#step:6:182

It seems that it often goes away when restarting a job. But I've seen it at least 4 times since the switch to generating `c_oper1.c` on the fly.

This is in code by @ChrisJefferson so I hope he has an idea how to tackle this.

**Comment by ChrisJefferson** [comment]
Thanks, I went looking and saw it had disappeared, so I wondered if it had been a one-off. Now I know it's appearing and disappearing I will look into it. I have a reasonable idea.

**Comment by fingolfin** [comment]
Fixed by @ChrisJefferson in PR #4450
