### ISSUE TITLE
InducedSubgroupRepresentation is documented but does not exist

### ISSUE THREAD

**Issue by DominikBernhardt** [gap-system/gap#4476]
While talking to @FriedrichRober , we noticed that ` InducedSubgroupRepresentation` is  [documented](https://www.gap-system.org/Manuals/pkg/repsn/doc/chap2.html#X7EE113967DB4AB68), however it does not exist in GAP and even `grep -Inri  InducedSubgroupRepresentation` does not yield any results at all. Does `InducedRepresentation` replace this and someone forgot to document the new function and remove the old one or are we missing something?

**Comment by fingolfin** [comment]
InducedSubgroupRepresentation is not part of the GAP library, but rather of the repsn package, which you need to load in order to use it.

**Comment by fingolfin** [comment]
(Perhaps you are saying that the repan package has an issue, and that loading it doesn't help; in that case, I suggest reporting it on the repsn package issue tracker
