### ISSUE TITLE
Automate test coverage

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#450]
A very nice enhancement in the Continuous Integration framework would be to automatically check what proportion of the changed lines in a pull request get tested by the standard tests and to report on which ones.

It probably needs too many tests run to be done as part of the automatic testing on every commit that we have now, but maybe it could be done nightly or weekly, so that long-standing pull requests have this information.

It won't catch all problems, of course, but knowing that all the new code had been tested would add some confidence when deciding whether a commit is ready to merge.

**Comment by fingolfin** [comment]
That would be really nice, of course!

But for starters, it would already be nice if we had a clear, easily accessible and ideally very simple HOWTO somewhere which tells you how to obtain coverage infomration on your own computer! That way, people who are willing to make the effort at least have a chance. And we could point people making pull requests to it, too... To this end, I just filed a bunch of issues at https://github.com/gap-packages/profiling

**Comment by alex-konovalov** [comment]
We have now https://codecov.io/gh/gap-system/gap which does this, so this issue may be closed. I have posted some screenshots below. See also related #545, #546, #547.

![screen shot 2016-08-04 at 15 56 00](https://cloud.githubusercontent.com/assets/5751387/17406619/1dcdd6ae-5a5c-11e6-8a98-b51023a01297.png)
![screen shot 2016-08-04 at 15 53 31](https://cloud.githubusercontent.com/assets/5751387/17406620/1de43930-5a5c-11e6-9452-1a5ada5cdfe1.png)
