### ISSUE TITLE
License issue: perfect groups library now partially under non-GPL license

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4542]
PR #4530 just was merged; unfortunately I did not have the opportunity to review it before, otherwise I would have pointed it out there earlier: that PR added files which are under the artistic license 2.0. And there is nothing wrong with that at all (I was one of the people suggesting this as a suitable license for the various group libraries).

However, GAP right now claims that all its parts (other than packages) is under the GPL, which now is not accurate anymore. We'll have to adjust license statements in various places to address this.

This is a blocker for 4.12.

**Comment by wilfwilson** [comment]
Thank you for spotting this, since I did not when reviewing #4530 – I am (un)fortunately not very switched on when it comes to licencing issues.

**Comment by hulpke** [comment]
Would it help if I also (in addition to the artictic license) license under GPL2?

**Comment by fingolfin** [comment]
It might help; I'll read up a bot on it. All in all, though, I don't think it'll be hard to resolve this, no worries. It just should be done before 4.12

**Comment by fingolfin** [comment]
@hulpke so I think the easiest way forward would indeed be if you could dual license those files.
