### ISSUE TITLE
Update licensing information for the new Windows installers

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#4543]
In #4389, I added a GitHub Actions workflow which uses https://github.com/ChrisJefferson/sage-windows to automatically create 32- and 64-bit Windows installers whenever a GAP release is made, and upload the installers to the GitHub release.

As far as I am aware (although perhaps I am missing something), the idea is that for GAP 4.12.0 onwards, this is the system that we will use for making Windows installers, and the old method of @alex-konovalov will stop being used.*

_*I seem to recall @ChrisJefferson mentioning that the new installers will only work on Windows 10. Is this right? If so, we should explicitly agree and announce that we are dropping supporting for older Windows versions. Without a Windows installation (new or old), I have no way of checking this myself._

Therefore, we most likely need to update the information about the Windows installers in the manual. This is what is currently written in [Section 1.4 "Copyright and License"](https://www.gap-system.org/Manuals/doc/ref/chap1.html#X7950EFA183E3F666):

> The executable of GAP for Windows that we distribute was compiled with the gcc compiler supplied with Cygwin installation (https://cygwin.com/).
>
> The GNU C compiler is
>
> Copyright © 2010 Free Software Foundation, Inc.
>
> under the terms of the GNU General Public License (GPL).
>
> The Cygwin API library is also covered by the GNU GPL. The executable we provide is linked against this library (and in the process includes GPL'd Cygwin glue code). This means that the executable falls under the GPL too, which it does anyhow.
>
> The `cyggcc_s-1.dll`, `cygncurses-10.dll`, `cygncursesw-10.dll`, `cygpanel-10.dll`, `cygpopt-0.dll`, `cygreadline7.dll`, `cygstart.exe`, `cygwin1.dll`, `libW11.dll`, `mintty.exe` and regtool.exe` are taken unmodified from the Cygwin distribution. They are copyright by RedHat Software and released under the GPL. For more information on Cygwin, see https://www.cygwin.com.

How much of this is still relevant? Does some of it need removing? Does some different information need adding? I am not able to answer these questions.

**Comment by ChrisJefferson** [comment]
I would change this to something like this (as we now package so much, we don't want to list it all.


    GAP for Windows is packaged with several packages from Cygwin (https://cygwin.com/). Files from Cygwin are provided under their respective licenses (included). The GAP executable itself is released under the GNU GPL.
