### ISSUE TITLE
Should `RecNames` be sorted?

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#4576]
`RecNames` gives the component names of a record. `RecNames` is not guaranteed to be sorted (EDIT: in the sense of `Sort`), indeed it is easy to come up with examples where the output is not sorted:
```
gap> r := rec( a := 1, b := 2 );;
gap> RecNames(r);
[ "b", "a" ]
gap> IsSortedList(RecNames(r));
false
```
Perhaps it should be sorted? Why: well, for predictability, and consistency across GAP versions/sessions. One example is discussed in https://github.com/gap-packages/json/pull/24. I imagine that there are similar use cases, too. Note that even the manual example has to work around the names not being sorted!:
```
    gap> r := rec( a := 1, b := 2 );;
    gap> Set(RecNames( r )); # 'Set' because ordering depends on GAP session
    [ "a", "b" ]
```

The name of a component of a record is either a string or a small integer – by the way, this includes the empty string:
```
gap> r.("") := 3;; r;
rec( ("") := 3, a := 2, b := 1 )
```
Therefore, `RecNames` _could_ be sorted; and indeed `RecNames` must be duplicate free, so we could even make it be a `Set`. Of course, this would add some overhead (in which case we might  want to add a not-necessarily-sorted version for those who really care about performance) but perhaps it is worth doing?

**Comment by fingolfin** [comment]
I think this is a subset of issue #3271 and there we already agreed that was OK. (Of course in general code then still can't rely on `RecNames` returning a sorted list, unless it also requires GAP >= 4.12; but we have to start somewhere).

I am wondering if @ThomasBreuer or @frankluebeck can think of some obstacles to doing this?

**Comment by ThomasBreuer** [comment]
An important feature of records is that binding, accessing, and unbinding must be fast for large numbers of record components.

In situations where this efficiency is not relevant, it is desirable to have reproducible results in different GAP sessions.
(The most relevant example for me is printing of records: As soon as one wants to see a record's contents in human readable form, performance is not important, thus one can sort the components and thus gets a reproducible result. I remember that I had to adjust a lot of manual examples involving records (in the AtlasRep package) whenever the behaviour of records had changed a little bit, until we arrived at this convention.)

I do not have a feeling whether the same holds for `RecNames`, that is, whether performance is unimportant as soon as one calls `RecNames`. (Is there a way to avoid `RecNames`? For example, there is no `for x in record ... od` iteration for records.)

**Comment by frankluebeck** [comment]
The result of `RecNames` is sorted! But with respect to the internal numbers representing the component names. So, for a record `r`
```
List(RecNames(r), RNamObj);
```
is always a sorted list of small positive integers. The integer representing a component name depends on the order in which these names where first used in the current GAP session. But the ordering of the result of `RecNames(r)` is consistent within a GAP session (and so is the `<` comparison of records). 

I would not change the implementation of `RecNames`. The ordering of the result is the internal ordering of the components in the record (at least after the call of `RecNames`, there is a lazy sorting internally). And if new records are to be created with these component names then the most efficient order of assignment is given by this list:
```
gap> r := rec();; for i in [1..100000] do r.(i) := i;od;time;
139
gap> n := RecNames(r);;
gap> s := rec(); for a in n do s.(a) := a; x := s.(a); od; time;
rec(  )
27
gap> n := Reversed(n);;
gap> s := rec(); for a in n do s.(a) := a; x := s.(a); od; time;
rec(  )
17799
gap> # Advantage of lazy sorting:
gap> s := rec(); for a in n do s.(a) := a;  od; time;
rec(  )
139
gap> s.1000; time;
"1000"
6
```
Users who want an alphabetically sorted (or reproducible in all GAP sessions) list of component names  can use `Set(RecNames(r))`.

**Comment by ChrisJefferson** [comment]
The main problem with the ordering of RecNames is it tends to be stable for users, often between multiple releases of GAP, so people often rely on it (often multiple times we've relied on it in tests). Then, things break when a new name gets introduced. People (in my experience) rarely go and check if functions will produce the same answer.

I know we've had this discussion before (sorry about that!), but as time goes by I feel things like this should either be (a) repeatable, or (b) always change, as far as possible, so people don't rely on behaviour which isn't fixed.

For the curious, I checked how expensive it would be to make `RecNames` always sort it's output.

For a record with 5 elements, it adds about 10%.  For records with 1,000 elements it is about 2x slower.

If you were expecting the slowdown to be much bigger, it's because we make a fresh copy of all the names of members of the record every time RecNames is called, and all that memory allocation is fairly expensive (there are good technical reasons to always copy the strings, but I won't list them here unless anyone wants gory details).

If we made a new RecNames, we could of course add RecNamesUnsorted (better name possible) for those who want a higher performance version.

**Comment by wilfwilson** [comment]
Thanks for pointing to #3271 @fingolfin, I hadn't seen that.

On the whole, I favour default behaviour that is unsurprising and consistent at the expense of worse performance. Of course, that's just an opinion. In this context, I feel that if the slowdown is 'small', then it's worth sorting `RecNames`, which I feel gives unsurprising and consistent behaviour.

Whatever the case, I feel that this is an area where the documentation should be improved. The current manual entry does not explicitly state that the names are not sorted w.r.t `Sort`; it only tangentially mentions that the ordering is not necessarily the same in different GAP sessions; it does not mention that `Print` and `View` _do_ sort record names. If we cannot agree to change the behaviour of `RecNames`, then I will make a PR with such improvements.

**Comment by frankluebeck** [comment]
Thinking again I even stronger vote for leaving `RecNames` as it is. The function was designed to return the component names in the order which is most efficient for assignment to (new or old) records. It is a typical usage pattern that `RecNames` is called to create new records with the same component names or to copy (some) components to another record. You can easily find examples in the library or in packages. I thought that the code example above is a convincing demonstration. 

I cannot see why people would rely on an alphabetic ordering of component names.  Sure, in manual examples or test files it can be useful, but there one can just use `Set(RecNames(r))`, similar to other cases (for example, when an output depends on
randomization).

Also, the documentation of `RecNames` looks good to me. The given example even says that one should not assume a specific ordering.

**Comment by wilfwilson** [comment]
Thank you @frankluebeck, I understand your arguments and I am satisfied by them.

Given the context of this discussion, I think that the manual entry for `RecNames` could be more helpful to the curious or confused user – and to stop this issue from being recreated in the future ("why _isn't_ `RecNames` sorted in some more 'obvious' and/or stable way?").

Here is the entire manual entry:
<img width="547" alt="Screenshot 2021-06-29 at 10 00 35" src="https://user-images.githubusercontent.com/8956868/123791497-6a6c9000-d8d7-11eb-9eb6-781f45c76410.png">

Certainly it makes no incorrect statements, but in my opinion, it could be more detailed, and I don't think it is 'good' to define the behaviour of a function in a sentence fragment in a comment in a code example.

I will attempt to create a pull request that adds some sentences that distill the important points that have been raised in this discussion, to make it (in my opinion) clearer that:
* `RecNames` is sorted by `RNamObj` value.
* This means that the ordering given by `RecNames` is consistent within a GAP session, but is not necessarily consistent in different GAP sessions.
* This is done for reasons of efficiency.
  * (and possibly mention how to benefit from this, i.e. it is most efficient to populate the components of a record in the order given by `RNamObj` for the component names).
* You can apply `Set` to obtain a result that is consistent across GAP sessions.

**Comment by ChrisJefferson** [comment]
We could make `--enable-debug` apply an extra shuffle

**Comment by zickgraf** [comment]
> We could make --enable-debug apply an extra shuffle

I assume this is a `configure` argument? I'm using the pre-built docker images for tests, so a runtime argument would be nicer for my applications.

**Comment by fingolfin** [comment]
@zickgraf doing this in general would slow down things for a very specific usecase. However, you don't need to wait for us, you can do it yourself: just redefines `RecNames` to do what you want, i.e. like this (of course you also need to deal with the read-only status of RecNames)
```gap
realRecNames:=RecNames;
RecNames:=r -> Shuffle(realRecNames(r));
```


@wilfwilson I agree that the documentation for `RecNames` could be better, if you still are interested in submitting a PR doing so, that'd be highly welcome.

**Comment by zickgraf** [comment]
@fingolfin Thanks for this suggestion, I somehow didn't think of this. I have already uncovered some issues in homalg_project using this :-) (And sorry for hijacking this thread, in hindsight I should have opened a separate issue.)

**Comment by wilfwilson** [comment]
@fingolfin I made a change to the documentation in #4590 to implement the ideas that I laid out in https://github.com/gap-system/gap/issues/4576#issuecomment-870547134, so the manual entry now looks like this:

<img width="547" alt="Screenshot 2022-07-29 at 12 56 50" src="https://user-images.githubusercontent.com/8956868/181753784-b84c053b-8e91-4ec4-b5ad-c069dde81a67.png">

For me, this change was sufficient to address the issue. So I wouldn't mind if this GitHub issue were closed.
