### ISSUE TITLE
Segfault when calling an attribute setter which returns nothing

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#4578]
In `recog` I can do the following (I'd be surprised though if this had anything to do with `recog`):
```
gap> InstallMethod( NiceGens, "for a recognition node",
> [IsRecogNode],
>   function(ri)
>     return ;
>   end );
gap> r := EmptyRecognitionInfoRecord(rec(), Group(()), false);
<unfinished recognition node
 I:has no image
 K:has no kernel>
gap> NiceGens(r);
Segmentation fault (core dumped)
```
Since I guess this is not due to an infinite recursion, I've opened a new issue instead of adding this to #4340.

**Comment by ChrisJefferson** [comment]
So, the fail route is (all in C)

In DoMutableAttribute,  DoOperation1Args returns a '0' obj (which represents no return), which is then passed to 'DoSetAttribute', which calls DoOperation2Args, which calls DoOperationNargs, which calls TYPE_OBJ_FEO, which finally crashes.

The question is, exactly who should be "blamed"? 

I'm sure operations aren't required to return a value, so the blame lies with DoMutableAttribute passing to DoSetAttribute
