### ISSUE TITLE
missing example in the documentation of `LowLayerSubgroups`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4581]
The entry for `LowLayerSubgroups` in the GAP Reference Manual states

> In  the  example below, the result would be the same with leaving out the fourth function,
> but calculation this way is slightly faster.

However, the manual does not show any example for this function.
(And the function should be described as `LowLayerSubgroups( [<act>, ]<G>, <lim>[, <cond>[, <dosub>]] )` not as `LowLayerSubgroups( act, G, lim, cond, dosub )`.

**Comment by fingolfin** [comment]
The referenced comment was added by @hulpke in PR #2733
