### ISSUE TITLE
Problem with strings as lists

### ISSUE THREAD

**Issue by mohammadfarrokhi** [gap-system/gap#4585]
What is wrong with the following codes? 

```
 ┌───────┐   GAP 4.11.0 of 29-Feb-2020
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-cygwin-default64-kv7
 Configuration:  gmp 6.1.2, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2019.09.04, AutPGrp 1.10.2, Browse 1.8.8,
             CaratInterface 2.3.3, CRISP 1.4.5, Cryst 4.1.23, CrystCat 1.1.9, CTblLib 1.2.2, FactInt 1.6.3,
             FGA 1.4.0, Forms 1.2.5, GAPDoc 1.6.3, genss 1.6.6, IO 4.7.0, IRREDSOL 1.4, LAGUNA 3.9.3,
             orb 4.8.3, Polenta 1.3.9, Polycyclic 2.15.1, PrimGrp 3.4.0, RadiRoot 2.8, recog 1.3.2,
             ResClasses 4.7.2, SmallGrp 1.4.1, Sophus 1.24, SpinSym 1.5.2, TomLib 1.2.9, TransGrp 2.0.5,
             utils 0.69
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> IO_mkdir(['D', ':', '/', 'T', 'e', 's', 't'], 0);
fail
gap> IO_mkdir("D:/Test", 0);
true
```

**Comment by jackschmidt** [comment]
In section 3 of the IO manual it mentions this strict requirement:

> Strings must be specified as GAP strings and integers as GAP immediate integers.

You can see the strict check in the code:

https://github.com/gap-packages/io/blob/0ac79a77a5346fc4a17bff0c9fb9463f80ee06af/src/io.c#L736
```
  if (!IS_STRING(pathname) || !IS_STRING_REP(pathname) || !IS_INTOBJ(mode)) {
```

You can use `ConvertToStringRep` to satisfy the stricter check.

```
gap> x:=['t', 'e', 's', 't'];
"test"
gap> IO_mkdir(x,0);
fail
gap> ConvertToStringRep(x);
gap> IO_mkdir(x,0);
true
```

**Comment by fingolfin** [comment]
@mohammadfarrokhi why are you using such inputs, I wonder?

**Comment by mohammadfarrokhi** [comment]
> @mohammadfarrokhi why are you using such inputs, I wonder?

My program makes a folder containing a couple of files and the folder name is computed character by character from the given input. For instance the input can be a 0-1 matrix. The entries of the matrix can be looked as bits giving a sequence of bytes, so they can be converted into a string (sequence of characters) and be used as the file name, The matrix can be recovered from the folder name as well.

**Comment by jackschmidt** [comment]
You might find `HexStringInt` and `Concatenation` useful. These create strings in the `IsStringRep` format and can be used to construct filenames programmatically. You can just add the `ConvertToStringRep` to your existing code, but if you haven't yet made a lot of data:

Be careful when constructing filenames -- I recall that windows can misbehave if you create a file called `con`, and both Windows and MacOS can misbehave if one of the bytes in the filename is 0x3A, `:`.  Hex with a file ending like `.txt` works well. Leaving off the ending, or using arbitrary bytes in filenames will misbehave in different ways on different systems.

**Comment by fingolfin** [comment]
@mohammadfarrokhi so, did any of the given suggestions help?

**Comment by mohammadfarrokhi** [comment]
> @mohammadfarrokhi so, did any of the given suggestions help?

Yes, of course. Thanks a lot. The function `ConvertToStringRep` gives a simple solution.

**Comment by frankluebeck** [comment]
In former versions of GAP there were many places where GAP converted silently lists of characters to strings in `IsStringRep`. But this led to various efficiency problems so that we have removed these instances. 

Instead GAP now tries to keep objects in `IsStringRep` in this representation when they are changed (and when possible).

@mohammadfarrokhi: How do you build up your strings? Maybe you just need to start with `""` (instead of `[]`) and you can add characters and append strings?
```
gap> str := [];
[  ]
gap> Add(str,'d'); Add(str, '\n');
gap> Append(str, "hello");
gap> str;
"d\nhello"
gap> IsStringRep(str);
false
gap> str := "";
""
gap> Add(str,'d'); Add(str, '\n');
gap> Append(str, "hello");
gap> str;
"d\nhello"
gap> IsStringRep(str);
true
```
