### ISSUE TITLE
An example of how `StructureDescription` is fundamentally misguided

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#4598]
I came upon this example, which illustrates an interesting way how the iterated naming scheme of `StructureDescription` doesn't really produce a meaningful answer:

```
gap> f:=FreeGroup("a","b","c","d");;
gap> rels:=ParseRelators(f,"a2,b2,c2,d2,(ac)2,(bd)2,(ad)2,(ab)5,(bc)3,(cd)3");
[ a^2, b^2, c^2, d^2, (a*c)^2, (b*d)^2, (a*d)^2, (a*b)^5, (b*c)^3, (c*d)^3 ]
gap> h:=f/rels;;
gap> p:=Image(IsomorphismPermGroup(h));;
gap> StructureDescription(p);
"(SL(2,5) : A5) : C2"
gap> List(NormalSubgroups(p),Size);
[ 1, 2, 7200, 14400 ]
```

I would have guessed from the given description that the group has a normal subgroup of order 120, but of course that is not the case. Instead the structure might be described better as (nonsplit) 2\cdot (A5\wr 2).

**Comment by fingolfin** [comment]
Not sure why one would guess that, though? A normal subgroup $U$ of a normal subgroup $V$ of a group $G$ in general is not normal in $G$?

That said, I think nobody who knows about it claims that `StructureDescription` will give the "best" description in general (whatever that is). It's a toy tool with limited use.

All in all, I am not quite sure what the goal of this discussion issue is? Do you want to suggest improvements to `StructureDescription`? Or would like to add more warnings / examples / bad examples to its documentation? Or ...?

**Comment by hulpke** [comment]
The reason for posting (I posted here since I got the impressionthe email lists are not used any longer)  it was just to make others aware, and have the example somewhere on the record.
As what to do with it one could alternatively have `StructureDescription` descend from the top, but then again that might lead to even less useful names.

**Comment by fingolfin** [comment]
The mailing lists are still there, but there is not much to discuss there, I guess. I don't think issues are good for recording such "gotchas" (nor are mailing lists) -- if you think this is important, it should be in the manual entry for `StructureDescription`. No user will find it here (nor most GAP developers)

That said, I still don't understand what the problem is with your example?
