### ISSUE TITLE
Optionally allow passing generator inverses to `MappedWord` ?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4606]
Right now, if applying `MappedWord` to words in a free group, it (re)computes inverses of the image generators (resp. "divides" by them). This is fine if inversion / "division" is cheap (such as for words, or permutations), but not so much if it is expensive (e.g. big matrices, automorphisms, ...).

So perhaps we could add another (optional) argument to `MappedWord` which receives a list of the inverses of the generators? Or perhaps there is something better we could do?

Perhaps @hulpke has some insights about this.

**Comment by hulpke** [comment]
How about allowing a user to specify also inverses as extra generators in `MappedWord`, and usingh the associated images if needed. This way there is no need to allow for further parameter lists, and it is just a small change in the code.

**Comment by fingolfin** [comment]
But how would that work in general? Do we add a check to the start of MappedWord, where we check if the length of the given generator list is even, say 2n, and that `gens[i] * gens[i+n]` is one? That seems costly to do a lot.

**Comment by hulpke** [comment]
No. The generators are words, and we can just check whether any of them is an inverse letter (and then see which letter it is an inverse off).

**Comment by hulpke** [comment]
I have put a draft implementation of such changes into #4612 
If there is interest in keeping it, I will add similarly to the other methods for `MappedWord`.
