### ISSUE TITLE
Possible bug in computation with ideals of rings?

### ISSUE THREAD

**Issue by bkuzma1** [gap-system/gap#4629]
I have observed a wrong result when multiplying a particular ideal of a ring with some ring element. Concretely, the ring is Z4 x Z4 (direct sum of two copies of integers mod 4), the element is x=(2,2) and the ideal I is generated with this element. The correct answer of x*I should be {0}, but the code below gives {0,x}.

gap> R:=DirectSum(Integers mod 4, Integers mod 4);;
gap> x:=DirectProductElement( [ ZmodnZObj(2,4), ZmodnZObj(2,4) ] );; 
gap>  I:=Ideal(R , [x] );;
gap> Elements(I*x);
[ DirectProductElement( [ ZmodnZObj(0,4), ZmodnZObj(0,4) ] ), DirectProductElement( [ ZmodnZObj(2,4), ZmodnZObj(2,4) ] ) ]

 The last command produces wrong answer -- the correct answer should  contain only the first  element. The correct answer is obtained by the command
gap> Set(Elements( I ), y -> x*y ); 
[ DirectProductElement( [ ZmodnZObj(0,4), ZmodnZObj(0,4) ] ) ]

### GAP BANNER:
 ┌───────┐   GAP 4.11.0 of 29-Feb-2020
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv7
 Configuration:  gmp 6.1.2, GASMAN
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2019.09.04, 
             AutPGrp 1.10.2, CaratInterface 2.3.3, CRISP 1.4.5, Cryst 4.1.23, 
             CrystCat 1.1.9, CTblLib 1.2.2, FactInt 1.6.3, FGA 1.4.0, 
             Forms 1.2.5, GAPDoc 1.6.3, genss 1.6.6, IO 4.7.0, IRREDSOL 1.4, 
             LAGUNA 3.9.3, orb 4.8.3, Polenta 1.3.9, Polycyclic 2.15.1, 
             PrimGrp 3.4.0, RadiRoot 2.8, recog 1.3.2, ResClasses 4.7.2, 
             SmallGrp 1.4.1, Sophus 1.24, SpinSym 1.5.2, TomLib 1.2.9, 
             TransGrp 2.0.5, utils 0.69
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'

### processor:  Intel® Core™ i7-9750H CPU @ 2.60GHz × 12 

with best regards, bojan

**Comment by ChrisJefferson** [comment]
Just to clarify the problem (this isn't a bit of GAP I use that much).

`I*x` doesn't multiply every element in `I` by `x`, but does the same thing as `LeftIdeal(I, [x])`. Just checking exactly what you were expecting, and what is happening.

**Comment by bkuzma1** [comment]
Dear Christopher

Thank you so much for a clarification. This completely answers my question.


With best regards, Bojan
