### ISSUE TITLE
Multi-line comments

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#463]
I would like GAP to have multi-line comments. These would make writing GAPDoc easier (because you don't have to put `#` at the start of every line), and be useful for lots of other things. The only problem is the notation (I am happy to edit the parser).

I am happy for suggestions. I would like to suggest using `/*` and `*/`, like C. I realise at first this will sound terrible, but it has two advantages:
- It doesn't clash with anything else currently in the parser
- Most people will be familiar with what it means, from seeing it in other languages.

Of course, other suggestions are welcome.

**Comment by fingolfin** [comment]
I am not fully convinced. What are the "lots of other things" you/d want to apply it for?

**Comment by alex-konovalov** [comment]
I think the GAPDoc-related argument itself is already fully convincing. It's now a pain to reformat a
paragraph in GAPDoc in GAP source because of comments, and examples should be indented by `##  ` after pasting. Other things IMHO are any other non GAP-doc related comments - the easier is to insert comments into a file, the more commented code you have.

**Comment by markuspf** [comment]
I did suggest at some point to use the multiline strings for this purpose. Is there any obvious downsides I am missing?

**Comment by alex-konovalov** [comment]
The difference is that comments are ignored by the GAP parser and useful information is extracted from them using other tools (e.g. GAPDoc), while multiline strings will be read into GAP.

**Comment by rbehrends** [comment]
Some things to consider for multi-line comments:

1. Should it be possible to nest them?
2. Can comment delimiters occur naturally within comments (say, as part of GAPDoc formatting)?
3. Might choice of comment delimiters preclude some future syntax extensions (such as a unary `*` operator) and would that be a problem?

**Comment by frankluebeck** [comment]
I do not like the idea of multiline comments. 

In C it is bad that you cannot easily comment a whole function which contains (as it should!) comments, because nested /* */ are not allowed.
One looses the ability to detect locally (that is, in every line) what is code and what is in comments; in particular longer GAPDoc parts in source files which may even contain GAP code  may be unpleasant. And of course it is easy to overlook that some GAP code itself is commented out.

For editing GAPDoc in source files I use two techniques:
-  a macro in  my editor which toggles the inclusion/removal of `##  ` (2 # and 2 spaces) prefixes and moves to the next line   (similarly for `%%  ` in TeX files)
- or I write long lines and use `par` for reformatting paragraphs (which preserves  prefixes and postfixes)

**Comment by ChrisJefferson** [comment]
If we added, /* */ comments, I would want to allow them to be nested. This would still cause problems when (for example) a GAPDoc file had a single */ in it, without a matching /*.

Making it easier to write GAPDoc is (I think) one of the main selling points of this (along with commenting out code). I suppose I could specially configure my editor to add/remove `##`, but I don't really want to. But if enough people are against this, that's fine.

**Comment by stevelinton** [comment]
I agree about nesting. We definitely want to allow nesting and on reflection, we might want to use a longer or uglier comment delimiter to reduce risk of finding it in material embedded in comments.

I think apart from that, it would be enough to say that it is bad style to have comments what are likely to be more than one screen long (so 20 or 30 lines). Just about every editor I ever used will colour comments so you can actually see what is comment and what is not.

**Comment by Stefan-Kohl** [comment]
Nowadays we are having Unicode / UTF-8 encoding -- so why not just start a multi-line comment with 诂 and end it with 末? -- These characters are likely non-existent in any present GAP code or -documentation, and to allow nesting of comments would be no problem. Also, these characters are highly unlikely to obstruct future other syntax extensions.

**Comment by fingolfin** [comment]
@Stefan-Kohl Is that some kind of joke, or an attempt at sarcasm?

In any case, so far nothing in the GAP core language goes beyond use of ASCII, and I don't think we should change that. Also, to the best of my knowledge, we do *not* actually support UTF-8 beyond some basics in GAP (although GAPDoc adds some limited support). OK, I can enter and print a string containing UTF-8, but GAP knows nothing about glyphs and other concepts required for meaningful work with UTF-8, so e.g. string processing of UTF-8 beyond trivial tasks is mostly out of the question.

**Comment by Stefan-Kohl** [comment]
@fingolfin As far as I remember, the GAP source files have been converted from ISO-... to UTF-8 a couple of years ago. In practice this mostly changed the way the umlauts in some developers names were represented -- but if I understood @frankluebeck right, the idea was to extend the allowed character set in the files. Now, of course, admittedly a move towards allowing arbitrary Unicode characters would be somewhat drastic.

**Comment by ChrisJefferson** [comment]
@Stefan-Kohl : I don't think so, while we try to do a better job of printing out UTF-8 in strings, in various ways, the non-string parts of source files (like identifiers) still have to be ASCII. If anything happens to work, I think it is considered a bug and should be fixed.

**Comment by Stefan-Kohl** [comment]
@ChrisJefferson So you would consider e.g. the following as a bug?:

```
gap> translations := rec(("诂") := "comment", ("末") := "end");
rec( ("末") := "end", ("诂") := "comment" )
gap> RecNames(translations);
[ "诂", "末" ]

```

I agree that it does make some sense to stay with ASCII -- though my impression was that slowly moving towards extending the allowed character set was intended (like GAP slowly moved away from the classical 8+3 DOS format for file names),

**Comment by ChrisJefferson** [comment]
No, because those are all inside strings.

I would consider (for example):

`translations.诂 := "comment"` to be an error, and it is.

**Comment by Stefan-Kohl** [comment]
@ChrisJefferson When moving towards extending the character set, allowing this as well would be the next step. -- But of course when one stays with ASCII, as you say it is a bug.

**Comment by fingolfin** [comment]
Folks, this is getting way off-topic. If you want to discuss use of UTF-8 identifiers in GAP, please open a separate issue and/or discuss it on the mailing list. But *this* issue is about multiline comments.

**Comment by ChrisJefferson** [comment]
I think there was a general agreement against this issue
