### ISSUE TITLE
Force loading a package from a certain location

### ISSUE THREAD

**Issue by zickgraf** [gap-system/gap#4630]
I have two settings where I would like to force loading a package from a certain location, even if a version of the package which would normally be preferred is available at some other location:

1. When doing a git bisect of a package in my user GAP root dir which is also distributed with GAP: If the bisect gets older than the distributed version, the distributed version is loaded instead of the one I currently bisect.
2. Testing packages in CI which are also distributed by GAP: If the CI clones a fresh copy of the package, but this package does not pass the availability test (e.g. because it cannot be compiled), I want to get an error and not fall back to testing the distributed package.

Is there some way to achieve what I want? I do not mind if the solution is hacky :D

**Comment by fingolfin** [comment]
Try `SetPackagePath`

**Comment by zickgraf** [comment]
Thanks for the quick reply, `SetPackagePath` does the trick! If anyone is interested in this: I have written the following code to put into `gaprc` which always prefers packages from `GAPInfo.UserGapRoot` over other paths:
```
(function()
  local name, package_info, pos;
    for name in RecNames( GAPInfo.PackagesInfo ) do
        package_info := GAPInfo.PackagesInfo.(name);
        pos := PositionProperty( package_info, info -> StartsWith( info.InstallationPath, GAPInfo.UserGapRoot ) );
        if pos <> fail then
            SetPackagePath( name, package_info[pos].InstallationPath );
        fi;
    od;
end)();
```
