### ISSUE TITLE
Accessing records in the same way as lists

### ISSUE THREAD

**Issue by zickgraf** [gap-system/gap#4647]
### Motivation

Syntax trees are built from records and lists, e.g.
```
rec(
  type := "EXPR_FUNCCALL_2ARGS",
  funcref := ...,
  args := [ ..., ... ]
)
```

When working with syntax trees, I often have generic code looping over all children of a tree, recursively. This means that in the above example I first loop over the components `type`, `funcref`, and `args` of the record, and than over the entries `1` and `2` of the list `args`.  So my generic code always has to distinguish between the `record.(string)` and `list[index]` syntax. To avoid this, it would be nice to be able to access records using `record[string]`. Edit: Additionally, it would also be nice to set values via `record[string] := value`, because that's usually the reason for iterating over the tree in the first place.

### Proposal

This can easily be achieved by adding the following methods:
```
InstallOtherMethod( \[\],
    [ IsRecord, IsString ],
    { record, string } -> record.(string)
);

InstallOtherMethod( \[\]\:\=,
    [ IsRecord, IsString, IsObject ],

  function ( record, string, value )
    
    record.(string) := value;
    
end );
```

Would you accept a PR adding those methods, or would you rather not like mixing things up?

**Comment by ChrisJefferson** [comment]
I understand the wish to iterate through both, but I find it sometimes confusing in Javascript (which has a similar overload).

Also, I assume you would still need to know the range you are iterating over?

Another option would be to introduce something like a KeyValueIterator (name to be discussed), which would let you iterate over both an array ( [4,3] would iterate as [1,4] then [2,3] ) or record ( rec(a := 2, b := 3) would iterate as ["a",2], ["b",3], or the other way around as array indexing isn't fixed). Might also want a SortedKeyValueIterator (to fix record iteration).

**Comment by zickgraf** [comment]
> Also, I assume you would still need to know the range you are iterating over?

Yes, but I already have a special function for getting the range (because I usually want to consider keys with actual children, e.g. not the key `type`), so that would not be a problem for me.

> Another option would be to introduce something like a KeyValueIterator (name to be discussed), which would let you iterate over both an array ( [4,3] would iterate as [1,4] then [2,3] ) or record ( rec(a := 2, b := 3) would iterate as ["a",2], ["b",3], or the other way around as array indexing isn't fixed). Might also want a SortedKeyValueIterator (to fix record iteration).

Yes, I agree that this would be the "proper" way. Although I also want a common way to set entries, because that's usually the reason for iterating over the tree in the first place (sorry, I should have included that application explicitly in my first comment), so that would need a new interface, too. However, I fear that I currently do not have the time to properly discuss, implement and document a completely new interface, that's why have proposed the "simple" solution.

**Comment by fingolfin** [comment]
I need to think about this, but I am always a bit wary about adding such new syntax, simply because it's almost impossible to undo adding it even if it later turns out to be problematic.

But in the meantime, this doesn't sound like such a bad situation you are in? Can't you simply add your own helper functions for this? They could even be local (closures), like this `get:=function(obj,idx)  if IsRecord(obj) then return obj.(idx); else return obj[idx]; fi; end;` and similar for `set` ?

**Comment by zickgraf** [comment]
> Can't you simply add your own helper functions for this?

I could, but then I would either have to define `get` and `set` at many places, or bind `get` and `set` globally, or give it a longer name (e.g. `CAP_get`) which would not be nice to read. Additionally, nested `get`s would be hard to type/read (e.g. `get(get(record, "a"), "b")`, so I would really prefer an infix operator.

However, seeing that nobody seems to be enthusiastic about this (which I expected, but I wanted to ask anyway :D ), I will solve this in a different way: I do some pre- and postprocessing of the syntax trees anyway, so I will simply convert lists to records with components `"1"`, `"2"`, and so on. This is probably bad in terms of performance, but my code is not optimized on that level anyway.

Nevertheless, thanks for your comments and suggestions, @ChrisJefferson and @fingolfin!
