### ISSUE TITLE
Naming of groups is inconsistent

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4649]
Consider and compare these:
```
gap> G:=CyclicGroup(2);;
gap> StructureDescription(G);
"C2"
gap> DisplayCompositionSeries(G);
G (1 gens, size 2)
 | Z(2)
1 (0 gens, size 1)
gap> Z(2);  # actually the user might think `Z(2)` is a valid command... which it is, but not in this way:
Z(2)^0
```
Of course there are good reasons for all this, but a user (esp. one who is not a group theorist) may be quite confused by this.

[The manual entry for`DisplayCompositionSeries`](https://www.gap-system.org/Manuals/doc/ref/chap39.html#X82C0D0217ACB2042) does not specify which names it prints. Looking at it, it uses `IsomorphismTypeInfoFiniteSimpleGroup`, whose [manual entry](https://www.gap-system.org/Manuals/doc/ref/chap39.html#X7C6AA6897C4409AC) explains the notation -- perhaps the manual should make this explicit, by adding a reference?

Furthermore, perhaps [`StructureDescription`](https://www.gap-system.org/Manuals/doc/ref/chap39.html#X8199B74B84446971) could reference `IsomorphismTypeInfoFiniteSimpleGroup` and explain that it uses different naming? (and vice versa)

CC @fieker

**Comment by hulpke** [comment]
The `Z(2)` printed there is old code written by a diploma student in the mid-90s. I don't see a problem renaming it to C2.
