### ISSUE TITLE
Stabilizer and OrbitStabilizer sometimes produce incorrect results

### ISSUE THREAD

**Issue by daniel-dpk** [gap-system/gap#4659]
Apologies if I am using GAP incorrectly, but I could not figure out what exactly is not right with my input. So, here is my report.

When computing the stabilizer using either `Stabilizer()` or `OrbitStabilizer()`, the result is in some cases incorrect. In particular, it seems to depend on what other operations have been performed with the group before the call (e.g. `Size()`).

I have tested this with GAP 4.11.1 and the current master branch, both on Ubuntu 20.04 (gcc 9.3.0).

### Observed behaviour

The following reproduces the issue:

```
gap> p_gens := [PermutationMat((1,2), 6), PermutationMat((1,2,3,4,5,6), 6)];;
gap> p_group := Group(p_gens);;
gap> s1 := DiagonalMat([-1, -1, 1, 1, 1, 1]);;
gap> s_gens := Orbit(p_group, s1);;
gap> ps_gens := Concatenation(p_gens, s_gens);;
gap> ps_group := Group(ps_gens);;
gap> v := [1,2,1,1,0,0];;
gap> orbit := Orbit(ps_group, v);;
gap> Size(ps_group);;    # <-- IMPORTANT: Removing this line fixes it!
gap> stab := Stabilizer(ps_group, v);;
gap> Size(orbit) * Size(stab) = Size(ps_group);
false
```

If the `Size(ps_group)` call is removed, the last line results in `true`. However, if the `Stabilizer(...)` line is run again after this, it produces the wrong result again. My current workaround is to create a new group object for each stabilizer.

### Expected behaviour

The stabilizer calculation should not depend on other operations performed using the group.

### Copy and paste GAP banner (to tell us about your setup)

```
 ┌───────┐   GAP 4.11.1 of 2021-03-02
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv7
 Configuration:  gmp 6.2.0, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2020.08.11, AutPGrp 1.10.2, CRISP 1.4.5, Cryst 4.1.23,
             CrystCat 1.1.9, CTblLib 1.3.1, FactInt 1.6.3, FGA 1.4.0, GAPDoc 1.6.4, IRREDSOL 1.4.1, LAGUNA 3.9.3, Polenta 1.3.9,
             Polycyclic 2.16, PrimGrp 3.4.1, RadiRoot 2.8, ResClasses 4.7.2, SmallGrp 1.4.2, Sophus 1.24, SpinSym 1.5.2,
             TomLib 1.2.9, TransGrp 3.0, utils 0.69
```

### Another failing case

```
gap> p_gens := [(1,3)(2,4), (1,3,5,7,9,11,13,15)(2,4,6,8,10,12,14,16)];;
gap> p_reps := [PermutationMat((1,2), 8), PermutationMat((1,2,3,4,5,6,7,8), 8)];;
gap> s_gens := [
>     (1,2)(3,4), (1,2)(5,6), (1,2)(7,8), (1,2)(9,10), (1,2)(11,12),
>     (1,2)(13,14), (1,2)(15,16)
> ];;
gap> s_reps := [
>     DiagonalMat([-1,-1, 1, 1, 1, 1, 1, 1]),
>     DiagonalMat([-1, 1,-1, 1, 1, 1, 1, 1]),
>     DiagonalMat([-1, 1, 1,-1, 1, 1, 1, 1]),
>     DiagonalMat([-1, 1, 1, 1,-1, 1, 1, 1]),
>     DiagonalMat([-1, 1, 1, 1, 1,-1, 1, 1]),
>     DiagonalMat([-1, 1, 1, 1, 1, 1,-1, 1]),
>     DiagonalMat([-1, 1, 1, 1, 1, 1, 1,-1])
> ];;
gap> ps_gens := Concatenation(p_gens, s_gens);;
gap> ps_reps := Concatenation(p_reps, s_reps);;
gap> ps_group := Group(ps_gens);;
gap> ps_hom := GroupHomomorphismByImages(ps_group, ps_gens, ps_reps);;
gap> action := {x, g} -> x^Image(ps_hom, g);;
gap> v := [1,2,1,1,0,0,0,0];;
gap> stab := Stabilizer(ps_group, v, action);;
gap> orbit := Orbit(ps_group, v, action);;
gap> Size(orbit) * Size(stab) = Size(ps_group);
false
```

### A succeeding case

The following seems to work reliably (i.e. when changing the dimension or the vector).
```
gap> p_gens := [
>     PermutationMat((1,2), 8),
>     PermutationMat((1,2,3,4,5,6,7,8), 8)
> ];;
gap> s_gens := [
>     DiagonalMat([-1,-1, 1, 1, 1, 1, 1, 1]),
>     DiagonalMat([-1, 1,-1, 1, 1, 1, 1, 1]),
>     DiagonalMat([-1, 1, 1,-1, 1, 1, 1, 1]),
>     DiagonalMat([-1, 1, 1, 1,-1, 1, 1, 1]),
>     DiagonalMat([-1, 1, 1, 1, 1,-1, 1, 1]),
>     DiagonalMat([-1, 1, 1, 1, 1, 1,-1, 1]),
>     DiagonalMat([-1, 1, 1, 1, 1, 1, 1,-1])
> ];;
gap> ps_gens := Concatenation(p_gens, s_gens);;
gap> v := [1,2,1,1,0,0,0,0];;
gap> ps_group := Group(ps_gens);; # <-- NOTE: Don't do anything with it
gap>                              #           before the Stabilizer()
gap>                              #           call!
gap> stab := Stabilizer(ps_group, v);;
gap> orbit := Orbit(ps_group, v);;
gap> Size(orbit) * Size(stab) = Size(ps_group);
true
```

**Comment by fingolfin** [comment]
Thanks for this detailed report. I can confirm that this is a bug. I just had a quick check and your leading example was fine in GAP 4.8 and broken in 4.9; so we could use that to narrow down which commit may have caused it.

Alternatively, @hulpke may have an idea what might be behind it.

**Comment by fingolfin** [comment]
Interestingly, `git bisect` pinpoints this to commit af4993d101580d3a25fffaf8b01df4d9f594e3ec, which makes sense in so far as it changed which orbit stabilizer algorithm is used in your example.

Anyhow: the computation is done  by this method:
```gap
InstallOtherMethod( StabilizerOp,
        "`OrbitStabilizerAlgorithm' without domain",true,
        [ IsGroup, IsObject, IsList, IsList, IsFunction ], 0,
function( G, d, gens, acts, act )
local   stb,  p,  orbstab;
  
  if     IsIdenticalObj( gens, acts )
    and act = OnTuples  or  act = OnPairs  then
    # for tuples compute the stabilizer iteratively
    stb := G;
    for p  in d  do
	stb := StabilizerOp( stb, p, GeneratorsOfGroup( stb ),
			GeneratorsOfGroup( stb ), OnPoints );
    od;
  else
    orbstab:=OrbitStabilizerAlgorithm(G,false,false,gens,acts,
                                      rec(pnt:=d,act:=act,onlystab:=true));
    stb := orbstab.stabilizer;
  fi;
  return stb;
end );
```
Where the inputs can be derived from your example as follows:
```gap
G:=ps_group;; act:=OnPoints;; d:=Immutable(v);; gens:=GeneratorsOfGroup(G);; acts:=gens;;
```

This dispatches to the following method from `oprt.gi:1397`:
```
InstallMethod( OrbitStabilizerAlgorithm,"use stabilizer size",true,
  [IsGroup and IsFinite and CanComputeSizeAnySubgroup,IsObject,IsObject,
   IsList,IsList,IsRecord],0,
...
```
which however just dispatches on to `DoOrbitStabilizerAlgorithmStabsize` in the same file, line 1114.


Anyway, in there, it eventually runs into this code:
```
...
	  else
	    notinc:=notinc+1;
	    if notinc*50>indh and notinc>1000 then
	      # we have failed often enough -- assume for the moment we have
	      # the right stabilizer
	      #Error("stop stabilizer increase");
	      stopat:=p;
	      incstb:=false; # do not increase the stabilizer, but keep
	                     # representatives
	      actsinv:=List(acts,Inverse);
	    fi;
...
```

And indeed, if I uncomment the `Error`, then it is triggered by the stabilizer computation.

Now, that alone need not be a problem.. after all, later on the function does this:
```gap
    if Size(G)/Size(stb)>Length(orb) then
      if stopat=fail then
	Error("generators do not match group");
      fi;
      p:=stopat;
...
```
Alas, `stopat` is 122 here, not `fail`. So it goes on to try and find the missing generators. But clearly this doesn't work out here.

The code in question is by @hulpke so I hope he has more insights. In the meantime, I suggest that in the spot where there is an commented out `Error("after")`, perhaps we should insert a final check for `Size(G)/Size(stb)=Length(orb)` and if it fails, trigger an error -- that seems better than returning wrong results. (Of course a proper fix would be better :-) ).

**Comment by hulpke** [comment]
Doesn't the fix I did show up in github?

**Comment by daniel-dpk** [comment]
@hulpke I can confirm that this fixes the issue in all cases I found, thanks for this fast fix!

@fingolfin Thanks for the detailed analysis. This is a very helpful example of how to work through the code path taken.
