### ISSUE TITLE
Representation of the result of FactorGroup

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#468]
I am observing now 
```
########> Diff in [ "./../../lib/grp.gd", 2679, 2687 ]
# Input is:
FactorGroup(g,n);
# Expected output:
Group([ f1, f2 ])
# But found:
<pc group of size 6 with 2 generators>
########
```
for a couple of days in the test of the manual example with default packages loaded. First I was going to make this example not dependent on the representation of the factor group (e.g. just check that `StructureDescription` returns `"S3"`), but then checked that the manual says that `FactorGroup` returns the image of the `NaturalHomomorphismByNormalSubgroup`. However, when the code is run the first time in a new GAP session, we have
```
gap> g:=Group((1,2,3,4),(1,2));;n:=Subgroup(g,[(1,2)(3,4),(1,3)(2,4)]);;
gap> hom:=NaturalHomomorphismByNormalSubgroup(g,n);
[ (1,2,3,4), (1,2) ] -> [ f1*f2, f1 ]
gap> Size(ImagesSource(hom));
6
gap> FactorGroup(g,n);
Group([ f1, f2 ])
```
exactly as in the manual, but then for all subsequent repetitions of these example we have
```
gap> g:=Group((1,2,3,4),(1,2));;n:=Subgroup(g,[(1,2)(3,4),(1,3)(2,4)]);;
gap> hom:=NaturalHomomorphismByNormalSubgroup(g,n);
[ (1,2,3,4), (1,2) ] -> [ f1*f2, f1 ]
gap> Size(ImagesSource(hom));
6
gap> F:=FactorGroup(g,n);
<pc group with 2 generators>
```
In both cases F is a pc-group, it's only printed in a different way. Why?

**Comment by alex-konovalov** [comment]
I've analysed last night's Jenkins logs - this happened on all three slaves when GAP compiled in 64-bit mode, and on none of them in 32-bit mode.

**Comment by stevelinton** [comment]
The critical issue is whether the FactorGroup has HasParent. That is checked explicitly in the ViewObj method in grppc.gi.

Not sure why one call produces something with HasParent and the other doesn't.

**Comment by alex-konovalov** [comment]
Yes, and in the 1st case `Group([ f1, f2 ])` has itself as a parent. Time to try profiling package to see the diffs! I've used a quickstart guide @ChrisJefferson wrote for http://www.codima.ac.uk/school2015/ and it shows different lines executed in `FactorGroupNC` from `lib/grp.gi`: in the method below:
* in the 1st call IsBound(F!.nathom) returns `false`, so only `F!.nathom:=hom;` is called. Apparently `F` has `ParentAttr` set at this point.
* in the 2nd call, IsBound(F!.nathom) returns `true`, so to avoid cached homomorphisms a new group is created, which has no `ParentAttr`.

Failed test is a side effect os some other change which causes the 2nd branch of if-then-else to be executed at the 1st run of the test.
```
InstallMethod( FactorGroupNC, "generic method for two groups", IsIdenticalObj,
    [ IsGroup, IsGroup ],
function( G, N )
local hom,F,new;
  hom:=NaturalHomomorphismByNormalSubgroupNC( G, N );
  F:=ImagesSource(hom);
  if not IsBound(F!.nathom) then
    F!.nathom:=hom;
  else
    # avoid cached homomorphisms
    new:=Group(GeneratorsOfGroup(F),One(F));
    hom:=hom*GroupHomomorphismByImagesNC(F,new,
      GeneratorsOfGroup(F),GeneratorsOfGroup(F));
    F:=new;
    F!.nathom:=hom;
  fi;
  return F;
end );
```

**Comment by alex-konovalov** [comment]
Closed, as the reason was determined. We may see this in the tests again.
