### ISSUE TITLE
grpauto benchmark timeout

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#4698]
Looking at logs of weekly Jenkins tests in St Andrews, noticed that the `benchmark/grpauto` test in 64-bit build on Linux was last time successful on 2021-09-11. `../../bin/gap.sh -o 1g test2.g` took 285920 ms. After that it time outs after 500 minutes.

P.S. This happens in the master branch, in the stable-4.11 it passes in 153408 ms (also, almost twice faster).

**Comment by fingolfin** [comment]
Comparing these timings between `stable-4.11` and `master` is of limited use, as both the GAP code but also the set of tests changed.

**Comment by alex-konovalov** [comment]
@fingolfin the benchmarking examples there were not changed since 2016:
```
gap $ git log benchmark/grpauto/test2.g                                          
commit 686b0a525b9fe01243af6add1db95fc98d6e8285
Author: Chris Jefferson <caj21@st-andrews.ac.uk>
Date:   Mon Jan 20 18:46:47 2020 +0000

    Make CamelCase versions of GapExitCode, QuitGap and ForceQuitGap

commit e1d140be1d3265c7e384458f1801644c7e78e0c1
Author: Alexander Konovalov <alexander.konovalov@st-andrews.ac.uk>
Date:   Tue Nov 29 16:33:27 2016 +0000

    Added new benchmarks for automorphism groups/group isomorphisms
    
    These are based on the extended version of tst/teststandard/grpauto.tst
```

**Comment by hulpke** [comment]
Thank you -- this is ndeed a bug in changing the logic for when to use the newer algorithm that excluded large solvable groups. I will fix this.

**Comment by alex-konovalov** [comment]
@hulpke nice, thanks!
