### ISSUE TITLE
GAPDoc not loadable in 32-bit mode

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#4701]
What happens here?

```
gap-jenkins@kovacs:/circa/scratch/gap-jenkins/workspace/GAP-master-compilers/GAPCOPTS/32build/GAPREADLINE/readline/label/gcc-8/GAP-master-snapshot $ bin/gap.sh -r
 ┌───────┐   GAP 4.12dev built on 2021-11-14 23:21:18+0000
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default32-kv8
 Configuration:  gmp 6.2.1, GASMAN, readline
 Loading the library and packages ...
#I  gapdoc package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  GAP: needed package gapdoc cannot be loaded
Error, failed to load needed package `gapdoc' (version >= 1.2) at /circa/scratch/gap-jenkins/workspace/GAP-master-compilers/GAPCOPTS/32build/GAPREADLINE/readline/label/gcc-8/GAP-\
master-snapshot/lib/package.gi:1927 called from
func(  
 ); at /circa/scratch/gap-jenkins/workspace/GAP-master-compilers/GAPCOPTS/32build/GAPREADLINE/readline/label/gcc-8/G\
AP-master-snapshot/lib/system.g:228 called from
<function "CallAndInstallPostRestore">( <arguments> )
 called from read-eval loop at /circa/scratch/gap-jenkins/workspace/GAP-master-compilers/GAPCOPTS/32build/GAPREADLINE/readline/label/gcc-8/GAP-m\
aster-snapshot/lib/init.g:700
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```

but

```
gap-jenkins@kovacs:/circa/scratch/gap-jenkins/workspace/GAP-master-compilers/GAPCOPTS/32build/GAPREADLINE/readline/label/gcc-8/GAP-master-snapshot $ ls pkg/
GAPDoc-1.6.4/  packages-required-master.tar.gz	primgrp-3.4.1/	SmallGrp-1.4.2/  transgrp/
```

As you can see from screenshot at the bottom of #4699, this happens with each gcc version that is tested on Linux.

**Comment by fingolfin** [comment]
GAPDoc has no compiled code so the gcc version ought to be irrelevant.

anyway: I can't reproduce this, nor can our GH Actions based CI. Without being able to inspect your build setup it may be difficult to analyze this one

**Comment by alex-konovalov** [comment]
What I mean is that it's loadable in 32-bit cygwin builds, problem occurs only on Linux. I have seen other builds when it was smallgrp or primgrp not loadable. So the problems seems not to be in GAPDoc but in some datastructure corrupted in 32-bit GAP. The build script is
```
./autogen.sh
./configure ABI=32 --with-readline=yes
make zlib gmp
make CFLAGS=-Werror V=1
```

**Comment by fingolfin** [comment]
OK, but once again: it works fine for me. So we'll need more details. But I am somewhat sceptical that a data corruption could be the problem -- everything until that part works, after all.

**Comment by alex-konovalov** [comment]
Could this be the reason?
```
brk> GAPInfo.RootPaths;
[ "/circa/scratch/gap-jenkins/workspace/GAP-master-compilers/GAPCOPTS/32build/GAPREADLINE/readline/label/gcc-8/GAP-master-snapshot/" ]
brk> Length(GAPInfo.RootPaths[1]);
128
```
Too long directory name for the 32-bit architecture?

**Comment by fingolfin** [comment]
I don't think so. The buffers used here are the same length regardless of the architecture, and usually at least 1024 bytes long

**Comment by fingolfin** [comment]
Since you can interact with GAP interactively, perhaps also check `GAPInfo.PackagesInfo` -- is it empty? Or is just GAPDoc missing? In fact, *is* it missing? What does `GAPInfo.PackagesInfo.gapdoc;` give?

**Comment by ChrisJefferson** [comment]
I can reproduce this on the machine (kovacs).

The problem is that when reading the contents of a directory, getdents fails. I snippet of an strace:

```
openat(AT_FDCWD, "/circa/scratch/caj/gap", O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_CLOEXEC|O_DIRECTORY) = 4
getdents(4, /* 2 entries */, 32768)     = 32
getdents(4, 0xa483b14, 32768)           = -1 EOVERFLOW (Value too large for defined data type)
close(4)
```

having a google around, this is the same bug: https://github.com/moby/moby/issues/39732

which links to a glibc 2.28 bug: https://sourceware.org/bugzilla/show_bug.cgi?id=23960

Having a skim through that bug, the short version seems to be running 32 bit binaries on 64bit OSes is broken in some cases and OSes. I can reproduce the problem with a simple C program using opendir & readdir.

I tried a couple of quick things (like -D_FILE_OFFSETS_BITS=64 ), but they didn't fix it.

**Comment by fingolfin** [comment]
That would explain why I can't reproduce the problem on my Ubuntu/Debian machines, if it depends on the glibc version

**Comment by ChrisJefferson** [comment]
I am personally tempted to suggest the "fix" for this is we stop testing 32 bit builds of packages -- there are increasingly few 32 bit machines, and (as this bug shows) there isn't a lot of reason to run 32 bit executables on 64 bit machines, and support is getting worse over time (with fairly fundamental things breaking, like this).

**Comment by alex-konovalov** [comment]
I am tempted too - while I am still keeping an eye on Jenkins, sometimes what I do now is to delete all past failed test notifications and see if problems healed by themselves. Of course, if anyone in St Andrews volunteers, I can subscribe you to Jenkins fail notifications too ;-) but so far I haven't been able to find volunteers, and we don't have anyone employed for this post-CoDiMa.

**Comment by fingolfin** [comment]
Honestly, I would prefer to move away completely from relying on that Jenkins, and revive a full gap-infra -- hence that's one of the main goals for [the upcoming GAP Days](https://www.gapdays.de/gapdays2022-winter/program/). It should be no problem to also test 32bit builds there (should we choose to do so) -- and it likewise should be "easy" to stop testing those.

**Comment by alex-konovalov** [comment]
Completely agree. Jenkins as not visible from outside St Andrews is a major limitation. If not retire completely, then we could keep it only for longer tests beyond time limitations of free services. Those are not run that often and hence are easier to monitor. One other important part in Jenkins is the automation for the package update system though - that also needs to be redesigned. But that's another project, and they are not depend on each other...

**Comment by alex-konovalov** [comment]
Seems to me that the problem only observed when I am building GAP development version from source. 32-bit GAP still worked in the last test of the release candidate (i.e. when `./autogen.sh` was run prior to that in 64-bit mode).
