### ISSUE TITLE
CI: PR cannot be merged because of error in the float package

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#4712]
It looks that the CI tests for "load all packages" fail, because of an issue with the `float` package. Can we make this particular test advisory, and not required?

Thanks!

**Comment by fingolfin** [comment]
I merged your PR #4697 using admin override. We are looking into the float issue (and have been for the past two weeks). We may have to revert float to an older version, or drop official 32bit support (which is essentially what "ignoring these failures" amounts to), but for now I am still hoping we can find a less radical solution. ... :-(

**Comment by alex-konovalov** [comment]
Float 1.0.2 is now in https://github.com/gap-system/gap-distribution/releases/tag/package-archives
