### ISSUE TITLE
outer automorphism group of G2(q)

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4724]
According to (for example) the Atlas of Finite Groups (Chapter 3, Section 3) and to Kleidman's 1988 paper, the outer automorphism groups of the simple groups of type G_2(q) are cyclic.
However, the following happens in GAP 4.11.1.
```
gap> q:= 9;;
gap> n:= q^6*(q^6-1)*(q^2-1);  # order of G2(q)
22594320403200
gap> r:= IsomorphismTypeInfoFiniteSimpleGroup( n );
rec( name := "G(2,9)", parameter := 9, series := "G", shortname := "G2(9)" )
gap> info:= DataAboutSimpleGroup( r );
rec( 
  allExtensions := [ [ 2, "2_1" ], [ 2, "2_2" ], [ 2, "2_3" ], [ 4, "2^2" ] ],
  classicalId := rec( parameter := [ 2, 9 ], series := "G" ), 
  fullAutGroup := [ 4, "2^2" ], 
  idSimple := rec( name := "G(2,9)", parameter := 9, series := "G", 
      shortname := "G2(9)" ), tomName := "G2(9)" )
```
The situation in the master branch is worse in the sense that the result record contains more components which are related to the wrong structure claimed for the outer automorphism group, as follows.
```
gap> info:= DataAboutSimpleGroup( r );
rec( 
  allExtensions := [ [ 2, "2_1" ], [ 2, "2_2" ], [ 2, "2_3" ], 
      [ 4, "2^2" ] ], 
  classicalId := rec( parameter := [ 2, 9 ], series := "G" ), 
  efactors := [ 1, 2, 2 ], fullAutGroup := [ 4, "2^2" ], 
  idSimple := rec( name := "G(2,9)", parameter := 9, series := "G", 
      shortname := "G2(9)" ), 
  outerAutomorphismGroup := <pc group of size 4 with 3 generators>, 
  tomName := "G2(9)" )
```
The function `DataAboutSimpleGroup` is currently undocumented, and I do not know where the new `efactors` component is intended to be used. If its meaning is `[ d, f, g ]` for the orders of the three cyclic groups of diagonal, field, and graph automorphisms then this component is fine, and just the call of `AbelianGroup` in the code of `DataAboutSimpleGroup` is wrong.

(By the way, also [the corresponding Wikipedia article](https://en.wikipedia.org/wiki/List_of_finite_simple_groups#Chevalley_groups,_E6(q),_E7(q),_E8(q),_F4(q),_G2(q)) contains this error, it claims a direct product structure for the group generated by field and graph automorphisms.)

**Comment by fingolfin** [comment]
As far as I can tell, `DataAboutSimpleGroup` was added in GAP 4.7 by @hulpke and already then returned the same information.

**Comment by hulpke** [comment]
Yes, this is wrong (and easily fixed).
Besides the data itself being wrong, the way it is used in the library will not have caused wrong results, as the order of the automorphism group is the same, and the extension names are only used as candidates for finding tabulated information.

*Question:* Are there other exceptional cases in which the graph automorphisms power on field or diagonal automorphisms?

As for the `efactors` component, it is included as a debugging tool for the function, but might actually be useful for other cases.

**Comment by ThomasBreuer** [comment]
@hulpke Concerning your question, the Atlas of Finite Groups (Chapter 3, Section 3) says:
> The outer automotphism group is a semidirect product (in this order) of groups of orders d (diagonal automorphisms), f (field automorphisms), and g (graph automorphisms modulo field automorphisms), except that for
>      B_2(2^f), G_2(3^f), F_4(2^f)
> the (extraordinary) graph automorphism squares to the generating field automorphism.

**Comment by hulpke** [comment]
@ThomasBreuer 
Thank you. Then a similar fix is required for F4 (and I'll do it).
B2 is handled as C2 -- symplectic, and the classical groups get their outer automorphism group differently (through `OuterAutoSimplePres` that uses a result of Bray/Holt/Roney-Dougal p. 36/37), so that should resolve it.
