### ISSUE TITLE
SocleTypePrimitiveGroup returns wrong result for non-primitive groups

### ISSUE THREAD

**Issue by DominikBernhardt** [gap-system/gap#4735]
### Observed behaviour
```
G := DirectProduct( AlternatingGroup(5), AlternatingGroup(6));; SocleTypePrimitiveGroup(G);
rec( name := "A(6) ~ A(1,9) = L(2,9) ~ B(1,9) = O(3,9) ~ C(1,9) = S(2,9) ~ 2A(1,9) = U(2,9)", parameter := 6, series := "A", width := 2 )
```
### Expected behaviour
Clearly the socle of `G` is a direct product of `A_5` and `A_6`. The socle of a non-primitive group is generally not isomorphic to `T^k` for a non-abelian finite simple group `T` so this function should return an error as `G` does not primitively.

**Comment by ThomasBreuer** [comment]
@DominikBernhardt The documentation of `SocleTypePrimitiveGroup` explicitly says

> If G does not have a faithful primitive action, the result is undefined.

So why do you expect an error in your example?

**Comment by fingolfin** [comment]
@DominikBernhardt I've merged your patch, but indeed Thomas has a point: strictly speaking you misused the function and it did what it promised. We can add a check here, but not in every place and for everything (slow downs add up, as does code bloat).

**Comment by DominikBernhardt** [comment]
@fingolfin and @ThomasBreuer I agree that you have a point, the documentation states that the result is undefined if the group does not have a faithful primitive action. I did not mean to say I expect an error, however testing for primitivity is rather cheap (nearly-linear time algorithm). I guess my point is "the result is undefined" is fairly unspecific. `SocleTypePrimitiveGroup` returns the last non-trivial group in a composition series of `soc(G)`. Now I guess as the test is that cheap I wanted to add it to make it a bit more user friendly.

**Comment by ThomasBreuer** [comment]
@DominikBernhardt Currently `SocleTypePrimitiveGroup` has exactly one method. Thus its documentation can be changed such that `SocleTypePrimitiveGroup` signals an error if the input is not primitive. If we leave the documentation as it is then new methods may decide to return some group instead of calling `Error`, and you cannot rely on the behaviour you wanted to achieve.

**Comment by DominikBernhardt** [comment]
Thanks, good idea @ThomasBreuer . I will change the documentation accordingly and submit a PR.

**Comment by ThomasBreuer** [comment]
Thanks @DominikBernhardt !
