### ISSUE TITLE
`Earns` documentation does not match behaviour

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#4744]
Just a minor issue here, the GAP reference manual says that `Earns` returns a list of subgroups:
> returns a list of the elementary abelian regular (when acting on Omega) normal subgroups of G.

But (at least in some cases) rather than returning a list, it seems to return either a single group or `fail`.
```
gap> n := 8;; List([1..NrPrimitiveGroups(n)], i -> Earns(PrimitiveGroup(n, i)));
[ Group([ (1,7)(2,8)(3,5)(4,6), (1,2)(3,4)(5,6)(7,8), (1,3)(2,4)(5,7)(6,8) ]),
  Group([ (1,7)(2,8)(3,5)(4,6), (1,4)(2,3)(5,8)(6,7), (1,2)(3,4)(5,6)(7,8) ]),
  Group([ (1,7)(2,8)(3,5)(4,6), (1,3)(2,4)(5,7)(6,8), (1,2)(3,4)(5,6)(7,8) ]), fail, fail, fail, fail ]
```

**Comment by hulpke** [comment]
Will fix.

**Comment by hulpke** [comment]
> I'll note that I've not yet found an example where a list is returned: it's always either a single group, or `fail`:

That's because there are only methods for primitive groups. ONS theorem implies that if a primitive group has an EARNS, it is unique.

The *definition* of EARNS however could apply to other groups, and if imprimitive, there *can* be multiple EARNS. Viz:

```
gap> g:=TransitiveGroup(8,22);;
gap> n:=Filtered(NormalSubgroups(g),x->IsElementaryAbelian(x) and IsRegular(x,[1..8]));
[ Group([ (1,8)(2,3)(4,5)(6,7), (1,3)(2,8)(4,7)(5,6), (1,7)(2,5)(3,4)(6,8) ]),
  Group([ (1,5)(2,6)(3,7)(4,8), (1,3)(2,8)(4,6)(5,7), (1,8)(2,3)(4,5)(6,7) ])
 ]
```

**Comment by wilfwilson** [comment]
Thanks for the details @hulpke 🙂
