### ISSUE TITLE
Decreased sensitivity of GAP to [ctrl][c] and [ctrl][z]

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#4747]
Since a while, I observe that pressing [ctrl][c] during a GAP computation does only sometimes (and often only after holding the keys for a longer time) cause GAP to enter a break loop. Similarly, [ctrl][z] does only sometimes end the GAP process (and also this often only after holding the keys for a longer time). I am not sure when this problem started, but in any case I observe it in GAP 4.11.1 under Ubuntu.

**Comment by fingolfin** [comment]
Could you be a bit more specific and e.g. state a concrete computation that exhibits this problem for you? 

Also:
- which Ubuntu version is that, exactly?
- Can you try an older GAP version on the same version to verify it works "better" there for you?

**Comment by Stefan-Kohl** [comment]
@fingolfin I don't know a concrete way to reliably reproduce the problem. -- If I find one, I will tell. I also don't know how to check that the problem for sure isn't present in some given other setting (GAP version / OS).

**Comment by fingolfin** [comment]
Well, then I am afraid there is not much we can do to help you - at least I don't have the same issue, and nobody else reported this, so without a way to reproduce, or even knowing whether it is caused by GAP or something else on your machine, I am not sure what we *could* do...?

**Comment by ChrisJefferson** [comment]
One possiblity I will suggest, as more packages (semigroups, digraphs, ferret) are writing in C/C++, and spend a long time in kernel code, while in that code pressing ctrl+c will (generally) not do anything, until they re-enter GAP code. So, if you are using such packages, ctrl+c often doesn't seem to work for a while. These packages can do things to make ctrl+c more responsive, but in my experience it's quite fiddly and easy to get wrong.

**Comment by Stefan-Kohl** [comment]
@fingolfin Now it seems that the cause of the problem is a combination of a hardware problem with the [ctrl]-key on my keyboard and (to a lesser extent) the effects @ChrisJefferson described. -- Sorry for the false alarm!

**Comment by fingolfin** [comment]
No worries. Hope your keyboard can be fixed, I know this is annoying (for a while my e key was stuck... ugh)
