### ISSUE TITLE
CI: `codecov/codecov-action@v2` has stopped uploading coverage data about GAP code

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#4752]
You can see by exploring the [Codecov webpages for GAP](https://app.codecov.io/gh/gap-system/gap) that coverage for GAP code is no longer being uploaded.

From a CI build yesterday we see the expected directories are considered:
> <img width="1160" alt="before" src="https://user-images.githubusercontent.com/8956868/152524163-375aa0ac-45ed-4ee5-9f4b-8e632fc7b18e.png">

But from the most recent CI build today, only the `src` directory has coverage data:
> <img width="1156" alt="after" src="https://user-images.githubusercontent.com/8956868/152524157-8d05536c-dc8b-4110-accb-56aad96e30a2.png">

The immediate culprit is that the 'Codecov report uploader' internally has been updated from v0.1.15 to v0.1.16, as can be seen immediately below the Codecov logo in the following logs.

From a build yesterday, we see that lots more files are uploaded, including `gap-coverage.json`:

https://github.com/gap-system/gap/runs/5046212057?check_suite_focus=true
```
Run codecov/codecov-action@v2
==> linux OS detected
https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
==> SHASUM file signed by key id 806bb28aed779869
==> Uploader SHASUM verified (330066ecce62f2cdcfd2fe1845095475f51bbad9649dce81ac7b663dc884bbef  codecov)
==> Running version latest
==> Running version v0.1.15
/home/runner/work/_actions/codecov/codecov-action/v2/dist/codecov -n  -Q github-action-2.1.0
[2022-02-03T02:41:45.483Z] ['info'] 
     _____          _
    / ____|        | |
   | |     ___   __| | ___  ___ _____   __
   | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
   | |___| (_) | (_| |  __/ (_| (_) \ V /
    \_____\___/ \__,_|\___|\___\___/ \_/

  Codecov report uploader 0.1.15
[2022-02-03T02:41:45.488Z] ['info'] => Project root located at: /home/runner/work/gap/gap
[2022-02-03T02:41:45.492Z] ['info'] -> No token specified or token is empty
[2022-02-03T02:41:45.498Z] ['info'] Searching for coverage files...
[2022-02-03T02:41:45.979Z] ['info'] Warning: Some files located via search were excluded from upload.
[2022-02-03T02:41:45.979Z] ['info'] If Codecov did not locate your files, please review https://docs.codecov.com/docs/supported-report-formats
[2022-02-03T02:41:45.980Z] ['info'] => Found 124 possible coverage files:
  #usr#include#x86_64-linux-gnu#bits#fcntl2.h.gcov
  #usr#include#x86_64-linux-gnu#bits#stdio2.h.gcov
  #usr#include#x86_64-linux-gnu#bits#stdlib.h.gcov
  #usr#include#x86_64-linux-gnu#bits#string_fortified.h.gcov
  #usr#include#x86_64-linux-gnu#bits#unistd.h.gcov
  #usr#include#x86_64-linux-gnu#gmp.h.gcov
  #usr#include#x86_64-linux-gnu#sys#stat.h.gcov
  build#c_oper1.c.gcov
  build#c_type1.c.gcov
  gap-coverage.json
  src#ariths.c.gcov
  src#ariths.h.gcov
  src#bags.c.gcov
  src#bags.inc.gcov
  src#bits_intern.h.gcov
  src#blister.c.gcov
  src#blister.h.gcov
  src#bool.c.gcov
  ...
```

But `gap-coverage.json` is absent from the more recent builds:

https://github.com/gap-system/gap/runs/5061361464?check_suite_focus=true
```
Run codecov/codecov-action@v2
==> linux OS detected
https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
==> SHASUM file signed by key id 806bb28aed779869
==> Uploader SHASUM verified (55be6c308e0644890a4ff3a00b508d0cdc6cc04edfd332986a811bceda162d11  codecov)
==> Running version latest
==> Running version v0.1.16
/home/runner/work/_actions/codecov/codecov-action/v2/dist/codecov -n  -Q github-action-2.1.0
[2022-02-04T02:35:26.692Z] ['info'] 
     _____          _
    / ____|        | |
   | |     ___   __| | ___  ___ _____   __
   | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
   | |___| (_) | (_| |  __/ (_| (_) \ V /
    \_____\___/ \__,_|\___|\___\___/ \_/

  Codecov report uploader 0.1.16
[2022-02-04T02:35:26.698Z] ['info'] => Project root located at: /home/runner/work/gap/gap
[2022-02-04T02:35:26.701Z] ['info'] -> No token specified or token is empty
[2022-02-04T02:35:26.707Z] ['info'] Searching for coverage files...
[2022-02-04T02:35:27.264Z] ['info'] Warning: Some files located via search were excluded from upload.
[2022-02-04T02:35:27.264Z] ['info'] If Codecov did not locate your files, please review https://docs.codecov.com/docs/supported-report-formats
[2022-02-04T02:35:27.265Z] ['info'] => Found 74 possible coverage files:
  build#c_oper1.c.gcov
  build#c_type1.c.gcov
  src#ariths.c.gcov
  src#bags.c.gcov
  src#blister.c.gcov
  src#bool.c.gcov
  ...
```

**Comment by fingolfin** [comment]
Extremely annoying. I wonder if it also affects packages?

I guess we could try to pass the filename explicitly to the action via the `files` parameter (see https://github.com/codecov/codecov-action), though I am not sure if this means that file is uploaded *in addition* to those which the action autodetects (which I hope is what happens), or whether it disables the automatic upload (then we'd have to do more).

**Comment by wilfwilson** [comment]
I think it does affect packages yes. It was even causing Vole’s tests to hang for 6 hours, so I have just disabled code coverage.

**Comment by fingolfin** [comment]
perhaps to fix it centrally, we can rename the JSON file to something the Codecov uploader still picks up automatically ... unfortunately they don't really document how they auto detect coverage files... I filed an issue for that, too

**Comment by fingolfin** [comment]
Looking at https://github.com/codecov/uploader/blob/main/src/helpers/files.ts#L155 there is a pattern `'*coverage*.*'` which I would expect to match `gap-coverage.json`. Weird. 

Another name on the accept list is `coverage-final.json` so we could rename to that and see if it helps... I am experimenting in PR #4755

**Comment by fingolfin** [comment]
Interesting... from my PR, where I set files to accept `gap-coverage.json`, it says:
```
[2022-02-05T16:51:19.916Z] ['info'] Warning: Some files passed via the -f flag would normally be excluded from search.
[35](https://github.com/gap-system/gap/pull/4755/checks#step:14:35)
```
Also, it *only* uploads the JSON, not the *.gcov files...

I also tried to rename the file to `coverage-final.json`, which is on the accept list, but it still wasn't uploaded.


Anyway, seems we are not the only ones to notice: https://github.com/codecov/uploader/issues/614

So perhaps they will fix it in the uploader...

**Comment by fingolfin** [comment]
Seems codecov deployed a fix. I've just restarted https://github.com/gap-system/gap/runs/5075197471?check_suite_focus=true so we can see if this restores the upload

**Comment by fingolfin** [comment]
Indeed, it is fixed, phew :-)
