### ISSUE TITLE
sysinfo.gap, bin/gac, bin/gap, bin/gap-bin and many other files aren't installed by the install target

### ISSUE THREAD

**Issue by yurivict** [gap-system/gap#4770]
The FreeBSD port has to install ```sysinfo.gap``` manually [here](https://cgit.freebsd.org/ports/tree/math/gap/Makefile#n90) along with many other files.

The complete list:
[missing-files.txt](https://github.com/gap-system/gap/files/8078399/missing-files.txt)

Version: 4.11.1
FreeBSD 13

**Comment by fingolfin** [comment]
There is no "install target", at least none that has official support (we briefly had one, which printed out a big warning that it is incomplete but people ignored it...)

Some additional reading:

- https://github.com/gap-system/gap/blob/master/README.buildsys.md#open-tasks
- #197
- #4746 
- #4731
