### ISSUE TITLE
Anything changed recently with weak pointers?

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#4781]
I got (in 4.dev) an error message

```
Error, Panic: basic object of type '<null>' is unkind in
  a <> fail at /Users/ahulpke/gap4/lib/pcgsperm.gi:1324 called from
CreateIsomorphicPcGroup( pcgs, false, false
 ) at /Users/ahulpke/gap4/lib/pcgsperm.gi:1370 called from
```

where a was obtained as weak pointer object (ought to be a family, but now is `fail`). Did anything in this context recently change?
(If not, I'll see to make a reproducable error report from it)

**Comment by fingolfin** [comment]
Nothing changed there recently (as in: during the past couple years)

**Comment by hulpke** [comment]
Thanks. I'll dig further.
