### ISSUE TITLE
`IsFpGroup(FreeGroup(infinity))` should be `false`

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#4793]
In the current GAP master branch:

### Observed behaviour
```
gap> IsFpGroup(FreeGroup(infinity));
true
```
### Expected behaviour
```
gap> IsFpGroup(FreeGroup(infinity));
false
```
since a free group of infinite rank is not finitely generated, and therefore not finitely presented.

---
Note also that the following behaviour, although not mathematically weird, is inconsistent with the behaviour for free semigroups, as detailed in https://github.com/gap-system/gap/issues/4786#issuecomment-1049726750:
```
gap> IsFpGroup(FreeGroup(2));
true
gap> IsFpSemigroup(FreeSemigroup(2));
false
```

**Comment by hulpke** [comment]
Basically `IsFpGroup` is a category ``generators and relations`` and free groups are made a subcategory so some basic calculations for them work with just the standard coset table/quotient methods.

Yes, the infinitely generated free group (which is basically there to make it easy to add further generators if needed) is not finitely presented, but that is basically just formalistic.

What one could do is:
- Rename `FpGroup` to `GeneratorsAndRelationsGroup`, and replace it everywhere in the library -- note that there aare derived names used for subgroups and homomorphisms.
- Re-add `IsFpGroup` as property
I feel this is overkill to just satisfy a formality amnd would rather change the definition of `IsFpGroup`.

**Comment by wilfwilson** [comment]
I wouldn't mind the documentation be changed in the appropriate places to note that `FreeGroup(infinity)` is an exception, for convenience.
