### ISSUE TITLE
missing `PreImagesRepresentative` method?

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4806]
The following happens in GAP 4.11 as well as in the master branch.
```
gap> G:= SL(2,2);;
gap> hom:= GroupHomomorphismByFunction( G, G, x -> x );;
gap> PreImagesRepresentative( hom, G.1 );  
Error, no default method for s.p. general mapping at /.../lib/mapping.gi:... called from
<function "PreImagesRepresentative for s.p. general mapping, and element">( <arguments> )
 called from read-eval loop at *stdin*:3
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```
For permutation groups and PC groups, GAP uses the defining function (`x -> x`) for creating a group homomorphism by images, and then delegates the task to this mapping.
(This is done by setting the filter `IsPreimagesByAsGroupGeneralMappingByImages` during the construction of the homomorphism, for these kinds of groups.)
What is the reason to forbid this for other kinds of groups?

**Comment by hulpke** [comment]
The intention behind `IsPreimagesByAsGroupGeneralMappingByImages` was not to forbid for other groups, but to be careful not to push aside other methods.
If `IsPreimagesByAsGroupGeneralMappingByImages` is set, any pre-image is calculated through a shadow GroupHomomorphismByImages, created by mapping a generating set under the map.
It probably would make sense to also set it for GroupHomomorphismByFunction if no pre-image (or inverse) function is given. This would solve the issue you noted.

**Comment by ThomasBreuer** [comment]
Yes. I will prepare a pull request for this extension.
