### ISSUE TITLE
Add SHA256 function(s) to GAP itself?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4844]
For various purposes it would be useful if GAP had a built-in way to compute standard checksums. While the [crypting package](https://github.com/gap-packages/crypting) does provide this functionality, fact is that this package may not always be available, so it is problematic to rely on it.

So I propose that we add this to the GAP kernel -- e.g. by copying the `crypting` kernel sources. Then update crypting to use the built-in versions if available.

Thoughts? @ThomasBreuer? @ChrisJefferson?

**Comment by fingolfin** [comment]
Also the interface for `crypting` probably should get some extras. E.g. a variant that produces the SHA256 as a hexstring. Right now I use this as workaround:
```
HexSHA256String := str -> LowercaseString(Concatenation(List(SHA256String(str),HexStringInt)));
```

**Comment by ThomasBreuer** [comment]
This feature would be very useful, it would allow me to use these checksums for the data files from the Atlas of Group Representations (and for other files).
Concerning the interface on the GAP level:
As you wrote, it would be good to have functions that take a string, a stream, or a filename, and return a hex string.

**Comment by ThomasBreuer** [comment]
The above function computes the same results as Julia's `str -> bytes2hex(sha256(str))`, for all data files in the Atlas of Group representations.
