### ISSUE TITLE
Failure in conjugacy class computation for a permutation group

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#4866]
### Observed behaviour

    gap> G := Group((7,8)(10,11)(15,16)(20,21)(25,26)(30,31)(35,36)
    >            (40,41)(43,44)(47,48)(50,51)(54,55)(57,58),
    >            (9,11)(12,14)(15,17)(18,20)(21,23)(24,26)(27,29)
    >            (30,32)(33,35)(36,38),
    >            (9,39)(11,40)(13,42)(15,44)(17,45)(19,46)(21,47)(23,49)
    >            (25,51)(27,52)(29,53)(31,54)(33,56)(35,58)(37,59));;
    gap> ConjugacyClasses(G);
    Error, wrong classes at /user/GAP/gap-4.11.1/lib/clashom.gi:2523 called from
    ConjugacyClassesViaRadical( G ) at /user/GAP/gap-4.11.1/lib/clashom.gi:3087 called from
    <function "ConjugacyClasses perm group">( <arguments> )
     called from read-eval loop at *stdin*:7
    you can 'quit;' to quit to outer loop, or
    you can 'return;' to continue
    brk> Sum(List(ncl,Size));
    29030400
    brk> Size(G);
    58060800
    brk> last/last2;
    2

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.11.1 of 2021-03-02
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv7
 Configuration:  gmp 5.1.3, GASMAN
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.4, PrimGrp 3.4.1, SmallGrp 1.4.2, TransGrp 3.0
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by fingolfin** [comment]
@Stefan-Kohl thank you for the report!

@hulpke this still happens in GAP master. Indeed:
```
brk> Sum(ncl,Size); Size(G);
29030400
58060800
brk> DisplayCompositionSeries(G);
G (3 gens, size 58060800)
 | C2
S (8 gens, size 29030400)
 | C2
S (7 gens, size 14515200)
 | A6
S (3 gens, size 40320)
 | C2
S (9 gens, size 20160)
 | L3(2)
S (4 gens, size 120)
 | A5
S (1 gens, size 2)
 | C2
1 (0 gens, size 1)
```
So it seems that somehow the classes of an index 2 subgroup are computed.

**Comment by fingolfin** [comment]
This errors was present since GAP 4.7. It did work in 4.6, though (i.e., no error, and the result of `ConjugacyClassesViaRadical` summed up to the right size, too).
