### ISSUE TITLE
Get rid of the gap.sh (or at least make it unnecessary)

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#487]
Having a shell script wrapper around the actual GAP executable is a bit annoying at times, esp. when one wants to run gdb or lldb or some other debugger on GAP.

So, we should get rid of gap.sh, or at least make it unnecessary. The only (?) remaining reason for it is to tell GAP the location of its libary, by setting a `GAP_DIR` variable. There are at least two things we can do to achieve this (and we probably should do both):
1. Compile the GAP path into the GAP executable itself, and use that to set a default for the library search paths.
2. Use various techniques in the GAP executable to find out its own location; then look in that location to see if there is a library, and if yes, use that to set up a default library search path.

Yes, I am aware that there are no portable and perfect ways to achieve 2., but there are solutions that do this 90% or so, and that is good enough -- the other cases are either caught by 1 or, well by using `gap.sh` or providing a `-l PATH` option to the executable.

**Comment by stevelinton** [comment]
GAP could also look at an environment variable

**Comment by fingolfin** [comment]
Yup, indeed. And all of these can be combined.

**Comment by alex-konovalov** [comment]
Can this be closed (is #1951 tested sufficiently well?)

**Comment by fingolfin** [comment]
Indeed, this works sufficiently well now. We still have gap.sh, for backwards compatibility and convenience, but I frequently don't use it
