### ISSUE TITLE
Print behaviour in test files

### ISSUE THREAD

**Issue by FriedrichRober** [gap-system/gap#4876]
### Short version
Calling `Print` in a `.tst` file is missing the last line of the output.

### Observed behaviour
So suppose I have a test file `tstPrint.tst` with the following content:
```
# Print Test
gap> a := "Hello World! \nGoodbye World!";
"Hello World! \nGoodbye World!"
gap> Print(a);
Hello World! 
Goodbye World!
gap> Display(a);
Hello World! 
Goodbye World!
```

Executing the commands in a gap session works as expected.
But if run the test file via `gap -c 'Test("tstPrint.tst");'` I get the following error message:
```
########> Diff in tstPrint.tst:4    
# Input is:
Print(a);
# Expected output:
Hello World! 
Goodbye World!
# But found:
Hello World! 
              ########
```

For some reason it seems, that the test file misses the last line of the Print output. I am not sure if this is expected behaviour.

In one of my packages I generate test files from the documentation examples via AutoDoc, and the Print examples now of corse all fail, because the last line is missing when runnning the test files.

### Copy and paste GAP banner (to tell us about your setup)
```
Using branch:	master

 ┌───────┐   GAP 4.12.0-597-gd4f2222 built on 2022-04-21 11:20:14+0200
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin20.3.0-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN
 Loading the library and packages ...
 Packages:   AtlasRep 2.1.1, Browse 1.8.13, CTblLib 1.3.3, FactInt 1.6.3, FGA 1.4.0, Forms 1.2.7, GAPDoc 1.6.5, genss 1.6.6, IO 4.7.2, 
             LINS 0.2, orb 4.8.4, PrimGrp 3.4.1, recog 1.3.2dev, SmallGrp 1.4.2, SpinSym 1.5.2, TomLib 1.2.9, TransGrp 3.5
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by FriedrichRober** [comment]
I can fix the test files by adding a newline at the end of each Print statement, e.g. `Print(a, "\n");` but for my use case in the documentation, it looks a bit weird if I have to add a `\n` for every Print-Statement.

**Comment by hulpke** [comment]
I think the weird behavior is actually in the interactive use. The command prompt empties out the print buffer (the last line w/o the \n) before printing the prompt. The Print statement itself actually only produces the `Hello World` line, and leaves the second line in the print buffer, and that is what happens in the test file.

For uses in the manual, I think this shoudl simply become an untested example -- testing it is not needed for stability of the system.

**Comment by FriedrichRober** [comment]
Ok, I see. Yes, the testing of the manual examples was only for figuring out if the output formatting is up to date, not for the stability of the system. Thanks for explaining!
