### ISSUE TITLE
emacs: used to contain GAP integration for emacs

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-system/gap#4888]
[Here](https://github.com/gap-system/gap/tree/master/etc#files-for-all-gap-users) gives the following description:

> emacs: used to contain GAP integration for emacs

But there is no file or directory named as `emacs` at all.

**Comment by james-d-mitchell** [comment]
If I remember correctly this file had to be removed from the package archive for legal reasons, I don't remember any more details than this, but I'm pretty sure that @fingolfin and @ChrisJefferson will remember this too!

**Comment by ChrisJefferson** [comment]
Yes, 'used' here means the file was here previously but was removed (it's a little confusingly worded).

From my memory, we received an email from the Free Software Foundation's Compliance Lab asking us to delete the files, or switch them to the GPL v3. The easiest route was to delete them (as changing license would have required contacting everyone who had ever worked on the file).

**Comment by hulpke** [comment]
and not just "asking" but threatening legal action if we did not comply.

**Comment by alex-konovalov** [comment]
Can we now delete this misleading line, since there is no `emacs` directory?

**Comment by hongyi-zhao** [comment]
Some related discussions can be seen [here](https://github.com/gap-system/gap/issues/4890).
