### ISSUE TITLE
About the vim-utils included in this repository.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-system/gap#4890]
I noticed the [vim-utils](https://github.com/gap-system/gap/tree/master/etc/vim) plugin provided in this repository. But I've some questions about it:

- This plugin has not been updated for many years. Does it still work well in the latest version of vim?
- It seems that this plugin only has the syntax highlight feature, I wonder if it can let the user run the gap script or code fragment directly from within vim.

I tried some other alternatives based on the described [here](https://www.gap-system.org/Faq/faq.html#8.1), and it seems that `vscode` is the right way to go. [The gap plugin](https://marketplace.visualstudio.com/items?itemName=feisele86.gap-language-support) is located [here](https://github.com/feisele/vscode-gap-language-support), and can be used out of the box.
 
N.B.: In order to activate the corresponding plugins automatically, the GAP script file must have the extension name `g`: 

![image](https://user-images.githubusercontent.com/11155854/166134816-9f6b02fa-5551-4b1b-99aa-6bc058682e68.png)

![image](https://user-images.githubusercontent.com/11155854/166135042-89c38c24-c598-47a7-bd2b-90786731c911.png)

Regards,
HZ

**Comment by hulpke** [comment]
I use the plugin for syntax highlighting and it seems to work very well. No need for updates.

Any why on earth would one want to run GAP from the editor? That almost looks like a solution in search of a problem.

**Comment by hongyi-zhao** [comment]
> Any why on earth would one want to run GAP from the editor?

For verify, test, debug, and rapid development of GAP script/program.

**Comment by fingolfin** [comment]
The directory `etc/vim` has a README and all files in it are commented. I think you can answer your question yourself by looking there.
