### ISSUE TITLE
quotient groups problems

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4897]
It seems to be allowed to form a factor group of a subgroup of a free group ...
```
gap> f:= FreeGroup( 2 );;
gap> s:= Subgroup( f, [ f.1^2 ]);;
gap> q:= s / [ s.1^5 ];
<fp group on the generators [ f1^2 ]>
```
... but this factor does not behave well.
```
gap> Size( q );
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `*' on 2 arguments
The 2nd argument is 'fail' which might point to an earlier problem
[...]
```
Trying to form a quotient of a subgroup of a f.p. group immediately yields an error because `/` is defined for `IsFpGroup` but not for `IsSubgroupFpGroup`.

Should perhaps also the construction of a factor group of a subgroup of a free group be forbidden?
And if yes, what would be the criterion for the decision whether a group is a full free group?
Do we expect that the group is identical to the value of the `!.freeGroup` component of the elements family, or is it enough if the generators of the full free group are among the generators?
`IsWholeFamily` gives the right answer, but this is a property, and it can in general not be computed if it is not set a priori.

**Comment by fingolfin** [comment]
@hulpke any thoughts on this issue?

My personal view is that it suffices (for now, at least) to support this for groups in `IsWholeFamily`, and print a helpful error in other cases -- this is far better than returning broken or incorrect results. Of course it'd be kinda nice if we could support *more*, but this is a pure bonus, isn't it?

**Comment by hulpke** [comment]
What goes wrong here is I think that the quotient method does not catch that it is only applicable to  the whole group. This is probably triggered by an implication that subgroups of free groups are free.

One could add a special method for subgroups of free groups, but it would only help solving this particular kind of example, I don't find this interesting.

If finite index, it would be comparatively easy to rewrite (ie. `IsomorphismFpGroup`) into subgroup generators, and then make the quotient a proper fp group, if someone wants to add such a method.

**Comment by ThomasBreuer** [comment]
I agree with @fingolfin that it is an acceptable workaround to restrict the installation of the "for free groups and relators" method of `\/` to the case that the first argument is in `IsFreeGroup and IsWholeFamily`; this prevents GAP from creating the corrupted group object.
An additional method with requirement `IsFreeGroup` can then just show an error message saying that currently there is no method for the situation that the free group does not know whether it contains all generators of its parent group.
(And if somebody wants to support quotients of proper subgroups of full free groups then this method will be the right place for improvements.)

I am going to make a pull request for this change.
