### ISSUE TITLE
The incorrect displayed symbols in GAP online reference manual 39.7-6 CosetDecomposition.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-system/gap#4898]
I noticed the following incorrect displayed symbol [here](https://www.gap-system.org/Manuals/doc/ref/chap39.html#X82F6ABE378B928D1):

![image](https://user-images.githubusercontent.com/11155854/174422422-d5614308-4528-4850-a31c-9d8265b68bf1.png)

It's obvious that the correct form should be **$S \le G$**.

Regards,
HZ

**Comment by fingolfin** [comment]
Go to the top of the page and click "Mathjax on", and you'll get to https://www.gap-system.org/Manuals/doc/ref/chap39_mj.html#X82F6ABE378B928D1 which should have all math formulas rendered nicely.

We probably should link to the mathjax version by default.

however, normally GAPDoc should (I think?!) convert such simple math formulas to Unicode even in the non-MathJax version, so perhaps more is going on? @frankluebeck will know.
