### ISSUE TITLE
problem with `MTX.InvariantQuadraticForm`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#4936]
The following happens in the current master branch as well as in GAP 4.11.1.

```
gap> F:= GF(7);;
gap> mats:= [
>   [ [ 0, 1, 0, 0, 0, 0 ], 
>     [ 1, 0, 0, 0, 0, 0 ], 
>     [ 0, 0, 0, 1, 0, 0 ],
>     [ 0, 0, 1, 0, 0, 0 ], 
>     [ 5, 5, 2, 2, 6, 0 ], 
>     [ 3, 3, 4, 4, 0, 6 ] ],
>   [ [ 4, 0, 0, 0, 0, 0 ], 
>     [ 0, 0, 1, 0, 0, 0 ], 
>     [ 0, 6, 1, 0, 0, 0 ],
>     [ 0, 0, 0, 0, 1, 0 ], 
>     [ 0, 0, 0, 0, 0, 1 ], 
>     [ 6, 0, 0, 2, 4, 3 ] ] ] * One( F );;
gap> StructureDescription( Group( mats ) );
"PSU(3,3)"
gap> m:= GModuleByMats( mats, F );;
gap> MTX.IsAbsolutelyIrreducible( m );
true
gap> Q:= MTX.InvariantQuadraticForm( m );;
gap> Display( Q );
 . . . 6 5 3
 . . 6 . . .
 . 1 . . . .
 1 . . . 5 3
 2 . . 2 . 5
 4 . . 4 2 .
gap> Q = - TransposedMat( Q );
true
```
The matrix group in question does not fix a nonzero quadratic form.
The GAP manual says the following
```
  69.11-3 MTX.InvariantQuadraticForm
  
  ‣ MTX.InvariantQuadraticForm( module ) ──────────────────────────── function
  
  returns  an  invariant  quadratic  form  of  module, or fail if no such form
  exists.  If  the characteristic of the field over which module is defined is
  not  2,  then  the  invariant  bilinear form (if any) divided by two will be
  returned. In characteristic 2, the form returned will be lower triangular.
```
This is consistent with the above output, since the invariant bilinear form is antisymmetric.
Moreover, the documentation does not claim that the returned forms are nondegenerate.
On the other hand, it says that `fail` is returned if no invariant quadratic form exists.
Thus I would prefer if `MTX.InvariantQuadraticForm` would return `fail` in this example,
and that its documentation is made precise.

What shall we do?

**Comment by hulpke** [comment]
I think this is code that got translated from the original Smash Meataxe, and I don't think it is used anywhere.

**Comment by frankluebeck** [comment]
I have used this function interactively from time to time. 
We probably want to know a non-degenerate quadratic form when calling this function. Otherwise we could simplify the code and always return the zero matrix. 
I have not studied the code. Does the function maybe always return an invariant quadratic form of maximal possible rank? 
In that case the functionality could remain and the documentation made more precise.

**Comment by ThomasBreuer** [comment]
@frankluebeck Since the argument of `MTX.InvariantQuadraticForm` must be absolutely irreducible (this should of course be stated in the documentation ...), there is either a nondegenerate invariant quadratic form or just the zero form.
As I wrote, one can interpret the current behaviour as correct, according to the documentation, just the statement about `fail` being returned if no such form exists is irritating.

If we decide to change just the documentation then the new documentation could look as follows.
- The argument `M` must be absolutely irreducible.
- `fail` is returned if `MTX.InvariantBilinearForm( M )` returns `fail`.
- In odd characteristic, the matrix `B` returned by `MTX.InvariantBilinearForm( M )` is just divided by 2 (which yields a nondegenerate invariant quadratic form if `B` is symmetric, and yields the zero form but not the zero matrix if `B` is antisymmetric).
- In characteristic 2, the matrix `B` is used to compute either a lower triangular matrix of a nondegenerate invariant quadratic form, or `fail` if there is no such form.

**Comment by fingolfin** [comment]
Is there anything left to do now that PR #4960 has been merged, and if so: what?

**Comment by ThomasBreuer** [comment]
If we decide that the changes in the documentation (and the fix of `MTX.OrthogonalSign`) from #4960 are sufficient then this issue can be closed. @frankluebeck, what do you think?

**Comment by frankluebeck** [comment]
I agree that the mentioned PR is a sufficient solution to this issue.
