### ISSUE TITLE
No way to turn off information printout in MinimumWeight (guava package)

### ISSUE THREAD

**Issue by qodesign** [gap-system/gap#4954]
Usually packages provide a way to turn off printing of information  for eample using SetInfoLevel . 
The guava package has a function "MinimumWeight" where there's no way to do that.
(Note the function works; just the extra information being printed is not needed; it clutters the screen and slows things down)

### Observed behaviour
code:=BestKnownLinearCode(7,4,GF(2));;
mat:=GeneratorMat(code);;
dmin:=MinimumWeight(GeneratorMatCode(mat,"",GF(2)));;

[ "--out", "C:/WINDOWS/Temp/gaptempfile.27oHNm", "--mod", 2, "C:/WINDOWS/Temp/gaptempfile.qIzGoV" ]
[7,4] linear code over GF(2) - minimum weight evaluation
Known lower-bound: 1
There are 2 generator matrices, ranks : 4 3
The weight of the minimum weight codeword satisfies 1 mod 2 congruence
Enumerating codewords with information weight 1 (w=1)
    Found new minimum weight 3
Number of matrices required for codeword enumeration 2
Completed w= 1, 8 codewords enumerated, lower-bound 3, upper-bound 3

### Expected behaviour
code:=BestKnownLinearCode(7,4,GF(2));;
mat:=GeneratorMat(code);;
dmin:=MinimumWeight(GeneratorMatCode(mat,"",GF(2)));;
(nothing printed out)

### Copy and paste GAP banner (to tell us about your setup)

 ┌───────┐   GAP 4.11.0 of 29-Feb-2020
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-cygwin-default64-kv7
 Configuration:  gmp 6.1.2, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.1.2, AtlasRep 2.1.0, AutoDoc 2019.09.04, AutPGrp 1.10.2, Browse 1.8.8,
             CaratInterface 2.3.3, CRISP 1.4.5, Cryst 4.1.23, CrystCat 1.1.9, CTblLib 1.2.2, FactInt 1.6.3, FGA 1.4.0,
             Forms 1.2.5, GAPDoc 1.6.3, genss 1.6.6, IO 4.7.0, IRREDSOL 1.4, LAGUNA 3.9.3, orb 4.8.3, Polenta 1.3.9,
             Polycyclic 2.15.1, PrimGrp 3.4.0, RadiRoot 2.8, recog 1.3.2, ResClasses 4.7.2, SmallGrp 1.4.1,
             Sophus 1.24, SpinSym 1.5.2, TomLib 1.2.9, TransGrp 2.0.5, utils 0.69
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'

**Comment by fingolfin** [comment]
Not much we can do about this. You'll have to report this to the Guava package authors/maintainers to get a change there. Try e.g. reporting at https://github.com/gap-packages/guava/issues or use the email addresses reported by the Guava package banner. (OK, I just tried that one, and it doesn't mention any contact data, which is bad; I'll report *that*).

**Comment by fingolfin** [comment]
See https://github.com/gap-packages/guava/issues/73
