### ISSUE TITLE
Disable by default (and eventually get rid) of "compatibility mode" in our build system

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#4996]
Our build system has a "compatibility mode" which is on by default, and exists to help packages with kernel extensions that expects certain things to be arranged exactly as they were in older GAP versions (before the new build system in 4.9).

I'd like to switch the default to "off" and at some point remove this mode. But that requires active testing for it and probably adjustments to a few packages. And possibly also to the GAP build system -- it may be that a few things that I back then only enabled in "compatibility mode" because I thought we don't need it anymore actually should be retained.

I plan to work on this, but I wouldn't mind help, so if anyone is interested... :-)

**Comment by ChrisJefferson** [comment]
How does one switch it off? I can check if anything terrible happens on windows

**Comment by fingolfin** [comment]
There is a configure switch, ask `./configure --help`. As it is, I am not even sure it works at all; and it may already break stuff on Linux

**Comment by fingolfin** [comment]
Some things compat mode creates:
1. `bin/gap.sh`
   - this still used by a ~13 packages, and also by GAP itself. 
2. symlink `sysinfo.gap-default64` -> `sysinfo.gap`
3. a bunch of symlinks in `bin/$GAPARCH`:
   - `config.h` -> ../../build/config.h`
   - `gac` -> ../../gac`
   - `gap` -> ../../gap`
   - `src` -> ${srcdir}/src

Since a lot uses `bin/gap.sh`, I'd leave it in for now. But the other kinks are prime candidates for removal. I've done this now in PR #5101

**Comment by fingolfin** [comment]
Packages which still seem to be using `gap.sh` unconditionally:
- [ ] `anupq` (in docs and internal helper scripts)
- [ ] `digraphs` (in the `doc` target of `Makefile.am` -- but a new build system with this fixed is already merged)
- [ ] `float` (in the `doc` target of `Makefile.am`)
- [ ] `jupyterkernel` (mentions it in `README.md`)
- [ ] `semigroups` (in the `doc` target of `Makefile.am`)
- [ ] `unipot` (mentions it in `README.md`, install instructions)
- [ ] `zeromqinterface` (in the `zgap` script, which [has been broken for a long time](https://github.com/gap-packages/ZeroMQInterface/issues/6) anyway)

So we are looking pretty good in this regard.
