### ISSUE TITLE
windows release notes suggested text

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#5002]
Wasn't positive where to put this (sorry). Comments / edits welcome. Text about the windows installer

The windows installer for GAP has been completely rewritten. There are many changes and minor fixes, the most significant are:

* GAP can be installed globally into "Program Files".
* GAP can also be installed without admin access into the user's home directory.
* Almost all packages work, including those with kernel modules and external programs.
* The default directory for saving is the user's "Documents" folder.
* There is no longer possible to choose which packages are installed.
* Windows versions before 8 are no longer supported.

If you experience any issues please report them at thttps://www.github.com/gap-system/gap/issues

**Comment by fingolfin** [comment]
Thank you

**Comment by fingolfin** [comment]
Integrated into PR #5005
