### ISSUE TITLE
[AtlasRep] Errors if AtlasRep cannot download files

### ISSUE THREAD

**Issue by zickgraf** [gap-system/gap#5015]
*Reporting here because I cannot find a bugtracker for AtlasRep:*

In line 3159 of `access.gi` in AtlasRep there is a check `body = fail`. This check should be `body = false` because AtlasOfGroupRepresentationsTransferFile returns `false` when an error is encountered. The current code leads to errors when there are issues with the network connection.

Version of AtlasRep: 2.1.4

**Comment by fingolfin** [comment]
In general I would recommend checking the README of a package to find out how to contact the author(s) for big reports. In this case: ping @ThomasBreuer

**Comment by ThomasBreuer** [comment]
@zickgraf tanks for your report. I will have to make a new release of the package.

**Comment by ThomasBreuer** [comment]
@zickgraf I have released version 2.1.5 of AtlasRep.

**Comment by zickgraf** [comment]
Thanks, I can confirm that the issue does not occur anymore with 2.1.5!
