### ISSUE TITLE
GAP 4.12.0: package test of `polycyclic` runs into infinite loop

### ISSUE THREAD

**Issue by frankluebeck** [gap-system/gap#5018]
### Observed behaviour
In GAP 4.12.0 the test `pkg/polycyclic/tst/bugfix.tst` hangs at line 38. The problem is that for 
 ```
g := PcGroupToPcpGroup(SmallGroup(48,1));
```
The commands
```
Centre(g); # or
FittingSubgroup(g);
```
do not return an answer. 

I'm not sure if this is a problem of the GAP library or of the `polycylic` package.

### Expected behaviour
The mentioned command should return their result almost instantly.

**Comment by stertooy** [comment]
See https://github.com/gap-packages/polycyclic/issues/46 - I think has been (mostly?) fixed, but `polycyclic` hasn't had a release that includes the fix(es).

**Comment by fingolfin** [comment]
Yes, this is known, and hence the PackageDistribution currently skips the polycyclic tests. It's being tracked in the polycyclic repository and will be fixed by the next release.
