### ISSUE TITLE
problem with "nice monomorphisms"

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5020]
(The following holds for released GAP versions as well as for the master branch.)

The problem mentioned in the first comment of oscar-system/Oscar.jl/pull/1520 is essentially the following.

We start with a matrix group.
```
gap> G:= Group( [ [ [ 0, 1 ], [ 1, 0 ] ] ] );;
gap> IsHandledByNiceMonomorphism( G );
true
```
Apparently it would be good for this group to store a nice monomorphism. We know such a monomorphism, so we try to help GAP by setting it.
```
gap> vecs:= Orbit( G, [ 1, 0 ], OnRight );
[ [ 1, 0 ], [ 0, 1 ] ]
gap> acthom:= ActionHomomorphism( G, vecs, OnRight );
<action homomorphism>
gap> SetNiceMonomorphism( G, acthom );
```
Now the following happens.
```
gap> Kernel( acthom );
Error, recursion depth trap (5000) in
  IsEvenInt( Length( attr ) ) at /.../gap/lib/grp.gi:4596 called from
...
```
The reason for this problem is that the `Kernel` method (more precisely, the `KernelOfMultiplicativeGeneralMapping` method) for the action homomorphism `acthom` wants to delegate to a `GroupHomomorphismByImagesNC` object `hom`, say, which is created from the given data, and that the source of `hom` is a group that knows the `NiceMonomorphism` object `acthom`.

In this situation, `GroupHomomorphismByImagesNC` creates `hom` as a composition mapping of `acthom` with another mapping. But then calling `Kernel` with `hom` will first try to compute the kernel of `acthom`, which yields the infinite recursion.

Setting nice monomorphisms by hand is apparently not safe. What would be needed to avoid this kind of error?

If one sets the `IsInjective` flag for `acthom` in the above example before calling `Kernel` then the error disappears. Is this the only requirement for safely setting nice monomorphisms?

And if yes, would it be a solution (and not only a workaround) to extend the dedicated `SetNiceMonomorphism` method in `lib/grpnice.gi` by an `IsInjective` check? Note that the automatically produced `NiceMonomorphism` objects get this flag during their construction, thus the additional check would be cheap for them.

**Comment by fingolfin** [comment]
Adding an `IsInjective` check to `SetNiceMonomorphism` sounds potentially expensive or possibly impossible? Could we instead require `HasIsInjective(hom) and IsInjective(hom)`, and if that fails, produce an error? Then the caller is neatly informed that they must provide a "certified" monomorphism.

**Comment by fingolfin** [comment]
Ping @hulpke

**Comment by ThomasBreuer** [comment]
@fingolfin Yes, this would be a good alternative.
Besides that, if we decide that setting a nice monomorphism by hand is "allowed" if the map is injective (and knows this) then this fact should be mentioned in the manual section "Nice Monomorphisms".

**Comment by fingolfin** [comment]
Sure, it should be documented (though I am pretty sure this is not an intentional design choice, but rather an emerging effect caused by implicit assumptions made in the code :-). Anyway, seems perfectly safe to me to change it like that

**Comment by ThomasBreuer** [comment]
O.k., I will create a pull request.

**Comment by ThomasBreuer** [comment]
Since #5029 has been merged, the problem is solved.
