### ISSUE TITLE
MatrixObj 8BitMatrixRep is used when it should not be

### ISSUE THREAD

**Issue by wucas** [gap-system/gap#5055]
Using the new StandardFF package by @frankluebeck one can create a matrix over a finite field created with that package. E.g. via
```
gap> ff := FF(3,2);
gap> ZeroMatrix(ff,2,2);
```
When this is done GAP tries to find the right representation for the matrix and then calls `NewZeroMatrix` with the respective filter. For this `DefaultMatrixRepForBaseDomain` is used (defined in `matobj.gi` lines 158-171). This function assumes, however, that the only finite field elements one could encounter are the one in the GAPlib. This function tests the Domain with `IsFinite`, `IsField` and checks that the field is smaller than 256. 
A finite field created with StandardFF passes these tests (and it should) so we need to use another test there to actually test whether it is a small finite field in the kernels internal representation. The only filter I could find now that correctly discriminates between `GF(3^2)` and `FFE(3,2)` is `IsFFECollection` but that does not seem like the correct solution either.

**Comment by ThomasBreuer** [comment]
The point seems to be what `IsFFE` means. Currently the FFEs in `IsInternalRep` are in this filter, but also the `IsZmodpZObj`s (constructed for example with `Z(NextPrimeInt(2^64))`).
If we agree (and document) that any other implementation of finite field elements is not in `IsFFE` then checking for `IsFFECollection` in `DefaultMatrixRepForBaseDomain` is fine.
