### ISSUE TITLE
Incorrect output for ImaginaryPart(x) with quaternions

### ISSUE THREAD

**Issue by BNasmith** [gap-system/gap#5060]
The quaternion "ImaginaryPart" command gives incorrect outputs.

### Observed behaviour

```
gap> H := QuaternionAlgebra(Rationals);
<algebra-with-one of dimension 4 over Rationals>
gap> List(Basis(H), x -> [ImaginaryPart(x),x]);
[ [ 0*e, e ], [ e, i ], [ k, j ], [ (-1)*j, k ] ]
```

### Expected behaviour

```
gap> H := QuaternionAlgebra(Rationals);
<algebra-with-one of dimension 4 over Rationals>
gap> List(Basis(H), x -> [ImaginaryPart(x),x]);
[ [ 0*e, e ], [ -(1)*i, i ], [ -(1)*j, j ], [ (-1)*k, k ] ]
```

### Copy and paste GAP banner (to tell us about your setup)

```
 ┌───────┐   GAP 4.12.0 of 2022-08-18
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv8
 Configuration:  gmp 6.2.0, GASMAN, readline
 Loaded workspace: /home/bnasmith/default
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.4, AutoDoc 2022.07.10, AutPGrp 1.11,
             Browse 1.8.14, CaratInterface 2.3.4, CRISP 1.4.5, Cryst 4.1.25,
             CrystCat 1.1.10, CTblLib 1.3.4, FactInt 1.6.3, FGA 1.4.0, Forms 1.2.8,
             GAPDoc 1.6.6, genss 1.6.7, IO 4.7.2, IRREDSOL 1.4.3, LAGUNA 3.9.5, orb 4.8.5,
             Polenta 1.3.10, Polycyclic 2.16, PrimGrp 3.4.2, RadiRoot 2.9, recog 1.3.2,
             ResClasses 4.7.3, SmallGrp 1.5, Sophus 1.27, SpinSym 1.5.2, TomLib 1.2.9,
             TransGrp 3.6.3, utils 0.76
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by fingolfin** [comment]
I don't see why `ImaginaryPart(i)` should be `-i`.

Are you perhaps confusing `ImaginaryPart` with `ComplexConjugate`?
```
gap> List(Basis(H), x -> [ComplexConjugate(x),x]);
[ [ e, e ], [ (-1)*i, i ], [ (-1)*j, j ], [ (-1)*k, k ] ]
```

The documentation says this:
> When ComplexConjugate is defined for an object `z` then `RealPart` and `ImaginaryPart` return
  `(z + ComplexConjugate( z )) / 2` and `(z - ComplexConjugate( z )) / 2 i`, respectively,
  where `i` denotes the corresponding imaginary unit.

And that seems consistent with the actual behavior.


(That said, I'd also expect a different definition, say `ImaginaryPart(z) := z - RealPart(z)`, but changing the long-time standing definition of a function just like that is highly problematic...)

**Comment by BNasmith** [comment]
My mistake with the expected behaviour, this is what I should have written:

### Expected behaviour
```
gap> H := QuaternionAlgebra(Rationals);
<algebra-with-one of dimension 4 over Rationals>
gap> List(Basis(H), x -> [ImaginaryPart(x),x]);
[ [ 0*e, e ], [ i, i ], [ j, j ], [ k, k ] ]
```

It seems that the division by `2i` in the definition above yields a result that I wouldn't expect when working with quaternions. The goal would be that `x = RealPart(x) + ImaginaryPart(x)` for quaternions.

**Comment by fingolfin** [comment]
Yes, I can see why you'd wish for that; but that's simply not how the function is defined.

So, I am afraid it works as intended, no bug here. You can easily write your owner helper function to achieve the effect you desire, though.

**Comment by BNasmith** [comment]
Much appreciated. Thanks for taking a look.
