### ISSUE TITLE
Including gap headers fails if a garbage collector is not specified

### ISSUE THREAD

**Issue by antonio-rojas** [gap-system/gap#5075]
### Observed behaviour
Try to compile the following file `testgap.c' 
```
#include <gap/objects.h>
```
with `gcc testgap.c`:
```
$ gcc testgap.c
In file included from /usr/include/gap/objects.h:20,
                 from testgap.c:1:
/usr/include/gap/gasman.h:401:2: error: #error unknown garbage collector
  401 | #error unknown garbage collector
      |  ^~~~~
```

### Expected behaviour

File compiles without needing to specify a garbage collector

### Copy and paste GAP banner (to tell us about your setup)
```
┌───────┐   GAP 4.12.0 of 2022-08-18
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN, readline
```

**Comment by fingolfin** [comment]
thanks, will fix this for 4.12.1 (hopefully to be released in about 2-3 weeks

**Comment by fingolfin** [comment]
See PR #5077

**Comment by antonio-rojas** [comment]
Thanks, can confirm sagemath builds fine after this even if no gc is specified
