### ISSUE TITLE
4.12.0: Build breaks: gen/config.h: No such file or directory

### ISSUE THREAD

**Issue by yurivict** [gap-system/gap#5084]
### Observed behavior
Build fails:
```
install: /disk-samsung/freebsd-ports/math/gap/work/gap-4.12.0/gen/config.h: No such file or directory
*** Error code 71
```

```
$ find . -name config.h
./work/gap-4.12.0/pkg/guava/src/ctjhai/config.h
./work/gap-4.12.0/build/config.h
./work/gap-4.12.0/bin/amd64/config.h
```

### Expected behavior
no such error

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.12.0 of 2022-08-18
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: amd64
 Configuration:  gmp 6.2.1, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.4, AutoDoc 2022.07.10, AutPGrp 1.11, CRISP 1.4.5, Cryst 4.1.25, CrystCat 1.1.10, CTblLib 1.3.4, FactInt 1.6.3, FGA 1.4.0, GAPDoc 1.6.6, 
             IRREDSOL 1.4.3, LAGUNA 3.9.5, Polenta 1.3.10, Polycyclic 2.16, PrimGrp 3.4.2, RadiRoot 2.9, ResClasses 4.7.3, SmallGrp 1.5, Sophus 1.27, SpinSym 1.5.2, TomLib 1.2.9, 
             TransGrp 3.6.3, utils 0.76
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

FreeBSD 13.1 STABLE

**Comment by ChrisJefferson** [comment]
Can you give a bit more context to where the build fails? Also note that build install isn't actually that useful, as it doesn't deal with installing GAP packages, so while it is in active development, if you just want a working GAP I wouldn't use it, and just run GAP from the directory where it was built.

**Comment by fingolfin** [comment]
@ChrisJefferson when you wrote "build install" did you mean `make install`? Otherwise I am not sure how to interpret what you meant.

Also, I think @yurivict is actually packaging GAP for FreeBSD (thanks for that!!!) and so is actually one of the people for whom I wrote `make install`. Of course it still does have shortcomings, but I am greatly interested in learning about them to be able to fix them! That said, I am not even sure they are using `make install`...

... because `make install` does not install `config.h`. On purpose -- GAP's `config.h` does not need to be installed in GAP 4.12.0, and indeed should not be installed.

@yurivict as @ChrisJefferson wrote we need more context to say anything. In particular: what command did you run that triggered that error? Ideally show the full input and full output?

**Comment by yurivict** [comment]
Yes, I maintain  the gap port on FreeBSD.
There are 18 systems that have gap packages: https://repology.org/project/gap/versions
Building manually and using it from the build directory (like it was suggested above) isn't an option for modern users.

I got the error from subject while trying to update the port to 4.12.0
I solved this problem by creating a symlink before build to one of the available config.h files.

**Comment by fingolfin** [comment]
> I got the error from subject while trying to update the port to 4.12.0 

I don't understand this sentence. What is "subject" in this context.

> I solved this problem by creating a symlink before build to one of the available config.h files.

That's definitely wrong.

Can't say what is right though as we still don't have enough information from you as to what you did precisely...

**Comment by fingolfin** [comment]
Once more: please send us the *full* output. We need the extra information in it to debug this.

**Comment by yurivict** [comment]
Here is a complete log: [gap-build.log](https://github.com/gap-system/gap/files/9728109/gap-build.log)

**Comment by fingolfin** [comment]
Thanks for the log file. Here's the relevant excerpt:
```
/usr/bin/install -c -d -m 0755 /disk-samsung/freebsd-ports/math/gap/work/stage/usr/local/lib
/bin/sh ./libtool --silent --mode=install /usr/bin/install -c -s libgap.la /disk-samsung/freebsd-ports/math/gap/work/stage/usr/local/lib
libtool: warning: remember to run 'libtool --finish /usr/local/lib'
gmake[2]: Leaving directory '/disk-samsung/freebsd-ports/math/gap/work/gap-4.12.0'
install  -m 0644 /disk-samsung/freebsd-ports/math/gap/work/gap-4.12.0/gen/config.h /disk-samsung/freebsd-ports/math/gap/work/stage/usr/local/include/gap
install: /disk-samsung/freebsd-ports/math/gap/work/gap-4.12.0/gen/config.h: No such file or directory
*** Error code 71
```
There is no `gen` directory in GAP 4.12. The offending line does *not* come from our `make install`. 

Looking at https://github.com/DragonFlyBSD/DPorts/blob/master/math/gap/Makefile I suspect it comes from your `postinstall` target, which at least in that version (which of course may differ from what you are working on right now) starts like this:
```
post-install:
	# additional header
	${INSTALL_DATA} ${WRKSRC}/gen/config.h ${STAGEDIR}${PREFIX}/include/gap
...
```
And yeah, that's wrong, you need to delete it. Also a ton of other steps in there are now obsolete.

**Comment by fingolfin** [comment]
@yurivict I am glad you could resolve it! Please do not hesitate to contact us again if there are more trouble! It can be really difficult to discern what is an expected change and what a bug; talking with us may be the most efficient way to figure it out.

And thanks for maintaining this port!
