### ISSUE TITLE
`InfoWarning` misused for advertisements

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5097]
When GAP gets started with the options `-A` and `-b`, the following happens when one loads the sonata package.
```
gap> LoadPackage( "sonata" );;
#I  You may wish to install the xgap package
#I  and enjoy the graphic capabilities of SONATA.
```
This advertisement is shown via `Info` calls with `InfoWarning` level at least `1` (the default). 
I think that printing these lines is not a good idea, at least if one has already switched off package banners.

**Comment by fingolfin** [comment]
Resolved in SONATA 2.9.5
