### ISSUE TITLE
Regressions caused by `libgap.pc` PR

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5113]
Unfortunately PR #5080 by @dimpase (UPDATE: together with PR #5106 by me -- which also had a bug completely of its own) introduced a few regressions:
1. weirdly, the `makemanuals ...` CI test is now failing
2. every time one enters `make` now, even if nothing else is to be done, one now gets this message:
```
$ make
Package libgap was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgap.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libgap' found
```

I am guessing problem 2 is because the `(shell PKG_CONFIG_PATH=$(DESTDIR)$(libdir)/pkgconfig pkg-config --modversion libgap)` is always executed. I think to fix this one needs to replace the `ifeq` by a shell `if`.

No idea right now what causes 1, but it might in fact be related

**Comment by fingolfin** [comment]
Aha, I think I see what went wrong with 1. I'll submit a PR to deal with both

**Comment by dimpase** [comment]
mea cupla...

**Comment by fingolfin** [comment]
Nah, no worries. Tests didn't catch it, and >60% of the problem were my fault anyway :-/
