### ISSUE TITLE
PermList with non-integer arguments

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#513]
This was reported earlier by @laurentbartholdi:

According to the documentation, `PermList` should raise an error if it is called with non-integer arguments, and return fail if its argument is an integer list that doesn't define a permutation.

However,

```
gap> PermList([rec()]);
fail
gap> PermList([[]]);
fail
```

etc. so at minimum the documentation is wrong. I think it makes sense to raise an error.

**Comment by stevelinton** [comment]
Looking at the code, it used to raise errors and someone deliberately changed it to return Fail -- the old code is commented out (src/permutat.c around line 2565). Given this I am inclined to fix the documentation.

**Comment by alex-konovalov** [comment]
@stevelinton thanks - and indeed it is commented out since GAP 4.5.0 release, so this behaviour is present since 2012. I think it's fine to fix the documentation to just remove "integer" from "if its argument is an integer list that doesn't define a permutation."
