### ISSUE TITLE
Cyclotomics (and probably others) missing a Representative

### ISSUE THREAD

**Issue by nthiery** [gap-system/gap#517]
Cyclotomics is missing a representative until either Zero or One is
computed:

     ┌───────┐   GAP, Version 4.7.9 of 29-Nov-2015 (free software, GPL)
     │  GAP  │   http://www.gap-system.org
     └───────┘   Architecture: x86_64-unknown-linux-gnu-gcc-default64

    gap> Representative(Cyclotomics);
    Error, no method found! For debugging hints type ?Recovery from NoMethodFound
    Error, no 1st choice method found for `Representative' on 1 arguments called from
    <function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
     called from read-eval loop at line 1 of *stdin*
    you can 'quit;' to quit to outer loop, or
    you can 'return;' to continue
    brk> quit;
    gap> One(Cyclotomics);
    1
    gap> Representative(Cyclotomics);
    1

Here we start by computing zero:

    gap> Zero(Cyclotomics);
    0
    gap> Representative(Cyclotomics);
    0

**Comment by stevelinton** [comment]
We could fix this specific issue easily, but I wonder if it's safe to install a Representative method for any field  that returns the Zero. I'm finding it hard to imagine a field that can't make it's Zero.

**Comment by stevelinton** [comment]
On reflection that looks like a bad idea. There are methods for Zero and One that use Representative.

**Comment by stevelinton** [comment]
Fixed in a tiny commit on master. All cyclotomic fields and Cyclotomics itself know to return 0 as representative.

**Comment by alex-konovalov** [comment]
commit ID for refefence: https://github.com/gap-system/gap/commit/8e90f29789dce66c48e052ce7b21b6ff33d8d55c
