### ISSUE TITLE
Change build system to detect when GAP cannot find GAPDoc

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#520]
This isssue evolved from the discussion on PR #497

Basically, it would be nice if we could detect from scripts and/or the build system whether GAP cannot find GAPDoc, so that we can properly inform the user. This is in particular important for targes like `testinstall`, which otherwise hide all GAP output (well, we might want to change the behavior of those targets in that regard, too, but that's a separate issue).

Right now, this happens:

```
$ ./bin/gap.sh
 ┌───────┐   GAP v4.8.1-109-g1276b85 of 2016-01-20 15:30:32 (GMT)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin15.2.0-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
#I  GAP: needed package gapdoc cannot be loaded
Error, failed to load needed package `gapdoc' (version >= 1.2) called from
func(  ); at /Users/mhorn/Projekte/GAP/gap.github/lib/system.g:159 called from
<function "CallAndInstallPostRestore">( <arguments> )
 called from read-eval loop at line 811 of /Users/mhorn/Projekte/GAP/gap.github/lib/init.g
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk>
```

Perhaps we should catch this specific case, and let GAP exit immediately with a special error code, so that we can test for the problem in a shell script (or in the Makefile, for that matter) and report it properly...

**Comment by fingolfin** [comment]
I thought that perhaps one could use a simple trick like this:
```
echo "IsPackageMarkedForLoading("gapdoc", ">= 1.2");" | ./bin/gap.sh -A -b -q
```
but somehow this is not working, while this does work as I expect it:
```
echo "1+1;" | ./bin/gap.sh -A -b -q
```
Probably some silly mistake on my side, hopefully somebody can point out the flaw :)

**Comment by alex-konovalov** [comment]
I think the error `Error, failed to load needed package `gapdoc' (version >= 1.2)` happens much earlier before you are able to call `IsPackageMarkedForLoading` at all...

**Comment by frankluebeck** [comment]
How about:
```
echo "IsPackageMarkedForLoading(\"gapdoc\", \">= 1.2\");" | ./bin/gap.sh -A -b -q -T
```
Of course, this produces a bit more than just `false` because some code from GAPDoc is missing.

**Comment by fingolfin** [comment]
@frankluebeck Aha, thanks -- I forgot to properly quote, silly me! So, this seems to work:
```
echo "QUIT;" | ./bin/gap.sh -A -b -q -T 2>&1 | fgrep -q "needed package gapdoc cannot be loaded"
```

**Comment by fingolfin** [comment]
So, I have changed the title of this issue -- the problem is not anymore to find out whether GAPDoc cannot be found. It's now just a matter of teaching the build system to do this, so that the user gets a better error message.

**Comment by fingolfin** [comment]
I am happy with how `make check` behaves when GAPDoc is missing, and there is no `make testinstall` etc. anymore.
