### ISSUE TITLE
Removing 32-bit cygwin

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#5226]
The current 32-bit cygwin release script has broken, because https://www.cygwin.com/setup-x86.exe has been replaced with an executable that just prints "Cygwin is not supported on 32bit Windows". While we could get an old version of the installer for a while, the clearly better plan is to remove 32-bit cygwin.

This will probably involve multiple changes, including:

[ ] remove 32-bit cygwin from release wrapping
[ ] remove 32-bit cygwin from releases web page (when the next release is made)

**Comment by fingolfin** [comment]
@ChrisJefferson this is complete, isn't it?

**Comment by ChrisJefferson** [comment]
Yes, I can't find any particular trace left
