### ISSUE TITLE
add index entries for supported user preferences to the Reference Manual

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5233]
The idea came up in the discussion of issue #5230.

Since there is no special GAPDoc magic for user preferences that would automatically generate index entries to their documentation, we can insert `<Index>` elements by hand in those places where the effects of the preferences are described.

For example, entering `??autoload` will then find the manual section(s) where the user preference `ExcludeFromAutoload` is mentioned.

**Comment by fingolfin** [comment]
I think an actual "table" with all the user preferences defined by GAP (not by packages) would be useful to have.

We could write a small script to do that, which iterates over all the declared user preferences, and which generates an XML file from their names and descriptions, which we then just include into the manual. I imagine the code for `ShowUserPreferences` has all the required bits to do this.

I.e., the script could generate a file `doc/ref/_userpref.xml` or so. It could either be generated as part of `doc/make_doc`, or perhaps easier: it could be added to git, and we just check that it is kept up-to-date by adding a CI test regenerating it (and reporting a test failure if there is a diff).

That script then can of course also insert the appropriate `<Index>` elements (if it is necessary; depends a bit on the exact XML it generates).

**Comment by fingolfin** [comment]
Bonus points if those entries can be referenced, so that when 76.2 talks about `ExcludeFromAutoload`, that could a `<Ref>` to its manual entry

**Comment by fingolfin** [comment]
@ThomasBreuer yes that sums it up nicely.

**Comment by ThomasBreuer** [comment]
O.k., I will provide a pull request for that.
(If we add GAPDoc markup to the text of the declarations then a release of the Browse will be needed to keep `BrowseUserPreferences` working.)

**Comment by fingolfin** [comment]
This was resolved by PR #5248
