### ISSUE TITLE
Segfault in 4.12.1

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#5237]
When I run 4.12.1 with the following file
[segfault.txt](https://github.com/gap-system/gap/files/10134106/segfault.txt)
(given as parameter to gap.sh), GAP segfaults after a few minutes.

This does not happen on a Linux system. The segfault does not seem to happen in 4.12.0 on the M1, which makes me believe that this is a GAP issue and not a compiler bug.

**Comment by fingolfin** [comment]
So where does it crash? Your messages suggests that perhaps on an M1 Mac? If so, what OS, what Xcode version, what does `clang --version` say, and why does this exclude a compiler bug?

Also, what is the backtrace when GAP crashes?

**Comment by ChrisJefferson** [comment]
Could you also give the output, just so I know how long I have to run it before it will crash, or when I've missed it (at least when you see it)

**Comment by fingolfin** [comment]
It's been running for over 2 hours now on my machine (M1 MacBook Pro, with macOS 12.6.1), no segfault so far. Built with `Apple clang version 14.0.0 (clang-1400.0.29.202)`

**Comment by hulpke** [comment]
Yes, M1 Mac Max (64GB). Compiler Version:
```
[burnside:~] hulpke% clang -v
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
And now of course it runs past the place when it crashed yesterday multiple times. Arrgh!

**Comment by fingolfin** [comment]
Closing this for now, feel free to reopen if you find a way to reproduce or can provide at least a backtrace (e.g. as reported by macOS crash reporter)
