### ISSUE TITLE
Performance regression in grpprmcs.tst

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#524]
tst/teststandard/grpprmcs.tst runs about 10 times slower in master than in 4.8.1. It's the same test file,
so it isn't that extra tests have been added.

**Comment by hulpke** [comment]
> tst/teststandard/grpprmcs.tst runs about 10 times slower in master than in 4.8.1. It's the same test file,
> so it isn't that extra tests have been added.
> 

If this is as part of the standard test suite, it is most likely the new assertions in the homomorphism code. Does the same slowdown happen if one runs without assertions turned on?

**Comment by stevelinton** [comment]
We’re tracking it down now. I’ll check that.

Steve

**Comment by stevelinton** [comment]
Yes. Forcing assertions off solves the problem.

So probably not actually a problem. 

I guess we shouldn’t really use our tests as our benchmarks.

If these assertions are too annoying for regular testing, we could raise them to level 3 
at which point standard tests will not trigger them.

We might also want a way to run a directory of tests with assertion level 0 as an actual fair benchmark.
