### ISSUE TITLE
Move AlgebraHomomorphismByFunction to the main GAP library 

### ISSUE THREAD

**Issue by cdwensley** [gap-system/gap#5240]
In XModAlg issue #57 @fingolfin pointed out that FR and XModAlg had slightly different implementations of the operation.  In FR 2.4.12 and XModAlg 1.23 the declarations and implementations have been synchronised, with the intention that the function (together with AlgebraWithOneHomomorphismByFunction) should be moved as soon as convenient to the main GAP library.

**Comment by fingolfin** [comment]
A PR doing this would be welcome

**Comment by cdwensley** [comment]
This issue is being addressed in PR #5255

**Comment by fingolfin** [comment]
Thanks for working on this.

BTW I now discovered that `ProductIdeal` is another problematic operation defined by both `fr` and `modisom`. I guess we should look

**Comment by cdwensley** [comment]
@fingolfin : regarding ProductIdeal: happy to work on this after the holiday, but too much on at present.
