### ISSUE TITLE
Profiling outputs malformed JSON if function names contain special characters

### ISSUE THREAD

**Issue by zickgraf** [gap-system/gap#5259]
`NameFunction` might contain special characters like `"` or `\`:
```gap
gap> func := x -> x;
function( x ) ... end
gap> SetNameFunction( func, "\"\\" );
gap> NameFunction( func );
"\"\\"
```

Real life application: In CAP we give functions telling names to simplify debugging, see https://github.com/homalg-project/CAP_project/blob/a7f6b2311a38ad3e941fa6a5aa6493b0415085fb/CAP/gap/InstallAdds.gi#L606 In these names we use the name of a CAP category, which sometimes contains `"`.

When profiling, GAP puts function names into JSON strings without escaping them: https://github.com/gap-system/gap/blob/5fa271513ff2fdd68be23724243ca354bdc4f92d/src/profile.c#L294-L297 Thus, a function name containing `"` produces a malformed output.

Possible implementation: According to https://stackoverflow.com/questions/3020094/how-should-i-escape-strings-in-json/3020108#3020108, only `"`, and `\` and control characters must be escaped, so this should not be too hard (and I guess one could also simply ignore control characters) but my GAP + C skills are not sufficient for implementing this cleanly :(

Another "solution" would of course be to simply forbid using `"` and `\` in function names.

**Comment by ChrisJefferson** [comment]
I think this should be fixed, as I don't think GAP would at this point want to ban these (banning them might have been a good idea at some point in the past, but if there are packages which use them, it's probably too late now).

**Comment by zickgraf** [comment]
I can confirm that the issue does not occur anymore, thanks @ChrisJefferson for the fix!
