### ISSUE TITLE
Unexpected behaviour of `Objectify`

### ISSUE THREAD

**Issue by zickgraf** [gap-system/gap#5277]
### Observed behaviour

The following code objectifies lists and records with different types and observes if the results lie in `IsPositionalObjectRep` or `IsComponentObjectRep`:

```
gap> IsPositionalObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsObject ), [ 1 ] ) );
false
gap> IsPositionalObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsPositionalObjectRep ), [ 1 ] ) );
true
gap> IsPositionalObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsComponentObjectRep ), [ 1 ] ) );
false
gap> IsPositionalObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsObject ), rec( a := 1 ) ) );
false
gap> IsPositionalObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsPositionalObjectRep ), rec( a := 1 ) ) );
true
gap> IsPositionalObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsComponentObjectRep ), rec( a := 1 ) ) );
false
```
```
gap> IsComponentObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsObject ), [ 1 ] ) );
false
gap> IsComponentObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsPositionalObjectRep ), [ 1 ] ) );
false
gap> IsComponentObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsComponentObjectRep ), [ 1 ] ) );
true
gap> IsComponentObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsObject ), rec( a := 1 ) ) );
false
gap> IsComponentObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsPositionalObjectRep ), rec( a := 1 ) ) );
false
gap> IsComponentObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsComponentObjectRep ), rec( a := 1 ) ) );
true
```

### Expected behaviour

The documentation of `Objectify` claims:

> If data is a list then Objectify turns it into a positional object, if data is a record then Objectify turns it into a component object [...].

Thus, I would for example expect the following outputs:
```
gap> IsPositionalObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsObject ), [ 1 ] ) );
true
gap> IsPositionalObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsPositionalObjectRep ), [ 1 ] ) );
true
gap> IsPositionalObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsComponentObjectRep ), [ 1 ] ) );
true
```

More generally, the result of the first objectify does not seem to lie in any representation:
```
gap> IsInternalRep( Objectify( NewType( NewFamily( "TestFamily" ), IsObject ), [ 1 ] ) );
false
gap> IsDataObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsObject ), [ 1 ] ) );
false
gap> IsComponentObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsObject ), [ 1 ] ) );
false
gap> IsComponentObjectRep( Objectify( NewType( NewFamily( "TestFamily" ), IsObject ), [ 1 ] ) );
false
```

The documentation says:
 > GAP  distinguishes  four essentially different ways to represent objects. First there are the representations IsInternalRep [...], and IsDataObjectRep [...].
>
>  All other objects are either in the representation IsComponentObjectRep or in the representation IsPositionalObjectRep [...].

This sound like any object should lie in one of the four representations.

Am I misinterpreting the documentation?

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.12.1 of 2022-10-20
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN, readline
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.6.dev, IO 4.7.0dev, PrimGrp 3.4.2, SmallGrp 1.5, TransGrp 3.6.3
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by fingolfin** [comment]
Whether something is a component object or a positional object is entirely determined by its TNUM on the C level. The filters `IsPositionalObjectRep` and `IsComponentObjectRep` are *not* implied by this, and at least currently, are not enforced consistently. So the problem here is that "is a component object" in the `Objectify` documentation refers to `IS_COMOBJ ` resp. equivalently `TNUM_OBJ(obj) = T_COMOBJ`, which (confusingly) is *not* the same as `IsComponentObjectRep(obj)`.

See also issue #1043 which discusses this and plans to make this less confusing.

**Comment by zickgraf** [comment]
I see, thanks for the explanation! Then I will close this as a dupe of #1043 and #4964.
