### ISSUE TITLE
problem with reading`.gap/gaprc`  from `bin/BuildPackages.sh`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5286]
The function `run_configure_and_make` in the script `bin/BuildPackages.sh` determines the name of the current package by starting GAP, reading the `PackageInfo.g` file, and then printing the value of `GAPInfo.PackageInfoCurrent.PackageName`.

Since #5182 got merged and thus in GAP 4.12.2, this GAP is started without the `-r` option, which means that the file `.gap/gaprc` gets read.
If this file contains a statement of the form `Print( "something\n" );` then `something` is taken as the package name.
A a consequence, several packages (`curlinterface`, `ferret`, `io`, ...) cannot be compiled in this situation.
(My `.gap/gaprc` contains such a `Print` statement.)

Do we perhaps need a way to enable the user's root directory but without reading `.gap/gaprc`?

**Comment by ChrisJefferson** [comment]
Alternatively, to catch issues with GAP printing errors or something, we could print something that was easier to find (prefix with something), then use `grep` to find the line with the package name.

**Comment by fingolfin** [comment]
We used to pass -r until PR #5182 by @mtorpey was merged. Unfortunately I think there are more things beyond printing which could negatively interfere with that code...

Perhaps an alternative solution that might then also work for @mtorpey would  be to restore the `-r` but also add `--bare`?

**Comment by mtorpey** [comment]
> restore the `-r` but also add `--bare`

This sounds good to me, so long as BuildPackages.sh doesn't require the use of GAPDoc or any other packages.

**Comment by fingolfin** [comment]
See PR #5293
