### ISSUE TITLE
Incomplete Stabilizer Chain records are being created

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#531]
It seems to pass when run as part of teststandard, but it fails:

```
gap> Test("tst/teststandard/grpperm.tst");
########> Diff in tst/teststandard/grpperm.tst, line 86:
# Input is:
List(MaximalSubgroupClassReps(g),Size);
# Expected output:
[ 93000000, 1488000, 6000000, 6000000, 60000, 48000, 46500 ]
# But found:
Error, List Element: <list>[77] must have an assigned value
######## 
########> Diff in tst/teststandard/grpperm.tst, line 90:
# Input is:
m:=MaximalSubgroupClassReps(w);;
# Expected output:
# But found:
Error, Record: '<rec>.labels' must have an assigned value
########
########> Diff in tst/teststandard/grpperm.tst, line 91:
#   Input is: 
Collected(List(m,x->Index(w,x)));
# Expected output:
[ [ 2, 3 ], [ 5, 1 ], [ 6, 1 ], [ 10, 1 ], [ 16, 1 ], [ 3125, 1 ], 
  [ 7776, 1 ], [ 100000, 1 ] ]
# But found:
Error, Variable: 'm' must have a value
########
grpperm.tst
GAP4stones: 10261
false
```

when run directly (with Test).

**Comment by alex-konovalov** [comment]
Problems observed in `make teststandard` as well: https://mail.gap-system.org/pipermail/gap/2016-January/000486.html

**Comment by stevelinton** [comment]
bisect leads me to
commit c033dcf... Add method 'SetStabChain', which sets both mutable and immutable stab chains in a

**Comment by stevelinton** [comment]
A quick test is 
[permgrpbug.txt](https://github.com/gap-system/gap/files/103173/permgrpbug.txt)

**Comment by ChrisJefferson** [comment]
The offending lines seems to be stbc.gi:463. I believe (but I'm not sure yet) that some function is passing in invalid stab chain into this method.

**Comment by ChrisJefferson** [comment]
I added a (very) basic VerifyStabChain method, to make sure that we only deal with valid stab chains, and added it at stbc.gi:463

Turns out quite a few places are producing invalid stab chains (missing required members like translabels). What I'm not sure about is if this is related to my changes, or this is a long-running issue which is being revealed. 

I think I might back out my changes to use ImmutableStabChains (so we get a working `master` branch), and then try re-adding the code, with a StabChain verification method.

**Comment by stevelinton** [comment]
I suspect this is long-term bad behaviour. Probably before the stabchains in question were not living as long. Your plan sounds good. The "verify" can stay in as an assertion. 

Might be worth a short-lived feature branch on which we can badger the authors/maintainers to clean up these issues.

**Comment by fingolfin** [comment]
On master, this test passes for me:
```
gap> Test("../../tst/testinstall/grpperm.tst");
   grpperm.tst
msecs: 26062
true
```
I it unclear to me whether that means the issue was fixed (how? when? by whom) or if I need to do something else to trigger it.

**Comment by ChrisJefferson** [comment]
I backed out some commits which were causing this, and haven't gone back in yet to try to redo the work, so this bug is fixed.
