### ISSUE TITLE
CI: gaplint CI job sometimes (?) seems to ignore its config

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5316]
Sometimes gaplint claims lots of violation for rules that are disabled in `.gaplint.yml`. See e.g.
- https://github.com/gap-system/gap/actions/runs/3898816472
- https://github.com/gap-system/gap/actions/runs/3902967652/jobs/6666696337

CC @james-d-mitchell

**Comment by james-d-mitchell** [comment]
Will investigate, thanks for the report!

**Comment by james-d-mitchell** [comment]
I’m pretty sure I know what this is and will fix first thing tomorrow, sorry for the inconvenience

**Comment by james-d-mitchell** [comment]
Unless anyone objects @fingolfin, is it ok if I transfer this issue to the gaplint repo?

**Comment by fingolfin** [comment]
Can one transfer issues across repositories? Anyway, I don't mind, as long as it is not forgotten :-)

**Comment by james-d-mitchell** [comment]
Ah, no it's not possible to transfer issues across organisations the "transfer issue" button fooled me. Anyway a fix is in
