### ISSUE TITLE
conventions for GAP code format?

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5321]
The CI test "Lint / gaplint" for the completely harmless pull request #5319 failed.
Apparently this is a quite new test which imposes certain convention on the format of GAP code, and apparently essentially all code files violate these conventions.

Did I miss some discussion/agreements about which kinds of conventions we want to enforce, and which code format counts as "correct", "wrong", "allowed" etc.?

For example, files in `lib` traditionally contain lines starting with `#O`, `#F`, etc., which I find quite useful; but now the tests claim that comment signs `#` must be followed by whitespace.
And why is whitespace behind opening brackets and in front of closing brackets regarded as forbidden? In fact, I do always insert such whitespace because I think this improves the readability.

Personally, I hate such unnecessary standardizations.

**Comment by james-d-mitchell** [comment]
@ThomasBreuer This is a bug in gaplint, there was no intention of adding any further rules to this beyond the existing 4 (or 2)  (no trailing whitespace, no tabs, no unused locals, no assigned but unused variables). See #5316, I'm going to fix that this morning, and sorry for the inconvenience!

**Comment by fingolfin** [comment]
Bug has been fixed, thanks @james-d-mitchell
