### ISSUE TITLE
Performance regression for matrices.

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#5341]
What I believe is the current development branch. Big compact matrices are highly inefficient in some operations:
```
map:=RegularActionHomomorphism(MathieuGroup(12));;
p:=Image(map);
mats:=List(GeneratorsOfGroup(p),x->PermutationMat(x,95040,GF(2))); # list of vectors. Really?
IsOne(mats[1]);
mats:=List(mats,x->ImmutableMatrix(GF(2),x)); #proper compact matrices
IsOne(mats[1]);
```

Both `IsOne` take lots of time and memory, since they call `Unpack`. Clearly not needed.

Same for `Order`, or if I change the field.

**Comment by fingolfin** [comment]
This isn't a regression, I can reproduce this also in GAP 4.12, 4.11, 4.10, 4.9, 4.8

**Comment by fingolfin** [comment]
However the cause for the slowdown:
- we indeed unpack
- but *then* we also use this test on the rest: `elm = elm^0` which is also horribly bad.

We'll look into fixing it
