### ISSUE TITLE
documentation of Omega

### ISSUE THREAD

**Issue by BrauerSuzuki** [gap-system/gap#5348]
The documentation states that Omega(G,p,n) is the **set** of elements g in a p-group G such that p^(p^n)=1. However, it is the subgroup generated by this set. The documentation of Agemo is however correct.

### Copy and paste GAP banner (to tell us about your setup)
 ┌───────┐   GAP 4.12.0 of 2022-08-18
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv8

**Comment by fingolfin** [comment]
Fixed by PR #5353
