### ISSUE TITLE
problem with `ConfluentMonoidPresentationForGroup` for the trivial group

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5354]
The (undocumented) function `ConfluentMonoidPresentationForGroup` runs into an error when the given group is trivial.
```
gap> ConfluentMonoidPresentationForGroup( CyclicGroup( 1 ) );
Error, MinimumList: <list> must contain at least one element
[...]
```
This happens in the master branch and in GAP 4.12.2.

**Comment by hulpke** [comment]
Is this a concrete problem?

**Comment by ThomasBreuer** [comment]
@hulpke It is just the usual problem that one's code gets more complicated if a function which one wants to use does not handle some trivial case.

**Comment by hulpke** [comment]
@ThomasBreuer 
If you can confirm that you have a concrete application (and are not just checking proactively) in which you use `ConfluenMon...` and it gets called for the trivial group  let me know and I will add a workaround. In the context of constructing extensions the trivial group did not really make sense, so that's why it was not covered.

**Comment by ThomasBreuer** [comment]
@hulpke Thanks. I had learned about the error from a user.
(I had looked at the code how to fix the problem, but since the function is undocumented it is not clear to me how the record must look like that shall be returned for the trivial group.)

**Comment by fieker** [comment]
On Wed, Feb 01, 2023 at 06:11:52AM -0800, Alexander Hulpke wrote:
> @ThomasBreuer 
> If you can confirm that you have a concrete application (and are not just checking proactively) in which you use `ConfluenMon...` and it gets called for the trivial group  let me know and I will add a workaround. In the context of constructing extensions the trivial group did not really make sense, so that's why it was not covered.

The application is group cohomology, well Galois cohomology. Of course,
the trivial group gives trivial cohomology, but the question is when and
where do we handle the special case...and how to fail...

**Comment by hulpke** [comment]
Thank you @fieker for the explanation. I have a fix for the `ConfluentMon..` function. I would expect that at least my 2-cohomology code will still stumble over the case of no generators, but I have not tried this. (I.e. even with this change other changes might be needed)

**Comment by fieker** [comment]
My application is yours: 2-cohomology, but for arbitrary modules that
support homs kernels,...
I need this in number theory and your paper was much more readable than
Derek Holt's in Magma...
So I followed you
