### ISSUE TITLE
buildsys: stop installing `${includedir}/gap/src` once no package needs it anymore

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5361]
Basically we need this while there are still distributed packages which use `#include "src/compiled.h"` or similar

As I write this, the following packages still do this:
1. [x] `caratinterface` -- resolved in version 2.3.5
1. [x] `digraphs` -- resolved in version 1.6.2
1. [x] `EDIM` -- resolved in version 1.3.7
1. [x] `IO` -- resolved in 4.8.1

**Comment by james-d-mitchell** [comment]
@fingolfin happy to fix this, what is the fix exactly?

**Comment by fingolfin** [comment]
@james-d-mitchell https://github.com/digraphs/Digraphs/pull/571

**Comment by fingolfin** [comment]
Merci @james-d-mitchell

**Comment by fingolfin** [comment]
Reopening as the prerequisites are done but not the actual change to `make install`
