### ISSUE TITLE
Current date and/or time in GAP

### ISSUE THREAD

**Issue by zickgraf** [gap-system/gap#5386]
Is there a reliable, cross-platform way of getting the current date and/or time in GAP? `NanosecondsSinceEpoch` seems to do the trick on Linux, but the documentation sounds like one should not rely on this.

Sorry if this question has been raised before, a search did not turn up an existing issue. From looking around I have the feeling there is no reliable method, but I wanted to check before starting to explore hacks :D

**Comment by zickgraf** [comment]
Looks nice and seems to rely on the `date` binary. Is this portable?

**Comment by ChrisJefferson** [comment]
I just checked and it does work on windows, although the exact format isn't fixed, I get: `"Fri Feb 24 15:55:29 CST 2023"` (note month and day are the other way around). Not sure if that's a difference because windows, or because different timezone.

**Comment by zickgraf** [comment]
> I just checked and it does work on windows, although the exact format isn't fixed, I get: `"Fri Feb 24 15:55:29 CST 2023"`

That's not a problem, I can call `date` myself with a fixed format.

Thanks @olexandr-konovalov and @ChrisJefferson for the suggestion and the test! :-)

**Comment by fingolfin** [comment]
On Slack (unaware of this issue) I advised @zickgraf about this code from PackageMaker, which does not require launching an external process and should work everywhere as long as IO is compiled:
```julia
# Return current date as a string with format DD/MM/YYYY.
BindGlobal( "Today", function()
    local secs, tmp, date;
    tmp := IO_gettimeofday();
    secs := tmp.tv_sec;

    date := DMYDay(Int(secs / 86400));
    date := date + [100, 100, 0];
    date := List( date, String );
    date := Concatenation( date[1]{[2,3]}, "/", date[2]{[2,3]}, "/", date[3] );

    return date;
end );
```

**Comment by zickgraf** [comment]
@fingolfin Thanks for this alternative suggestion, this looks very useful!
