### ISSUE TITLE
Resultant computation fails

### ISSUE THREAD

**Issue by vdlee37** [gap-system/gap#5392]
Running GAP 4.12.2 on Windows 11. Was trying to find the resultant wrt. `X` of the polynomials `X^3+2X+2` and `-X^2-X+Y` over the ring  `Z/4[T]/(T^2-T-1)`. The latter was constructed through a call to `RingByStructureConstants()`. The resultant can be found by evaluating a (sparse) determinant, so there should be no need for divisions - which is where the error apparently took place. Source of the function `res()` I used is in the file attached below.
[res.txt](https://github.com/gap-system/gap/files/10902263/res.txt) [and typed out here to avoid having to download a file]

```
  T := EmptySCTable(2,0,"symmetric");                        # 2 gens, zero coefficient
#
# generators: "u" (the unit, = 1) and "t", an element with t^2=t+1
#
# format of the value list in structure constants table entries is [coeff,gen,coeff,gen,...]
#
  SetEntrySCTable(T,1,1,[1,1]);                              # u*u = 1*u
  SetEntrySCTable(T,1,2,[1,2]);                              # u*t = 1*t
  SetEntrySCTable(T,2,2,[1,1,1,2]);                          # t*t = 1*1+1*t

  R := RingByStructureConstants([4,4],T,["u","t"]);          # 4*u = 0 = 4*t in R

  Print("\n",R,", of order ",Size(R),", unital: \"",IsRingWithOne(R),"\"\n");
  Print("gens: ",GeneratorsOfRing(R),"\n\n");

  u := GeneratorsOfRing(R)[1];
  t := GeneratorsOfRing(R)[2];

  P := PolynomialRing(R,["x","y"]);                          # polynomial ring
  x := X(R,"x");
  y := X(R,"y");

  f := x^3+2*x+2;
  g := -x^2-x+y;
  Print("f = ",f,", g = ",g,"\n");

  r := Resultant(f,g,1);
  Print("the resultant wrt. y is ",r,", g = ",g,"\n");
```

The response is:
```
f = x^3+2*u*x+2*u, g = -x^2-x+y
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for InverseMutable on 1 arguments at /opt/gap-v4.12.2/.libs/../lib/methsel2.g:249 called from
InverseOp( elm ) at /opt/gap-v4.12.2/.libs/../lib/arith.gi:421 called from
r / x at /opt/gap-v4.12.2/.libs/../lib/ratfun.gi:1696 called from
Resultant( f, g, 1 ) at *stdin*:14397 called from
<function "res">( <arguments> )
 called from read-eval loop at *stdin*:14401
type 'quit;' to quit to outer loop
brk>
```
GAP banner:
```
┌───────┐   GAP 4.12.2 built on 2022-12-19 10:30:03+0000
│  GAP  │   https://www.gap-system.org
└───────┘   Architecture: x86_64-pc-cygwin-default64-kv8
Configuration:  gmp 6.2.1, GASMAN, readline
Loading the library and packages ...
Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.6, AutPGrp 1.11, Browse 1.8.19, CaratInterface 2.3.4, CRISP 1.4.6, Cryst
            IRREDSOL 1.4.4, LAGUNA 3.9.5, orb 4.9.0, Polenta 1.3.10, Polycyclic 2.16, PrimGrp 3.4.3, RadiRoot 2.9, recog 1.4.
Try ??help for help. See also ?copyright, ?cite and ?authors
```

**Comment by hulpke** [comment]
The implemented resultant method implemented indeed assumes that the coefficient ring is a field. There are probably other places in the polynomial code that will fail if the coefficient ring is not an integral domain.

**Comment by vdlee37** [comment]
Is there a way to tell GAP that the ring I'm using is a ring-with-one? For `DeterminantMatrixDivFree(mat)` also fails, perhaps for the reason the ring is not recognized as unital.

**Comment by hulpke** [comment]
Send me code that constrcuts your ring and I will see to add such functionality.

Best,

  Alexander Hulpke

On Mar 6, 2023, at 2:29 PM, Matthé van der Lee ***@***.***> wrote:


** Caution: EXTERNAL Sender **


Is there a way to tell GAP that the ring I'm using is a ring-with-one? For DeterminantMatrixDivFree(mat) also fails, perhaps for the reason the ring is not recognized as unital.

**Comment by hulpke** [comment]
The commit under

https://github.com/hulpke/gap/commit/72a0c2aaeb7da3b1c8b4a417686ee09c0fc56af7

will resolve this issue.

**Comment by vdlee37** [comment]
Thank you very much!
