### ISSUE TITLE
Program cleanup logic not run when quiting from an error during processing init files

### ISSUE THREAD

**Issue by zickgraf** [gap-system/gap#5414]
After ac59afff6258ed1ca9f49949e67029e6ad1ed80c, the program cleanup logic is not run if an error is triggered in an init file and the user types `quit;` (or Ctrl-D). This can be observed as follows:

```
$ gap -c "DirectoryTemporary(); Error(\"test\");"
 ┌───────┐   GAP 4.13dev-356-g7cc5d76 built on 2023-03-17 16:17:00+0100
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN, readline
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.6.dev, IO 4.7.0dev, PrimGrp 3.4.0, SmallGrp 1.4.1, TransGrp 2.0.5
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
Error, test called from
not in any function at stream:1
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> quit;
```

This leaves behind a temporary directory which is not cleaned up.

I'm not sure what a good solution would be. The issue can be fixed by what I describe in https://github.com/gap-system/gap/pull/5179#issuecomment-1326326715 but this seems to be a rather fundamental change. Maybe a new mechanism for triggering the cleanup logic which does not rely on the `init.g` file would be helpful and also solve #5413.

**Comment by fingolfin** [comment]
See #4695

**Comment by zickgraf** [comment]
Sounds like `CALL_CATCH_QUIT` proposed in #4695 would do something similar to what I tried in https://github.com/gap-system/gap/pull/5179#issuecomment-1326326715. Closing as duplicate.
