### ISSUE TITLE
inconsistency with `CompanionMatrix`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5423]
The GAP documentation does not define what a companion matrix is, and shows no example,
and the behaviour of GAP is inconsistent.

(To be precise, there are two independent places in the GAP Reference Manual about `CompanionMatrix`. [The one in the chapter about vector and matrix objects](https://docs.gap-system.org/doc/ref/chap26_mj.html#X85FAB7E778A71C19) states that row convention is used, but [the one in the chapter about matrices](https://docs.gap-system.org/doc/ref/chap24_mj.html#X85B403857F2855F7) does not say which convention is used. I think the latter manual section is older.)

The method that takes just a polynomial puts the coefficients of the polynomial into the last *column* of the matrix,
whereas the methods that specify the internal representation of the matrix put the coefficients into the last *row*.
```
gap> x:= X(GF(3));;  pol:= x^2 + x + 1;;
gap> Display( CompanionMatrix( pol ) );
 . 2
 1 2
gap> Display( Unpack( CompanionMatrix( IsPlistMatrixRep, pol, GF(3) ) ) );
 . 1
 2 2
gap> Display( Unpack( CompanionMatrix( Is8BitMatrixRep, pol, GF(3) ) ) );
 . 1
 2 2
```
How shall we proceed?

**Comment by fingolfin** [comment]
Luckily there seems to be no package using `CompanionMatrix`. Only `CompanionMat` is used. Even `cvec` (which provides a method for it) uses `CompanionMat` in one spot.

I would thus tend to think that we should document and implement whatever `CompanionMat` does?
