### ISSUE TITLE
Kernel: Make calls to MakeBagTypePublic etc. stand out as HPC-GAP specific

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#543]
Part of the plan for unifiication of our two primary branches asks for clearly marking kernel code that is HPC-GAP specific as such.

Currently, this is still being violated by calls to the the functions
-  `MakeBagTypePublic`
- `MakeBagTypeProtected`
- `MakeBagPublic`
- `MakeBagReadOnly`
  They are no-ops on the master branch, but do occur in various spots.

There are two ways to resolve this:
1. Surround each invocation by an `#ifdef HPCGAP`
2. Rename the functions to have an `HPC` prefix (or suffix, or whatever).

If we use solution 1, then we can also remove the no-op definitions of these functions (and thus would catch any accidental calls to them not surrounded by `#ifdef HPCGAP`

The discussion in #521 remainded me of this.

**Comment by ChrisJefferson** [comment]
I will look at this, but wait a couple of weeks for the current merging / rearrange of @markuspf to finish, to avoid unnessasary clashes.

**Comment by fingolfin** [comment]
So, I wonder what our status on this is..

**Comment by fingolfin** [comment]
This was resolved by PR #2511
