### ISSUE TITLE
BuildPackages.sh is not installed by `make install`

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#5448]
### Observed behaviour

After running `make install`, the script `BuildPackages.sh` is not found where `packagemanager` expects it.

### Expected behaviour

It should get installed (to `bin/` of the prefix)

### Copy and paste GAP banner (to tell us about your setup)

happens with 4.12.2, and on the current master ` GAP 4.13dev-384-g4bf725e built on 2023-05-06 23:50:14+0100`

**Comment by dimpase** [comment]
It's actually fixed in PackageManager, just not in the GAP release yet. See
https://github.com/gap-packages/PackageManager/pull/108

**Comment by dimpase** [comment]
No, sorry, it's actually still relevant, even after https://github.com/gap-packages/PackageManager/pull/108 - because GAP's `make install` does not do anything with packages, so even with the new release of PackageManager it's still the same.

**Comment by fingolfin** [comment]
`BuildPackages.sh` is not meant to be installed and won't be installed. It is not necessary for an installation either. It is a crutch.

What is the actual problem you want to solve?

**Comment by dimpase** [comment]
It's necessary for compiling packages, while they are installed by `PackageManager`. 

I know that https://github.com/gap-packages/PackageManager/pull/108 bundles it into `PackageManager`. 
So the question is as follows.

Is the latest `PackageManager` "relocatable", in the sense that no matter where you copy it, it can call  its bundled `BuildPackages.sh` if needed, and `BuildPackages.sh` does not need to be installed at a specific location related to the prefix GAP is installed in? 

Yes, it's related to the unresolved issue of `make install` for packages. Actually, if the latter is true, then the latter issue is largely resolved, in the sense that we can delegate installation of packages to `PackageManager`. (Now I'm getting flashbacks from the never-ending Python packaging saga...)

**Comment by fingolfin** [comment]
> It's necessary for compiling packages, while they are installed by `PackageManager`.

No, it is not necessary with the current `PackageManager` release.

> 
> I know that [gap-packages/PackageManager#108](https://github.com/gap-packages/PackageManager/pull/108) bundles it into `PackageManager`. So the question is as follows.
> 
> Is the latest `PackageManager` "relocatable", in the sense that no matter where you copy it, it can call its bundled `BuildPackages.sh` if needed, and `BuildPackages.sh` does not need to be installed at a specific location related to the prefix GAP is installed in?

Yes.

> 
> Yes, it's related to the unresolved issue of `make install` for packages. Actually, if the latter is true, then the latter issue is largely resolved, in the sense that we can delegate installation of packages to `PackageManager`. (Now I'm getting flashbacks from the never-ending Python packaging saga...)

I don't quite follow this sentence ("latter" is used multiple times to refer to different things, and I am not sure how to parse the sentence). In any case, I don't think using `PackageManager` is necessary for distro packagers. Nor is `BuildPackages.sh` -- all the latter does in the latest iteration is a glorified version of `./configure && make`. And all the former does is download, extract (both not necessary for distro packagers), and then copy packages, and finally run `BuildPackages.sh`. It doesn't do any clever things. Perhaps it *should* do them (like getting rid of `*.o` files or so), but it currently doesn't.

**Comment by dimpase** [comment]
sorry for unclear writing. 

I meant "Actually, if _the latest PackageManager is "relocatable"_ then the issue _of  absence of_ `make install`  _for packages_ is largely resolved".
