### ISSUE TITLE
Make it super-easy to collect code coverage for test suite

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#545]
We should make it super easy to compute code coverage results for the test suite. E.g. there could be a `make` target `coverage`, or perhaps `cov-testinstall` and `cov-testandard`, and thes would start GAP with the right options, run the selected test suite, dump everything into a specific place, run `profiling` on it to create HTML, and finally tell the user where the `index.html` is.

**Comment by ChrisJefferson** [comment]
If anyone wants to work on this, there is a basis vagrant box here, which I have used to profile GAP and C (it isn't really in a finished state as it is). https://github.com/ChrisJefferson/GAPCoverage

**Comment by fingolfin** [comment]
With the codecov setup, I am personally mostly happy now, and we might consider this as resolved.

Of course it would be nice if we next could also provide a read-made solution to package authors, so that they can trivially setup travis and codecov for their packages... Something like my `GitHubPagesForGAP` just for packages. But that's really a separate issue.

**Comment by fingolfin** [comment]
I am actually satisfied with the current state using codecov; we already pushed this out to dozens of packages, too.
