### ISSUE TITLE
Create a website where we display the latest code coverage results for our testsuite

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#546]
Building upon #545 there should be a website where the display the latest code coverage results. This website should be updated regularly (ideally on every commit, but more realistic is, say, every 24 hours).

I am not sure whether we can use Travis for that (probably not, due to runtime limitations), but perhaps a Jenkins task could be setup for that? The last step of that task could be to copy the created HTML files to a location where a webserver can access them. I.e. it is not even necessary to open Jenkins up to the public.

**Comment by alex-konovalov** [comment]
Assigned to myself - Jenkins is certainly the right tool here. I will need help from John for the last step.

**Comment by alex-konovalov** [comment]
For the record, by now I have dedicated Jenkins slave in the cloud, which produces the coverage report. It remains to sort out the publishing part.

**Comment by alex-konovalov** [comment]
I will add some starting page with the description, but for now http://gap-coverage.northeurope.cloudapp.azure.com/ already reports coverage in testinstall.g and testall.g when GAP started with `-r -A` this evening. Just click on links to directories to see coverage reports.

**Comment by hungaborhorvath** [comment]
Thank you, this is really great! I have one question, though. What is the difference between the green and the red lines? (In particular, how do you get a red line? I only got green lines so far.) I did not seem to find a legend for this anywhere in the homepage of the profiling package.

**Comment by ChrisJefferson** [comment]
A bright red green line is executed.

A bright red line is NOT executed.

Lines which are neither bright red or bright green are not executed (you might think those lines were executed, this is to do with how GAP internally represents code.

The important thing is, get rid of bright red lines by adding tests!

**Comment by alex-konovalov** [comment]
For the first time in history - coverage report for the reference manual: http://gap-coverage.northeurope.cloudapp.azure.com/coverage-testmanuals/

**Comment by alex-konovalov** [comment]
And now the next part: http://gap-coverage.northeurope.cloudapp.azure.com/coverage-total/ contains merged coverage report for teststandard and testmanuals

**Comment by ChrisJefferson** [comment]
@alex-konovalov : Can you update  http://gap-coverage.northeurope.cloudapp.azure.com/coverage-total/ ? (or send me the script you made it with)?

**Comment by alex-konovalov** [comment]
@ChrisJefferson It's run via Jenkins and needs no my intervention to be updated!!! ;-) 

As soon as the test passes successfully, it copies all to http://gap-coverage.northeurope.cloudapp.azure.com/ - the date of the creation of the directories that you may see there is `2016-02-23 19:48` so this is last night's build.

It's only when tests fail that the HTML will not be copied over.

Next update will be tomorrow, after nightly tests will start at 6pm.

**Comment by alex-konovalov** [comment]
http://gap-coverage.northeurope.cloudapp.azure.com/ now has the fresh version, produced using the json update picked up this morning. Coloured cells indicating % of the coverage looks great!

**Comment by markuspf** [comment]
This can now be closed, we have `codecov.io` coverage.

**Comment by markuspf** [comment]
Here is a link: https://codecov.io/gh/gap-system/gap
