### ISSUE TITLE
GAP Icon Stays Orange

### ISSUE THREAD

**Issue by mattzamat** [gap-system/gap#5466]
Hi there,

Not sure if this is a bug or not, but the GAP icon continues to stay illuminated in orange after using the extension- even after clicking and viewing its results. See below:

![Screenshot 2023-06-22 at 15 38 38](https://github.com/gap-system/gap/assets/96935285/5794605f-29be-40c5-9a39-ae4dc801fbca)

Thank you!

**Comment by ChrisJefferson** [comment]
Just checking, are you sure you are submitting this issue to the right GAP? :) This GAP is a programming language for mathematics.

If you are using our GAP, can you give more details, as I wasn't aware we had an extension which illuminated orange?

**Comment by fingolfin** [comment]
Perhaps this might refer to https://github.com/xnl-h4ck3r/GAP-Burp-Extension where @mattzamat opened an issue before.
