### ISSUE TITLE
Gamify test coverage

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#547]
Further building upon #545 and #546, it would be super-awesome if there was a way to compute for a given pull request how it affects code coverage, and then disaply that information publically (ideally on the PR itself).

A simple aggregated "score" would already be a start. Bonus points if the summary could say something like:  "in lib/, NNN lines were added, NNN lines removed, code coverage increased / decreased by NNN lines`.

**Comment by fingolfin** [comment]
The hope being that this makes submitting PRs fun to crazy people like me, who enjoy seeing that their tests now cause e.g. 100 lines additionaly of `lib` to be covered.

And yes, I realize that test coverage alone does not mean the test suite is great. But a line that is never tested certainly is worse than a line that *is* tested, even if the test is not very good. Plus, we of course would still review PRs, and reject nonsensical submissions.

**Comment by markuspf** [comment]
We now have codecov.io reports and a badge. It does pretty much what is suggested in this issue.

**Comment by alex-konovalov** [comment]
One could also to the PR details as below. I can't find this on codecov site, so just attaching the screenshot of an example shown in their email.

![screen shot 2016-08-04 at 16 03 06](https://cloud.githubusercontent.com/assets/5751387/17406846/056b5c52-5a5d-11e6-86d1-25b714cde525.png)

**Comment by alex-konovalov** [comment]
With https://codecov.io/gh/gap-system/gap it pretty much achieves this goal. With recent additions we have 68% covered by Travis/AppVeyor tests. Further improvements could be to look how package code is covered by their tests, or how the library code is exercised by package tests, but that's for another issue, and maybe different setup of package update mechanism...
