### ISSUE TITLE
ldots -> \ldots in 24.13-4 BlownUpMat

### ISSUE THREAD

**Issue by Spamakin** [gap-system/gap#5470]
In the documentation for [24.13-4 BlownUpMat](https://docs.gap-system.org/doc/ref/chap24_mj.html#X85923C107A4569D0) there is a `ldots` that should be `\ldots`. I would submit a PR to the documentation but I could not find the relevant file in the `doc` directory.

**Comment by ChrisJefferson** [comment]
Thanks for the issue. I managed to find the problem by using github search to look for text in the docs for `BlownUpMat`, which found it in 'lib/matrix.gd' -- some functions are documented where they are defined. If you would like to make a PR fixing that, great, else i'm happy to do it if you like.

**Comment by Spamakin** [comment]
Done. I did not realize the `.gd` files were documentation. I was looking for `.tex` or `.md` or `.html` files.
