### ISSUE TITLE
Regression in packages kan and fr

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5478]
Commit 4d79f6e595d63627b2d11c88a40b7312c094fd51 from PR #5468 by @hulpke broke the package tests for `fr` and `kan`.

To reproduce, enter e.g. `TestPackage("kan");` and wait for the failures. The first is in this test:
```
LoadPackage("kan");  # should be run before the test snippet below

## Section 2.1
gap> F4 := FreeGroup( 4 );;
gap> rels := [ Comm(F4.1,F4.2) * Comm(F4.3,F4.4) ];;
gap> H4 := F4/rels;; 
gap> L := [2,1,4,3,6,5,8,7];;
gap> order := "wreath";;
gap> alph4 := "aAbBcCdD";;
gap> rws4 := ReducedConfluentRewritingSystem( H4, L, order, 0, alph4 );;
```
Which results in the error:
```
gap> rws4 := ReducedConfluentRewritingSystem( H4, L, order, 0, alph4 );;
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `[]' on 2 arguments at /Users/mhorn/Projekte/GAP/gap/lib/methsel2.g:250 called from
u := kbrws!.tzrules[ui]; at /Users/mhorn/Projekte/GAP/gap/lib/kbsemi.gi:779 called from
KBOverlaps( i[1], i[2], kbrws, p ) at /Users/mhorn/Projekte/GAP/gap/pkg/kan/lib/kbrws.gi:48 called from
LimitedMakeKnuthBendixRewritingSystemConfluent( kbrws, limit
 ); at /Users/mhorn/Projekte/GAP/gap/pkg/kan/lib/kbrws.gi:81 called from
MakeConfluent( kbrws, limit ); at /Users/mhorn/Projekte/GAP/gap/pkg/kan/lib/kbrws.gi:151 called from
ReducedConfluentRewritingSystem( M, ord, limit ) at /Users/mhorn/Projekte/GAP/gap/pkg/kan/lib/kbrws.gi:241 called from
...  at *stdin*:10
type 'quit;' to quit to outer loop
brk> kbrws!.tzrules;
[ [ [ 1, 2 ], [  ] ], [ [ 2, 1 ], [  ] ], [ [ 3, 4 ], [  ] ], [ [ 4, 3 ], [  ] ], [ [ 5, 6 ], [  ] ],
  [ [ 6, 5 ], [  ] ], [ [ 7, 8 ], [  ] ], [ [ 8, 7 ], [  ] ], [ [ 2, 4, 1, 3, 6, 8, 5, 7 ], [  ] ] ]
brk> ui;
'A'
```

**Comment by hulpke** [comment]
This is to some extent a problem in Kan, that copied and modified a library function and accesses internal entries, rather5 than sorting out a clean interface.

I have a workaround with which the only remaining error messages from the test are harmless (Different arrangement of rules).

**Comment by fingolfin** [comment]
Note that fr also has issues (but I did not yet investigate those)

**Comment by hulpke** [comment]
I think fr modifies the `tzrules` entry and does not update the `pairs2check`. Another workaround (and another hour of my life down the drain ...)

**Comment by cdwensley** [comment]
Away for next ten days. Will deal with this when home.

**Comment by cdwensley** [comment]
At last able to look at what has been going on with this issue, but see no real point in doing so since @hulpke has already got rid of the problem. Just want to make it clear that I would have been happy to do the necessary work on Kan if asked. PR#26 has dealt with the varying outputs from DisplayRwsRules.

**Comment by fingolfin** [comment]
Actually the changes by @hulpke only fully resolved the issue in fr, in kan there are still failures. See e.g. https://github.com/gap-system/PackageDistro/actions/runs/5869213193/job/15914195985

**Comment by fingolfin** [comment]
Huh, what do you mean, "no details"? It says:
```
testing: /home/runner/gap/pkg/kan-1.35/tst/manual/dcrws1.tst
########> Diff in /home/runner/gap/pkg/kan-1.35/tst/manual/dcrws1.tst:
25
# Input is:
DisplayRwsRules( rws4 );
# Expected output:
[ [ aA, id ], [ Aa, id ], [ bB, id ], [ Bb, id ], [ cC, id ], [ Cc, \
id ], [ dD\
, id ], [ Dd, id ], [ cd, dcBAba ], [ cBAbaD, Dc ], [ CD, BAbaDC ], [ Cd, dABa\
\
bC ] ]
true
# But found:
[ [ aA, id ], [ Aa, id ], [ bB, id ], [ Bb, id ], [ cC, id ], [ Cc, \
id ], [ dD\
, id ], [ Dd, id ], [ Cd, dABabC ], [ CD, BAbaDC ], [ cBAbaD, Dc ], [ cd, dcBA\
\
ba ] ]
true
########
      45 ms (40 ms GC) and 607KB allocated for dcrws1.tst
testing: /home/runner/gap/pkg/kan-1.35/tst/manual/dcrws2.tst
      36 ms (28 ms GC) and 1.71MB allocated for dcrws2.tst
testing: /home/runner/gap/pkg/kan-1.35/tst/manual/dcrws3.tst
########> Diff in /home/runner/gap/pkg/kan-1.35/tst/manual/dcrws3.tst:
28
# Input is:
DisplayRwsRules( rwsT );;
# Expected output:
[ [ dD, id ], [ Dd, id ], [ C, ccDD ], [ ccc, dd ], [ ddc, cdd ], [ \
Dc, dcDD ]\
 ]
# But found:
[ [ dD, id ], [ Dd, id ], [ ccc, dd ], [ ddc, cdd ], [ C, ccDD ], [ \
Dc, dcDD ]\
 ]
########
      39 ms (29 ms GC) and 1.92MB allocated for dcrws3.tst
testing: /home/runner/gap/pkg/kan-1.35/tst/manual/dcrws4.tst
    2910 ms (168 ms GC) and 340MB allocated for dcrws4.tst
testing: /home/runner/gap/pkg/kan-1.35/tst/manual/history.tst
      37 ms (32 ms GC) and 779KB allocated for history.tst
testing: /home/runner/gap/pkg/kan-1.35/tst/extra/kbtest.tst
      31 ms (28 ms GC) and 337KB allocated for kbtest.tst
-----------------------------------
total      3098 ms (325 ms GC) and 345MB allocated
              2 failures in 2 of 6 files

#I  Errors detected while testing
```

Also, those tests are against the latest kan *release*.

**Comment by cdwensley** [comment]
Sorry if I am being dense, but all I see is a list of packages, including Kan with a Red Cross against it. 
But, anyway, the listing you sent confirms that the problem is the ordering of rules in the output of DisplayRwsRules. That is what has been fixed in the latest PR, so I will make a new release. 
Before I do so, should I remove the Status entry from PackageInfo.g, or would that be premature? 
Thanks again.

**Comment by fingolfin** [comment]
@cdwensley which browser are you using? Here is a screenshot from Safari but for me it also works with Firefox and Vivaldi.
<img width="1623" alt="Screen Shot 2023-08-25 at 10 08 15" src="https://github.com/gap-system/gap/assets/241512/47f24700-a244-44ca-b0ca-127a13d6018d">

Regarding the `Status` entry from `PackageInfo.g`: that's rather immaterial from my point of view. Removing them is not necessary for anything, except that they'll be misleading going forward, as we will not use them for anything anymore. 

I guess there will be a point when we'll push for removing them in all packages at one point, but I'd rather complete all the other bits first (like, have GAP 4.13 released, and the website updated to not use package's own `Status` field etc.)

**Comment by cdwensley** [comment]
(I run GAP in a text window, but that's immaterial!). 
The screenshot above appears to be using kan-1.35 whereas I released kan-1.36 last week as a fix for this problem.  Has 1.36 not been picked up for some reason?

**Comment by fingolfin** [comment]
We detected no new kan release

**Comment by cdwensley** [comment]
Well it appears to be there in https://github.com/gap-packages/kan

**Comment by fingolfin** [comment]
https://gap-packages.github.io/kan/ still lists 1.35, perhaps the gh-pages branch update was not pushed?

**Comment by cdwensley** [comment]
But I was a little concerned at the time of making the release that the process had not completed in the usual way.  But seeing the "1.36 Latest" on https://github.com/gap-packages/kan made me think all was OK. 
I will try making a 1.37 and see what happens (out of practice with this procedure).

**Comment by cdwensley** [comment]
Cannot remember now about the gh-pages branch.  Had an idea that that happened automatically?

**Comment by fingolfin** [comment]
There is really ni need to make 1.37! Just update the website. I can explain how when I am back at a computer in a bit (typing on my phone eight now)

**Comment by cdwensley** [comment]
OK - I'll wait for instructions.

**Comment by fingolfin** [comment]
The new kan release fixes the issue. Thanks, @cdwensley and @hulpke !
