### ISSUE TITLE
problem with the documentation of `FamilyPcgs`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5483]
The documentation of `FamilyPcgs` says:
```
‣ FamilyPcgs( grp ) ────────────────────────────────────────────── attribute
  
returns  a  "natural"  pcgs  of  a  pc group grp (with respect to which pcgs
operations as described in Chapter 45 are particularly efficient).
```
This is true only if `grp` is a "full pc group".
If `grp` is a subgroup then the family pcgs of the full group is returned.
```
gap> g:= DihedralGroup(8);
<pc group of size 8 with 3 generators>
gap> c:= Centre(g);
Group([ f3 ])
gap> FamilyPcgs( g );
Pcgs([ f1, f2, f3 ])
gap> FamilyPcgs( g ) = FamilyPcgs( c );
true
```
Note that `IsPcGroup` returns `true` also for subgroups of full pc groups.
(The situation is different for fp groups, there we have `IsFpGroup` only for the full group, and `IsSubgroupFpGroup` for subgroups.)

By the way: What is the recommended way to find out whether a given pc group `grp` is in fact a full pc group?
One can of course check whether `grp` contains `FamilyPcgs( grp )`, but is there an easier way?

**Comment by hulpke** [comment]
It probably should say: of a group A, containing grp, with A chosen maximal.

It might be worth to align language with the documentation for `HomePcgs`.

**Comment by ThomasBreuer** [comment]
@hulpke Thanks. I am going to create a pull request for that.

**Comment by ThomasBreuer** [comment]
Concerning `HomePcgs` mentioned by @hulpke, this function is undocumented, as well as the concept of home pcgs. The term "home" in the sense of "home pcgs" still occurs in a few places in the Reference Manual:
- The documentation of `ClassesSolvableGroup` mentions home pcgs.
- The documentation of `ExtendedPcgs` erroneously refers to `home` as if it were the name of an argument. A possible fix would be to remove this reference. (Anyhow, the documentation of `ExtendedPcgs` is not really helpful. Moreover, all calls of `ExtendedPcgs` in the GAP library except one are commented out, and the one exception is inside the undocumented function `TailOfPcgsPermGroup`.)

**Comment by fingolfin** [comment]
@ThomasBreuer Has this been resolved by PR #5488? If not, what is left to be done?

**Comment by ThomasBreuer** [comment]
The original problem is solved.

@hulpke had suggested to achieve some consistency in the documentation of `FamilyPcgs` and `HomePcgs`. The latter is undocumented, so I do not know how to proceed with this suggestion.

**Comment by ThomasBreuer** [comment]
@hulpke I have not dealt with `HomePcgs` in #5488, but you had mentioned `HomePcgs` in a comment. Shall we change something about it, or close this issue?

**Comment by hulpke** [comment]
> @hulpke I have not dealt with `HomePcgs` in #5488, but you had mentioned `HomePcgs` in a comment. Shall we change something about it, or close this issue?

I think close -- I just wanted to alert everyone that there is a related issue for HomePcgs.
