### ISSUE TITLE
Segfault when/after calling Enumerate on a partial perm orbit

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/gap#55]
In the most recent development version of non-HPC GAP (commit ```51025ca```) using Orb 4.7.3 (whether or not it is compiled) [https://github.com/gap-system/orb/] testing of the Semigroups package has revealed a segfault:

If load GAP with:
```bin/gap.sh -r -A```
And then call:
```gap
gap> LoadPackage("orb", false);
gap> comp := BlistList([ 1 .. 3 ], [  ]);;
gap> opts := 
> rec(lookingfor := function(o, x)
>   if not IsEmpty(x) then
>     return IsPosInt(comp[ x[ 1 ] ]);
>   fi;
>   return false;
> end);;
gap> gens := [ PartialPerm( [ 1, 3 ], [ 3, 2 ] ) ];;
gap> o := Orb(gens, [ 1 ], OnSets, opts);;
gap> Enumerate(o);;
gap> Elements(o);
[ [  ], [ 1 ], [ 2 ], [ 3 ] ]
gap> Elements(o);;
Segmentation fault: 11
```
Calling ```Elements(o)``` the second time triggers a segfault.

LLDB says the segfault seems to happen in the GAP library in ```src/plist.c``` on line 706:

```gap
/* This had better return the cyclotomics family, could be speeded up */
family = FAMILY_TYPE( TYPE_OBJ( ELM_PLIST( list, 1 ) ) );
```
The list ```list``` is empty but this is not expected. Markus thinks this might be a problem with partial perms in GAP.

I originally found by using the most recent HPC-GAP. Using HPC-GAP, the segfault happens in the ```Enumerate(o)``` function. Perhaps these are different bugs, but it seems reasonable to think it is the same problem.

**Comment by james-d-mitchell** [comment]
This is the same issue as Issue 10 in the Orb package. I suggested a fix there.

**Comment by markuspf** [comment]
Inserting the code suggested in [orb issue #10](https://github.com/gap-system/orb/issues/10) into pperm.c fixes this, but it feels dirty.

**Comment by james-d-mitchell** [comment]
How so?

**Comment by stevelinton** [comment]
Unfortunately you have to install a lot of methods specifically for the empty list in situations like this. This is a place where GAPs lack of static typing really hurts us. There is no way to tell what kind of elements any empty doesn't contain any of :-). Is a list with no ints or no vectors (and if so of what length over what field)?

**Comment by james-d-mitchell** [comment]
Yes, I see what you mean.

**Comment by markuspf** [comment]
This should be fixed by #66 as per the fix suggested by @james-d-mitchell

**Comment by fingolfin** [comment]
It was only fixed in hpcgap, though, I can trigger a segfault in master with this code snippet:
```
LoadPackage("orb");
S := Semigroup(PartialPerm([]));
for i in [1..10] do o := Orb(GeneratorsOfSemigroup(S), [1], OnSets);Enumerate(o);AsList(o); od;
```

**Comment by alex-konovalov** [comment]
I've just cherry-picked this onto master and stable-4.7 branches.
