### ISSUE TITLE
2nd argument of GaloisType

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#551]
Does anyone know the meaning of the 2nd argument of `GaloisType` (see line 28 in https://github.com/gap-system/gap/blob/master/lib/galois.gd)? It is not documented there.

**Comment by hungaborhorvath** [comment]
This probably will not help much, but lines 801-805 of galois.gi are the following: 

````
if Length(arg)=1 then
    cand:=[1..TRANSLENGTHS[n]];
  else
    cand:=arg[2];
  fi;
````

I have no idea what ````TRANSLENGTH```` is, but ````cand```` seems to be some placeholder where possible candidates can be given. At least that was my impression of reading the code further.

**Comment by stevelinton** [comment]
Suggests that you can restrict the range of transitive permutation groups that will be considered as possible Galois groups

**Comment by hulpke** [comment]
That is exactly right. Not documented because it is somewhat experimental and can lead to wrong results.

**Comment by alex-konovalov** [comment]
@hulpke thanks - but it is documented because the 2nd argument is mentioned in the manual as optional:
```
 <Func Name="GaloisType" Arg='f[,cand]'/>
```
Perhaps we change this to `Arg='f'` then.

**Comment by hulpke** [comment]
I wonder whether the documentation happened semi-automatical when moving to GAPdoc format.

**Comment by alex-konovalov** [comment]
@hulpke: No - GAP 4.4.12 manual has `GaloisType( f[, cand] )` as well.

**Comment by alex-konovalov** [comment]
Updated documentation and left a comment in the code in https://github.com/gap-system/gap/commit/7143f105497a966d4fd7115724e1a1e7e64b4900
