### ISSUE TITLE
atlasrep test suite failures with current GAP master

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5538]
Due to some recent changes on GAP master, the `atlasrep` test suite is failing, as can be seen on the package distribution. Since there is no `atlasrep` issue tracker, I am posting it here.

For an example, see e.g. [here](https://github.com/gap-system/PackageDistro/actions/runs/7108396024/job/19352204258):
```
...
########> Diff in /home/runner/gap/pkg/atlasrep-2.1.7/tst/docxpl2.tst:72
# Input is:
NrMovedPoints( Image( hom ) );
# Expected output:
1540
# But found:
266
########
docxpl2.tst
msecs: 25408
atlasrep.tst
msecs: 27121
########> Diff in /home/runner/gap/pkg/atlasrep-2.1.7/tst/docxpl2.tst:72
# Input is:
NrMovedPoints( Image( hom ) );
# Expected output:
1540
# But found:
266
########
docxpl2.tst
msecs: 20327
...
```

**Comment by hulpke** [comment]
The number 1540 is the result of `SmallerDegreePermutationRepresentation`, called on a subgroup. This function now produces a better result, so the test file needs to be changed.

(I actually recommend against checking for the actual degree, as other changes might affect it again.)

**Comment by ThomasBreuer** [comment]
O. k., I will remove this example.

Its purpose was to demonstrate that `SmallerDegreePermutationRepresentation` cannot be expected to find a representation of smallest possible degree.
This had been the case for several years.
Before that time, the result used to be minimal.

(The funny thing is that I get degree 1540 when I run just the example in a GAP session.
Degree 266 appears only in the context of the whole test file.
I guess that many random computations occur inside.)

**Comment by hulpke** [comment]
Yes, there is some random search in reducing the permutation degree, as well as a slightly better estimates in what is a good enough degree,

**Comment by ThomasBreuer** [comment]
Just for the record: Today I have released a new AtlasRep version.

**Comment by fingolfin** [comment]
Yes, thank you, and it fixes the failure in the package distro CI tests, which are now 100% green again, yay!
