### ISSUE TITLE
xmod test suite fails with current GAP master

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5539]
Due to some recent changes on GAP master, the `xmod` test suite is failing, as can be seen on the package distribution. The change seems to be related to recent changes in the double coset code. I can't tell if the cause is a regression in the DC code; or whether they simply exposed an existing bug in `xmod`. I hope @hulpke and @cdwensley can figure it out.

For an example test log [see here](https://github.com/gap-system/PackageDistro/actions/runs/7108396024/job/19352233371). It is also easy to trigger interactively:
```
gap> LoadPackage("xmod", false);
gap> AllXMods( 36 );;
Error, Action not well-defined. See the manual section
``Action on canonical representatives''. at /Users/mhorn/Projekte/GAP/gap/lib/oprt.gd:441 called from
TestIdentityAction( acts, pnt, act ) at /Users/mhorn/Projekte/GAP/gap/lib/oprt.gd:834 called from
Orbit( lst, One( st ), function ( rep, g )
      return CanonicalRightCosetElement( st, rep * g );
  end ) at /Users/mhorn/Projekte/GAP/gap/lib/csetgrp.gi:1426 called from
DoubleCosetRepsAndSizes( G, C, D ) at /Users/mhorn/Projekte/GAP/gap/lib/morpheus.gi:1220 called from
MorClassOrbs( range, cenis[i], reps[i], cen[i + 1]
 ) at /Users/mhorn/Projekte/GAP/gap/lib/morpheus.gi:1521 called from
MorClassLoop( G, bi, params, 9 ) at /Users/mhorn/Projekte/GAP/gap/lib/teaching.g:1023 called from
...  at *stdin*:2
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk>
```

**Comment by hulpke** [comment]
Is there any chance to isolate out the library calculation? It is a pain having to install xmod with all its dependencies.

**Comment by cdwensley** [comment]
Leave it to me - I'll have a look tomorrow and add comments/questions here if I'm stuck.

**Comment by cdwensley** [comment]
Recomipled, and still fails with: GAP 4.8.8-8987-g9a21937-dirty built on 2023-12-07 18:00:11+0000

**Comment by hulpke** [comment]
Thank you @cdwensley   This made it easy to identify the issue (which is because of mapping into a group handled by a nice monomorphism)
