### ISSUE TITLE
Nonzero exit code when lib/init.g is missing

### ISSUE THREAD

**Issue by orlitzky** [gap-system/gap#5541]
I noticed this while trying to automate some tests:

```
$ gap -l "nope"
gap: hmm, I cannot find 'lib/init.g' maybe use option '-l <gaproot>'?
$ echo $?
0
```

Of course I'm not _trying_ to pass junk as the root path, but if it winds up there, the subsequent GAP run should fail as far as the terminal is concerned.

There are a few related issues open but none that I think qualifies as a duplicate:

* https://github.com/gap-system/gap/issues/436
* https://github.com/gap-system/gap/issues/4662

**Comment by fingolfin** [comment]
Agreed, this should give a non-zero exit code. And yeah it is not a dup of the other issues, it involves quite different code (and is as such either to fix).

Alas, weirdly enough, right now with `master` `./gap -l nope` produces NO OUTPUT at all, which looks like a regression to me. I do get a message with 4.12.2 and older versions

**Comment by fingolfin** [comment]
Bisected to b0ba728dd001207df5dd306538f7b50ee4cb21d8. I'll submit a fix for both.
