### ISSUE TITLE
```SmallGeneratingSet``` throws error on matrix group

### ISSUE THREAD

**Issue by schnellecom** [gap-system/gap#5542]
### Observed behaviour
Throws an error on the following setup:
```
g:=Group([ [[0,1,0], [-1,0,-2], [0,0,1]] , [[0,-1,0], [1,0,2], [0,0,1]] , [[-1,0,0], [0,-1,0], [0,0,1]] ]);
SmallGeneratingSet(g);
```
![image](https://github.com/gap-system/gap/assets/33157020/2ff8f7af-a2db-42ff-8377-6690e4f0bca5)

### Expected behaviour
Returning a small generating set (possibly even the same) for the group ```g```

### Copy and paste GAP banner (to tell us about your setup)
```
gap
 ┌───────┐   GAP 4.12.2 of 2022-12-18
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN, readline
 Loading the library and packages ...
 Packages:   AtlasRep 2.1.6, AttributeScheduler 2019.12.05, AutoDoc 2022.10.20, Browse 1.8.19, CTblLib 1.3.4,
             datastructures 0.3.0, Digraphs 1.6.1, FactInt 1.6.3, FGA 1.4.0, Forms 1.2.9, GAPDoc 1.6.6, genss 1.6.8,
             GRAPE 4.9.0, IO 4.8.0, NautyTracesInterface 0.2, orb 4.9.0, PrimGrp 3.4.3, recog 1.4.2,
             SimplicialSurfaces 0.6, SmallGrp 1.5.1, SpinSym 1.5.2, TomLib 1.2.9, TransGrp 3.6.3, utils 0.81
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by hulpke** [comment]
This is an infinite matrix group, so how would this be supposed to work?

The only issue could be to have a nicer catch for this case, there are probably many other such situations.

**Comment by schnellecom** [comment]
Good point, I didn't think about how it could even work mathematically. 
Would it be better if there was something in the documentation or it would just return the original set? Not sure if this is a valid use case but I maybe if someone iterates over a set of generators and tries to reduce them it could be annoying to just get an error.

**Comment by hulpke** [comment]
There are really two questions here:
- Should the existing method be subject to extra conditions? (`IsFinite`, `CanEasilyTestMembership` would be potential candidates, even though the method is more general)
- Should there be a fallback method for `SmallGeneratingSet` that simply returns the existing generators.

**Comment by Stefan-Kohl** [comment]
I think that even a very basic method which only tries to eliminate generators which are easily seen to be redundant could be useful. For example, such method would remove the identity and duplicate generators, generators which are inverses of other generators and generators which are products of two (or a few) other generators and / or inverses of other generators. Such method would not need to require much more than CanEasilyCompareElements.

**Comment by ThomasBreuer** [comment]
@ahulpke I think that having one generic method `SMALLGENERATINGSETGENERIC` is fine.
There are already case distinctions inside this function, depending on known (in)finiteness and `CanComputeSizeAnySubgroup`.

Thus I think it would be a good solution to rearrange this function, as follows.
1. Unconditionally try the obvious possible omissions mentioned by @Stefan-Kohl.
2. If `CanEasilyTestMembership` holds for the group then test for each generator whether it is contained in the group generated by the other generators.

Or perhaps restrict step 1. to the case that `CanEasilyCompareElements` holds for the group?
If one thinks about finitely presented groups then checking an element for being the identity might still cause an error message.

I am not sure how far we want to go; note that the nontrivial example given by Stefan in #5790 deals with a group in `IsRcwaGroupOverZ`, which is not in `CanEasilyCompareElements`. (Would it be reasonable to set this filter?)

**Comment by Stefan-Kohl** [comment]
@ThomasBreuer In the example I gave, setting the filter `CanEasilyTestMembership` would not be reasonable, as in general, the membership problem for groups in `IsRcwaGroupOverZ` is algorithmically unsolvable (this is an immediate consequence of the existence of groups in `IsRcwaGroupOverZ` which are isomorphic to the direct product of two free groups of rank 2). But in practice, nevertheless in many, many cases membership can be decided easily, so making `CanEasilyTestMembership` a requirement would make the method much less useful. What I suggest is ideally a membership test with a timeout (if that is reasonably possible) or alternatively the computation of balls up to a certain radius to check whether they intersect. There could be either an option or an additional argument to specify the timeout respectively the search radius.

**Comment by ChrisJefferson** [comment]
Unfortunately, it is not possible for GAP to run a method with a timeout (there used to be, but it was removed as it caused too many bugs).

We could hypothetically add a new `TryTestMembership` method, which groups can use to try for a while but give up if they take too long, but that would be a fairly significant new bunch of code, and I'm not sure it would be that generally useful.
