### ISSUE TITLE
Clean up or extend TNUM space

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#555]

**Comment by fingolfin** [comment]
I think this is essentially done for now (the TNUM space is now quite cleanly organized), resp. in progress (e.g. if we can get rid of `IMMUTABLE` as part of the TNUM, this will free up a lot; similar for COPYING).

So closing this for now. But perhaps you had something else in mind for this issue -- if so, of course you can reopen, but then perhaps clarify what the intention is?
