### ISSUE TITLE
strange behaviour of `Test` in the master branch

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5552]
Consider the following two test files.

**file test1.tst**
```
gap> SizeScreen( [ 72 ] );;
gap> START_TEST("test1.tst");;
gap> SizeScreen()[1];
72
gap> true;  # a test that passes
true
gap> SizeScreen()[1];
72
gap> STOP_TEST("test1.tst");;
```

**file test2.tst**
```
gap> SizeScreen( [ 72 ] );;
gap> START_TEST( "test2.tst" );;
gap> SizeScreen()[1];
72
gap> true;  # a test that fails
false
gap> SizeScreen()[1];
72
gap> STOP_TEST( "test2.tst" );;
```

In GAP 4.12.2, we get the following.
```
gap> Test("test1.tst");
test1.tst                           
msecs: 0
true
gap> Test("test2.tst");
########> Diff in test2.tst:5       
# Input is:
true;  # a test that fails
# Expected output:
false
# But found:
true
########
test2.tst
msecs: 0
false
```
This is fine: No error is reported for `test1.tst`, and the failing test is reported for `test2.tst`.

The current master branch behaves differently:
```
gap> Test("test1.tst");
test1.tst                           
msecs: 0
true                                
gap> Test("test2.tst");
########> Diff in test2.tst:5       
# Input is:
true;  # a test that fails
# Expected output:
false
# But found:
true
########
########> Diff in test2.tst:7       
# Input is:
SizeScreen()[1];
# Expected output:
72
# But found:
80
########
test2.tst                           
msecs: 1
false
```

Here the failure in `test2.tst` is reported, which is good.
However, afterwards the line length has apparently been set to 80. Why?

Note that the effect is that after this first failed test, failures will be reported for all outputs that depend on the line length, no matter whether these outputs are correct (w.r.t. the intended line length) or not.

I think the behaviour in GAP 4.12.2 was better.

**Comment by ThomasBreuer** [comment]
Now I understand what happened. #5210 introduces that differences are reported as soon es they are detected. For showing the differences, the line length is temporarily set to the line length before the start of the tests, and afterwards it is set back to "the line length intended for the tests" (with default 80).

This conflicts with my idea that the test code may contain calls to `SizeScreen`, in order to set the line length.
(Yes, one can set a default line length in the optional argument of `Test`, but I think that logically, setting the line length is better part of the test file, not part of the `Test` call. I am thinking mainly about files that serve as documentation of computations, such as tutorials, which can be checked with `Test`.)

I will provide a pull request that solves the problem.

**Comment by ChrisJefferson** [comment]
Thanks, that case didn't occur to me when I wrote that code. If you have trouble with the PR let me know, as I broke it.
