### ISSUE TITLE
Cannot load saved workspace

### ISSUE THREAD

**Issue by egri-nagy** [gap-system/gap#556]
When trying to load a saved workspace I get the

Floating point  exception (core dumped)

error message. I use system gmp on ubuntu and I did not pull changes and recompile before trying to load the saved image. I used to get this message often with different versions, most recently with v4.8.1-g4851f0d.
I haven't investigated the issue, and I hope you might know immediately what's going on.
Thanks!

**Comment by ChrisJefferson** [comment]
Can you give an example of a complete list of GAP command you use, and GAP's output (so we can see which packages you have saved/loaded).

Also (just in case you are trying to do this), saving a workspace on one git version of GAP, and then trying to load it on another git version of GAP, is likely to go badly (in fact, I don't think we currently check if users are trying to do that. We should check, and reject).

**Comment by egri-nagy** [comment]
Yes, I agree that different git versions should reject reloading workspaces. I thought even recompiling the same GAP version invalidates saved workspaces. 

However, this time it was very easy to recreate the problem. In one go:
```
kvadpancs:~/GAP/pkg/SUBSEMI$ gap
┌───────┐   GAP v4.8.1-207-g606200a of 2016-01-30 21:04:53 (AEDT)
│  GAP  │   http://www.gap-system.org
└───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
Libs used:  gmp, readline
Loading the library and packages ...
No need to patch HASH_FUNC_FOR_BLIST.
Error, Variable: 'SEMIGROUPS' must have a value
not in any function at line 5 of /home/sirna/.gap/gaprc
Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
Packages:   biogap 0.2.4, GAPDoc 1.5.1, genss 1.6.2, GRAPE 4.6.1, IO 4.4.4, orb 4.7.5, Semigroups 2.8, SgpDec 0.7.32, Smallsemi 0.6.9, SubSemi 0.71
Try '?help' for help. See also  '?copyright' and  '?authors'
gap> SaveWorkspace("x.ws");
true
gap> 
kvadpancs:~/GAP/pkg/SUBSEMI$ gap -L x.ws 
Floating point exception
```

**Comment by stevelinton** [comment]
Could you try with gap -r to suppress your personal configuration.

That is 

gap -r
....
gap> SaveWorkspace("x,ws");

gap -r -L x,ws

**Comment by egri-nagy** [comment]
Playing with gap -r and trying to load packages incrementally, it turns out that the Semigroups package triggers the exception. I'll create the issue for the package, but keep this one open until we figure out what goes wrong.

**Comment by ChrisJefferson** [comment]
Can I ask where you got semigroups 2.8 from? I assume it's a dev branch -- wondering which one? (The latest released version seems to be 2.7.2)

**Comment by egri-nagy** [comment]
hg up 2.7.1-release 
gave me that. I assume this was a typo. 

Yes, I've just tried 2.7.2, and I have the same problem.

**Comment by ChrisJefferson** [comment]
OK, so I've just tried the following on a 64-bit ubuntu 15.10.

* Get gap head. Run `./configure --with-gmp=system; make; make bootstrap-pkg-full`.
* Replace io, orb and semigroups with most recent versions, and build both io and orb (semigroups doesn't have any C code in 2.7.2).

I then try various combinations of loading gap with/without -r, loading semigroups, saving workspace then loading it back in, but none of them seems to crash.

This kind of bug has an annoying habit of being very sensitive to user configuration, so if you could find some instructions (preferably from an empty directory) which make a gap which crashes (and also say if you are on 64/32-bit ubuntu, and which version), that would be very helpful in reproducing it!

Alternatively, I could give you instructions for trying to debug on your machine.

**Comment by james-d-mitchell** [comment]
I guess that @egri-nagy is using the hg repo of the Semigroups package and:

- has compiled the kernel module of the next major release (which is still only very partially developed, and is probably not safe with respect to loading and saving workspaces, and many other things)
- has not deleted the kernel module
- has updated to the commit in the Semigroups repo containing the release of version 2.7.2
- has loaded GAP and this is causing the problem. 

@egri-nagy mentioned to me once before that he could load functions in the kernel module of the next major release of Semigroups after having compiled it, and then switching to the release version in the hg repo, and loading GAP. I.e. the function `SEMIGROUPS_KERNEL_FOO` is a C function in the kernel module for a version of the Semigroups package (not released only in the repo), then after switching to a version of the Semigroup repo which does not have a kernel module and where no function named `SEMIGROUPS_KERNEL_FOO` is defined, loading GAP, and still having the function `SEMIGROUPS_KERNEL_FOO` available. Obviously the build files, and executables are not managed in the repository and so they are still there even when the repository is updated to a branch which has no kernel module. 

This is what I guess is going on here.

**Comment by james-d-mitchell** [comment]
Also, I don't know where version 2.8 of Semigroups is coming from, there is a closed branch with that version number, but none of the release versions nor tags corresponds has version 2.8 in the package info file.

**Comment by egri-nagy** [comment]
I did make clean in the Semigroups folder for the dev branch, then switched to the released version. So nothing is compiled for Semigroups. 

I used to use that `trick' at some point to get a kernel hash function accidentally, but when I realized what was going on, I stopped that.

**Comment by james-d-mitchell** [comment]
`make clean` does not delete the executables, so I still think this is the problem.

**Comment by egri-nagy** [comment]
yep, that's it. I removed the bin/ folder from semigroups and the problem is gone. Thanks!

Is there a reason why ```make clean``` leaves the executables?
