### ISSUE TITLE
regression in conjugacy tests for permutation groups?

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5564]
The GAP input shown below needs about 11 seconds time and less than 200 MB space in GAP 4.12.2.
With the current master branch version, the default upper bound of 2 GB for the space is reached after 35 seconds.
If I do not prescribe this bound then the master branch version grows to 6 GB after 10 minutes, and still has not finished.

```
q:= 4;;  n:= 8;;
G:= DerivedSubgroup( SO( 1, n, q ) );;
points:= NormedRowVectors( GF(q)^n );;
orbs:= OrbitsDomain( G, points, OnLines );;
G:= Image( ActionHomomorphism( G, orbs[1], OnLines ) );;
repeat x:= Random( G ); until Order( x ) mod 13 = 0;
x:= x^( Order( x ) / 13 );;
c:= Centralizer( G, x );;
syl5:= SylowSubgroup( c, 5 );;
elms:= Filtered( Elements( syl5 ), y -> Order( y ) = 5 );;
reps:= Set( elms, SmallestGeneratorPerm );;
reps65:= List( reps, y -> SubgroupNC( G, [ y * x ] ) );;
pairs:= Combinations( reps65, 2 );;
res:= ForAny( pairs, p -> IsConjugate( G, p[1], p[2] ) );
```

**Comment by hulpke** [comment]
Ah, for many short orbits the new code is inefficient, and cyclic subgroups actually are handled specially by the backtrack. I have corrected this.

**Comment by fingolfin** [comment]
@hulpke it seems you have a potential fix ready, would you submit it as a PR?
