### ISSUE TITLE
`KnowsHowToDecompose` with 2-arguments never uses the 2nd argument

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#5586]
In GAP `master` and `4.12.2` there is the property and 2 argument operation:

https://github.com/gap-system/gap/blob/9d3fdea2d3cebe20cb2469c4e8da7a730c0bee3f/lib/grp.gd#L409-L410

The property is used in a bunch of places, but the 2 argument operation isn't used anywhere in the GAP repo or any packages (at least in the 4.12.2 release archive). The only installed method for the operation `KnowsHowToDecompose` is:

https://github.com/gap-system/gap/blob/9d3fdea2d3cebe20cb2469c4e8da7a730c0bee3f/lib/grp.gi#L5562-L5570

which doesn't use the 2nd argument. Should we remove the operation with 2 arguments?

**Comment by james-d-mitchell** [comment]
> `KnowsHowToDecompose` is documented in the manual as having either 1 or 2 arguments. And the two argument version does seem useful?
> 
> Moreover:
> 
> ```gap
> gap> Length(MethodsOperation(KnowsHowToDecompose, 2));
> 7
> ```
> 
> So I am not quite sure why you think there i sjust one method for it on two arguments?

So, if you actually look at the methods in the library for `KnowsHowToDecompose` you see that they are:

~~~
InstallMethod( KnowsHowToDecompose, "matrix groups",
        [ IsMatrixGroup, IsList ], ReturnFalse );

InstallMethod( KnowsHowToDecompose,
    "pc group and generators: always true",
    IsIdenticalObj,
    [ IsPcGroup, IsList ], 0,
    ReturnTrue);

InstallMethod(KnowsHowToDecompose,
    "perm group and generators: always true",
    IsIdenticalObj,
    [ IsPermGroup, IsList ],
    ReturnTrue);

InstallMethod( KnowsHowToDecompose,"generic: just groups of order < 1000",
    IsIdenticalObj, [ IsGroup, IsList ],
function(G,l)
  if CanComputeSize(G) then
    return Size(G)<1000;
  else
    return false;
  fi;
end);

InstallOtherMethod( KnowsHowToDecompose,"trivial group",true,
  [IsGroup,IsEmpty], ReturnTrue);

InstallMethod( KnowsHowToDecompose,
    "group: use GeneratorsOfGroup",
    [ IsGroup ],
    G -> KnowsHowToDecompose( G, GeneratorsOfGroup( G ) ) );

InstallMethod( KnowsHowToDecompose,"fp groups: Say yes if finite index",
    IsIdenticalObj, [ IsSubgroupFpGroup, IsList ], 0,
function(G,l)
  return CanComputeIndex(FamilyObj(G)!.wholeGroup,G)
         and IndexInWholeGroup(G)<infinity;
end);
~~~

and as I previously claimed, none of them uses the second argument. Perhaps this isn't a good reason to get rid of the 2 argument version.

**Comment by fingolfin** [comment]
Yes it is not a good reason because while these groups can either do it for all or for no generator list, there are conceivably group types where it is more complicated. 

And eg the fp group could be improved to check if the given set is the "canonical" generating set (or a permutation thereof) in which case it could just immediately return `true`
