### ISSUE TITLE
[Question] Build in pkg/simpcomp fails intermittently: is this build needed?

### ISSUE THREAD

**Issue by yurivict** [gap-system/gap#5599]
I am the maintainer of the math/gap port on FreeBSD.

For some reason we have this extra build step after the main build finishes:
```
post-build:
        @echo "build in pkg/simpcomp"
        @cd ${WRKSRC}/pkg/simpcomp && \
                ${SETENV} ${CONFIGURE_ENV} ${SH} configure \
                        ${CONFIGURE_ARGS:N--with-*} && \
                ${MAKE} ${MAKEFLAGS} && \
                ${MAKE} ${MAKEFLAGS} install-strip && \
                ${MAKE} ${MAKEFLAGS} distclean
```

This step installs just one extra file: /usr/local/share/gap/pkg/simpcomp/bin/bistellar.
There are a lot of other files installed under /usr/local/share/gap/pkg/simpcomp by the main build step, just not bin/bistellar.

I don't know why this build step was added - there are no comments in the code.

I have these questions:
* What is bin/bistellar? 
* Why is it not installed by the main build but the specific build in pkg/simpcomp installs it?

Version: 4.12.2

Thank you,
Yuri

**Comment by fingolfin** [comment]
`bin/bistellar` is an external executable used by the `simpcomp` package for some computations jobs.

As to why it wasn't "installed" by the "main build": neither we nor any GAP packages provide (as far as I know) any official way for "installing" a package. To quote `INSTALL.md`:

> Note also that `make install` at this
time only installs GAP itself; GAP packages still must be installed manually
(which in many cases just means copying them into a suitable directory, e.g.
`<GAPPREFIX>/share/gap/pkg/` -- we are still working on a good solution for
packages that require compilation).

So I am not sure what exactly you are referring to? Any code for installing GAP packages must be specific to your setup for the FreeBSD packages, so I guess you'd have to ask yourself... ? ;-)

That leaves me guessing... Perhaps you are using our `bin/BuildPackage.sh` script to build packages, and your question is really about that tool? But that definitely ends up building `bin/bistellar` for me.

**Comment by fingolfin** [comment]
Also, you write in the headline of this issue that it "fails intermittently" -- what exactly do you mean by that? What kind of failure?

**Comment by yurivict** [comment]
The failures during the above extra build step is what attracted my attention. They are intermittent:
```
gmake[1]: Leaving directory '/wrkdirs/usr/ports/math/gap/work/gap-4.12.2'
configure: loading site script /usr/ports/Templates/config.site
checking for a BSD-compatible install... (cached) /usr/bin/install
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... (cached) /bin/mkdir -p
checking for gawk... (cached) /usr/bin/awk
checking whether gmake sets $(MAKE)... yes
checking whether gmake supports nested variables... yes
checking for c++... c++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether c++ accepts -g... yes 
checking for style of include used by gmake... GNU
checking dependency style of c++... gcc3
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
 cd . && /bin/sh /wrkdirs/usr/ports/math/gap/work/gap-4.12.2/pkg/simpcomp/missing automake-1.16 --foreign
aclocal.m4:17: warning: this file was generated for autoconf 2.69.
You have another version of autoconf.  It may work, but is not guaranteed to.
If you have problems, you may need to regenerate the build system entirely.
To do so, use the procedure documented by the package, typically 'autoreconf'.
configure.ac:3: error: version mismatch.  This is Automake 1.16.5,
configure.ac:3: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:3: comes from Automake 1.15.1.  You should recreate
configure.ac:3: aclocal.m4 with aclocal and run automake again.
WARNING: 'automake-1.16' is probably too old.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
*** Error code 1
```

**Comment by yurivict** [comment]
The main build is done as for all other GNU based projects: ```./configure && make```.

Then this extra step runs ```./configure && make && make install-strip``` in ```pkg/simpcomp```.
So it is installed first.

Then ```make install``` is run from the main project.

And the result ends up having 1 extra file: bin/bistellar.

It's confusing for why isn't bin/bistellar installed during ```./configure && make && make install```.

**Comment by yurivict** [comment]
No, we don't use ```bin/BuildPackages.sh```.

**Comment by yurivict** [comment]
We need to understand what exactly is missing when the standard ```./configure && make && make install``` is used.

This is what we do in the FreeBSD port.

Do you have any files missing when you do this instead of ```bin/BuildPackages.sh```?

**Comment by ChrisJefferson** [comment]
When you say "intermitant failure", I guess it fails on some people's computers and not others, based on the errors based on autoconf and automake versions?

We don't support, in general, running `make install` in packages. We never have, and possibly never will. When you say "There are a lot of other files installed under /usr/local/share/gap/pkg/simpcomp by the main build step", I don't know what the "main build step" is, as I don't think it's part of GAP itself?

**Comment by yurivict** [comment]
> When you say "intermitant failure", I guess it fails on some people's computers and not others ...

It fails on the same computers for the same people intermittently. When I build it 10 times, it would fail like 1-3 times.

> [...] I don't know what the "main build step" is [...]

It is ```./configure && make && make install```.

We would like to only do this, but I am trying to figure out why does it not install ```bin/bistellar```  and what is the difference between ```./configure && make && make install``` and running ```bin/BuildPackages.sh```.

**Comment by ChrisJefferson** [comment]
So, to be clear, we do not run `make install` for packages. We don't recommend it, I have no idea what it will do, and `bin/BuildPackages.sh` doesn't do it.

I am fairly sure the only fully official and supported way to run GAP is to build GAP and all it's packages, and then use it in place, no `install` required, and GAP and all it's packages live in one directory. I realise this isn't what distributions want, and various distributions do package GAP in such a way it fits more neatly into traditional directory structures (you could look at debian for inspiration for example).

In the latest version of GAP, all ../bin/BuildPackages.sh does is run `./configure && gmake clean && gmake` (the clean, and gmake vs make, are quite possibly not necessary here, but we try to use the same way of building all packages)

**Comment by yurivict** [comment]
@ChrisJefferson 

> I am fairly sure the only fully official and supported way to run GAP is to build GAP and all it's packages, and then use it in place, no install required [...]

These days all software packages need to be installed in a packaged way. Users can't be building them manually.

16 different packaging systems install GAP for users: https://repology.org/project/gap/versions

I recommend that the GAP upstream officially supports GAP being installed, because that's what users obviously want.

**Comment by fingolfin** [comment]
I'll quote `INSTALL.md` again, please read it carefully:

> Note that starting with GAP 4.12, there is experimental support for installing
GAP via `make install`. By default this attempts to install GAP into the
`/usr` prefix, but this can be adjusted via the `--prefix` option for
`configure`. This feature is still quite new and has not received extensive
testing yet, and we mainly recommend it for use by people who wish to package
GAP for a Linux distribution or similar. Note also that `make install` at this
time only installs GAP itself; GAP packages still must be installed manually
(which in many cases just means copying them into a suitable directory, e.g.
`<GAPPREFIX>/share/gap/pkg/` -- we are still working on a good solution for
packages that require compilation).



I.e., we have been *hard* at work making `make install` work, it wasn't easy, and it doesn't cover packages. One of the reasons is that the 16 different packaging systems you cite all have quite different views of how things ought to be installed, and some of them like to make up additional rules. And on the other hand GAP packages have their own authors and also sometimes do "special" things. There is no simple solution.

As such, statements like this really are not helpful:
> I recommend that the GAP upstream should officially support GAP being installed, because that's what users obviously want.

It's like telling a sports team "just score more points than your opponent and you'll win". Well, yes, d'oh, of course. But it's easier said than done.

Note that most packagers seem to manage installing the package just fine, after reading the text I quoted above and some experiments, perhaps sometimes with a little help from us. We (well, *me*) have also been quite proactive about trying to talk to them and make things work smoother.

As a matter of fact, I emailed you about this specific matter (simpcomp being the only package that gets compiled by FreeBSD) on 20 December 2022 but never got a reply.
