### ISSUE TITLE
Support for user CFLAGS and LDFLAGS in gac?

### ISSUE THREAD

**Issue by orlitzky** [gap-system/gap#5601]
Originally reported as https://bugs.gentoo.org/922705

Gentoo packages should try to respect the user's `CFLAGS` and `LDFLAGS` where possible. Would it be reasonable to do so here?

The first thing that comes to mind would be to either prepend or append `CFLAGS`/`LDFLAGS` from the environment to the compile and link commands in gac. But I'm not sure how sensitive GAP kernel modules are to these flags. If it's essentially guaranteed to cause problems, I can just WONTFIX the bugs. But if it's possible to (say) compile a kernel module at a higher optimization level than GAP itself, or if it's possible to use a different linker to link the module (via `LDFLAGS`), then that would be nice to have as an option.

**Comment by fingolfin** [comment]
Looking at the linked bug report report, you are talking about the build system of the EDIM package. But this here is the bug tracker for GAP. Issues with the EDIM package should be reported to its maintainer.

I don't think this is an issue with `gac`: think of it as a compiler like `gcc` or `clang`. And you don't expect them to handle `CFLAGS` or `LDFLAGS`, rather the build system calling them should do so.

Indeed GAP packages using `Makefile.gappkg` do so (or at least should). 

As such, I think this is an issue you'll have to raise with the EDIM maintainer directly, i.e. @frankluebeck

**Comment by orlitzky** [comment]
> Looking at the linked bug report report, you are talking about the build system of the EDIM package. But this here is the bug tracker for GAP. Issues with the EDIM package should be reported to its maintainer.
> 
> I don't think this is an issue with `gac`: think of it as a compiler like `gcc` or `clang`. And you don't expect them to handle `CFLAGS` or `LDFLAGS`, rather the build system calling them should do so.
> 
> Indeed GAP packages using `Makefile.gappkg` do so (or at least should).
> 
> As such, I think this is an issue you'll have to raise with the EDIM maintainer directly, i.e. @frankluebeck

Ok, thanks, I just wanted to be sure before I started changing things. Sorry for all the noise lately. Day one with 60+ new packages was bound to be chaos.
