### ISSUE TITLE
Support for CC changes in gac

### ISSUE THREAD

**Issue by orlitzky** [gap-system/gap#5606]
Next down the line: if I build GAP with `CC=clang-16`, that value gets stored in `sysinfo.gap`...

```
$ grep clang /usr/lib64/gap/sysinfo.gap 
GAP_CC="clang-16 "
GAP_CXX="clang++-16 -std=gnu++11 "
```

which is used by gac from then on:

```
$ grep CC /usr/bin/gac
c_compiler="${GAP_CC}"
c_dyn_linker="${GAP_CC}"
```

But, if I later upgrade to clang-17 (removing clang-16), further package builds will fail. This happens every few months on Gentoo so is not really a rare event.

What's the best way to support those types of changes in compiler? I'm willing to hack `gac` to say e.g. `c_compiler="${CC}"` but maybe there's a better way that will work for everyone?

**Comment by ChrisJefferson** [comment]
Couldn't you just build GAP with `clang`, if you want it to always use the latest version you have installed?

**Comment by orlitzky** [comment]
To be honest that's not really what I want, it just makes for an easy example and was how I discovered the issue. The goal is to make it robust for other users who will change `CC` for arcane and unknowable reasons, both in and out of their control. For example, uninstalling clang entirely on a system with GCC is a plausible scenario.

**Comment by ChrisJefferson** [comment]
So, the reason this is here at all (just for some background, sorry if this is obvious) is that some people have incompatible compilers, classic examples include cross-compilers (32bit vs 64bit), also super-common on windows, it's important we use the same cygwin compiler (as opposed to picking up a mingw compiler or some such) to compile gap and kernel modules.

One possibility would be for gac to use ${CC} and friends if they are defined, and use the saved value if not? That seems initially reasonable to me (might be an issue I'm not thinking about).

**Comment by orlitzky** [comment]
> So, the reason this is here at all (just for some background, sorry if this is obvious) is that some people have incompatible compilers, classic examples include cross-compilers (32bit vs 64bit), also super-common on windows, it's important we use the same cygwin compiler (as opposed to picking up a mingw compiler or some such) to compile gap and kernel modules.

Understood. While it's our policy to make such things possible where possible, it does lead to some silly bugs. I don't blame you for trying to avoid them.

> One possibility would be for gac to use ${CC} and friends if they are defined, and use the saved value if not? That seems initially reasonable to me (might be an issue I'm not thinking about).

I think that would work for us. If no one else objects, I could try it out to be sure.
