### ISSUE TITLE
OctaveAlgebra generators don't show expected behaviour

### ISSUE THREAD

**Issue by qodesign** [gap-system/gap#5610]
The multiplication table of the Octonion algebra (OctaveAlgebra) doesn't match
the usual definitions where the squares of the generators are 1 or -1 :

### Observed behaviour
```
alg:=OctaveAlgebra(Rationals);
gen:=GeneratorsOfAlgebra(alg);
Print(gen,"\n");
Print(List(gen,x->x^2),"\n");
```
```
[ s1, t1, s2, t2, s3, t3, s4, t4 ]
[ s1, t1, 0*s1, 0*s1, 0*s1, 0*s1, 0*s1, 0*s1 ]
```
### Expected behaviour
```
~ [1,-1,-1,-1,-1,-1,-1,-1]
```
Maybe GAP uses a less common basis but I couldn't find a reference for the definition of s1,t1,...s4,t4

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.12.0 of 2022-08-18
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-cygwin-default64-kv8
 Configuration:  gmp 6.2.1, GASMAN, readline
 Loading the library and packages ...
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.4, AutoDoc 2022.07.10, AutPGrp 1.11, Browse 1.8.14,
             CaratInterface 2.3.4, CRISP 1.4.5, Cryst 4.1.25, CrystCat 1.1.10, CTblLib 1.3.4, FactInt 1.6.3,
             FGA 1.4.0, Forms 1.2.8, GAPDoc 1.6.6, genss 1.6.7, IO 4.7.2, IRREDSOL 1.4.3, LAGUNA 3.9.5, orb 4.8.5,
             Polenta 1.3.10, Polycyclic 2.16, PrimGrp 3.4.2, RadiRoot 2.9, recog 1.3.2, ResClasses 4.7.3,
             SmallGrp 1.5, Sophus 1.27, SpinSym 1.5.2, TomLib 1.2.9, TransGrp 3.6.3, utils 0.76
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
```

**Comment by fingolfin** [comment]
As far as I can tell @ThomasBreuer implemented this in 1997?

Anyway, while I agree that this is unusual behavior and not what I'd expect, it's being like this for almost 27 years, so I don't think we can do anything here other than augment the manual entry to explain what's going on.

**Comment by fingolfin** [comment]
Ah, looking a bit closer, this seems to the [split octonions](https://en.wikipedia.org/wiki/Split-octonion). The basis is given in hyperbolic pairs. You can get one matching (up to reordering) what the linked Wikipedia page has via
```
gap> A:=OctaveAlgebra(Rationals);
<algebra of dimension 8 over Rationals>
gap> One(A);  # verify what the neutral element looks like
s1+t1
gap> Bnew := Basis(A, [A.1+A.2, A.1-A.2, A.3+A.4, A.3-A.4, A.5+A.6, A.5-A.6, A.7+A.8, A.7-A.8]);
```
Note that three basis elements square to -1 and the others to 1.

**Comment by qodesign** [comment]
Thanks; this clears things up. I think this can now be closed.
