### ISSUE TITLE
make install should install gapmacro and friends

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#5630]
Currently `make install` does not install things from `doc/`, such as `doc/gapmacro*.tex`, `makeindex`, etc.
As they are needed by many packages for their documentation, cf. e.g. #639, it's important that `make install` takes care of this.

Distributions use  `make install` to create GAP installations in particular (e.g. SageMath, Gentoo - see #5627 ) etc.

**Comment by fingolfin** [comment]
Actually it was deliberate to not install those, the idea being that nobody should be using these files; package authors that still use them need to jump through extra hoops, but that's fine.

I guess the one reason to have this is for distro packagers who for one reason or another prefer to rebuild GAP package manuals; for them I guess this would be convenient. But is this reason enough to do it? Hm

**Comment by dimpase** [comment]
How about people who want to update a GAP package that uses these tools? E.g. I stumbled upon this issue during the latest round of working on the latest ACE update - turns out that an otherwise perfect Gentoo GAP installation is not OK for this purpose.

**Comment by fingolfin** [comment]
As was pointed out in https://github.com/gap-system/gap/discussions/5627 we actually do install all these files, I just forgot about it.

In any case: issues with packages are package issues. It is not the obligation of the core GAP team to ensure that development of individual packages that chose to use or stick with legacy technology is kept simple. We won't actively try to impede them, but in the end, it is up to each package to deal with this.

Some of these packages have listed "The GAP Team" as maintainer. Which means we'll try to merge reasonable PRs, apply certain janitorial tweaks, and take care of releases (which includes rebuilding manuals). But this does not entail conversion of the manuals to GAPDoc nor other work to make building the documentation easier for some people.

There is a trick one can use for most of these packages which I'll describe on the GH Discussion linked above, but that's about it.

**Comment by fingolfin** [comment]
Ah, but later in that discussion it is pointed out that `gapmacro.tex` is not installed. Re-opening.

**Comment by dimpase** [comment]
The problem of location of `*.tex` files can be dealt with by setting `TEXMFLOCAL` to point to whatever location `make install` is going to install them. No need to use relative paths in TeX's  `\input` commands.

I am not sure what else in `doc/` is needed for the TeX-based package manuals to build  (again, scripts can be dealt with by manipulating `PATH`).

**Comment by fingolfin** [comment]
Whatever is done, please keep in mind that the primary way of how GAP and GAP packages are developed must keep working -- and that is not using `make install`.

**Comment by dimpase** [comment]
It's matter of adjusting environment variables to point to the right places, be it the in-tree building of the package, or the package using "make install" infrastructure, or something else.

GAP's PackageManager can facilitate this.
It can get an option triggering rebuild of a package docs.

**Comment by fingolfin** [comment]
I'll happily review your PRs for all that, I laid out the ground rules.
