### ISSUE TITLE
CI: find a way to run autoconf 2.72 when creating release tarballs

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5643]
See the discussion [here](https://github.com/gap-system/gap/discussions/5627#discussioncomment-8400187) for why. In a nutshell, future GCC versions will break backwards compatibility with ancient C variants (pre-ANSI C) in a way that breaks some autoconf checks.

**Comment by james-d-mitchell** [comment]
One possible approach would be to use homebrew, there's a gh-action for that:

https://github.com/Homebrew/actions/tree/master/setup-homebrew

and then `brew install autoconf` should give version 2.72:

https://formulae.brew.sh/formula/autoconf
