### ISSUE TITLE
`Cite` command keys for package should not include versions

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5646]
Using e.g. `Cite("smallgrp")` produces
```
<entry id="SmallGrp1.5.3"><misc>
```
resp.
```
@misc{ SmallGrp1.5.3,
```
That is, it suggests keys for the bibitems that include the version number.

I always remove these. I never found them useful, and I think using them is a bad practice for most people.

Can we just drop them, or is there a deeper reason I am missing?

**Comment by ChrisJefferson** [comment]
I'm happy to drop them. I mention package versions in text, but it seems weird to put them in references. Also it ends up spreading out references for hiring committees and such like who care about H-indices and such like (they shouldn't, but they often do)
