### ISSUE TITLE
Loading GAP fails in master and stable-4.12

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#5672]
With:
~~~
Error, Variable: 'DatabaseAttributeAdd' must have a value
~~~

This is occurring in the CI for digraphs and semigroups. Haven't had the chance to figure out where this might have come from.

**Comment by ThomasBreuer** [comment]
@james-d-mitchell I know how to fix the problem by making a new release of CTblLib, but it looks as if there is a problem with the new "package extensions", concerning the order in which packages get loaded.

**Comment by james-d-mitchell** [comment]
Thanks @ThomasBreuer for the info!

**Comment by ThomasBreuer** [comment]
Now I can reproduce the problem locally, as follows:
Start GAP with the -A option and then enter
```
LoadPackage( "tomlib" : OnlyNeeded );
LoadPackage( "ctbllib" : OnlyNeeded );
```
Loading the packages in this order did apparently not occur in my tests.
I see no other way to solve this problem than a new release of CTblLib.

**Comment by ThomasBreuer** [comment]
The new CTblLib release has been noticed, see gap-system/PackageDistro/pull/923.

**Comment by fingolfin** [comment]
I've just merged the update, it'll take a few minutes for the archives to be rebuilt etc. and then this should be resolved, I hope.
