### ISSUE TITLE
regression in GAP 4.13.0, concerning `IsomorphismPermGroupOrFailFpGroup`?

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5697]
Consider the following input.
```
F:= FreeGroup(2);
gens:= GeneratorsOfGroup( F );
x:= gens[1];; y:= gens[2];;
rels:= [ y*x^-1*y^-1*x*y^-1*x^-1, x^-1*y*x*y*x^-1*y^-2 ];;
G:= F / rels;
IsomorphismPermGroupOrFailFpGroup(G, 100000);
```
In GAP 4.12.2, this yields an isomorphism.
In GAP 4.13.0 and in the current master branch, I get `fail`.

**Comment by fingolfin** [comment]
This regression was introduced by PR #5229 resp. commit df91fdb89344e71f43d88b68555193b14c059876 (ping @hulpke)

**Comment by fingolfin** [comment]
Thomas' group is just SL(2,5) in disguise:
```
gap> Size(G);
120
gap> StructureDescription(G);
"SL(2,5)"
```

**Comment by fingolfin** [comment]
Ah OK, so the coset limit is highly relevant. It works with the default `CosetTableDefaultMaxLimit`$= 4096000$  but not with Thomas' smaller limit. Nor with `CosetTableDefaultMaxLimit/10` it turns out. So 409600 cosets are not enough for this group of size 120?

**Comment by ThomasBreuer** [comment]
To be precise: The `Size` attribute of `G` is already set when `IsomorphismPermGroupOrFailFpGroup` returns `fail`. How can this happen?
