### ISSUE TITLE
`ReadPackage` should error when given an invalid path, not silently proceed

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#5745]
Consider this:
```
gap> ReadPackage("io", "dsfjsdlkfdjsfj");
false
```
I think that's really problematic behavior. Because it means that if one has a typo in a package's `init.g` or `read.g`, one may have to search for quite a bit before discovering this.

It also has other consequences: if a file is missing by accident (error copying it over, whatever), this may manifest in weird errors.

I have one setup were multiple GAP's are loaded in parallel on a multi-core machine, and a certain path goes through a symlink, and for (bad) reasons each time a new GAP is started, that symlink is recreated. I've fixed this by now (I think) but it manifested in a really confusing way: a package would load just fine, but then later calling into it, it might complain about some function not being defined... That can happen if you read the file with `DeclareGlobalFunction` but not the one with `InstallGlobalFunction`. This one confused me a lot initially because it was obvious that files both before and *after* the file with the `InstallGlobalFunction` call had been read. 

All in all, I have by now encountered (and described) multiple situations where having `ReadPackage` raise an error would be beneficial.

Can anyone name a plausible reason where the *current* behavior is preferable? (The fact that it is "documented behavior" is true but not a reason by itself, as we can always change this).

If not I'd really like to change this in 4.14 (or even before, really).

Note to anyone trying to implement this: `RereadPackage` is implemented by calling `ReadPackage` but it would be bad if `ReadPackage` raised an error, as that would leave `REREADING` in the wrong state. So implementation wise, one could either add another optional argument or an option to `ReadPackage` to make it return a bool again instead of raising an error; or one could rename `ReadPackage` into `_ReadPackage` (which would still return a bool) and then call that from both `RereadPackage` and a new `ReadPackage`.

**Comment by ChrisJefferson** [comment]
I agree this behaviour is bad, and we should change it.

If anyone asks for the current behaviour, we can add a function which provides it (I wouldn't bother adding that until anyone wants it)

**Comment by fingolfin** [comment]
I experimented with this. Turns out, as usual if one is lax about enforcing something, it gets misused, whether intentionally or accidentally *sigh*:
```
ReadPackage could not read <smallgrp>/gap/utils.gd
ReadPackage could not read <smallgrp>/gap/utils.gi
ReadPackage could not read <smallgrp>/small12/smlgp12.g
ReadPackage could not read <smallgrp>/id7/idgrp7.g
ReadPackage could not read <smallgrp>/id8/idgrp8.g
ReadPackage could not read <smallgrp>/id11/idgrp11.g
ReadPackage could not read <recog>/gap/obsolete.gi
ReadPackage could not read <cvec>/gap/matrix.gd
ReadPackage could not read <cvec>/local/calibration.eduroam-ipv4-3-0499.triple-a.uni-kl.de
ReadPackage could not read <laguna>/lib/mip.gd
ReadPackage could not read <laguna>/lib/mip.g
ReadPackage could not read <laguna>/lib/liftings.g
ReadPackage could not read <laguna>/lib/mip.gi
```
The attempts to read `utils.gi` and `utils.gd` in `smallgrp` are an accidental leftover from a cleanup in 2017. The other in `smallgrp` are due to a generic loading loop. I'll prepare a patch.


Next, `<recog>/gap/obsolete.gi` seems to be an accident.


The one in `cvec` is intentional:
```
# Now read hostname-specific calibration data:
if IsBoundGlobal("IO_gethostname") then
    CVEC_hostname := IO_gethostname();
    CVEC_calibrationfile := Concatenation("local/calibration.",
                                            CVEC_hostname);
    if CVEC_hostname <> "" then
        if ReadPackage("cvec",CVEC_calibrationfile) = true then
            Info(InfoCVec,1,"Have read host-specific calibration file ",
                    CVEC_calibrationfile);
        fi;
    fi;
fi;
```

**Comment by fingolfin** [comment]
I believe all affected packages have now been updated to resolve the issue. That said, some new issues may have crept in, and 3rd party packages may still be affected.
