### ISSUE TITLE
Build instructions do not say how to obtain necessary packages.

### ISSUE THREAD

**Issue by rokicki** [gap-system/gap#5748]
The README.buildsys.md does not indicate how to get the required packages to run GAP if you build it from the source repo.

Suggested patch:

```
diff --git a/README.buildsys.md b/README.buildsys.md
index 7da9c45..b8c6e61 100644
--- a/README.buildsys.md
+++ b/README.buildsys.md
@@ -30,6 +30,16 @@ can follow the standard procedure:
     ./configure
     make
 
+If you are building from the repository source, you will need to install
+the basic packages needed for GAP to start.  You can use
+
+    make bootstrap-pkg-minimal
+
+to get the bare minimum to run, or
+
+    make bootstrap-pkg-full
+
+to load the full normal set of GAP packages.
 
 == Overview of the files constituting the GAP build system
 
```

**Comment by fingolfin** [comment]
The `README.md` explains this. It would be out of scope for the `README.buildsys.md` which is "an overview of how the GAP build system works". Basically, the former is what you should read to build GAp, the latter is there for people would would like to modify the GAP build system.
