### ISSUE TITLE
What is the maximal degree of a permutation?

### ISSUE THREAD

**Issue by frankluebeck** [gap-system/gap#575]
Because of a typo I noticed the following:

In 32-bit GAP one runs into an error if a permutation moves a point >= 2^28, while the documention under `?IsPerm filter` tells that permutation are internally image lists for 16-bit or 32-bit integers.
(I can understand that dealing with non-immediate integers as points of a permutation would be a bit nasty, but this limitation should probably be mentioned in the documentation?)

In 64-bit GAP one runs into an error with the similar message as above for a point >=2^60. But there is no such error message for points >=2^32 and <2^60, instead one runs into a `exceeded the permitted memory` break loop. Is this a bug? Again, it would be good to document the limitation explicitly.

**Comment by stevelinton** [comment]
Obviously we should both document and check the limit. 
Is everyone OK with the limit being 2^28 or 32 bit systems? A permutation of that size fills about 1/3 of the largest possible workspace, so it doesn't seem like a harsh limit.

On 64 bit systems the limit may as well be 2^32. 

Anyone fancy pre-emptively implementing T_PERM8? :-).

**Comment by fingolfin** [comment]
@stevelinton That seems fine to me. Who will do it? :)

Regarding T_PERM8: The perm code is actually a great example of code which Id really like to rewrite using C++ templates... then something like T_PERM8 falls out basically "for free", and without introducing yet more code duplication

**Comment by stevelinton** [comment]
I can do the documentation & checking. Shouldn't take long.

**Comment by stevelinton** [comment]
The initial text in the chapter "Permutations" in the reference manual does say that 

    The  points on which permutations in GAP act are the positive integers up to
     a  certain  architecture dependent limit,

So maybe all that's needed on the documentation front is to mention that in the documentation of
`IsPerm`, `PermList` etc.

**Comment by frankluebeck** [comment]
I agree  that limits of 2^28-1, resp. 2^32-1, are fine, and that for the moment we don't need T_PERM8.
It would be nice to add this information in the documentation, and to give an appropriate error message if in 64-bit GAP a permutation contains a point in the range 2^32..2^60-1.

**Comment by ChrisJefferson** [comment]
Now fixed by #581
