### ISSUE TITLE
Problem with the use  of `DirectoriesSystemPrograms`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5752]
The recommended way to find a system program `<sysprog>` is to call `Filename( DirectoriesSystemPrograms(), "<sysprog>" )`.
This way, one gets the first match w.r.t. the `$PATH` variable.
For people (like me) who have the current directory `.` in their `$PATH`, this can lead to strange errors if there is a subdirectory or file with the name `<sysprog>` in `.` that is not executable.

Wouldn't it be safer to have a GAP function `PathSystemProgram( "<sysprog>" )` that runs over the paths in question and returns the first matching path to an *executable* program? (This is the behaviour of `which`.)

**Comment by ChrisJefferson** [comment]
I agree a new function which finds an executable program would be sensible, and probably (from a quick look at the pkgs directory) what basically every user of DirectoriesSystemPrograms() actually wants.

**Comment by ThomasBreuer** [comment]
Yes, there are many packages which should switch to the new function once it becomes available.
