### ISSUE TITLE
`Cite` treats "The GAP Team" as the name of a person

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/gap#5768]
Consider the following session:
```
gap> Cite( "alnuth" );
Please use one of the following samples
to cite Alnuth version from this installation

Text:

[ADET22]  Assmann,  B.,  Distler,  A.,  Eick,  B.  and GAP Team, T., Alnuth,
ALgebraic  NUmber  THeory  and  an  interface  to  PARI/GP, Version 3.2.1dev
(2022), GAP package, https://gap-packages.github.io/alnuth.

HTML:
[...]
```
We see that the author "The GAP Team" appears as "GAP Team, T.", and it contributes a "T" to the label.
This looks strange.
Should we perhaps just add a special treatment for "The GAP Team", such that we get
```
[ADEG22]  Assmann,  B.,  Distler,  A.,  Eick,  B.  and The GAP Team, Alnuth,
[...]
```
or something similar?

(Currently there are at least three other open issues about `Cite`, perhaps they could be addressed all at once:
#5647, #5648, #5649.)

**Comment by fingolfin** [comment]
If someone would like to add special handling for "The GAP Team", that'd be fine for me. Of course a more general solution would be nice, but I don't see how to do that, and in any case I think that's no excuse to not handle the immediate issue directly.
