### ISSUE TITLE
Stabiliser for AlternatingGroup produces incorrect result

### ISSUE THREAD

**Issue by stertooy** [gap-system/gap#5808]
### Observed behaviour
For a particular action (twisted conjugation) of an alternating group on itself, GAP calculates the stabiliser of the identity as the entire group, even though it should be a subgroup of order 5.

```
gap> G := AlternatingGroup( 6 );;
gap> hom1 := GroupHomomorphismByImages( G, G, [ (1,2,3,4,5), (4,5,6) ], [ (1,2,6,3,5), (1,4,5) ] );;
gap> hom2 := GroupHomomorphismByImages( G, G, [ (1,2,3,4,5), (4,5,6) ], [ (1,2,3,4,5), (4,5,6) ] );;
gap> tc := function ( g, h ) return (h^hom2)^-1 * g * h^hom1; end;;
gap> stab := Stabilizer( G, One(G), tc );
Group([ (1,5,3)(2,6,4), (1,6,3)(2,4,5), (1,5,3,6)(2,4) ])
gap> Size( stab );
360
gap> Number( G, g -> tc( One( G ), g ) = One( G ) );
5
```

### Expected behaviour
```
gap> G := AlternatingGroup( 6 );;
gap> hom1 := GroupHomomorphismByImages( G, G, [ (1,2,3,4,5), (4,5,6) ], [ (1,2,6,3,5), (1,4,5) ] );;
gap> hom2 := GroupHomomorphismByImages( G, G, [ (1,2,3,4,5), (4,5,6) ], [ (1,2,3,4,5), (4,5,6) ] );;
gap> tc := function ( g, h ) return (h^hom2)^-1 * g * h^hom1; end;;
gap> stab := Stabilizer( G, One(G), tc );
Group([ (1,2,6,4,3) ])
gap> Size( stab );
5
gap> Number( G, g -> tc( One( G ), g ) = One( G ) );
5
```

### Copy and paste GAP banner (to tell us about your setup)
```
 ┌───────┐   GAP 4.13.1 of 2024-06-11
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv9
 Configuration:  gmp 6.3.0, GASMAN
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.7, PrimGrp 3.4.4, SmallGrp 1.5.3, TransGrp 3.6.5
```
<hr>

As far as I can tell, the problem seems to be this method:
https://github.com/gap-system/gap/blob/00e1e101dbdc34e88f2cc0596a27a3e4854d6d5b/lib/gpprmsya.gi#L1031-L1044
It assumes that the given action for the alternating group is also a well-defined action for the parent symmetric group. This need not be the case.

**Comment by fingolfin** [comment]
Thank you for the report, and create work on narrowing down the issue. I just checked and this worked correct in GAP 4.7.9 but is broken in GAP 4.8. 

The stabilizer method you point out was introduced in PR #366 resp. commit 6d60859 which is consistent with my observation.


Anyway I think I have a fix and will submit it as a PR soon.

**Comment by fingolfin** [comment]
See PR #5811
