### ISSUE TITLE
Increment/Decrement an Integer

### ISSUE THREAD

**Issue by jaslamMiktex** [gap-system/gap#5819]
I have long been searching for this "Increment/Decrement an Integer".
Did I miss it, or has it been intentionally ignored?

**Comment by james-d-mitchell** [comment]
`I := I + 1` is the only supported syntax, if you're thinking of something like `I++` or `I+=1`

**Comment by jaslamMiktex** [comment]
Is it not a natural update to add something like I++ or I+=1?

**Comment by fingolfin** [comment]
It could be done but there is very little gain for a lot of work (think of cases like `mat[i,j] += 1` which require a lot of additional coding in the interpreter).
