### ISSUE TITLE
IsPrimitiveRootMod

### ISSUE THREAD

**Issue by johnbamberg** [gap-system/gap#5829]
Is there a bug with `IsPrimitiveRootMod`?

```
gap> IsPrimitiveRootMod(2, 27);
true
gap> 2^18 mod 27;
1
gap> OrderMod(2,27);
18
```

**Comment by Stefan-Kohl** [comment]
@johnbamberg The output seems correct to me. -- Which output do you expect to get?

**Comment by johnbamberg** [comment]
Ah yes, my mistake. Euler phi of 27 is indeed 18.
