### ISSUE TITLE
IsSolvableGroup cannot even verify solvability for infinite fp-groups?

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#584]
IsSolvableGroup may not always terminate for infinite groups, even if the group is solvable. In fact, it errors out on the infinite dihedral group. 

````
gap> F := FreeGroup("r", "s");; r := F.1;; s := F.2;;
gap> G := F/[s^2, s*r*s*r];;
gap> IsSolvableGroup(G);
Error, the coset enumeration has defined more than 4096000 cosets
 called from
TCENUM.CosetTableFromGensAndRels( fgens, grels, fsgens 
 ) at /home/ghorvath/work/gap/lib/grpfp.gi:1032 called from
CosetTableFromGensAndRels( fgens, grels, fsgens 
 ) at /home/ghorvath/work/gap/lib/grpfp.gi:1310 called from
TryCosetTableInWholeGroup( H 
 ) at /home/ghorvath/work/gap/lib/grpfp.gi:1323 called from
CosetTableInWholeGroup( H 
 ) at /home/ghorvath/work/gap/lib/grpfp.gi:1667 called from
IndexInWholeGroup( H 
 ) at /home/ghorvath/work/gap/lib/grpfp.gi:1643 called from
...  at line 3 of *stdin*
type 'return;' if you want to continue with a new limit of 8192000 cosets,
type 'quit;' if you want to quit the coset enumeration,
type 'maxlimit := 0; return;' in order to continue without a limit
brk> 
````

The polycyclic verification breaks, as well: 
````
gap> F := FreeGroup("r", "s");; r := F.1;; s := F.2;;
gap> G := F/[s^2, s*r*s*r];;
gap> IsPolycyclicGroup(G);
#I  DerivedSeriesOfGroup: may not stop for infinite group <G>
Error, the coset enumeration has defined more than 4096000 cosets
 called from
TCENUM.CosetTableFromGensAndRels( fgens, grels, fsgens 
 ) at /home/ghorvath/work/gap/lib/grpfp.gi:1032 called from
CosetTableFromGensAndRels( fgens, grels, fsgens 
 ) at /home/ghorvath/work/gap/lib/grpfp.gi:1310 called from
TryCosetTableInWholeGroup( H 
 ) at /home/ghorvath/work/gap/lib/grpfp.gi:1323 called from
CosetTableInWholeGroup( H 
 ) at /home/ghorvath/work/gap/lib/grpfp.gi:1667 called from
IndexInWholeGroup( H 
 ) at /home/ghorvath/work/gap/lib/grpfp.gi:1643 called from
...  at line 3 of *stdin*
type 'return;' if you want to continue with a new limit of 8192000 cosets,
type 'quit;' if you want to quit the coset enumeration,
type 'maxlimit := 0; return;' in order to continue without a limit
brk> 
````

However, GAP can verify that this group is really solvable: 
````
gap> F := FreeGroup("r", "s");; r := F.1;; s := F.2;;
gap> G := F/[s^2, s*r*s*r];;
gap> IsAbelian(DerivedSubgroup(G)); 
true
````

The reason is that ````DerivedSeries```` computes derived subgroups, and checks if the derived subgroup computed is different than the previous one. This may not terminate or error out. 

Therefore I propose to change DerivedSeries computation such that it checks first if the computed group is Abelian, and if it is, then it adds the final term to the series and returns it. This new method would be more expensive than the old by an extra IsAbelian check for all members of the series, but would terminate for some fp groups for which it yet did not. 

I will do this in a pull request soon.

**Comment by hulpke** [comment]
> such that it checks first if the computed group is Abelian
How do you want to test whether the derived subgroup of an fp group is abelian?

**Comment by hungaborhorvath** [comment]
With ````IsAbelian````.

**Comment by hulpke** [comment]
:-)
Yes, and what does IsAbelian do? You will need an equality test for elements which you do not have in an infinite finitely presented group.

**Comment by hungaborhorvath** [comment]
Which would work in this particular example, because the derived subgroup is cyclic, hence it knows already that it is Abelian.

**Comment by hungaborhorvath** [comment]
I am saying it would work in some cases (anyway, more than currently). I know that IsSolvable is algorithmically undecidable. 

Alternatively, we could try to compute G^(k) for a big k and check if that group is trivial.

**Comment by hungaborhorvath** [comment]
Polycyclicity should at least be possible to verify by Sims' book on Computation with finitely presented groups, but I do not understand polycyclic groups enough to be able to compute that.

**Comment by hungaborhorvath** [comment]
PR #585 is the one about this issue.

**Comment by hulpke** [comment]
The problem you observe can be resolved by a small change in the DerivedSubgroup method for subgroups of fp groups. (When I implemented the code I only thought about finite groups.). I will do that.

**Comment by hungaborhorvath** [comment]
#618 fixes this.
