### ISSUE TITLE
Segmentation fault with `SET_TYPE_COMOBJ`

### ISSUE THREAD

**Issue by ArhanChaudhary** [gap-system/gap#5847]
```
gap> SET_TYPE_COMOBJ(rec(), 1);
zsh: segmentation fault (core dumped)  gap
```
Version:
```
 ┌───────┐   GAP 4.13.1 of 2024-06-11
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv9
 Configuration:  gmp 6.3.0, GASMAN, readline
```

**Comment by fingolfin** [comment]
Thank you for your report.

`SET_TYPE_COMOBJ` is an internal kernel function that end users are not supposed to call directly. It doesn't validate its arguments. So this is expected behavior.

**Comment by ArhanChaudhary** [comment]
> Thank you for your report.
> 
> `SET_TYPE_COMOBJ` is an internal kernel function that end users are not supposed to call directly. It doesn't validate its arguments. So this is expected behavior.

I was initially under the same impression, but I saw test cases for this function [here](https://github.com/gap-system/gap/blob/ff53a46c0f630d92445ead54b0fba0c179acb675/tst/testinstall/kernel/objects.tst#L26) which implies use within the user space.

**Comment by fingolfin** [comment]
That test is part of a bunch of tests for kernel functions. The existence of this test does not imply that users should use this function.

Of course users *can* call this function. But if they choose to do so, they are on their own, all bets are off, including crashes or worse.
