### ISSUE TITLE
SchurCovers does not return a list, when there is only one Schur cover

### ISSUE THREAD

**Issue by BrauerSuzuki** [gap-system/gap#5852]
If a group G has a trivial Schur multiplier, then SchurCovers(G) simply returns G. However, the documentation states that the command always returns a list. I'm also wondering how I can disable the debug messages of this command.

**Comment by fingolfin** [comment]
Hi there. Could you please provide the exact input code you used to reproduce the issue, as well as detail about which GAP version you are using? E.g. copy&pate the banner printed by GAP during startup

**Comment by BrauerSuzuki** [comment]
I'm not using the latest version, but the polycyclic package wasn't updated since 2020. Also, I'm using a workspace, as you can see:

 ┌───────┐   GAP 4.13.0 of 2024-03-15
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv9
 Configuration:  gmp 6.3.0, GASMAN, readline
 Loaded workspace: /home/benjamin/.gap/workspace
 Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.8, AutPGrp 1.11, 
             Browse 1.8.21, CaratInterface 2.3.6, cohomolo 1.6.11, 
             CRISP 1.4.6, Cryst 4.1.27, CrystCat 1.1.10, CTblLib 1.3.9, 
             CTBlocks 0.9.5, Cubefree 1.19, curlInterface 2.3.2, EDIM 1.3.8, 
             FactInt 1.6.3, Forms 1.2.9, GAPDoc 1.6.7, genss 1.6.8, 
             GRAPE 4.9.0, GrpConst 2.6.5, IO 4.8.2, IRREDSOL 1.4.4, 
             LiePRing 2.8, LieRing 2.4.2, orb 4.9.0, Polenta 1.3.10, 
             Polycyclic 2.16, PrimGrp 3.4.4, RadiRoot 2.9, recog 1.4.2, 
             SglPPow 2.3, singular 2023.02.09, SmallGrp 1.5.3, SpinSym 1.5.2, 
             StandardFF 1.0, TomLib 1.2.11, TransGrp 3.6.5, utils 0.85
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> SchurCovers(CyclicGroup(4));
  Schur Mult has type [  ]
<pc group of size 4 with 2 generators>
gap>
