### ISSUE TITLE
Error when running GAP 4.14.0

### ISSUE THREAD

**Issue by rvf0068** [gap-system/gap#5860]
I tried to run the new version in my Ubuntu 20.04 machine. The program and the packages compiled without errors. I have pointed my gap executable to the new version, and I get the following. Any ideas about how to proceed? 

BTW, I noticed the same error happens with 4.12.0, but not with 4.11.1, which works perfectly here.

rafael@dell2:~$ gap
 ┌───────┐   GAP 4.14.0 of 2024-12-05
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv9
 Configuration:  gmp 6.2.0, GASMAN, readline
 Loading the library and packages ...
Error, Record Element: '<rec>.Date' must have an assigned value in
  if Length( record.Date ) = 10 and record.Date{[ 5, 8 ]} = "--" then
    date := List( SplitString( record.Date, "-" ), Int );
    date := Permuted( date, (1,3) );
    if date[1] < 10 then
        dd := Concatenation( "0", String( date[1] ) );
    else
        dd := String( date[1] );
    fi;
    if date[2] < 10 then
        mm := Concatenation( "0", String( date[2] ) );
    else
        mm := String( date[2] );
    fi;
    record.Date := Concatenation( dd, "/", mm, "/", String( date[3] ) );
fi; at /usr/local/share/gap-4.14.0/lib/package.gi:267 called from 
AddPackageInfos( files, pkgdir, ignore 
 ); at /usr/local/share/gap-4.14.0/lib/package.gi:344 called from
InitializePackagesInfoRecords(  
 ); at /usr/local/share/gap-4.14.0/lib/package.gi:2054 called from
func(  ); at /usr/local/share/gap-4.14.0/lib/system.g:228 called from
<function "CallAndInstallPostRestore">( <arguments> )
 called from read-eval loop at /usr/local/share/gap-4.14.0/lib/init.g:688
type 'quit;' to quit to outer loop
brk> quit;

**Comment by ChrisJefferson** [comment]
So, I think this might be being caused by a package you have, which is out-of-date (but we should still improve the error message!)

If you type `print(record)` when GAP enters the break loop, you should be able to see the package (both name, and version) it is getting stuck on. `print(file[1])` should tell us the name of the file which is causing the problem. Can you have a look?

**Comment by rvf0068** [comment]
You're right, Print(record); showed I had some old packages of mine in ~/.gap/pkg/ that caused the error. I moved them and now GAP loads fine. Thanks!
