### ISSUE TITLE
GAP seg faults on startup when compiled in 32-bit with clang

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#589]
I get the following when I try to compile GAP in 32-bit mode using:

```
 ~/gap4r8p1]$ clang -v
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```

This is with the GAP 4.8.1 binary, and I tried it in stable-4.8 and it happens there too. 

I'm doing:

```
~/gap4r8p1]$ ./configure ABI=32 --with-gmp=no ; make
```

then I get:

```
~/gap4r8p1]$ bin/gap-default32.sh -A -r
Segmentation fault: 11
```

I don't know, but this might be related to [Issue 14](https://bitbucket.org/james-d-mitchell/digraphs/issues/14/build-in-32-bit-mode-fails) in Digraphs.

**Comment by ChrisJefferson** [comment]
On my machine it seems to work fine on the stable-4.8 branch. Have you tried doing `make distclean`, just to make sure no code is hanging about?

**Comment by james-d-mitchell** [comment]
Yes, I did `make distclean`, still seg faults, in both GAP 4.8.1 and in stable-4.8.

**Comment by alex-konovalov** [comment]
Same version is used on our Jenkins OS X slave, and it works fine there, too.

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by fingolfin** [comment]
Works fine for me, too, on Mac OS X 10.11.3.

**Comment by fingolfin** [comment]
@james-d-mitchell Could you please tell us on which exact OS (including version) this is? And what is the output of `cc -v` ? [ NOT `clang -v` ]

**Comment by james-d-mitchell** [comment]
From `cc -v` I get:

    Apple LLVM version 7.0.2 (clang-700.1.81)
    Target: x86_64-apple-darwin15.2.0
    Thread model: posix

and I'm using Mac OS X 10.11.2.

Could this be caused by my compiler flags?

    -g -O3 -fPIC -Wall -Wextra -Wno-unused-parameter -Wtype-limits -Wformat-security -Wpointer-arith -Wno-div-by-zero -Wreturn-type -Woverloaded-shift-op-parentheses -Wstring-conversion -Wswitch -Wsizeof-array-argument -Wloop-analysis -Wunused-label -ferror-limit=100 -fno-omit-frame-pointer -fcolor-diagnostics -fno-omit-frame-pointer -Wshadow -Wtautological-constant-out-of-range-compare

Please let me know if there are any more details that would be helpful.

**Comment by fingolfin** [comment]
Gee, using custom compiler flags is a rather import "detail" ;-). So how and where do you pass these flags to GAP's configure, exactly?

**Comment by fingolfin** [comment]
And did you try without them?

**Comment by ChrisJefferson** [comment]
I tried ramming those compiler flags in and I still ended up with a working executable.

Another thing worth trying is cleaning out any files you might have hanging around, including ignored ones.

To do this:

1) *IMPORTANT* move your `pkg` directory if you keep it inside your git repository, as this will delete that! (of course you could have a bad `IO` or something, so be sure to clean that too).

2) Run `git clean -f -x`.

You can run `git clean -n -x` to see a list of file that `git clean -f -x` would remove, then do it yourself, if you prefer.

**Comment by dimpase** [comment]
Apple's clang cannot be trusted (especially 32-bit version probably receives very little attention); since OSX 10.7, Sage on OSX is built by gcc built from source (at least this works with clang, thanks goodness).

**Comment by ChrisJefferson** [comment]
@dimpase : clang isn't anywhere near that bad -- it certainly builds GAP, along with (almost) every piece of software in homebrew. I don't know what sage is doing to cause problems with clang of course.

**Comment by fingolfin** [comment]
Well, clang used to be a lot worse -- just like gcc used to be a terrible compiler. And as always, once you have a bad rep, it tends to stick.

**Comment by ChrisJefferson** [comment]
@james-d-mitchell : Did this eventually go away, or are you still having this problem?

**Comment by james-d-mitchell** [comment]
I haven't had time to investigate further. Last time I tried this was still a problem. I'll try again this afternoon and report.

**Comment by alex-konovalov** [comment]
@james-d-mitchell was this problem healed by itself, or it still persists?

**Comment by james-d-mitchell** [comment]
Definitely not healed, if anything worse: I can't even compile the master branch with ABI=32 currently. I get an error from the linker complaining about symbols not being available for my architecture x86_64. I can post the log here if that's helpful.

**Comment by dimpase** [comment]
What OS are we talking about? On Linux, one would typically need multiarch stuff installed...

**Comment by dimpase** [comment]
@ChrisJefferson : one reason Sage builds its own gcc is to have (g)fortran, needed by Sage and sadly missing in Apple's toolchain. The only other fortran for OSX we know about is sold by Intel for a lot of money, so this rules out using it.

**Comment by alex-konovalov** [comment]
@james-d-mitchell any updates on this issue? Are you still experiencing this problem?

**Comment by alex-konovalov** [comment]
@james-d-mitchell could you please let us know if the problem is still there?

**Comment by fingolfin** [comment]
The only way to make progress on this would be for @james-d-mitchell to provide a full log of what isngoing on: what commands are enter d, their full terminal output; possibly also a copy of the two config.log files.

Also, thenoriginak report was with GMP disabld; but these days GAP *requires* GMP, sso that can't be how the error is reproduced these days... or is it?!?

**Comment by james-d-mitchell** [comment]
I will try again in the next couple of day to see if this is still an issue.

**Comment by fingolfin** [comment]
Still pending reply. For me, I still cannot reproduce the issue (with Apple clang-800.0.42.1 on OS X 10.11.

**Comment by james-d-mitchell** [comment]
I cannot reproduce this any longer either, so I'll close the issue.
