### ISSUE TITLE
Jumping between presentations of groups

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#594]
Groups may be represented in a computationally hard way (e.g. fp-groups), but sometimes they can be presented in much nicer forms, e.g. like pcgroups. In such situations it is desirable to switch the presentation, compute whatever one wants, and then pull back the result by the isomorphism. I know that something like this exists in GAP already with Nice Homomorphisms, but as far as I understand, this is for matrix representations. 

Are there any other similar handling methods? E.g. for solvable/nilpotent/abelian fp-groups, a lot of things can be computed easier if converted first to pc groups. Just to give a very embarrassin.g example, ````IndependentGeneratorsOfAbelianGroup```` breaks for an fp-group, but computes (after some time) for pc-group: 
````
gap> G := CyclicGroup(IsFpGroup, Factorial(100));
<fp group of size 
93326215443944152681699238856266700490715968264381621468592963895217599993229\
91560894146397615651828625369792082722375825118521091686400000000000000000000\
0000 on the generators [ a ]>
gap> IndependentGeneratorsOfAbelianGroup(G);
Error, Range: <first> must be an integer less than 2^60 (not a integer (>= 2^60)) in
  [ for i  in [ n, n - 1 .. 1 ]  do
        list[i] := obj;
    od; at /home/ghorvath/work/gap/lib/list.gi:3541 called from 
ListWithIdenticalEntries( n, g 
     ) at /home/ghorvath/work/gap/lib/wordrep.gi:1329 called from
    LetterRepAssocWord( elm 
     ) at /home/ghorvath/work/gap/lib/wordrep.gi:250 called from
    NiceStringAssocWord( elm 
     ) at /home/ghorvath/work/gap/lib/wordrep.gi:266 called from
    ViewObj( obj ); at /home/ghorvath/work/gap/lib/oper.g:1564 called from
    View( obj![1] ); at /home/ghorvath/work/gap/lib/grpfp.gi:54 called from
    ...  at line 2 of *stdin*
you can replace <first> via 'return <first>;'
brk> 
gap> G := CyclicGroup(IsFpGroup, Factorial(100));
<fp group of size 
93326215443944152681699238856266700490715968264381621468592963895217599993229\
91560894146397615651828625369792082722375825118521091686400000000000000000000\
0000 on the generators [ a ]>
gap> hom := IsomorphismPcGroup(G); time; 
[ a ] -> [ f1*f2^2*f3^3*f4^4*f5^2*f6*f7^6*f8^17*f9^20*f10^28*f11^9*f12^9*f13^
    7*f14^7*f15^45*f16^18*f17^36*f18^23*f19^16*f20^38*f21^63*f22^51*f23^
    26*f24^51*f25^16*f27*f30^5*f31^10*f32^2*f33^16*f34^13*f35^28*f36^23*f37^
    13*f38^31*f39^29*f40^24*f42^2*f43^2*f44^3*f45^9*f46^12*f47*f48^5*f49^
    6*f50^16*f51^5*f54*f55^6*f56^7*f57^7*f58^5*f59*f60^2*f63*f64^6*f65^9*f66^
    6*f67^8*f68^15*f72*f73^9*f74^11*f76^2*f77^3*f78^6*f79^4*f80^5*f83^4*f84^
    3*f85^6*f88^4*f89^4*f90^6*f92^2*f93*f94^6*f96*f97^2*f98^5*f100^2*f101^
    3*f102^2*f104^2*f105^2*f106^3*f108*f109^4*f110^3*f112^2*f113^4*f114^
    5*f116^2*f117^2*f120^2*f121^2*f123^2*f124^2*f126*f127^4*f129^2*f130^
    3*f133^4*f135*f136^2*f139^3*f144^2*f148^2*f150^2*f152*f154^2*f156^2*f158^
    2*f160*f162*f166*f168*f172^2*f174*f178*f180^2*f182*f184*f188^2*f190^2 ]
20436
gap> IndependentGeneratorsOfAbelianGroup(Image(hom));; time; 
50116
gap> List(IndependentGeneratorsOfAbelianGroup(Image(hom)), x -> PreImage(hom, x));; time;
1896
````
I guess my question is whether GAP has some (uniform) way of handling such jumps between different presentations, and if yes, then how is that handled, or if not, then is there a plan on doing this?

**Comment by bh11** [comment]
If you know a nice monomorphism (allowing efficient translation from rep A to B and back), you can install `NiceMonomorphism`, `NiceObject` and set `IsHandledByNiceMonomorphism` and use GAP's automatic translations. But as far as I can see, there are no `NiceMonomorphism` methods for `IndependentGeneratorsOfAbelianGroup`.

**Comment by stevelinton** [comment]
Yes, the `Nicemonomorphism` mechanism is used more widely than just for matrix groups, but it's always a bit tricky to work out in general when to look for a nice morphism and when to just solve the problem as you were given it. We tend to err on the side of not automatically embarking on potentially very long searches in these cases, and leave it to the user to use IsomorphismPcGroup or IsomorphismPermGroup if they choose to.

**Comment by fingolfin** [comment]
I don't see why this is an "issue". It seems more like an attempt to start a discussion, and as such, would be better suited for our mailing list.

I am closing this for now. If you want to report a concrete bug, or want to suggest a concrete enhancement based around this idea, please open a new issue for those.
