### ISSUE TITLE
Needed test for ClassicalMaximals

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#598]
I've picked up one of the files with zero coverage by tests: `grp/clasmax.grp`. I've tested that at least the following works:

```
List(CLASMAXDATA,x -> CallFuncList(ClassicalMaximals,x{[1..3]}));
```

so we have the ability to read the data and construct lists of maximal subgroups from them. 

Looking further, `ClassicalMaximals` is called only in one place, namely `MaxesAlmostSimple` in `lib/maxsub.gi`. Tests exercise only the initial part of the code of `MaxesAlmostSimple`. To get to the call of `ClassicalMaximals`, one should use the group for which `TomDataMaxesAlmostSimple` returns fail.

The first such case in the list `CLASMAXDATA` is PSL(3,13). Using local version with an extra Info message, I have

```
gap> G:=PSL(3,13);
<permutation group of size 270178272 with 2 generators>
gap> MaximalSubgroups(G);;
#I  Simple type: A(2,13) = L(3,13) 
#I  MaxesAlmostSimple: Use ClassicalMaximals
#I  8 type 2 maxes
```

but this seem to take too long and I've terminated it. Any ideas for a better test?

**Comment by hulpke** [comment]
`ClassicalMaximals` is currently only a list lookup of generators for dimension up to 12 and fields of order up to 200. My reason to add this was to have a least a hook for eventually tying in the proper code -- a translation of the Bray/Holt/Roney-Dougal code in Magma (which I am currently working on).

The problem with `MaximalSubgroups` is that is tries to calculate all. If you use `MaximalSubgroupClassReps` instead the result should be instantaneous.

**Comment by fingolfin** [comment]
Right now, `grp/clasmax.grp` has 75% coverage. While of course that leaves room of improvements, it is now above average. So there is no reason to single it out, hence I am closing this issue.
