### ISSUE TITLE
Is it possible to report line number of Error/ErrorNoReturn statements?

### ISSUE THREAD

**Issue by bh11** [gap-system/gap#599]
When debugging code, it would be extremely useful if the output of the `Error` and `ErrorNoReturn` functions could include the line number of the error statement itself. So far, it only reports the line number of the next function down the calling stack. Of course, I could just use a wrapper for `Error` but there might be a more elegant solution. 

For example, this code
```
CallError := function()
    Error ("testing error function");
end;

CallError();

```
produces the following break loop – the line number 5 refers to the CallError() statement. 
```
Error, testing error function called from
<function "CallError">( <arguments> )
 called from read-eval loop at line 
5 of /Users/Burkhard/GAP/packages-git/pkg/irredsol/private/test_error.g
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
```
Thanks!

**Comment by fingolfin** [comment]
That would indeed be quite useful.
