### ISSUE TITLE
Get rid of automatic search for compiled library files in compiled/...

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#60]
At the moment `ReadGapRoot` looks for compiled versions of GAP Library files as statically linked modules (which we use a little) and as dynamically loadable modules in directories under compiled/. If found they are loaded instead of the GAP file (provided various checksums match). 

I don't think anyone uses the dynamic option and, in the interest of slightly cleaning up a very complicated piece of code, I'd quite like to withdraw it. 

It's not urgent. It isn't causing a current bug, but `ReadGapRoot` is horrible and making it less horrible would be nice.

**Comment by fingolfin** [comment]
I believe this was resolved by PR #448. Feel free to reopen if I am mistaken!
