### ISSUE TITLE
Documentation of ordering of points in Action

### ISSUE THREAD

**Issue by stevelinton** [gap-system/gap#613]
At the moment it is not explicitly stated that how the points acted on by the group produced by `Action' relate to the objects acted on in the input to `Action`. I believe the correspondence is the obvious one, preserving the order of the objects as supplied, but I can't see documentation of this. If it is true it should be documented.

**Comment by hulpke** [comment]
My interpretation was that "the action of G on Omega" ensured this already -- I will clarify.

**Comment by stevelinton** [comment]
Excellent. Can someone pull the patch across to master and stable?
