### ISSUE TITLE
Factorise a permutation in a permutation group over the original generators.

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#617]
There doesn't seem to be a sensible way to factorise a permutation over the generators of permutation group, and it would be really useful if such a method existed. Perhaps it does, in which case I will be happy to learn what it is. 

Ideally, I'd like a function that takes a stab chain for a permutation group `G` and a permutation `p` and returns a list `word` of integers corresponding to the generators of `G` so that 

    Product(List(word, i -> GeneratorsOfGroup(G)[i]))

equals `p`. It is not important for the application I have, if the length of the word is minimal or not. 

There are the functions `Factorization` and I seem to remember that you can factorise a permutation over the strong generators of stab chain (I can't remember the name of the function that does this, and I can't seem to locate it). 

The problem with `Factorization` is that it is slow, and returns an element of the free group, not a list of integers, and so is hard to use in code. 

The problem with the other approach is that the factorisation is over the strong generators of the stab chain and not the original generators of the group.

**Comment by hulpke** [comment]
The `Product` construct you have would not work in any case because of inverses (unless you want to specify a monoid decomposition).

If you want a list of integers (and `MappedWord` will not do what you want), you can get them easily from the word as its letter representation:

    gap> g:=MathieuGroup(12);;
    gap> w:=Factorization(g,(1,5,12,7,11,6,2,4)(3,10,9,8));
    x1^-1*x2^-1*x1^2*x3*x2*x1^2*x3*x1
    gap> LetterRepAssocWord(w);
    [ -1, -2, 1, 1, 3, 2, 1, 1, 3, 1 ]

If you want speed and do not care about length, using a homomorphism will do so:

    gap> epi:=EpimorphismFromFreeGroup(g);;
    gap> w:=PreImagesRepresentative(epi,(1,5,12,7,11,6,2,4)(3,10,9,8));
    x2^-1*x1^2*x3*x1^-1*(x2^-1*x1^-1*x2^-1*x1)^2*(x2^-1*x1)^2

**Comment by james-d-mitchell** [comment]
Ok, thanks for point out `EpimorphismFromFreeGroup`, this will be useful.
