### ISSUE TITLE
nilmat: with package loaded, valid code suddenly runs into an error

### ISSUE THREAD

**Issue by bh11** [gap-system/gap#631]
Just for the records: 

there is a small bug in the nilmat package which is triggered by the new socle code by @hungaborhorvath and test code in the CRISP package (but unrelated to CRISP, it can be reproduced without the CRISP package).

```
LoadPackage("nilmat");
G :=  Group([], IdentityMat (4, GF(2)));Socle(G);
```

runs into an error when used with the dev version. 

The follwing related code also runs into an error in GAP 4.7 and 4.8.

```
LoadPackage("nilmat");
G :=  Group([], IdentityMat (4, GF(2)));SylowSystem(G);
```

I've contacted the authors of nilmat about the problem.

Does it make sense to include the above code (without the LoadPackage call, of course) in some tst files?

**Comment by alex-konovalov** [comment]
For the moment, `bugfix.tst` has a section at the end which collects small bugfix tests that require packages. If need be, such small test could be placed there. But in general, I would like to rethink how we perform tests that require loading additional packages.

**Comment by bh11** [comment]
@alex-konovalov I meant just the line, without an explicit LoadPackage call, so that one can easily discover that it works without package but fails when the relevant package is loaded. 

The real question is: do we want the test code now (causing errors as long as nilmat isn't fixed but reminding us of the problem), or is it better to wait until the problem gets fixed. I guess it's you who regularly checks automatic tests, so imo it really depends what you prefer. In any case, I think I can't make a PR because automatic testing would detect a problem (or maybe it doesn't because tests are done without packages?)

**Comment by alex-konovalov** [comment]
@bh11 thank you for clarification - should be reading more carefully. OK, so such line could go to any appropriate test then, but I suggest to not to add it now - it will flood me with failure notifications each day until new Nilmat will appear, and will obscure more important failures. 

The best way I see is the  "submit and forget" approach: to make a PR, so the job is done and it will be waiting till its time. Whenever the automated testing will pass or fail, that PR should be them marked "DO NOT MERGE" and a comment should explain that it waits till new Nilmat. Then we don't have to remember this constantly.

**Comment by fingolfin** [comment]
BTW, in other languages, the test system(s) usually have a feature to mark tests as "known failure" for precisely such situations.

**Comment by fingolfin** [comment]
We asked the nilmat atuhors again for a new release in August 2016, and I sent another email April 12, 2017 (CC to GAP support list). Unfortunately, no reaction so far, as far as I can tell... :-(

**Comment by alex-konovalov** [comment]
Confirm that Nilmat 1.3 fixes the problem. When we will close #632, this may be closed too.
