### ISSUE TITLE
gapmacro doesn't indent last line of examples

### ISSUE THREAD

**Issue by chsievers** [gap-system/gap#633]
After commit dac88baa, the last line of an example typeset with the commands `\beginexample` and `\endexample` from doc/gapmacro.tex is not indented.
After TeXing it, you can see an example of this behaviour on page 15 of gapmacrodoc.

**Comment by bh11** [comment]
@chsievers Thanks for spotting this. Should be fixed in the master branch now.

**Comment by chsievers** [comment]
@bh11 Indeed, thanks. Is it my part to close this now?
