### ISSUE TITLE
convert.pl has trouble mixing <vars> and > relations

### ISSUE THREAD

**Issue by chsievers** [gap-system/gap#634]
The script in etc/convert.pl renders `$|<v1><v2><v3>| > |<v1>| - |<v2>| + |<v3>|$` (which appears in the FGA manual as part of the documentation for `FreeGeneratorsOfGroup`) like this:
` |v1 > v2 v3 | |v1 | − |v2 | + |v3 |`
(see http://gap-system.org/Manuals/pkg/fga/htm/CHAP002.htm#SSEC001.1 at the end of the second inner bullet point)

TeX with gapmacro as well as the online help have no problem with this admittedly convoluted expression.

**Comment by bh11** [comment]
@chsievers Should be fixed now. Please feel free to close the issue if your problem is solved.

**Comment by chsievers** [comment]
That works, thanks.
Is it intentional that this fix is in stable-4.8, while the one for #633 is in master?

**Comment by bh11** [comment]
@chsievers Of course not. The fix for #633 should have gone to stable-4.8 as well. I've cherry picked it on stable-4.8 now.
