### ISSUE TITLE
Add function `TestPackage`

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#637]
It might make life easier for package authors if we added a function `TestPackage`. This would run packages tests in the same way our regression testing does.

This has several advantages:

* Package authors can have confidence we are running tests how they like.
* Package users have an easy way of checking packages they have installed work correctly.

It is unfortunately hard for me to imagine (i should maybe imagine better) how we can tell if the tests would pass or fail easily (seeing as we do this check based on reading the output for a particular string), but it would be a useful step forwards.

This was inspired by a message by @Stefan-Kohl on #630.

**Comment by alex-konovalov** [comment]
FYI `tst/testutil.g` already provides `RunPackageTests`. It's called from `make testpackages`, but maybe is not so convenient to run manually. It seems to me that the way to go it to make a target for `make testonepackage` and use it like
```
export PKG_NAME=package_name
make testonepackage
```

**Comment by alex-konovalov** [comment]
@ChrisJefferson I've implemented both approaches (make target and GAP level function) in PR #647., Waiting for some feedback before documenting it.

**Comment by markuspf** [comment]
I merged #647 so I am closing this issue.
