### ISSUE TITLE
Highlight all the GAP!

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#638]
I have started a wiki page to list the various way editors and other software can syntax highlight GAP https://github.com/gap-system/gap/wiki/Syntax-Highlighting-GAP .

If anyone knows of any other systems where highlighting exists, please list it. If anyone has any places they want highlighting, please also list it.

For me, I would like rouge highlighting in `rouge` ,( https://github.com/jneen/rouge ), as this is what github now uses for github pages. Anyone who knows ruby and wants to dive into this, please do!

**Comment by markuspf** [comment]
I added the emacs gap-mode and the CodeMirror GAP mode (which is used in
Jupyter, so I'd really like someone to fix my ill attempts at adding GAP to it
;)).

**Comment by alex-konovalov** [comment]
I've recently updated [8.3: Where is the GAP file editor? How do I save GAP programs?](http://www.gap-system.org/Faq/faq.html#8.3) from the GAP F.A.Q. which now lists 8 different editors. Would be good to keep those lists in sync.

**Comment by fingolfin** [comment]
Agreed. In fact I'd argue we should have only one list. If we keep the one on the wiki, I'd transfer all info from the FAQ to it, and then change the FAQ to link to the Wiki.

@ChrisJefferson Highlighting GAP code on GitHub already works:
```gap
if x in list then
  Print("yay\n");
fi;
```

**Comment by ChrisJefferson** [comment]
@fingolfin : We should mention github does highlighting!

However, by 'github pages', I meant "the way that GAP will automatically generate webpages by running jekyll, from a gh-pages branch'. Unfortunately, github has just upgraded github-pages to use jekyll 3, and in the process switched from the pygments highlighter (which does highlight GAP), to rouge (which does not).

**Comment by frankluebeck** [comment]
The GAP repository contains files etc/*.vim and a etc/README.vim-utils.

Of course, that is the only hilighting  and editor support that is really needed!

**Comment by fingolfin** [comment]
@ChrisJefferson ahhh, I see. Sorry, I misunderstood.

**Comment by alex-konovalov** [comment]
@fingolfin I agree that Wiki page is a better place - one should only take care of not renaming the page arbitrarily and break the link to it on the GAP website.

**Comment by fingolfin** [comment]
Is there a point in leaving this open?

**Comment by frankluebeck** [comment]
The mentioned wiki and FAQ pages do not list the support for `vim` which I mentioned above. 

This is even documented in GAP, try
```
gap> ?vim
gap> ??editor
```

**Comment by alex-konovalov** [comment]
I've mentioned vim on Wiki page, and will add it to the FAQ page. Otherwise, I agree that this issue may be closed. If anyone thinks it should be kept open, please reopen it.
