### ISSUE TITLE
doc/manualindex missing

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#640]
Various files relevant for gapmacros were removed at some point, namely here: b98e9416296a0e3549ebccc821419c9fe04b4d3e

As a result, I cannot build various package manuals (e.g. ace, xgap, ...), or can only build them without an index, because they rely on `manualindex`

Perhaps we should restore `manualindex` (and maybe others, have not yet tested)? It seems weird to leave `gapmacro.tex` in, but remove these other parts.

**Comment by fingolfin** [comment]
@alex-konovalov You removed those files, by the way ;-)

**Comment by bh11** [comment]
@fingolfin Very good point. Especially since manualindex is documented in gapmacrodoc. In a GAP release, it should go to the same archive as gapmacro.tex and convert.pl.

**Comment by alex-konovalov** [comment]
The file is restored in #642. It should be included in the tools archive in GAP 4.8.3 (TODO: https://github.com/gap-system/gap-distribution/issues/12)
