### ISSUE TITLE
GAP can't do Union(Rationals,Integers)

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#657]
Previously we had a bug (caused by CRISP) which mean GAP got a wrong answer for `Union(Rationals,Integers)`. Now it just can't do it. It would be nice if it did.

GAP does know `IsSubset(Rationals, Integers)`. This suggests (to me) a low-priority method for `Union` (and  maybe `Intersection`) which uses `IsSubset`, and calls `TryNextMethod` if it fails.

I'm not going to do this myself, but it might be a nice thing for someone else to work on, if they want to.

**Comment by abdulazizali77** [comment]
@ChrisJefferson @fingolfin would like to have a stab at this. Which file/folder/class should one start from?
Trying out 4.8.3, cant seem to find Union that works thats not Union(list). Which version prior to 4.8.3 did it work?
Also, im assuming we should also address `Difference` too?

**Comment by ChrisJefferson** [comment]
In GAP 4.8.6, the following works (not sure if this is what you mean):

```
gap> Union([1,2], [3,4]);
[ 1 .. 4 ]
gap> Union(Integers, [1]);
Integers
gap> Union(PositiveIntegers, [5]);
PositiveIntegers
gap> Union(PositiveIntegers, [-5]);
Error, sorry, cannot unite <C1> with the infinite collection <C2> at /Users/caj/reps/gap/gap/lib/coll.gi:2560 called from
Union2( S, R
 ) at /Users/caj/reps/gap/gap/pkg/resclasses-4.5.0/lib/resclass.gi:1704 called from
Union2( tounite[1], tounite[2] ) at /Users/caj/reps/gap/gap/lib/coll.gi:2764 called from
<function "Union">( <arguments> )
 called from read-eval loop at *stdin*:8
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
```

So, looking round about those functions in coll.gi would be a good idea. `Difference` could be looked at to, but might be harder.

**Comment by abdulazizali77** [comment]
thanks thats exactly what i meant, i guess i should start with downloading 4.8.6 then.

**Comment by ChrisJefferson** [comment]
If you are writing new code, I would recommend using the 'master' branch from here. On most days it works well (we try very hard not to break it, and i use it for my day-to-day usage).

**Comment by abdulazizali77** [comment]
thanks! i will start looking at trunk/master then instead of a tag (which wasnt what i meant! )
