### ISSUE TITLE
DotFileLatticeSubgroups can't handle trivial group

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#663]
```gap
DotFileLatticeSubgroups( LatticeSubgroups( Group(()) ), "test" );
```
throws an error:
```
Error, MaximumList: <list> must contain at least one element called from
...
```

**Comment by markuspf** [comment]
Nice catch!

Would you mind adding some code that handles this case and opening a pull request?

**Comment by markuspf** [comment]
Sorry I just saw that @hulpke already fixed this.

**Comment by ssiccha** [comment]
Yes, I figured it shouldn't be too hard to find the relevant code but Alexander beat me to it.
Cheers

**Comment by alex-konovalov** [comment]
This is marked for 4.8.3 but still waits a PR from @hulpke or should be postponed as non-critical.

**Comment by hulpke** [comment]
This was part of PR #667 Thus closed.
