### ISSUE TITLE
GAP4stones not normalized

### ISSUE THREAD

**Issue by Stefan-Kohl** [gap-system/gap#666]
When running testinstall.g in GAP 4.8.2, it says "You should expect the test to take about one minute and show about 100000 GAP4stones on an Intel Core 2 Duo / 2.53 GHz machine.". However, on my
machine it shows in total about 3000-4000 GAP4stones, as if the test would take half an hour or so.
The actual duration is about 100 seconds.

**Comment by alex-konovalov** [comment]
Thanks - we should try to renormalise them. The default now is 10K, not 100K - that should be updated too.

**Comment by ChrisJefferson** [comment]
There is (I think) 3 issues here:

1) We should replace the words "Intel Core 2 Duo / 2.53 Ghz machine" with "modern desktop machine", to avoid having to keep changing it :)

2) Maybe testinstall is getting a bit long, and should be pruned a little

3) The GAP-stones do indeed need renormalising with each release (I always tend to just put in 1 with new tests)

**Comment by Stefan-Kohl** [comment]
Another question is how useful the GAP4stones really are, compared to just printing run times
and providing typical values for some types of recent machines for comparison.

**Comment by alex-konovalov** [comment]
Renormalised in https://github.com/gap-system/gap/commit/7e9d1d281eeea92c3d2a0c7d496fdf09f5f5e15c.

@Stefan-Kohl answering your question, I think they such indicators like GAP4stones were fashionable when they were introduced, and are less of an interest now. But to get rid of them, some one has to take the code out, submit a pull request, which is more work than keeping them and renormalising from time to time.
