### ISSUE TITLE
Z(4,5) crashes GAP

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#676]
Trying the following invalid code:

```
gap> Z(4,5);
```

Immediately crashes GAP with a floating point exception.

**Comment by stevelinton** [comment]
This happens in stable-4.7 but not in master.

**Comment by markuspf** [comment]
This does also happen in `stable-4.8`, but you probably meant that. I wonder what change fixed that or whether @hulpke just fixed it at some point.

**Comment by ChrisJefferson** [comment]
`Z(6,5)` still crashes master

**Comment by markuspf** [comment]
This is because `FuncZ2` in finfield.c does not check whether the parameters actually are valid (i.e. p a prime) before trying to access the finite field that `Z` supposedly belongs to....

**Comment by stevelinton** [comment]
This code needs a bit of cleanup. There is duplication between Z2 and FiniteField and I suspect FInitefield could be made nicer at the cost of a (today) trivial amount of memory.

**Comment by fingolfin** [comment]
I fixed the crash in d3baa774119f5db69cf6257e506458ee6526e9e0, not realizing this bug was related.

I am not closing this yet, though, as it still accepts `Z(4,5)` (treating it equal to `Z(2,10)`), which it really shouldn't. But at least no crash anymore!
