### ISSUE TITLE
Printing large powers of elements of free group takes ages

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#677]
```
gap> F := FreeGroup(2);
gap> F.1^1000000;
```

Takes ages. I think this was already a matter of discussion on mailing lists, I believe.

**Comment by hulpke** [comment]
On my system this takes 58 ms. in the master branch. (Yes, 4.8 takes longer, and it is possible to construct words that take notably longer).

**Comment by markuspf** [comment]
Were there changes to the printing of those elements recently?

**Comment by hulpke** [comment]
Yes. PR #618, commit b2d2bb21ddf6c8c3c60431786ea41fc5d345e080

**Comment by markuspf** [comment]
Ok. Then I'll close this.
