### ISSUE TITLE
timeout.tst

### ISSUE THREAD

**Issue by hulpke** [gap-system/gap#688]
I again observe that the tests of a pull request -- #683 -- is hanging in the installation test of timeout.tst.

I understand that this is recent work and is more delicate concerning operating system dependencies, but   wouldn't it make sense to not have this be part of the standard tests?

Would anyone object to me reviving timeout.tst from the installation test suite and move it to a suite that is not tested by TravisCI?

**Comment by alex-konovalov** [comment]
I suggest to wait till we hear from @markuspf. Maybe #672 fixes this.

**Comment by markuspf** [comment]
My pull-request does indeed fix the issue, the patch is just hideous because it does conditional compilation by using `#include` on source files. I could of course back out the hideous part again and leave the posix timer code commented out if we want this fix to be merged really soon.
