### ISSUE TITLE
Merging of #683 makes grplatt.tst take a long time 

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#693]
I have just noticed that `grplatt.tst` seems to be taking a long time now. I will have to investigate that.

**Comment by alex-konovalov** [comment]
Good catch! I can see the spike in the plot for nightly builds performance too. First time it happened in the build  #293 (Mar 25, 2016 6:00:00 PM) based on revision f3cda31ec0e0358177927064638519f8c2d29786, and the new changes after the previous nightly builds were:

- Fix last line of 'Where' not using filename:line notation
- Add filename:line information to Error statements 
- Temporarily move timeout.tst to teststandard 
- ENHANCE: LowIndexSubgroups as generic operation
- ENHANCE: Improvement for PartitionStabilizerPermGroup
- ENHANCE: Reduce degree of simple permutation factor
- ENHANCE: Improve subgroup fetch from table of marks. 

![getplot](https://cloud.githubusercontent.com/assets/5751387/14091449/43fb1d8e-f538-11e5-8759-caadd4f58b7f.png)

**Comment by hulpke** [comment]
You probably mean #683, not #293. Anyhow, this merge contains new tests in grplatt.tst (as such tests had been requested). These are likely to increase runtime with assertions substantially.

**Comment by alex-konovalov** [comment]
@hulpke no I mean 293 but that was the number of the Jenkins build. I've forgot that it will be linked then to another thing. Now removed it from my comment to avoid confusion.

Yes, #683 is an obvious reason. In one of the tests on another machine (not the one where the plot was produced), a week ago the runtime was 189s and now 4223s. That's a bit too much I'm afraid. Maybe we need to revise the tests or assertions...

**Comment by alex-konovalov** [comment]
P.S. And of course seeing timeouts in the whole teststandard, I was assuming that they are coming from not yet fixed alarms....

**Comment by markuspf** [comment]
As pointed out above the additional tests in `grplatt.tst` are the cause for the test taking long. Maybe we'll introduce `tst/testintense`?

**Comment by alex-konovalov** [comment]
All tests in the master branch are now runnable (at least in 64-bit build on my desktop), but the runtime of the jenkins job (build GAP and packages and then run `make teststandard`) increased from ~2 hrs to almost 5 hours.

This really demands for moving intense tests out of the teststandard.

**Comment by hulpke** [comment]
My guess is that the homomorphism tests contribute to the extreme runtime. Would it make sense to run the tests at a lower assertion level (or change the assertion level for the homomorphism tests to 3)?

**Comment by alex-konovalov** [comment]
Just tried to run `grplatt.tst` and was forced to terminate it. Assigned this issue to GAP 4.9.0 to ensure that we will look at it.

**Comment by alex-konovalov** [comment]
Current runtimes for `grplatt.tst` on one of our Jenkins slaves are 
- 56 min without packages
- 45 min with packages
I will close this issue, as this does not constitute a problem now.
