### ISSUE TITLE
RFC: should `Test()` ignore whitespace by default?

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#697]
By default, `Test` checks for the the exact match of the actual and the reference outputs. This is used, for example, in testinstall/standard/manuals.

It also has an option to check them up to whitespaces. For example, this option is used in `make testpackages` for packages providing standard tests as `.tst` files.

Assume that in the future we will start to care more about code formatting and will clean up all existing inconsistencies (for example, spaces and no tabs, X spaces for indentation, etc.). However, we will not be able to get rid of trailing whitespaces: the GAP output may contain them e.g. in the output of long lists. Would it be useful to make the default check up to trailing whitespaces? This will also help to avoid confusing outputs like

```
gap> Test("testwsp.tst");
########> Diff in testwsp.tst, line 1:
# Input is:
1+1;
# Expected output:
2    
# But found:
2
########
false
```

where I've introduced several spaces after 2 in the test file.

**Comment by hulpke** [comment]
> Assume that in the future we will start to care more about code formatting and will clean up all existing inconsistencies (for example, spaces and no tabs, X spaces for indentation, etc.).

Why on earth would we want to do this? It has little if any practical benefit and is a surefire way to get a clash of personal preferences.

Having said this, I would strongly support to do tests only up to whitespace. It is very easy to get trailing whitespace when copying and pasting versus hand editing and I can't see a benefit in having this being marked as wrong.

**Comment by alex-konovalov** [comment]
> Why on earth would we want to do this? It has little if any practical benefit and is a surefire way to get a clash of personal preferences.

@hulpke see for example [this wiki page]((https://github.com/gapdays/gap-sage-days2016/wiki/Code-formatting-recommendations) resulting from a discussion on GAP Days in January 2016 (it should b revised, so that's why it's still hosted elsewhere). It has motivation and further links, and as you will see, it rules out some practices, but leaves enough freedom to do what is sensible and make exceptions.

**Comment by fingolfin** [comment]
I changed the description of this issue to something which I think matches the intent of it (i.e. it suggest to change the default behavior of `Test()`. Please change back if this was wrong.

However, this might be a bad place to discuss this anyway. A better way would be to just create a PR which changes the default (it should be a matter of changing 1-3 lines in `lib/test.gi`), then invite people to discuss and review the PR.

**Comment by alex-konovalov** [comment]
OK, I may try to do a PR which will ignore only trailing whitespaces (this is likely a bit more work than just making "uptowhitespace" a default setting).
