### ISSUE TITLE
New components in PackageInfo.g file

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#7]
The proposal is to add the optional components for the repository, issue tracker and support email address for a package in order to be displayed on the automatically generated overview pages for packages:
- `Repository := rec( URL := "http://FOO", Type := "hg/git/svn/cvs")`
- `IssueTrackerURL`
- `SupportEmail`

Knowing the type of the repository would be useful if we ever want to use these fields in some automated procedure. 

I will update the template for the PackageInfo.g file in the example package and ask package authors to update their PackageInfo.g files.

**Comment by fingolfin** [comment]
I like the idea!

On the risk of being overly nitpicky: the term `Repository` is overly generic, so perhaps it should be renamed to make it clear that this refers to a "source repository"? E.g. "SourceRepository" ?

**Comment by alex-konovalov** [comment]
This is now implemented in the Example package which is now hosted on GitHub. It remains to implement the check for the new components in `ValidatePackageInfo`.

**Comment by markuspf** [comment]
Can this be closed now?

**Comment by alex-konovalov** [comment]
Closing - the relevant changes are in commits https://github.com/gap-system/gap/commit/9b83f219f2d0619c552830b3ecdfbf9df34fc145 and https://github.com/gap-system/gap/commit/433c24bc9f0a8f434293281962383630a97fbd17
