### ISSUE TITLE
GAP misreports where errors occurred

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#71]
I'm looking for examples of where GAP incorrectly reports where errors occur, or prints ```<compiled or corrupted statement>```, when the code is purely in GAP. For now I'll keep them all in one bug report.

* Matrix deref, for example:
``` function() local S; S := []; return S[0]; end; ```
* atomic access (in HPC-GAP)
``` function() atomic R do od; end; ```

Any other occurrences welcome (no promises about fixing them, but let's at least find them).

**Comment by ChrisJefferson** [comment]
matrix deref fixed in #72. Unfortunately, it's (as far as I can tell) impossible to test with a .tst file, as they don't give you the failing location.

**Comment by alex-konovalov** [comment]
This is another example from GAP 4.7.7:
```
gap> FindGoodNode := function()
> local Flag, Signs, CoGood;
> Signs:=[];
> Flag:=0;
> while Flag = 0 do
>     CoGood := 0;
>     Flag := 1;
> od;
> return Signs[CoGood];
> end;
function(  ) ... end
```
The error in the code comes from trying to return 0-th element of the list `Signs`, but the error message mentions the check of `Flag = 0`:
```
gap> FindGoodNode();
Error, no method found! For debugging hints type ?Recove\
ry from NoMethodFound
Error, no 1st choice method found for `[]' on 2 arguments called from
Flag = 0 called from
<function "FindGoodNode">( <arguments> )
 called from read-eval loop at line 11 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```

**Comment by alex-konovalov** [comment]
Great - my example now fixed, thanks! Now the line causing the error is reported properly:
```
gap> FindGoodNode();
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `[]' on 2 arguments called from
Signs[CoGood] on line 9 of file *stdin* called from...
```

**Comment by fingolfin** [comment]
What is the status of this issue?

**Comment by ChrisJefferson** [comment]
The current status is I believe all known issues are fixed, but I haven't looked hard for new ones.

I'm debating having an internal rewrite, as the internals in this area seem to be a mess (although perhaps there is a reason they are the way they are, no-one seems able to remember..).

**Comment by stevelinton** [comment]
The internals are largely my code and my mess. I was trying to go in the direction of something like a proper exceptions mechanism, with as much of it as possible written in GAP. Not sure if I really made any progress.

**Comment by fingolfin** [comment]
Based on what @ChrisJefferson wrote, I am closing this issue now, as there are no known instances of this issue left. If more similar problems crop up, I think it makes more sense to file new, separate issues for them, instead of expecting people to locate this old issue and appending their findings here ;-).
