### ISSUE TITLE
Cannot compute size of a 6-element subgroup?

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#712]
New bug....
````
G := DirectProduct(DihedralGroup(12), SymmetricGroup(4));
gap> DirectFactorsOfGroup(G); 
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 3rd choice method found for `DirectFactorsOfGroup' on 1 arguments at /home/ghorvath/work/gap/lib/methsel2.g:241 called from
DirectFactorsOfGroup( B 
 ) at /home/ghorvath/work/gap/lib/grpnames.gi:400 called from
DirectFactorsOfGroup( Image( Embedding( G, i ), info[i] ) 
 ) at /home/ghorvath/work/gap/lib/grpnames.gi:284 called from
<function "unknown">( <arguments> )
 called from read-eval loop at *stdin*:2
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
````
The reason is the following: first the algorithm recognizes the two direct products, then tries to factorize them. It realizes that the first one can be factorized to two normal subgroups (as C2xD6 in reality), and then recursively calls itself on the factors. However, somehow this D6 factor does not obtain a size, further, it does not even obtain ````CanComputeSize````. Thus for this group a no method found error is produced (I added the check for ````CanComputeSize```` into grpnames.gi:360 in commit  c47602c, I am not entirely sure why). 

Now, there are several ways to resolve this: 
1) probably the easiest is just to remove ````CanComputeSize```` either by committing again or removing commit c47602, if that is somehow possible. 
2) Tweak ````CanComputeSize````in such a way that whenever it is a subgroup or a factorgroup of a finite group having size, then is should have ````CanComputeSize````

I have no idea how to do the second one, but I can certainly do the first one, at least by introducing a new commit by removing the check for ````CanComputeSize````. 

Any preferences?

**Comment by hulpke** [comment]
2) will not work: `HasSize` implies `CanComputeSize` but there are groups that happen to know the size, but cannot do so for sub/factor groups.

**Comment by fingolfin** [comment]
It is of course exactly as @hulpke says; in particular, direct products (such as the one that occur in this very example) in general do not permit efficient computation of subgroup sizes. There is no good algorithm implemented for them in any case, so GAP has to resort to enumerating elements of subgroups in order to compute their sizes. Needless to say, this quickly gets very slow.

So your option (2) is simply not an option, it would be wrong. I cannot judge whether option 1 is OK or not.

**Comment by hungaborhorvath** [comment]
#713 does (1) and is merged.
