### ISSUE TITLE
RootFFE does not handle 0; nor roots which require field extensions

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#721]
While working on recog, I discovered that RootFFE was recently added to GAP. I explored using it in recog, but decided against it for two reasons:

1. It fails to compute roots of 0 (admittedly, this is easy to workaround, but still seems like a bug).
2. It does not allow specifying a base field it works. Hence it cannot be used to compute many roots, e.g. consider this example:
```gap
gap> RootFFE(Z(7^2)^24, 2);
fail
```
So perhaps this function should take a field or the size of a field as a third parameter?

**Comment by fingolfin** [comment]
Here is another bug Sometimes `RootFFE` even fails to find roots, even when they are contained in the prime field:
```
gap> RootFFE( Z(13)^8, 16);
fail
gap> (Z(13)^8)^16;
Z(13)^8
```
If this function is to be kept around, and fixed, then I think there really should be an extensive set of test cases added first. I found all of these issues with a relatively simple loop over some fields, elements of those fields, and values r for which I took the r-th root.

**Comment by fingolfin** [comment]
The last example could be fixed by reducing the "root exponent" (or whatever one call this??!), which is  r=16 in that example, modulo `Phi(q)`. But there are other examples where this does not help. E.g. in GF(13), the following three pairs of value and "root exponent" result in `RootFFE` returning `fail`: [ [ Z(13)^3, 9 ], [ Z(13)^4, 8 ], [ Z(13)^6, 9 ] ]

**Comment by fingolfin** [comment]
At this point, I have some doubts whether the current "algorithm" implemented for RootFFE can be rescuved. Perhaps we should investigate the literature on published algorithms for this? For example, google reveals this: https://www.ma.utexas.edu/users/voloch/Preprints/roots.pdf

**Comment by hulpke** [comment]
Yes, you are right that RootFFE should permit a field. The operation was prompted by conversion of Magma code and Magma's syntax (where every element carries a domain with itself) did confuse me. This is changed now.

I've also done a minor fix in the method for FFEs (if the exponent involves coprime powering in the subgroup) -- all examples now run through without problems.

**Comment by fingolfin** [comment]
Nice! BTW, you may want to use GcdInt instead of Gcd (avoids some tiny overhead).
