### ISSUE TITLE
taking Product() of a very long list of transpositions blows up memory

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#723]
Multiplying 370656 transpositions, with disjoint support, in a list s, using Product(s), blows up memory
No matter how big (I went to 10GB!) I set -o, I get (with GAP 4.8.3)

```
 Error, reached the pre-set memory limit (change it with the -o command line option) in
 res[i] := func( C[i] ); at /home/scratch/dimpase/gap/latest/lib/coll.gi:743 called from
 <function "List">( <arguments> )
 called from read-eval loop at line 24  of x.g
```

here is how I get there:
[x.g.txt](https://github.com/gap-system/gap/files/212030/x.g.txt)

PS. I wish there was a function to convert list of lists into a permutation. Of course I can create a list, presenting the permutation I need, and convert it into permutation (or just multiplying 370656 permutations one by one - this took 30 min or so of wall clock time).

**Comment by frankluebeck** [comment]
The first problem is that you probably cannot hold these transposition in memory:

```
gap> MemoryUsage( (300000,300001) );
1200020
```
And, multiplying these permutations is very inefficient (GAP has no data type for sparse partitions (maybe it should?):
```
gap> # instead of:   w:=Product(List(s,y->(y[1],y[2]))); you can avoid the memory problem with:
gap> w := ();;
gap> for y in s do w := w*(y[1],y[2]); od; time;  # will probably take hours
???
gap> # but:
gap> w := [1..741312];;
gap> for y in s do w[y[1]] := y[2]; w[y[2]] := y[1]; od; time;
64
gap> w := PermList(w);; time;
4
```

**Comment by dimpase** [comment]
Ah, OK, thanks, it has not crossed my mind that permutations are never sparse in GAP. Although this kind of usage is a good example of  usefulness of sparse permutations.

**Comment by markuspf** [comment]
For science, I ran the for loop, it took `3604669` milliseconds (so, almost exactly an hour),  according to GAP's `time` on my laptop (Core i5 mobile of some description).

**Comment by markuspf** [comment]
Sparse permutations might be a nice project to instruct a beginner (student or otherwise) in GAP programming (in case noone gets frustrated quickly enough to do it).

**Comment by dimpase** [comment]
I guess it depends upon how far one is willing to take it. There is a
potential advantage of switching over to sparse representation
automatically - the question is how often in practice such a setup arises.

**Comment by fingolfin** [comment]
Closing this, as there is no actual bug here, and all the ideas for enhancements one might derive from it seem to be already logged in various issues.
