### ISSUE TITLE
Add sparse permutations

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#724]
In response to #723 the idea of adding sparse permutations came up. This would probably make a nice project for a sufficiently advanced programmer to be introduced to GAP programming.

**Comment by ChrisJefferson** [comment]
I would personally first working on a sparse list (a sparse permutation is very similar to a sparse list).

The best place to work on such a list would probably be in a package, as that allows more freedom to try out new things and break interfaces.

Such a thing could be built on top of the 'data' package ( https://github.com/gap-packages/datastructures ), which itself needs improving / cleanup.

**Comment by dvberkel** [comment]
I will take a look at the datastructures package

**Comment by fingolfin** [comment]
I've discussed this at some point with @wucas and in the end, couldn't really come up with a convincing usecase for this. I am not saying it doesn't exist, but the thing is that most elements of a "random" permutation group of large degree will be dense. The generators of course can often be chosen sparse, (e.g. take a bunch of transpositions to generate a symmetric group). But for most non-trivial computations, things get dense fairly quickly, and then you end up with a lot of overhead (for using spare perms to represent dense ones; and/or for conversions between the representation) with dubious gains.

In contrast, I still think that accumulators for permutations, integers, rationals, cyclotomics and other things might be quite useful.
