### ISSUE TITLE
distribute InstPackages*.sh in the GAP tarball

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#729]
Having to download this script and change its permissions is a unnecessary chore. Why not just package them in the tarball?

**Comment by alex-konovalov** [comment]
Since it now lives in gap-distribution repository (e.g. https://github.com/gap-system/gap-distribution/tree/master/testing/stable for stable branch), that may be done easier than before. 

Aa proper place to report this would be https://github.com/gap-system/gap-distribution/issues though.

**Comment by dimpase** [comment]
OK, opened it there...
