### ISSUE TITLE
IsSSortedList not correctly set in master 

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#730]
I get the following, in the tip of the master branch at present. I guess this is related to the recent changes in sorting @ChrisJefferson:

    gap> tmp := [ 1, 2, 3 ];;
    gap> IsSSortedList(tmp);
    true
    gap> SortBy(tmp, x -> ((x + 1) mod 3) + 1);
    gap> tmp;
    [ 2, 3, 1 ]
    gap> IsSSortedList(tmp);
    true
    gap> 1 in tmp;
    false

**Comment by ChrisJefferson** [comment]
Thanks, great catch! I know what is to blame, will fix.
