### ISSUE TITLE
Union is broken for collections in the master branch

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#746]
In the master branch I get:

    gap> G := Group((1,2));
    Group([ (1,2) ])
    gap> Union(G, G, G);
    Error, no method found! For debugging hints type ?Recovery from NoMethodFound
    Error, no 1st choice method found for `UniteSet' on 2 arguments at /Users/jdm/gap/lib/methsel2.g:241 called from
    UniteSet( u, tounite[i] ); at /Users/jdm/gap/lib/coll.gi:2751 called from
    <function "Union">( <arguments> )
     called from read-eval loop at *stdin*:36
    you can 'quit;' to quit to outer loop, or
    you can 'return;' to continue
    brk>

Whereas in stable-4.8, I get:

    gap> G := Group((1,2));
    Group([ (1,2) ])
    gap> Union(G, G, G);
    [ (), (1,2) ]

**Comment by james-d-mitchell** [comment]
Postscript: I think this has been broken for a while. In the Semigroups package, we do something list:

    Union(List(Something(S), x-> SomethingElse(x, 43)));

in several places, and whenever `Something(S)` has more than two elements in it, the above error occurs.

**Comment by markuspf** [comment]
This was introduced by a few commits that changed the behaviour of `Union`. The fact that there is no method found was introduced in f609ef51 whereas even before (2fafd07) that the behaviour had changed to the following
```
gap> G := Group((1,2));;
gap> Union(G,G,G);
Group([ (1,2) ])
```

The original new Union implementation yielded the same result as `stable-4.8`.
