### ISSUE TITLE
Update profile.c to use NanosecondsSinceEpoch

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#749]
At the moment `profile.c` uses `gettimeofday`. I think using `NanosecondsSinceEpoch` is the cleaner approach now.

**Comment by ChrisJefferson** [comment]
I'll look at this -- my only concern is that it is important that no code gets run which could itself cause the profiler to execute, else we get stuck in an infinite loop (that's why the profiler has to do all the file I/O by itself).

**Comment by markuspf** [comment]
Mhm, if calling `FuncNanosecondsSinceEpoch` (which uses some of the GMP arithmetic to construct the nanoseconds) is too dangerous, we could factor out the code that calls into the OS and return some long enough integer (64 bits should be enough), use that and provide that integer to the GAP level appropriately?

**Comment by ChrisJefferson** [comment]
That would be OK and (quick check) a 64-bit integers nanoseconds gets us 500 years, long enough for GAP :)

**Comment by ChrisJefferson** [comment]
Let me try doing this (extraction) and #750 at the same time

**Comment by ChrisJefferson** [comment]
sorted
