### ISSUE TITLE
Given a positional object, how to make an immutable copy in the public region?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#75]
It seems there are some fundamental difference in the way HPC-GAP handles component objects vs. positional objects. The former seem to be automatically in the public region:
```
gap> fam := NewFamily("foo");;
gap> comType := NewType( fam, IsComponentObjectRep );;
gap> comObj := Objectify( comType, rec(a:=1, b:=2, c:=3) );;
gap> RegionOf(comObj);
<region: public region>
```
Not so for positional objects, they are put into a thread local region:
```
gap> fam := NewFamily("foo");;
gap> posType := NewType( fam, IsPositionalObjectRep );;
gap> posObj := Objectify( posType, [1,2,3] );;
gap> RegionOf(posObj);
<region: thread region #0>
```
Unfortunately, not even taking an immutable copy helps (perhaps not surprising, since IS_MUTABLE_OBJ and IsMutable return false for posObj anyway):
```
gap> RegionOf(`posObj);
<region: thread region #0>
```

The only way to get a positional object in the public region that I found is to pass an immutable list to `Objectify`:
```
gap> posObj := Objectify( posType, `[1,2,3] );;
gap> RegionOf(posObj);
<region: public region>
```

But in actual code, this is not always an option. E.g. when dealing with collectors and rws groups: The collectors are positional objects. Initially, they are created mutable. Later, one creates an immutable copy. But due to the above behavior, that copy is in a thread local region, which is annoying.

I tried to use `MakeReadOnly` on those objects as a workaround, but that doesn't really help, as it doesn't seem to recurse to the subobjects.

**Comment by markuspf** [comment]
There is `IsAtomicPositionalObjectRep` to get an object in the public region (where accesses to positions are guarded), but you have to be careful with subobjects and multiple assignments. There's also `IsReadOnlyPositionalObjectRep`. 

```
gap> fam := NewFamily("foo");;
gap> posType := NewType( fam, IsAtomicPositionalObjectRep);  
NewType( NewFamily( "foo", [  ], [  ] ), [ 38, 43 ], fail )
gap> posObj := Objectify( posType, [1,2,3] );;             
gap> RegionOf(posObj);
<region: public region>
```

**Comment by alex-konovalov** [comment]
@markuspf thanks, was about to write the same. To complete the picture, to define datatypes that can be stored in thread local regions it is necessary to use `IsNonAtomicComponentObjectRep`, or `IsReadOnlyPositionalObjectRep`, for example:
```
BindGlobal( "IsTFam", NewFamily( "IsTFam" ) );
DeclareCategory( "IsTCat", IsNonAtomicComponentObjectRep);
DeclareRepresentation( "IsTTypeByDefault", IsTCat, ["test"] );
BindGlobal( "TType", NewType(IsTFam, IsTCat and IsTTypeByDefault) );
```

**Comment by fingolfin** [comment]
This still leaves me wondering as to why component objects are by default in the public region, but positional objects are not?

**Comment by stevelinton** [comment]
That was a design decision. If you Objectify a record you get by default an atomic component object, if you objectify a list you get a non-atomic positional object. The rationale was that positional objects are typically used for elements and can often be read-only. Often they have no writeable subobjects by construction. Component objects are typically attribute storing and are often shared algebraic structures like groups. The other two possibilities exist, but these seemed the most useful defaults. 

The collector code is relatively unusual in having these large writable structures in a positional object.

**Comment by stevelinton** [comment]
Clearly more documentation is needed.

**Comment by fingolfin** [comment]
So it is still not clear to me how to make an positional immutable -- do I really have to write a function which iterats over all bound entries in the object, copies them to a new list, then makes that list immutable, then invokes Objectify on it?

Nativel, I would expect `Immutable` to do exactly that... But even if there is some reason it doesn't, wouldn't it be still useful to have such a function around?

**Comment by alex-konovalov** [comment]
I think you have to use `MakeReadOnly` for that. For example, consider the library code from `cyclotom.g` which does that:
```
BIND_GLOBAL( "infinity",
    Objectify( NewType( CyclotomicsFamily, IsInfinity
                        and IsPositionalObjectRep ), [] ) );
MakeReadOnly(infinity);
```
Let's try this on your initial example above:
```
gap> fam := NewFamily("foo");;
gap> posType := NewType( fam, IsPositionalObjectRep );;
gap> posObj := Objectify( posType, [1,2,3] );;
gap> RegionOf(posObj);
<region: thread region #0>
gap> MakeReadOnly(posObj);
<object>
```
Now we have the expected behaviour:
```
gap> RegionOf(posObj);
<region: read-only region>
gap> RegionOf(posObj![1]);
<region: public region>
```

**Comment by stevelinton** [comment]
It might be worth walking through the variations of atomic and read-only and regular objects of all three types (component, positional and data) and the functions for converting between them this afternoon. At least to produce a clear document, but maybe to identify any final changes we want to make.
