### ISSUE TITLE
Polynomials in different characteristic can be added

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#757]
While researching another issue, I stumbled upon this:
```
gap> t:=Indeterminate(GF(7), "t");;
gap> x:=Indeterminate(Cyclotomics, "x");;
gap> d:=x^2-t+1;
x^2+(-t+Z(7)^0)
gap> Characteristic(d);
0
```
Oops.
I would have expected a "no method found" error, or even better, an error saying something like "ring elements in different characteristic cannot be added".

Returning a mathematical invalid object is certainly not a good alternative.

It goes on:
```
gap> Characteristic(d);
0
gap> d + d;
Z(7)^2*x^2+0*Z(7)*x+(Z(7)^5*t+Z(7)^2)
gap> Characteristic(d + d);
0
```

Finally, trying to compute `x/d` seems to lead to an infinite loop (but that is probably fair, the method there receives invalid objects as input

**Comment by hulpke** [comment]
This was code that allowed embedding of coefficient rings and rationals (to allow constructions such as `X(PolynomialRing(GF(5),1))+Z(5)+4/3` to work). I have added tests now and this will win into an error now.

**Comment by hulpke** [comment]
Stupid github question: I thought the reference to this issue in the fix would have closed it after merging. Did I miss something or do I misunderstand this feature?

**Comment by alex-konovalov** [comment]
@hulpke could happen that this only works for the master branch: https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by hulpke** [comment]
As this is resoolved, close issue
