### ISSUE TITLE
RootMod on newer versions of gap

### ISSUE THREAD

**Issue by pedritomelenas** [gap-system/gap#758]
I was teaching `RootMod` in the computer classroom and an student came to me with the following example. He was puzzled that for the first time (Miller-Rabin and other stuff) his own implementation was faster than that of GAP.

```
c := 87665785060273447596735547586847436354365986897267;
d := 5676193656034756392656593936564928264920283748503726385950382638505826243749593626948538293405737101;
gap> RootMod(c,d);time;
fail
69688
```

The above example was executed in noether (St. Andrews, with GAP 4.8.1). If you execute it twice, then it takes nothing. Even if you change c to get a positve answer

```
gap> c := 87665785060273447596735547586847436354365986897267+12;
87665785060273447596735547586847436354365986897279
gap> RootMod(c,d);time;
277281960068688920231110666322684535614170829118408321537065593309824476399230514\
2689466354417560800
0
```

In my old laptop with GAP Version 4.7.4, the output takes 0 milliseconds, even in the first call. So the problem seems to reproduce in newer versions of GAP.

I wonder if RootMod is checking if d is (psedo)prime, and if Jacobi(c,d)=1 or not. Is the newer version loading something the first time `RootMod` is called? Am I doing something wrong?

Thanks,
Pedro

**Comment by fingolfin** [comment]
I cannot reproduce this problem with the current git master branch of GAP. Granted, the computations still 35 milliseconds on my laptop, but not 70 *seconds* as in your example.

What happens if you start gap with `-A`? Also, perhaps upgrade to GAP 4.8.3?

**Comment by pedritomelenas** [comment]
Max,
Thanks for the reply. Yes, with `-A` it takes 100 milliseconds. 
The thing seems to happen in 4.7.9 (my student's gap version) and 4.8.1 (cloud.gap-system.org).
I will check at home with the git version.
Thans

**Comment by pedritomelenas** [comment]
Just in case it helps. The funny thing is that my old version of gap only loads  GAPDoc 1.5.1, IO 4.2, and it is quit fast doing RootMod...
With -A as suggested by Max in noether (cloud.gap-system.org), it is also really fast.
Thanks,
Pedro

**Comment by bh11** [comment]
Seems to be related to the FactInt package. When it's loaded, `FactorsInt(d)` takes a long time, and interrupting GAP shows FactInt code at work. Perhaps @Stefan-Kohl can have a look.

**Comment by Stefan-Kohl** [comment]
The issue is that the function ´PrimalityProof_FindStructure' interprets the FactInt option `FactIntPartial', and makes it depend on this option how to proceed.
I can't tell what the rationale behind this is, and I don't know the algorithm used.
It seems that in one case the function tries to factor d-1 which is hard, and in the other it tries to factor d+1 which is cheap, and it seems possible to obtain a primality proof for d in both ways.
Maybe the author of the primality testing code should look into this.

**Comment by Stefan-Kohl** [comment]
Another question is why RootMod needs to prove primality of any large integer at all if it can find a root as requested also otherwise (a factorization into BPSW pseudoprimes should be enough, shouldn't it?).

**Comment by pedritomelenas** [comment]
Yes, in this case it is even simpler. A primality test on d would be enough (d is prime), and then apply the algorithm for finding square roots of c mod d. Indeed for the first c, Jacobi(c,d)=-1, and thus `fail` without any factorization in between.
```
gap> IsPrimeInt(d);
true
```

**Comment by Stefan-Kohl** [comment]
But IsPrimeInt IS the culprit here! -- Just sometimes it factors d+1 which is cheap for this particular d, and sometimes it factors d-1 which takes time for this particular d.

**Comment by pedritomelenas** [comment]
Uhm.. And why not a Miller-Rabin or something of the sort?

Enviado con Aquamail para Android
http://www.aqua-mail.com


El 21 de abril de 2016 6:20:38 p. m. Stefan Kohl <notifications@github.com> 
escribio:

**Comment by Stefan-Kohl** [comment]
That's just what I suggested. -- IsProbablyPrimeInt does a combination of Miller-Rabin and a similar other test for which at present no composites are known which are not recognized as such
 -- cf. https://en.wikipedia.org/wiki/Baillie%E2%80%93PSW_primality_test.

**Comment by fingolfin** [comment]
Digging into "forgotten" issues...

So to fix this, we could indeed modify  `RootMod`, and make it pass the `UseProbabilisticPrimalityTest` option to `FactorsInt`. Then we know that `p` is a BPSW pseudoprime for sure. But that alone is not enough: `RootModPrime` requires that `n` is a Fermat pseudo-prime to a certain base, but BPSW only ensures this for base 2. The solution is simple, though: We can just add an explicit test to see if `n` satisfies `n^(p-1)=1 (mod p)`. If yes, all is fine, and we go on; if no, we either found a bug (more likely) or a BPSW pseudo-prime; in any case, we just raise an error.

I'll see if I can implement the required change.

**Comment by pedritomelenas** [comment]
Thanks
