### ISSUE TITLE
Hap: loading of Hap fails if SmallGroups are not installed

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap#775]
loading of Hap fails with an error in 
`line 162 of pkg/Hap1.11/lib/HapCocyclic/gap/ccgroup.gi`, saying 

```
 Error, <opr> is not an operation called from
 <compiled or corrupted statement>  called from
 <function "local function">( <arguments> )
 called from read-eval loop
```

Line 162 is the last line of 

```
 InstallMethod
 (  IdGroup,
 true,
 [ IsCcGroup ],
 0,

  function( Cc )
     return IdGroup( Image(IsomorphismPermGroup(Cc)) );
 end
 );
```

Indeed, without SmallGroups installed `IdGroup` is a function, not an attribute. Probably this means that Hap misses a dependence.

**Comment by alex-konovalov** [comment]
There is no package "SmallGroups", and the Small Groups library is a part of the core GAP system. How could it happen that one attempts to load HAP in such system?

**Comment by markuspf** [comment]
This happens because in `init.g` (of the GAP library) `IdGroup` is assinged `NONAVAILABLE_FUNC` (which is a function), then, if `smallgroups` is loaded, `IdGroup` is unbound and bound as an attribute for groups.

One (clean) solution would be to declare the attribute `IdGroup` for groups in the GAP library.

**Comment by dimpase** [comment]
@alex-konovalov : given that Small Groups has a separate, non-GPL-compatible, license (see http://gap-system.org/Packages/sgl.html), it cannot be a part of core GAP system, de juro at least... In Sage Small Groups live in an optional package, and might not always be installed.

**Comment by dimpase** [comment]
ideally, they could have been resolved by making the license in question reasonable; (forbidding distribution of modified sources in case of mathematical data is so wrong on many counts...).
But yes, changing the initial `IdGroup` setting to allow extendability would be great too.

**Comment by markuspf** [comment]
Lets accept the reality of the licenses and move on.

**Comment by markuspf** [comment]
Actually, since IdGroup is the smallgroups numbering, anyone who'd want to install methods here other than the small groups library should be required to keep the smallgroups numbering intact (or we forbid others to fiddle with `IdGroup`).

**Comment by dimpase** [comment]
Naturally, people want `IdGroup` not to be restricted to what's "natively" supported, as you see in the code snippet from Hap above.

**Comment by alex-konovalov** [comment]
As far as I understand the snippet, it simply converts the group to the more efficient representation first, so this method does not change the numbering. Perhaps we could ask the author to rename it in HAP to e.g. `IdIsomorphismPermGroup` instead.

**Comment by dimpase** [comment]
Why would one want to rename? GAP already has way too many names for basically identical things...

**Comment by fingolfin** [comment]
To resolve this, I guess we should ask Graham to add the new smallgrp package as a dependency to HAP?

**Comment by alex-konovalov** [comment]
@fingolfin yes. This is the right thing to do, although there is no any urgency of this since SmallGrp is a needed package in GAP 4.9. In general, we need to say this to all package authors when we will provide 4.9 beta - if your package depends on one or more of SmallGrp/PrimGrp/TransGrp, document that explicitly in package dependencies.

**Comment by dimpase** [comment]
I've noticed that 4.9 has (quietly?) made SmallGroups and TransGroups GPL-compatible. This is **great**, and I take the liberty to close this issue.

**Comment by alex-konovalov** [comment]
Good! Perhaps you missed that because they are now proper packages:
- https://github.com/gap-packages/smallgrp/issues/7
- https://github.com/hulpke/transgrp/issues/7
