### ISSUE TITLE
Self-check at startup

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#776]
Taking into account that some third-party GAP distributions (e.g. Sage or Debian) change the structure of the distribution and split it into separate packages, which are very often missing in default installations, I suggest to add a kind of a self-check when GAP starts. It could check for the presence of the data libraries and packages usually loaded by default, and display a warning in case these are missing. The warning could list missing components and suggest to either download the source distribution from the GAP website or check with the installer providers what is the way to add missing components.

**Comment by hulpke** [comment]
I think this is a good idea, however I wonder whether some distributors then would simply disable such a warning to make GAP "work" with their installation.

**Comment by alex-konovalov** [comment]
Hmm, should they document in this case that they have changed the core GAP system and suppressed that warning?

**Comment by frankluebeck** [comment]
I would not support such a self-check.

The pratice of some re-distributers of GAP only shows once more how sensible it is to move the remaining libraries in core GAP to proper packages. Maybe the Debian maintainer have already done most of the work that is needed for a proper SmallGroups package? Then there is no need for any special self-check because the usual package dependencies can be used.

**Comment by markuspf** [comment]
I doubt that the distributors have done any work, after all the license of the
small groups library states that one must not alter it.

If we can convince the authors of the small groups library that the change to
a package is sensible, then I support this.

(As far as I remember the condition to not change the small groups library is
about keeping the data and numbering of the small groups consistent, so in
theory this should not be a problem).

**Comment by markuspf** [comment]
As a followup: I made the `small` directory into a package, which isn't that hard, but a bit fiddly. I can contact the authors of the small groups library to ask whether they would like to release the small groups library in that format as a package (I did most of the work I think, mostly we'll have to test everything still works and gives the expected results).

**Comment by alex-konovalov** [comment]
@markuspf of course, in this case, also we will need the package manual... I am happy to help to that.

**Comment by dimpase** [comment]
@alex-konovalov : the problem you mention stems from the fact that GAP plays fast and loose with licensing issues, making a false impression that a default install consists of GPL-compatible parts. Distributions that take the licensing issue seriously have to play safe. (By the way, the self-check you propose probably violates GPL, if not in letter, then certainly in spirit).

**Comment by dimpase** [comment]
@markuspf : the SmallGroup library license has an effect of stalling any GAP software work in the area, (unless it originates from within SmallGroup authors' circle). Indeed, suppose X has a good student seriously willing to improve algorithms in SmallGroup. It's a no-starter, unless X manages to secure some kind of guarantee from SmallGroup authors that they would take up improvements and release them.

**Comment by alex-konovalov** [comment]
@dimpase: Let's do one step at a time. Moving data libraries (not only small, but also prim and trans) into proper packages is the move in the right direction anyway. And the self-check is because we don't want GAP to be blamed to be slow or non-functional when the core system happened to be unassumingly installed without packages that speed up or extend its functionality.

**Comment by alex-konovalov** [comment]
@frankluebeck: A self-check would be a simple and implementable solution, which does not depend on the policies used by the 3rd party providers. As https://packages.debian.org/sid/math/gap shows, Debian splits GAP into components classified as "depends", "recommends", "suggests", and the meaning of these is explained at https://www.debian.org/doc/debian-policy/ch-relationships.html. As we see, e.g. tables of marks and character tables are suggested, and small groups is split into two parts, one recommended and one suggested.

**Comment by dimpase** [comment]
@alex-konovalov : rest assured that if GAP were to put this sort of check anywhere, Sage would not display it :-) Besides, you essentially suggest that GAP displays a misleading ad for its website...

**Comment by alex-konovalov** [comment]
This was implemented in #788 which was the closed without merging, so I am closing this issue too.
