### ISSUE TITLE
Tests don't fail, even though they probably should

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#786]
This is related to #785, in `tst/testinstall/trans.tst` we find the following line

```
gap> PermLeftQuoTransformationNC((), IdentityTransformation);
Error, PermLeftQuoTransformationNC: the arguments must both be transformations\
 (not permutation (small) and transformation (sm
```

These tests pass, even though the error message is truncated.

**Comment by ChrisJefferson** [comment]
This will be fixed by #799 (I also fixed those tests at the same time, which began failing)
