### ISSUE TITLE
Making a package for Transitive Permutation Groups Library

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#792]
This library (http://www.gap-system.org/Datalib/trans.html) should become a proper package, loadable via `LoadPackage`. The library is in the separate `trans` directory, and the documentation is already in GAPDoc format at http://www.gap-system.org/Manuals/doc/ref/chap50.html#X7FBB970F7D110FDB.

For the beginning, I suggest to make it needed package for GAP for backwards compatibility (so GAP will not start without it). Packages that rely on it (Browse, maybe more) would then be able to include it in their dependencies. Eventually we will put it into the list of packages loaded by default but not needed to start GAP. 
- License: GPL v2
- Authors: @hulpke as stated at http://www.gap-system.org/Datalib/trans.html
- package name: "trans" or "TransitiveGroups" or "TransitiveGroupsLibrary"? My current choice is "TransitiveGroups" as the name of the directory (note that `LoadPackage("trans");`) will still work as long as there is no other package started with "prim"). Any other opinions?

I am happy to do the conversion which is pretty straightforward. I am setting GAP 4.9.0 as a milestone and assigning it to myself.

**Comment by hulpke** [comment]
If there is a desire to make this a package I can do so over the summer, though I  see little benefit from the change. As the library uses the transitive groups functionality extensively some declarations will have to move to the library, also the package should autoload (thus the name is not really an issue and I'm happy with `TransitiveGroups').

The license definitively should not be GPL, but something analog to the small groups library -- the reason for this is the bad experience I heard (from the small groups library and from OEIS) about other software aggressively repackaging data libraries and potentially introducing problems.

**Comment by ChrisJefferson** [comment]
I wonder if it would be possible (or a good idea?) to try to seperate out the 'data library' part of the small groups library / transitivegroups, and the code.

We could place the code under the GPL, while the data files (which would not be code) could be under another licence. This might make things smoother (although it is just moving things around). Also, it would make later (small) changes to the code easier, and mean the library could be more easily used by non-GAP systems.

**Comment by markuspf** [comment]
On Mon, May 16, 2016 at 09:51:14AM -0700, Christopher Jefferson wrote:
> I wonder if it would be possible (or a good idea?) to try to seperate out the
> 'data library' part of the small groups library / transitivegroups, and the
> code.

The problem is that there is not such a clear distinction between code and
data. Sure there are some datafiles, but there is also code that works for all
groups of order p * q * r say, for p,q,r being distinct primes.

Cheers,
Markus

**Comment by ChrisJefferson** [comment]
OK, scratch that idea.

**Comment by alex-konovalov** [comment]
This may be closed after merging #1650.

**Comment by alex-konovalov** [comment]
The package TransGrp now resides here: 
  * repository: https://github.com/hulpke/transgrp
  * website: http://www.math.colostate.edu/~hulpke/transgrp/
and `trans` directory has been removed in #1650.
