### ISSUE TITLE
TransitiveGroup(1,1) fails

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#797]
### Observed behaviour
```
gap> NrTransitiveGroups(1);
1
gap> TransitiveGroup(1,1);
Error, List Element: <list>[1] must have an assigned value in
  l[5] := BlistStringDecode( l[5], TRANSPARTNUM[deg] - 1 ); at /Users/caj/reps/gap/gap/trans/trans.grp:323 called from
TRANSProperties( deg, num ) at /Users/caj/reps/gap/gap/trans/trans.grp:355 called from
<function "TransitiveGroup">( <arguments> )
 called from read-eval loop at *stdin*:10
you can 'return;' after assigning a value
```

### Expected behaviour
I get the transitive group on one point (the identity group), or return `fail` for NrTransitiveGroups(1)
### Copy and paste GAP banner (to tell us about your setup)
 GAP v4.8.3-643-g3460711-dirty of 2016-05-11 09:25:22 (BST)

This at least hasn't worked since 4.7.2

**Comment by hulpke** [comment]
The transitive group of degree 1 is always awkward, as the trivial group is in fact transitive of degree 0. Thus my inclination would be to return 0 (or fail).

**Comment by hulpke** [comment]
This is corrected in my `fixes' branch and will go in stable the next time I merge.

**Comment by alex-konovalov** [comment]
@hulpke - thanks : only suggest to wait for GAP 4.8.4 which should be there in a couple of days....
