### ISSUE TITLE
Allow GAP to find it's own library / make it easier to move GAP

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#803]
This issue is for pull request #802, but I thought I just put it here for people who don't read pull requests directly.

Short version: At the moment users must always pass in GAP's library location with the `-l` option. With this patch, GAP tries looking in whatever the directory the executable is in, and it's parent directories (which would normally find GAP's library).

The complicated part of the patch is finding where an executable is based, there are a number of OS-specific ways of doing this (there is an alternative, generic way where we look at `argv[0]`, but that is very hard to get right).

With this patch, we could (in principle) remove `gap.sh`, and just sym-link the `gap` executable, or encourage users to do so.

At the same time, I also added a `GAPROOT` environment variable which GAP will look in as well for it's library path.

**Comment by fingolfin** [comment]
Resolved by #1951
