### ISSUE TITLE
Different categories can have the same name

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#809]
Currently it is possible to do the following

```
gap> c1 := NewCategory("IsSilly", IsObject);
<Category "IsSilly">
gap> c2 := NewCategory("IsSilly", IsObject);
<Category "IsSilly">
gap> c1 = c2;
false
```

Of course this doesn't happen if one uses `DeclareCategory`, because then the global variable `IsSilly` is already bound.

And while one can find arguments for this being entirely valid, I think categories should be identified by unique names (and we should enforce this).

What do people think?

**Comment by hulpke** [comment]
Blocking this would cause complications fro Reread, I think.

**Comment by markuspf** [comment]
I noticed that there's a different issue at play here, namely that GAP allows (and encourages) overloading heavily. This poses no problems in GAP itself (its a feature to be able to overload names after all).

The absence of externally unique identifiers causes problems with a project we're working on:  automatic interfacing between computer mathematics systems. I now think this needs to be resolved in a different way from trying to enforce rules on GAP.

**Comment by fingolfin** [comment]
I think the outcome here was that we can't do much about it at this point in GAP.

Closing this. Please reopen with additional information if I am wrong.
