### ISSUE TITLE
`List` silent swallows arguments after the second

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#820]
### Observed behaviour
```
gap> List([1,2,3], x -> x + 1, "some", "random", "extra", "arguments");
[2,3,4]
```
### Expected behaviour
GAP complains about the extra arguments

**Comment by grouptheoryenthusiast** [comment]
Hi, I am a newcomer and would like to try this project, to help familiarise myself with the workings of GAP and Github.  I was able to edit the code so that GAP  throws an Error("Usage:...") in this case, but I wondered if this was the correct type of error to throw?
Thank you

**Comment by ChrisJefferson** [comment]
I think so. The current error for `List()` should probably be extended to also cover the longer version.

Be sure to write a number of tests to make sure we catch the various types of errors (it should probably also test 0 arguments, which I suspect is not currently tested).

**Comment by ChrisJefferson** [comment]
One difference, should probably use `ErrorNoReturn`. That is like `Error`, except you can't return (which doesn't make sense in most situations). I would change the existing `Error` to `ErrorNoReturn` as well, because returning doesn't really make sense!

**Comment by grouptheoryenthusiast** [comment]
Hi Chris, thank you for your reply. I will look into these things.

**Comment by grouptheoryenthusiast** [comment]
If I make a test file called List.tst and put this in the tst  /teststandard directory,  do I need to do anything else to make GAP aware of this file or are does GAP just go through each .tst file in the directory. Thank you.

**Comment by ChrisJefferson** [comment]
GAP will just iterate through these directories, so just popping it in should be fine.

**Comment by grouptheoryenthusiast** [comment]
Hi Chris, thank you for your help with this! I have changed Error to ErrorNoReturn, but now when I start GAP, before the usual GAP banner I get:
`Syntax warning: unbound global variable in /proc/cygdrive/C/gap4r8/lib/coll.gi line 731
      ErrorNoReturn( "usage: List( <C>[, <func>] )" );
`
I have found discussion of a similar problem in the GAP forum archive, the suggested solution was to use:
`if not IsBound( GlobalStuff ) then
GlobalStuff := fail;
fi;`

Is this still the preferred work around?

Apologies for all the questions on something that I feel should be easy! I am learning a lot.

**Comment by alex-konovalov** [comment]
@grouptheoryenthusiast : thanks for looking at this! It seems to me that `testinstall/listgen.tst` is a natural place to add a test, so there is now need to create a new test file just for this PR. 

Also, although this may be undocumented, all test files have names in lowercase, so I would suggest to follow that convention.

**Comment by grouptheoryenthusiast** [comment]
Thank you for the reply and advice @alex-konovalov . Can you advise what is the best way to deal with the
`Syntax warning: unbound global variable in /proc/cygdrive/C/gap4r8/lib/coll.gi line 731 ErrorNoReturn( "usage: List( <C>[, <func>] )" );`
 warning that appears before the GAP banner, if I replace` Error` with `ErrorNoReturn` in `coll.gi` .

Thank you.

**Comment by ChrisJefferson** [comment]
I'm going to investigate fixing that this afternoon. I think I know what's wrong.

**Comment by ChrisJefferson** [comment]
This will be fixed by #841 , which should get merged in shortly -- basically `Error` gets defined earlier in GAP's startup, I made sure `ErrorNoReturn` gets defined at the same time!

**Comment by grouptheoryenthusiast** [comment]
Thanks @ChrisJefferson and @alex-konovalov . I appreciate all the effort you have put into helping me. I hope to contribute to GAP throughout the course of my PhD so I hope this is a worthwhile investment. :)

**Comment by alex-konovalov** [comment]
@grouptheoryenthusiast thanks to you too, you're very welcome! If you're a PhD student based in the UK, I suggest to get in touch with me by email - we are planning an event similar to http://www.codima.ac.uk/school2015/ in October this year.

**Comment by ChrisJefferson** [comment]
@grouptheoryenthusiast : You should (hopefully!) find your patch now works fine after updating.

I recommend learning about 'rebase', rather than 'merge', as it leads to a cleaner history.. if you get your code updated and rebased, you have learn the most painful git features at that point (git can be a bit horrible, if you haven't used it much).

**Comment by grouptheoryenthusiast** [comment]
Thanks for the advice Chris, I 'rebased' the fork I have issued the pull request for (I hope...) You are right that git can be a bit horrible at times, I still have a lot to learn with it.
