### ISSUE TITLE
Range of restricted degrees in AllPrimitiveGroups

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#832]
This comes from testing #818.

### Observed behaviour
```
gap> AllPrimitiveGroups(NrMovedPoints,10000);
#W  AllPrimitiveGroups: Degree restricted to [ 1 .. 2499 ]
[  ]
```
but
```
gap> PrimitiveGroup(1,1);
Error, There are only 0 groups of degree 1
 called from
PRIMGrp( deg, num ) at /Users/alexk/gap4r8p4/prim/primitiv.gi:81 called from
<function "PrimitiveGroup">( <arguments> )
 called from read-eval loop at line 9 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```
### Expected behaviour

The error message should say that the degree is restricted to [ 2 .. 2499 ]

**Comment by alex-konovalov** [comment]
I have used MAGMA online calculator to get the number of primitive groups of all degrees up to 4095:
```
[NumberOfPrimitiveGroups(i) : i in [1..4095]]
```
All number agreed with those already in the primitive group library or provided by this pull request, except that GAP reports that there are zero primitive groups of degree one, and MAGMA says there is one.

**Comment by colva** [comment]
I suggest adjusting the error message to [2..2499].

**Comment by alex-konovalov** [comment]
Done this in my fork already - will submit a PR at some point.

**Comment by alex-konovalov** [comment]
This is now in PR #851 - please review it and leave comments there.
