### ISSUE TITLE
Problem with AllHomomorphisms and Free groups

### ISSUE THREAD

**Issue by ThGroth** [gap-system/gap#836]
I experienced some problems using the function AllHomomorphismClasses() with a free group as first argument.  

### Observed behaviour
The calculation of:
```
F2 := FreeGroup(2);
S3 := SymmetricGroup(3);
AllHomomorphismClasses(F2,S3);
```
doesn't stop. 

But if I alter the last line in the definition of the function AllHomomorphismClasses to
```
emb := MorClassLoop( G, bi, params, 8 );
Info( InfoMorph, 2, Length( emb ), " homomorphisms" );
return emb;
```
So changing the 9 to a 8. It gives the expected result. 

Furthermore in some special cases the function returned an empty list given a free group as first argument and a finite group as second. Unfortunately I could't come up with in easy to reproduce example. 

### setup
 ┌───────┐   GAP 4.8.3, 19-Mar-2016, build of 2016-04-20 10:15:48 (CEST)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp
 Loading the library and packages ...
 Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.0, AutPGrp 1.6, 
             CRISP 1.4.3, Cryst 4.1.12, CrystCat 1.1.6, CTblLib 1.2.2, 
             FactInt 1.5.3, FGA 1.3.1, FR 2.2.0, GAPDoc 1.5.1, GBNP 1.0.3, 
             IRREDSOL 1.2.4, LAGUNA 3.7.0, Polenta 1.3.6, Polycyclic 2.11, 
             RadiRoot 2.7, ResClasses 4.4.2, Sophus 1.23, SpinSym 1.5, 
             TomLib 1.2.5, Utils 0.39

**Comment by markuspf** [comment]
Thanks for the report. Actually looking at the documentation of `MorClassLoop` in `morpheus.gi` reveals that replacing 9 by 8 is the correct fix in this situation.

Additionally I suggest adding a check for the input argument `action`.

**Comment by markuspf** [comment]
If only I could read properly. While trying to fix this I noticed that the options of 1,2,4, and 8 for "action" are supposed to be bit representations. I'll have a closer look.

**Comment by markuspf** [comment]
I think @hulpke will be better qualified to find a quick fix. I'll wait for his feedback.

**Comment by hulpke** [comment]
I'm not sure what the suggestion refers to. In 4.8.4, the lines in the library are:

    emb:=MorClassLoop(G,bi,params,
    # all homs = 1+8
    9);

The non-termination is because AllHomomorphismClasses was written with finite groups in mind and does quick tests for element orders -- I'll exclude infinity  to make it work there as well for 4.9.
Ditto for the fact that the free group has no relators for GQuotients.
