### ISSUE TITLE
Performance regression in teststandard/small_groups2.tst?

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#846]
Looking at the travis-ci builds recently, there is a two-fold slowdown between the linux/gcc and the osx/clang test of `small_groups2.tst`.

**Comment by fingolfin** [comment]
It is unclear to me whether this is really a bug, or a case of travis performance fluctuating quite heavily.

Also, it is not quite clear to me when exactly (which date?!) that regression supposedly happened; that would be very useful information to have in this report :-).

**Comment by fingolfin** [comment]
There is not enough information in this issue to act upon.
