### ISSUE TITLE
Profiling misses lines in records

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#857]
In the following code, profiling marks the lines with a '#' as read, but not executed. Need to investigate why.

```gap
f := function()
    local r;
    r := rec(
        x := [], #
        y := [], #
        z := []
    );
    return r;
end;
```

**Comment by alex-konovalov** [comment]
@ChrisJefferson any progress?

**Comment by ChrisJefferson** [comment]
I know why it happens, I'm not sure how to fix it...

**Comment by fingolfin** [comment]
Is this actually a bug in GAP, or in `profiling`? Perhaps it should be moved to the `profiling` tracker?

**Comment by fingolfin** [comment]
@ChrisJefferson status?

**Comment by ChrisJefferson** [comment]
Has been fixed.

Some lines in records are mapped as neither read or executed, because we handle records specially, rather than making a Stat or Expr for every line, but there is at least one executed line in a record, and no inconsistencies.
