### ISSUE TITLE
After merge of #861, remove redundant  IsIdenticalObj(x, IsObject) tests 

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#865]
After I merged #861, we should remove the redundant tests for IsIdenticalObj(x, IsObject) from the library.

**Comment by alex-konovalov** [comment]
You likely mean not the issue #861, but PR #863 which fixes it.

**Comment by fingolfin** [comment]
PR #863 was merged half a year ago. Then again, I see no checks of the form `IsIdenticalObj(x, IsObject)` in the library -- there was one, removed by PR #863, and I see no sign that there were ever more...

So I am closing this. Feel free to re-open if you think I missed something.
