### ISSUE TITLE
polycyclic: IsConjugate for pcp groups returns element instead of boolean

### ISSUE THREAD

**Issue by ThGroth** [gap-system/gap#874]
### Observed behaviour

As verified in the code the method IsConjugate for polycyclic groups (pkg/polycyclic-2.11/gap/pcpgrp/centcon.gi:328) returns not a boolean but in some cases the conjugator.
For example:

```
H := DihedralPcpGroup( 0 );
IsConjugate(H,One(H),One(H));
```

returns "id" instead of "true"

Perhaps the method should be changed to

```
 InstallMethod( IsConjugate, "for a pcp group", IsCollsElmsElms, [IsPcpGroup, IsPcpElement, IsPcpElement],
      function( G, g, h )
           return not false = ConjugacyElementsBySeries( G, g, h, PcpsOfEfaSeries(G) );
 end );
```

GAP 4.8.3, 19-Mar-2016, build of 2016-04-20 10:15:48 (CEST)
Architecture: x86_64-pc-linux-gnu-gcc-default64

**Comment by markuspf** [comment]
While this is a bug, and the fix seems to be the correct one, this is a bug in the polycyclic package. @fingolfin would you be able to fix this?

**Comment by fingolfin** [comment]
Yes, this should get fixed in polycyclic. Ahh, I wish I had a public bug tracker for that.. Gotta talk to Bettina about this

**Comment by alex-konovalov** [comment]
This issue is migrated to https://github.com/gap-packages/polycyclic/issues/18. Thank you @ThGroth for reporting it.
