### ISSUE TITLE
Bug with new fp code in IsomorphismFpGroupByGeneratorsNC

### ISSUE THREAD

**Issue by laurentbartholdi** [gap-system/gap#887]
Observed behaviour
-----------------

```
gap> src := FreeGroup(6);;
gap> AssignGeneratorVariables(src);;
gap> src := src / [f5*f4*f6*f2*f1*f3];;
gap> AssignGeneratorVariables(src);;
gap> gens := [ f3, f1, f2^-1*f4^-1*f2*f4*f2, f5*f4*f6*f4^-1*f5^-1, f2^-1*f4^-1*f2^-1*f4*f2*f4*f2, f5 ];;
gap> fp := IsomorphismFpGroupByGeneratorsNC(src,gens,"F");;
gap> dst := Image(fp);;
gap> MappedWord(RelatorsOfFpGroup(dst)[1],GeneratorsOfGroup(FreeGroupOfFpGroup(dst)),gens);
f2^-1*f4^-1*f2^-1*f4*f2*f4*f2*f5*f4*f6*f4^-1*f1*f3*f2^-1*f4^-1
```

Expected behaviour
----------------

The relator should evaluate back to a trivial element in src (namely, a conjugate of f5*f4*f6*f2*f1*f3). It seems that the new code miscalculates the relator of the image.

Copy and paste GAP banner (to tell us about your setup)
-----------------------
Latest sources from github:
```
 ┌───────┐   GAP v4.8.1-1789-gd876566 of 2016-08-02 22:42:15 (CEST)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin13.4.0-gcc-default64
 Libs used:  gmp
 Loading the library and packages ...
```

**Comment by laurentbartholdi** [comment]
Hmmm, how does one write blocks of GAP code, without putting backticks on every line?

**Comment by alex-konovalov** [comment]
@laurentbartholdi : three backticks before and after the block:
```
this is code
```

**Comment by alex-konovalov** [comment]
@laurentbartholdi and what happen if you will omit "NC"? I mean, could it be the problem with the input, which NC version does not check?

**Comment by laurentbartholdi** [comment]
No, it changes nothing; the non-NC version calls the NC one:
```
gap> fp := IsomorphismFpGroupByGenerators(src,gens);;
gap> dst := Image(fp);;
gap> MappedWord(RelatorsOfFpGroup(dst)[1],GeneratorsOfGroup(FreeGroupOfFpGroup(dst)),gens);
f2^-1*f4^-1*f2^-1*f4*f2*f4*f2*f5*f4*f6*f4^-1*f1*f3*f2^-1*f4^-1*f2*f4*f2
```

By the way, the `IsomorphismFpGroupByGeneratorsNC` command holds its last argument `nam` in contempt.

**Comment by hulpke** [comment]
This is an easier example

```
src := FreeGroup(3);;
AssignGeneratorVariables(src);;
src := src / [f3*f1];;
SetReducedMultiplication(src);
f1:=src.1;f2:=src.2;f3:=src.3;
gens := [ f1, f2, f2^-1*f3*f2 ];;
fp := IsomorphismFpGroupByGeneratorsNC(src,gens,"F");;
dst := Image(fp);;
m:=MappedWord(RelatorsOfFpGroup(dst)[1],GeneratorsOfGroup(FreeGroupOfFpGroup(dst)),gens);
```

**Comment by hulpke** [comment]
I have fixed this -- the code for IsomorphismFpGroup accidentally used the stored subgroup generators, not the given ones.
Name string is also fixed.

**Comment by hulpke** [comment]
As a fix is in the pipeline I'm going to close this.

**Comment by fingolfin** [comment]
I think it's better to keep this open, until the fix has been merged (coincidentally, you apparently didn't close this anyway :-)

**Comment by laurentbartholdi** [comment]
Thanks to all and @hulpke for the quick fix. Again a beginner's question: how do I get the fix without cloning Alexander H's repo? It's rather annoying because it breaks FR.

**Comment by hulpke** [comment]
@laurentbartholdi 
In what way does FR break? That is something I should fix.
Do you want me to move the fix into another branch instead?

**Comment by laurentbartholdi** [comment]
@hulpke Any way of making the fix available asap is welcome. It breaks GroupHomomorphismByImages from f.p. groups when the source generating set is not standard, and this occurs in lots of places in FR and IMG.

**Comment by hulpke** [comment]
@laurentbartholdi Can you send me an example of such a homomorphism (without the need to load FR)?

**Comment by fingolfin** [comment]
@hulpke I think Laurent is referring to this bug here! He just wants to know how he can get resp. try out your fix... That's how I understand it at least

**Comment by hulpke** [comment]
@fingolfin @laurentbartholdi I understand -- "this" is the fixed bug, not my repo.

To avoid the intermeshing with other code I've moved it into a separate pull request, #91. Basically you would only need to merge this branch to your own working repository.

**Comment by laurentbartholdi** [comment]
Yes, @fingolfin, that was exactly my wish. I did
```
git fetch origin pull/891/head:ahulpkefix
git checkout master
git merge ahulpkefix
```
and now it works like a charm. (note the "891" instead of "91")

**Comment by laurentbartholdi** [comment]
Well... it doesn't work like a charm :(
The test code does indeed succeed, but performance dropped drastically. All the time seems to be spend in the "Merge" function, at
```
Merge( a, b ); at /usr/local/src/gap/lib/sgpres.gi:2418 called from
NEWTC_Coincidence( DATA, f, b ); at /usr/local/src/gap/lib/sgpres.gi:2753 called from
NEWTC_ScanAndFill( DATA, 1, DATA.subgword[w] ); at /usr/local/src/gap/lib/sgpres.gi:2966 called from
NEWTC_DoCosetEnum( freegens, freerels, subgens, false, trace
 ) at /usr/local/src/gap/lib/sgpres.gi:3141 called from
...
```
@hulpke, is there a way of accessing the previous code?

**Comment by laurentbartholdi** [comment]
Here's something that doesn't work anymore, but used to work with the previous code and FGA:
```
src := FreeGroup("f1","f2","f3","g1","g2","g3");;
AssignGeneratorVariables(src);;
src := src / [ f3*f2*f1*g3*g2*g1 ];
AssignGeneratorVariables(src);;
map := GroupHomomorphismByImages(src,src,[ f1, f2, f3, g1, g2, g3 ], [ f1, f2^-1*f3^-1*f2*f3*f2, f2^-1*f3*f2, g1, g2, g3 ]);;
Inverse(map); # waits forever
```

**Comment by hulpke** [comment]
@laurentbartholdi works now.

**Comment by laurentbartholdi** [comment]
Dear @hulpke, can you provide a new pull request that I can test, and tell me at which branch (4.8.0?) I can get the previous GroupHomomorphismByImages code, so as to check everything including for performance?

**Comment by hulpke** [comment]
@laurentbartholdi 
I had this added already to the same pull request (#892 Note that due to some problems I had to redo the PR from the initial attempt 891 earlier) yesterday. That is if you repeat the merge you'll have the fix -- it will merge in the `master' branch. Alternatively, you could apply the patch of 06a79e7bbc8d11d002f762c6b2d7b0ffb90dcac2
at https://github.com/gap-system/gap/pull/892/commits/06a79e7bbc8d11d002f762c6b2d7b0ffb90dcac2
