### ISSUE TITLE
Tutorial incorrect for Read

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#898]
The tutorial for `Read` includes:

```
 You  can  either  give the full absolute path name of the source file or its relative
  path  name  from  the  GAP root directory (the directory containing bin/, doc/, lib/,
  etc.).
```

That second part is a lie -- you can't give a relative path name from the GAP root directory. It would be easy to make GAP look there if we wanted it to, but I imagine we want to look relative to the directory GAP is started from (which we already do).

**Comment by alex-konovalov** [comment]
Yes - it should be either full path or relative from the **current** directory. On Windows, one could call `DirectoryCurrent();` to see what is that, and by default it will be `%HOMEDRIVE%%HOMEPATH%` that is the user home directory. On UNIX, `DirectoryCurrent();` is not very informative, but `Exec("pwd");` will do the job.

**Comment by ChrisJefferson** [comment]
I wonder if DirectoryCurrent() should give the actual directory, instead of `./` (but that’s a separate issue).
