### ISSUE TITLE
Regression in grpperm.tst

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#899]
Supposedly after #878 by @hulpke has been merged, we have a regression in grpperm.tst. As I wrote in a comment to #878, it sometimes displays 

```
########> Diff in /home/hudson/hudson/workspace/GAP-pkg-update-master-quicktes\
t/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/standard/label/graupius/GAP-pkg-update\
-master-snapshot/tst/teststandard/grpperm.tst:223
# Input is:
IsomorphismGroups(gp1,gp2)<>fail;
# Expected output:
true
# But found:
Error, reached the pre-set memory limit
(change it with the -o command line option)
########
```

when all packages are loaded. Also, see the performance plot below.
![grpperm](https://cloud.githubusercontent.com/assets/5751387/18768726/2faf2fc8-811f-11e6-8587-ee96c2e8506e.png) - something is going on here.

**Comment by hulpke** [comment]
The runtime changed because of a new (hard) example. As part of #896 I will move it to the new test file (which anyhow needs more than standard memory, thus memory use is not an extra issue there), so with that change the speed regression should go away again.
