### ISSUE TITLE
Document StableSort and its variants

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#908]
Some time ago, @ChrisJefferson add `StableSort` (in commit 1d345639e557138a5a17bcc883292f847bd20227 with the somewhat unhelpful commit message "Code reformat" ;-). 

As far as I can tell, the library does not use it, so I assume it is intended for endusers. But it is not actually documented!

So I suggest we add some documentation for it. It doesn't have to be long -- one entry for all the new functions, which explains what "stable" means, and otherweise refers the reader to the regular variants, would already be helpful. Also, the regular "Sort" etc. should then perhaps mention that they may not be stable, and refer to the Stable variants in return?

Also, these functions should be mentioned in the 4.9 release notes as a new feature. (Do we have a place to log things like that? Perhaps by just adding a milestone to this issue? @alex-konovalov any thoughts?)

**Comment by alex-konovalov** [comment]
@fingolfin I have added Milestone 4.9.0 - this will ensure that this issue will be revisited before 4.9 and not overlooked. The place to collect entries for release notes for GAP 4.9 also exists - it is at https://github.com/gap-system/gap/wiki/Changes-between-GAP-4.8-and-GAP-4.9

**Comment by ChrisJefferson** [comment]
Something weird must have happened in merging, I definately remember documenting StableSort, but it must have gotten lost!
