### ISSUE TITLE
Add built-in support for reading (and writing?) gzip'ed files

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#916]
Right now, we allow to transparently read .gz files via e.g. `Read()`. This is done by executing a seprate `gzip` binary, and piping data through it. But this only works if gzip is available. So it can be an issue on Windows (see also #910).

It would be nice if we could just integrate support for reading gzip files; while at it, we might even do more than the current slightly hackish support, and offer a GZipInputStream (and perhaps also a GZipOutputStream).

One simple solution is to link against zlib, if available (and if not, fallback to the gzip+pipe trick). This library is widely available, and very easy to use (however, as usual interaction with memory management might be tricky to get right... I wish there was a way in that GAP GC to temporaril "lock" some allocated memory, to guarantee it is not moved... would make interaction with many C libraries that allow specifying custom allocators much easier...).

Another solution would be bundle another `inflate` implementation, so that we can modify it to work with out GC. E.g. tinf, see https://bitbucket.org/jibsen/tinf -- it doesn't allocate _any_ memory. Drawback: it requires the complete input (compressed) and output (decompressed) data to be in memory.

Finally, we could just roll our own (it's not _that_ hard), and / or modiy an existing solution (like tinf) heavily to suite our needs.

**Comment by markuspf** [comment]
I actually started playing with zlib today to address this issue. Not that I got that far yet, but if I have anything worth testing I'll pull-request it.

**Comment by fingolfin** [comment]
Implemented by @ChrisJefferson in PR #2509
