### ISSUE TITLE
GAP tab-completion should be case insensitive

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/gap#919]
I would prefer it if GAP's tab completion was case insensitive. This is even more useful to some users (such as blind ones) where worrying about case is quite annoying.

I am happy to write the patch to do this, the only question is if it should be done at all, and if so if it should be on by default, or configurable. My personal preference would be always on, not configurable, but some people might have another opinion.

One option would be to only do case-insensitive when all characters are lower case.

**Comment by markuspf** [comment]
how about a more general tab completion where one can type bits of the name, i.e.

```
gap> Dir Cur<tab>
```
would yield
```
gap> DirectoryCurrent
```
or better yet
```
gap> DirectoryCurrent(
```

**Comment by ChrisJefferson** [comment]
I'm wondering if the better option would be lift the tab completion function to GAP (leave the optimised version in place), then we can all play around with whatever completion we'd like to try, and see what settles :)

The only issue I have is I have no idea how I would do that for readline, as I don't use it.

**Comment by fingolfin** [comment]
Well, we should also look into refactoring the readline code, too, as the way it is currently hooked up in GAP seems like quite a hack to me...
At the same time, the extended functionality provided by readline is really important to me (e.g. highlighting matching parens, lots of extra key commands)...

Still, perhaps we can achieve all of that in pure GAP code, and get rid of readline again? The julia folks did that, and the result is really cool, like proper multiline support... Sounds like a lot of work, though... And is way beyond this feature request... :-).

As for me, I'd be happy with tab completion being case insensitive; perhaps make it a flag (for now, at least), to please everybody (in general, I am not a fan of such flags, but it's the easiest way out from a "political" point of view).

@markuspf I don't like the automatically added opening parenthesis at all, as I write lots of functional style code, like `List(x, DirectoryCurrent)`. Of course one can now argue whether it is better to force some people to type an extra backspace or others to type an extra openikng parens...  :-)

**Comment by alex-konovalov** [comment]
Optional case-insensitive autocomplete (available only when GAP is compiled with readline support) has been added in #928
