### ISSUE TITLE
SylowSubgroupPermGroup is undocumented and does not terminate if parameter is not prime

### ISSUE THREAD

**Issue by markuspf** [gap-system/gap#926]
Please use the following template to submit an issue
(you may delete lines which are not used). Thank You!
### Observed behaviour

``` gap
gap> SylowSubgroupsPermGroup(SymmetricGroup(12), 4);

```

(No termination)
### Expected behaviour

An error message, or at least documentation that reflects that this function is of the `NC` variety.
### Copy and paste GAP banner (to tell us about your setup)

```
┌───────┐   GAP v4.8.4-21-gf760aef-dirty of 2016-08-19 12:12:51 (BST)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-unknown-dragonfly4.7-gcc-default64
```

**Comment by hulpke** [comment]
Is there a reason for using this (internal) function, instead of the default `SylowSubgroup' operation?

**Comment by markuspf** [comment]
Other than me randomly poking around functions that show up with tab-completion (and trying to see how GAP computes Sylow subgroups) there isn't.

One of the possible fixes (which I am also willing to implement) is to just write 2 sentences of documentation saying "This is an internal function, and it assumes that the parameter `p` is prime".

**Comment by fingolfin** [comment]
Uhm, so should we now document all undocumented functions as being undocumented? I don't quire see the point...

Of course it would be nice if we had namespaces (real ones, not that @ hack we have), then we could hide implementation details and undocumented functions. Alas, we don't right now...

**Comment by ChrisJefferson** [comment]
We could (in cases like this) switch to the ALL_CAPS which (I think) we are supposed to use for undocumented functions? To be honest I tend to just start undocumented functions with an `_`, which is enough to hide them from tab-completing prying eyes.

**Comment by ChrisJefferson** [comment]
Or stop tab completion displaying undocumented functions? (would require some GAPDoc integration possibly)

**Comment by fingolfin** [comment]
We could - but this would affect thousands of variables and functions...

**Comment by fingolfin** [comment]
So a user would not be able to tab complete their own functions ? I don't think that's a good idea...

**Comment by ChrisJefferson** [comment]
@fingolfin : Yes, I was just about to write a reply thinking about user's own functions..

We could in principle capture "global name defined in the library, or by a package", by marking when we start and stop loading the library..

**Comment by hulpke** [comment]
Is the issue maybe that the name is too ``tempting'' -- I'd be happy to rename the function and it would be a small, localized change.

**Comment by alex-konovalov** [comment]
Maybe blue sky thinking, but what displaying documented/undocumented names using different style, when the `ColorPrompt` is turned on?

**Comment by markuspf** [comment]
There is actually also a point in documenting how GAP computes Sylow subgroups (of permutation groups, or other groups). I am not saying we (or Alexander) have to do this right now, but it would certainly be a nice thing to have.

**Comment by hulpke** [comment]
If the permutation group is not solvable, the method is similar to what has been published by Cannon and Holt: Reduce by homomorphisms related to (im)primitivity and use that if $P$ is a $p$-subgroup that is not yet Sylow, then $N_G(P)$ (or C_G(Z(P))) will have a larger $p$-part.

If the group is solvable, the PC method is used. (Incidentally I just found a bad inefficiency there, that will be fixed by
https://github.com/gap-system/gap/pull/896/commits/fc44a2c9e222ff964d79ad6516850175737bbab0

**Comment by fingolfin** [comment]
I think this issue should be closed as invalid.

However, several new issues might be created instead: "Document how GAP computes things" resp. "Document how sylow subgroups are computed";  or "prefix all undocumented functions with XYZ";  or (my favorit :-) "Add proper namespace capabilities to GAP" (this is a big one, but I think it'll get more and more important with each new package; most recently, the conflict between YAGS and digraphs / grape highlighted this).

**Comment by fingolfin** [comment]
I am closing this now as invalid. Feel free to open new issues as suggested above.
