### ISSUE TITLE
Explain usage of filters in 'Group Libraries'-documentation

### ISSUE THREAD

**Issue by ssiccha** [gap-system/gap#930]
In issue #929 a discussion was opened if and how the documentation of functions like `DihedralGroup` should be extended to explain how to use the optional filter argument.

@fingolfin suggested to add brief sentences to the manual entries like this: `To learn more about the meaning of the optional filter argument, read section X.Y`. And/or add explicit examples to each of them.

**Comment by alex-konovalov** [comment]
I've labeled this as "newcomer-friendly" - doing this is a good way to practice pull requests if you haven't yet tried submitting them, and familiarise yourself with GAP documentation. The task is to add the reference to Section "Basic Groups" to each of the 13 mansections in this section and submit the pull request to the appropriate "stable" branch (`stable-4.8` at the time of writing). Documentation for appropriate functions is in the GAP source files, linked to the manual via `Include` elements in https://github.com/gap-system/gap/blob/master/doc/ref/grplib.xml.

You may find useful [this Wiki page](https://github.com/gap-system/gap/wiki/Building-main-GAP-manuals) telling how to build GAP manuals (they will be also built as a part of automated testing of the pull request).

**Comment by ssiccha** [comment]
Thanks! :) I'll try to take care of it tomorrow.
