### ISSUE TITLE
Some global variables exist twice on master branch

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#935]
In PR #579, mos global variables in the kernel were move into a new master struct.

However, some variables were missed, as I just learned the hard way (i.e. by weird behaviour due to a forgoten `TLS(...)` wrapper :-). The three I stumbled upon are `ErrorLVars`, `ErrorLVars0` and `ErrorLLevel`. Perhaps that's all, but I think it would be a good idea to double check all members of the `GlobalState` struct. This can be semi-automated with a script, I think: First, extract the variables names from `GlobalState` (with some regex). Then for each variable name, do something like 
```
git grep UserHasQUIT | fgrep -v "TLS(UserHasQUIT)" | fgrep -v extern | fgrep "TL:"
```
Which should yield a commented out definition line. If it doesn't, something is wrong. (Of course, this can also be scripted. And of course it is not 100% fool proof, but it *does* catch the three cases I mentioned above).

**Comment by markuspf** [comment]
I shall do this later tonight.

**Comment by fingolfin** [comment]
This is mostly fixed now. However, gap.h still contains this:
```
extern Obj ErrorLVars;
extern Obj ErrorLVars0;
```
So one could still accidentally forget a `TLS(...)`. But at least now we'd get a linker error which makes it less hard to debug :-).

Of course that is trivial to fix, but I wonder whether it is the only instance?

**Comment by markuspf** [comment]
I'll run my grepping tool again to see...
