### ISSUE TITLE
IsMatrix and its documentation disagree 

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/gap#951]
### Observed behaviour

    gap> IsMatrix([[1,2,3], [1,2]]);
    true

### Expected behaviour
I expect nothing, but the documentation of `IsMatrix` says: 

> A matrix  is  a list of lists of equal length whose entries lie in a common ring.

So the documentation and the behaviour disagree. I have seen this [GAP forum](http://mail.gap-system.org/pipermail/forum/2010/002991.html) reply by @alex-konovalov, which says that the behaviour of `IsMatrix` is correct (if not really what I'd expect), but in this case the documentation is still wrong some six years later.

### Copy and paste GAP banner (to tell us about your setup)
This is in the master branch, but also in GAP 4.8.something.

**Comment by markuspf** [comment]
The behaviour is intended, but not "correct". This is basically because it's expensive or impossible to decide whether a list of lists is a matrix.

**Comment by markuspf** [comment]
Also this is in scope of the project that @fingolfin started a week ago about finally sorting out `MatrixObj`.

**Comment by james-d-mitchell** [comment]
I agree it falls into the scope of the `MatrixObj` issue, but I think the documentation is still misleading. `IsMatrix` returns `true` for arguments that don't satisfy the definition of a matrix as given in the documentation of `IsMatrix`. 

Whether it's too expensive or impossible to decide if a list of lists is a matrix or not is immaterial, this is simply about having clear documentation. I think the documentation for `IsMatrix` should clearly state when it returns `true` and when it returns `false`, if possible.
