### ISSUE TITLE
ConjugacyClassesSubgroups is twice faster with no packages loaded in one particular example

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#962]
The following example (A5:S5) takes half time without packages on current master (6 seconds without packages, 13 seconds with packages):

````
G := Group([ (6,7,8,9,10), (8,9,10), (1,2)(6,7), (1,2,3,4,5)(6,7,8,9,10) ]);;
ConjugacyClassesSubgroups(G);;
````
I would expect any computation be faster using packages than the other way around.

**Comment by fingolfin** [comment]
The actual relevant function being called is `LatticeSubgroups`. And it does something different depending on whether `tomlib` is loaded or not: It modifies the `cefastersize` value.

Perhaps @hulpke can shed some light on this?

**Comment by hulpke** [comment]
The `cefastersize` is a limit up to which order cyclic extension is faster for a fitting free group than the new algorithm (my ISSAC2013 paper). The values are basically heuristics, the value of 1 if `tomlib` is available indicating that we can get the subgroups of simple groups from there.

It is unsurprising that one can construct examples in which the heuristic fails, but for the given times I don't see this as an issue.
