### ISSUE TITLE
kernel: get rid of `StringAndFilter` 

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#977]
I think we can get rid of `StringAndFilter` -- it is a left-over, but some recent refactoring (by @markuspf ?) removed the only place using it.

**Comment by markuspf** [comment]
Max Horn writes:

> I think we can get rid of StringAndFilter -- it is a left-over, but some recent refactoring (by @markuspf ?) removed the only place using it.

I agree, but I think the credit is due for @ChrisJefferson though ;)
