### ISSUE TITLE
Recursion trap in MaximalSubgroupClassReps in grpperm.tst

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#984]
This currently occurs only on one of the two Linux slaves, and only when all packages are loaded. I have seen it twice by now in two consecutive runs of `make testandard`:
```
########> Diff in /data/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/64build\
/GAPTARGET/standard/label/kovacs/GAP-master-snapshot/tst/teststandard/grpperm.\
tst:80
# Input is:
Length(ConjugacyClassesSubgroups(g));
# Expected output:
2048
# But found:
Error, List Element: <list>[32] must have an assigned value
########
```

**Comment by hulpke** [comment]
This is a subgroup lattice computation of M_{11}\wr 2 and quite involved code that exercises homomorphisms, complements, normalizers, Sylow subgroups, and much more, both in permutation representation and pc representations.

Can you reproduce the error outside a test file (so one can see at least which line triggers the error) -- I have been unable to do so?

**Comment by alex-konovalov** [comment]
This problem has gone after merges happening on Dec 8th. There are now another troubles however (master branch, both with and without packages):
```
########> Diff in /data/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/64build\
/GAPTARGET/standard/label/kovacs/GAP-master-snapshot/tst/teststandard/grpperm.\
tst:90
# Input is:
m:=MaximalSubgroupClassReps(w);;
# Expected output:
# But found:
Error, recursion depth trap (5000)

########
########> Diff in /data/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/64build\
/GAPTARGET/standard/label/kovacs/GAP-master-snapshot/tst/teststandard/grpperm.\
tst:91
# Input is:
Collected(List(m,x->Index(w,x)));
# Expected output:
[ [ 2, 3 ], [ 5, 1 ], [ 6, 1 ], [ 10, 1 ], [ 16, 1 ], [ 3125, 1 ], 
  [ 7776, 1 ], [ 100000, 1 ] ]
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `ListOp' on 2 arguments
########
```

**Comment by hulpke** [comment]
@alex-konovalov 
What is happening is that code checking for tables of marks and code checking for maximal subgroups refer to each other. I have a fix for this, which I will commit soon.

What it (unfortunately) implies is that I need to move the maximal subgroups routine for symmetric/alternating out of the primitive groups library (where it anyhow does not belong if it simply is a data package) and into the main library. So presumably this will imply a change in the primitive groups package as well. Do you want me to submit a PR for that package?

This change will also make it easier to include this use of a data library in #986 

The second bug is just a consequence of the first.

**Comment by alex-konovalov** [comment]
@hulpke thanks for the explanation and the incoming fix. Yes, please submit a PR to https://github.com/gap-packages/primgrp. I've also just invited you to that package so that you can also have write access.
