### ISSUE TITLE
Nice Monomorphism for Ree groups takes a looooooong time

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/gap#987]
Happens on current master.

It takes a really long time (almost 20 minutes on my machine) to create a nice monomorphism for the simple group ````Ree(27)````. I only found this out, because I wanted to increase code coverage for ````StructureDescription```` and this is the smallest group for one of the lines. This is what I observed: 
````
 ┌───────┐   GAP v4.8.6-925-g8efd681 of 2016-12-06 08:13:49 (CET)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 3.0, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.1, AutPGrp 1.6, 
             Browse 1.8.6, CRISP 1.4.4, Cryst 4.1.12, CrystCat 1.1.6, 
             CTblLib 1.2.2, FactInt 1.5.3, FGA 1.3.1, GAPDoc 1.5.1, IO 4.4.6, 
             IRREDSOL 1.3.1, LAGUNA 3.7.0, Polenta 1.3.7, Polycyclic 2.11, 
             RadiRoot 2.7, ResClasses 4.5.0, Sophus 1.23, SpinSym 1.5, 
             TomLib 1.2.6, Utils 0.43
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> StructureDescription(Ree(27)); time; 
"Ree(27)"
1137264
````
Using ````TraceMethods```` I confirmed that the nice monomorphism method is the first that it tries.
Now the interesting thing is that the relevant lines in ````StructureDescription```` would take almost no time (after merging #985), but the nice monomorphism method takes precedent (which it should). I even tried to install a new method for simple finite groups, but of course its rank is still not high enough (nor should it be) to precede the nice monomorphism method. 

So I guess it should be fixed with the nice monomorphism, if at all?

I have not experienced this with the other simple group constructions of GAP, but I have not gone too deep into this topic.

**Comment by hulpke** [comment]
I think this is a fundamental misunderstanding of what you want the computer to do (and what `StrucrtureDescription` could do.
You *know* that the group is Ree(27) and you feed it in as if it is a random matrix group. This will be slow.
Why should one expect to call `StructureDescription` on subgroups of GL(7_27) of order 10^10?
