### ISSUE TITLE
Manual example for MaximalNormalSubgroups from grp.gd fails

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#996]
This presently occurs in nightly tests of the master branch 
```
########> Diff in [ "./../../lib/grp.gd", 1772, 1778 ]
# Input is:
List(MaximalNormalSubgroups(f/[x^2, y^2]), GeneratorsOfGroup);
# Expected output:
[ [ x, y*x*y^-1 ], [ y, x*y*x^-1 ], [ y*x^-1 ] ]
# But found:
#I  Coset table calculation failed -- trying with bigger table limit
#I  Coset table calculation failed -- trying with bigger table limit
#I  Coset table calculation failed -- trying with bigger table limit
#I  Coset table calculation failed -- trying with bigger table limit
Error, reached the pre-set memory limit
(change it with the -o command line option)
########
```

The following changes are new comparatively to the test from yesterday:
* Add IsAbelian filters to IsSolvableGroup and DerivedSeries
* ReadPackage error 
* ENHANCE: Remove multi-declaration warning if both declarations are equal 
* ENHANCE: CharacteristicSubgroupsLib to CharacteristicSubgroups

**Comment by hungaborhorvath** [comment]
This is my mess, sorry. The problem was with setting assertion levels to 2 instead of 3 as @fingolfin suggested. Fixed in #1007
