### ISSUE TITLE
Add `License` field to PackageInfo.g format

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#997]
(I thought I'd seen this discussed before, but didn't see an issue, so I am opening a new one. If there is already an issue, feel free to close this one with a pointer to the existing issue. Thanks)

We should add a `License` field to GAP packages. It would initially be optional, but on the long run mandatory. Several variants for the content of that file come to mind:

1. A (package relative) path to a license file, e.g.
```
   License := "COPYING",   # point to our copy of the GPL
```
2. The name of the license, say in the form of an SPDX license identifier.
3. There could actually be two fields: a `License` field with the license name (SPDX license expression), and a `LicenseFile` field with file path.

UPDATE: for now we have settled on variant 2, and here is a "roadmap" suggested by @alex-konovalov

- [x] update PackageInfo.g in Example package (see https://github.com/gap-packages/example/pull/22)
- [x] update PackageMaker (see https://github.com/gap-system/PackageMaker/commit/d8b22bf4661255984ca716485270914006ca5470)
- [x] update `ValidatePackageInfo` (see https://github.com/gap-system/gap/pull/3286)
- [x] update website scripts that extract details from PackageInfo.g for package overview pages -> see https://github.com/gap-system/gap-distribution/pull/81
- [x] <s>optionally: update GitHubPagesForGAP to render info on License, if present</s> (transferred to <https://github.com/gap-system/GitHubPagesForGAP/issues/17>)
- [x] Mention in the announcement of the beta release (will be taken care off in the regular release notes process)

**Comment by alex-konovalov** [comment]
Shall we try this for GAP 4.9.0? Then packages updating for GAP 4.9.1 would be able to make use of this.

**Comment by fingolfin** [comment]
A pull request for this would be welcome at any time.

**Comment by alex-konovalov** [comment]
More detailed plan:
- [ ] Adjust `ValidatePackageInfo` to produce a warning
- [ ] Update PackageInfo.g template in the Example package
- [ ] Update scripts in gap-distribution, if needed
- [ ] Changes in https://github.com/fingolfin/PackageMaker
- [ ] Mention in the announcement of the beta release

**Comment by fingolfin** [comment]
So, which of my several proposals do you want to implement?

For your plan: Perhaps also notify package authors to add the field, and which values are permissible? This notification could be sent as soon as the master branch implements this, no need to wait for 4.9 (in particular since adding this field will not break compatibility with old GAP versions).
Also, If the license name is to be specified, then we should also state explicitly which value we want for "GPL2 or later", the license most package are using (I think).

**Comment by wilfwilson** [comment]
I support the idea of adding these field(s).

**Comment by fingolfin** [comment]
While this would be nice to have, I don't think it's mandatory for 4.9.0, hence I just removed the milestone. Perhaps we can try to get this into 4.10.0.

**Comment by alex-konovalov** [comment]
I agree (perhaps even some 4.9.X will be fine, as it only adds new fields). One should do this:
- [ ] update PackageInfo.g in Example package
- [ ] update PackageMaker
- [ ] update ValidatePackageInfo
- [ ] update website scripts that extract details from PackageInfo.g for package overview pages.

**Comment by fingolfin** [comment]
I really want to get this done in GAP 4.11. I suggest that we use approach 2., a License field using an SPDX identifier (see <https://spdx.org>). We can then still add a `LicenseFile` later on, should we really want to, but  don't think it's that useful, while SPDX allows for machine processing and hence can be used to generate info on the website, collect statistics about licenses used in packages, etc.

**Comment by alex-konovalov** [comment]
@fingolfin this can be closed - all boxes now ticked (one of them transferred to https://github.com/gap-system/GitHubPagesForGAP/issues/17)
