### ISSUE TITLE
RewindStream fails for compressed files

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap#999]
GAP supports reading from gzip compressed files transparently. I.e. GAP code need not be aware of this, it just happens "automatically".

However, `RewindStream` does not work in that case -- not surprising, given that we implement this by piping the data through a separate gunzip process.

One way to fix this would be to implement native gzip decompression (see issue #916). But of course it is probably much easier to fix just this special case. To do that, we probably would have to modify `SEEK_POSITION_FILE` or `SyFseek` in the kernel somehow.

By the way, this issue results in GAP not support gzip compressed `manual.six` files, which is why Debian includes a workaround fix which replaces a `RewindStream` call in the help system by code which closes the file and reopens it. See also this issue on our old private tracker: http://tracker.gap-system.org/issues/466

**Comment by ChrisJefferson** [comment]
At the moment we don't store the filename a stream is based on, but we could certainly store that, and then try to reopen the file later.

**Comment by fingolfin** [comment]
@ChrisJefferson I wonder if this is now fixed with the use of zlib?

**Comment by ChrisJefferson** [comment]
It is, works fine in master!

**Comment by fingolfin** [comment]
Great, so this was resolved by PR #2509 -- and that even adds a check for seeking, in commit 40d3c8758059285183608eb15815f6e638f0503f. So we can close this.
